/*
 Highcharts JS v8.2.2 (2020-11-23)

 Accessibility module

 (c) 2010-2019 Highsoft AS
 Author: Oystein Moseng

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/accessibility",["highcharts"],function(p){a(p);a.Highcharts=p;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function p(a,f,l,n){a.hasOwnProperty(f)||(a[f]=n.apply(null,l))}a=a?a._modules:{};p(a,"Accessibility/Utils/HTMLUtilities.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,f){function r(a){return a.replace(/&/g,
"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;").replace(/\//g,"&#x2F;")}var n=a.doc,m=a.win,k=f.merge;return{addClass:function(a,k){a.classList?a.classList.add(k):0>a.className.indexOf(k)&&(a.className+=k)},escapeStringForHTML:r,getElement:function(a){return n.getElementById(a)},getFakeMouseEvent:function(a){if("function"===typeof m.MouseEvent)return new m.MouseEvent(a);if(n.createEvent){var g=n.createEvent("MouseEvent");if(g.initMouseEvent)return g.initMouseEvent(a,
!0,!0,m,"click"===a?1:0,0,0,0,0,!1,!1,!1,!1,0,null),g}return{type:a}},removeElement:function(a){a&&a.parentNode&&a.parentNode.removeChild(a)},reverseChildNodes:function(a){for(var k=a.childNodes.length;k--;)a.appendChild(a.childNodes[k])},setElAttrs:function(a,k){Object.keys(k).forEach(function(e){var d=k[e];null===d?a.removeAttribute(e):(d=r(""+d),a.setAttribute(e,d))})},stripHTMLTagsFromString:function(a){return"string"===typeof a?a.replace(/<\/?[^>]+(>|$)/g,""):a},visuallyHideElement:function(a){k(!0,
a.style,{position:"absolute",width:"1px",height:"1px",overflow:"hidden",whiteSpace:"nowrap",clip:"rect(1px, 1px, 1px, 1px)",marginTop:"-3px","-ms-filter":"progid:DXImageTransform.Microsoft.Alpha(Opacity=1)",filter:"alpha(opacity=1)",opacity:"0.01"})}}});p(a,"Accessibility/Utils/ChartUtilities.js",[a["Accessibility/Utils/HTMLUtilities.js"],a["Core/Utilities.js"]],function(a,f){function r(d){var c,b;if(null===(c=d.points)||void 0===c?0:c.length)return d=q(d.points,function(b){return!!b.graphic}),null===
(b=null===d||void 0===d?void 0:d.graphic)||void 0===b?void 0:b.element}function n(d){var c=r(d);return c&&c.parentNode||d.graph&&d.graph.element||d.group&&d.group.element}function m(d,c){c.setAttribute("aria-hidden",!1);c!==d.renderTo&&c.parentNode&&(Array.prototype.forEach.call(c.parentNode.childNodes,function(b){b.hasAttribute("aria-hidden")||b.setAttribute("aria-hidden",!0)}),m(d,c.parentNode))}var k=a.stripHTMLTagsFromString,g=f.defined,q=f.find,e=f.fireEvent;return{getChartTitle:function(d){return k(d.options.title.text||
d.langFormat("accessibility.defaultChartTitle",{chart:d}))},getAxisDescription:function(d){return k(d&&(d.userOptions&&d.userOptions.accessibility&&d.userOptions.accessibility.description||d.axisTitle&&d.axisTitle.textStr||d.options.id||d.categories&&"categories"||d.dateTime&&"Time"||"values"))},getPointFromXY:function(d,c,b){for(var h=d.length,t;h--;)if(t=q(d[h].points||[],function(u){return u.x===c&&u.y===b}))return t},getSeriesFirstPointElement:r,getSeriesFromName:function(d,c){return c?(d.series||
[]).filter(function(b){return b.name===c}):d.series},getSeriesA11yElement:n,unhideChartElementFromAT:m,hideSeriesFromAT:function(d){(d=n(d))&&d.setAttribute("aria-hidden",!0)},scrollToPoint:function(d){var c=d.series.xAxis,b=d.series.yAxis,h=(null===c||void 0===c?0:c.scrollbar)?c:b;if((c=null===h||void 0===h?void 0:h.scrollbar)&&g(c.to)&&g(c.from)){b=c.to-c.from;if(g(h.dataMin)&&g(h.dataMax)){var t=h.toPixels(h.dataMin),u=h.toPixels(h.dataMax);d=(h.toPixels(d["xAxis"===h.coll?"x":"y"]||0)-t)/(u-t)}else d=
0;c.updatePosition(d-b/2,d+b/2);e(c,"changed",{from:c.from,to:c.to,trigger:"scrollbar",DOMEvent:null})}}}});p(a,"Accessibility/KeyboardNavigationHandler.js",[a["Core/Utilities.js"]],function(a){function f(a,f){this.chart=a;this.keyCodeMap=f.keyCodeMap||[];this.validate=f.validate;this.init=f.init;this.terminate=f.terminate;this.response={success:1,prev:2,next:3,noHandler:4,fail:5}}var r=a.find;f.prototype={run:function(a){var f=a.which||a.keyCode,k=this.response.noHandler,g=r(this.keyCodeMap,function(a){return-1<
a[0].indexOf(f)});g?k=g[1].call(this,f,a):9===f&&(k=this.response[a.shiftKey?"prev":"next"]);return k}};return f});p(a,"Accessibility/Utils/DOMElementProvider.js",[a["Core/Globals.js"],a["Accessibility/Utils/HTMLUtilities.js"],a["Core/Utilities.js"]],function(a,f,l){var r=a.doc,m=f.removeElement;a=l.extend;f=function(){this.elements=[]};a(f.prototype,{createElement:function(){var a=r.createElement.apply(r,arguments);this.elements.push(a);return a},destroyCreatedElements:function(){this.elements.forEach(function(a){m(a)});
this.elements=[]}});return f});p(a,"Accessibility/Utils/EventProvider.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,f){var r=f.addEvent;f=f.extend;var n=function(){this.eventRemovers=[]};f(n.prototype,{addEvent:function(){var f=r.apply(a,arguments);this.eventRemovers.push(f);return f},removeAddedEvents:function(){this.eventRemovers.forEach(function(a){a()});this.eventRemovers=[]}});return n});p(a,"Accessibility/AccessibilityComponent.js",[a["Accessibility/Utils/ChartUtilities.js"],
a["Accessibility/Utils/DOMElementProvider.js"],a["Accessibility/Utils/EventProvider.js"],a["Core/Globals.js"],a["Accessibility/Utils/HTMLUtilities.js"],a["Core/Utilities.js"]],function(a,f,l,n,m,k){function g(){}var q=a.unhideChartElementFromAT,e=n.doc,d=n.win,c=m.removeElement,b=m.getFakeMouseEvent;a=k.extend;var h=k.fireEvent,t=k.merge;g.prototype={initBase:function(b){this.chart=b;this.eventProvider=new l;this.domElementProvider=new f;this.keyCodes={left:37,right:39,up:38,down:40,enter:13,space:32,
esc:27,tab:9}},addEvent:function(){return this.eventProvider.addEvent.apply(this.eventProvider,arguments)},createElement:function(){return this.domElementProvider.createElement.apply(this.domElementProvider,arguments)},fireEventOnWrappedOrUnwrappedElement:function(b,c){var u=c.type;e.createEvent&&(b.dispatchEvent||b.fireEvent)?b.dispatchEvent?b.dispatchEvent(c):b.fireEvent(u,c):h(b,u,c)},fakeClickEvent:function(c){if(c){var u=b("click");this.fireEventOnWrappedOrUnwrappedElement(c,u)}},addProxyGroup:function(b){this.createOrUpdateProxyContainer();
var c=this.createElement("div");Object.keys(b||{}).forEach(function(u){null!==b[u]&&c.setAttribute(u,b[u])});this.chart.a11yProxyContainer.appendChild(c);return c},createOrUpdateProxyContainer:function(){var b=this.chart,c=b.renderer.box;b.a11yProxyContainer=b.a11yProxyContainer||this.createProxyContainerElement();c.nextSibling!==b.a11yProxyContainer&&b.container.insertBefore(b.a11yProxyContainer,c.nextSibling)},createProxyContainerElement:function(){var b=e.createElement("div");b.className="highcharts-a11y-proxy-container";
return b},createProxyButton:function(b,c,a,h,d){var u=b.element,e=this.createElement("button"),x=t({"aria-label":u.getAttribute("aria-label")},a);Object.keys(x).forEach(function(b){null!==x[b]&&e.setAttribute(b,x[b])});e.className="highcharts-a11y-proxy-button";d&&this.addEvent(e,"click",d);this.setProxyButtonStyle(e);this.updateProxyButtonPosition(e,h||b);this.proxyMouseEventsForButton(u,e);c.appendChild(e);x["aria-hidden"]||q(this.chart,e);return e},getElementPosition:function(b){var c=b.element;
return(b=this.chart.renderTo)&&c&&c.getBoundingClientRect?(c=c.getBoundingClientRect(),b=b.getBoundingClientRect(),{x:c.left-b.left,y:c.top-b.top,width:c.right-c.left,height:c.bottom-c.top}):{x:0,y:0,width:1,height:1}},setProxyButtonStyle:function(b){t(!0,b.style,{"border-width":0,"background-color":"transparent",cursor:"pointer",outline:"none",opacity:.001,filter:"alpha(opacity=1)","-ms-filter":"progid:DXImageTransform.Microsoft.Alpha(Opacity=1)",zIndex:999,overflow:"hidden",padding:0,margin:0,display:"block",
position:"absolute"})},updateProxyButtonPosition:function(b,c){c=this.getElementPosition(c);t(!0,b.style,{width:(c.width||1)+"px",height:(c.height||1)+"px",left:(c.x||0)+"px",top:(c.y||0)+"px"})},proxyMouseEventsForButton:function(b,c){var a=this;"click touchstart touchend touchcancel touchmove mouseover mouseenter mouseleave mouseout".split(" ").forEach(function(h){var d=0===h.indexOf("touch");a.addEvent(c,h,function(c){var h=d?a.cloneTouchEvent(c):a.cloneMouseEvent(c);b&&a.fireEventOnWrappedOrUnwrappedElement(b,
h);c.stopPropagation();c.preventDefault()},{passive:!1})})},cloneMouseEvent:function(c){if("function"===typeof d.MouseEvent)return new d.MouseEvent(c.type,c);if(e.createEvent){var a=e.createEvent("MouseEvent");if(a.initMouseEvent)return a.initMouseEvent(c.type,c.bubbles,c.cancelable,c.view||d,c.detail,c.screenX,c.screenY,c.clientX,c.clientY,c.ctrlKey,c.altKey,c.shiftKey,c.metaKey,c.button,c.relatedTarget),a}return b(c.type)},cloneTouchEvent:function(b){var c=function(b){for(var c=[],a=0;a<b.length;++a){var h=
b.item(a);h&&c.push(h)}return c};if("function"===typeof d.TouchEvent)return c=new d.TouchEvent(b.type,{touches:c(b.touches),targetTouches:c(b.targetTouches),changedTouches:c(b.changedTouches),ctrlKey:b.ctrlKey,shiftKey:b.shiftKey,altKey:b.altKey,metaKey:b.metaKey,bubbles:b.bubbles,cancelable:b.cancelable,composed:b.composed,detail:b.detail,view:b.view}),b.defaultPrevented&&c.preventDefault(),c;c=this.cloneMouseEvent(b);c.touches=b.touches;c.changedTouches=b.changedTouches;c.targetTouches=b.targetTouches;
return c},destroyBase:function(){c(this.chart.a11yProxyContainer);this.domElementProvider.destroyCreatedElements();this.eventProvider.removeAddedEvents()}};a(g.prototype,{init:function(){},getKeyboardNavigation:function(){},onChartUpdate:function(){},onChartRender:function(){},destroy:function(){}});return g});p(a,"Accessibility/KeyboardNavigation.js",[a["Core/Globals.js"],a["Core/Utilities.js"],a["Accessibility/Utils/HTMLUtilities.js"],a["Accessibility/Utils/EventProvider.js"]],function(a,f,l,n){function r(c,
b){this.init(c,b)}var k=a.doc,g=a.win,q=f.addEvent,e=f.fireEvent,d=l.getElement;q(k,"keydown",function(c){27===(c.which||c.keyCode)&&a.charts&&a.charts.forEach(function(b){b&&b.dismissPopupContent&&b.dismissPopupContent()})});a.Chart.prototype.dismissPopupContent=function(){var c=this;e(this,"dismissPopupContent",{},function(){c.tooltip&&c.tooltip.hide(0);c.hideExportMenu()})};r.prototype={init:function(c,b){var a=this,d=this.eventProvider=new n;this.chart=c;this.components=b;this.modules=[];this.currentModuleIx=
0;this.update();d.addEvent(this.tabindexContainer,"keydown",function(b){return a.onKeydown(b)});d.addEvent(this.tabindexContainer,"focus",function(b){return a.onFocus(b)});["mouseup","touchend"].forEach(function(b){return d.addEvent(k,b,function(){return a.onMouseUp()})});["mousedown","touchstart"].forEach(function(b){return d.addEvent(c.renderTo,b,function(){a.isClickingChart=!0})});d.addEvent(c.renderTo,"mouseover",function(){a.pointerIsOverChart=!0});d.addEvent(c.renderTo,"mouseout",function(){a.pointerIsOverChart=
!1});this.modules.length&&this.modules[0].init(1)},update:function(c){var b=this.chart.options.accessibility;b=b&&b.keyboardNavigation;var a=this.components;this.updateContainerTabindex();b&&b.enabled&&c&&c.length?(this.modules=c.reduce(function(b,c){c=a[c].getKeyboardNavigation();return b.concat(c)},[]),this.updateExitAnchor()):(this.modules=[],this.currentModuleIx=0,this.removeExitAnchor())},onFocus:function(c){var b,a=this.chart;c=c.relatedTarget&&a.container.contains(c.relatedTarget);this.isClickingChart||
c||(null===(b=this.modules[0])||void 0===b?void 0:b.init(1))},onMouseUp:function(){delete this.isClickingChart;if(!this.keyboardReset&&!this.pointerIsOverChart){var c=this.chart,b=this.modules&&this.modules[this.currentModuleIx||0];b&&b.terminate&&b.terminate();c.focusElement&&c.focusElement.removeFocusBorder();this.currentModuleIx=0;this.keyboardReset=!0}},onKeydown:function(c){c=c||g.event;var b,a=this.modules&&this.modules.length&&this.modules[this.currentModuleIx];this.keyboardReset=!1;if(a){var d=
a.run(c);d===a.response.success?b=!0:d===a.response.prev?b=this.prev():d===a.response.next&&(b=this.next());b&&(c.preventDefault(),c.stopPropagation())}},prev:function(){return this.move(-1)},next:function(){return this.move(1)},move:function(c){var b=this.modules&&this.modules[this.currentModuleIx];b&&b.terminate&&b.terminate(c);this.chart.focusElement&&this.chart.focusElement.removeFocusBorder();this.currentModuleIx+=c;if(b=this.modules&&this.modules[this.currentModuleIx]){if(b.validate&&!b.validate())return this.move(c);
if(b.init)return b.init(c),!0}this.currentModuleIx=0;0<c?(this.exiting=!0,this.exitAnchor.focus()):this.tabindexContainer.focus();return!1},updateExitAnchor:function(){var c=d("highcharts-end-of-chart-marker-"+this.chart.index);this.removeExitAnchor();c?(this.makeElementAnExitAnchor(c),this.exitAnchor=c):this.createExitAnchor()},updateContainerTabindex:function(){var c=this.chart.options.accessibility;c=c&&c.keyboardNavigation;c=!(c&&!1===c.enabled);var b=this.chart,a=b.container;b.renderTo.hasAttribute("tabindex")&&
(a.removeAttribute("tabindex"),a=b.renderTo);this.tabindexContainer=a;var d=a.getAttribute("tabindex");c&&!d?a.setAttribute("tabindex","0"):c||b.container.removeAttribute("tabindex")},makeElementAnExitAnchor:function(c){var b=this.tabindexContainer.getAttribute("tabindex")||0;c.setAttribute("class","highcharts-exit-anchor");c.setAttribute("tabindex",b);c.setAttribute("aria-hidden",!1);this.addExitAnchorEventsToEl(c)},createExitAnchor:function(){var c=this.chart,b=this.exitAnchor=k.createElement("div");
c.renderTo.appendChild(b);this.makeElementAnExitAnchor(b)},removeExitAnchor:function(){this.exitAnchor&&this.exitAnchor.parentNode&&(this.exitAnchor.parentNode.removeChild(this.exitAnchor),delete this.exitAnchor)},addExitAnchorEventsToEl:function(c){var b=this.chart,a=this;this.eventProvider.addEvent(c,"focus",function(c){c=c||g.event;c.relatedTarget&&b.container.contains(c.relatedTarget)||a.exiting?a.exiting=!1:(a.tabindexContainer.focus(),c.preventDefault(),a.modules&&a.modules.length&&(a.currentModuleIx=
a.modules.length-1,(c=a.modules[a.currentModuleIx])&&c.validate&&!c.validate()?a.prev():c&&c.init(-1)))})},destroy:function(){this.removeExitAnchor();this.eventProvider.removeAddedEvents();this.chart.container.removeAttribute("tabindex")}};return r});p(a,"Accessibility/Components/LegendComponent.js",[a["Core/Globals.js"],a["Core/Legend.js"],a["Core/Utilities.js"],a["Accessibility/AccessibilityComponent.js"],a["Accessibility/KeyboardNavigationHandler.js"],a["Accessibility/Utils/HTMLUtilities.js"]],
function(a,f,l,n,m,k){function g(b){var c=b.legend&&b.legend.allItems,a=b.options.legend.accessibility||{};return!(!c||!c.length||b.colorAxis&&b.colorAxis.length||!1===a.enabled)}var q=l.addEvent,e=l.extend,d=l.find,c=l.fireEvent,b=k.stripHTMLTagsFromString,h=k.removeElement;a.Chart.prototype.highlightLegendItem=function(b){var a=this.legend.allItems,d=this.highlightedLegendItemIx;if(a[b]){a[d]&&c(a[d].legendGroup.element,"mouseout");d=this.legend;var h=d.allItems[b].pageIx,t=d.currentPage;"undefined"!==
typeof h&&h+1!==t&&d.scroll(1+h-t);this.setFocusToElement(a[b].legendItem,a[b].a11yProxyElement);c(a[b].legendGroup.element,"mouseover");return!0}return!1};q(f,"afterColorizeItem",function(b){var c=b.item;this.chart.options.accessibility.enabled&&c&&c.a11yProxyElement&&c.a11yProxyElement.setAttribute("aria-pressed",b.visible?"false":"true")});a=function(){};a.prototype=new n;e(a.prototype,{init:function(){var b=this;this.proxyElementsList=[];this.recreateProxies();this.addEvent(f,"afterScroll",function(){this.chart===
b.chart&&(b.updateProxiesPositions(),b.updateLegendItemProxyVisibility(),this.chart.highlightLegendItem(b.highlightedLegendItemIx))});this.addEvent(f,"afterPositionItem",function(c){this.chart===b.chart&&this.chart.renderer&&b.updateProxyPositionForItem(c.item)})},updateLegendItemProxyVisibility:function(){var b=this.chart.legend,c=b.currentPage||1,a=b.clipHeight||0;(b.allItems||[]).forEach(function(d){var h=d.pageIx||0,e=d._legendItemPos?d._legendItemPos[1]:0,t=d.legendItem?Math.round(d.legendItem.getBBox().height):
0;h=e+t-b.pages[h]>a||h!==c-1;d.a11yProxyElement&&(d.a11yProxyElement.style.visibility=h?"hidden":"visible")})},onChartRender:function(){g(this.chart)?this.updateProxiesPositions():this.removeProxies()},updateProxiesPositions:function(){for(var b=0,c=this.proxyElementsList;b<c.length;b++){var a=c[b];this.updateProxyButtonPosition(a.element,a.posElement)}},updateProxyPositionForItem:function(b){var c=d(this.proxyElementsList,function(c){return c.item===b});c&&this.updateProxyButtonPosition(c.element,
c.posElement)},recreateProxies:function(){this.removeProxies();g(this.chart)&&(this.addLegendProxyGroup(),this.proxyLegendItems(),this.updateLegendItemProxyVisibility())},removeProxies:function(){h(this.legendProxyGroup);this.proxyElementsList=[]},addLegendProxyGroup:function(){var b=this.chart.options.accessibility,c=this.chart.langFormat("accessibility.legend.legendLabel",{});this.legendProxyGroup=this.addProxyGroup({"aria-label":c,role:"all"===b.landmarkVerbosity?"region":null})},proxyLegendItems:function(){var b=
this;(this.chart.legend&&this.chart.legend.allItems||[]).forEach(function(c){c.legendItem&&c.legendItem.element&&b.proxyLegendItem(c)})},proxyLegendItem:function(c){if(c.legendItem&&c.legendGroup){var a=this.chart.langFormat("accessibility.legend.legendItem",{chart:this.chart,itemName:b(c.name)}),d=c.legendGroup.div?c.legendItem:c.legendGroup;c.a11yProxyElement=this.createProxyButton(c.legendItem,this.legendProxyGroup,{tabindex:-1,"aria-pressed":!c.visible,"aria-label":a},d);this.proxyElementsList.push({item:c,
element:c.a11yProxyElement,posElement:d})}},getKeyboardNavigation:function(){var b=this.keyCodes,c=this;return new m(this.chart,{keyCodeMap:[[[b.left,b.right,b.up,b.down],function(b){return c.onKbdArrowKey(this,b)}],[[b.enter,b.space],function(){return c.onKbdClick(this)}]],validate:function(){return c.shouldHaveLegendNavigation()},init:function(b){return c.onKbdNavigationInit(b)}})},onKbdArrowKey:function(b,c){var a=this.keyCodes,d=b.response,h=this.chart,e=h.options.accessibility,t=h.legend.allItems.length;
c=c===a.left||c===a.up?-1:1;return h.highlightLegendItem(this.highlightedLegendItemIx+c)?(this.highlightedLegendItemIx+=c,d.success):1<t&&e.keyboardNavigation.wrapAround?(b.init(c),d.success):d[0<c?"next":"prev"]},onKbdClick:function(b){var a=this.chart.legend.allItems[this.highlightedLegendItemIx];a&&a.a11yProxyElement&&c(a.a11yProxyElement,"click");return b.response.success},shouldHaveLegendNavigation:function(){var b=this.chart,c=b.colorAxis&&b.colorAxis.length,a=(b.options.legend||{}).accessibility||
{};return!!(b.legend&&b.legend.allItems&&b.legend.display&&!c&&a.enabled&&a.keyboardNavigation&&a.keyboardNavigation.enabled)},onKbdNavigationInit:function(b){var c=this.chart,a=c.legend.allItems.length-1;b=0<b?0:a;c.highlightLegendItem(b);this.highlightedLegendItemIx=b}});return a});p(a,"Accessibility/Components/MenuComponent.js",[a["Core/Globals.js"],a["Core/Utilities.js"],a["Accessibility/AccessibilityComponent.js"],a["Accessibility/KeyboardNavigationHandler.js"],a["Accessibility/Utils/ChartUtilities.js"],
a["Accessibility/Utils/HTMLUtilities.js"]],function(a,f,l,n,m,k){function g(c){return c.exportSVGElements&&c.exportSVGElements[0]}f=f.extend;var q=m.unhideChartElementFromAT,e=k.removeElement,d=k.getFakeMouseEvent;a.Chart.prototype.showExportMenu=function(){var c=g(this);if(c&&(c=c.element,c.onclick))c.onclick(d("click"))};a.Chart.prototype.hideExportMenu=function(){var c=this.exportDivElements;c&&this.exportContextMenu&&(c.forEach(function(b){if("highcharts-menu-item"===b.className&&b.onmouseout)b.onmouseout(d("mouseout"))}),
this.highlightedExportItemIx=0,this.exportContextMenu.hideMenu(),this.container.focus())};a.Chart.prototype.highlightExportItem=function(c){var b=this.exportDivElements&&this.exportDivElements[c],a=this.exportDivElements&&this.exportDivElements[this.highlightedExportItemIx];if(b&&"LI"===b.tagName&&(!b.children||!b.children.length)){var e=!!(this.renderTo.getElementsByTagName("g")[0]||{}).focus;b.focus&&e&&b.focus();if(a&&a.onmouseout)a.onmouseout(d("mouseout"));if(b.onmouseover)b.onmouseover(d("mouseover"));
this.highlightedExportItemIx=c;return!0}return!1};a.Chart.prototype.highlightLastExportItem=function(){var c;if(this.exportDivElements)for(c=this.exportDivElements.length;c--;)if(this.highlightExportItem(c))return!0;return!1};a=function(){};a.prototype=new l;f(a.prototype,{init:function(){var c=this.chart,b=this;this.addEvent(c,"exportMenuShown",function(){b.onMenuShown()});this.addEvent(c,"exportMenuHidden",function(){b.onMenuHidden()})},onMenuHidden:function(){var c=this.chart.exportContextMenu;
c&&c.setAttribute("aria-hidden","true");this.isExportMenuShown=!1;this.setExportButtonExpandedState("false")},onMenuShown:function(){var c=this.chart,b=c.exportContextMenu;b&&(this.addAccessibleContextMenuAttribs(),q(c,b));this.isExportMenuShown=!0;this.setExportButtonExpandedState("true")},setExportButtonExpandedState:function(c){var b=this.exportButtonProxy;b&&b.setAttribute("aria-expanded",c)},onChartRender:function(){var c=this.chart,b=c.options.accessibility;e(this.exportProxyGroup);var a=c.options.exporting,
d=g(c);a&&!1!==a.enabled&&a.accessibility&&a.accessibility.enabled&&d&&d.element&&(this.exportProxyGroup=this.addProxyGroup("all"===b.landmarkVerbosity?{"aria-label":c.langFormat("accessibility.exporting.exportRegionLabel",{chart:c}),role:"region"}:{}),b=g(this.chart),this.exportButtonProxy=this.createProxyButton(b,this.exportProxyGroup,{"aria-label":c.langFormat("accessibility.exporting.menuButtonLabel",{chart:c}),"aria-expanded":"false"}))},addAccessibleContextMenuAttribs:function(){var c=this.chart,
b=c.exportDivElements;b&&b.length&&(b.forEach(function(b){"LI"!==b.tagName||b.children&&b.children.length?b.setAttribute("aria-hidden","true"):b.setAttribute("tabindex",-1)}),b=b[0].parentNode,b.removeAttribute("aria-hidden"),b.setAttribute("aria-label",c.langFormat("accessibility.exporting.chartMenuLabel",{chart:c})))},getKeyboardNavigation:function(){var c=this.keyCodes,b=this.chart,a=this;return new n(b,{keyCodeMap:[[[c.left,c.up],function(){return a.onKbdPrevious(this)}],[[c.right,c.down],function(){return a.onKbdNext(this)}],
[[c.enter,c.space],function(){return a.onKbdClick(this)}]],validate:function(){return b.exportChart&&!1!==b.options.exporting.enabled&&!1!==b.options.exporting.accessibility.enabled},init:function(){var c=a.exportButtonProxy,d=b.exportingGroup;d&&c&&b.setFocusToElement(d,c)},terminate:function(){b.hideExportMenu()}})},onKbdPrevious:function(c){var b=this.chart,a=b.options.accessibility;c=c.response;for(var d=b.highlightedExportItemIx||0;d--;)if(b.highlightExportItem(d))return c.success;return a.keyboardNavigation.wrapAround?
(b.highlightLastExportItem(),c.success):c.prev},onKbdNext:function(c){var b=this.chart,a=b.options.accessibility;c=c.response;for(var d=(b.highlightedExportItemIx||0)+1;d<b.exportDivElements.length;++d)if(b.highlightExportItem(d))return c.success;return a.keyboardNavigation.wrapAround?(b.highlightExportItem(0),c.success):c.next},onKbdClick:function(c){var b=this.chart,a=b.exportDivElements[b.highlightedExportItemIx],d=g(b).element;this.isExportMenuShown?this.fakeClickEvent(a):(this.fakeClickEvent(d),
b.highlightExportItem(0));return c.response.success}});return a});p(a,"Accessibility/Components/SeriesComponent/SeriesKeyboardNavigation.js",[a["Core/Series/Series.js"],a["Core/Chart/Chart.js"],a["Series/Line/LineSeries.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"],a["Accessibility/KeyboardNavigationHandler.js"],a["Accessibility/Utils/EventProvider.js"],a["Accessibility/Utils/ChartUtilities.js"]],function(a,f,l,n,m,k,g,q){function e(b){var c=b.index,a=b.series.points,d=a.length;if(a[c]!==
b)for(;d--;){if(a[d]===b)return d}else return c}function d(b){var c=b.chart.options.accessibility.keyboardNavigation.seriesNavigation,a=b.options.accessibility||{},d=a.keyboardNavigation;return d&&!1===d.enabled||!1===a.enabled||!1===b.options.enableMouseTracking||!b.visible||c.pointNavigationEnabledThreshold&&c.pointNavigationEnabledThreshold<=b.points.length}function c(b){var c=b.series.chart.options.accessibility;return b.isNull&&c.keyboardNavigation.seriesNavigation.skipNullPoints||!1===b.visible||
d(b.series)}function b(b,c,a,d){var y=Infinity,h=c.points.length,e=function(b){return!(x(b.plotX)&&x(b.plotY))};if(!e(b)){for(;h--;){var v=c.points[h];if(!e(v)&&(v=(b.plotX-v.plotX)*(b.plotX-v.plotX)*(a||1)+(b.plotY-v.plotY)*(b.plotY-v.plotY)*(d||1),v<y)){y=v;var w=h}}return x(w)?c.points[w]:void 0}}function h(b){var c=!1;delete b.highlightedPoint;return c=b.series.reduce(function(b,c){return b||c.highlightFirstValidPoint()},!1)}function t(b,c){this.keyCodes=c;this.chart=b}var u=a.seriesTypes,x=m.defined,
r=m.extend,A=m.fireEvent,p=q.getPointFromXY,B=q.getSeriesFromName,C=q.scrollToPoint;l.prototype.keyboardMoveVertical=!0;["column","pie"].forEach(function(b){u[b]&&(u[b].prototype.keyboardMoveVertical=!1)});n.prototype.highlight=function(){var b=this.series.chart;if(this.isNull)b.tooltip&&b.tooltip.hide(0);else this.onMouseOver();C(this);this.graphic&&b.setFocusToElement(this.graphic);b.highlightedPoint=this;return this};f.prototype.highlightAdjacentPoint=function(b){var a=this.series,h=this.highlightedPoint,
w=h&&e(h)||0,k=h&&h.series.points,g=this.series&&this.series[this.series.length-1];g=g&&g.points&&g.points[g.points.length-1];if(!a[0]||!a[0].points)return!1;if(h){if(a=a[h.series.index+(b?1:-1)],w=k[w+(b?1:-1)],!w&&a&&(w=a.points[b?0:a.points.length-1]),!w)return!1}else w=b?a[0].points[0]:g;return c(w)?(a=w.series,d(a)?this.highlightedPoint=b?a.points[a.points.length-1]:a.points[0]:this.highlightedPoint=w,this.highlightAdjacentPoint(b)):w.highlight()};l.prototype.highlightFirstValidPoint=function(){var b=
this.chart.highlightedPoint,a=(b&&b.series)===this?e(b):0;b=this.points;var d=b.length;if(b&&d){for(var h=a;h<d;++h)if(!c(b[h]))return b[h].highlight();for(;0<=a;--a)if(!c(b[a]))return b[a].highlight()}return!1};f.prototype.highlightAdjacentSeries=function(c){var a,h=this.highlightedPoint;var e=(a=this.series&&this.series[this.series.length-1])&&a.points&&a.points[a.points.length-1];if(!this.highlightedPoint)return a=c?this.series&&this.series[0]:a,(e=c?a&&a.points&&a.points[0]:e)?e.highlight():!1;
a=this.series[h.series.index+(c?-1:1)];if(!a)return!1;e=b(h,a,4);if(!e)return!1;if(d(a))return e.highlight(),c=this.highlightAdjacentSeries(c),c?c:(h.highlight(),!1);e.highlight();return e.series.highlightFirstValidPoint()};f.prototype.highlightAdjacentPointVertical=function(b){var a=this.highlightedPoint,h=Infinity,e;if(!x(a.plotX)||!x(a.plotY))return!1;this.series.forEach(function(y){d(y)||y.points.forEach(function(d){if(x(d.plotY)&&x(d.plotX)&&d!==a){var v=d.plotY-a.plotY,w=Math.abs(d.plotX-a.plotX);
w=Math.abs(v)*Math.abs(v)+w*w*4;y.yAxis&&y.yAxis.reversed&&(v*=-1);!(0>=v&&b||0<=v&&!b||5>w||c(d))&&w<h&&(h=w,e=d)}})});return e?e.highlight():!1};r(t.prototype,{init:function(){var b=this,c=this.chart,a=this.eventProvider=new g;a.addEvent(l,"destroy",function(){return b.onSeriesDestroy(this)});a.addEvent(c,"afterDrilldown",function(){h(this);this.focusElement&&this.focusElement.removeFocusBorder()});a.addEvent(c,"drilldown",function(c){c=c.point;var a=c.series;b.lastDrilledDownPoint={x:c.x,y:c.y,
seriesName:a?a.name:""}});a.addEvent(c,"drillupall",function(){setTimeout(function(){b.onDrillupAll()},10)})},onDrillupAll:function(){var b=this.lastDrilledDownPoint,c=this.chart,a=b&&B(c,b.seriesName),d;b&&a&&x(b.x)&&x(b.y)&&(d=p(a,b.x,b.y));c.container&&c.container.focus();d&&d.highlight&&d.highlight();c.focusElement&&c.focusElement.removeFocusBorder()},getKeyboardNavigationHandler:function(){var b=this,c=this.keyCodes,a=this.chart,d=a.inverted;return new k(a,{keyCodeMap:[[d?[c.up,c.down]:[c.left,
c.right],function(c){return b.onKbdSideways(this,c)}],[d?[c.left,c.right]:[c.up,c.down],function(c){return b.onKbdVertical(this,c)}],[[c.enter,c.space],function(b,c){if(b=a.highlightedPoint)A(b.series,"click",r(c,{point:b})),b.firePointEvent("click");return this.response.success}]],init:function(c){return b.onHandlerInit(this,c)},terminate:function(){return b.onHandlerTerminate()}})},onKbdSideways:function(b,c){var a=this.keyCodes;return this.attemptHighlightAdjacentPoint(b,c===a.right||c===a.down)},
onKbdVertical:function(b,c){var a=this.chart,d=this.keyCodes;c=c===d.down||c===d.right;d=a.options.accessibility.keyboardNavigation.seriesNavigation;if(d.mode&&"serialize"===d.mode)return this.attemptHighlightAdjacentPoint(b,c);a[a.highlightedPoint&&a.highlightedPoint.series.keyboardMoveVertical?"highlightAdjacentPointVertical":"highlightAdjacentSeries"](c);return b.response.success},onHandlerInit:function(b,c){var a=this.chart;if(0<c)h(a);else{c=a.series.length;for(var d;c--&&!(a.highlightedPoint=
a.series[c].points[a.series[c].points.length-1],d=a.series[c].highlightFirstValidPoint()););}return b.response.success},onHandlerTerminate:function(){var b,c,a=this.chart,d=a.highlightedPoint;null===(b=a.tooltip)||void 0===b?void 0:b.hide(0);null===(c=null===d||void 0===d?void 0:d.onMouseOut)||void 0===c?void 0:c.call(d);delete a.highlightedPoint},attemptHighlightAdjacentPoint:function(b,c){var a=this.chart,d=a.options.accessibility.keyboardNavigation.wrapAround;return a.highlightAdjacentPoint(c)?
b.response.success:d?b.init(c?1:-1):b.response[c?"next":"prev"]},onSeriesDestroy:function(b){var c=this.chart;c.highlightedPoint&&c.highlightedPoint.series===b&&(delete c.highlightedPoint,c.focusElement&&c.focusElement.removeFocusBorder())},destroy:function(){this.eventProvider.removeAddedEvents()}});return t});p(a,"Accessibility/Components/AnnotationsA11y.js",[a["Accessibility/Utils/HTMLUtilities.js"]],function(a){function f(a){return(a.annotations||[]).reduce(function(a,d){var c;!1!==(null===(c=
d.options)||void 0===c?void 0:c.visible)&&(a=a.concat(d.labels));return a},[])}function l(a){var e,d,c,b,h=null===(d=null===(e=a.options)||void 0===e?void 0:e.accessibility)||void 0===d?void 0:d.description;return h?h:(null===(b=null===(c=a.graphic)||void 0===c?void 0:c.text)||void 0===b?void 0:b.textStr)||""}function r(a){var e,d,c=null===(d=null===(e=a.options)||void 0===e?void 0:e.accessibility)||void 0===d?void 0:d.description;if(c)return c;e=a.chart;d=l(a);c=a.points.filter(function(b){return!!b.graphic}).map(function(b){var c,
a;if(!(a=null===(c=null===b||void 0===b?void 0:b.accessibility)||void 0===c?void 0:c.valueDescription)){var d,e;a=(null===(e=null===(d=null===b||void 0===b?void 0:b.graphic)||void 0===d?void 0:d.element)||void 0===e?void 0:e.getAttribute("aria-label"))||""}b=(null===b||void 0===b?void 0:b.series.name)||"";return(b?b+", ":"")+"data point "+a}).filter(function(b){return!!b});var b=c.length;a="accessibility.screenReaderSection.annotations.description"+(1<b?"MultiplePoints":b?"SinglePoint":"NoPoints");
d={annotationText:d,numPoints:b,annotationPoint:c[0],additionalAnnotationPoints:c.slice(1)};return e.langFormat(a,d)}function m(a){return f(a).map(function(a){return(a=k(g(r(a))))?"<li>"+a+"</li>":""})}var k=a.escapeStringForHTML,g=a.stripHTMLTagsFromString;return{getAnnotationsInfoHTML:function(a){var e=a.annotations;return e&&e.length?"<ul>"+m(a).join(" ")+"</ul>":""},getAnnotationLabelDescription:r,getAnnotationListItems:m,getPointAnnotationTexts:function(a){var e=f(a.series.chart).filter(function(d){return-1<
d.points.indexOf(a)});return e.length?e.map(function(a){return""+l(a)}):[]}}});p(a,"Accessibility/Components/SeriesComponent/SeriesDescriber.js",[a["Accessibility/Components/AnnotationsA11y.js"],a["Accessibility/Utils/ChartUtilities.js"],a["Accessibility/Utils/HTMLUtilities.js"],a["Core/Tooltip.js"],a["Core/Utilities.js"]],function(a,f,l,n,m){function k(b){var c=b.index;return b.series&&b.series.data&&H(c)?L(b.series.data,function(b){return!!(b&&"undefined"!==typeof b.index&&b.index>c&&b.graphic&&
b.graphic.element)})||null:null}function g(b){var c=b.chart.options.accessibility.series.pointDescriptionEnabledThreshold;return!!(!1!==c&&b.points&&b.points.length>=c)}function q(b){var c=b.options.accessibility||{};return!g(b)&&!c.exposeAsGroupOnly}function e(b){var c=b.chart.options.accessibility.keyboardNavigation.seriesNavigation;return!(!b.points||!(b.points.length<c.pointNavigationEnabledThreshold||!1===c.pointNavigationEnabledThreshold))}function d(b,c){var a=b.series.chart,d=a.options.accessibility.point||
{};b=b.series.tooltipOptions||{};a=a.options.lang;return K(c)?N(c,d.valueDecimals||b.valueDecimals||-1,a.decimalPoint,a.accessibility.thousandsSep||a.thousandsSep):c}function c(b){var c=(b.options.accessibility||{}).description;return c&&b.chart.langFormat("accessibility.series.description",{description:c,series:b})||""}function b(b,c){return b.chart.langFormat("accessibility.series."+c+"Description",{name:z(b[c]),series:b})}function h(b){var c=b.series,a=c.chart,d=a.options.accessibility.point||
{};if(c.xAxis&&c.xAxis.dateTime)return c=n.prototype.getXDateFormat.call({getDateFormat:n.prototype.getDateFormat,chart:a},b,a.options.tooltip,c.xAxis),d=d.dateFormatter&&d.dateFormatter(b)||d.dateFormat||c,a.time.dateFormat(d,b.x,void 0)}function t(b){var c=h(b),a=(b.series.xAxis||{}).categories&&H(b.category)&&(""+b.category).replace("<br/>"," "),d=b.id&&0>b.id.indexOf("highcharts-"),e="x, "+b.x;return b.name||c||a||(d?b.id:e)}function u(b,c,a){var e=c||"",h=a||"";return b.series.pointArrayMap.reduce(function(c,
a){c+=c.length?", ":"";var y=d(b,E(b[a],b.options[a]));return c+(a+": "+e+y+h)},"")}function x(b){var c=b.series,a=c.chart.options.accessibility.point||{},e=c.tooltipOptions||{},h=a.valuePrefix||e.valuePrefix||"";a=a.valueSuffix||e.valueSuffix||"";e=d(b,b["undefined"!==typeof b.value?"value":"y"]);return b.isNull?c.chart.langFormat("accessibility.series.nullPointValue",{point:b}):c.pointArrayMap?u(b,h,a):h+e+a}function r(b){var c=b.series,a=c.chart,d=a.options.accessibility.point.valueDescriptionFormat,
e=(c=E(c.xAxis&&c.xAxis.options.accessibility&&c.xAxis.options.accessibility.enabled,!a.angular))?t(b):"";b={point:b,index:H(b.index)?b.index+1:"",xDescription:e,value:x(b),separator:c?", ":""};return M(d,b,a)}function A(b){var c=b.series,a=c.chart,d=r(b),e=b.options&&b.options.accessibility&&b.options.accessibility.description;e=e?" "+e:"";c=1<a.series.length&&c.name?" "+c.name+".":"";a=b.series.chart;var h=C(b),y={point:b,annotations:h};a=h.length?a.langFormat("accessibility.series.pointAnnotationsDescription",
y):"";b.accessibility=b.accessibility||{};b.accessibility.valueDescription=d;return d+e+c+(a?" "+a:"")}function p(b){var c=q(b),a=e(b);(c||a)&&b.points.forEach(function(b){var a;if(!(a=b.graphic&&b.graphic.element)&&(a=b.series&&b.series.is("sunburst"),a=b.isNull&&!a)){var d=b.series,e=k(b);d=(a=e&&e.graphic)?a.parentGroup:d.graph||d.group;e=e?{x:E(b.plotX,e.plotX,0),y:E(b.plotY,e.plotY,0)}:{x:E(b.plotX,0),y:E(b.plotY,0)};e=b.series.chart.renderer.rect(e.x,e.y,1,1);e.attr({"class":"highcharts-a11y-dummy-point",
fill:"none",opacity:0,"fill-opacity":0,"stroke-opacity":0});d&&d.element?(b.graphic=e,b.hasDummyGraphic=!0,e.add(d),d.element.insertBefore(e.element,a?a.element:null),a=e.element):a=void 0}a&&(a.setAttribute("tabindex","-1"),a.style.outline="0",c?(e=b.series,d=e.chart.options.accessibility.point||{},e=e.options.accessibility||{},b=D(J(e.pointDescriptionFormatter&&e.pointDescriptionFormatter(b)||d.descriptionFormatter&&d.descriptionFormatter(b)||A(b))),a.setAttribute("role","img"),a.setAttribute("aria-label",
b)):a.setAttribute("aria-hidden",!0))})}function B(a){var d=a.chart,e=d.types||[],h=c(a),y=function(b){return d[b]&&1<d[b].length&&a[b]},k=b(a,"xAxis"),g=b(a,"yAxis"),v={name:a.name||"",ix:a.index+1,numSeries:d.series&&d.series.length,numPoints:a.points&&a.points.length,series:a};e=1<e.length?"Combination":"";return(d.langFormat("accessibility.series.summary."+a.type+e,v)||d.langFormat("accessibility.series.summary.default"+e,v))+(h?" "+h:"")+(y("yAxis")?" "+g:"")+(y("xAxis")?" "+k:"")}var C=a.getPointAnnotationTexts,
z=f.getAxisDescription,y=f.getSeriesFirstPointElement,v=f.getSeriesA11yElement,w=f.unhideChartElementFromAT,D=l.escapeStringForHTML,G=l.reverseChildNodes,J=l.stripHTMLTagsFromString,L=m.find,M=m.format,K=m.isNumber,N=m.numberFormat,E=m.pick,H=m.defined;return{describeSeries:function(b){var c=b.chart,a=y(b),d=v(b),e=c.is3d&&c.is3d();if(d){d.lastChild!==a||e||G(d);p(b);w(c,d);e=b.chart;c=e.options.chart||{};a=1<e.series.length;e=e.options.accessibility.series.describeSingleSeries;var h=(b.options.accessibility||
{}).exposeAsGroupOnly;c.options3d&&c.options3d.enabled&&a||!(a||e||h||g(b))?d.setAttribute("aria-label",""):(c=b.chart.options.accessibility,a=c.landmarkVerbosity,(b.options.accessibility||{}).exposeAsGroupOnly?d.setAttribute("role","img"):"all"===a&&d.setAttribute("role","region"),d.setAttribute("tabindex","-1"),d.style.outline="0",d.setAttribute("aria-label",D(J(c.series.descriptionFormatter&&c.series.descriptionFormatter(b)||B(b)))))}},defaultPointDescriptionFormatter:A,defaultSeriesDescriptionFormatter:B,
getPointA11yTimeDescription:h,getPointXDescription:t,getPointValue:x,getPointValueDescription:r}});p(a,"Accessibility/Utils/Announcer.js",[a["Core/Globals.js"],a["Accessibility/Utils/DOMElementProvider.js"],a["Accessibility/Utils/HTMLUtilities.js"]],function(a,f,l){var r=a.doc,m=l.setElAttrs,k=l.visuallyHideElement;l=function(){function a(a,e){this.chart=a;this.domElementProvider=new f;this.announceRegion=this.addAnnounceRegion(e)}a.prototype.destroy=function(){this.domElementProvider.destroyCreatedElements()};
a.prototype.announce=function(a){var e=this;this.announceRegion.innerHTML=a;this.clearAnnouncementRegionTimer&&clearTimeout(this.clearAnnouncementRegionTimer);this.clearAnnouncementRegionTimer=setTimeout(function(){e.announceRegion.innerHTML="";delete e.clearAnnouncementRegionTimer},1E3)};a.prototype.addAnnounceRegion=function(a){var e=this.chart.announcerContainer||this.createAnnouncerContainer(),d=this.domElementProvider.createElement("div");m(d,{"aria-hidden":!1,"aria-live":a});k(d);e.appendChild(d);
return d};a.prototype.createAnnouncerContainer=function(){var a=this.chart,e=r.createElement("div");m(e,{"aria-hidden":!1,style:"position:relative","class":"highcharts-announcer-container"});a.renderTo.insertBefore(e,a.renderTo.firstChild);return a.announcerContainer=e};return a}();return a.Announcer=l});p(a,"Accessibility/Components/SeriesComponent/NewDataAnnouncer.js",[a["Core/Globals.js"],a["Series/Line/LineSeries.js"],a["Core/Utilities.js"],a["Accessibility/Utils/ChartUtilities.js"],a["Accessibility/Components/SeriesComponent/SeriesDescriber.js"],
a["Accessibility/Utils/Announcer.js"],a["Accessibility/Utils/EventProvider.js"]],function(a,f,l,n,m,k,g){function q(b){var c=b.series.data.filter(function(c){return b.x===c.x&&b.y===c.y});return 1===c.length?c[0]:b}function e(b,c){var a=(b||[]).concat(c||[]).reduce(function(b,c){b[c.name+c.index]=c;return b},{});return Object.keys(a).map(function(b){return a[b]})}var d=l.extend,c=l.defined,b=n.getChartTitle,h=m.defaultPointDescriptionFormatter,t=m.defaultSeriesDescriptionFormatter;l=function(b){this.chart=
b};d(l.prototype,{init:function(){var b=this.chart,c=b.options.accessibility.announceNewData.interruptUser?"assertive":"polite";this.lastAnnouncementTime=0;this.dirty={allSeries:{}};this.eventProvider=new g;this.announcer=new k(b,c);this.addEventListeners()},destroy:function(){this.eventProvider.removeAddedEvents();this.announcer.destroy()},addEventListeners:function(){var b=this,c=this.chart,a=this.eventProvider;a.addEvent(c,"afterDrilldown",function(){b.lastAnnouncementTime=0});a.addEvent(f,"updatedData",
function(){b.onSeriesUpdatedData(this)});a.addEvent(c,"afterAddSeries",function(c){b.onSeriesAdded(c.series)});a.addEvent(f,"addPoint",function(c){b.onPointAdded(c.point)});a.addEvent(c,"redraw",function(){b.announceDirtyData()})},onSeriesUpdatedData:function(b){var c=this.chart;b.chart===c&&c.options.accessibility.announceNewData.enabled&&(this.dirty.hasDirty=!0,this.dirty.allSeries[b.name+b.index]=b)},onSeriesAdded:function(b){this.chart.options.accessibility.announceNewData.enabled&&(this.dirty.hasDirty=
!0,this.dirty.allSeries[b.name+b.index]=b,this.dirty.newSeries=c(this.dirty.newSeries)?void 0:b)},onPointAdded:function(b){var a=b.series.chart;this.chart===a&&a.options.accessibility.announceNewData.enabled&&(this.dirty.newPoint=c(this.dirty.newPoint)?void 0:b)},announceDirtyData:function(){var b=this;if(this.chart.options.accessibility.announceNewData&&this.dirty.hasDirty){var c=this.dirty.newPoint;c&&(c=q(c));this.queueAnnouncement(Object.keys(this.dirty.allSeries).map(function(c){return b.dirty.allSeries[c]}),
this.dirty.newSeries,c);this.dirty={allSeries:{}}}},queueAnnouncement:function(b,c,a){var d=this,h=this.chart.options.accessibility.announceNewData;if(h.enabled){var k=+new Date;h=Math.max(0,h.minAnnounceInterval-(k-this.lastAnnouncementTime));b=e(this.queuedAnnouncement&&this.queuedAnnouncement.series,b);if(c=this.buildAnnouncementMessage(b,c,a))this.queuedAnnouncement&&clearTimeout(this.queuedAnnouncementTimer),this.queuedAnnouncement={time:k,message:c,series:b},this.queuedAnnouncementTimer=setTimeout(function(){d&&
d.announcer&&(d.lastAnnouncementTime=+new Date,d.announcer.announce(d.queuedAnnouncement.message),delete d.queuedAnnouncement,delete d.queuedAnnouncementTimer)},h)}},buildAnnouncementMessage:function(c,d,e){var k=this.chart,g=k.options.accessibility.announceNewData;if(g.announcementFormatter&&(c=g.announcementFormatter(c,d,e),!1!==c))return c.length?c:null;c=a.charts&&1<a.charts.length?"Multiple":"Single";c=d?"newSeriesAnnounce"+c:e?"newPointAnnounce"+c:"newDataAnnounce";g=b(k);return k.langFormat("accessibility.announceNewData."+
c,{chartTitle:g,seriesDesc:d?t(d):null,pointDesc:e?h(e):null,point:e,series:d})}});return l});p(a,"Accessibility/Components/SeriesComponent/ForcedMarkers.js",[a["Series/Line/LineSeries.js"],a["Core/Utilities.js"]],function(a,f){function l(a){m(!0,a,{marker:{enabled:!0,states:{normal:{opacity:0}}}})}var r=f.addEvent,m=f.merge;return function(){r(a,"render",function(){var a=this.options,g=!1!==(this.options.accessibility&&this.options.accessibility.enabled);if(g=this.chart.options.accessibility.enabled&&
g)g=this.chart.options.accessibility,g=this.points.length<g.series.pointDescriptionEnabledThreshold||!1===g.series.pointDescriptionEnabledThreshold;if(g){if(a.marker&&!1===a.marker.enabled&&(this.a11yMarkersForced=!0,l(this.options)),this._hasPointMarkers&&this.points&&this.points.length)for(a=this.points.length;a--;){g=this.points[a];var f=g.options;delete g.hasForcedA11yMarker;f.marker&&(f.marker.enabled?(m(!0,f.marker,{states:{normal:{opacity:f.marker.states&&f.marker.states.normal&&f.marker.states.normal.opacity||
1}}}),g.hasForcedA11yMarker=!1):(l(f),g.hasForcedA11yMarker=!0))}}else this.a11yMarkersForced&&(delete this.a11yMarkersForced,(a=this.resetA11yMarkerOptions)&&m(!0,this.options,{marker:{enabled:a.enabled,states:{normal:{opacity:a.states&&a.states.normal&&a.states.normal.opacity}}}}))});r(a,"afterSetOptions",function(a){this.resetA11yMarkerOptions=m(a.options.marker||{},this.userOptions.marker||{})});r(a,"afterRender",function(){if(this.chart.styledMode){if(this.markerGroup)this.markerGroup[this.a11yMarkersForced?
"addClass":"removeClass"]("highcharts-a11y-markers-hidden");this._hasPointMarkers&&this.points&&this.points.length&&this.points.forEach(function(a){a.graphic&&(a.graphic[a.hasForcedA11yMarker?"addClass":"removeClass"]("highcharts-a11y-marker-hidden"),a.graphic[!1===a.hasForcedA11yMarker?"addClass":"removeClass"]("highcharts-a11y-marker-visible"))})}})}});p(a,"Accessibility/Components/SeriesComponent/SeriesComponent.js",[a["Core/Globals.js"],a["Core/Utilities.js"],a["Accessibility/AccessibilityComponent.js"],
a["Accessibility/Components/SeriesComponent/SeriesKeyboardNavigation.js"],a["Accessibility/Components/SeriesComponent/NewDataAnnouncer.js"],a["Accessibility/Components/SeriesComponent/ForcedMarkers.js"],a["Accessibility/Utils/ChartUtilities.js"],a["Accessibility/Components/SeriesComponent/SeriesDescriber.js"],a["Core/Tooltip.js"]],function(a,f,l,n,m,k,g,q,e){f=f.extend;var d=g.hideSeriesFromAT,c=q.describeSeries;a.SeriesAccessibilityDescriber=q;k();a=function(){};a.prototype=new l;f(a.prototype,{init:function(){this.newDataAnnouncer=
new m(this.chart);this.newDataAnnouncer.init();this.keyboardNavigation=new n(this.chart,this.keyCodes);this.keyboardNavigation.init();this.hideTooltipFromATWhenShown();this.hideSeriesLabelsFromATWhenShown()},hideTooltipFromATWhenShown:function(){var b=this;this.addEvent(e,"refresh",function(){this.chart===b.chart&&this.label&&this.label.element&&this.label.element.setAttribute("aria-hidden",!0)})},hideSeriesLabelsFromATWhenShown:function(){this.addEvent(this.chart,"afterDrawSeriesLabels",function(){this.series.forEach(function(b){b.labelBySeries&&
b.labelBySeries.attr("aria-hidden",!0)})})},onChartRender:function(){this.chart.series.forEach(function(b){!1!==(b.options.accessibility&&b.options.accessibility.enabled)&&b.visible?c(b):d(b)})},getKeyboardNavigation:function(){return this.keyboardNavigation.getKeyboardNavigationHandler()},destroy:function(){this.newDataAnnouncer.destroy();this.keyboardNavigation.destroy()}});return a});p(a,"Accessibility/Components/ZoomComponent.js",[a["Accessibility/AccessibilityComponent.js"],a["Accessibility/Utils/ChartUtilities.js"],
a["Core/Globals.js"],a["Accessibility/Utils/HTMLUtilities.js"],a["Accessibility/KeyboardNavigationHandler.js"],a["Core/Utilities.js"]],function(a,f,l,n,m,k){var g=f.unhideChartElementFromAT;f=l.noop;var q=n.removeElement,e=n.setElAttrs;n=k.extend;var d=k.pick;l.Axis.prototype.panStep=function(c,b){var a=b||3;b=this.getExtremes();var d=(b.max-b.min)/a*c;a=b.max+d;d=b.min+d;var e=a-d;0>c&&d<b.dataMin?(d=b.dataMin,a=d+e):0<c&&a>b.dataMax&&(a=b.dataMax,d=a-e);this.setExtremes(d,a)};f.prototype=new a;
n(f.prototype,{init:function(){var c=this,b=this.chart;["afterShowResetZoom","afterDrilldown","drillupall"].forEach(function(a){c.addEvent(b,a,function(){c.updateProxyOverlays()})})},onChartUpdate:function(){var c=this.chart,b=this;c.mapNavButtons&&c.mapNavButtons.forEach(function(a,d){g(c,a.element);b.setMapNavButtonAttrs(a.element,"accessibility.zoom.mapZoom"+(d?"Out":"In"))})},setMapNavButtonAttrs:function(c,b){var a=this.chart;b=a.langFormat(b,{chart:a});e(c,{tabindex:-1,role:"button","aria-label":b})},
onChartRender:function(){this.updateProxyOverlays()},updateProxyOverlays:function(){var c=this.chart;q(this.drillUpProxyGroup);q(this.resetZoomProxyGroup);c.resetZoomButton&&this.recreateProxyButtonAndGroup(c.resetZoomButton,"resetZoomProxyButton","resetZoomProxyGroup",c.langFormat("accessibility.zoom.resetZoomButton",{chart:c}));c.drillUpButton&&this.recreateProxyButtonAndGroup(c.drillUpButton,"drillUpProxyButton","drillUpProxyGroup",c.langFormat("accessibility.drillUpButton",{chart:c,buttonText:c.getDrilldownBackText()}))},
recreateProxyButtonAndGroup:function(c,b,a,d){q(this[a]);this[a]=this.addProxyGroup();this[b]=this.createProxyButton(c,this[a],{"aria-label":d,tabindex:-1})},getMapZoomNavigation:function(){var c=this.keyCodes,b=this.chart,a=this;return new m(b,{keyCodeMap:[[[c.up,c.down,c.left,c.right],function(b){return a.onMapKbdArrow(this,b)}],[[c.tab],function(b,c){return a.onMapKbdTab(this,c)}],[[c.space,c.enter],function(){return a.onMapKbdClick(this)}]],validate:function(){return!!(b.mapZoom&&b.mapNavButtons&&
b.mapNavButtons.length)},init:function(b){return a.onMapNavInit(b)}})},onMapKbdArrow:function(c,b){var a=this.keyCodes;this.chart[b===a.up||b===a.down?"yAxis":"xAxis"][0].panStep(b===a.left||b===a.up?-1:1);return c.response.success},onMapKbdTab:function(c,b){var a=this.chart;c=c.response;var d=(b=b.shiftKey)&&!this.focusedMapNavButtonIx||!b&&this.focusedMapNavButtonIx;a.mapNavButtons[this.focusedMapNavButtonIx].setState(0);if(d)return a.mapZoom(),c[b?"prev":"next"];this.focusedMapNavButtonIx+=b?-1:
1;b=a.mapNavButtons[this.focusedMapNavButtonIx];a.setFocusToElement(b.box,b.element);b.setState(2);return c.success},onMapKbdClick:function(c){this.fakeClickEvent(this.chart.mapNavButtons[this.focusedMapNavButtonIx].element);return c.response.success},onMapNavInit:function(c){var b=this.chart,a=b.mapNavButtons[0],d=b.mapNavButtons[1];a=0<c?a:d;b.setFocusToElement(a.box,a.element);a.setState(2);this.focusedMapNavButtonIx=0<c?0:1},simpleButtonNavigation:function(c,b,a){var e=this.keyCodes,h=this,g=
this.chart;return new m(g,{keyCodeMap:[[[e.tab,e.up,e.down,e.left,e.right],function(b,a){return this.response[b===e.tab&&a.shiftKey||b===e.left||b===e.up?"prev":"next"]}],[[e.space,e.enter],function(){var b=a(this,g);return d(b,this.response.success)}]],validate:function(){return g[c]&&g[c].box&&h[b]},init:function(){g.setFocusToElement(g[c].box,h[b])}})},getKeyboardNavigation:function(){return[this.simpleButtonNavigation("resetZoomButton","resetZoomProxyButton",function(a,b){b.zoomOut()}),this.simpleButtonNavigation("drillUpButton",
"drillUpProxyButton",function(a,b){b.drillUp();return a.response.prev}),this.getMapZoomNavigation()]}});return f});p(a,"Accessibility/Components/RangeSelectorComponent.js",[a["Accessibility/AccessibilityComponent.js"],a["Accessibility/Utils/ChartUtilities.js"],a["Core/Globals.js"],a["Accessibility/Utils/HTMLUtilities.js"],a["Accessibility/KeyboardNavigationHandler.js"],a["Core/Utilities.js"]],function(a,f,l,n,m,k){var g=f.unhideChartElementFromAT,q=n.setElAttrs;f=k.extend;l.Chart.prototype.highlightRangeSelectorButton=
function(a){var d,c,b=(null===(d=this.rangeSelector)||void 0===d?void 0:d.buttons)||[];d=this.highlightedRangeSelectorItemIx;var e=null===(c=this.rangeSelector)||void 0===c?void 0:c.selected;"undefined"!==typeof d&&b[d]&&d!==e&&b[d].setState(this.oldRangeSelectorItemState||0);this.highlightedRangeSelectorItemIx=a;return b[a]?(this.setFocusToElement(b[a].box,b[a].element),a!==e&&(this.oldRangeSelectorItemState=b[a].state,b[a].setState(1)),!0):!1};l=function(){};l.prototype=new a;f(l.prototype,{onChartUpdate:function(){var a,
d=this.chart,c=this,b=d.rangeSelector;b&&((null===(a=b.buttons)||void 0===a?0:a.length)&&b.buttons.forEach(function(b){g(d,b.element);c.setRangeButtonAttrs(b)}),b.maxInput&&b.minInput&&["minInput","maxInput"].forEach(function(a,e){if(a=b[a])g(d,a),c.setRangeInputAttrs(a,"accessibility.rangeSelector."+(e?"max":"min")+"InputLabel")}))},setRangeButtonAttrs:function(a){q(a.element,{tabindex:-1,role:"button"})},setRangeInputAttrs:function(a,d){var c=this.chart;q(a,{tabindex:-1,role:"textbox","aria-label":c.langFormat(d,
{chart:c})})},getRangeSelectorButtonNavigation:function(){var a=this.chart,d=this.keyCodes,c=this;return new m(a,{keyCodeMap:[[[d.left,d.right,d.up,d.down],function(b){return c.onButtonNavKbdArrowKey(this,b)}],[[d.enter,d.space],function(){return c.onButtonNavKbdClick(this)}]],validate:function(){return a.rangeSelector&&a.rangeSelector.buttons&&a.rangeSelector.buttons.length},init:function(b){var c=a.rangeSelector.buttons.length-1;a.highlightRangeSelectorButton(0<b?0:c)}})},onButtonNavKbdArrowKey:function(a,
d){var c=a.response,b=this.keyCodes,e=this.chart,g=e.options.accessibility.keyboardNavigation.wrapAround;d=d===b.left||d===b.up?-1:1;return e.highlightRangeSelectorButton(e.highlightedRangeSelectorItemIx+d)?c.success:g?(a.init(d),c.success):c[0<d?"next":"prev"]},onButtonNavKbdClick:function(a){a=a.response;var d=this.chart;3!==d.oldRangeSelectorItemState&&this.fakeClickEvent(d.rangeSelector.buttons[d.highlightedRangeSelectorItemIx].element);return a.success},getRangeSelectorInputNavigation:function(){var a=
this.chart,d=this.keyCodes,c=this;return new m(a,{keyCodeMap:[[[d.tab,d.up,d.down],function(b,a){return c.onInputKbdMove(this,b===d.tab&&a.shiftKey||b===d.up?-1:1)}]],validate:function(){return!!(a.rangeSelector&&a.rangeSelector.inputGroup&&"hidden"!==a.rangeSelector.inputGroup.element.getAttribute("visibility")&&!1!==a.options.rangeSelector.inputEnabled&&a.rangeSelector.minInput&&a.rangeSelector.maxInput)},init:function(b){c.onInputNavInit(b)},terminate:function(){c.onInputNavTerminate()}})},onInputKbdMove:function(a,
d){var c=this.chart;a=a.response;var b=c.highlightedInputRangeIx+=d;if(1<b||0>b)return a[0<d?"next":"prev"];c.rangeSelector[b?"maxInput":"minInput"].focus();return a.success},onInputNavInit:function(a){var d=this.chart;a=0<a?0:1;d.highlightedInputRangeIx=a;d.rangeSelector[a?"maxInput":"minInput"].focus()},onInputNavTerminate:function(){var a=this.chart.rangeSelector||{};a.maxInput&&a.hideInput("max");a.minInput&&a.hideInput("min")},getKeyboardNavigation:function(){return[this.getRangeSelectorButtonNavigation(),
this.getRangeSelectorInputNavigation()]}});return l});p(a,"Accessibility/Components/InfoRegionsComponent.js",[a["Core/Globals.js"],a["Core/Utilities.js"],a["Accessibility/AccessibilityComponent.js"],a["Accessibility/Utils/Announcer.js"],a["Accessibility/Components/AnnotationsA11y.js"],a["Accessibility/Utils/ChartUtilities.js"],a["Accessibility/Utils/HTMLUtilities.js"]],function(a,f,l,n,m,k,g){function q(b){return b.replace(/&lt;(h[1-7]|p|div|ul|ol|li)&gt;/g,"<$1>").replace(/&lt;&#x2F;(h[1-7]|p|div|ul|ol|li|a|button)&gt;/g,
"</$1>").replace(/&lt;(div|a|button) id=&quot;([a-zA-Z\-0-9#]*?)&quot;&gt;/g,'<$1 id="$2">')}var e=a.doc,d=f.extend,c=f.format,b=f.pick,h=m.getAnnotationsInfoHTML,t=k.unhideChartElementFromAT,u=k.getChartTitle,r=k.getAxisDescription,p=g.addClass,A=g.setElAttrs,F=g.escapeStringForHTML,B=g.stripHTMLTagsFromString,C=g.getElement,z=g.visuallyHideElement;a.Chart.prototype.getTypeDescription=function(b){var a=b[0],c=this.series&&this.series[0]||{};c={numSeries:this.series.length,numPoints:c.points&&c.points.length,
chart:this,mapTitle:c.mapTitle};if(!a)return this.langFormat("accessibility.chartTypes.emptyChart",c);if("map"===a)return c.mapTitle?this.langFormat("accessibility.chartTypes.mapTypeDescription",c):this.langFormat("accessibility.chartTypes.unknownMap",c);if(1<this.types.length)return this.langFormat("accessibility.chartTypes.combinationChart",c);b=b[0];a=this.langFormat("accessibility.seriesTypeDescriptions."+b,c);var d=this.series&&2>this.series.length?"Single":"Multiple";return(this.langFormat("accessibility.chartTypes."+
b+d,c)||this.langFormat("accessibility.chartTypes.default"+d,c))+(a?" "+a:"")};f=function(){};f.prototype=new l;d(f.prototype,{init:function(){var b=this.chart,a=this;this.initRegionsDefinitions();this.addEvent(b,"afterGetTable",function(b){a.onDataTableCreated(b)});this.addEvent(b,"afterViewData",function(b){a.dataTableDiv=b;setTimeout(function(){a.focusDataTable()},300)});this.announcer=new n(b,"assertive")},initRegionsDefinitions:function(){var b=this;this.screenReaderSections={before:{element:null,
buildContent:function(a){var c=a.options.accessibility.screenReaderSection.beforeChartFormatter;return c?c(a):b.defaultBeforeChartFormatter(a)},insertIntoDOM:function(b,a){a.renderTo.insertBefore(b,a.renderTo.firstChild)},afterInserted:function(){"undefined"!==typeof b.sonifyButtonId&&b.initSonifyButton(b.sonifyButtonId);"undefined"!==typeof b.dataTableButtonId&&b.initDataTableButton(b.dataTableButtonId)}},after:{element:null,buildContent:function(a){var c=a.options.accessibility.screenReaderSection.afterChartFormatter;
return c?c(a):b.defaultAfterChartFormatter()},insertIntoDOM:function(b,a){a.renderTo.insertBefore(b,a.container.nextSibling)}}}},onChartRender:function(){var b=this;this.linkedDescriptionElement=this.getLinkedDescriptionElement();this.setLinkedDescriptionAttrs();Object.keys(this.screenReaderSections).forEach(function(a){b.updateScreenReaderSection(a)})},getLinkedDescriptionElement:function(){var b=this.chart.options.accessibility.linkedDescription;if(b){if("string"!==typeof b)return b;b=c(b,this.chart);
b=e.querySelectorAll(b);if(1===b.length)return b[0]}},setLinkedDescriptionAttrs:function(){var b=this.linkedDescriptionElement;b&&(b.setAttribute("aria-hidden","true"),p(b,"highcharts-linked-description"))},updateScreenReaderSection:function(b){var a=this.chart,c=this.screenReaderSections[b],d=c.buildContent(a),e=c.element=c.element||this.createElement("div"),h=e.firstChild||this.createElement("div");this.setScreenReaderSectionAttribs(e,b);h.innerHTML=d;e.appendChild(h);c.insertIntoDOM(e,a);z(h);
t(a,h);c.afterInserted&&c.afterInserted()},setScreenReaderSectionAttribs:function(b,a){var c=this.chart,d=c.langFormat("accessibility.screenReaderSection."+a+"RegionLabel",{chart:c});A(b,{id:"highcharts-screen-reader-region-"+a+"-"+c.index,"aria-label":d});b.style.position="relative";"all"===c.options.accessibility.landmarkVerbosity&&d&&b.setAttribute("role","region")},defaultBeforeChartFormatter:function(){var b,c=this.chart,d=c.options.accessibility.screenReaderSection.beforeChartFormat,e=this.getAxesDescription(),
g=c.sonify&&(null===(b=c.options.sonification)||void 0===b?void 0:b.enabled);b="highcharts-a11y-sonify-data-btn-"+c.index;var f="hc-linkto-highcharts-data-table-"+c.index,k=h(c),m=c.langFormat("accessibility.screenReaderSection.annotations.heading",{chart:c});e={chartTitle:u(c),typeDescription:this.getTypeDescriptionText(),chartSubtitle:this.getSubtitleText(),chartLongdesc:this.getLongdescText(),xAxisDescription:e.xAxis,yAxisDescription:e.yAxis,playAsSoundButton:g?this.getSonifyButtonText(b):"",viewTableButton:c.getCSV?
this.getDataTableButtonText(f):"",annotationsTitle:k?m:"",annotationsList:k};c=a.i18nFormat(d,e,c);this.dataTableButtonId=f;this.sonifyButtonId=b;return q(F(c)).replace(/<(\w+)[^>]*?>\s*<\/\1>/g,"")},defaultAfterChartFormatter:function(){var b=this.chart,c=b.options.accessibility.screenReaderSection.afterChartFormat,d={endOfChartMarker:this.getEndOfChartMarkerText()};b=a.i18nFormat(c,d,b);return q(F(b)).replace(/<(\w+)[^>]*?>\s*<\/\1>/g,"")},getLinkedDescription:function(){var b=this.linkedDescriptionElement;
return B(b&&b.innerHTML||"")},getLongdescText:function(){var b=this.chart.options,a=b.caption;a=a&&a.text;var c=this.getLinkedDescription();return b.accessibility.description||c||a||""},getTypeDescriptionText:function(){var b=this.chart;return b.types?b.options.accessibility.typeDescription||b.getTypeDescription(b.types):""},getDataTableButtonText:function(b){var a=this.chart;a=a.langFormat("accessibility.table.viewAsDataTableButtonText",{chart:a,chartTitle:u(a)});return'<button id="'+b+'">'+a+"</button>"},
getSonifyButtonText:function(b){var a,c=this.chart;if(!1===(null===(a=c.options.sonification)||void 0===a?void 0:a.enabled))return"";a=c.langFormat("accessibility.sonification.playAsSoundButtonText",{chart:c,chartTitle:u(c)});return'<button id="'+b+'">'+a+"</button>"},getSubtitleText:function(){var b=this.chart.options.subtitle;return B(b&&b.text||"")},getEndOfChartMarkerText:function(){var b=this.chart,a=b.langFormat("accessibility.screenReaderSection.endOfChartMarker",{chart:b});return'<div id="highcharts-end-of-chart-marker-'+
b.index+'">'+a+"</div>"},onDataTableCreated:function(b){var a=this.chart;a.options.accessibility.enabled&&(this.viewDataTableButton&&this.viewDataTableButton.setAttribute("aria-expanded","true"),b.html=b.html.replace("<table ",'<table tabindex="-1" summary="'+a.langFormat("accessibility.table.tableSummary",{chart:a})+'"'))},focusDataTable:function(){var b=this.dataTableDiv;(b=b&&b.getElementsByTagName("table")[0])&&b.focus&&b.focus()},initSonifyButton:function(b){var a=this,c=this.sonifyButton=C(b),
d=this.chart,e=function(b){null===c||void 0===c?void 0:c.setAttribute("aria-hidden","true");null===c||void 0===c?void 0:c.setAttribute("aria-label","");b.preventDefault();b.stopPropagation();b=d.langFormat("accessibility.sonification.playAsSoundClickAnnouncement",{chart:d});a.announcer.announce(b);setTimeout(function(){null===c||void 0===c?void 0:c.removeAttribute("aria-hidden");null===c||void 0===c?void 0:c.removeAttribute("aria-label");d.sonify&&d.sonify()},1E3)};c&&d&&(A(c,{tabindex:"-1"}),c.onclick=
function(b){var a;((null===(a=d.options.accessibility)||void 0===a?void 0:a.screenReaderSection.onPlayAsSoundClick)||e).call(this,b,d)})},initDataTableButton:function(b){var a=this.viewDataTableButton=C(b),c=this.chart;b=b.replace("hc-linkto-","");a&&(A(a,{tabindex:"-1","aria-expanded":!!C(b)}),a.onclick=c.options.accessibility.screenReaderSection.onViewDataTableClick||function(){c.viewData()})},getAxesDescription:function(){var a=this.chart,c=function(c,d){c=a[c];return 1<c.length||c[0]&&b(c[0].options.accessibility&&
c[0].options.accessibility.enabled,d)},d=!!a.types&&0>a.types.indexOf("map"),e=!!a.hasCartesianSeries,h=c("xAxis",!a.angular&&e&&d);c=c("yAxis",e&&d);d={};h&&(d.xAxis=this.getAxisDescriptionText("xAxis"));c&&(d.yAxis=this.getAxisDescriptionText("yAxis"));return d},getAxisDescriptionText:function(b){var a=this,c=this.chart,d=c[b];return c.langFormat("accessibility.axis."+b+"Description"+(1<d.length?"Plural":"Singular"),{chart:c,names:d.map(function(b){return r(b)}),ranges:d.map(function(b){return a.getAxisRangeDescription(b)}),
numAxes:d.length})},getAxisRangeDescription:function(b){var a=b.options||{};return a.accessibility&&"undefined"!==typeof a.accessibility.rangeDescription?a.accessibility.rangeDescription:b.categories?this.getCategoryAxisRangeDesc(b):!b.dateTime||0!==b.min&&0!==b.dataMin?this.getAxisFromToDescription(b):this.getAxisTimeLengthDesc(b)},getCategoryAxisRangeDesc:function(b){var a=this.chart;return b.dataMax&&b.dataMin?a.langFormat("accessibility.axis.rangeCategories",{chart:a,axis:b,numCategories:b.dataMax-
b.dataMin+1}):""},getAxisTimeLengthDesc:function(b){var a=this.chart,c={},d="Seconds";c.Seconds=((b.max||0)-(b.min||0))/1E3;c.Minutes=c.Seconds/60;c.Hours=c.Minutes/60;c.Days=c.Hours/24;["Minutes","Hours","Days"].forEach(function(b){2<c[b]&&(d=b)});var e=c[d].toFixed("Seconds"!==d&&"Minutes"!==d?1:0);return a.langFormat("accessibility.axis.timeRange"+d,{chart:a,axis:b,range:e.replace(".0","")})},getAxisFromToDescription:function(b){var a=this.chart,c=a.options.accessibility.screenReaderSection.axisRangeDateFormat,
d=function(d){return b.dateTime?a.time.dateFormat(c,b[d]):b[d]};return a.langFormat("accessibility.axis.rangeFromTo",{chart:a,axis:b,rangeFrom:d("min"),rangeTo:d("max")})},destroy:function(){var b;null===(b=this.announcer)||void 0===b?void 0:b.destroy()}});return f});p(a,"Accessibility/Components/ContainerComponent.js",[a["Accessibility/AccessibilityComponent.js"],a["Accessibility/Utils/ChartUtilities.js"],a["Core/Globals.js"],a["Accessibility/Utils/HTMLUtilities.js"],a["Core/Utilities.js"]],function(a,
f,l,n,m){var k=f.unhideChartElementFromAT,g=f.getChartTitle,q=l.doc,e=n.stripHTMLTagsFromString;f=m.extend;l=function(){};l.prototype=new a;f(l.prototype,{onChartUpdate:function(){this.handleSVGTitleElement();this.setSVGContainerLabel();this.setGraphicContainerAttrs();this.setRenderToAttrs();this.makeCreditsAccessible()},handleSVGTitleElement:function(){var a=this.chart,c="highcharts-title-"+a.index,b=e(a.langFormat("accessibility.svgContainerTitle",{chartTitle:g(a)}));if(b.length){var h=this.svgTitleElement=
this.svgTitleElement||q.createElementNS("http://www.w3.org/2000/svg","title");h.textContent=b;h.id=c;a.renderTo.insertBefore(h,a.renderTo.firstChild)}},setSVGContainerLabel:function(){var a=this.chart,c=e(a.langFormat("accessibility.svgContainerLabel",{chartTitle:g(a)}));a.renderer.box&&c.length&&a.renderer.box.setAttribute("aria-label",c)},setGraphicContainerAttrs:function(){var a=this.chart,c=a.langFormat("accessibility.graphicContainerLabel",{chartTitle:g(a)});c.length&&a.container.setAttribute("aria-label",
c)},setRenderToAttrs:function(){var a=this.chart;"disabled"!==a.options.accessibility.landmarkVerbosity?a.renderTo.setAttribute("role","region"):a.renderTo.removeAttribute("role");a.renderTo.setAttribute("aria-label",a.langFormat("accessibility.chartContainerLabel",{title:g(a),chart:a}))},makeCreditsAccessible:function(){var a=this.chart,c=a.credits;c&&(c.textStr&&c.element.setAttribute("aria-label",e(a.langFormat("accessibility.credits",{creditsStr:c.textStr}))),k(a,c.element))},destroy:function(){this.chart.renderTo.setAttribute("aria-hidden",
!0)}});return l});p(a,"Accessibility/HighContrastMode.js",[a["Core/Globals.js"]],function(a){var f=a.doc,l=a.isMS,n=a.win;return{isHighContrastModeActive:function(){var a=/(Edg)/.test(n.navigator.userAgent);if(n.matchMedia&&a)return n.matchMedia("(-ms-high-contrast: active)").matches;if(l&&n.getComputedStyle){a=f.createElement("div");a.style.backgroundImage="url(data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==)";f.body.appendChild(a);var k=(a.currentStyle||n.getComputedStyle(a)).backgroundImage;
f.body.removeChild(a);return"none"===k}return!1},setHighContrastTheme:function(a){a.highContrastModeActive=!0;var f=a.options.accessibility.highContrastTheme;a.update(f,!1);a.series.forEach(function(a){var g=f.plotOptions[a.type]||{};a.update({color:g.color||"windowText",colors:[g.color||"windowText"],borderColor:g.borderColor||"window"});a.points.forEach(function(a){a.options&&a.options.color&&a.update({color:g.color||"windowText",borderColor:g.borderColor||"window"},!1)})});a.redraw()}}});p(a,"Accessibility/HighContrastTheme.js",
[],function(){return{chart:{backgroundColor:"window"},title:{style:{color:"windowText"}},subtitle:{style:{color:"windowText"}},colorAxis:{minColor:"windowText",maxColor:"windowText",stops:[]},colors:["windowText"],xAxis:{gridLineColor:"windowText",labels:{style:{color:"windowText"}},lineColor:"windowText",minorGridLineColor:"windowText",tickColor:"windowText",title:{style:{color:"windowText"}}},yAxis:{gridLineColor:"windowText",labels:{style:{color:"windowText"}},lineColor:"windowText",minorGridLineColor:"windowText",
tickColor:"windowText",title:{style:{color:"windowText"}}},tooltip:{backgroundColor:"window",borderColor:"windowText",style:{color:"windowText"}},plotOptions:{series:{lineColor:"windowText",fillColor:"window",borderColor:"windowText",edgeColor:"windowText",borderWidth:1,dataLabels:{connectorColor:"windowText",color:"windowText",style:{color:"windowText",textOutline:"none"}},marker:{lineColor:"windowText",fillColor:"windowText"}},pie:{color:"window",colors:["window"],borderColor:"windowText",borderWidth:1},
boxplot:{fillColor:"window"},candlestick:{lineColor:"windowText",fillColor:"window"},errorbar:{fillColor:"window"}},legend:{backgroundColor:"window",itemStyle:{color:"windowText"},itemHoverStyle:{color:"windowText"},itemHiddenStyle:{color:"#555"},title:{style:{color:"windowText"}}},credits:{style:{color:"windowText"}},labels:{style:{color:"windowText"}},drilldown:{activeAxisLabelStyle:{color:"windowText"},activeDataLabelStyle:{color:"windowText"}},navigation:{buttonOptions:{symbolStroke:"windowText",
theme:{fill:"window"}}},rangeSelector:{buttonTheme:{fill:"window",stroke:"windowText",style:{color:"windowText"},states:{hover:{fill:"window",stroke:"windowText",style:{color:"windowText"}},select:{fill:"#444",stroke:"windowText",style:{color:"windowText"}}}},inputBoxBorderColor:"windowText",inputStyle:{backgroundColor:"window",color:"windowText"},labelStyle:{color:"windowText"}},navigator:{handles:{backgroundColor:"window",borderColor:"windowText"},outlineColor:"windowText",maskFill:"transparent",
series:{color:"windowText",lineColor:"windowText"},xAxis:{gridLineColor:"windowText"}},scrollbar:{barBackgroundColor:"#444",barBorderColor:"windowText",buttonArrowColor:"windowText",buttonBackgroundColor:"window",buttonBorderColor:"windowText",rifleColor:"windowText",trackBackgroundColor:"window",trackBorderColor:"windowText"}}});p(a,"Accessibility/Options/Options.js",[a["Core/Color/Palette.js"]],function(a){return{accessibility:{enabled:!0,screenReaderSection:{beforeChartFormat:"<h5>{chartTitle}</h5><div>{typeDescription}</div><div>{chartSubtitle}</div><div>{chartLongdesc}</div><div>{playAsSoundButton}</div><div>{viewTableButton}</div><div>{xAxisDescription}</div><div>{yAxisDescription}</div><div>{annotationsTitle}{annotationsList}</div>",
afterChartFormat:"{endOfChartMarker}",axisRangeDateFormat:"%Y-%m-%d %H:%M:%S"},series:{describeSingleSeries:!1,pointDescriptionEnabledThreshold:200},point:{valueDescriptionFormat:"{index}. {xDescription}{separator}{value}."},landmarkVerbosity:"all",linkedDescription:'*[data-highcharts-chart="{index}"] + .highcharts-description',keyboardNavigation:{enabled:!0,focusBorder:{enabled:!0,hideBrowserFocusOutline:!0,style:{color:a.highlightColor80,lineWidth:2,borderRadius:3},margin:2},order:["series","zoom",
"rangeSelector","legend","chartMenu"],wrapAround:!0,seriesNavigation:{skipNullPoints:!0,pointNavigationEnabledThreshold:!1}},announceNewData:{enabled:!1,minAnnounceInterval:5E3,interruptUser:!1}},legend:{accessibility:{enabled:!0,keyboardNavigation:{enabled:!0}}},exporting:{accessibility:{enabled:!0}}}});p(a,"Accessibility/Options/LangOptions.js",[],function(){return{accessibility:{defaultChartTitle:"Chart",chartContainerLabel:"{title}. Highcharts interactive chart.",svgContainerLabel:"Interactive chart",
drillUpButton:"{buttonText}",credits:"Chart credits: {creditsStr}",thousandsSep:",",svgContainerTitle:"",graphicContainerLabel:"",screenReaderSection:{beforeRegionLabel:"Chart screen reader information.",afterRegionLabel:"",annotations:{heading:"Chart annotations summary",descriptionSinglePoint:"{annotationText}. Related to {annotationPoint}",descriptionMultiplePoints:"{annotationText}. Related to {annotationPoint}{ Also related to, #each(additionalAnnotationPoints)}",descriptionNoPoints:"{annotationText}"},
endOfChartMarker:"End of interactive chart."},sonification:{playAsSoundButtonText:"Play as sound, {chartTitle}",playAsSoundClickAnnouncement:"Play"},legend:{legendLabel:"Toggle series visibility",legendItem:"Hide {itemName}"},zoom:{mapZoomIn:"Zoom chart",mapZoomOut:"Zoom out chart",resetZoomButton:"Reset zoom"},rangeSelector:{minInputLabel:"Select start date.",maxInputLabel:"Select end date."},table:{viewAsDataTableButtonText:"View as data table, {chartTitle}",tableSummary:"Table representation of chart."},
announceNewData:{newDataAnnounce:"Updated data for chart {chartTitle}",newSeriesAnnounceSingle:"New data series: {seriesDesc}",newPointAnnounceSingle:"New data point: {pointDesc}",newSeriesAnnounceMultiple:"New data series in chart {chartTitle}: {seriesDesc}",newPointAnnounceMultiple:"New data point in chart {chartTitle}: {pointDesc}"},seriesTypeDescriptions:{boxplot:"Box plot charts are typically used to display groups of statistical data. Each data point in the chart can have up to 5 values: minimum, lower quartile, median, upper quartile, and maximum.",
arearange:"Arearange charts are line charts displaying a range between a lower and higher value for each point.",areasplinerange:"These charts are line charts displaying a range between a lower and higher value for each point.",bubble:"Bubble charts are scatter charts where each data point also has a size value.",columnrange:"Columnrange charts are column charts displaying a range between a lower and higher value for each point.",errorbar:"Errorbar series are used to display the variability of the data.",
funnel:"Funnel charts are used to display reduction of data in stages.",pyramid:"Pyramid charts consist of a single pyramid with item heights corresponding to each point value.",waterfall:"A waterfall chart is a column chart where each column contributes towards a total end value."},chartTypes:{emptyChart:"Empty chart",mapTypeDescription:"Map of {mapTitle} with {numSeries} data series.",unknownMap:"Map of unspecified region with {numSeries} data series.",combinationChart:"Combination chart with {numSeries} data series.",
defaultSingle:"Chart with {numPoints} data {#plural(numPoints, points, point)}.",defaultMultiple:"Chart with {numSeries} data series.",splineSingle:"Line chart with {numPoints} data {#plural(numPoints, points, point)}.",splineMultiple:"Line chart with {numSeries} lines.",lineSingle:"Line chart with {numPoints} data {#plural(numPoints, points, point)}.",lineMultiple:"Line chart with {numSeries} lines.",columnSingle:"Bar chart with {numPoints} {#plural(numPoints, bars, bar)}.",columnMultiple:"Bar chart with {numSeries} data series.",
barSingle:"Bar chart with {numPoints} {#plural(numPoints, bars, bar)}.",barMultiple:"Bar chart with {numSeries} data series.",pieSingle:"Pie chart with {numPoints} {#plural(numPoints, slices, slice)}.",pieMultiple:"Pie chart with {numSeries} pies.",scatterSingle:"Scatter chart with {numPoints} {#plural(numPoints, points, point)}.",scatterMultiple:"Scatter chart with {numSeries} data series.",boxplotSingle:"Boxplot with {numPoints} {#plural(numPoints, boxes, box)}.",boxplotMultiple:"Boxplot with {numSeries} data series.",
bubbleSingle:"Bubble chart with {numPoints} {#plural(numPoints, bubbles, bubble)}.",bubbleMultiple:"Bubble chart with {numSeries} data series."},axis:{xAxisDescriptionSingular:"The chart has 1 X axis displaying {names[0]}. {ranges[0]}",xAxisDescriptionPlural:"The chart has {numAxes} X axes displaying {#each(names, -1) }and {names[-1]}.",yAxisDescriptionSingular:"The chart has 1 Y axis displaying {names[0]}. {ranges[0]}",yAxisDescriptionPlural:"The chart has {numAxes} Y axes displaying {#each(names, -1) }and {names[-1]}.",
timeRangeDays:"Range: {range} days.",timeRangeHours:"Range: {range} hours.",timeRangeMinutes:"Range: {range} minutes.",timeRangeSeconds:"Range: {range} seconds.",rangeFromTo:"Range: {rangeFrom} to {rangeTo}.",rangeCategories:"Range: {numCategories} categories."},exporting:{chartMenuLabel:"Chart menu",menuButtonLabel:"View chart menu",exportRegionLabel:"Chart menu"},series:{summary:{"default":"{name}, series {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",defaultCombination:"{name}, series {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",
line:"{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",lineCombination:"{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.",spline:"{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",splineCombination:"{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.",column:"{name}, bar series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bars, bar)}.",
columnCombination:"{name}, series {ix} of {numSeries}. Bar series with {numPoints} {#plural(numPoints, bars, bar)}.",bar:"{name}, bar series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bars, bar)}.",barCombination:"{name}, series {ix} of {numSeries}. Bar series with {numPoints} {#plural(numPoints, bars, bar)}.",pie:"{name}, pie {ix} of {numSeries} with {numPoints} {#plural(numPoints, slices, slice)}.",pieCombination:"{name}, series {ix} of {numSeries}. Pie with {numPoints} {#plural(numPoints, slices, slice)}.",
scatter:"{name}, scatter plot {ix} of {numSeries} with {numPoints} {#plural(numPoints, points, point)}.",scatterCombination:"{name}, series {ix} of {numSeries}, scatter plot with {numPoints} {#plural(numPoints, points, point)}.",boxplot:"{name}, boxplot {ix} of {numSeries} with {numPoints} {#plural(numPoints, boxes, box)}.",boxplotCombination:"{name}, series {ix} of {numSeries}. Boxplot with {numPoints} {#plural(numPoints, boxes, box)}.",bubble:"{name}, bubble series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bubbles, bubble)}.",
bubbleCombination:"{name}, series {ix} of {numSeries}. Bubble series with {numPoints} {#plural(numPoints, bubbles, bubble)}.",map:"{name}, map {ix} of {numSeries} with {numPoints} {#plural(numPoints, areas, area)}.",mapCombination:"{name}, series {ix} of {numSeries}. Map with {numPoints} {#plural(numPoints, areas, area)}.",mapline:"{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",maplineCombination:"{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.",
mapbubble:"{name}, bubble series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bubbles, bubble)}.",mapbubbleCombination:"{name}, series {ix} of {numSeries}. Bubble series with {numPoints} {#plural(numPoints, bubbles, bubble)}."},description:"{description}",xAxisDescription:"X axis, {name}",yAxisDescription:"Y axis, {name}",nullPointValue:"No value",pointAnnotationsDescription:"{Annotation: #each(annotations). }"}}}});p(a,"Accessibility/Options/DeprecatedOptions.js",[a["Core/Utilities.js"]],
function(a){function f(a,d,c){for(var b,e=0;e<d.length-1;++e)b=d[e],a=a[b]=q(a[b],{});a[d[d.length-1]]=c}function l(a,d,c,b){function e(b,a){return a.reduce(function(b,a){return b[a]},b)}var k=e(a.options,d),l=e(a.options,c);Object.keys(b).forEach(function(e){var h,t=k[e];"undefined"!==typeof t&&(f(l,b[e],t),g(32,!1,a,(h={},h[d.join(".")+"."+e]=c.join(".")+"."+b[e].join("."),h)))})}function n(a){var d=a.options.chart||{},c=a.options.accessibility||{};["description","typeDescription"].forEach(function(b){var e;
d[b]&&(c[b]=d[b],g(32,!1,a,(e={},e["chart."+b]="use accessibility."+b,e)))})}function m(a){a.axes.forEach(function(d){(d=d.options)&&d.description&&(d.accessibility=d.accessibility||{},d.accessibility.description=d.description,g(32,!1,a,{"axis.description":"use axis.accessibility.description"}))})}function k(a){var d={description:["accessibility","description"],exposeElementToA11y:["accessibility","exposeAsGroupOnly"],pointDescriptionFormatter:["accessibility","pointDescriptionFormatter"],skipKeyboardNavigation:["accessibility",
"keyboardNavigation","enabled"]};a.series.forEach(function(c){Object.keys(d).forEach(function(b){var e,k=c.options[b];"undefined"!==typeof k&&(f(c.options,d[b],"skipKeyboardNavigation"===b?!k:k),g(32,!1,a,(e={},e["series."+b]="series."+d[b].join("."),e)))})})}var g=a.error,q=a.pick;return function(a){n(a);m(a);a.series&&k(a);l(a,["accessibility"],["accessibility"],{pointDateFormat:["point","dateFormat"],pointDateFormatter:["point","dateFormatter"],pointDescriptionFormatter:["point","descriptionFormatter"],
pointDescriptionThreshold:["series","pointDescriptionEnabledThreshold"],pointNavigationThreshold:["keyboardNavigation","seriesNavigation","pointNavigationEnabledThreshold"],pointValueDecimals:["point","valueDecimals"],pointValuePrefix:["point","valuePrefix"],pointValueSuffix:["point","valueSuffix"],screenReaderSectionFormatter:["screenReaderSection","beforeChartFormatter"],describeSingleSeries:["series","describeSingleSeries"],seriesDescriptionFormatter:["series","descriptionFormatter"],onTableAnchorClick:["screenReaderSection",
"onViewDataTableClick"],axisRangeDateFormat:["screenReaderSection","axisRangeDateFormat"]});l(a,["accessibility","keyboardNavigation"],["accessibility","keyboardNavigation","seriesNavigation"],{skipNullPoints:["skipNullPoints"],mode:["mode"]});l(a,["lang","accessibility"],["lang","accessibility"],{legendItem:["legend","legendItem"],legendLabel:["legend","legendLabel"],mapZoomIn:["zoom","mapZoomIn"],mapZoomOut:["zoom","mapZoomOut"],resetZoomButton:["zoom","resetZoomButton"],screenReaderRegionLabel:["screenReaderSection",
"beforeRegionLabel"],rangeSelectorButton:["rangeSelector","buttonText"],rangeSelectorMaxInput:["rangeSelector","maxInputLabel"],rangeSelectorMinInput:["rangeSelector","minInputLabel"],svgContainerEnd:["screenReaderSection","endOfChartMarker"],viewAsDataTable:["table","viewAsDataTableButtonText"],tableSummary:["table","tableSummary"]})}});p(a,"Accessibility/A11yI18n.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,f){function l(a,g){var f=a.indexOf("#each("),e=a.indexOf("#plural("),d=a.indexOf("["),
c=a.indexOf("]");if(-1<f){d=a.slice(f).indexOf(")")+f;var b=a.substring(0,f);e=a.substring(d+1);d=a.substring(f+6,d).split(",");f=Number(d[1]);a="";if(g=g[d[0]])for(f=isNaN(f)?g.length:f,f=0>f?g.length+f:Math.min(f,g.length),d=0;d<f;++d)a+=b+g[d]+e;return a.length?a:""}if(-1<e){b=a.slice(e).indexOf(")")+e;a=a.substring(e+8,b).split(",");switch(Number(g[a[0]])){case 0:a=m(a[4],a[1]);break;case 1:a=m(a[2],a[1]);break;case 2:a=m(a[3],a[1]);break;default:a=a[1]}a?(g=a,g=g.trim&&g.trim()||g.replace(/^\s+|\s+$/g,
"")):g="";return g}return-1<d?(e=a.substring(0,d),a=Number(a.substring(d+1,c)),g=g[e],!isNaN(a)&&g&&(0>a?(b=g[g.length+a],"undefined"===typeof b&&(b=g[0])):(b=g[a],"undefined"===typeof b&&(b=g[g.length-1]))),"undefined"!==typeof b?b:""):"{"+a+"}"}var n=f.format,m=f.pick;a.i18nFormat=function(a,f,m){var e=function(a,b){a=a.slice(b||0);var c=a.indexOf("{"),d=a.indexOf("}");if(-1<c&&d>c)return{statement:a.substring(c+1,d),begin:b+c+1,end:b+d}},d=[],c=0;do{var b=e(a,c);var h=a.substring(c,b&&b.begin-
1);h.length&&d.push({value:h,type:"constant"});b&&d.push({value:b.statement,type:"statement"});c=b?b.end+1:c+1}while(b);d.forEach(function(a){"statement"===a.type&&(a.value=l(a.value,f))});return n(d.reduce(function(a,b){return a+b.value},""),f,m)};a.Chart.prototype.langFormat=function(f,g){f=f.split(".");for(var k=this.options.lang,e=0;e<f.length;++e)k=k&&k[f[e]];return"string"===typeof k?a.i18nFormat(k,g,this):""}});p(a,"Accessibility/FocusBorder.js",[a["Core/Globals.js"],a["Core/Renderer/SVG/SVGElement.js"],
a["Core/Renderer/SVG/SVGLabel.js"],a["Core/Utilities.js"]],function(a,f,l,n){function m(a){if(!a.focusBorderDestroyHook){var b=a.destroy;a.destroy=function(){var c,d;null===(d=null===(c=a.focusBorder)||void 0===c?void 0:c.destroy)||void 0===d?void 0:d.call(c);return b.apply(a,arguments)};a.focusBorderDestroyHook=b}}function k(a){for(var b=[],d=1;d<arguments.length;d++)b[d-1]=arguments[d];a.focusBorderUpdateHooks||(a.focusBorderUpdateHooks={},c.forEach(function(c){c+="Setter";var d=a[c]||a._defaultSetter;
a.focusBorderUpdateHooks[c]=d;a[c]=function(){var c=d.apply(a,arguments);a.addFocusBorder.apply(a,b);return c}}))}function g(a){a.focusBorderUpdateHooks&&(Object.keys(a.focusBorderUpdateHooks).forEach(function(b){var c=a.focusBorderUpdateHooks[b];c===a._defaultSetter?delete a[b]:a[b]=c}),delete a.focusBorderUpdateHooks)}var q=n.addEvent,e=n.extend,d=n.pick,c="x y transform width height r d stroke-width".split(" ");e(f.prototype,{addFocusBorder:function(b,c){this.focusBorder&&this.removeFocusBorder();
var e=this.getBBox(),f=d(b,3);e.x+=this.translateX?this.translateX:0;e.y+=this.translateY?this.translateY:0;var g=e.x-f,h=e.y-f,n=e.width+2*f,q=e.height+2*f,p=this instanceof l;if("text"===this.element.nodeName||p){var r=!!this.rotation;if(p)var z={x:r?1:0,y:0};else g=z=0,"middle"===this.attr("text-anchor")?(z=a.isFirefox&&this.rotation?.25:.5,g=a.isFirefox&&!this.rotation?.75:.5):this.rotation?z=.25:g=.75,z={x:z,y:g};g=+this.attr("x")-e.width*z.x-f;h=+this.attr("y")-e.height*z.y-f;p&&r&&(p=n,n=q,
q=p,g=+this.attr("x")-e.height*z.x-f,h=+this.attr("y")-e.width*z.y-f)}this.focusBorder=this.renderer.rect(g,h,n,q,parseInt((c&&c.borderRadius||0).toString(),10)).addClass("highcharts-focus-border").attr({zIndex:99}).add(this.parentGroup);this.renderer.styledMode||this.focusBorder.attr({stroke:c&&c.stroke,"stroke-width":c&&c.strokeWidth});k(this,b,c);m(this)},removeFocusBorder:function(){g(this);this.focusBorderDestroyHook&&(this.destroy=this.focusBorderDestroyHook,delete this.focusBorderDestroyHook);
this.focusBorder&&(this.focusBorder.destroy(),delete this.focusBorder)}});a.Chart.prototype.renderFocusBorder=function(){var a=this.focusElement,c=this.options.accessibility.keyboardNavigation.focusBorder;a&&(a.removeFocusBorder(),c.enabled&&a.addFocusBorder(c.margin,{stroke:c.style.color,strokeWidth:c.style.lineWidth,borderRadius:c.style.borderRadius}))};a.Chart.prototype.setFocusToElement=function(a,c){var b=this.options.accessibility.keyboardNavigation.focusBorder;(c=c||a.element)&&c.focus&&(c.hcEvents&&
c.hcEvents.focusin||q(c,"focusin",function(){}),c.focus(),b.hideBrowserFocusOutline&&(c.style.outline="none"));this.focusElement&&this.focusElement.removeFocusBorder();this.focusElement=a;this.renderFocusBorder()}});p(a,"Accessibility/Accessibility.js",[a["Accessibility/Utils/ChartUtilities.js"],a["Core/Globals.js"],a["Accessibility/KeyboardNavigationHandler.js"],a["Series/Line/LineSeries.js"],a["Core/Options.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"],a["Accessibility/AccessibilityComponent.js"],
a["Accessibility/KeyboardNavigation.js"],a["Accessibility/Components/LegendComponent.js"],a["Accessibility/Components/MenuComponent.js"],a["Accessibility/Components/SeriesComponent/SeriesComponent.js"],a["Accessibility/Components/ZoomComponent.js"],a["Accessibility/Components/RangeSelectorComponent.js"],a["Accessibility/Components/InfoRegionsComponent.js"],a["Accessibility/Components/ContainerComponent.js"],a["Accessibility/HighContrastMode.js"],a["Accessibility/HighContrastTheme.js"],a["Accessibility/Options/Options.js"],
a["Accessibility/Options/LangOptions.js"],a["Accessibility/Options/DeprecatedOptions.js"]],function(a,f,l,n,m,k,g,p,e,d,c,b,h,t,u,x,I,A,F,B,C){function q(a){this.init(a)}var r=f.doc,v=g.addEvent,w=g.extend,D=g.fireEvent,G=g.merge;G(!0,m.defaultOptions,F,{accessibility:{highContrastTheme:A},lang:B});f.A11yChartUtilities=a;f.KeyboardNavigationHandler=l;f.AccessibilityComponent=p;q.prototype={init:function(a){this.chart=a;r.addEventListener&&a.renderer.isSVG?(C(a),this.initComponents(),this.keyboardNavigation=
new e(a,this.components),this.update()):a.renderTo.setAttribute("aria-hidden",!0)},initComponents:function(){var a=this.chart,e=a.options.accessibility;this.components={container:new x,infoRegions:new u,legend:new d,chartMenu:new c,rangeSelector:new t,series:new b,zoom:new h};e.customComponents&&w(this.components,e.customComponents);var f=this.components;this.getComponentOrder().forEach(function(b){f[b].initBase(a);f[b].init()})},getComponentOrder:function(){if(!this.components)return[];if(!this.components.series)return Object.keys(this.components);
var a=Object.keys(this.components).filter(function(a){return"series"!==a});return["series"].concat(a)},update:function(){var a=this.components,b=this.chart,c=b.options.accessibility;D(b,"beforeA11yUpdate");b.types=this.getChartTypes();this.getComponentOrder().forEach(function(c){a[c].onChartUpdate();D(b,"afterA11yComponentUpdate",{name:c,component:a[c]})});this.keyboardNavigation.update(c.keyboardNavigation.order);!b.highContrastModeActive&&I.isHighContrastModeActive()&&I.setHighContrastTheme(b);
D(b,"afterA11yUpdate",{accessibility:this})},destroy:function(){var a=this.chart||{},b=this.components;Object.keys(b).forEach(function(a){b[a].destroy();b[a].destroyBase()});this.keyboardNavigation&&this.keyboardNavigation.destroy();a.renderTo&&a.renderTo.setAttribute("aria-hidden",!0);a.focusElement&&a.focusElement.removeFocusBorder()},getChartTypes:function(){var a={};this.chart.series.forEach(function(b){a[b.type]=1});return Object.keys(a)}};f.Chart.prototype.updateA11yEnabled=function(){var a=
this.accessibility,b=this.options.accessibility;b&&b.enabled?a?a.update():this.accessibility=new q(this):a?(a.destroy&&a.destroy(),delete this.accessibility):this.renderTo.setAttribute("aria-hidden",!0)};v(f.Chart,"render",function(a){this.a11yDirty&&this.renderTo&&(delete this.a11yDirty,this.updateA11yEnabled());var b=this.accessibility;b&&b.getComponentOrder().forEach(function(a){b.components[a].onChartRender()})});v(f.Chart,"update",function(a){if(a=a.options.accessibility)a.customComponents&&
(this.options.accessibility.customComponents=a.customComponents,delete a.customComponents),G(!0,this.options.accessibility,a),this.accessibility&&this.accessibility.destroy&&(this.accessibility.destroy(),delete this.accessibility);this.a11yDirty=!0});v(k,"update",function(){this.series.chart.accessibility&&(this.series.chart.a11yDirty=!0)});["addSeries","init"].forEach(function(a){v(f.Chart,a,function(){this.a11yDirty=!0})});["update","updatedData","remove"].forEach(function(a){v(n,a,function(){this.chart.accessibility&&
(this.chart.a11yDirty=!0)})});["afterDrilldown","drillupall"].forEach(function(a){v(f.Chart,a,function(){this.accessibility&&this.accessibility.update()})});v(f.Chart,"destroy",function(){this.accessibility&&this.accessibility.destroy()})});p(a,"masters/modules/accessibility.src.js",[],function(){})});
//# sourceMappingURL=accessibility.js.map