/*
 Highcharts JS v8.2.2 (2020-11-23)

 (c) 2009-2019 Sebastian Bochan, Rafal Sebestjanski

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/dumbbell",["highcharts"],function(e){b(e);b.Highcharts=e;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function e(b,d,e,k){b.hasOwnProperty(d)||(b[d]=k.apply(null,e))}b=b?b._modules:{};e(b,"Series/ColumnRangeSeries.js",[b["Core/Series/Series.js"],b["Series/Column/ColumnSeries.js"],b["Core/Globals.js"],b["Core/Options.js"],
b["Core/Utilities.js"]],function(b,d,e,k,r){var c=d.prototype;d=e.noop;k=k.defaultOptions;var t=r.clamp,u=r.merge,p=r.pick,v=b.seriesTypes.arearange.prototype;b.seriesType("columnrange","arearange",u(k.plotOptions.column,k.plotOptions.arearange,{pointRange:null,marker:null,states:{hover:{halo:!1}}}),{setOptions:function(){u(!0,arguments[0],{stacking:void 0});return v.setOptions.apply(this,arguments)},translate:function(){var b=this,d=b.yAxis,h=b.xAxis,a=h.startAngleRad,w,l=b.chart,A=b.xAxis.isRadial,
f=Math.max(l.chartWidth,l.chartHeight)+999,x;c.translate.apply(b);b.points.forEach(function(m){var c=m.shapeArgs,e=b.options.minPointLength;m.plotHigh=x=t(d.translate(m.high,0,1,0,1),-f,f);m.plotLow=t(m.plotY,-f,f);var n=x;var g=p(m.rectPlotY,m.plotY)-x;Math.abs(g)<e?(e-=g,g+=e,n-=e/2):0>g&&(g*=-1,n-=g);A?(w=m.barX+a,m.shapeType="arc",m.shapeArgs=b.polarArc(n+g,n,w,w+m.pointWidth)):(c.height=g,c.y=n,m.tooltipPos=l.inverted?[d.len+d.pos-l.plotLeft-n-g/2,h.len+h.pos-l.plotTop-c.x-c.width/2,g]:[h.left-
l.plotLeft+c.x+c.width/2,d.pos-l.plotTop+n+g/2,g])})},directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:d,getSymbol:d,crispCol:function(){return c.crispCol.apply(this,arguments)},drawPoints:function(){return c.drawPoints.apply(this,arguments)},drawTracker:function(){return c.drawTracker.apply(this,arguments)},getColumnMetrics:function(){return c.getColumnMetrics.apply(this,arguments)},pointAttribs:function(){return c.pointAttribs.apply(this,arguments)},adjustForMissingColumns:function(){return c.adjustForMissingColumns.apply(this,
arguments)},animate:function(){return c.animate.apply(this,arguments)},polarArc:function(){return c.polarArc.apply(this,arguments)},translate3dPoints:function(){return c.translate3dPoints.apply(this,arguments)},translate3dShapes:function(){return c.translate3dShapes.apply(this,arguments)}},{setState:c.pointClass.prototype.setState});""});e(b,"Series/DumbbellSeries.js",[b["Core/Series/Series.js"],b["Series/Column/ColumnSeries.js"],b["Series/Line/LineSeries.js"],b["Core/Color/Palette.js"],b["Core/Renderer/SVG/SVGRenderer.js"],
b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,d,e,k,r,c,t){var u=b.seriesTypes,p=u.arearange.prototype,v=d.prototype,z=e.prototype,y=t.extend,h=t.pick;d=p.pointClass.prototype;b.seriesType("dumbbell","arearange",{trackByArea:!1,fillColor:"none",lineWidth:0,pointRange:1,connectorWidth:1,stickyTracking:!1,groupPadding:.2,crisp:!1,pointPadding:.1,lowColor:k.neutralColor80,states:{hover:{lineWidthPlus:0,connectorWidthPlus:1,halo:!1}}},{trackerGroups:["group","markerGroup","dataLabelsGroup"],
drawTracker:c.TrackerMixin.drawTrackerPoint,drawGraph:c.noop,crispCol:v.crispCol,getConnectorAttribs:function(a){var b=this.chart,l=a.options,c=this.options,f=this.xAxis,d=this.yAxis,e=h(l.connectorWidth,c.connectorWidth),k=h(l.connectorColor,c.connectorColor,l.color,a.zone?a.zone.color:void 0,a.color),p=h(c.states&&c.states.hover&&c.states.hover.connectorWidthPlus,1),n=h(l.dashStyle,c.dashStyle),g=h(a.plotLow,a.plotY),q=d.toPixels(c.threshold||0,!0);q=h(a.plotHigh,b.inverted?d.len-q:q);a.state&&
(e+=p);0>g?g=0:g>=d.len&&(g=d.len);0>q?q=0:q>=d.len&&(q=d.len);if(0>a.plotX||a.plotX>f.len)e=0;a.upperGraphic&&(f={y:a.y,zone:a.zone},a.y=a.high,a.zone=a.zone?a.getZone():void 0,k=h(l.connectorColor,c.connectorColor,l.color,a.zone?a.zone.color:void 0,a.color),y(a,f));a={d:r.prototype.crispLine([["M",a.plotX,g],["L",a.plotX,q]],e,"ceil")};b.styledMode||(a.stroke=k,a["stroke-width"]=e,n&&(a.dashstyle=n));return a},drawConnector:function(a){var b=h(this.options.animationLimit,250);b=a.connector&&this.chart.pointCount<
b?"animate":"attr";a.connector||(a.connector=this.chart.renderer.path().addClass("highcharts-lollipop-stem").attr({zIndex:-1}).add(this.markerGroup));a.connector[b](this.getConnectorAttribs(a))},getColumnMetrics:function(){var a=v.getColumnMetrics.apply(this,arguments);a.offset+=a.width/2;return a},translatePoint:p.translate,setShapeArgs:u.columnrange.prototype.translate,translate:function(){this.setShapeArgs.apply(this);this.translatePoint.apply(this,arguments);this.points.forEach(function(a){var b=
a.shapeArgs,c=a.pointWidth;a.plotX=b.x;b.x=a.plotX-c/2;a.tooltipPos=null});this.columnMetrics.offset-=this.columnMetrics.width/2},seriesDrawPoints:p.drawPoints,drawPoints:function(){var a=this.chart,b=this.points.length,c=this.lowColor=this.options.lowColor,d=0;for(this.seriesDrawPoints.apply(this,arguments);d<b;){var f=this.points[d];this.drawConnector(f);f.upperGraphic&&(f.upperGraphic.element.point=f,f.upperGraphic.addClass("highcharts-lollipop-high"));f.connector.element.point=f;if(f.lowerGraphic){var e=
f.zone&&f.zone.color;e=h(f.options.lowColor,c,f.options.color,e,f.color,this.color);a.styledMode||f.lowerGraphic.attr({fill:e});f.lowerGraphic.addClass("highcharts-lollipop-low")}d++}},markerAttribs:function(){var a=p.markerAttribs.apply(this,arguments);a.x=Math.floor(a.x);a.y=Math.floor(a.y);return a},pointAttribs:function(a,b){var c=z.pointAttribs.apply(this,arguments);"hover"===b&&delete c.fill;return c}},{destroyElements:d.destroyElements,isValid:d.isValid,pointSetState:d.setState,setState:function(){var a=
this.series,b=a.chart,c=a.options.marker,d=this.options,e=h(d.lowColor,a.options.lowColor,d.color,this.zone&&this.zone.color,this.color,a.color),k="attr";this.pointSetState.apply(this,arguments);this.state||(k="animate",this.lowerGraphic&&!b.styledMode&&(this.lowerGraphic.attr({fill:e}),this.upperGraphic&&(b={y:this.y,zone:this.zone},this.y=this.high,this.zone=this.zone?this.getZone():void 0,c=h(this.marker?this.marker.fillColor:void 0,c?c.fillColor:void 0,d.color,this.zone?this.zone.color:void 0,
this.color),this.upperGraphic.attr({fill:c}),y(this,b))));this.connector[k](a.getConnectorAttribs(this))}});""});e(b,"masters/modules/dumbbell.src.js",[],function(){})});
//# sourceMappingURL=dumbbell.js.map