/*
 Highcharts JS v8.2.2 (2020-11-23)

 Highcharts funnel module

 (c) 2010-2019 Kacper Madej

 License: www.highcharts.com/license
*/
(function(d){"object"===typeof module&&module.exports?(d["default"]=d,module.exports=d):"function"===typeof define&&define.amd?define("highcharts/modules/funnel3d",["highcharts","highcharts/highcharts-3d","highcharts/modules/cylinder"],function(k){d(k);d.Highcharts=k;return d}):d("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(d){function k(d,l,n,p){d.hasOwnProperty(l)||(d[l]=p.apply(null,n))}d=d?d._modules:{};k(d,"Series/Funnel3DSeries.js",[d["Core/Series/Series.js"],d["Core/Color/Color.js"],
d["Core/Globals.js"],d["Extensions/Math3D.js"],d["Core/Utilities.js"]],function(d,l,n,p,h){var k=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return b(a,c)};return function(a,c){function e(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),I=d.seriesTypes,y=I.column,J=I.line,x=l.parse,K=n.charts;
l=n.Renderer.prototype;var L=l.cuboidPath;l=l.elements3d;var M=p.perspective,N=h.error,E=h.extend,q=h.merge,F=h.pick,B=h.relativeLength;p=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.center=void 0;a.data=void 0;a.options=void 0;a.points=void 0;return a}k(a,b);a.prototype.alignDataLabel=function(a,b,f){var c=a.dlBoxRaw,e=this.chart.inverted,m=a.plotY>F(this.translatedThreshold,this.yAxis.len),d=F(f.inside,!!this.options.stacking),g={x:c.x,y:c.y,height:0};f.align=F(f.align,
!e||d?"center":m?"right":"left");f.verticalAlign=F(f.verticalAlign,e||d?"middle":m?"top":"bottom");"top"!==f.verticalAlign&&(g.y+=c.bottom/("bottom"===f.verticalAlign?1:2));g.width=this.getWidthAt(g.y);this.options.reversed&&(g.width=c.fullWidth-g.width);d?g.x-=g.width/2:"left"===f.align?(f.align="right",g.x-=1.5*g.width):"right"===f.align?(f.align="left",g.x+=g.width/2):g.x-=g.width/2;a.dlBox=g;y.prototype.alignDataLabel.apply(this,arguments)};a.prototype.bindAxes=function(){J.prototype.bindAxes.apply(this,
arguments);E(this.xAxis.options,{gridLineWidth:0,lineWidth:0,title:null,tickPositions:[]});E(this.yAxis.options,{gridLineWidth:0,title:null,labels:{enabled:!1}})};a.prototype.translate=function(){J.prototype.translate.apply(this,arguments);var a=0,b=this.chart,f=this.options,D=f.reversed,d=f.ignoreHiddenPoint,m=b.plotWidth,H=b.plotHeight,g=0,q=f.center,r=B(q[0],m),C=B(q[1],H),l=B(f.width,m),u,k,v=B(f.height,H),n=B(f.neckWidth,m),p=B(f.neckHeight,H),h=C-v/2+v-p;m=this.data;var z,x,w,A,y,G,t;this.getWidthAt=
k=function(a){var b=C-v/2;return a>h||v===p?n:n+(l-n)*(1-(a-b)/(v-p))};this.center=[r,C,v];this.centerX=r;m.forEach(function(b){d&&!1===b.visible||(a+=b.y)});m.forEach(function(c){y=null;z=a?c.y/a:0;w=C-v/2+g*v;A=w+z*v;u=k(w);G=A-w;t={gradientForSides:F(c.options.gradientForSides,f.gradientForSides),x:r,y:w,height:G,width:u,z:1,top:{width:u}};u=k(A);t.bottom={fraction:z,width:u};w>=h?t.isCylinder=!0:A>h&&(y=A,u=k(h),A=h,t.bottom.width=u,t.middle={fraction:G?(h-w)/G:0,width:u});D&&(t.y=w=C+v/2-(g+
z)*v,t.middle&&(t.middle.fraction=1-(G?t.middle.fraction:0)),u=t.width,t.width=t.bottom.width,t.bottom.width=u);c.shapeArgs=E(c.shapeArgs,t);c.percentage=100*z;c.plotX=r;c.plotY=D?C+v/2-(g+z/2)*v:(w+(y||A))/2;x=M([{x:r,y:c.plotY,z:D?-(l-k(c.plotY))/2:-k(c.plotY)/2}],b,!0)[0];c.tooltipPos=[x.x,x.y];c.dlBoxRaw={x:r,width:k(c.plotY),y:w,bottom:t.height,fullWidth:l};d&&!1===c.visible||(g+=z)})};a.defaultOptions=q(y.defaultOptions,{center:["50%","50%"],width:"90%",neckWidth:"30%",height:"100%",neckHeight:"25%",
reversed:!1,gradientForSides:!0,animation:!1,edgeWidth:0,colorByPoint:!0,showInLegend:!1,dataLabels:{align:"right",crop:!1,inside:!1,overflow:"allow"}});return a}(y);E(p.prototype,{translate3dShapes:n.noop});h=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.dlBoxRaw=void 0;a.options=void 0;a.series=void 0;a.y=void 0;return a}k(a,b);return a}(y.prototype.pointClass);p.prototype.pointClass=h;E(h.prototype,{shapeType:"funnel3d"});l.funnel3d=q(l.cuboid,{parts:"top bottom frontUpper backUpper frontLower backLower rightUpper rightLower".split(" "),
mainParts:["top","bottom"],sideGroups:["upperGroup","lowerGroup"],sideParts:{upperGroup:["frontUpper","backUpper","rightUpper"],lowerGroup:["frontLower","backLower","rightLower"]},pathType:"funnel3d",opacitySetter:function(b){var a=this,c=a.parts,e=n.charts[a.renderer.chartIndex],f="group-opacity-"+b+"-"+e.index;a.parts=a.mainParts;a.singleSetterForParts("opacity",b);a.parts=c;e.renderer.filterId||(e.renderer.definition({tagName:"filter",id:f,children:[{tagName:"feComponentTransfer",children:[{tagName:"feFuncA",
type:"table",tableValues:"0 "+b}]}]}),a.sideGroups.forEach(function(b){a[b].attr({filter:"url(#"+f+")"})}),a.renderer.styledMode&&(e.renderer.definition({tagName:"style",textContent:".highcharts-"+f+" {filter:url(#"+f+")}"}),a.sideGroups.forEach(function(a){a.addClass("highcharts-"+f)})));return a},fillSetter:function(b){var a=this,c=x(b),e=c.rgba[3],f={top:x(b).brighten(.1).get(),bottom:x(b).brighten(-.2).get()};1>e?(c.rgba[3]=1,c=c.get("rgb"),a.attr({opacity:e})):c=b;c.linearGradient||c.radialGradient||
!a.gradientForSides||(c={linearGradient:{x1:0,x2:1,y1:1,y2:1},stops:[[0,x(b).brighten(-.2).get()],[.5,b],[1,x(b).brighten(-.2).get()]]});c.linearGradient?a.sideGroups.forEach(function(b){var e=a[b].gradientBox,d=c.linearGradient,D=q(c,{linearGradient:{x1:e.x+d.x1*e.width,y1:e.y+d.y1*e.height,x2:e.x+d.x2*e.width,y2:e.y+d.y2*e.height}});a.sideParts[b].forEach(function(a){f[a]=D})}):(q(!0,f,{frontUpper:c,backUpper:c,rightUpper:c,frontLower:c,backLower:c,rightLower:c}),c.radialGradient&&a.sideGroups.forEach(function(b){var c=
a[b].gradientBox,f=c.x+c.width/2,e=c.y+c.height/2,d=Math.min(c.width,c.height);a.sideParts[b].forEach(function(b){a[b].setRadialReference([f,e,d])})}));a.singleSetterForParts("fill",null,f);a.color=a.fill=b;c.linearGradient&&[a.frontLower,a.frontUpper].forEach(function(b){(b=(b=b.element)&&a.renderer.gradients[b.gradient])&&"userSpaceOnUse"!==b.attr("gradientUnits")&&b.attr({gradientUnits:"userSpaceOnUse"})});return a},adjustForGradient:function(){var b=this,a;b.sideGroups.forEach(function(c){var e=
{x:Number.MAX_VALUE,y:Number.MAX_VALUE},f={x:-Number.MAX_VALUE,y:-Number.MAX_VALUE};b.sideParts[c].forEach(function(c){a=b[c].getBBox(!0);e={x:Math.min(e.x,a.x),y:Math.min(e.y,a.y)};f={x:Math.max(f.x,a.x+a.width),y:Math.max(f.y,a.y+a.height)}});b[c].gradientBox={x:e.x,width:f.x-e.x,y:e.y,height:f.y-e.y}})},zIndexSetter:function(){this.finishedOnAdd&&this.adjustForGradient();return this.renderer.Element.prototype.zIndexSetter.apply(this,arguments)},onAdd:function(){this.adjustForGradient();this.finishedOnAdd=
!0}});n.Renderer.prototype.funnel3d=function(b){var a=this.element3d("funnel3d",b),c=this.styledMode,e={"stroke-width":1,stroke:"none"};a.upperGroup=this.g("funnel3d-upper-group").attr({zIndex:a.frontUpper.zIndex}).add(a);[a.frontUpper,a.backUpper,a.rightUpper].forEach(function(b){c||b.attr(e);b.add(a.upperGroup)});a.lowerGroup=this.g("funnel3d-lower-group").attr({zIndex:a.frontLower.zIndex}).add(a);[a.frontLower,a.backLower,a.rightLower].forEach(function(b){c||b.attr(e);b.add(a.lowerGroup)});a.gradientForSides=
b.gradientForSides;return a};n.Renderer.prototype.funnel3dPath=function(b){this.getCylinderEnd||N("A required Highcharts module is missing: cylinder.js",!0,K[this.chartIndex]);var a=K[this.chartIndex],c=b.alphaCorrection=90-Math.abs(a.options.chart.options3d.alpha%180-90),e=L.call(this,q(b,{depth:b.width,width:(b.width+b.bottom.width)/2})),f=e.isTop,d=!e.isFront,k=!!b.middle,m=this.getCylinderEnd(a,q(b,{x:b.x-b.width/2,z:b.z-b.width/2,alphaCorrection:c})),h=b.bottom.width,g=q(b,{width:h,x:b.x-h/2,
z:b.z-h/2,alphaCorrection:c}),l=this.getCylinderEnd(a,g,!0),r=h,n=g,p=l,u=l;k&&(r=b.middle.width,n=q(b,{y:b.y+b.middle.fraction*b.height,width:r,x:b.x-r/2,z:b.z-r/2}),p=this.getCylinderEnd(a,n,!1),u=this.getCylinderEnd(a,n,!1));e={top:m,bottom:l,frontUpper:this.getCylinderFront(m,p),zIndexes:{group:e.zIndexes.group,top:0!==f?0:3,bottom:1!==f?0:3,frontUpper:d?2:1,backUpper:d?1:2,rightUpper:d?2:1}};e.backUpper=this.getCylinderBack(m,p);m=1!==Math.min(r,b.width)/Math.max(r,b.width);e.rightUpper=this.getCylinderFront(this.getCylinderEnd(a,
q(b,{x:b.x-b.width/2,z:b.z-b.width/2,alphaCorrection:m?-c:0}),!1),this.getCylinderEnd(a,q(n,{alphaCorrection:m?-c:0}),!k));k&&(m=1!==Math.min(r,h)/Math.max(r,h),q(!0,e,{frontLower:this.getCylinderFront(u,l),backLower:this.getCylinderBack(u,l),rightLower:this.getCylinderFront(this.getCylinderEnd(a,q(g,{alphaCorrection:m?-c:0}),!0),this.getCylinderEnd(a,q(n,{alphaCorrection:m?-c:0}),!1)),zIndexes:{frontLower:d?2:1,backLower:d?1:2,rightLower:d?1:2}}));return e};d.registerSeriesType("funnel3d",p);"";
return p});k(d,"masters/modules/funnel3d.src.js",[],function(){})});
//# sourceMappingURL=funnel3d.js.map