/*
 Highcharts Gantt JS v8.2.2 (2020-11-23)

 Gantt series

 (c) 2016-2019 Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(d){"object"===typeof module&&module.exports?(d["default"]=d,module.exports=d):"function"===typeof define&&define.amd?define("highcharts/modules/gantt",["highcharts"],function(J){d(J);d.Highcharts=J;return d}):d("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(d){function J(d,x,r,w){d.hasOwnProperty(x)||(d[x]=w.apply(null,r))}d=d?d._modules:{};J(d,"Gantt/Tree.js",[d["Core/Utilities.js"]],function(d){var x=d.extend,r=d.isNumber,w=d.pick,t=function(d,A){var c=d.reduce(function(c,
k){var q=w(k.parent,"");"undefined"===typeof c[q]&&(c[q]=[]);c[q].push(k);return c},{});Object.keys(c).forEach(function(n,k){var q=c[n];""!==n&&-1===A.indexOf(n)&&(q.forEach(function(c){k[""].push(c)}),delete k[n])});return c},z=function(d,A,c,n,k,q){var p=0,I=0,g=q&&q.after,e=q&&q.before;A={data:n,depth:c-1,id:d,level:c,parent:A};var G,E;"function"===typeof e&&e(A,q);e=(k[d]||[]).map(function(f){var a=z(f.id,d,c+1,f,k,q),b=f.start;f=!0===f.milestone?b:f.end;G=!r(G)||b<G?b:G;E=!r(E)||f>E?f:E;p=p+
1+a.descendants;I=Math.max(a.height+1,I);return a});n&&(n.start=w(n.start,G),n.end=w(n.end,E));x(A,{children:e,descendants:p,height:I});"function"===typeof g&&g(A,q);return A};return{getListOfParents:t,getNode:z,getTree:function(d,A){var c=d.map(function(c){return c.id});d=t(d,c);return z("",null,1,null,d,A)}}});J(d,"Core/Axis/TreeGridTick.js",[d["Core/Color/Palette.js"],d["Core/Utilities.js"]],function(d,x){var r=x.addEvent,w=x.defined,t=x.isObject,z=x.isNumber,B=x.pick,A=x.wrap,c;(function(c){function k(){this.treeGrid||
(this.treeGrid=new e(this))}function q(e,g){e=e.treeGrid;var f=!e.labelIcon,a=g.renderer,b=g.xy,h=g.options,F=h.width,u=h.height,m=b.x-F/2-h.padding;b=b.y-u/2;var C=g.collapsed?90:180,y=g.show&&z(b),D=e.labelIcon;D||(e.labelIcon=D=a.path(a.symbols[h.type](h.x,h.y,F,u)).addClass("highcharts-label-icon").add(g.group));y||D.attr({y:-9999});a.styledMode||D.attr({"stroke-width":1,fill:B(g.color,d.neutralColor60)}).css({cursor:"pointer",stroke:h.lineColor,strokeWidth:h.lineWidth});D[f?"attr":"animate"]({translateX:m,
translateY:b,rotation:C})}function p(e,g,f,a,b,h,F,u,m){var C=B(this.options&&this.options.labels,h);h=this.pos;var y=this.axis,D="treegrid"===y.options.type;e=e.apply(this,[g,f,a,b,C,F,u,m]);D&&(g=C&&t(C.symbol,!0)?C.symbol:{},C=C&&z(C.indentation)?C.indentation:0,h=(h=(y=y.treeGrid.mapOfPosToGridNode)&&y[h])&&h.depth||1,e.x+=g.width+2*g.padding+(h-1)*C);return e}function I(e){var g=this,f=g.pos,a=g.axis,b=g.label,h=a.treeGrid.mapOfPosToGridNode,F=a.options,u=B(g.options&&g.options.labels,F&&F.labels),
m=u&&t(u.symbol,!0)?u.symbol:{},C=(h=h&&h[f])&&h.depth;F="treegrid"===F.type;var y=-1<a.tickPositions.indexOf(f);f=a.chart.styledMode;F&&h&&b&&b.element&&b.addClass("highcharts-treegrid-node-level-"+C);e.apply(g,Array.prototype.slice.call(arguments,1));F&&b&&b.element&&h&&h.descendants&&0<h.descendants&&(a=a.treeGrid.isCollapsed(h),q(g,{color:!f&&b.styles&&b.styles.color||"",collapsed:a,group:b.parentGroup,options:m,renderer:b.renderer,show:y,xy:b.xy}),m="highcharts-treegrid-node-"+(a?"expanded":
"collapsed"),b.addClass("highcharts-treegrid-node-"+(a?"collapsed":"expanded")).removeClass(m),f||b.css({cursor:"pointer"}),[b,g.treeGrid.labelIcon].forEach(function(a){a&&!a.attachedTreeGridEvents&&(r(a.element,"mouseover",function(){b.addClass("highcharts-treegrid-node-active");b.renderer.styledMode||b.css({textDecoration:"underline"})}),r(a.element,"mouseout",function(){var a=w(u.style)?u.style:{};b.removeClass("highcharts-treegrid-node-active");b.renderer.styledMode||b.css({textDecoration:a.textDecoration})}),
r(a.element,"click",function(){g.treeGrid.toggleCollapse()}),a.attachedTreeGridEvents=!0)}))}var g=!1;c.compose=function(e){g||(r(e,"init",k),A(e.prototype,"getLabelPosition",p),A(e.prototype,"renderLabel",I),e.prototype.collapse=function(e){this.treeGrid.collapse(e)},e.prototype.expand=function(e){this.treeGrid.expand(e)},e.prototype.toggleCollapse=function(e){this.treeGrid.toggleCollapse(e)},g=!0)};var e=function(){function e(e){this.tick=e}e.prototype.collapse=function(e){var f=this.tick,a=f.axis,
b=a.brokenAxis;b&&a.treeGrid.mapOfPosToGridNode&&(f=a.treeGrid.collapse(a.treeGrid.mapOfPosToGridNode[f.pos]),b.setBreaks(f,B(e,!0)))};e.prototype.expand=function(e){var f=this.tick,a=f.axis,b=a.brokenAxis;b&&a.treeGrid.mapOfPosToGridNode&&(f=a.treeGrid.expand(a.treeGrid.mapOfPosToGridNode[f.pos]),b.setBreaks(f,B(e,!0)))};e.prototype.toggleCollapse=function(e){var f=this.tick,a=f.axis,b=a.brokenAxis;b&&a.treeGrid.mapOfPosToGridNode&&(f=a.treeGrid.toggleCollapse(a.treeGrid.mapOfPosToGridNode[f.pos]),
b.setBreaks(f,B(e,!0)))};return e}();c.Additions=e})(c||(c={}));return c});J(d,"Mixins/TreeSeries.js",[d["Core/Color/Color.js"],d["Core/Utilities.js"]],function(d,x){var r=x.extend,w=x.isArray,t=x.isNumber,z=x.isObject,B=x.merge,A=x.pick;return{getColor:function(c,n){var k=n.index,q=n.mapOptionsToLevel,p=n.parentColor,I=n.parentColorIndex,g=n.series,e=n.colors,G=n.siblings,E=g.points,f=g.chart.options.chart,a;if(c){E=E[c.i];c=q[c.level]||{};if(q=E&&c.colorByPoint){var b=E.index%(e?e.length:f.colorCount);
var h=e&&e[b]}if(!g.chart.styledMode){e=E&&E.options.color;f=c&&c.color;if(a=p)a=(a=c&&c.colorVariation)&&"brightness"===a.key?d.parse(p).brighten(k/G*a.to).get():p;a=A(e,f,h,a,g.color)}var F=A(E&&E.options.colorIndex,c&&c.colorIndex,b,I,n.colorIndex)}return{color:a,colorIndex:F}},getLevelOptions:function(c){var n=null;if(z(c)){n={};var k=t(c.from)?c.from:1;var q=c.levels;var p={};var I=z(c.defaults)?c.defaults:{};w(q)&&(p=q.reduce(function(g,e){if(z(e)&&t(e.level)){var c=B({},e);var p="boolean"===
typeof c.levelIsConstant?c.levelIsConstant:I.levelIsConstant;delete c.levelIsConstant;delete c.level;e=e.level+(p?0:k-1);z(g[e])?r(g[e],c):g[e]=c}return g},{}));q=t(c.to)?c.to:1;for(c=0;c<=q;c++)n[c]=B({},I,z(p[c])?p[c]:{})}return n},setTreeValues:function q(n,k){var p=k.before,I=k.idRoot,g=k.mapIdToNode[I],e=k.points[n.i],G=e&&e.options||{},E=0,f=[];r(n,{levelDynamic:n.level-(("boolean"===typeof k.levelIsConstant?k.levelIsConstant:1)?0:g.level),name:A(e&&e.name,""),visible:I===n.id||("boolean"===
typeof k.visible?k.visible:!1)});"function"===typeof p&&(n=p(n,k));n.children.forEach(function(a,b){var h=r({},k);r(h,{index:b,siblings:n.children.length,visible:n.visible});a=q(a,h);f.push(a);a.visible&&(E+=a.val)});n.visible=0<E||n.visible;p=A(G.value,E);r(n,{children:f,childrenTotal:E,isLeaf:n.visible&&!E,val:p});return n},updateRootId:function(n){if(z(n)){var k=z(n.options)?n.options:{};k=A(n.rootNode,k.rootId,"");z(n.userOptions)&&(n.userOptions.rootId=k);n.rootNode=k}return k}}});J(d,"Core/Axis/GridAxis.js",
[d["Core/Axis/Axis.js"],d["Core/Globals.js"],d["Core/Axis/Tick.js"],d["Core/Utilities.js"]],function(d,x,r,w){var t=w.addEvent,z=w.defined,B=w.erase,A=w.find,c=w.isArray,n=w.isNumber,k=w.merge,q=w.pick,p=w.timeUnits,I=w.wrap,g=x.Chart,e=function(f){var a=f.options;a.labels||(a.labels={});a.labels.align=q(a.labels.align,"center");f.categories||(a.showLastLabel=!1);f.labelRotation=0;a.labels.rotation=0};"";d.prototype.getMaxLabelDimensions=function(f,a){var b={width:0,height:0};a.forEach(function(a){a=
f[a];if(w.isObject(a,!0)){var h=w.isObject(a.label,!0)?a.label:{};a=h.getBBox?h.getBBox().height:0;h.textStr&&!n(h.textPxLength)&&(h.textPxLength=h.getBBox().width);var u=n(h.textPxLength)?Math.round(h.textPxLength):0;h.textStr&&(u=Math.round(h.getBBox().width));b.height=Math.max(a,b.height);b.width=Math.max(u,b.width)}});return b};x.dateFormats.W=function(f){f=new this.Date(f);var a=(this.get("Day",f)+6)%7,b=new this.Date(f.valueOf());this.set("Date",b,this.get("Date",f)-a+3);a=new this.Date(this.get("FullYear",
b),0,1);4!==this.get("Day",a)&&(this.set("Month",f,0),this.set("Date",f,1+(11-this.get("Day",a))%7));return(1+Math.floor((b.valueOf()-a.valueOf())/6048E5)).toString()};x.dateFormats.E=function(f){return this.dateFormat("%a",f,!0).charAt(0)};t(g,"afterSetChartSize",function(){this.axes.forEach(function(f){(f.grid&&f.grid.columns||[]).forEach(function(a){a.setAxisSize();a.setAxisTranslation()})})});t(r,"afterGetLabelPosition",function(f){var a=this.label,b=this.axis,h=b.reversed,e=b.chart,u=b.options.grid||
{},m=b.options.labels,C=m.align,y=E.Side[b.side],g=f.tickmarkOffset,c=b.tickPositions,L=this.pos-g;c=n(c[f.index+1])?c[f.index+1]-g:b.max+g;var H=b.tickSize("tick");g=H?H[0]:0;H=H?H[1]/2:0;if(!0===u.enabled){if("top"===y){u=b.top+b.offset;var l=u-g}else"bottom"===y?(l=e.chartHeight-b.bottom+b.offset,u=l+g):(u=b.top+b.len-b.translate(h?c:L),l=b.top+b.len-b.translate(h?L:c));"right"===y?(y=e.chartWidth-b.right+b.offset,h=y+g):"left"===y?(h=b.left+b.offset,y=h-g):(y=Math.round(b.left+b.translate(h?c:
L))-H,h=Math.round(b.left+b.translate(h?L:c))-H);this.slotWidth=h-y;f.pos.x="left"===C?y:"right"===C?h:y+(h-y)/2;f.pos.y=l+(u-l)/2;e=e.renderer.fontMetrics(m.style.fontSize,a.element);a=a.getBBox().height;m.useHTML?f.pos.y+=e.b+-(a/2):(a=Math.round(a/e.h),f.pos.y+=(e.b-(e.h-e.f))/2+-((a-1)*e.h/2));f.pos.x+=b.horiz&&m.x||0}});var G=function(){function f(a){this.axis=a}f.prototype.isOuterAxis=function(){var a=this.axis,b=a.grid.columnIndex,h=a.linkedParent&&a.linkedParent.grid.columns||a.grid.columns,
f=b?a.linkedParent:a,e=-1,m=0;a.chart[a.coll].forEach(function(b,h){b.side!==a.side||b.options.isInternal||(m=h,b===f&&(e=h))});return m===e&&(n(b)?h.length===b:!0)};f.prototype.renderBorder=function(a){var b=this.axis,h=b.chart.renderer,f=b.options;a=h.path(a).addClass("highcharts-axis-line").add(b.axisBorder);h.styledMode||a.attr({stroke:f.lineColor,"stroke-width":f.lineWidth,zIndex:7});return a};return f}(),E=function(){function f(){}f.compose=function(a){d.keepProps.push("grid");I(a.prototype,
"unsquish",f.wrapUnsquish);t(a,"init",f.onInit);t(a,"afterGetOffset",f.onAfterGetOffset);t(a,"afterGetTitlePosition",f.onAfterGetTitlePosition);t(a,"afterInit",f.onAfterInit);t(a,"afterRender",f.onAfterRender);t(a,"afterSetAxisTranslation",f.onAfterSetAxisTranslation);t(a,"afterSetOptions",f.onAfterSetOptions);t(a,"afterSetOptions",f.onAfterSetOptions2);t(a,"afterSetScale",f.onAfterSetScale);t(a,"afterTickSize",f.onAfterTickSize);t(a,"trimTicks",f.onTrimTicks);t(a,"destroy",f.onDestroy)};f.onAfterGetOffset=
function(){var a=this.grid;(a&&a.columns||[]).forEach(function(a){a.getOffset()})};f.onAfterGetTitlePosition=function(a){if(!0===(this.options.grid||{}).enabled){var b=this.axisTitle,h=this.height,e=this.horiz,u=this.left,m=this.offset,g=this.opposite,y=this.options.title,c=void 0===y?{}:y;y=this.top;var k=this.width,L=this.tickSize(),H=b&&b.getBBox().width,l=c.x||0,v=c.y||0,K=q(c.margin,e?5:10);b=this.chart.renderer.fontMetrics(c.style&&c.style.fontSize,b).f;L=(e?y+h:u)+(e?1:-1)*(g?-1:1)*(L?L[0]/
2:0)+(this.side===f.Side.bottom?b:0);a.titlePosition.x=e?u-H/2-K+l:L+(g?k:0)+m+l;a.titlePosition.y=e?L-(g?h:0)+(g?b:-b)/2+m+v:y-K+v}};f.onAfterInit=function(){var a=this.chart,b=this.options.grid;b=void 0===b?{}:b;var h=this.userOptions;b.enabled&&(e(this),I(this,"labelFormatter",function(a){var b=this.axis,h=this.value,f=b.tickPositions,e=(b.isLinked?b.linkedParent:b).series[0],m=h===f[0];f=h===f[f.length-1];var l=e&&A(e.options.data,function(a){return a[b.isXAxis?"x":"y"]===h});if(l&&e.is("gantt")){var v=
k(l);x.seriesTypes.gantt.prototype.setGanttPointAliases(v)}this.isFirst=m;this.isLast=f;this.point=v;return a.call(this)}));if(b.columns)for(var f=this.grid.columns=[],u=this.grid.columnIndex=0;++u<b.columns.length;){var m=k(h,b.columns[b.columns.length-u-1],{linkedTo:0,type:"category",scrollbar:{enabled:!1}});delete m.grid.columns;m=new d(this.chart,m);m.grid.isColumn=!0;m.grid.columnIndex=u;B(a.axes,m);B(a[this.coll],m);f.push(m)}};f.onAfterRender=function(){var a,b=this.grid,h=this.options;if(!0===
(h.grid||{}).enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();if(this.grid&&this.grid.isOuterAxis()&&this.axisLine&&(h=h.lineWidth)){h=this.getLinePath(h);var e=h[0],u=h[1],m=((this.tickSize("tick")||[1])[0]-1)*(this.side===f.Side.top||this.side===f.Side.left?-1:1);"M"===e[0]&&"L"===u[0]&&(this.horiz?(e[2]+=m,u[2]+=m):(e[1]+=m,u[1]+=m));!this.horiz&&this.chart.marginRight&&(e=[e,["L",this.left,e[2]]],m=["L",this.chart.chartWidth-
this.chart.marginRight,this.toPixels(this.max+this.tickmarkOffset)],u=[["M",u[1],this.toPixels(this.max+this.tickmarkOffset)],m],this.grid.upperBorder||0===this.min%1||(this.grid.upperBorder=this.grid.renderBorder(e)),this.grid.upperBorder&&this.grid.upperBorder.animate({d:e}),this.grid.lowerBorder||0===this.max%1||(this.grid.lowerBorder=this.grid.renderBorder(u)),this.grid.lowerBorder&&this.grid.lowerBorder.animate({d:u}));this.grid.axisLineExtra?this.grid.axisLineExtra.animate({d:h}):this.grid.axisLineExtra=
this.grid.renderBorder(h);this.axisLine[this.showAxis?"show":"hide"](!0)}(b&&b.columns||[]).forEach(function(a){a.render()});!this.horiz&&this.chart.hasRendered&&(this.scrollbar||(null===(a=this.linkedParent)||void 0===a?0:a.scrollbar))&&(a=this.max,b=this.tickmarkOffset,h=this.tickPositions[this.tickPositions.length-1],u=this.tickPositions[0],this.min-u>b?this.ticks[u].label.hide():this.ticks[u].label.show(),h-a>b?this.ticks[h].label.hide():this.ticks[h].label.show(),h-a<b&&0<h-a&&this.ticks[h].isLast?
this.ticks[h].mark.hide():this.ticks[h-1].mark.show())}};f.onAfterSetAxisTranslation=function(){var a,b=this.tickPositions&&this.tickPositions.info,h=this.options,e=h.grid||{},f=this.userOptions.labels||{};this.horiz?(!0===e.enabled&&this.series.forEach(function(a){a.options.pointRange=0}),b&&h.dateTimeLabelFormats&&h.labels&&!z(f.align)&&(!1===h.dateTimeLabelFormats[b.unitName].range||1<b.count)&&(h.labels.align="left",z(f.x)||(h.labels.x=3))):"treegrid"!==this.options.type&&(null===(a=this.grid)||
void 0===a?0:a.columns)&&(this.minPointOffset=this.tickInterval)};f.onAfterSetOptions=function(a){var b=this.options;a=a.userOptions;var h=b&&w.isObject(b.grid,!0)?b.grid:{};if(!0===h.enabled){var e=k(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,
reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},a);"xAxis"===this.coll&&(z(a.linkedTo)&&!z(a.tickPixelInterval)&&(e.tickPixelInterval=350),z(a.tickPixelInterval)||!z(a.linkedTo)||z(a.tickPositioner)||z(a.tickInterval)||(e.tickPositioner=function(a,b){var h=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(h){var f,m=e.units;for(f=0;f<m.length;f++)if(m[f][0]===
h.unitName){var u=f;break}if(m[u+1]){var g=m[u+1][0];var H=(m[u+1][1]||[1])[0]}else"year"===h.unitName&&(g="year",H=10*h.count);h=p[g];this.tickInterval=h*H;return this.getTimeTicks({unitRange:h,count:H,unitName:g},a,b,this.options.startOfWeek)}}));k(!0,this.options,e);this.horiz&&(b.minPadding=q(a.minPadding,0),b.maxPadding=q(a.maxPadding,0));n(b.grid.borderWidth)&&(b.tickWidth=b.lineWidth=h.borderWidth)}};f.onAfterSetOptions2=function(a){a=(a=a.userOptions)&&a.grid||{};var b=a.columns;a.enabled&&
b&&k(!0,this.options,b[b.length-1])};f.onAfterSetScale=function(){(this.grid.columns||[]).forEach(function(a){a.setScale()})};f.onAfterTickSize=function(a){var b=d.defaultLeftAxisOptions,h=this.horiz,e=this.maxLabelDimensions,f=this.options.grid;f=void 0===f?{}:f;f.enabled&&e&&(b=2*Math.abs(b.labels.x),h=h?f.cellHeight||b+e.height:b+e.width,c(a.tickSize)?a.tickSize[0]=h:a.tickSize=[h,0])};f.onDestroy=function(a){var b=this.grid;(b.columns||[]).forEach(function(b){b.destroy(a.keepEvents)});b.columns=
void 0};f.onInit=function(a){a=a.userOptions||{};var b=a.grid||{};b.enabled&&z(b.borderColor)&&(a.tickColor=a.lineColor=b.borderColor);this.grid||(this.grid=new G(this))};f.onTrimTicks=function(){var a=this.options,b=this.categories,h=this.tickPositions,f=h[0],e=h[h.length-1],m=this.linkedParent&&this.linkedParent.min||this.min,g=this.linkedParent&&this.linkedParent.max||this.max,y=this.tickInterval;!0!==(a.grid||{}).enabled||b||!this.horiz&&!this.isLinked||(f<m&&f+y>m&&!a.startOnTick&&(h[0]=m),e>
g&&e-y<g&&!a.endOnTick&&(h[h.length-1]=g))};f.wrapUnsquish=function(a){var b=this.options.grid;return!0===(void 0===b?{}:b).enabled&&this.categories?this.tickInterval:a.apply(this,Array.prototype.slice.call(arguments,1))};return f}();(function(f){f=f.Side||(f.Side={});f[f.top=0]="top";f[f.right=1]="right";f[f.bottom=2]="bottom";f[f.left=3]="left"})(E||(E={}));E.compose(d);return E});J(d,"Core/Axis/BrokenAxis.js",[d["Core/Axis/Axis.js"],d["Series/Line/LineSeries.js"],d["Extensions/Stacking.js"],d["Core/Utilities.js"]],
function(d,x,r,w){var t=w.addEvent,z=w.find,B=w.fireEvent,A=w.isArray,c=w.isNumber,n=w.pick,k=function(){function c(c){this.hasBreaks=!1;this.axis=c}c.isInBreak=function(c,k){var g=c.repeat||Infinity,e=c.from,p=c.to-c.from;k=k>=e?(k-e)%g:g-(e-k)%g;return c.inclusive?k<=p:k<p&&0!==k};c.lin2Val=function(k){var p=this.brokenAxis;p=p&&p.breakArray;if(!p)return k;var g;for(g=0;g<p.length;g++){var e=p[g];if(e.from>=k)break;else e.to<k?k+=e.len:c.isInBreak(e,k)&&(k+=e.len)}return k};c.val2Lin=function(k){var p=
this.brokenAxis;p=p&&p.breakArray;if(!p)return k;var g=k,e;for(e=0;e<p.length;e++){var n=p[e];if(n.to<=k)g-=n.len;else if(n.from>=k)break;else if(c.isInBreak(n,k)){g-=k-n.from;break}}return g};c.prototype.findBreakAt=function(c,k){return z(k,function(g){return g.from<c&&c<g.to})};c.prototype.isInAnyBreak=function(k,q){var g=this.axis,e=g.options.breaks,p=e&&e.length,E;if(p){for(;p--;)if(c.isInBreak(e[p],k)){var f=!0;E||(E=n(e[p].showPoints,!g.isXAxis))}var a=f&&q?f&&!E:f}return a};c.prototype.setBreaks=
function(k,q){var g=this,e=g.axis,p=A(k)&&!!k.length;e.isDirty=g.hasBreaks!==p;g.hasBreaks=p;e.options.breaks=e.userOptions.breaks=k;e.forceRedraw=!0;e.series.forEach(function(e){e.isDirty=!0});p||e.val2lin!==c.val2Lin||(delete e.val2lin,delete e.lin2val);p&&(e.userOptions.ordinal=!1,e.lin2val=c.lin2Val,e.val2lin=c.val2Lin,e.setExtremes=function(e,f,a,b,h){if(g.hasBreaks){for(var c,u=this.options.breaks;c=g.findBreakAt(e,u);)e=c.to;for(;c=g.findBreakAt(f,u);)f=c.from;f<e&&(f=e)}d.prototype.setExtremes.call(this,
e,f,a,b,h)},e.setAxisTranslation=function(){d.prototype.setAxisTranslation.call(this);g.unitLength=null;if(g.hasBreaks){var k=e.options.breaks||[],f=[],a=[],b=0,h,F=e.userMin||e.min,u=e.userMax||e.max,m=n(e.pointRangePadding,0),C;k.forEach(function(a){h=a.repeat||Infinity;c.isInBreak(a,F)&&(F+=a.to%h-F%h);c.isInBreak(a,u)&&(u-=u%h-a.from%h)});k.forEach(function(a){D=a.from;for(h=a.repeat||Infinity;D-h>F;)D-=h;for(;D<F;)D+=h;for(C=D;C<u;C+=h)f.push({value:C,move:"in"}),f.push({value:C+(a.to-a.from),
move:"out",size:a.breakSize})});f.sort(function(a,b){return a.value===b.value?("in"===a.move?0:1)-("in"===b.move?0:1):a.value-b.value});var y=0;var D=F;f.forEach(function(e){y+="in"===e.move?1:-1;1===y&&"in"===e.move&&(D=e.value);0===y&&(a.push({from:D,to:e.value,len:e.value-D-(e.size||0)}),b+=e.value-D-(e.size||0))});e.breakArray=g.breakArray=a;g.unitLength=u-F-b+m;B(e,"afterBreaks");e.staticScale?e.transA=e.staticScale:g.unitLength&&(e.transA*=(u-e.min+m)/g.unitLength);m&&(e.minPixelPadding=e.transA*
e.minPointOffset);e.min=F;e.max=u}});n(q,!0)&&e.chart.redraw()};return c}();w=function(){function q(){}q.compose=function(p,q){p.keepProps.push("brokenAxis");var g=x.prototype;g.drawBreaks=function(e,g){var k=this,f=k.points,a,b,h,F;if(e&&e.brokenAxis&&e.brokenAxis.hasBreaks){var u=e.brokenAxis;g.forEach(function(m){a=u&&u.breakArray||[];b=e.isXAxis?e.min:n(k.options.threshold,e.min);f.forEach(function(f){F=n(f["stack"+m.toUpperCase()],f[m]);a.forEach(function(a){if(c(b)&&c(F)){h=!1;if(b<a.from&&
F>a.to||b>a.from&&F<a.from)h="pointBreak";else if(b<a.from&&F>a.from&&F<a.to||b>a.from&&F>a.to&&F<a.from)h="pointInBreak";h&&B(e,h,{point:f,brk:a})}})})})}};g.gappedPath=function(){var e=this.currentDataGrouping,c=e&&e.gapSize;e=this.options.gapSize;var g=this.points.slice(),f=g.length-1,a=this.yAxis,b;if(e&&0<f)for("value"!==this.options.gapUnit&&(e*=this.basePointRange),c&&c>e&&c>=this.basePointRange&&(e=c),b=void 0;f--;)b&&!1!==b.visible||(b=g[f+1]),c=g[f],!1!==b.visible&&!1!==c.visible&&(b.x-
c.x>e&&(b=(c.x+b.x)/2,g.splice(f+1,0,{isNull:!0,x:b}),a.stacking&&this.options.stacking&&(b=a.stacking.stacks[this.stackKey][b]=new r(a,a.options.stackLabels,!1,b,this.stack),b.total=0)),b=c);return this.getGraphPath(g)};t(p,"init",function(){this.brokenAxis||(this.brokenAxis=new k(this))});t(p,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});t(p,"afterSetTickPositions",function(){var e=this.brokenAxis;if(e&&e.hasBreaks){var c=this.tickPositions,
g=this.tickPositions.info,f=[],a;for(a=0;a<c.length;a++)e.isInAnyBreak(c[a])||f.push(c[a]);this.tickPositions=f;this.tickPositions.info=g}});t(p,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});t(q,"afterGeneratePoints",function(){var e=this.options.connectNulls,c=this.points,g=this.xAxis,f=this.yAxis;if(this.isDirty)for(var a=c.length;a--;){var b=c[a],h=!(null===b.y&&!1===e)&&(g&&g.brokenAxis&&g.brokenAxis.isInAnyBreak(b.x,!0)||f&&f.brokenAxis&&
f.brokenAxis.isInAnyBreak(b.y,!0));b.visible=h?!1:!1!==b.options.visible}});t(q,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,n(this.pointArrayMap,["y"]))})};return q}();w.compose(d,x);return w});J(d,"Core/Axis/TreeGridAxis.js",[d["Core/Globals.js"],d["Core/Axis/Axis.js"],d["Core/Axis/Tick.js"],d["Gantt/Tree.js"],d["Core/Axis/TreeGridTick.js"],d["Mixins/TreeSeries.js"],d["Core/Utilities.js"]],function(d,x,r,w,t,z,B){var A=z.getLevelOptions,c=B.addEvent,n=B.find,
k=B.fireEvent,q=B.isArray,p=B.isNumber,I=B.isObject,g=B.isString,e=B.merge,G=B.pick,E=B.wrap,f;(function(a){function b(a,b){var l=a.collapseStart||0;a=a.collapseEnd||0;a>=b&&(l-=.5);return{from:l,to:a,showPoints:!1}}function f(a,b,l){var e=[],f=[],h={},m={},c=-1,H="boolean"===typeof b?b:!1;a=w.getTree(a,{after:function(a){a=m[a.pos];var l=0,b=0;a.children.forEach(function(a){b+=(a.descendants||0)+1;l=Math.max((a.height||0)+1,l)});a.descendants=b;a.height=l;a.collapsed&&f.push(a)},before:function(a){var l=
I(a.data,!0)?a.data:{},b=g(l.name)?l.name:"",f=h[a.parent];f=I(f,!0)?m[f.pos]:null;var v=function(a){return a.name===b},u;H&&I(f,!0)&&(u=n(f.children,v))?(v=u.pos,u.nodes.push(a)):v=c++;m[v]||(m[v]=u={depth:f?f.depth+1:0,name:b,id:l.id,nodes:[a],children:[],pos:v},-1!==v&&e.push(b),I(f,!0)&&f.children.push(u));g(a.id)&&(h[a.id]=a);u&&!0===l.collapsed&&(u.collapsed=!0);a.pos=v}});m=function(a,l){var b=function(a,f,e){var v=f+(-1===f?0:l-1),h=(v-f)/2,m=f+h;a.nodes.forEach(function(a){var l=a.data;I(l,
!0)&&(l.y=f+(l.seriesIndex||0),delete l.seriesIndex);a.pos=m});e[m]=a;a.pos=m;a.tickmarkOffset=h+.5;a.collapseStart=v+.5;a.children.forEach(function(a){b(a,v+1,e);v=(a.collapseEnd||0)-.5});a.collapseEnd=v+.5;return e};return b(a["-1"],-1,{})}(m,l);return{categories:e,mapOfIdToNode:h,mapOfPosToGridNode:m,collapsedNodes:f,tree:a}}function F(a){a.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(b){var l=b.options||{},v=l.labels,h=l.uniqueNames,m=0;l=l.max;if(!b.treeGrid.mapOfPosToGridNode||
b.series.some(function(a){return!a.hasRendered||a.isDirtyData||a.isDirty})){var c=b.series.reduce(function(a,b){b.visible&&((b.options.data||[]).forEach(function(l){b.options.keys&&b.options.keys.length&&(l=b.pointClass.prototype.optionsToObject.call({series:b},l),d.seriesTypes.gantt.prototype.setGanttPointAliases(l));I(l,!0)&&(l.seriesIndex=m,a.push(l))}),!0===h&&m++);return a},[]);if(l&&c.length<l)for(var u=c.length;u<=l;u++)c.push({name:u+"\u200b"});l=f(c,h||!1,!0===h?m:1);b.categories=l.categories;
b.treeGrid.mapOfPosToGridNode=l.mapOfPosToGridNode;b.hasNames=!0;b.treeGrid.tree=l.tree;b.series.forEach(function(a){var b=(a.options.data||[]).map(function(b){q(b)&&a.options.keys&&a.options.keys.length&&c.forEach(function(a){0<=b.indexOf(a.x)&&0<=b.indexOf(a.x2)&&(b=a)});return I(b,!0)?e(b):b});a.visible&&a.setData(b,!1)});b.treeGrid.mapOptionsToLevel=A({defaults:v,from:1,levels:v&&v.levels,to:b.treeGrid.tree&&b.treeGrid.tree.height});"beforeRender"===a.type&&(b.treeGrid.collapsedNodes=l.collapsedNodes)}})}
function u(a,b){var l=this.treeGrid.mapOptionsToLevel||{},f=this.ticks,e=f[b],h;if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var m=this.treeGrid.mapOfPosToGridNode[b];(l=l[m.depth])&&(h={labels:l});e?(e.parameters.category=m.name,e.options=h,e.addLabel()):f[b]=new r(this,b,void 0,void 0,{category:m.name,tickmarkOffset:m.tickmarkOffset,options:h})}else a.apply(this,Array.prototype.slice.call(arguments,1))}function m(a){var b=this.options;b=(b=b&&b.labels)&&p(b.indentation)?
b.indentation:0;var l=a.apply(this,Array.prototype.slice.call(arguments,1));if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var f=this.treeGrid.mapOfPosToGridNode[-1].height||0;l.width+=b*(f-1)}return l}function C(a,b,l){var v=this,h="treegrid"===l.type;v.treeGrid||(v.treeGrid=new M(v));h&&(c(b,"beforeRender",F),c(b,"beforeRedraw",F),c(b,"addSeries",function(a){a.options.data&&(a=f(a.options.data,l.uniqueNames||!1,1),v.treeGrid.collapsedNodes=(v.treeGrid.collapsedNodes||[]).concat(a.collapsedNodes))}),
c(v,"foundExtremes",function(){v.treeGrid.collapsedNodes&&v.treeGrid.collapsedNodes.forEach(function(a){var b=v.treeGrid.collapse(a);v.brokenAxis&&(v.brokenAxis.setBreaks(b,!1),v.treeGrid.collapsedNodes&&(v.treeGrid.collapsedNodes=v.treeGrid.collapsedNodes.filter(function(b){return a.collapseStart!==b.collapseStart||a.collapseEnd!==b.collapseEnd})))})}),c(v,"afterBreaks",function(){var a;"yAxis"===v.coll&&!v.staticScale&&(null===(a=v.chart.options.chart)||void 0===a?0:a.height)&&(v.isDirty=!0)}),
l=e({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},l,{reversed:!0,grid:{columns:void 0}}));a.apply(v,[b,l]);h&&(v.hasNames=!0,v.options.showLastLabel=!0)}function y(a){var b=this.options;"treegrid"===b.type?(this.min=G(this.userMin,b.min,this.dataMin),this.max=G(this.userMax,b.max,this.dataMax),k(this,"foundExtremes"),this.setAxisTranslation(),this.tickmarkOffset=.5,
this.tickInterval=1,this.tickPositions=this.treeGrid.mapOfPosToGridNode?this.treeGrid.getTickPositions():[]):a.apply(this,Array.prototype.slice.call(arguments,1))}var D=!1;a.compose=function(a){D||(E(a.prototype,"generateTick",u),E(a.prototype,"getMaxLabelDimensions",m),E(a.prototype,"init",C),E(a.prototype,"setTickInterval",y),t.compose(r),D=!0)};var M=function(){function a(a){this.axis=a}a.prototype.setCollapsedStatus=function(a){var b=this.axis,f=b.chart;b.series.forEach(function(b){var l=b.options.data;
if(a.id&&l){var e=f.get(a.id);b=l[b.data.indexOf(e)];e&&b&&(e.collapsed=a.collapsed,b.collapsed=a.collapsed)}})};a.prototype.collapse=function(a){var l=this.axis,f=l.options.breaks||[],e=b(a,l.max);f.push(e);a.collapsed=!0;l.treeGrid.setCollapsedStatus(a);return f};a.prototype.expand=function(a){var l=this.axis,f=l.options.breaks||[],e=b(a,l.max);a.collapsed=!1;l.treeGrid.setCollapsedStatus(a);return f.reduce(function(a,b){b.to===e.to&&b.from===e.from||a.push(b);return a},[])};a.prototype.getTickPositions=
function(){var a=this.axis,b=Math.floor(a.min/a.tickInterval)*a.tickInterval,f=Math.ceil(a.max/a.tickInterval)*a.tickInterval;return Object.keys(a.treeGrid.mapOfPosToGridNode||{}).reduce(function(l,e){e=+e;!(e>=b&&e<=f)||a.brokenAxis&&a.brokenAxis.isInAnyBreak(e)||l.push(e);return l},[])};a.prototype.isCollapsed=function(a){var l=this.axis,e=l.options.breaks||[],f=b(a,l.max);return e.some(function(a){return a.from===f.from&&a.to===f.to})};a.prototype.toggleCollapse=function(a){return this.isCollapsed(a)?
this.expand(a):this.collapse(a)};return a}();a.Additions=M})(f||(f={}));x.prototype.utils={getNode:w.getNode};f.compose(x);return f});J(d,"Extensions/CurrentDateIndication.js",[d["Core/Axis/Axis.js"],d["Core/Color/Palette.js"],d["Core/Utilities.js"],d["Core/Axis/PlotLineOrBand.js"]],function(d,x,r,w){var t=r.addEvent,z=r.merge;r=r.wrap;var B={currentDateIndicator:!0,color:x.highlightColor20,width:2,label:{format:"%a, %b %d %Y, %H:%M",formatter:function(d,c){return this.axis.chart.time.dateFormat(c,
d)},rotation:0,style:{fontSize:"10px"}}};t(d,"afterSetOptions",function(){var d=this.options,c=d.currentDateIndicator;c&&(c="object"===typeof c?z(B,c):z(B),c.value=new Date,d.plotLines||(d.plotLines=[]),d.plotLines.push(c))});t(w,"render",function(){this.label&&this.label.attr({text:this.getLabelText(this.options.label)})});r(w.prototype,"getLabelText",function(d,c){var n=this.options;return n.currentDateIndicator&&n.label&&"function"===typeof n.label.formatter?(n.value=new Date,n.label.formatter.call(this,
n.value,n.label.format)):d.call(this,c)})});J(d,"Extensions/StaticScale.js",[d["Core/Axis/Axis.js"],d["Core/Chart/Chart.js"],d["Core/Utilities.js"]],function(d,x,r){var w=r.addEvent,t=r.defined,z=r.isNumber,B=r.pick;w(d,"afterSetOptions",function(){var d=this.chart.options&&this.chart.options.chart;!this.horiz&&z(this.options.staticScale)&&(!d.height||d.scrollablePlotArea&&d.scrollablePlotArea.minHeight)&&(this.staticScale=this.options.staticScale)});x.prototype.adjustHeight=function(){"adjustHeight"!==
this.redrawTrigger&&((this.axes||[]).forEach(function(d){var c=d.chart,n=!!c.initiatedScale&&c.options.animation,k=d.options.staticScale;if(d.staticScale&&t(d.min)){var q=B(d.brokenAxis&&d.brokenAxis.unitLength,d.max+d.tickInterval-d.min)*k;q=Math.max(q,k);k=q-c.plotHeight;1<=Math.abs(k)&&(c.plotHeight=q,c.redrawTrigger="adjustHeight",c.setSize(void 0,c.chartHeight+k,n));d.series.forEach(function(k){(k=k.sharedClipKey&&c[k.sharedClipKey])&&k.attr({height:c.plotHeight})})}}),this.initiatedScale=!0);
this.redrawTrigger=null};w(x,"render",x.prototype.adjustHeight)});J(d,"Extensions/ArrowSymbols.js",[d["Core/Renderer/SVG/SVGRenderer.js"]],function(d){d.prototype.symbols.arrow=function(d,r,w,t){return[["M",d,r+t/2],["L",d+w,r],["L",d,r+t/2],["L",d+w,r+t]]};d.prototype.symbols["arrow-half"]=function(x,r,w,t){return d.prototype.symbols.arrow(x,r,w/2,t)};d.prototype.symbols["triangle-left"]=function(d,r,w,t){return[["M",d+w,r],["L",d,r+t/2],["L",d+w,r+t],["Z"]]};d.prototype.symbols["arrow-filled"]=
d.prototype.symbols["triangle-left"];d.prototype.symbols["triangle-left-half"]=function(x,r,w,t){return d.prototype.symbols["triangle-left"](x,r,w/2,t)};d.prototype.symbols["arrow-filled-half"]=d.prototype.symbols["triangle-left-half"]});J(d,"Gantt/Connection.js",[d["Core/Globals.js"],d["Core/Options.js"],d["Core/Series/Point.js"],d["Core/Utilities.js"]],function(d,x,r,w){function t(c){var g=c.shapeArgs;return g?{xMin:g.x,xMax:g.x+g.width,yMin:g.y,yMax:g.y+g.height}:(g=c.graphic&&c.graphic.getBBox())?
{xMin:c.plotX-g.width/2,xMax:c.plotX+g.width/2,yMin:c.plotY-g.height/2,yMax:c.plotY+g.height/2}:null}"";var z=w.defined,B=w.error,A=w.extend,c=w.merge,n=w.objectEach,k=d.deg2rad,q=Math.max,p=Math.min;A(x.defaultOptions,{connectors:{type:"straight",lineWidth:1,marker:{enabled:!1,align:"center",verticalAlign:"middle",inside:!1,lineWidth:1},startMarker:{symbol:"diamond"},endMarker:{symbol:"arrow-filled"}}});x=function(){function d(c,e,k){this.toPoint=this.pathfinder=this.graphics=this.fromPoint=this.chart=
void 0;this.init(c,e,k)}d.prototype.init=function(c,e,k){this.fromPoint=c;this.toPoint=e;this.options=k;this.chart=c.series.chart;this.pathfinder=this.chart.pathfinder};d.prototype.renderPath=function(c,e,k){var g=this.chart,f=g.styledMode,a=g.pathfinder,b=!g.options.chart.forExport&&!1!==k,h=this.graphics&&this.graphics.path;a.group||(a.group=g.renderer.g().addClass("highcharts-pathfinder-group").attr({zIndex:-1}).add(g.seriesGroup));a.group.translate(g.plotLeft,g.plotTop);h&&h.renderer||(h=g.renderer.path().add(a.group),
f||h.attr({opacity:0}));h.attr(e);c={d:c};f||(c.opacity=1);h[b?"animate":"attr"](c,k);this.graphics=this.graphics||{};this.graphics.path=h};d.prototype.addMarker=function(c,e,d){var g=this.fromPoint.series.chart,f=g.pathfinder;g=g.renderer;var a="start"===c?this.fromPoint:this.toPoint,b=a.getPathfinderAnchorPoint(e);if(e.enabled&&((d="start"===c?d[1]:d[d.length-2])&&"M"===d[0]||"L"===d[0])){d={x:d[1],y:d[2]};d=a.getRadiansToVector(d,b);b=a.getMarkerVector(d,e.radius,b);d=-d/k;if(e.width&&e.height){var h=
e.width;var F=e.height}else h=F=2*e.radius;this.graphics=this.graphics||{};b={x:b.x-h/2,y:b.y-F/2,width:h,height:F,rotation:d,rotationOriginX:b.x,rotationOriginY:b.y};this.graphics[c]?this.graphics[c].animate(b):(this.graphics[c]=g.symbol(e.symbol).addClass("highcharts-point-connecting-path-"+c+"-marker").attr(b).add(f.group),g.styledMode||this.graphics[c].attr({fill:e.color||this.fromPoint.color,stroke:e.lineColor,"stroke-width":e.lineWidth,opacity:0}).animate({opacity:1},a.series.options.animation))}};
d.prototype.getPath=function(g){var e=this.pathfinder,k=this.chart,d=e.algorithms[g.type],f=e.chartObstacles;if("function"!==typeof d)return B('"'+g.type+'" is not a Pathfinder algorithm.'),{path:[],obstacles:[]};d.requiresObstacles&&!f&&(f=e.chartObstacles=e.getChartObstacles(g),k.options.connectors.algorithmMargin=g.algorithmMargin,e.chartObstacleMetrics=e.getObstacleMetrics(f));return d(this.fromPoint.getPathfinderAnchorPoint(g.startMarker),this.toPoint.getPathfinderAnchorPoint(g.endMarker),c({chartObstacles:f,
lineObstacles:e.lineObstacles||[],obstacleMetrics:e.chartObstacleMetrics,hardBounds:{xMin:0,xMax:k.plotWidth,yMin:0,yMax:k.plotHeight},obstacleOptions:{margin:g.algorithmMargin},startDirectionX:e.getAlgorithmStartDirection(g.startMarker)},g))};d.prototype.render=function(){var g=this.fromPoint,e=g.series,k=e.chart,d=k.pathfinder,f=c(k.options.connectors,e.options.connectors,g.options.connectors,this.options),a={};k.styledMode||(a.stroke=f.lineColor||g.color,a["stroke-width"]=f.lineWidth,f.dashStyle&&
(a.dashstyle=f.dashStyle));a["class"]="highcharts-point-connecting-path highcharts-color-"+g.colorIndex;f=c(a,f);z(f.marker.radius)||(f.marker.radius=p(q(Math.ceil((f.algorithmMargin||8)/2)-1,1),5));g=this.getPath(f);k=g.path;g.obstacles&&(d.lineObstacles=d.lineObstacles||[],d.lineObstacles=d.lineObstacles.concat(g.obstacles));this.renderPath(k,a,e.options.animation);this.addMarker("start",c(f.marker,f.startMarker),k);this.addMarker("end",c(f.marker,f.endMarker),k)};d.prototype.destroy=function(){this.graphics&&
(n(this.graphics,function(c){c.destroy()}),delete this.graphics)};return d}();d.Connection=x;A(r.prototype,{getPathfinderAnchorPoint:function(c){var k=t(this);switch(c.align){case "right":var e="xMax";break;case "left":e="xMin"}switch(c.verticalAlign){case "top":var d="yMin";break;case "bottom":d="yMax"}return{x:e?k[e]:(k.xMin+k.xMax)/2,y:d?k[d]:(k.yMin+k.yMax)/2}},getRadiansToVector:function(c,k){var e;z(k)||(e=t(this))&&(k={x:(e.xMin+e.xMax)/2,y:(e.yMin+e.yMax)/2});return Math.atan2(k.y-c.y,c.x-
k.x)},getMarkerVector:function(c,k,e){var d=2*Math.PI,g=t(this),f=g.xMax-g.xMin,a=g.yMax-g.yMin,b=Math.atan2(a,f),h=!1;f/=2;var F=a/2,u=g.xMin+f;g=g.yMin+F;for(var m=u,C=g,y=1,D=1;c<-Math.PI;)c+=d;for(;c>Math.PI;)c-=d;d=Math.tan(c);c>-b&&c<=b?(D=-1,h=!0):c>b&&c<=Math.PI-b?D=-1:c>Math.PI-b||c<=-(Math.PI-b)?(y=-1,h=!0):y=-1;h?(m+=y*f,C+=D*f*d):(m+=a/(2*d)*y,C+=D*F);e.x!==u&&(m=e.x);e.y!==g&&(C=e.y);return{x:m+k*Math.cos(c),y:C-k*Math.sin(c)}}});return x});J(d,"Gantt/PathfinderAlgorithms.js",[d["Core/Utilities.js"]],
function(d){function x(c,d,n){n=n||0;var k=c.length-1;d-=1e-7;for(var g,e;n<=k;)if(g=k+n>>1,e=d-c[g].xMin,0<e)n=g+1;else if(0>e)k=g-1;else return g;return 0<n?n-1:0}function r(c,d){for(var k=x(c,d.x+1)+1;k--;){var n;if(n=c[k].xMax>=d.x)n=c[k],n=d.x<=n.xMax&&d.x>=n.xMin&&d.y<=n.yMax&&d.y>=n.yMin;if(n)return k}return-1}function w(c){var k=[];if(c.length){k.push(["M",c[0].start.x,c[0].start.y]);for(var d=0;d<c.length;++d)k.push(["L",c[d].end.x,c[d].end.y])}return k}function t(k,d){k.yMin=c(k.yMin,d.yMin);
k.yMax=A(k.yMax,d.yMax);k.xMin=c(k.xMin,d.xMin);k.xMax=A(k.xMax,d.xMax)}var z=d.extend,B=d.pick,A=Math.min,c=Math.max,n=Math.abs;d=z(function(c,d,p){function k(a,b,e,f,c){a={x:a.x,y:a.y};a[b]=e[f||b]+(c||0);return a}function g(a,b,e){var f=n(b[e]-a[e+"Min"])>n(b[e]-a[e+"Max"]);return k(b,e,a,e+(f?"Max":"Min"),f?1:-1)}var e=[],q=B(p.startDirectionX,n(d.x-c.x)>n(d.y-c.y))?"x":"y",t=p.chartObstacles,f=r(t,c);p=r(t,d);if(-1<p){var a=t[p];p=g(a,d,q);a={start:p,end:d};var b=p}else b=d;-1<f&&(t=t[f],p=g(t,
c,q),e.push({start:c,end:p}),p[q]>=c[q]===p[q]>=b[q]&&(q="y"===q?"x":"y",d=c[q]<d[q],e.push({start:p,end:k(p,q,t,q+(d?"Max":"Min"),d?1:-1)}),q="y"===q?"x":"y"));c=e.length?e[e.length-1].end:c;p=k(c,q,b);e.push({start:c,end:p});q=k(p,"y"===q?"x":"y",b);e.push({start:p,end:q});e.push(a);return{path:w(e),obstacles:e}},{requiresObstacles:!0});return{fastAvoid:z(function(d,q,p){function k(a,b,l){var e,f=a.x<b.x?1:-1;if(a.x<b.x){var c=a;var h=b}else c=b,h=a;if(a.y<b.y){var m=a;var d=b}else m=b,d=a;for(e=
0>f?A(x(y,h.x),y.length-1):0;y[e]&&(0<f&&y[e].xMin<=h.x||0>f&&y[e].xMax>=c.x);){if(y[e].xMin<=h.x&&y[e].xMax>=c.x&&y[e].yMin<=d.y&&y[e].yMax>=m.y)return l?{y:a.y,x:a.x<b.x?y[e].xMin-1:y[e].xMax+1,obstacle:y[e]}:{x:a.x,y:a.y<b.y?y[e].yMin-1:y[e].yMax+1,obstacle:y[e]};e+=f}return b}function g(a,b,l,e,f){var c=f.soft,h=f.hard,m=e?"x":"y",d={x:b.x,y:b.y},v={x:b.x,y:b.y};f=a[m+"Max"]>=c[m+"Max"];c=a[m+"Min"]<=c[m+"Min"];var u=a[m+"Max"]>=h[m+"Max"];h=a[m+"Min"]<=h[m+"Min"];var g=n(a[m+"Min"]-b[m]),y=n(a[m+
"Max"]-b[m]);l=10>n(g-y)?b[m]<l[m]:y<g;v[m]=a[m+"Min"];d[m]=a[m+"Max"];a=k(b,v,e)[m]!==v[m];b=k(b,d,e)[m]!==d[m];l=a?b?l:!0:b?!1:l;l=c?f?l:!0:f?!1:l;return h?u?l:!0:u?!1:l}function e(a,f,l){if(a.x===f.x&&a.y===f.y)return[];var h=l?"x":"y",d=p.obstacleOptions.margin;var n={soft:{xMin:F,xMax:u,yMin:m,yMax:C},hard:p.hardBounds};var D=r(y,a);if(-1<D){D=y[D];n=g(D,a,f,l,n);t(D,p.hardBounds);var H=l?{y:a.y,x:D[n?"xMax":"xMin"]+(n?1:-1)}:{x:a.x,y:D[n?"yMax":"yMin"]+(n?1:-1)};var q=r(y,H);-1<q&&(q=y[q],t(q,
p.hardBounds),H[h]=n?c(D[h+"Max"]-d+1,(q[h+"Min"]+D[h+"Max"])/2):A(D[h+"Min"]+d-1,(q[h+"Max"]+D[h+"Min"])/2),a.x===H.x&&a.y===H.y?(b&&(H[h]=n?c(D[h+"Max"],q[h+"Max"])+1:A(D[h+"Min"],q[h+"Min"])-1),b=!b):b=!1);a=[{start:a,end:H}]}else h=k(a,{x:l?f.x:a.x,y:l?a.y:f.y},l),a=[{start:a,end:{x:h.x,y:h.y}}],h[l?"x":"y"]!==f[l?"x":"y"]&&(n=g(h.obstacle,h,f,!l,n),t(h.obstacle,p.hardBounds),n={x:l?h.x:h.obstacle[n?"xMax":"xMin"]+(n?1:-1),y:l?h.obstacle[n?"yMax":"yMin"]+(n?1:-1):h.y},l=!l,a=a.concat(e({x:h.x,
y:h.y},n,l)));return a=a.concat(e(a[a.length-1].end,f,!l))}function z(a,b,l){var e=A(a.xMax-b.x,b.x-a.xMin)<A(a.yMax-b.y,b.y-a.yMin);l=g(a,b,l,e,{soft:p.hardBounds,hard:p.hardBounds});return e?{y:b.y,x:a[l?"xMax":"xMin"]+(l?1:-1)}:{x:b.x,y:a[l?"yMax":"yMin"]+(l?1:-1)}}var E=B(p.startDirectionX,n(q.x-d.x)>n(q.y-d.y)),f=E?"x":"y",a=[],b=!1,h=p.obstacleMetrics,F=A(d.x,q.x)-h.maxWidth-10,u=c(d.x,q.x)+h.maxWidth+10,m=A(d.y,q.y)-h.maxHeight-10,C=c(d.y,q.y)+h.maxHeight+10,y=p.chartObstacles;var D=x(y,F);
h=x(y,u);y=y.slice(D,h+1);if(-1<(h=r(y,q))){var M=z(y[h],q,d);a.push({end:q,start:M});q=M}for(;-1<(h=r(y,q));)D=0>q[f]-d[f],M={x:q.x,y:q.y},M[f]=y[h][D?f+"Max":f+"Min"]+(D?1:-1),a.push({end:q,start:M}),q=M;d=e(d,q,E);d=d.concat(a.reverse());return{path:w(d),obstacles:d}},{requiresObstacles:!0}),straight:function(c,d){return{path:[["M",c.x,c.y],["L",d.x,d.y]],obstacles:[{start:c,end:d}]}},simpleConnect:d}});J(d,"Gantt/Pathfinder.js",[d["Gantt/Connection.js"],d["Core/Chart/Chart.js"],d["Core/Globals.js"],
d["Core/Options.js"],d["Core/Series/Point.js"],d["Core/Utilities.js"],d["Gantt/PathfinderAlgorithms.js"]],function(d,x,r,w,t,z,B){function A(a){var b=a.shapeArgs;return b?{xMin:b.x,xMax:b.x+b.width,yMin:b.y,yMax:b.y+b.height}:(b=a.graphic&&a.graphic.getBBox())?{xMin:a.plotX-b.width/2,xMax:a.plotX+b.width/2,yMin:a.plotY-b.height/2,yMax:a.plotY+b.height/2}:null}function c(a){for(var b=a.length,c=0,d,m,g=[],k=function(a,b,c){c=e(c,10);var h=a.yMax+c>b.yMin-c&&a.yMin-c<b.yMax+c,l=a.xMax+c>b.xMin-c&&a.xMin-
c<b.xMax+c,m=h?a.xMin>b.xMax?a.xMin-b.xMax:b.xMin-a.xMax:Infinity,d=l?a.yMin>b.yMax?a.yMin-b.yMax:b.yMin-a.yMax:Infinity;return l&&h?c?k(a,b,Math.floor(c/2)):Infinity:f(m,d)};c<b;++c)for(d=c+1;d<b;++d)m=k(a[c],a[d]),80>m&&g.push(m);g.push(80);return E(Math.floor(g.sort(function(a,b){return a-b})[Math.floor(g.length/10)]/2-1),1)}function n(a){if(a.options.pathfinder||a.series.reduce(function(a,b){b.options&&g(!0,b.options.connectors=b.options.connectors||{},b.options.pathfinder);return a||b.options&&
b.options.pathfinder},!1))g(!0,a.options.connectors=a.options.connectors||{},a.options.pathfinder),p('WARNING: Pathfinder options have been renamed. Use "chart.connectors" or "series.connectors" instead.')}"";var k=z.addEvent,q=z.defined,p=z.error,I=z.extend,g=z.merge,e=z.pick,G=z.splat,E=Math.max,f=Math.min;I(w.defaultOptions,{connectors:{type:"straight",lineWidth:1,marker:{enabled:!1,align:"center",verticalAlign:"middle",inside:!1,lineWidth:1},startMarker:{symbol:"diamond"},endMarker:{symbol:"arrow-filled"}}});
var a=function(){function a(a){this.lineObstacles=this.group=this.connections=this.chartObstacleMetrics=this.chartObstacles=this.chart=void 0;this.init(a)}a.prototype.init=function(a){this.chart=a;this.connections=[];k(a,"redraw",function(){this.pathfinder.update()})};a.prototype.update=function(a){var b=this.chart,e=this,f=e.connections;e.connections=[];b.series.forEach(function(a){a.visible&&!a.options.isInternal&&a.points.forEach(function(a){var l=a.options;l&&l.dependency&&(l.connect=l.dependency);
var c;l=a.options&&a.options.connect&&G(a.options.connect);a.visible&&!1!==a.isInside&&l&&l.forEach(function(l){c=b.get("string"===typeof l?l:l.to);c instanceof t&&c.series.visible&&c.visible&&!1!==c.isInside&&e.connections.push(new d(a,c,"string"===typeof l?{}:l))})})});for(var c=0,h,g,k=f.length,n=e.connections.length;c<k;++c){g=!1;for(h=0;h<n;++h)if(f[c].fromPoint===e.connections[h].fromPoint&&f[c].toPoint===e.connections[h].toPoint){e.connections[h].graphics=f[c].graphics;g=!0;break}g||f[c].destroy()}delete this.chartObstacles;
delete this.lineObstacles;e.renderConnections(a)};a.prototype.renderConnections=function(a){a?this.chart.series.forEach(function(a){var b=function(){var b=a.chart.pathfinder;(b&&b.connections||[]).forEach(function(b){b.fromPoint&&b.fromPoint.series===a&&b.render()});a.pathfinderRemoveRenderEvent&&(a.pathfinderRemoveRenderEvent(),delete a.pathfinderRemoveRenderEvent)};!1===a.options.animation?b():a.pathfinderRemoveRenderEvent=k(a,"afterAnimate",b)}):this.connections.forEach(function(a){a.render()})};
a.prototype.getChartObstacles=function(a){for(var b=[],f=this.chart.series,h=e(a.algorithmMargin,0),d,g=0,k=f.length;g<k;++g)if(f[g].visible&&!f[g].options.isInternal)for(var n=0,p=f[g].points.length,H;n<p;++n)H=f[g].points[n],H.visible&&(H=A(H))&&b.push({xMin:H.xMin-h,xMax:H.xMax+h,yMin:H.yMin-h,yMax:H.yMax+h});b=b.sort(function(a,b){return a.xMin-b.xMin});q(a.algorithmMargin)||(d=a.algorithmMargin=c(b),b.forEach(function(a){a.xMin-=d;a.xMax+=d;a.yMin-=d;a.yMax+=d}));return b};a.prototype.getObstacleMetrics=
function(a){for(var b=0,e=0,c,f,h=a.length;h--;)c=a[h].xMax-a[h].xMin,f=a[h].yMax-a[h].yMin,b<c&&(b=c),e<f&&(e=f);return{maxHeight:e,maxWidth:b}};a.prototype.getAlgorithmStartDirection=function(a){var b="top"!==a.verticalAlign&&"bottom"!==a.verticalAlign;return"left"!==a.align&&"right"!==a.align?b?void 0:!1:b?!0:void 0};return a}();a.prototype.algorithms=B;r.Pathfinder=a;I(t.prototype,{getPathfinderAnchorPoint:function(a){var b=A(this);switch(a.align){case "right":var e="xMax";break;case "left":e=
"xMin"}switch(a.verticalAlign){case "top":var c="yMin";break;case "bottom":c="yMax"}return{x:e?b[e]:(b.xMin+b.xMax)/2,y:c?b[c]:(b.yMin+b.yMax)/2}},getRadiansToVector:function(a,e){var b;q(e)||(b=A(this))&&(e={x:(b.xMin+b.xMax)/2,y:(b.yMin+b.yMax)/2});return Math.atan2(e.y-a.y,a.x-e.x)},getMarkerVector:function(a,e,c){var b=2*Math.PI,f=A(this),d=f.xMax-f.xMin,h=f.yMax-f.yMin,g=Math.atan2(h,d),k=!1;d/=2;var n=h/2,q=f.xMin+d;f=f.yMin+n;for(var l=q,v=f,K=1,p=1;a<-Math.PI;)a+=b;for(;a>Math.PI;)a-=b;b=
Math.tan(a);a>-g&&a<=g?(p=-1,k=!0):a>g&&a<=Math.PI-g?p=-1:a>Math.PI-g||a<=-(Math.PI-g)?(K=-1,k=!0):K=-1;k?(l+=K*d,v+=p*d*b):(l+=h/(2*b)*K,v+=p*n);c.x!==q&&(l=c.x);c.y!==f&&(v=c.y);return{x:l+e*Math.cos(a),y:v-e*Math.sin(a)}}});x.prototype.callbacks.push(function(b){!1!==b.options.connectors.enabled&&(n(b),this.pathfinder=new a(this),this.pathfinder.update(!0))});return a});J(d,"Series/XRangeSeries.js",[d["Core/Axis/Axis.js"],d["Core/Series/Series.js"],d["Core/Globals.js"],d["Core/Color/Color.js"],
d["Series/Column/ColumnSeries.js"],d["Series/Line/LineSeries.js"],d["Core/Series/Point.js"],d["Core/Utilities.js"]],function(d,x,r,w,t,z,B,A){var c=w.parse,n=t.prototype;w=A.addEvent;var k=A.clamp,q=A.correctFloat,p=A.defined,I=A.find,g=A.isNumber,e=A.isObject,G=A.merge,E=A.pick,f=x.seriesTypes;x.seriesType("xrange","column",{colorByPoint:!0,dataLabels:{formatter:function(){var a=this.point.partialFill;e(a)&&(a=a.amount);if(g(a)&&0<a)return q(100*a)+"%"},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:'<span style="font-size: 10px">{point.x} - {point.x2}</span><br/>',
pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.yCategory}</b><br/>'},borderRadius:3,pointRange:0},{type:"xrange",parallelArrays:["x","x2","y"],requireSorting:!1,animate:f.line.prototype.animate,cropShoulder:1,getExtremesFromAll:!0,autoIncrement:r.noop,buildKDTree:r.noop,init:function(){f.column.prototype.init.apply(this,arguments);this.options.stacking=void 0},getColumnMetrics:function(){function a(){b.series.forEach(function(a){var b=a.xAxis;a.xAxis=a.yAxis;
a.yAxis=b})}var b=this.chart;a();var e=n.getColumnMetrics.call(this);a();return e},cropData:function(a,b,e,c){b=z.prototype.cropData.call(this,this.x2Data,b,e,c);b.xData=a.slice(b.start,b.end);return b},findPointIndex:function(a){var b=this.cropped,e=this.cropStart,c=this.points,f=a.id;if(f)var d=(d=I(c,function(a){return a.id===f}))?d.index:void 0;"undefined"===typeof d&&(d=(d=I(c,function(b){return b.x===a.x&&b.x2===a.x2&&!b.touched}))?d.index:void 0);b&&g(d)&&g(e)&&d>=e&&(d-=e);return d},translatePoint:function(a){var b=
this.xAxis,c=this.yAxis,f=this.columnMetrics,d=this.options,m=d.minPointLength||0,n=a.plotX,y=E(a.x2,a.x+(a.len||0)),D=b.translate(y,0,0,0,1);y=Math.abs(D-n);var q=this.chart.inverted,t=E(d.borderWidth,1)%2/2,H=f.offset,l=Math.round(f.width);m&&(m-=y,0>m&&(m=0),n-=m/2,D+=m/2);n=Math.max(n,-10);D=k(D,-10,b.len+10);p(a.options.pointWidth)&&(H-=(Math.ceil(a.options.pointWidth)-l)/2,l=Math.ceil(a.options.pointWidth));d.pointPlacement&&g(a.plotY)&&c.categories&&(a.plotY=c.translate(a.y,0,1,0,1,d.pointPlacement));
a.shapeArgs={x:Math.floor(Math.min(n,D))+t,y:Math.floor(a.plotY+H)+t,width:Math.round(Math.abs(D-n)),height:l,r:this.options.borderRadius};d=a.shapeArgs.x;m=d+a.shapeArgs.width;0>d||m>b.len?(d=k(d,0,b.len),m=k(m,0,b.len),D=m-d,a.dlBox=G(a.shapeArgs,{x:d,width:m-d,centerX:D?D/2:null})):a.dlBox=null;d=a.tooltipPos;m=q?1:0;D=q?0:1;f=this.columnMetrics?this.columnMetrics.offset:-f.width/2;d[m]=k(d[m]+y/2*(b.reversed?-1:1)*(q?-1:1),0,b.len-1);d[D]=k(d[D]+(q?-1:1)*f,0,c.len-1);if(f=a.partialFill)e(f)&&
(f=f.amount),g(f)||(f=0),c=a.shapeArgs,a.partShapeArgs={x:c.x,y:c.y,width:c.width,height:c.height,r:this.options.borderRadius},n=Math.max(Math.round(y*f+a.plotX-n),0),a.clipRectArgs={x:b.reversed?c.x+y-n:c.x,y:c.y,width:n,height:c.height}},translate:function(){n.translate.apply(this,arguments);this.points.forEach(function(a){this.translatePoint(a)},this)},drawPoint:function(a,b){var f=this.options,d=this.chart.renderer,g=a.graphic,m=a.shapeType,k=a.shapeArgs,n=a.partShapeArgs,q=a.clipRectArgs,p=a.partialFill,
t=f.stacking&&!f.borderRadius,H=a.state,l=f.states[H||"normal"]||{},v="undefined"===typeof H?"attr":b;H=this.pointAttribs(a,H);l=E(this.chart.options.chart.animation,l.animation);if(a.isNull||!1===a.visible)g&&(a.graphic=g.destroy());else{if(g)g.rect[b](k);else a.graphic=g=d.g("point").addClass(a.getClassName()).add(a.group||this.group),g.rect=d[m](G(k)).addClass(a.getClassName()).addClass("highcharts-partfill-original").add(g);n&&(g.partRect?(g.partRect[b](G(n)),g.partialClipRect[b](G(q))):(g.partialClipRect=
d.clipRect(q.x,q.y,q.width,q.height),g.partRect=d[m](n).addClass("highcharts-partfill-overlay").add(g).clip(g.partialClipRect)));this.chart.styledMode||(g.rect[b](H,l).shadow(f.shadow,null,t),n&&(e(p)||(p={}),e(f.partialFill)&&(p=G(f.partialFill,p)),a=p.fill||c(H.fill).brighten(-.3).get()||c(a.color||this.color).brighten(-.3).get(),H.fill=a,g.partRect[v](H,l).shadow(f.shadow,null,t)))}},drawPoints:function(){var a=this,b=a.getAnimationVerb();a.points.forEach(function(f){a.drawPoint(f,b)})},getAnimationVerb:function(){return this.chart.pointCount<
(this.options.animationLimit||250)?"animate":"attr"}},{resolveColor:function(){var a=this.series;if(a.options.colorByPoint&&!this.options.color){var b=a.options.colors||a.chart.options.colors;var f=this.y%(b?b.length:a.chart.options.chart.colorCount);b=b&&b[f];a.chart.styledMode||(this.color=b);this.options.colorIndex||(this.colorIndex=f)}else this.color||(this.color=a.color)},init:function(){B.prototype.init.apply(this,arguments);this.y||(this.y=0);return this},setState:function(){B.prototype.setState.apply(this,
arguments);this.series.drawPoint(this,this.series.getAnimationVerb())},getLabelConfig:function(){var a=B.prototype.getLabelConfig.call(this),b=this.series.yAxis.categories;a.x2=this.x2;a.yCategory=this.yCategory=b&&b[this.y];return a},tooltipDateKeys:["x","x2"],isValid:function(){return"number"===typeof this.x&&"number"===typeof this.x2}});w(d,"afterGetSeriesExtremes",function(){var a=this.series,b;if(this.isXAxis){var f=E(this.dataMax,-Number.MAX_VALUE);a.forEach(function(a){a.x2Data&&a.x2Data.forEach(function(a){a>
f&&(f=a,b=!0)})});b&&(this.dataMax=f)}});""});J(d,"Series/GanttSeries.js",[d["Core/Series/Series.js"],d["Core/Globals.js"],d["Series/Line/LineSeries.js"],d["Core/Utilities.js"]],function(d,x,r,w){var t=w.isNumber,z=w.merge,B=w.pick,A=w.splat,c=d.seriesTypes.xrange;d.seriesType("gantt","xrange",{grouping:!1,dataLabels:{enabled:!0},tooltip:{headerFormat:'<span style="font-size: 10px">{series.name}</span><br/>',pointFormat:null,pointFormatter:function(){var c=this.series,d=c.chart.tooltip,q=c.xAxis,
p=c.tooltipOptions.dateTimeLabelFormats,t=q.options.startOfWeek,g=c.tooltipOptions,e=g.xDateFormat,r=this.options.milestone,w="<b>"+(this.name||this.yCategory)+"</b>";if(g.pointFormat)return this.tooltipFormatter(g.pointFormat);e||(e=A(d.getDateFormat(q.closestPointRange,this.start,t,p))[0]);d=c.chart.time.dateFormat(e,this.start);c=c.chart.time.dateFormat(e,this.end);w+="<br/>";return r?w+(d+"<br/>"):w+("Start: "+d+"<br/>End: ")+(c+"<br/>")}},connectors:{type:"simpleConnect",animation:{reversed:!0},
startMarker:{enabled:!0,symbol:"arrow-filled",radius:4,fill:"#fa0",align:"left"},endMarker:{enabled:!1,align:"right"}}},{pointArrayMap:["start","end","y"],keyboardMoveVertical:!1,translatePoint:function(d){c.prototype.translatePoint.call(this,d);if(d.options.milestone){var k=d.shapeArgs;var n=k.height;d.shapeArgs={x:k.x-n/2,y:k.y,width:n,height:n}}},drawPoint:function(d,k){var n=this.options,p=this.chart.renderer,r=d.shapeArgs,g=d.plotY,e=d.graphic,w=d.selected&&"select",x=n.stacking&&!n.borderRadius;
if(d.options.milestone)if(t(g)&&null!==d.y&&!1!==d.visible){r=p.symbols.diamond(r.x,r.y,r.width,r.height);if(e)e[k]({d:r});else d.graphic=p.path(r).addClass(d.getClassName(),!0).add(d.group||this.group);this.chart.styledMode||d.graphic.attr(this.pointAttribs(d,w)).shadow(n.shadow,null,x)}else e&&(d.graphic=e.destroy());else c.prototype.drawPoint.call(this,d,k)},setData:r.prototype.setData,setGanttPointAliases:function(c){function d(d,k){"undefined"!==typeof k&&(c[d]=k)}d("x",B(c.start,c.x));d("x2",
B(c.end,c.x2));d("partialFill",B(c.completed,c.partialFill))}},z(c.prototype.pointClass.prototype,{applyOptions:function(d,k){d=c.prototype.pointClass.prototype.applyOptions.call(this,d,k);x.seriesTypes.gantt.prototype.setGanttPointAliases(d);return d},isValid:function(){return("number"===typeof this.start||"number"===typeof this.x)&&("number"===typeof this.end||"number"===typeof this.x2||this.milestone)}}));""});J(d,"Core/Chart/GanttChart.js",[d["Core/Chart/Chart.js"],d["Core/Globals.js"],d["Core/Utilities.js"]],
function(d,x,r){var w=r.getOptions,t=r.isArray,z=r.merge,B=r.splat;x.ganttChart=function(r,c,n){var k="string"===typeof r||r.nodeName,q=c.series,p=w(),x,g=c;c=arguments[k?1:0];t(c.xAxis)||(c.xAxis=[c.xAxis||{},{}]);c.xAxis=c.xAxis.map(function(c,d){1===d&&(x=0);return z(p.xAxis,{grid:{enabled:!0},opposite:!0,linkedTo:x},c,{type:"datetime"})});c.yAxis=B(c.yAxis||{}).map(function(c){return z(p.yAxis,{grid:{enabled:!0},staticScale:50,reversed:!0,type:c.categories?c.type:"treegrid"},c)});c.series=null;
c=z(!0,{chart:{type:"gantt"},title:{text:null},legend:{enabled:!1},navigator:{series:{type:"gantt"},yAxis:{type:"category"}}},c,{isGantt:!0});c.series=g.series=q;return k?new d(r,c,n):new d(c,c)}});J(d,"Core/Axis/ScrollbarAxis.js",[d["Core/Globals.js"],d["Core/Utilities.js"]],function(d,x){var r=x.addEvent,w=x.defined,t=x.pick;return function(){function x(){}x.compose=function(x,A){r(x,"afterInit",function(){var c=this;c.options&&c.options.scrollbar&&c.options.scrollbar.enabled&&(c.options.scrollbar.vertical=
!c.horiz,c.options.startOnTick=c.options.endOnTick=!1,c.scrollbar=new A(c.chart.renderer,c.options.scrollbar,c.chart),r(c.scrollbar,"changed",function(n){var k=t(c.options&&c.options.min,c.min),q=t(c.options&&c.options.max,c.max),p=w(c.dataMin)?Math.min(k,c.min,c.dataMin):k,r=(w(c.dataMax)?Math.max(q,c.max,c.dataMax):q)-p;w(k)&&w(q)&&(c.horiz&&!c.reversed||!c.horiz&&c.reversed?(k=p+r*this.to,p+=r*this.from):(k=p+r*(1-this.from),p+=r*(1-this.to)),t(this.options.liveRedraw,d.svg&&!d.isTouchDevice&&
!this.chart.isBoosting)||"mouseup"===n.DOMType||!w(n.DOMType)?c.setExtremes(p,k,!0,"mousemove"!==n.DOMType,n):this.setRange(this.from,this.to))}))});r(x,"afterRender",function(){var c=Math.min(t(this.options.min,this.min),this.min,t(this.dataMin,this.min)),d=Math.max(t(this.options.max,this.max),this.max,t(this.dataMax,this.max)),k=this.scrollbar,q=this.axisTitleMargin+(this.titleOffset||0),p=this.chart.scrollbarsOffsets,r=this.options.margin||0;k&&(this.horiz?(this.opposite||(p[1]+=q),k.position(this.left,
this.top+this.height+2+p[1]-(this.opposite?r:0),this.width,this.height),this.opposite||(p[1]+=r),q=1):(this.opposite&&(p[0]+=q),k.position(this.left+this.width+2+p[0]-(this.opposite?0:r),this.top,this.width,this.height),this.opposite&&(p[0]+=r),q=0),p[q]+=k.size+k.options.margin,isNaN(c)||isNaN(d)||!w(this.min)||!w(this.max)||this.min===this.max?k.setRange(0,1):(p=(this.min-c)/(d-c),c=(this.max-c)/(d-c),this.horiz&&!this.reversed||!this.horiz&&this.reversed?k.setRange(p,c):k.setRange(1-c,1-p)))});
r(x,"afterGetOffset",function(){var c=this.horiz?2:1,d=this.scrollbar;d&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[c]+=d.size+d.options.margin)})};return x}()});J(d,"Core/Scrollbar.js",[d["Core/Axis/Axis.js"],d["Core/Globals.js"],d["Core/Color/Palette.js"],d["Core/Axis/ScrollbarAxis.js"],d["Core/Utilities.js"],d["Core/Options.js"]],function(d,x,r,w,t,z){var B=t.addEvent,A=t.correctFloat,c=t.defined,n=t.destroyObjectProperties,k=t.fireEvent,q=t.merge,p=t.pick,I=t.removeEvent;t=z.defaultOptions;
var g=x.hasTouch,e=x.isTouchDevice,G=x.swapXY=function(c,f){f&&c.forEach(function(a){for(var b=a.length,c,f=0;f<b;f+=2)c=a[f+1],"number"===typeof c&&(a[f+1]=a[f+2],a[f+2]=c)});return c};z=function(){function d(c,a,b){this._events=[];this.from=this.chartY=this.chartX=0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=
1;this.userOptions={};this.y=this.x=0;this.chart=b;this.options=a;this.renderer=b.renderer;this.init(c,a,b)}d.prototype.addEvents=function(){var c=this.options.inverted?[1,0]:[0,1],a=this.scrollbarButtons,b=this.scrollbarGroup.element,d=this.track.element,e=this.mouseDownHandler.bind(this),k=this.mouseMoveHandler.bind(this),m=this.mouseUpHandler.bind(this);c=[[a[c[0]].element,"click",this.buttonToMinClick.bind(this)],[a[c[1]].element,"click",this.buttonToMaxClick.bind(this)],[d,"click",this.trackClick.bind(this)],
[b,"mousedown",e],[b.ownerDocument,"mousemove",k],[b.ownerDocument,"mouseup",m]];g&&c.push([b,"touchstart",e],[b.ownerDocument,"touchmove",k],[b.ownerDocument,"touchend",m]);c.forEach(function(a){B.apply(null,a)});this._events=c};d.prototype.buttonToMaxClick=function(c){var a=(this.to-this.from)*p(this.options.step,.2);this.updatePosition(this.from+a,this.to+a);k(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:c})};d.prototype.buttonToMinClick=function(c){var a=A(this.to-this.from)*
p(this.options.step,.2);this.updatePosition(A(this.from-a),A(this.to-a));k(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:c})};d.prototype.cursorToScrollbarPosition=function(c){var a=this.options;a=a.minWidth>this.calculatedWidth?a.minWidth:0;return{chartX:(c.chartX-this.x-this.xOffset)/(this.barWidth-a),chartY:(c.chartY-this.y-this.yOffset)/(this.barWidth-a)}};d.prototype.destroy=function(){var c=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar",
"scrollbarGroup","group"].forEach(function(a){this[a]&&this[a].destroy&&(this[a]=this[a].destroy())},this);c&&this===c.scrollbar&&(c.scrollbar=null,n(c.scrollbarButtons))};d.prototype.drawScrollbarButton=function(c){var a=this.renderer,b=this.scrollbarButtons,d=this.options,f=this.size;var e=a.g().add(this.group);b.push(e);e=a.rect().addClass("highcharts-scrollbar-button").add(e);this.chart.styledMode||e.attr({stroke:d.buttonBorderColor,"stroke-width":d.buttonBorderWidth,fill:d.buttonBackgroundColor});
e.attr(e.crisp({x:-.5,y:-.5,width:f+1,height:f+1,r:d.buttonBorderRadius},e.strokeWidth()));e=a.path(G([["M",f/2+(c?-1:1),f/2-3],["L",f/2+(c?-1:1),f/2+3],["L",f/2+(c?2:-2),f/2]],d.vertical)).addClass("highcharts-scrollbar-arrow").add(b[c]);this.chart.styledMode||e.attr({fill:d.buttonArrowColor})};d.prototype.init=function(c,a,b){this.scrollbarButtons=[];this.renderer=c;this.userOptions=a;this.options=q(d.defaultOptions,a);this.chart=b;this.size=p(this.options.size,this.options.height);a.enabled&&(this.render(),
this.addEvents())};d.prototype.mouseDownHandler=function(c){c=this.chart.pointer.normalize(c);c=this.cursorToScrollbarPosition(c);this.chartX=c.chartX;this.chartY=c.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=!0};d.prototype.mouseMoveHandler=function(c){var a=this.chart.pointer.normalize(c),b=this.options.vertical?"chartY":"chartX",d=this.initPositions||[];!this.grabbedCenter||c.touches&&0===c.touches[0][b]||(a=this.cursorToScrollbarPosition(a)[b],b=this[b],b=a-b,this.hasDragged=
!0,this.updatePosition(d[0]+b,d[1]+b),this.hasDragged&&k(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:c.type,DOMEvent:c}))};d.prototype.mouseUpHandler=function(c){this.hasDragged&&k(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:c.type,DOMEvent:c});this.grabbedCenter=this.hasDragged=this.chartX=this.chartY=null};d.prototype.position=function(c,a,b,d){var e=this.options.vertical,f=0,g=this.rendered?"animate":"attr";this.x=c;this.y=a+this.trackBorderWidth;
this.width=b;this.xOffset=this.height=d;this.yOffset=f;e?(this.width=this.yOffset=b=f=this.size,this.xOffset=a=0,this.barWidth=d-2*b,this.x=c+=this.options.margin):(this.height=this.xOffset=d=a=this.size,this.barWidth=b-2*d,this.y+=this.options.margin);this.group[g]({translateX:c,translateY:this.y});this.track[g]({width:b,height:d});this.scrollbarButtons[1][g]({translateX:e?0:b-a,translateY:e?d-f:0})};d.prototype.removeEvents=function(){this._events.forEach(function(c){I.apply(null,c)});this._events.length=
0};d.prototype.render=function(){var c=this.renderer,a=this.options,b=this.size,d=this.chart.styledMode,e;this.group=e=c.g("scrollbar").attr({zIndex:a.zIndex,translateY:-99999}).add();this.track=c.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:a.trackBorderRadius||0,height:b,width:b}).add(e);d||this.track.attr({fill:a.trackBackgroundColor,stroke:a.trackBorderColor,"stroke-width":a.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%
2/2});this.scrollbarGroup=c.g().add(e);this.scrollbar=c.rect().addClass("highcharts-scrollbar-thumb").attr({height:b,width:b,r:a.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=c.path(G([["M",-3,b/4],["L",-3,2*b/3],["M",0,b/4],["L",0,2*b/3],["M",3,b/4],["L",3,2*b/3]],a.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);d||(this.scrollbar.attr({fill:a.barBackgroundColor,stroke:a.barBorderColor,"stroke-width":a.barBorderWidth}),this.scrollbarRifles.attr({stroke:a.rifleColor,
"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};d.prototype.setRange=function(d,a){var b=this.options,e=b.vertical,f=b.minWidth,g=this.barWidth,m,k=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(c(g)){d=Math.max(d,0);var y=Math.ceil(g*d);this.calculatedWidth=m=A(g*
Math.min(a,1)-y);m<f&&(y=(g-f+m)*d,m=f);f=Math.floor(y+this.xOffset+this.yOffset);g=m/2-.5;this.from=d;this.to=a;e?(this.scrollbarGroup[k]({translateY:f}),this.scrollbar[k]({height:m}),this.scrollbarRifles[k]({translateY:g}),this.scrollbarTop=f,this.scrollbarLeft=0):(this.scrollbarGroup[k]({translateX:f}),this.scrollbar[k]({width:m}),this.scrollbarRifles[k]({translateX:g}),this.scrollbarLeft=f,this.scrollbarTop=0);12>=m?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===b.showFull&&(0>=
d&&1<=a?this.group.hide():this.group.show());this.rendered=!0}};d.prototype.trackClick=function(c){var a=this.chart.pointer.normalize(c),b=this.to-this.from,d=this.y+this.scrollbarTop,e=this.x+this.scrollbarLeft;this.options.vertical&&a.chartY>d||!this.options.vertical&&a.chartX>e?this.updatePosition(this.from+b,this.to+b):this.updatePosition(this.from-b,this.to-b);k(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:c})};d.prototype.update=function(c){this.destroy();this.init(this.chart.renderer,
q(!0,this.options,c),this.chart)};d.prototype.updatePosition=function(c,a){1<a&&(c=A(1-A(a-c)),a=1);0>c&&(a=A(a-c),c=0);this.from=c;this.to=a};d.defaultOptions={height:e?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:r.neutralColor20,barBorderWidth:1,barBorderColor:r.neutralColor20,buttonArrowColor:r.neutralColor80,buttonBackgroundColor:r.neutralColor10,buttonBorderColor:r.neutralColor20,buttonBorderWidth:1,rifleColor:r.neutralColor80,
trackBackgroundColor:r.neutralColor5,trackBorderColor:r.neutralColor5,trackBorderWidth:1};return d}();x.Scrollbar||(t.scrollbar=q(!0,z.defaultOptions,t.scrollbar),x.Scrollbar=z,w.compose(d,z));return x.Scrollbar});J(d,"Extensions/RangeSelector.js",[d["Core/Axis/Axis.js"],d["Core/Chart/Chart.js"],d["Core/Globals.js"],d["Core/Options.js"],d["Core/Color/Palette.js"],d["Core/Renderer/SVG/SVGElement.js"],d["Core/Utilities.js"]],function(d,x,r,w,t,z,B){var A=w.defaultOptions,c=B.addEvent,n=B.createElement,
k=B.css,q=B.defined,p=B.destroyObjectProperties,I=B.discardElement,g=B.extend,e=B.fireEvent,G=B.isNumber,E=B.merge,f=B.objectEach,a=B.pick,b=B.pInt,h=B.splat;g(A,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:t.neutralColor60}}});A.lang=E(A.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});var F=function(){function u(a){this.buttons=
void 0;this.buttonOptions=u.prototype.defaultButtons;this.options=void 0;this.chart=a;this.init(a)}u.prototype.clickButton=function(b,e){var f=this.chart,g=this.buttonOptions[b],m=f.xAxis[0],k=f.scroller&&f.scroller.getUnionExtremes()||m||{},n=k.dataMin,l=k.dataMax,v=m&&Math.round(Math.min(m.max,a(l,m.max))),K=g.type;k=g._range;var p,u=g.dataGrouping;if(null!==n&&null!==l){f.fixedRange=k;u&&(this.forcedDataGrouping=!0,d.prototype.setDataGrouping.call(m||{chart:this.chart},u,!1),this.frozenStates=
g.preserveDataGrouping);if("month"===K||"year"===K)if(m){K={range:g,max:v,chart:f,dataMin:n,dataMax:l};var C=m.minFromRange.call(K);G(K.newMax)&&(v=K.newMax)}else k=g;else if(k)C=Math.max(v-k,n),v=Math.min(C+k,l);else if("ytd"===K)if(m)"undefined"===typeof l&&(n=Number.MAX_VALUE,l=Number.MIN_VALUE,f.series.forEach(function(a){a=a.xData;n=Math.min(a[0],n);l=Math.max(a[a.length-1],l)}),e=!1),v=this.getYTDExtremes(l,n,f.time.useUTC),C=p=v.min,v=v.max;else{this.deferredYTDClick=b;return}else"all"===K&&
m&&(C=n,v=l);q(C)&&(C+=g._offsetMin);q(v)&&(v+=g._offsetMax);this.setSelected(b);if(m)m.setExtremes(C,v,a(e,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:g});else{var r=h(f.options.xAxis)[0];var Q=r.range;r.range=k;var t=r.min;r.min=p;c(f,"load",function(){r.range=Q;r.min=t})}}};u.prototype.setSelected=function(a){this.selected=this.options.selected=a};u.prototype.init=function(a){var b=this,d=a.options.rangeSelector,f=d.buttons||b.defaultButtons.slice(),g=d.selected,m=function(){var a=
b.minInput,c=b.maxInput;a&&a.blur&&e(a,"blur");c&&c.blur&&e(c,"blur")};b.chart=a;b.options=d;b.buttons=[];b.buttonOptions=f;this.unMouseDown=c(a.container,"mousedown",m);this.unResize=c(a,"resize",m);f.forEach(b.computeButtonRange);"undefined"!==typeof g&&f[g]&&this.clickButton(g,!1);c(a,"load",function(){a.xAxis&&a.xAxis[0]&&c(a.xAxis[0],"setExtremes",function(c){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==c.trigger&&"updatedData"!==c.trigger&&b.forcedDataGrouping&&!b.frozenStates&&
this.setDataGrouping(!1,!1)})})};u.prototype.updateButtonStates=function(){var a=this,b=this.chart,c=b.xAxis[0],d=Math.round(c.max-c.min),e=!c.hasVisibleSeries,f=b.scroller&&b.scroller.getUnionExtremes()||c,g=f.dataMin,l=f.dataMax;b=a.getYTDExtremes(l,g,b.time.useUTC);var k=b.min,h=b.max,n=a.selected,p=G(n),q=a.options.allButtonsEnabled,u=a.buttons;a.buttonOptions.forEach(function(b,f){var m=b._range,v=b.type,y=b.count||1,K=u[f],D=0,H=b._offsetMax-b._offsetMin;b=f===n;var r=m>l-g,t=m<c.minRange,C=
!1,Q=!1;m=m===d;("month"===v||"year"===v)&&d+36E5>=864E5*{month:28,year:365}[v]*y-H&&d-36E5<=864E5*{month:31,year:366}[v]*y+H?m=!0:"ytd"===v?(m=h-k+H===d,C=!b):"all"===v&&(m=c.max-c.min>=l-g,Q=!b&&p&&m);v=!q&&(r||t||Q||e);y=b&&m||m&&!p&&!C||b&&a.frozenStates;v?D=3:y&&(p=!0,D=2);K.state!==D&&(K.setState(D),0===D&&n===f&&a.setSelected(null))})};u.prototype.computeButtonRange=function(b){var c=b.type,d=b.count||1,e={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(e[c])b._range=
e[c]*d;else if("month"===c||"year"===c)b._range=864E5*{month:30,year:365}[c]*d;b._offsetMin=a(b.offsetMin,0);b._offsetMax=a(b.offsetMax,0);b._range+=b._offsetMax-b._offsetMin};u.prototype.setInputValue=function(a,b){var c=this.chart.options.rangeSelector,d=this.chart.time,e="min"===a?this.minInput:this.maxInput;if(e){var f=e.getAttribute("data-hc-time");f=q(f)?Number(f):void 0;q(b)&&(f&&e.setAttribute("data-hc-time-previous",f),e.setAttribute("data-hc-time",b),f=b);e.value=d.dateFormat(c.inputEditDateFormat||
"%Y-%m-%d",f);this[a+"DateBox"].attr({text:d.dateFormat(c.inputDateFormat||"%b %e, %Y",f)})}};u.prototype.showInput=function(a){var b=this.inputGroup,c=this[a+"DateBox"];k(this[a+"Input"],{left:b.translateX+c.x+"px",top:b.translateY+"px",width:c.width-2+"px",height:c.height-2+"px",border:"2px solid silver"})};u.prototype.hideInput=function(a){k(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)};u.prototype.defaultInputDateParser=function(a,c,d){var e=a.split("/").join("-").split(" ").join("T");
-1===e.indexOf("T")&&(e+="T00:00");if(c)e+="Z";else{var f;if(f=r.isSafari)f=e,f=!(6<f.length&&(f.lastIndexOf("-")===f.length-6||f.lastIndexOf("+")===f.length-6));f&&(f=(new Date(e)).getTimezoneOffset()/60,e+=0>=f?"+"+r.pad(-f)+":00":"-"+r.pad(f)+":00")}e=Date.parse(e);G(e)||(a=a.split("-"),e=Date.UTC(b(a[0]),b(a[1])-1,b(a[2])));d&&c&&(e+=6E4*d.getTimezoneOffset(e));return e};u.prototype.drawInput=function(a){function b(){var a=c.xAxis[0];var b=c.scroller&&c.scroller.xAxis?c.scroller.xAxis:a;var e=
b.dataMin,f=b.dataMax,l=h.maxInput,g=h.minInput;b=(m.inputDateParser||d)(q.value,c.time.useUTC,c.time);b!==Number(q.getAttribute("data-hc-time-previous"))&&G(b)&&(q.setAttribute("data-hc-time-previous",b),p&&l&&G(e)?b>Number(l.getAttribute("data-hc-time"))?b=void 0:b<e&&(b=e):g&&G(f)&&(b<Number(g.getAttribute("data-hc-time"))?b=void 0:b>f&&(b=f)),"undefined"!==typeof b&&a.setExtremes(p?b:a.min,p?a.max:b,void 0,void 0,{trigger:"rangeSelectorInput"}))}var c=this.chart,d=this.defaultInputDateParser,
e=this.div,f=this.inputGroup,h=this,l=c.renderer.style||{},v=c.renderer,m=c.options.rangeSelector,p="min"===a,q,u;this[a+"Label"]=u=v.label(A.lang[p?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(f);f.offset+=u.width+5;this[a+"DateBox"]=v=v.label("",f.offset).addClass("highcharts-range-input").attr({padding:2,width:m.inputBoxWidth||90,height:m.inputBoxHeight||17,"text-align":"center"}).on("click",function(){h.showInput(a);h[a+
"Input"].focus()});c.styledMode||v.attr({stroke:m.inputBoxBorderColor||t.neutralColor20,"stroke-width":1});v.add(f);f.offset+=v.width+(p?10:0);this[a+"Input"]=q=n("input",{name:a,className:"highcharts-range-selector",type:"text"},{top:c.plotTop+"px"},e);c.styledMode||(u.css(E(l,m.labelStyle)),v.css(E({color:t.neutralColor80},l,m.inputStyle)),k(q,g({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:l.fontSize,fontFamily:l.fontFamily,top:"-9999em"},m.inputStyle)));
q.onfocus=function(){h.showInput(a)};q.onblur=function(){q===r.doc.activeElement&&b();h.hideInput(a);q.blur()};q.onchange=b;q.onkeypress=function(a){13===a.keyCode&&b()}};u.prototype.getPosition=function(){var a=this.chart,b=a.options.rangeSelector;a="top"===b.verticalAlign?a.plotTop-a.axisOffset[0]:0;return{buttonTop:a+b.buttonPosition.y,inputTop:a+b.inputPosition.y-10}};u.prototype.getYTDExtremes=function(a,b,c){var d=this.chart.time,e=new d.Date(a),f=d.get("FullYear",e);c=c?d.Date.UTC(f,0,1):+new d.Date(f,
0,1);b=Math.max(b||0,c);e=e.getTime();return{max:Math.min(a||e,e),min:b}};u.prototype.render=function(b,c){var d=this,e=d.chart,f=e.renderer,g=e.container,k=e.options,l=k.exporting&&!1!==k.exporting.enabled&&k.navigation&&k.navigation.buttonOptions,v=A.lang,h=d.div,m=k.rangeSelector,q=a(k.chart.style&&k.chart.style.zIndex,0)+1,p=m.floating,u=d.buttons;h=d.inputGroup;var r=m.buttonTheme,t=m.buttonPosition,w=m.inputPosition;k=m.inputEnabled;var x=r&&r.states,C=e.plotLeft,z=d.buttonGroup,B,E=d.options.verticalAlign,
F=e.legend,I=F&&F.options,G=t.y,J=w.y,P=e.hasLoaded,R=P?"animate":"attr",O=0,N=0;if(!1!==m.enabled){d.rendered||(d.group=B=f.g("range-selector-group").attr({zIndex:7}).add(),d.buttonGroup=z=f.g("range-selector-buttons").add(B),d.zoomText=f.text(v.rangeSelectorZoom,0,15).add(z),e.styledMode||(d.zoomText.css(m.labelStyle),r["stroke-width"]=a(r["stroke-width"],0)),d.buttonOptions.forEach(function(a,b){u[b]=f.button(a.text,0,0,function(c){var e=a.events&&a.events.click,f;e&&(f=e.call(a,c));!1!==f&&d.clickButton(b);
d.isActive=!0},r,x&&x.hover,x&&x.select,x&&x.disabled).attr({"text-align":"center"}).add(z);a.title&&u[b].attr("title",a.title)}),!1!==k&&(d.div=h=n("div",null,{position:"relative",height:0,zIndex:q}),g.parentNode.insertBefore(h,g),d.inputGroup=h=f.g("input-group").add(B),h.offset=0,d.drawInput("min"),d.drawInput("max")));d.zoomText[R]({x:a(C+t.x,C)});var S=a(C+t.x,C)+d.zoomText.getBBox().width+5;d.buttonOptions.forEach(function(b,c){u[c][R]({x:S});S+=u[c].width+a(m.buttonSpacing,5)});C=e.plotLeft-
e.spacing[3];d.updateButtonStates();l&&this.titleCollision(e)&&"top"===E&&"right"===t.align&&t.y+z.getBBox().height-12<(l.y||0)+l.height&&(O=-40);g=t.x-e.spacing[3];"right"===t.align?g+=O-C:"center"===t.align&&(g-=C/2);z.align({y:t.y,width:z.getBBox().width,align:t.align,x:g},!0,e.spacingBox);d.group.placed=P;d.buttonGroup.placed=P;!1!==k&&(O=l&&this.titleCollision(e)&&"top"===E&&"right"===w.align&&w.y-h.getBBox().height-12<(l.y||0)+l.height+e.spacing[0]?-40:0,"left"===w.align?g=C:"right"===w.align&&
(g=-Math.max(e.axisOffset[1],-O)),h.align({y:w.y,width:h.getBBox().width,align:w.align,x:w.x+g-2},!0,e.spacingBox),l=h.alignAttr.translateX+h.alignOptions.x-O+h.getBBox().x+2,g=h.alignOptions.width,v=z.alignAttr.translateX+z.getBBox().x,C=z.getBBox().width+20,(w.align===t.align||v+C>l&&l+g>v&&G<J+h.getBBox().height)&&h.attr({translateX:h.alignAttr.translateX+(e.axisOffset[1]>=-O?0:-O),translateY:h.alignAttr.translateY+z.getBBox().height+10}),d.setInputValue("min",b),d.setInputValue("max",c),d.inputGroup.placed=
P);d.group.align({verticalAlign:E},!0,e.spacingBox);b=d.group.getBBox().height+20;c=d.group.alignAttr.translateY;"bottom"===E&&(F=I&&"bottom"===I.verticalAlign&&I.enabled&&!I.floating?F.legendHeight+a(I.margin,10):0,b=b+F-20,N=c-b-(p?0:m.y)-(e.titleOffset?e.titleOffset[2]:0)-10);if("top"===E)p&&(N=0),e.titleOffset&&e.titleOffset[0]&&(N=e.titleOffset[0]),N+=e.margin[0]-e.spacing[0]||0;else if("middle"===E)if(J===G)N=0>J?c+void 0:c;else if(J||G)N=0>J||0>G?N-Math.min(J,G):c-b+NaN;d.group.translate(m.x,
m.y+Math.floor(N));e=d.minInput;p=d.maxInput;!1!==k&&e&&p&&(e.style.marginTop=d.group.translateY+"px",p.style.marginTop=d.group.translateY+"px");d.rendered=!0}};u.prototype.getHeight=function(){var a=this.options,b=this.group,c=a.y,d=a.buttonPosition.y,e=a.inputPosition.y;if(a.height)return a.height;a=b?b.getBBox(!0).height+13+c:0;b=Math.min(e,d);if(0>e&&0>d||0<e&&0<d)a+=Math.abs(b);return a};u.prototype.titleCollision=function(a){return!(a.options.title.text||a.options.subtitle.text)};u.prototype.update=
function(a){var b=this.chart;E(!0,b.options.rangeSelector,a);this.destroy();this.init(b);b.rangeSelector.render()};u.prototype.destroy=function(){var a=this,b=a.minInput,c=a.maxInput;a.unMouseDown();a.unResize();p(a.buttons);b&&(b.onfocus=b.onblur=b.onchange=null);c&&(c.onfocus=c.onblur=c.onchange=null);f(a,function(b,c){b&&"chart"!==c&&(b instanceof z?b.destroy():b instanceof window.HTMLElement&&I(b));b!==u.prototype[c]&&(a[c]=null)},this)};return u}();F.prototype.defaultButtons=[{type:"month",count:1,
text:"1m",title:"View 1 month"},{type:"month",count:3,text:"3m",title:"View 3 months"},{type:"month",count:6,text:"6m",title:"View 6 months"},{type:"ytd",text:"YTD",title:"View year to date"},{type:"year",count:1,text:"1y",title:"View 1 year"},{type:"all",text:"All",title:"View all"}];d.prototype.minFromRange=function(){var b=this.range,c=b.type,d=this.max,e=this.chart.time,f=function(a,b){var d="year"===c?"FullYear":"Month",f=new e.Date(a),l=e.get(d,f);e.set(d,f,l+b);l===e.get(d,f)&&e.set("Date",
f,0);return f.getTime()-a};if(G(b)){var g=d-b;var k=b}else g=d+f(d,-b.count),this.chart&&(this.chart.fixedRange=d-g);var h=a(this.dataMin,Number.MIN_VALUE);G(g)||(g=h);g<=h&&(g=h,"undefined"===typeof k&&(k=f(g,b.count)),this.newMax=Math.min(g+k,this.dataMax));G(d)||(g=void 0);return g};r.RangeSelector||(c(x,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new F(this))}),c(x,"beforeRender",function(){var a=this.axes,b=this.rangeSelector;b&&(G(b.deferredYTDClick)&&
(b.clickButton(b.deferredYTDClick),delete b.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),b.render(),a=b.options.verticalAlign,b.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),c(x,"update",function(a){var b=a.options.rangeSelector;a=this.rangeSelector;var c=this.extraBottomMargin,d=this.extraTopMargin;b&&b.enabled&&!q(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new F(this));this.extraTopMargin=
this.extraBottomMargin=!1;a&&(a.render(),b=b&&b.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)),this.extraBottomMargin!==c||this.extraTopMargin!==d)&&(this.isDirtyBox=!0)}),c(x,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),c(x,"getMargins",function(){var a=
this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),x.prototype.callbacks.push(function(a){function b(){d=a.xAxis[0].getExtremes();f=a.legend;k=null===e||void 0===e?void 0:e.options.verticalAlign;G(d.min)&&e.render(d.min,d.max);e&&f.display&&"top"===k&&k===f.options.verticalAlign&&(g=E(a.spacingBox),g.y="vertical"===f.options.layout?a.plotTop:g.y+e.getHeight(),f.group.placed=!1,f.align(g))}var d,e=a.rangeSelector,f,g,k;if(e){var h=
c(a.xAxis[0],"afterSetExtremes",function(a){e.render(a.min,a.max)});var l=c(a,"redraw",b);b()}c(a,"destroy",function(){e&&(l(),h())})}),r.RangeSelector=F);return r.RangeSelector});J(d,"Core/Axis/NavigatorAxis.js",[d["Core/Globals.js"],d["Core/Utilities.js"]],function(d,x){var r=d.isTouchDevice,w=x.addEvent,t=x.correctFloat,z=x.defined,B=x.isNumber,A=x.pick,c=function(){function c(c){this.axis=c}c.prototype.destroy=function(){this.axis=void 0};c.prototype.toFixedRange=function(c,d,n,r){var g=this.axis,
e=g.chart;e=e&&e.fixedRange;var k=(g.pointRange||0)/2;c=A(n,g.translate(c,!0,!g.horiz));d=A(r,g.translate(d,!0,!g.horiz));g=e&&(d-c)/e;z(n)||(c=t(c+k));z(r)||(d=t(d-k));.7<g&&1.3>g&&(r?c=d-e:d=c+e);B(c)&&B(d)||(c=d=void 0);return{min:c,max:d}};return c}();return function(){function d(){}d.compose=function(d){d.keepProps.push("navigatorAxis");w(d,"init",function(){this.navigatorAxis||(this.navigatorAxis=new c(this))});w(d,"zoom",function(c){var d=this.chart.options,k=d.navigator,g=this.navigatorAxis,
e=d.chart.pinchType,n=d.rangeSelector;d=d.chart.zoomType;this.isXAxis&&(k&&k.enabled||n&&n.enabled)&&("y"===d?c.zoomed=!1:(!r&&"xy"===d||r&&"xy"===e)&&this.options.range&&(k=g.previousZoom,z(c.newMin)?g.previousZoom=[this.min,this.max]:k&&(c.newMin=k[0],c.newMax=k[1],g.previousZoom=void 0)));"undefined"!==typeof c.zoomed&&c.preventDefault()})};d.AdditionsClass=c;return d}()});J(d,"Core/Navigator.js",[d["Core/Axis/Axis.js"],d["Core/Series/Series.js"],d["Core/Chart/Chart.js"],d["Core/Color/Color.js"],
d["Core/Globals.js"],d["Series/Line/LineSeries.js"],d["Core/Axis/NavigatorAxis.js"],d["Core/Options.js"],d["Core/Color/Palette.js"],d["Core/Scrollbar.js"],d["Core/Utilities.js"]],function(d,x,r,w,t,z,B,A,c,n,k){w=w.parse;var q=t.hasTouch,p=t.isTouchDevice,I=A.defaultOptions,g=k.addEvent,e=k.clamp,G=k.correctFloat,E=k.defined,f=k.destroyObjectProperties,a=k.erase,b=k.extend,h=k.find,F=k.isArray,u=k.isNumber,m=k.merge,C=k.pick,y=k.removeEvent,D=k.splat,J=function(a){for(var b=[],c=1;c<arguments.length;c++)b[c-
1]=arguments[c];b=[].filter.call(b,u);if(b.length)return Math[a].apply(0,b)};x="undefined"===typeof x.seriesTypes.areaspline?"line":"areaspline";b(I,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:c.neutralColor5,borderColor:c.neutralColor40},maskFill:w(c.highlightColor60).setOpacity(.3).get(),outlineColor:c.neutralColor20,outlineWidth:1,series:{type:x,fillOpacity:.05,lineWidth:1,compare:null,
dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",
tickLength:0,lineWidth:0,gridLineColor:c.neutralColor10,gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:c.neutralColor40},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});t.Renderer.prototype.symbols["navigator-handle"]=function(a,b,c,d,e){a=(e&&e.width||0)/2;b=Math.round(a/3)+.5;e=e&&e.height||0;return[["M",
-a-1,.5],["L",a,.5],["L",a,e+.5],["L",-a-1,e+.5],["L",-a-1,.5],["M",-b,4],["L",-b,e-3],["M",b-1,4],["L",b-1,e-3]]};var L=function(){function c(a){this.zoomedMin=this.zoomedMax=this.yAxis=this.xAxis=this.top=this.size=this.shades=this.rendered=this.range=this.outlineHeight=this.outline=this.opposite=this.navigatorSize=this.navigatorSeries=this.navigatorOptions=this.navigatorGroup=this.navigatorEnabled=this.left=this.height=this.handles=this.chart=this.baseSeries=void 0;this.init(a)}c.prototype.drawHandle=
function(a,b,c,d){var e=this.navigatorOptions.handles.height;this.handles[b][d](c?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(a,10)+.5-e)}:{translateX:Math.round(this.left+parseInt(a,10)),translateY:Math.round(this.top+this.height/2-e/2-1)})};c.prototype.drawOutline=function(a,b,c,d){var e=this.navigatorOptions.maskInside,f=this.outline.strokeWidth(),l=f/2,g=f%2/2;f=this.outlineHeight;var k=this.scrollbarHeight||0,h=this.size,v=this.left-k,m=this.top;c?
(v-=l,c=m+b+g,b=m+a+g,g=[["M",v+f,m-k-g],["L",v+f,c],["L",v,c],["L",v,b],["L",v+f,b],["L",v+f,m+h+k]],e&&g.push(["M",v+f,c-l],["L",v+f,b+l])):(a+=v+k-g,b+=v+k-g,m+=l,g=[["M",v,m],["L",a,m],["L",a,m+f],["L",b,m+f],["L",b,m],["L",v+h+2*k,m]],e&&g.push(["M",a-l,m],["L",b+l,m]));this.outline[d]({d:g})};c.prototype.drawMasks=function(a,b,c,d){var e=this.left,f=this.top,l=this.height;if(c){var g=[e,e,e];var k=[f,f+a,f+b];var h=[l,l,l];var v=[a,b-a,this.size-b]}else g=[e,e+a,e+b],k=[f,f,f],h=[a,b-a,this.size-
b],v=[l,l,l];this.shades.forEach(function(a,b){a[d]({x:g[b],y:k[b],width:h[b],height:v[b]})})};c.prototype.renderElements=function(){var a=this,b=a.navigatorOptions,c=b.maskInside,d=a.chart,e=d.renderer,f,g={cursor:d.inverted?"ns-resize":"ew-resize"};a.navigatorGroup=f=e.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!c,c,!c].forEach(function(c,l){a.shades[l]=e.rect().addClass("highcharts-navigator-mask"+(1===l?"-inside":"-outside")).add(f);d.styledMode||a.shades[l].attr({fill:c?b.maskFill:
"rgba(0,0,0,0)"}).css(1===l&&g)});a.outline=e.path().addClass("highcharts-navigator-outline").add(f);d.styledMode||a.outline.attr({"stroke-width":b.outlineWidth,stroke:b.outlineColor});b.handles.enabled&&[0,1].forEach(function(c){b.handles.inverted=d.inverted;a.handles[c]=e.symbol(b.handles.symbols[c],-b.handles.width/2-1,0,b.handles.width,b.handles.height,b.handles);a.handles[c].attr({zIndex:7-c}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][c]).add(f);if(!d.styledMode){var l=
b.handles;a.handles[c].attr({fill:l.backgroundColor,stroke:l.borderColor,"stroke-width":l.lineWidth}).css(g)}})};c.prototype.update=function(a){(this.series||[]).forEach(function(a){a.baseSeries&&delete a.baseSeries.navigatorSeries});this.destroy();m(!0,this.chart.options.navigator,this.options,a);this.init(this.chart)};c.prototype.render=function(a,b,c,d){var f=this.chart,l=this.scrollbarHeight,g,k=this.xAxis,h=k.pointRange||0;var v=k.navigatorAxis.fake?f.xAxis[0]:k;var m=this.navigatorEnabled,n,
p=this.rendered;var q=f.inverted;var r=f.xAxis[0].minRange,t=f.xAxis[0].options.maxRange;if(!this.hasDragged||E(c)){a=G(a-h/2);b=G(b+h/2);if(!u(a)||!u(b))if(p)c=0,d=C(k.width,v.width);else return;this.left=C(k.left,f.plotLeft+l+(q?f.plotWidth:0));this.size=n=g=C(k.len,(q?f.plotHeight:f.plotWidth)-2*l);f=q?l:g+2*l;c=C(c,k.toPixels(a,!0));d=C(d,k.toPixels(b,!0));u(c)&&Infinity!==Math.abs(c)||(c=0,d=f);a=k.toValue(c,!0);b=k.toValue(d,!0);var w=Math.abs(G(b-a));w<r?this.grabbedLeft?c=k.toPixels(b-r-h,
!0):this.grabbedRight&&(d=k.toPixels(a+r+h,!0)):E(t)&&G(w-h)>t&&(this.grabbedLeft?c=k.toPixels(b-t-h,!0):this.grabbedRight&&(d=k.toPixels(a+t+h,!0)));this.zoomedMax=e(Math.max(c,d),0,n);this.zoomedMin=e(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(c,d),0,n);this.range=this.zoomedMax-this.zoomedMin;n=Math.round(this.zoomedMax);c=Math.round(this.zoomedMin);m&&(this.navigatorGroup.attr({visibility:"visible"}),p=p&&!this.hasDragged?"animate":"attr",this.drawMasks(c,n,q,p),this.drawOutline(c,
n,q,p),this.navigatorOptions.handles.enabled&&(this.drawHandle(c,0,q,p),this.drawHandle(n,1,q,p)));this.scrollbar&&(q?(q=this.top-l,v=this.left-l+(m||!v.opposite?0:(v.titleOffset||0)+v.axisTitleMargin),l=g+2*l):(q=this.top+(m?this.height:-l),v=this.left-l),this.scrollbar.position(v,q,f,l),this.scrollbar.setRange(this.zoomedMin/(g||1),this.zoomedMax/(g||1)));this.rendered=!0}};c.prototype.addMouseEvents=function(){var a=this,b=a.chart,c=b.container,d=[],e,f;a.mouseMoveHandler=e=function(b){a.onMouseMove(b)};
a.mouseUpHandler=f=function(b){a.onMouseUp(b)};d=a.getPartsEvents("mousedown");d.push(g(b.renderTo,"mousemove",e),g(c.ownerDocument,"mouseup",f));q&&(d.push(g(b.renderTo,"touchmove",e),g(c.ownerDocument,"touchend",f)),d.concat(a.getPartsEvents("touchstart")));a.eventsToUnbind=d;a.series&&a.series[0]&&d.push(g(a.series[0].xAxis,"foundExtremes",function(){b.navigator.modifyNavigatorAxisExtremes()}))};c.prototype.getPartsEvents=function(a){var b=this,c=[];["shades","handles"].forEach(function(d){b[d].forEach(function(e,
f){c.push(g(e.element,a,function(a){b[d+"Mousedown"](a,f)}))})});return c};c.prototype.shadesMousedown=function(a,b){a=this.chart.pointer.normalize(a);var c=this.chart,d=this.xAxis,e=this.zoomedMin,f=this.left,g=this.size,l=this.range,k=a.chartX;c.inverted&&(k=a.chartY,f=this.top);if(1===b)this.grabbedCenter=k,this.fixedWidth=l,this.dragOffset=k-e;else{a=k-f-l/2;if(0===b)a=Math.max(0,a);else if(2===b&&a+l>=g)if(a=g-l,this.reversedExtremes){a-=l;var h=this.getUnionExtremes().dataMin}else var m=this.getUnionExtremes().dataMax;
a!==e&&(this.fixedWidth=l,b=d.navigatorAxis.toFixedRange(a,a+l,h,m),E(b.min)&&c.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,b.max),!0,null,{trigger:"navigator"}))}};c.prototype.handlesMousedown=function(a,b){this.chart.pointer.normalize(a);a=this.chart;var c=a.xAxis[0],d=this.reversedExtremes;0===b?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=d?c.min:c.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=d?c.max:c.min);a.fixedRange=
null};c.prototype.onMouseMove=function(a){var b=this,c=b.chart,d=b.left,e=b.navigatorSize,f=b.range,g=b.dragOffset,l=c.inverted;a.touches&&0===a.touches[0].pageX||(a=c.pointer.normalize(a),c=a.chartX,l&&(d=b.top,c=a.chartY),b.grabbedLeft?(b.hasDragged=!0,b.render(0,0,c-d,b.otherHandlePos)):b.grabbedRight?(b.hasDragged=!0,b.render(0,0,b.otherHandlePos,c-d)):b.grabbedCenter&&(b.hasDragged=!0,c<g?c=g:c>e+g-f&&(c=e+g-f),b.render(0,0,c-g,c-g+f)),b.hasDragged&&b.scrollbar&&C(b.scrollbar.options.liveRedraw,
t.svg&&!p&&!this.chart.isBoosting)&&(a.DOMType=a.type,setTimeout(function(){b.onMouseUp(a)},0)))};c.prototype.onMouseUp=function(a){var b=this.chart,c=this.xAxis,d=this.scrollbar,e=a.DOMEvent||a,f=b.inverted,g=this.rendered&&!this.hasDragged?"animate":"attr";if(this.hasDragged&&(!d||!d.hasDragged)||"scrollbar"===a.trigger){d=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var l=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var k=this.fixedExtreme;this.zoomedMax===
this.size&&(k=this.reversedExtremes?d.dataMin:d.dataMax);0===this.zoomedMin&&(l=this.reversedExtremes?d.dataMax:d.dataMin);c=c.navigatorAxis.toFixedRange(this.zoomedMin,this.zoomedMax,l,k);E(c.min)&&b.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:e})}"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=
this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&u(this.zoomedMin)&&u(this.zoomedMax)&&(b=Math.round(this.zoomedMin),a=Math.round(this.zoomedMax),this.shades&&this.drawMasks(b,a,f,g),this.outline&&this.drawOutline(b,a,f,g),this.navigatorOptions.handles.enabled&&Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(b,0,f,g),this.drawHandle(a,1,f,g)))};c.prototype.removeEvents=function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(a){a()}),this.eventsToUnbind=
void 0);this.removeBaseSeriesEvents()};c.prototype.removeBaseSeriesEvents=function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&a.forEach(function(a){y(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&y(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))};c.prototype.init=function(a){var b=a.options,c=b.navigator,e=c.enabled,f=b.scrollbar,k=f.enabled;b=e?c.height:0;var l=k?f.height:0;this.handles=[];this.shades=[];this.chart=
a;this.setBaseSeries();this.height=b;this.scrollbarHeight=l;this.scrollbarEnabled=k;this.navigatorEnabled=e;this.navigatorOptions=c;this.scrollbarOptions=f;this.outlineHeight=b+l;this.opposite=C(c.opposite,!(e||!a.inverted));var h=this;e=h.baseSeries;f=a.xAxis.length;k=a.yAxis.length;var p=e&&e[0]&&e[0].xAxis||a.xAxis[0]||{options:{}};a.isDirtyBox=!0;h.navigatorEnabled?(h.xAxis=new d(a,m({breaks:p.options.breaks,ordinal:p.options.ordinal},c.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,
type:"datetime",index:f,isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[l,0,-l,0],width:b}:{offsets:[0,-l,0,l],height:b})),h.yAxis=new d(a,m(c.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:k,isInternal:!0,reversed:C(c.yAxis&&c.yAxis.reversed,a.yAxis[0]&&a.yAxis[0].reversed,!1),zoomEnabled:!1},a.inverted?{width:b}:{height:b})),e||c.series.data?h.updateNavigatorSeries(!1):0===a.series.length&&(h.unbindRedraw=
g(a,"beforeRedraw",function(){0<a.series.length&&!h.series&&(h.setBaseSeries(),h.unbindRedraw())})),h.reversedExtremes=a.inverted&&!h.xAxis.reversed||!a.inverted&&h.xAxis.reversed,h.renderElements(),h.addMouseEvents()):(h.xAxis={chart:a,navigatorAxis:{fake:!0},translate:function(b,c){var d=a.xAxis[0],e=d.getExtremes(),f=d.len-2*l,g=J("min",d.options.min,e.dataMin);d=J("max",d.options.max,e.dataMax)-g;return c?b*d/f+g:f*(b-g)/d},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,
!0)}},h.xAxis.navigatorAxis.axis=h.xAxis,h.xAxis.navigatorAxis.toFixedRange=B.AdditionsClass.prototype.toFixedRange.bind(h.xAxis.navigatorAxis));a.options.scrollbar.enabled&&(a.scrollbar=h.scrollbar=new n(a.renderer,m(a.options.scrollbar,{margin:h.navigatorEnabled?0:10,vertical:a.inverted}),a),g(h.scrollbar,"changed",function(b){var c=h.size,d=c*this.to;c*=this.from;h.hasDragged=h.scrollbar.hasDragged;h.render(0,0,c,d);(a.options.scrollbar.liveRedraw||"mousemove"!==b.DOMType&&"touchmove"!==b.DOMType)&&
setTimeout(function(){h.onMouseUp(b)})}));h.addBaseSeriesEvents();h.addChartEvents()};c.prototype.getUnionExtremes=function(a){var b=this.chart.xAxis[0],c=this.xAxis,d=c.options,e=b.options,f;a&&null===b.dataMin||(f={dataMin:C(d&&d.min,J("min",e.min,b.dataMin,c.dataMin,c.min)),dataMax:C(d&&d.max,J("max",e.max,b.dataMax,c.dataMax,c.max))});return f};c.prototype.setBaseSeries=function(a,b){var c=this.chart,d=this.baseSeries=[];a=a||c.options&&c.options.navigator.baseSeries||(c.series.length?h(c.series,
function(a){return!a.options.isInternal}).index:0);(c.series||[]).forEach(function(b,c){b.options.isInternal||!b.options.showInNavigator&&(c!==a&&b.options.id!==a||!1===b.options.showInNavigator)||d.push(b)});this.xAxis&&!this.xAxis.navigatorAxis.fake&&this.updateNavigatorSeries(!0,b)};c.prototype.updateNavigatorSeries=function(a,c){var d=this,e=d.chart,f=d.baseSeries,g,h,k=d.navigatorOptions.series,l,n={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",
yAxis:"navigator-y-axis",showInLegend:!1,stacking:void 0,isInternal:!0,states:{inactive:{opacity:1}}},p=d.series=(d.series||[]).filter(function(a){var b=a.baseSeries;return 0>f.indexOf(b)?(b&&(y(b,"updatedData",d.updatedDataHandler),delete b.navigatorSeries),a.chart&&a.destroy(),!1):!0});f&&f.length&&f.forEach(function(a){var q=a.navigatorSeries,v=b({color:a.color,visible:a.visible},F(k)?I.navigator.series:k);q&&!1===d.navigatorOptions.adaptToUpdatedData||(n.name="Navigator "+f.length,g=a.options||
{},l=g.navigatorOptions||{},h=m(g,n,v,l),h.pointRange=C(v.pointRange,l.pointRange,I.plotOptions[h.type||"line"].pointRange),v=l.data||v.data,d.hasNavigatorData=d.hasNavigatorData||!!v,h.data=v||g.data&&g.data.slice(0),q&&q.options?q.update(h,c):(a.navigatorSeries=e.initSeries(h),a.navigatorSeries.baseSeries=a,p.push(a.navigatorSeries)))});if(k.data&&(!f||!f.length)||F(k))d.hasNavigatorData=!1,k=D(k),k.forEach(function(a,b){n.name="Navigator "+(p.length+1);h=m(I.navigator.series,{color:e.series[b]&&
!e.series[b].options.isInternal&&e.series[b].color||e.options.colors[b]||e.options.colors[0]},n,a);h.data=a.data;h.data&&(d.hasNavigatorData=!0,p.push(e.initSeries(h)))});a&&this.addBaseSeriesEvents()};c.prototype.addBaseSeriesEvents=function(){var b=this,c=b.baseSeries||[];c[0]&&c[0].xAxis&&g(c[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);c.forEach(function(c){g(c,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});g(c,"hide",function(){this.navigatorSeries&&
this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&c.xAxis&&g(c,"updatedData",this.updatedDataHandler);g(c,"remove",function(){this.navigatorSeries&&(a(b.series,this.navigatorSeries),E(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)};c.prototype.getBaseSeriesMin=function(a){return this.baseSeries.reduce(function(a,b){return Math.min(a,b.xData?b.xData[0]:a)},a)};c.prototype.modifyNavigatorAxisExtremes=function(){var a=
this.xAxis,b;"undefined"!==typeof a.getExtremes&&(!(b=this.getUnionExtremes(!0))||b.dataMin===a.min&&b.dataMax===a.max||(a.min=b.dataMin,a.max=b.dataMax))};c.prototype.modifyBaseAxisExtremes=function(){var a=this.chart.navigator,b=this.getExtremes(),c=b.dataMin,d=b.dataMax;b=b.max-b.min;var e=a.stickToMin,f=a.stickToMax,g=C(this.options.overscroll,0),h=a.series&&a.series[0],k=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(e){var m=c;var n=m+b}f&&(n=d+g,e||
(m=Math.max(c,n-b,a.getBaseSeriesMin(h&&h.xData?h.xData[0]:-Number.MAX_VALUE))));k&&(e||f)&&u(m)&&(this.min=this.userMin=m,this.max=this.userMax=n)}a.stickToMin=a.stickToMax=null};c.prototype.updatedDataHandler=function(){var a=this.chart.navigator,b=this.navigatorSeries,c=a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?0===Math.round(a.zoomedMin):Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=u(this.xAxis.min)&&this.xAxis.min<=c&&(!this.chart.fixedRange||!a.stickToMax);
b&&!a.hasNavigatorData&&(b.options.pointStart=this.xData[0],b.setData(this.options.data,!1,null,!1))};c.prototype.addChartEvents=function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(g(this.chart,"redraw",function(){var a=this.navigator,b=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||this.xAxis[0]);b&&a.render(b.min,b.max)}),g(this.chart,"getMargins",function(){var a=this.navigator,b=a.opposite?"plotTop":"marginBottom";this.inverted&&(b=a.opposite?"marginRight":
"plotLeft");this[b]=(this[b]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:0)+a.navigatorOptions.margin}))};c.prototype.destroy=function(){this.removeEvents();this.xAxis&&(a(this.chart.xAxis,this.xAxis),a(this.chart.axes,this.xAxis));this.yAxis&&(a(this.chart.yAxis,this.yAxis),a(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&a.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&
this[a].destroy&&this[a].destroy();this[a]=null},this);[this.handles].forEach(function(a){f(a)},this)};return c}();t.Navigator||(t.Navigator=L,B.compose(d),g(r,"beforeShowResetZoom",function(){var a=this.options,b=a.navigator,c=a.rangeSelector;if((b&&b.enabled||c&&c.enabled)&&(!p&&"x"===a.chart.zoomType||p&&"x"===a.chart.pinchType))return!1}),g(r,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new L(this)}),g(r,"afterSetChartSize",
function(){var a=this.legend,b=this.navigator;if(b){var c=a&&a.options;var d=b.xAxis;var e=b.yAxis;var f=b.scrollbarHeight;this.inverted?(b.left=b.opposite?this.chartWidth-f-b.height:this.spacing[3]+f,b.top=this.plotTop+f):(b.left=this.plotLeft+f,b.top=b.navigatorOptions.top||this.chartHeight-b.height-f-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(c&&"bottom"===c.verticalAlign&&"proximate"!==c.layout&&c.enabled&&!c.floating?a.legendHeight+C(c.margin,
10):0)-(this.titleOffset?this.titleOffset[2]:0));d&&e&&(this.inverted?d.options.left=e.options.left=b.left:d.options.top=e.options.top=b.top,d.setAxisSize(),e.setAxisSize())}}),g(r,"update",function(a){var b=a.options.navigator||{},c=a.options.scrollbar||{};this.navigator||this.scroller||!b.enabled&&!c.enabled||(m(!0,this.options.navigator,b),m(!0,this.options.scrollbar,c),delete a.options.navigator,delete a.options.scrollbar)}),g(r,"afterUpdate",function(a){this.navigator||this.scroller||!this.options.navigator.enabled&&
!this.options.scrollbar.enabled||(this.scroller=this.navigator=new L(this),C(a.redraw,!0)&&this.redraw(a.animation))}),g(r,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),g(z,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),r.prototype.callbacks.push(function(a){var b=a.navigator;b&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))}));t.Navigator=L;return t.Navigator});J(d,"masters/modules/gantt.src.js",
[],function(){})});
//# sourceMappingURL=gantt.js.map