/*
 Highmaps JS v8.2.2 (2020-11-23)

 (c) 2009-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/heatmap",["highcharts"],function(p){c(p);c.Highcharts=p;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function p(c,f,q,t){c.hasOwnProperty(f)||(c[f]=t.apply(null,q))}c=c?c._modules:{};p(c,"Mixins/ColorSeries.js",[],function(){return{colorPointMixin:{setVisible:function(c){var f=this,q=c?"show":"hide";f.visible=f.options.visible=
!!c;["graphic","dataLabel"].forEach(function(c){if(f[c])f[c][q]()});this.series.buildKDTree()}},colorSeriesMixin:{optionalAxis:"colorAxis",colorAxis:0,translateColors:function(){var c=this,f=this.options.nullColor,q=this.colorAxis,t=this.colorKey;(this.data.length?this.data:this.points).forEach(function(m){var n=m.getNestedProperty(t);(n=m.options.color||(m.isNull||null===m.value?f:q&&"undefined"!==typeof n?q.toColor(n,m):m.color||c.color))&&m.color!==n&&(m.color=n,"point"===c.options.legendType&&
m.legendItem&&c.chart.legend.colorizeItem(m,m.visible))})}}}});p(c,"Core/Axis/ColorAxis.js",[c["Core/Axis/Axis.js"],c["Core/Chart/Chart.js"],c["Core/Color/Color.js"],c["Mixins/ColorSeries.js"],c["Core/Animation/Fx.js"],c["Core/Globals.js"],c["Core/Legend.js"],c["Mixins/LegendSymbol.js"],c["Series/Line/LineSeries.js"],c["Core/Color/Palette.js"],c["Core/Series/Point.js"],c["Core/Utilities.js"]],function(c,f,q,t,m,n,p,D,r,E,F,u){var z=this&&this.__extends||function(){var a=function(b,d){a=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(d,e){d.__proto__=e}||function(d,e){for(var b in e)e.hasOwnProperty(b)&&(d[b]=e[b])};return a(b,d)};return function(b,d){function h(){this.constructor=b}a(b,d);b.prototype=null===d?Object.create(d):(h.prototype=d.prototype,new h)}}(),w=q.parse;q=t.colorPointMixin;t=t.colorSeriesMixin;var C=n.noop,v=u.addEvent,x=u.erase,A=u.extend,y=u.isNumber,a=u.merge,l=u.pick,I=u.splat;"";A(r.prototype,t);A(F.prototype,q);f.prototype.collectionsWithUpdate.push("colorAxis");
f.prototype.collectionsWithInit.colorAxis=[f.prototype.addColorAxis];var B=function(g){function b(d,b){var e=g.call(this,d,b)||this;e.beforePadding=!1;e.chart=void 0;e.coll="colorAxis";e.dataClasses=void 0;e.legendItem=void 0;e.legendItems=void 0;e.name="";e.options=void 0;e.stops=void 0;e.visible=!0;e.init(d,b);return e}z(b,g);b.buildOptions=function(d,b,e){d=d.options.legend||{};var k=e.layout?"vertical"!==e.layout:"vertical"!==d.layout;return a(b,{side:k?2:1,reversed:!k},e,{opposite:!k,showEmpty:!1,
title:null,visible:d.enabled&&(e?!1!==e.visible:!0)})};b.prototype.init=function(d,h){var e=b.buildOptions(d,b.defaultOptions,h);this.coll="colorAxis";g.prototype.init.call(this,d,e);h.dataClasses&&this.initDataClasses(h);this.initStops();this.horiz=!e.opposite;this.zoomEnabled=!1};b.prototype.initDataClasses=function(d){var b=this.chart,e,k=0,g=b.options.chart.colorCount,c=this.options,l=d.dataClasses.length;this.dataClasses=e=[];this.legendItems=[];d.dataClasses.forEach(function(d,h){d=a(d);e.push(d);
if(b.styledMode||!d.color)"category"===c.dataClassColor?(b.styledMode||(h=b.options.colors,g=h.length,d.color=h[k]),d.colorIndex=k,k++,k===g&&(k=0)):d.color=w(c.minColor).tweenTo(w(c.maxColor),2>l?.5:h/(l-1))})};b.prototype.hasData=function(){return!!(this.tickPositions||[]).length};b.prototype.setTickPositions=function(){if(!this.dataClasses)return g.prototype.setTickPositions.call(this)};b.prototype.initStops=function(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];
this.stops.forEach(function(d){d.color=w(d[1])})};b.prototype.setOptions=function(d){g.prototype.setOptions.call(this,d);this.options.crosshair=this.options.marker};b.prototype.setAxisSize=function(){var d=this.legendSymbol,h=this.chart,e=h.options.legend||{},k,a;d?(this.left=e=d.attr("x"),this.top=k=d.attr("y"),this.width=a=d.attr("width"),this.height=d=d.attr("height"),this.right=h.chartWidth-e-a,this.bottom=h.chartHeight-k-d,this.len=this.horiz?a:d,this.pos=this.horiz?e:k):this.len=(this.horiz?
e.symbolWidth:e.symbolHeight)||b.defaultLegendLength};b.prototype.normalizedValue=function(d){this.logarithmic&&(d=this.logarithmic.log2lin(d));return 1-(this.max-d)/(this.max-this.min||1)};b.prototype.toColor=function(d,b){var e=this.dataClasses,k=this.stops,a;if(e)for(a=e.length;a--;){var h=e[a];var g=h.from;k=h.to;if(("undefined"===typeof g||d>=g)&&("undefined"===typeof k||d<=k)){var c=h.color;b&&(b.dataClass=a,b.colorIndex=h.colorIndex);break}}else{d=this.normalizedValue(d);for(a=k.length;a--&&
!(d>k[a][0]););g=k[a]||k[a+1];k=k[a+1]||g;d=1-(k[0]-d)/(k[0]-g[0]||1);c=g.color.tweenTo(k.color,d)}return c};b.prototype.getOffset=function(){var d=this.legendGroup,b=this.chart.axisOffset[this.side];d&&(this.axisParent=d,g.prototype.getOffset.call(this),this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=b)};b.prototype.setLegendColor=function(){var d=this.reversed,b=d?1:0;d=d?0:1;b=this.horiz?[b,0,d,0]:[0,d,0,b];this.legendColor={linearGradient:{x1:b[0],
y1:b[1],x2:b[2],y2:b[3]},stops:this.stops}};b.prototype.drawLegendSymbol=function(d,a){var e=d.padding,k=d.options,g=this.horiz,h=l(k.symbolWidth,g?b.defaultLegendLength:12),c=l(k.symbolHeight,g?12:b.defaultLegendLength),f=l(k.labelPadding,g?16:30);k=l(k.itemDistance,10);this.setLegendColor();a.legendSymbol=this.chart.renderer.rect(0,d.baseline-11,h,c).attr({zIndex:1}).add(a.legendGroup);this.legendItemWidth=h+e+(g?k:f);this.legendItemHeight=c+e+(g?f:0)};b.prototype.setState=function(d){this.series.forEach(function(b){b.setState(d)})};
b.prototype.setVisible=function(){};b.prototype.getSeriesExtremes=function(){var d=this.series,b=d.length,e;this.dataMin=Infinity;for(this.dataMax=-Infinity;b--;){var a=d[b];var g=a.colorKey=l(a.options.colorKey,a.colorKey,a.pointValKey,a.zoneAxis,"y");var c=a.pointArrayMap;var G=a[g+"Min"]&&a[g+"Max"];if(a[g+"Data"])var f=a[g+"Data"];else if(c){f=[];c=c.indexOf(g);var m=a.yData;if(0<=c&&m)for(e=0;e<m.length;e++)f.push(l(m[e][c],m[e]))}else f=a.yData;G?(a.minColorValue=a[g+"Min"],a.maxColorValue=
a[g+"Max"]):(f=r.prototype.getExtremes.call(a,f),a.minColorValue=f.dataMin,a.maxColorValue=f.dataMax);"undefined"!==typeof a.minColorValue&&(this.dataMin=Math.min(this.dataMin,a.minColorValue),this.dataMax=Math.max(this.dataMax,a.maxColorValue));G||r.prototype.applyExtremes.call(a)}};b.prototype.drawCrosshair=function(d,b){var a=b&&b.plotX,c=b&&b.plotY,l=this.pos,h=this.len;if(b){var f=this.toPixels(b.getNestedProperty(b.series.colorKey));f<l?f=l-2:f>l+h&&(f=l+h+2);b.plotX=f;b.plotY=this.len-f;g.prototype.drawCrosshair.call(this,
d,b);b.plotX=a;b.plotY=c;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,!this.chart.styledMode&&this.crosshair&&this.cross.attr({fill:this.crosshair.color}))}};b.prototype.getPlotLinePath=function(d){var b=this.left,a=d.translatedValue,c=this.top;return y(a)?this.horiz?[["M",a-4,c-6],["L",a+4,c-6],["L",a,c],["Z"]]:[["M",b,a],["L",b-6,a+6],["L",b-6,a-6],["Z"]]:g.prototype.getPlotLinePath.call(this,
d)};b.prototype.update=function(d,c){var e=this.chart,l=e.legend,h=b.buildOptions(e,{},d);this.series.forEach(function(d){d.isDirtyData=!0});(d.dataClasses&&l.allItems||this.dataClasses)&&this.destroyItems();e.options[this.coll]=a(this.userOptions,h);g.prototype.update.call(this,h,c);this.legendItem&&(this.setLegendColor(),l.colorizeItem(this,!0))};b.prototype.destroyItems=function(){var d=this.chart;this.legendItem?d.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(b){d.legend.destroyItem(b)});
d.isDirtyLegend=!0};b.prototype.remove=function(d){this.destroyItems();g.prototype.remove.call(this,d)};b.prototype.getDataClassLegendSymbols=function(){var d=this,b=d.chart,a=d.legendItems,g=b.options.legend,c=g.valueDecimals,l=g.valueSuffix||"",f;a.length||d.dataClasses.forEach(function(e,g){var h=!0,k=e.from,m=e.to,n=b.numberFormatter;f="";"undefined"===typeof k?f="< ":"undefined"===typeof m&&(f="> ");"undefined"!==typeof k&&(f+=n(k,c)+l);"undefined"!==typeof k&&"undefined"!==typeof m&&(f+=" - ");
"undefined"!==typeof m&&(f+=n(m,c)+l);a.push(A({chart:b,name:f,options:{},drawLegendSymbol:D.drawRectangle,visible:!0,setState:C,isDataClass:!0,setVisible:function(){h=d.visible=!h;d.series.forEach(function(b){b.points.forEach(function(b){b.dataClass===g&&b.setVisible(h)})});b.legend.colorizeItem(this,h)}},e))});return a};b.defaultLegendLength=200;b.defaultOptions={lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},
width:.01,color:E.neutralColor40},labels:{overflow:"justify",rotation:0},minColor:E.highlightColor10,maxColor:E.highlightColor100,tickLength:5,showInLegend:!0};b.keepProps=["legendGroup","legendItemHeight","legendItemWidth","legendItem","legendSymbol"];return b}(c);Array.prototype.push.apply(c.keepProps,B.keepProps);n.ColorAxis=B;["fill","stroke"].forEach(function(a){m.prototype[a+"Setter"]=function(){this.elem.attr(a,w(this.start).tweenTo(w(this.end),this.pos),null,!0)}});v(f,"afterGetAxes",function(){var a=
this,b=a.options;this.colorAxis=[];b.colorAxis&&(b.colorAxis=I(b.colorAxis),b.colorAxis.forEach(function(b,c){b.index=c;new B(a,b)}))});v(r,"bindAxes",function(){var a=this.axisTypes;a?-1===a.indexOf("colorAxis")&&a.push("colorAxis"):this.axisTypes=["colorAxis"]});v(p,"afterGetAllItems",function(a){var b=[],d,c;(this.chart.colorAxis||[]).forEach(function(e){(d=e.options)&&d.showInLegend&&(d.dataClasses&&d.visible?b=b.concat(e.getDataClassLegendSymbols()):d.visible&&b.push(e),e.series.forEach(function(b){if(!b.options.showInLegend||
d.dataClasses)"point"===b.options.legendType?b.points.forEach(function(b){x(a.allItems,b)}):x(a.allItems,b)}))});for(c=b.length;c--;)a.allItems.unshift(b[c])});v(p,"afterColorizeItem",function(a){a.visible&&a.item.legendColor&&a.item.legendSymbol.attr({fill:a.item.legendColor})});v(p,"afterUpdate",function(){var a=this.chart.colorAxis;a&&a.forEach(function(b,a,c){b.update({},c)})});v(r,"afterTranslate",function(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()});
return B});p(c,"Mixins/ColorMapSeries.js",[c["Core/Globals.js"],c["Core/Series/Point.js"],c["Core/Utilities.js"]],function(c,f,q){var p=q.defined;return{colorMapPointMixin:{dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value},setState:function(c){f.prototype.setState.call(this,c);this.graphic&&this.graphic.attr({zIndex:"hover"===c?1:0})}},colorMapSeriesMixin:{pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group",
"markerGroup","dataLabelsGroup"],getSymbol:c.noop,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:c.seriesTypes.column.prototype.pointAttribs,colorAttribs:function(c){var f={};p(c.color)&&(f[this.colorProp||"fill"]=c.color);return f}}}});p(c,"Series/HeatmapSeries.js",[c["Core/Series/Series.js"],c["Mixins/ColorMapSeries.js"],c["Core/Globals.js"],c["Core/Series/Point.js"],c["Mixins/LegendSymbol.js"],c["Series/Line/LineSeries.js"],c["Core/Color/Palette.js"],c["Core/Renderer/SVG/SVGRenderer.js"],
c["Core/Utilities.js"]],function(c,f,q,p,m,n,H,D,r){var t=c.seriesTypes,F=f.colorMapPointMixin;f=f.colorMapSeriesMixin;var u=q.noop,z=r.clamp,w=r.extend,C=r.fireEvent,v=r.isNumber,x=r.merge,A=r.pick,y=D.prototype.symbols;"";c.seriesType("heatmap","scatter",{animation:!1,borderWidth:0,nullColor:H.neutralColor3,dataLabels:{formatter:function(){return this.point.value},inside:!0,verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},
select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}}},x(f,{pointArrayMap:["y","value"],hasPointSpecificOptions:!0,getExtremesFromAll:!0,directTouch:!0,init:function(){n.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=A(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=a.rowsize||1;w(y,{ellipse:y.circle,rect:y.square})},getSymbol:n.prototype.getSymbol,setClip:function(a){var c=this.chart;
n.prototype.setClip.apply(this,arguments);(!1!==this.options.clip||a)&&this.markerGroup.clip((a||this.clipBox)&&this.sharedClipKey?c[this.sharedClipKey]:c.clipRect)},translate:function(){var a=this.options,c=a.marker&&a.marker.symbol||"",f=y[c]?c:"rect";a=this.options;var m=-1!==["circle","square"].indexOf(f);this.generatePoints();this.points.forEach(function(a){var b=a.getCellAttributes(),d={x:Math.min(b.x1,b.x2),y:Math.min(b.y1,b.y2),width:Math.max(Math.abs(b.x2-b.x1),0),height:Math.max(Math.abs(b.y2-
b.y1),0)};var l=a.hasImage=0===(a.marker&&a.marker.symbol||c||"").indexOf("url");if(m){var e=Math.abs(d.width-d.height);d.x=Math.min(b.x1,b.x2)+(d.width<d.height?0:e/2);d.y=Math.min(b.y1,b.y2)+(d.width<d.height?e/2:0);d.width=d.height=Math.min(d.width,d.height)}e={plotX:(b.x1+b.x2)/2,plotY:(b.y1+b.y2)/2,clientX:(b.x1+b.x2)/2,shapeType:"path",shapeArgs:x(!0,d,{d:y[f](d.x,d.y,d.width,d.height)})};l&&(a.marker={width:d.width,height:d.height});w(a,e)});C(this,"afterTranslate")},pointAttribs:function(a,
c){var l=n.prototype.pointAttribs.call(this,a,c),f=this.options||{},g=this.chart.options.plotOptions||{},b=g.series||{},d=g.heatmap||{};g=f.borderColor||d.borderColor||b.borderColor;b=f.borderWidth||d.borderWidth||b.borderWidth||l["stroke-width"];l.stroke=a&&a.marker&&a.marker.lineColor||f.marker&&f.marker.lineColor||g||this.color;l["stroke-width"]=b;c&&(a=x(f.states[c],f.marker&&f.marker.states[c],a.options.states&&a.options.states[c]||{}),c=a.brightness,l.fill=a.color||q.color(l.fill).brighten(c||
0).get(),l.stroke=a.lineColor);return l},markerAttribs:function(a,c){var f=a.marker||{},l=this.options.marker||{},g=a.shapeArgs||{},b={};if(a.hasImage)return{x:a.plotX,y:a.plotY};if(c){var d=l.states[c]||{};var h=f.states&&f.states[c]||{};[["width","x"],["height","y"]].forEach(function(a){b[a[0]]=(h[a[0]]||d[a[0]]||g[a[0]])+(h[a[0]+"Plus"]||d[a[0]+"Plus"]||0);b[a[1]]=g[a[1]]+(g[a[0]]-b[a[0]])/2})}return c?b:g},drawPoints:function(){var a=this;if((this.options.marker||{}).enabled||this._hasPointMarkers)n.prototype.drawPoints.call(this),
this.points.forEach(function(c){c.graphic&&c.graphic[a.chart.styledMode?"css":"animate"](a.colorAttribs(c))})},hasData:function(){return!!this.processedXData.length},getValidPoints:function(a,c){return n.prototype.getValidPoints.call(this,a,c,!0)},getBox:u,drawLegendSymbol:m.drawRectangle,alignDataLabel:t.column.prototype.alignDataLabel,getExtremes:function(){var a=n.prototype.getExtremes.call(this,this.valueData),c=a.dataMin;a=a.dataMax;v(c)&&(this.valueMin=c);v(a)&&(this.valueMax=a);return n.prototype.getExtremes.call(this)}}),
x(F,{applyOptions:function(a,c){a=p.prototype.applyOptions.call(this,a,c);a.formatPrefix=a.isNull||null===a.value?"null":"point";return a},isValid:function(){return Infinity!==this.value&&-Infinity!==this.value},haloPath:function(a){if(!a)return[];var c=this.shapeArgs;return["M",c.x-a,c.y-a,"L",c.x-a,c.y+c.height+a,c.x+c.width+a,c.y+c.height+a,c.x+c.width+a,c.y-a,"Z"]},getCellAttributes:function(){var a=this.series,c=a.options,f=(c.colsize||1)/2,m=(c.rowsize||1)/2,g=a.xAxis,b=a.yAxis,d=this.options.marker||
a.options.marker;a=a.pointPlacementToXValue();var h=A(this.pointPadding,c.pointPadding,0),e={x1:z(Math.round(g.len-(g.translate(this.x-f,!1,!0,!1,!0,-a)||0)),-g.len,2*g.len),x2:z(Math.round(g.len-(g.translate(this.x+f,!1,!0,!1,!0,-a)||0)),-g.len,2*g.len),y1:z(Math.round(b.translate(this.y-m,!1,!0,!1,!0)||0),-b.len,2*b.len),y2:z(Math.round(b.translate(this.y+m,!1,!0,!1,!0)||0),-b.len,2*b.len)};[["width","x"],["height","y"]].forEach(function(a){var b=a[0];a=a[1];var c=a+"1",f=a+"2",g=Math.abs(e[c]-
e[f]),k=d&&d.lineWidth||0,l=Math.abs(e[c]+e[f])/2;d[b]&&d[b]<g&&(e[c]=l-d[b]/2-k/2,e[f]=l+d[b]/2+k/2);h&&("y"===a&&(c=f,f=a+"1"),e[c]+=h,e[f]-=h)});return e}}));""});p(c,"masters/modules/heatmap.src.js",[],function(){})});
//# sourceMappingURL=heatmap.js.map