/*
 Highcharts JS v8.2.2 (2020-11-23)

 (c) 2009-2019 Sebastian Bochan, Rafal Sebestjanski

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/lollipop",["highcharts"],function(e){a(e);a.Highcharts=e;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function e(a,d,e,f){a.hasOwnProperty(d)||(a[d]=f.apply(null,e))}a=a?a._modules:{};e(a,"Series/ColumnRangeSeries.js",[a["Core/Series/Series.js"],a["Series/Column/ColumnSeries.js"],a["Core/Globals.js"],a["Core/Options.js"],
a["Core/Utilities.js"]],function(a,d,e,f,h){var c=d.prototype;d=e.noop;f=f.defaultOptions;var t=h.clamp,q=h.merge,n=h.pick,m=a.seriesTypes.arearange.prototype;a.seriesType("columnrange","arearange",q(f.plotOptions.column,f.plotOptions.arearange,{pointRange:null,marker:null,states:{hover:{halo:!1}}}),{setOptions:function(){q(!0,arguments[0],{stacking:void 0});return m.setOptions.apply(this,arguments)},translate:function(){var a=this,d=a.yAxis,l=a.xAxis,b=l.startAngleRad,u,r=a.chart,y=a.xAxis.isRadial,
g=Math.max(r.chartWidth,r.chartHeight)+999,v;c.translate.apply(a);a.points.forEach(function(c){var h=c.shapeArgs,e=a.options.minPointLength;c.plotHigh=v=t(d.translate(c.high,0,1,0,1),-g,g);c.plotLow=t(c.plotY,-g,g);var f=v;var k=n(c.rectPlotY,c.plotY)-v;Math.abs(k)<e?(e-=k,k+=e,f-=e/2):0>k&&(k*=-1,f-=k);y?(u=c.barX+b,c.shapeType="arc",c.shapeArgs=a.polarArc(f+k,f,u,u+c.pointWidth)):(h.height=k,h.y=f,c.tooltipPos=r.inverted?[d.len+d.pos-r.plotLeft-f-k/2,l.len+l.pos-r.plotTop-h.x-h.width/2,k]:[l.left-
r.plotLeft+h.x+h.width/2,d.pos-r.plotTop+f+k/2,k])})},directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:d,getSymbol:d,crispCol:function(){return c.crispCol.apply(this,arguments)},drawPoints:function(){return c.drawPoints.apply(this,arguments)},drawTracker:function(){return c.drawTracker.apply(this,arguments)},getColumnMetrics:function(){return c.getColumnMetrics.apply(this,arguments)},pointAttribs:function(){return c.pointAttribs.apply(this,arguments)},adjustForMissingColumns:function(){return c.adjustForMissingColumns.apply(this,
arguments)},animate:function(){return c.animate.apply(this,arguments)},polarArc:function(){return c.polarArc.apply(this,arguments)},translate3dPoints:function(){return c.translate3dPoints.apply(this,arguments)},translate3dShapes:function(){return c.translate3dShapes.apply(this,arguments)}},{setState:c.pointClass.prototype.setState});""});e(a,"Series/DumbbellSeries.js",[a["Core/Series/Series.js"],a["Series/Column/ColumnSeries.js"],a["Series/Line/LineSeries.js"],a["Core/Color/Palette.js"],a["Core/Renderer/SVG/SVGRenderer.js"],
a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,d,e,f,h,c,t){var q=a.seriesTypes,n=q.arearange.prototype,m=d.prototype,x=e.prototype,w=t.extend,l=t.pick;d=n.pointClass.prototype;a.seriesType("dumbbell","arearange",{trackByArea:!1,fillColor:"none",lineWidth:0,pointRange:1,connectorWidth:1,stickyTracking:!1,groupPadding:.2,crisp:!1,pointPadding:.1,lowColor:f.neutralColor80,states:{hover:{lineWidthPlus:0,connectorWidthPlus:1,halo:!1}}},{trackerGroups:["group","markerGroup","dataLabelsGroup"],
drawTracker:c.TrackerMixin.drawTrackerPoint,drawGraph:c.noop,crispCol:m.crispCol,getConnectorAttribs:function(b){var a=this.chart,c=b.options,d=this.options,g=this.xAxis,e=this.yAxis,f=l(c.connectorWidth,d.connectorWidth),n=l(c.connectorColor,d.connectorColor,c.color,b.zone?b.zone.color:void 0,b.color),q=l(d.states&&d.states.hover&&d.states.hover.connectorWidthPlus,1),m=l(c.dashStyle,d.dashStyle),k=l(b.plotLow,b.plotY),p=e.toPixels(d.threshold||0,!0);p=l(b.plotHigh,a.inverted?e.len-p:p);b.state&&
(f+=q);0>k?k=0:k>=e.len&&(k=e.len);0>p?p=0:p>=e.len&&(p=e.len);if(0>b.plotX||b.plotX>g.len)f=0;b.upperGraphic&&(g={y:b.y,zone:b.zone},b.y=b.high,b.zone=b.zone?b.getZone():void 0,n=l(c.connectorColor,d.connectorColor,c.color,b.zone?b.zone.color:void 0,b.color),w(b,g));b={d:h.prototype.crispLine([["M",b.plotX,k],["L",b.plotX,p]],f,"ceil")};a.styledMode||(b.stroke=n,b["stroke-width"]=f,m&&(b.dashstyle=m));return b},drawConnector:function(b){var a=l(this.options.animationLimit,250);a=b.connector&&this.chart.pointCount<
a?"animate":"attr";b.connector||(b.connector=this.chart.renderer.path().addClass("highcharts-lollipop-stem").attr({zIndex:-1}).add(this.markerGroup));b.connector[a](this.getConnectorAttribs(b))},getColumnMetrics:function(){var b=m.getColumnMetrics.apply(this,arguments);b.offset+=b.width/2;return b},translatePoint:n.translate,setShapeArgs:q.columnrange.prototype.translate,translate:function(){this.setShapeArgs.apply(this);this.translatePoint.apply(this,arguments);this.points.forEach(function(b){var a=
b.shapeArgs,c=b.pointWidth;b.plotX=a.x;a.x=b.plotX-c/2;b.tooltipPos=null});this.columnMetrics.offset-=this.columnMetrics.width/2},seriesDrawPoints:n.drawPoints,drawPoints:function(){var b=this.chart,a=this.points.length,c=this.lowColor=this.options.lowColor,d=0;for(this.seriesDrawPoints.apply(this,arguments);d<a;){var g=this.points[d];this.drawConnector(g);g.upperGraphic&&(g.upperGraphic.element.point=g,g.upperGraphic.addClass("highcharts-lollipop-high"));g.connector.element.point=g;if(g.lowerGraphic){var e=
g.zone&&g.zone.color;e=l(g.options.lowColor,c,g.options.color,e,g.color,this.color);b.styledMode||g.lowerGraphic.attr({fill:e});g.lowerGraphic.addClass("highcharts-lollipop-low")}d++}},markerAttribs:function(){var b=n.markerAttribs.apply(this,arguments);b.x=Math.floor(b.x);b.y=Math.floor(b.y);return b},pointAttribs:function(b,a){var c=x.pointAttribs.apply(this,arguments);"hover"===a&&delete c.fill;return c}},{destroyElements:d.destroyElements,isValid:d.isValid,pointSetState:d.setState,setState:function(){var a=
this.series,c=a.chart,d=a.options.marker,e=this.options,g=l(e.lowColor,a.options.lowColor,e.color,this.zone&&this.zone.color,this.color,a.color),f="attr";this.pointSetState.apply(this,arguments);this.state||(f="animate",this.lowerGraphic&&!c.styledMode&&(this.lowerGraphic.attr({fill:g}),this.upperGraphic&&(c={y:this.y,zone:this.zone},this.y=this.high,this.zone=this.zone?this.getZone():void 0,d=l(this.marker?this.marker.fillColor:void 0,d?d.fillColor:void 0,e.color,this.zone?this.zone.color:void 0,
this.color),this.upperGraphic.attr({fill:d}),w(this,c))));this.connector[f](a.getConnectorAttribs(this))}});""});e(a,"Series/LollipopSeries.js",[a["Core/Series/Series.js"],a["Series/Column/ColumnSeries.js"],a["Core/Globals.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,d,e,f,h){d=d.prototype;var c=h.isObject,m=h.pick;h=a.seriesTypes.area.prototype;a.seriesType("lollipop","dumbbell",{lowColor:void 0,threshold:0,connectorWidth:1,groupPadding:.2,pointPadding:.1,states:{hover:{lineWidthPlus:0,
connectorWidthPlus:1,halo:!1}},tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.y}</b><br/>'}},{pointArrayMap:["y"],pointValKey:"y",toYData:function(a){return[m(a.y,a.low)]},translatePoint:h.translate,drawPoint:h.drawPoints,drawDataLabels:d.drawDataLabels,setShapeArgs:d.translate},{pointSetState:h.pointClass.prototype.setState,setState:e.seriesTypes.dumbbell.prototype.pointClass.prototype.setState,init:function(a,d,e){c(d)&&"low"in d&&(d.y=d.low,delete d.low);
return f.prototype.init.apply(this,arguments)}});""});e(a,"masters/modules/lollipop.src.js",[],function(){})});
//# sourceMappingURL=lollipop.js.map