/*
 Highmaps JS v8.2.2 (2020-11-23)

 Highmaps as a plugin for Highcharts or Highstock.

 (c) 2011-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/map",["highcharts"],function(u){a(u);a.Highcharts=u;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function u(a,e,m,t){a.hasOwnProperty(e)||(a[e]=t.apply(null,m))}a=a?a._modules:{};u(a,"Core/Axis/MapAxis.js",[a["Core/Axis/Axis.js"],a["Core/Utilities.js"]],function(a,e){var m=e.addEvent,t=e.pick,r=function(){return function(a){this.axis=
a}}();e=function(){function a(){}a.compose=function(a){a.keepProps.push("mapAxis");m(a,"init",function(){this.mapAxis||(this.mapAxis=new r(this))});m(a,"getSeriesExtremes",function(){if(this.mapAxis){var a=[];this.isXAxis&&(this.series.forEach(function(h,b){h.useMapGeometry&&(a[b]=h.xData,h.xData=[])}),this.mapAxis.seriesXData=a)}});m(a,"afterGetSeriesExtremes",function(){if(this.mapAxis){var a=this.mapAxis.seriesXData||[],h;if(this.isXAxis){var b=t(this.dataMin,Number.MAX_VALUE);var g=t(this.dataMax,
-Number.MAX_VALUE);this.series.forEach(function(f,x){f.useMapGeometry&&(b=Math.min(b,t(f.minX,b)),g=Math.max(g,t(f.maxX,g)),f.xData=a[x],h=!0)});h&&(this.dataMin=b,this.dataMax=g);this.mapAxis.seriesXData=void 0}}});m(a,"afterSetAxisTranslation",function(){if(this.mapAxis){var a=this.chart,h=a.plotWidth/a.plotHeight;a=a.xAxis[0];var b;"yAxis"===this.coll&&"undefined"!==typeof a.transA&&this.series.forEach(function(a){a.preserveAspectRatio&&(b=!0)});if(b&&(this.transA=a.transA=Math.min(this.transA,
a.transA),h/=(a.max-a.min)/(this.max-this.min),h=1>h?this:a,a=(h.max-h.min)*h.transA,h.mapAxis.pixelPadding=h.len-a,h.minPixelPadding=h.mapAxis.pixelPadding/2,a=h.mapAxis.fixTo)){a=a[1]-h.toValue(a[0],!0);a*=h.transA;if(Math.abs(a)>h.minPixelPadding||h.min===h.dataMin&&h.max===h.dataMax)a=0;h.minPixelPadding-=a}}});m(a,"render",function(){this.mapAxis&&(this.mapAxis.fixTo=void 0)})};return a}();e.compose(a);return e});u(a,"Mixins/ColorSeries.js",[],function(){return{colorPointMixin:{setVisible:function(a){var e=
this,m=a?"show":"hide";e.visible=e.options.visible=!!a;["graphic","dataLabel"].forEach(function(a){if(e[a])e[a][m]()});this.series.buildKDTree()}},colorSeriesMixin:{optionalAxis:"colorAxis",colorAxis:0,translateColors:function(){var a=this,e=this.options.nullColor,m=this.colorAxis,t=this.colorKey;(this.data.length?this.data:this.points).forEach(function(r){var k=r.getNestedProperty(t);(k=r.options.color||(r.isNull||null===r.value?e:m&&"undefined"!==typeof k?m.toColor(k,r):r.color||a.color))&&r.color!==
k&&(r.color=k,"point"===a.options.legendType&&r.legendItem&&a.chart.legend.colorizeItem(r,r.visible))})}}}});u(a,"Core/Axis/ColorAxis.js",[a["Core/Axis/Axis.js"],a["Core/Chart/Chart.js"],a["Core/Color/Color.js"],a["Mixins/ColorSeries.js"],a["Core/Animation/Fx.js"],a["Core/Globals.js"],a["Core/Legend.js"],a["Mixins/LegendSymbol.js"],a["Series/Line/LineSeries.js"],a["Core/Color/Palette.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,e,m,t,r,k,c,A,h,b,g,f){var x=this&&this.__extends||
function(){var d=function(n,q){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(p,q){p.__proto__=q}||function(p,q){for(var d in q)q.hasOwnProperty(d)&&(p[d]=q[d])};return d(n,q)};return function(n,q){function p(){this.constructor=n}d(n,q);n.prototype=null===q?Object.create(q):(p.prototype=q.prototype,new p)}}(),E=m.parse;m=t.colorPointMixin;t=t.colorSeriesMixin;var F=k.noop,z=f.addEvent,D=f.erase,C=f.extend,y=f.isNumber,d=f.merge,n=f.pick,v=f.splat;"";C(h.prototype,t);C(g.prototype,
m);e.prototype.collectionsWithUpdate.push("colorAxis");e.prototype.collectionsWithInit.colorAxis=[e.prototype.addColorAxis];var B=function(a){function l(q,p){var d=a.call(this,q,p)||this;d.beforePadding=!1;d.chart=void 0;d.coll="colorAxis";d.dataClasses=void 0;d.legendItem=void 0;d.legendItems=void 0;d.name="";d.options=void 0;d.stops=void 0;d.visible=!0;d.init(q,p);return d}x(l,a);l.buildOptions=function(q,p,n){q=q.options.legend||{};var a=n.layout?"vertical"!==n.layout:"vertical"!==q.layout;return d(p,
{side:a?2:1,reversed:!a},n,{opposite:!a,showEmpty:!1,title:null,visible:q.enabled&&(n?!1!==n.visible:!0)})};l.prototype.init=function(q,p){var d=l.buildOptions(q,l.defaultOptions,p);this.coll="colorAxis";a.prototype.init.call(this,q,d);p.dataClasses&&this.initDataClasses(p);this.initStops();this.horiz=!d.opposite;this.zoomEnabled=!1};l.prototype.initDataClasses=function(q){var p=this.chart,n,a=0,l=p.options.chart.colorCount,f=this.options,b=q.dataClasses.length;this.dataClasses=n=[];this.legendItems=
[];q.dataClasses.forEach(function(q,G){q=d(q);n.push(q);if(p.styledMode||!q.color)"category"===f.dataClassColor?(p.styledMode||(G=p.options.colors,l=G.length,q.color=G[a]),q.colorIndex=a,a++,a===l&&(a=0)):q.color=E(f.minColor).tweenTo(E(f.maxColor),2>b?.5:G/(b-1))})};l.prototype.hasData=function(){return!!(this.tickPositions||[]).length};l.prototype.setTickPositions=function(){if(!this.dataClasses)return a.prototype.setTickPositions.call(this)};l.prototype.initStops=function(){this.stops=this.options.stops||
[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(q){q.color=E(q[1])})};l.prototype.setOptions=function(q){a.prototype.setOptions.call(this,q);this.options.crosshair=this.options.marker};l.prototype.setAxisSize=function(){var q=this.legendSymbol,p=this.chart,d=p.options.legend||{},a,n;q?(this.left=d=q.attr("x"),this.top=a=q.attr("y"),this.width=n=q.attr("width"),this.height=q=q.attr("height"),this.right=p.chartWidth-d-n,this.bottom=p.chartHeight-a-q,this.len=this.horiz?
n:q,this.pos=this.horiz?d:a):this.len=(this.horiz?d.symbolWidth:d.symbolHeight)||l.defaultLegendLength};l.prototype.normalizedValue=function(d){this.logarithmic&&(d=this.logarithmic.log2lin(d));return 1-(this.max-d)/(this.max-this.min||1)};l.prototype.toColor=function(d,p){var q=this.dataClasses,a=this.stops,n;if(q)for(n=q.length;n--;){var l=q[n];var f=l.from;a=l.to;if(("undefined"===typeof f||d>=f)&&("undefined"===typeof a||d<=a)){var b=l.color;p&&(p.dataClass=n,p.colorIndex=l.colorIndex);break}}else{d=
this.normalizedValue(d);for(n=a.length;n--&&!(d>a[n][0]););f=a[n]||a[n+1];a=a[n+1]||f;d=1-(a[0]-d)/(a[0]-f[0]||1);b=f.color.tweenTo(a.color,d)}return b};l.prototype.getOffset=function(){var d=this.legendGroup,p=this.chart.axisOffset[this.side];d&&(this.axisParent=d,a.prototype.getOffset.call(this),this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=p)};l.prototype.setLegendColor=function(){var d=this.reversed,p=d?1:0;d=d?0:1;p=this.horiz?[p,0,d,
0]:[0,d,0,p];this.legendColor={linearGradient:{x1:p[0],y1:p[1],x2:p[2],y2:p[3]},stops:this.stops}};l.prototype.drawLegendSymbol=function(d,p){var a=d.padding,q=d.options,f=this.horiz,b=n(q.symbolWidth,f?l.defaultLegendLength:12),g=n(q.symbolHeight,f?12:l.defaultLegendLength),v=n(q.labelPadding,f?16:30);q=n(q.itemDistance,10);this.setLegendColor();p.legendSymbol=this.chart.renderer.rect(0,d.baseline-11,b,g).attr({zIndex:1}).add(p.legendGroup);this.legendItemWidth=b+a+(f?q:v);this.legendItemHeight=
g+a+(f?v:0)};l.prototype.setState=function(d){this.series.forEach(function(p){p.setState(d)})};l.prototype.setVisible=function(){};l.prototype.getSeriesExtremes=function(){var d=this.series,p=d.length,a;this.dataMin=Infinity;for(this.dataMax=-Infinity;p--;){var l=d[p];var f=l.colorKey=n(l.options.colorKey,l.colorKey,l.pointValKey,l.zoneAxis,"y");var b=l.pointArrayMap;var g=l[f+"Min"]&&l[f+"Max"];if(l[f+"Data"])var v=l[f+"Data"];else if(b){v=[];b=b.indexOf(f);var w=l.yData;if(0<=b&&w)for(a=0;a<w.length;a++)v.push(n(w[a][b],
w[a]))}else v=l.yData;g?(l.minColorValue=l[f+"Min"],l.maxColorValue=l[f+"Max"]):(v=h.prototype.getExtremes.call(l,v),l.minColorValue=v.dataMin,l.maxColorValue=v.dataMax);"undefined"!==typeof l.minColorValue&&(this.dataMin=Math.min(this.dataMin,l.minColorValue),this.dataMax=Math.max(this.dataMax,l.maxColorValue));g||h.prototype.applyExtremes.call(l)}};l.prototype.drawCrosshair=function(d,p){var n=p&&p.plotX,l=p&&p.plotY,q=this.pos,f=this.len;if(p){var b=this.toPixels(p.getNestedProperty(p.series.colorKey));
b<q?b=q-2:b>q+f&&(b=q+f+2);p.plotX=b;p.plotY=this.len-b;a.prototype.drawCrosshair.call(this,d,p);p.plotX=n;p.plotY=l;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,!this.chart.styledMode&&this.crosshair&&this.cross.attr({fill:this.crosshair.color}))}};l.prototype.getPlotLinePath=function(d){var p=this.left,n=d.translatedValue,l=this.top;return y(n)?this.horiz?[["M",n-4,l-6],["L",n+
4,l-6],["L",n,l],["Z"]]:[["M",p,n],["L",p-6,n+6],["L",p-6,n-6],["Z"]]:a.prototype.getPlotLinePath.call(this,d)};l.prototype.update=function(n,p){var q=this.chart,f=q.legend,b=l.buildOptions(q,{},n);this.series.forEach(function(d){d.isDirtyData=!0});(n.dataClasses&&f.allItems||this.dataClasses)&&this.destroyItems();q.options[this.coll]=d(this.userOptions,b);a.prototype.update.call(this,b,p);this.legendItem&&(this.setLegendColor(),f.colorizeItem(this,!0))};l.prototype.destroyItems=function(){var d=
this.chart;this.legendItem?d.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(p){d.legend.destroyItem(p)});d.isDirtyLegend=!0};l.prototype.remove=function(d){this.destroyItems();a.prototype.remove.call(this,d)};l.prototype.getDataClassLegendSymbols=function(){var d=this,p=d.chart,n=d.legendItems,a=p.options.legend,l=a.valueDecimals,f=a.valueSuffix||"",b;n.length||d.dataClasses.forEach(function(a,q){var g=!0,v=a.from,h=a.to,w=p.numberFormatter;b="";"undefined"===typeof v?
b="< ":"undefined"===typeof h&&(b="> ");"undefined"!==typeof v&&(b+=w(v,l)+f);"undefined"!==typeof v&&"undefined"!==typeof h&&(b+=" - ");"undefined"!==typeof h&&(b+=w(h,l)+f);n.push(C({chart:p,name:b,options:{},drawLegendSymbol:A.drawRectangle,visible:!0,setState:F,isDataClass:!0,setVisible:function(){g=d.visible=!g;d.series.forEach(function(d){d.points.forEach(function(d){d.dataClass===q&&d.setVisible(g)})});p.legend.colorizeItem(this,g)}},a))});return n};l.defaultLegendLength=200;l.defaultOptions=
{lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:b.neutralColor40},labels:{overflow:"justify",rotation:0},minColor:b.highlightColor10,maxColor:b.highlightColor100,tickLength:5,showInLegend:!0};l.keepProps=["legendGroup","legendItemHeight","legendItemWidth","legendItem","legendSymbol"];return l}(a);Array.prototype.push.apply(a.keepProps,B.keepProps);k.ColorAxis=B;["fill","stroke"].forEach(function(d){r.prototype[d+
"Setter"]=function(){this.elem.attr(d,E(this.start).tweenTo(E(this.end),this.pos),null,!0)}});z(e,"afterGetAxes",function(){var d=this,a=d.options;this.colorAxis=[];a.colorAxis&&(a.colorAxis=v(a.colorAxis),a.colorAxis.forEach(function(a,p){a.index=p;new B(d,a)}))});z(h,"bindAxes",function(){var d=this.axisTypes;d?-1===d.indexOf("colorAxis")&&d.push("colorAxis"):this.axisTypes=["colorAxis"]});z(c,"afterGetAllItems",function(d){var a=[],n,p;(this.chart.colorAxis||[]).forEach(function(p){(n=p.options)&&
n.showInLegend&&(n.dataClasses&&n.visible?a=a.concat(p.getDataClassLegendSymbols()):n.visible&&a.push(p),p.series.forEach(function(a){if(!a.options.showInLegend||n.dataClasses)"point"===a.options.legendType?a.points.forEach(function(a){D(d.allItems,a)}):D(d.allItems,a)}))});for(p=a.length;p--;)d.allItems.unshift(a[p])});z(c,"afterColorizeItem",function(d){d.visible&&d.item.legendColor&&d.item.legendSymbol.attr({fill:d.item.legendColor})});z(c,"afterUpdate",function(){var d=this.chart.colorAxis;d&&
d.forEach(function(d,a,p){d.update({},p)})});z(h,"afterTranslate",function(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()});return B});u(a,"Mixins/ColorMapSeries.js",[a["Core/Globals.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,e,m){var t=m.defined;return{colorMapPointMixin:{dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value},setState:function(a){e.prototype.setState.call(this,
a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})}},colorMapSeriesMixin:{pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:a.noop,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:a.seriesTypes.column.prototype.pointAttribs,colorAttribs:function(a){var r={};t(a.color)&&(r[this.colorProp||"fill"]=a.color);return r}}}});u(a,"Maps/MapNavigation.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],
function(a,e,m){function t(a){a&&(a.preventDefault&&a.preventDefault(),a.stopPropagation&&a.stopPropagation(),a.cancelBubble=!0)}function r(a){this.init(a)}var k=e.doc,c=m.addEvent,A=m.extend,h=m.merge,b=m.objectEach,g=m.pick;r.prototype.init=function(a){this.chart=a;a.mapNavButtons=[]};r.prototype.update=function(a){var f=this.chart,r=f.options.mapNavigation,k,e,m,C,y,d=function(d){this.handler.call(f,d);t(d)},n=f.mapNavButtons;a&&(r=f.options.mapNavigation=h(f.options.mapNavigation,a));for(;n.length;)n.pop().destroy();
g(r.enableButtons,r.enabled)&&!f.renderer.forExport&&b(r.buttons,function(a,b){k=h(r.buttonOptions,a);f.styledMode||(e=k.theme,e.style=h(k.theme.style,k.style),C=(m=e.states)&&m.hover,y=m&&m.select);a=f.renderer.button(k.text,0,0,d,e,C,y,0,"zoomIn"===b?"topbutton":"bottombutton").addClass("highcharts-map-navigation highcharts-"+{zoomIn:"zoom-in",zoomOut:"zoom-out"}[b]).attr({width:k.width,height:k.height,title:f.options.lang[b],padding:k.padding,zIndex:5}).add();a.handler=k.onclick;c(a.element,"dblclick",
t);n.push(a);var g=k,l=c(f,"load",function(){a.align(A(g,{width:a.width,height:2*a.height}),null,g.alignTo);l()})});this.updateEvents(r)};r.prototype.updateEvents=function(a){var b=this.chart;g(a.enableDoubleClickZoom,a.enabled)||a.enableDoubleClickZoomTo?this.unbindDblClick=this.unbindDblClick||c(b.container,"dblclick",function(a){b.pointer.onContainerDblClick(a)}):this.unbindDblClick&&(this.unbindDblClick=this.unbindDblClick());g(a.enableMouseWheelZoom,a.enabled)?this.unbindMouseWheel=this.unbindMouseWheel||
c(b.container,"undefined"===typeof k.onmousewheel?"DOMMouseScroll":"mousewheel",function(a){b.pointer.onContainerMouseWheel(a);t(a);return!1}):this.unbindMouseWheel&&(this.unbindMouseWheel=this.unbindMouseWheel())};A(a.prototype,{fitToBox:function(a,b){[["x","width"],["y","height"]].forEach(function(f){var g=f[0];f=f[1];a[g]+a[f]>b[g]+b[f]&&(a[f]>b[f]?(a[f]=b[f],a[g]=b[g]):a[g]=b[g]+b[f]-a[f]);a[f]>b[f]&&(a[f]=b[f]);a[g]<b[g]&&(a[g]=b[g])});return a},mapZoom:function(a,b,h,r,k){var f=this.xAxis[0],
c=f.max-f.min,e=g(b,f.min+c/2),d=c*a;c=this.yAxis[0];var n=c.max-c.min,v=g(h,c.min+n/2);n*=a;e=this.fitToBox({x:e-d*(r?(r-f.pos)/f.len:.5),y:v-n*(k?(k-c.pos)/c.len:.5),width:d,height:n},{x:f.dataMin,y:c.dataMin,width:f.dataMax-f.dataMin,height:c.dataMax-c.dataMin});d=e.x<=f.dataMin&&e.width>=f.dataMax-f.dataMin&&e.y<=c.dataMin&&e.height>=c.dataMax-c.dataMin;r&&f.mapAxis&&(f.mapAxis.fixTo=[r-f.pos,b]);k&&c.mapAxis&&(c.mapAxis.fixTo=[k-c.pos,h]);"undefined"===typeof a||d?(f.setExtremes(void 0,void 0,
!1),c.setExtremes(void 0,void 0,!1)):(f.setExtremes(e.x,e.x+e.width,!1),c.setExtremes(e.y,e.y+e.height,!1));this.redraw()}});c(a,"beforeRender",function(){this.mapNavigation=new r(this);this.mapNavigation.update()});e.MapNavigation=r});u(a,"Maps/MapPointer.js",[a["Core/Pointer.js"],a["Core/Utilities.js"]],function(a,e){var m=e.extend,t=e.pick;e=e.wrap;m(a.prototype,{onContainerDblClick:function(a){var k=this.chart;a=this.normalize(a);k.options.mapNavigation.enableDoubleClickZoomTo?k.pointer.inClass(a.target,
"highcharts-tracker")&&k.hoverPoint&&k.hoverPoint.zoomTo():k.isInsidePlot(a.chartX-k.plotLeft,a.chartY-k.plotTop)&&k.mapZoom(.5,k.xAxis[0].toValue(a.chartX),k.yAxis[0].toValue(a.chartY),a.chartX,a.chartY)},onContainerMouseWheel:function(a){var k=this.chart;a=this.normalize(a);var c=a.detail||-(a.wheelDelta/120);k.isInsidePlot(a.chartX-k.plotLeft,a.chartY-k.plotTop)&&k.mapZoom(Math.pow(k.options.mapNavigation.mouseWheelSensitivity,c),k.xAxis[0].toValue(a.chartX),k.yAxis[0].toValue(a.chartY),a.chartX,
a.chartY)}});e(a.prototype,"zoomOption",function(a){var k=this.chart.options.mapNavigation;t(k.enableTouchZoom,k.enabled)&&(this.chart.options.chart.pinchType="xy");a.apply(this,[].slice.call(arguments,1))});e(a.prototype,"pinchTranslate",function(a,k,c,e,h,b,g){a.call(this,k,c,e,h,b,g);"map"===this.chart.options.chart.type&&this.hasZoom&&(a=e.scaleX>e.scaleY,this.pinchTranslateDirection(!a,k,c,e,h,b,g,a?e.scaleX:e.scaleY))})});u(a,"Maps/Map.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Options.js"],
a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,e,m,t,r){function k(a,b,g,h,c,k,e,r){return[["M",a+c,b],["L",a+g-k,b],["C",a+g-k/2,b,a+g,b+k/2,a+g,b+k],["L",a+g,b+h-e],["C",a+g,b+h-e/2,a+g-e/2,b+h,a+g-e,b+h],["L",a+r,b+h],["C",a+r/2,b+h,a,b+h-r/2,a,b+h-r],["L",a,b+c],["C",a,b+c/2,a+c/2,b,a+c,b],["Z"]]}m=m.defaultOptions;var c=r.extend,A=r.getOptions,h=r.merge,b=r.pick;r=e.Renderer;var g=e.VMLRenderer;c(m.lang,{zoomIn:"Zoom in",zoomOut:"Zoom out"});m.mapNavigation={buttonOptions:{alignTo:"plotBox",
align:"left",verticalAlign:"top",x:0,width:18,height:18,padding:5,style:{fontSize:"15px",fontWeight:"bold"},theme:{"stroke-width":1,"text-align":"center"}},buttons:{zoomIn:{onclick:function(){this.mapZoom(.5)},text:"+",y:0},zoomOut:{onclick:function(){this.mapZoom(2)},text:"-",y:28}},mouseWheelSensitivity:1.1};m=e.splitPath=function(a){"string"===typeof a&&(a=a.replace(/([A-Za-z])/g," $1 ").replace(/^\s*/,"").replace(/\s*$/,""),a=a.split(/[ ,;]+/).map(function(a){return/[A-za-z]/.test(a)?a:parseFloat(a)}));
return t.prototype.pathToSegments(a)};e.maps={};t.prototype.symbols.topbutton=function(a,b,g,h,c){c=c&&c.r||0;return k(a-1,b-1,g,h,c,c,0,0)};t.prototype.symbols.bottombutton=function(a,b,g,h,c){c=c&&c.r||0;return k(a-1,b-1,g,h,0,0,c,c)};r===g&&["topbutton","bottombutton"].forEach(function(a){g.prototype.symbols[a]=t.prototype.symbols[a]});return{mapChart:e.Map=e.mapChart=function(g,c,k){var f="string"===typeof g||g.nodeName,e=arguments[f?1:0],r=e,m={endOnTick:!1,visible:!1,minPadding:0,maxPadding:0,
startOnTick:!1},y=A().credits;var d=e.series;e.series=null;e=h({chart:{panning:{enabled:!0,type:"xy"},type:"map"},credits:{mapText:b(y.mapText,' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:b(y.mapTextFull,"{geojson.copyright}")},tooltip:{followTouchMove:!1},xAxis:m,yAxis:h(m,{reversed:!0})},e,{chart:{inverted:!1,alignTicks:!1}});e.series=r.series=d;return f?new a(g,e,k):new a(e,c)},maps:e.maps,splitPath:m}});u(a,"Series/Map/MapPoint.js",[a["Core/Series/Series.js"],
a["Mixins/ColorMapSeries.js"],a["Core/Utilities.js"]],function(a,e,m){var t=this&&this.__extends||function(){var a=function(c,e){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var g in b)b.hasOwnProperty(g)&&(a[g]=b[g])};return a(c,e)};return function(c,e){function h(){this.constructor=c}a(c,e);c.prototype=null===e?Object.create(e):(h.prototype=e.prototype,new h)}}();e=e.colorMapPointMixin;var r=m.extend;a=function(a){function c(){var c=null!==
a&&a.apply(this,arguments)||this;c.options=void 0;c.path=void 0;c.series=void 0;return c}t(c,a);c.prototype.applyOptions=function(c,h){var b=this.series;c=a.prototype.applyOptions.call(this,c,h);h=b.joinBy;b.mapData&&b.mapMap&&(h=a.prototype.getNestedProperty.call(c,h[1]),(h="undefined"!==typeof h&&b.mapMap[h])?(b.xyFromShape&&(c.x=h._midX,c.y=h._midY),r(c,h)):c.value=c.value||null);return c};c.prototype.onMouseOver=function(c){m.clearTimeout(this.colorInterval);if(null!==this.value||this.series.options.nullInteraction)a.prototype.onMouseOver.call(this,
c);else this.series.onMouseOut(c)};c.prototype.zoomTo=function(){var a=this.series;a.xAxis.setExtremes(this._minX,this._maxX,!1);a.yAxis.setExtremes(this._minY,this._maxY,!1);a.chart.redraw()};return c}(a.seriesTypes.scatter.prototype.pointClass);r(a.prototype,{dataLabelOnNull:e.dataLabelOnNull,isValid:e.isValid,setState:e.setState});return a});u(a,"Series/Map/MapSeries.js",[a["Core/Series/Series.js"],a["Mixins/ColorMapSeries.js"],a["Core/Globals.js"],a["Mixins/LegendSymbol.js"],a["Series/Line/LineSeries.js"],
a["Maps/Map.js"],a["Core/Color/Palette.js"],a["Series/Map/MapPoint.js"],a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,e,m,t,r,k,c,A,h,b){var g=this&&this.__extends||function(){var a=function(d,p){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,d){for(var p in d)d.hasOwnProperty(p)&&(a[p]=d[p])};return a(d,p)};return function(d,p){function b(){this.constructor=d}a(d,p);d.prototype=null===p?Object.create(p):(b.prototype=p.prototype,
new b)}}(),f=a.seriesTypes,x=f.column,C=f.scatter;e=e.colorMapSeriesMixin;f=m.noop;var F=k.maps,z=k.splitPath;k=b.extend;var D=b.fireEvent,u=b.getNestedProperty,y=b.isArray,d=b.isNumber,n=b.merge,v=b.objectEach,B=b.pick,w=b.splat;b=function(a){function b(){var d=null!==a&&a.apply(this,arguments)||this;d.baseTrans=void 0;d.chart=void 0;d.data=void 0;d.group=void 0;d.joinBy=void 0;d.options=void 0;d.points=void 0;d.transformGroup=void 0;return d}g(b,a);b.prototype.animate=function(a){var d=this.options.animation,
b=this.group,n=this.xAxis,p=this.yAxis,g=n.pos,l=p.pos;this.chart.renderer.isSVG&&(!0===d&&(d={duration:1E3}),a?b.attr({translateX:g+n.len/2,translateY:l+p.len/2,scaleX:.001,scaleY:.001}):b.animate({translateX:g,translateY:l,scaleX:1,scaleY:1},d))};b.prototype.animateDrilldown=function(a){var d=this.chart.plotBox,b=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],n=b.bBox,p=this.chart.options.drilldown.animation;a||(a=Math.min(n.width/d.width,n.height/d.height),b.shapeArgs={scaleX:a,
scaleY:a,translateX:n.x,translateY:n.y},this.points.forEach(function(a){a.graphic&&a.graphic.attr(b.shapeArgs).animate({scaleX:1,scaleY:1,translateX:0,translateY:0},p)}))};b.prototype.animateDrillupFrom=function(a){x.prototype.animateDrillupFrom.call(this,a)};b.prototype.animateDrillupTo=function(a){x.prototype.animateDrillupTo.call(this,a)};b.prototype.doFullTranslate=function(){return this.isDirtyData||this.chart.isResizing||this.chart.renderer.isVML||!this.baseTrans};b.prototype.drawMapDataLabels=
function(){r.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)};b.prototype.drawPoints=function(){var a=this,d=a.xAxis,b=a.yAxis,n=a.group,g=a.chart,l=g.renderer,c=this.baseTrans;a.transformGroup||(a.transformGroup=l.g().attr({scaleX:1,scaleY:1}).add(n),a.transformGroup.survive=!0);if(a.doFullTranslate())g.hasRendered&&!g.styledMode&&a.points.forEach(function(d){d.shapeArgs&&(d.shapeArgs.fill=a.pointAttribs(d,d.state).fill)}),a.group=a.transformGroup,
x.prototype.drawPoints.apply(a),a.group=n,a.points.forEach(function(d){if(d.graphic){var b="";d.name&&(b+="highcharts-name-"+d.name.replace(/ /g,"-").toLowerCase());d.properties&&d.properties["hc-key"]&&(b+=" highcharts-key-"+d.properties["hc-key"].toLowerCase());b&&d.graphic.addClass(b);g.styledMode&&d.graphic.css(a.pointAttribs(d,d.selected&&"select"||void 0))}}),this.baseTrans={originX:d.min-d.minPixelPadding/d.transA,originY:b.min-b.minPixelPadding/b.transA+(b.reversed?0:b.len/b.transA),transAX:d.transA,
transAY:b.transA},this.transformGroup.animate({translateX:0,translateY:0,scaleX:1,scaleY:1});else{var f=d.transA/c.transAX;var q=b.transA/c.transAY;var v=d.toPixels(c.originX,!0);var h=b.toPixels(c.originY,!0);.99<f&&1.01>f&&.99<q&&1.01>q&&(q=f=1,v=Math.round(v),h=Math.round(h));var e=this.transformGroup;if(g.renderer.globalAnimation){var k=e.attr("translateX");var w=e.attr("translateY");var r=e.attr("scaleX");var m=e.attr("scaleY");e.attr({animator:0}).animate({animator:1},{step:function(a,d){e.attr({translateX:k+
(v-k)*d.pos,translateY:w+(h-w)*d.pos,scaleX:r+(f-r)*d.pos,scaleY:m+(q-m)*d.pos})}})}else e.attr({translateX:v,translateY:h,scaleX:f,scaleY:q})}g.styledMode||n.element.setAttribute("stroke-width",B(a.options[a.pointAttrToOptions&&a.pointAttrToOptions["stroke-width"]||"borderWidth"],1)/(f||1));this.drawMapDataLabels()};b.prototype.getBox=function(a){var d=Number.MAX_VALUE,b=-d,n=d,g=-d,p=d,l=d,c=this.xAxis,f=this.yAxis,q;(a||[]).forEach(function(a){if(a.path){"string"===typeof a.path?a.path=z(a.path):
"M"===a.path[0]&&(a.path=h.prototype.pathToSegments(a.path));var c=a.path||[],f=-d,v=d,e=-d,k=d,w=a.properties;a._foundBox||(c.forEach(function(a){var d=a[a.length-2];a=a[a.length-1];"number"===typeof d&&"number"===typeof a&&(v=Math.min(v,d),f=Math.max(f,d),k=Math.min(k,a),e=Math.max(e,a))}),a._midX=v+(f-v)*B(a.middleX,w&&w["hc-middle-x"],.5),a._midY=k+(e-k)*B(a.middleY,w&&w["hc-middle-y"],.5),a._maxX=f,a._minX=v,a._maxY=e,a._minY=k,a.labelrank=B(a.labelrank,(f-v)*(e-k)),a._foundBox=!0);b=Math.max(b,
a._maxX);n=Math.min(n,a._minX);g=Math.max(g,a._maxY);p=Math.min(p,a._minY);l=Math.min(a._maxX-a._minX,a._maxY-a._minY,l);q=!0}});q&&(this.minY=Math.min(p,B(this.minY,d)),this.maxY=Math.max(g,B(this.maxY,-d)),this.minX=Math.min(n,B(this.minX,d)),this.maxX=Math.max(b,B(this.maxX,-d)),c&&"undefined"===typeof c.options.minRange&&(c.minRange=Math.min(5*l,(this.maxX-this.minX)/5,c.minRange||d)),f&&"undefined"===typeof f.options.minRange&&(f.minRange=Math.min(5*l,(this.maxY-this.minY)/5,f.minRange||d)))};
b.prototype.getExtremes=function(){var a=r.prototype.getExtremes.call(this,this.valueData),b=a.dataMin;a=a.dataMax;this.chart.hasRendered&&this.isDirtyData&&this.getBox(this.options.data);d(b)&&(this.valueMin=b);d(a)&&(this.valueMax=a);return{dataMin:this.minY,dataMax:this.maxY}};b.prototype.hasData=function(){return!!this.processedXData.length};b.prototype.pointAttribs=function(a,d){d=a.series.chart.styledMode?this.colorAttribs(a):x.prototype.pointAttribs.call(this,a,d);d["stroke-width"]=B(a.options[this.pointAttrToOptions&&
this.pointAttrToOptions["stroke-width"]||"borderWidth"],"inherit");return d};b.prototype.render=function(){var a=this,d=r.prototype.render;a.chart.renderer.isVML&&3E3<a.data.length?setTimeout(function(){d.call(a)}):d.call(a)};b.prototype.setData=function(a,b,g,l){var f=this.options,c=this.chart.options.chart,p=c&&c.map,q=f.mapData,h=this.joinBy,e=f.keys||this.pointArrayMap,k=[],B={},w=this.chart.mapTransforms;!q&&p&&(q="string"===typeof p?F[p]:p);a&&a.forEach(function(b,n){var g=0;if(d(b))a[n]={value:b};
else if(y(b)){a[n]={};!f.keys&&b.length>e.length&&"string"===typeof b[0]&&(a[n]["hc-key"]=b[0],++g);for(var l=0;l<e.length;++l,++g)e[l]&&"undefined"!==typeof b[g]&&(0<e[l].indexOf(".")?A.prototype.setNestedProperty(a[n],b[g],e[l]):a[n][e[l]]=b[g])}h&&"_i"===h[0]&&(a[n]._i=n)});this.getBox(a);(this.chart.mapTransforms=w=c&&c.mapTransforms||q&&q["hc-transform"]||w)&&v(w,function(a){a.rotation&&(a.cosAngle=Math.cos(a.rotation),a.sinAngle=Math.sin(a.rotation))});if(q){"FeatureCollection"===q.type&&(this.mapTitle=
q.title,q=m.geojson(q,this.type,this));this.mapData=q;this.mapMap={};for(w=0;w<q.length;w++)c=q[w],p=c.properties,c._i=w,h[0]&&p&&p[h[0]]&&(c[h[0]]=p[h[0]]),B[c[h[0]]]=c;this.mapMap=B;if(a&&h[1]){var G=h[1];a.forEach(function(a){a=u(G,a);B[a]&&k.push(B[a])})}if(f.allAreas){this.getBox(q);a=a||[];if(h[1]){var t=h[1];a.forEach(function(a){k.push(u(t,a))})}k="|"+k.map(function(a){return a&&a[h[0]]}).join("|")+"|";q.forEach(function(d){h[0]&&-1!==k.indexOf("|"+d[h[0]]+"|")||(a.push(n(d,{value:null})),
l=!1)})}else this.getBox(k)}r.prototype.setData.call(this,a,b,g,l)};b.prototype.setOptions=function(a){a=r.prototype.setOptions.call(this,a);var d=a.joinBy;null===d&&(d="_i");d=this.joinBy=w(d);d[1]||(d[1]=d[0]);return a};b.prototype.translate=function(){var a=this,b=a.xAxis,n=a.yAxis,g=a.doFullTranslate();a.generatePoints();a.data.forEach(function(l){d(l._midX)&&d(l._midY)&&(l.plotX=b.toPixels(l._midX,!0),l.plotY=n.toPixels(l._midY,!0));g&&(l.shapeType="path",l.shapeArgs={d:a.translatePath(l.path)})});
D(a,"afterTranslate")};b.prototype.translatePath=function(a){var d=this.xAxis,b=this.yAxis,n=d.min,l=d.transA,g=d.minPixelPadding,c=b.min,f=b.transA,q=b.minPixelPadding,h=[];a&&a.forEach(function(a){"M"===a[0]?h.push(["M",(a[1]-(n||0))*l+g,(a[2]-(c||0))*f+q]):"L"===a[0]?h.push(["L",(a[1]-(n||0))*l+g,(a[2]-(c||0))*f+q]):"C"===a[0]?h.push(["C",(a[1]-(n||0))*l+g,(a[2]-(c||0))*f+q,(a[3]-(n||0))*l+g,(a[4]-(c||0))*f+q,(a[5]-(n||0))*l+g,(a[6]-(c||0))*f+q]):"Q"===a[0]?h.push(["Q",(a[1]-(n||0))*l+g,(a[2]-
(c||0))*f+q,(a[3]-(n||0))*l+g,(a[4]-(c||0))*f+q]):"Z"===a[0]&&h.push(["Z"])});return h};b.defaultOptions=n(C.defaultOptions,{animation:!1,dataLabels:{crop:!1,formatter:function(){return this.point.value},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},marker:null,nullColor:c.neutralColor3,stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}<br/>"},turboThreshold:0,allAreas:!0,borderColor:c.neutralColor20,borderWidth:1,joinBy:"hc-key",states:{hover:{halo:null,
brightness:.2},normal:{animation:!0},select:{color:c.neutralColor20},inactive:{opacity:1}}});return b}(C);k(b.prototype,{type:"map",axisTypes:e.axisTypes,colorAttribs:e.colorAttribs,colorKey:e.colorKey,directTouch:!0,drawDataLabels:f,drawGraph:f,drawLegendSymbol:t.drawRectangle,forceDL:!0,getExtremesFromAll:!0,getSymbol:e.getSymbol,parallelArrays:e.parallelArrays,pointArrayMap:e.pointArrayMap,pointClass:A,preserveAspectRatio:!0,searchPoint:f,trackerGroups:e.trackerGroups,useMapGeometry:!0});a.registerSeriesType("map",
b);"";return b});u(a,"Series/MapLine/MapLineSeries.js",[a["Core/Series/Series.js"],a["Series/Map/MapSeries.js"],a["Core/Utilities.js"]],function(a,e,m){var t=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var g in b)b.hasOwnProperty(g)&&(a[g]=b[g])};return a(c,b)};return function(c,b){function g(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(g.prototype=b.prototype,new g)}}(),
r=a.seriesTypes.line,k=m.extend,c=m.merge;m=function(a){function h(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}t(h,a);h.prototype.pointAttribs=function(a,g){a=e.prototype.pointAttribs.call(this,a,g);a.fill=this.options.fillColor;return a};h.defaultOptions=c(e.defaultOptions,{lineWidth:1,fillColor:"none"});return h}(e);k(m.prototype,{type:"mapline",colorProp:"stroke",drawLegendSymbol:r.prototype.drawLegendSymbol,pointAttrToOptions:{stroke:"color",
"stroke-width":"lineWidth"}});a.registerSeriesType("mapline",m);"";return m});u(a,"Series/MapPoint/MapPointPoint.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,e){var m=this&&this.__extends||function(){var a=function(e,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(e,c)};return function(e,c){function k(){this.constructor=e}a(e,c);e.prototype=null===c?Object.create(c):
(k.prototype=c.prototype,new k)}}(),t=e.merge;return function(a){function e(){var c=null!==a&&a.apply(this,arguments)||this;c.options=void 0;c.series=void 0;return c}m(e,a);e.prototype.applyOptions=function(c,e){c="undefined"!==typeof c.lat&&"undefined"!==typeof c.lon?t(c,this.series.chart.fromLatLonToPoint(c)):c;return a.prototype.applyOptions.call(this,c,e)};return e}(a.seriesTypes.scatter.prototype.pointClass)});u(a,"Series/MapPoint/MapPointSeries.js",[a["Core/Series/Series.js"],a["Core/Color/Palette.js"],
a["Series/MapPoint/MapPointPoint.js"],a["Core/Utilities.js"]],function(a,e,m,t){var r=this&&this.__extends||function(){var a=function(b,g){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var g in b)b.hasOwnProperty(g)&&(a[g]=b[g])};return a(b,g)};return function(b,g){function c(){this.constructor=b}a(b,g);b.prototype=null===g?Object.create(g):(c.prototype=g.prototype,new c)}}(),k=a.seriesTypes.scatter,c=t.extend,A=t.merge;t=function(a){function b(){var b=
null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}r(b,a);b.prototype.drawDataLabels=function(){a.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)};b.defaultOptions=A(k.defaultOptions,{dataLabels:{crop:!1,defer:!1,enabled:!0,formatter:function(){return this.point.name},overflow:!1,style:{color:e.neutralColor100}}});return b}(k);c(t.prototype,{type:"mappoint",forceDL:!0,pointClass:m});a.registerSeriesType("mappoint",
t);"";return t});u(a,"Series/Bubble/BubblePoint.js",[a["Core/Series/Series.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,e,m){var t=this&&this.__extends||function(){var a=function(e,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(e,c)};return function(e,c){function k(){this.constructor=e}a(e,c);e.prototype=null===c?Object.create(c):(k.prototype=c.prototype,new k)}}();
m=m.extend;a=function(a){function k(){var c=null!==a&&a.apply(this,arguments)||this;c.options=void 0;c.series=void 0;return c}t(k,a);k.prototype.haloPath=function(a){return e.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)};return k}(a.seriesTypes.scatter.prototype.pointClass);m(a.prototype,{ttBelow:!1});return a});u(a,"Series/Bubble/BubbleLegend.js",[a["Core/Chart/Chart.js"],a["Core/Color/Color.js"],a["Core/Globals.js"],a["Core/Legend.js"],a["Series/Line/LineSeries.js"],
a["Core/Color/Palette.js"],a["Core/Utilities.js"]],function(a,e,m,t,r,k,c){var A=e.parse,h=m.noop;e=c.addEvent;var b=c.arrayMax,g=c.arrayMin,f=c.isNumber,x=c.merge,E=c.objectEach,u=c.pick,z=c.setOptions,D=c.stableSort,C=c.wrap;"";z({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,
color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});z=function(){function a(a,b){this.options=this.symbols=this.visible=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=h;this.init(a,b)}a.prototype.init=function(a,
b){this.options=a;this.visible=!0;this.chart=b.chart;this.legend=b};a.prototype.addToLegend=function(a){a.splice(this.options.legendIndex,0,this)};a.prototype.drawLegendSymbol=function(a){var d=this.chart,b=this.options,g=u(a.options.itemDistance,20),c=b.ranges;var l=b.connectorDistance;this.fontMetrics=d.renderer.fontMetrics(b.labels.style.fontSize.toString()+"px");c&&c.length&&f(c[0].value)?(D(c,function(a,d){return d.value-a.value}),this.ranges=c,this.setOptions(),this.render(),d=this.getMaxLabelSize(),
c=this.ranges[0].radius,a=2*c,l=l-c+d.width,l=0<l?l:0,this.maxLabel=d,this.movementX="left"===b.labels.align?l:0,this.legendItemWidth=a+l+g,this.legendItemHeight=a+this.fontMetrics.h/2):a.options.bubbleLegend.autoRanges=!0};a.prototype.setOptions=function(){var a=this.ranges,b=this.options,c=this.chart.series[b.seriesIndex],g=this.legend.baseline,f={"z-index":b.zIndex,"stroke-width":b.borderWidth},l={"z-index":b.zIndex,"stroke-width":b.connectorWidth},q=this.getLabelStyles(),e=c.options.marker.fillOpacity,
h=this.chart.styledMode;a.forEach(function(d,n){h||(f.stroke=u(d.borderColor,b.borderColor,c.color),f.fill=u(d.color,b.color,1!==e?A(c.color).setOpacity(e).get("rgba"):c.color),l.stroke=u(d.connectorColor,b.connectorColor,c.color));a[n].radius=this.getRangeRadius(d.value);a[n]=x(a[n],{center:a[0].radius-a[n].radius+g});h||x(!0,a[n],{bubbleStyle:x(!1,f),connectorStyle:x(!1,l),labelStyle:q})},this)};a.prototype.getLabelStyles=function(){var a=this.options,b={},c="left"===a.labels.align,g=this.legend.options.rtl;
E(a.labels.style,function(a,d){"color"!==d&&"fontSize"!==d&&"z-index"!==d&&(b[d]=a)});return x(!1,b,{"font-size":a.labels.style.fontSize,fill:u(a.labels.style.color,k.neutralColor100),"z-index":a.zIndex,align:g||c?"right":"left"})};a.prototype.getRangeRadius=function(a){var d=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,d.ranges[d.ranges.length-1].value,d.ranges[0].value,d.minSize,d.maxSize,a)};a.prototype.render=function(){var a=this.chart.renderer,b=this.options.zThreshold;
this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=a.g("bubble-legend");this.legendItem=a.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(a){a.value>=b&&this.renderRange(a)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};a.prototype.renderRange=function(a){var d=this.options,b=d.labels,c=this.chart.renderer,g=this.symbols,l=g.labels,
f=a.center,e=Math.abs(a.radius),h=d.connectorDistance||0,k=b.align,m=b.style.fontSize;h=this.legend.options.rtl||"left"===k?-h:h;b=d.connectorWidth;var r=this.ranges[0].radius||0,t=f-e-d.borderWidth/2+b/2;m=m/2-(this.fontMetrics.h-m)/2;var y=c.styledMode;"center"===k&&(h=0,d.connectorDistance=0,a.labelStyle.align="center");k=t+d.labels.y;var x=r+h+d.labels.x;g.bubbleItems.push(c.circle(r,f+((t%1?1:.5)-(b%2?0:.5)),e).attr(y?{}:a.bubbleStyle).addClass((y?"highcharts-color-"+this.options.seriesIndex+
" ":"")+"highcharts-bubble-legend-symbol "+(d.className||"")).add(this.legendSymbol));g.connectors.push(c.path(c.crispLine([["M",r,t],["L",r+h,t]],d.connectorWidth)).attr(y?{}:a.connectorStyle).addClass((y?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(d.connectorClassName||"")).add(this.legendSymbol));a=c.text(this.formatLabel(a),x,k+m).attr(y?{}:a.labelStyle).addClass("highcharts-bubble-legend-labels "+(d.labels.className||"")).add(this.legendSymbol);
l.push(a);a.placed=!0;a.alignAttr={x:x,y:k+m}};a.prototype.getMaxLabelSize=function(){var a,b;this.symbols.labels.forEach(function(d){b=d.getBBox(!0);a=a?b.width>a.width?b:a:b});return a||{}};a.prototype.formatLabel=function(a){var d=this.options,b=d.labels.formatter;d=d.labels.format;var g=this.chart.numberFormatter;return d?c.format(d,a):b?b.call(a):g(a.value,1)};a.prototype.hideOverlappingLabels=function(){var a=this.chart,b=this.symbols;!this.options.labels.allowOverlap&&b&&(a.hideOverlappingLabels(b.labels),
b.labels.forEach(function(a,d){a.newOpacity?a.newOpacity!==a.oldOpacity&&b.connectors[d].show():b.connectors[d].hide()}))};a.prototype.getRanges=function(){var a=this.legend.bubbleLegend,c=a.options.ranges,e,h=Number.MAX_VALUE,k=-Number.MAX_VALUE;a.chart.series.forEach(function(a){a.isBubble&&!a.ignoreSeries&&(e=a.zData.filter(f),e.length&&(h=u(a.options.zMin,Math.min(h,Math.max(g(e),!1===a.options.displayNegative?a.options.zThreshold:-Number.MAX_VALUE))),k=u(a.options.zMax,Math.max(k,b(e)))))});
var l=h===k?[{value:k}]:[{value:h},{value:(h+k)/2},{value:k,autoRanges:!0}];c.length&&c[0].radius&&l.reverse();l.forEach(function(a,d){c&&c[d]&&(l[d]=x(!1,c[d],a))});return l};a.prototype.predictBubbleSizes=function(){var a=this.chart,b=this.fontMetrics,c=a.legend.options,g="horizontal"===c.layout,f=g?a.legend.lastLineHeight:0,l=a.plotSizeX,e=a.plotSizeY,h=a.series[this.options.seriesIndex];a=Math.ceil(h.minPxSize);var k=Math.ceil(h.maxPxSize);h=h.options.maxSize;var m=Math.min(e,l);if(c.floating||
!/%$/.test(h))b=k;else if(h=parseFloat(h),b=(m+f-b.h/2)*h/100/(h/100+1),g&&e-b>=l||!g&&l-b>=e)b=k;return[a,Math.ceil(b)]};a.prototype.updateRanges=function(a,b){var d=this.legend.options.bubbleLegend;d.minSize=a;d.maxSize=b;d.ranges=this.getRanges()};a.prototype.correctSizes=function(){var a=this.legend,b=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(b.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,b.maxPxSize),a.render())};return a}();e(t,"afterGetAllItems",
function(a){var d=this.bubbleLegend,b=this.options,c=b.bubbleLegend,g=this.chart.getVisibleBubbleSeriesIndex();d&&d.ranges&&d.ranges.length&&(c.ranges.length&&(c.autoRanges=!!c.ranges[0].autoRanges),this.destroyItem(d));0<=g&&b.enabled&&c.enabled&&(c.seriesIndex=g,this.bubbleLegend=new m.BubbleLegend(c,this),this.bubbleLegend.addToLegend(a.allItems))});a.prototype.getVisibleBubbleSeriesIndex=function(){for(var a=this.series,d=0;d<a.length;){if(a[d]&&a[d].isBubble&&a[d].visible&&a[d].zData.length)return d;
d++}return-1};t.prototype.getLinesHeights=function(){var a=this.allItems,d=[],b=a.length,c,g=0;for(c=0;c<b;c++)if(a[c].legendItemHeight&&(a[c].itemHeight=a[c].legendItemHeight),a[c]===a[b-1]||a[c+1]&&a[c]._legendItemPos[1]!==a[c+1]._legendItemPos[1]){d.push({height:0});var f=d[d.length-1];for(g;g<=c;g++)a[g].itemHeight>f.height&&(f.height=a[g].itemHeight);f.step=c}return d};t.prototype.retranslateItems=function(a){var d,b,c,g=this.options.rtl,f=0;this.allItems.forEach(function(l,e){d=l.legendGroup.translateX;
b=l._legendItemPos[1];if((c=l.movementX)||g&&l.ranges)c=g?d-l.options.maxSize/2:d+c,l.legendGroup.attr({translateX:c});e>a[f].step&&f++;l.legendGroup.attr({translateY:Math.round(b+a[f].height/2)});l._legendItemPos[1]=b+a[f].height/2})};e(r,"legendItemClick",function(){var a=this.chart,b=this.visible,c=this.chart.legend;c&&c.bubbleLegend&&(this.visible=!b,this.ignoreSeries=b,a=0<=a.getVisibleBubbleSeriesIndex(),c.bubbleLegend.visible!==a&&(c.update({bubbleLegend:{enabled:a}}),c.bubbleLegend.visible=
a),this.visible=b)});C(a.prototype,"drawChartBox",function(a,b,c){var d=this.legend,g=0<=this.getVisibleBubbleSeriesIndex();if(d&&d.options.enabled&&d.bubbleLegend&&d.options.bubbleLegend.autoRanges&&g){var f=d.bubbleLegend.options;g=d.bubbleLegend.predictBubbleSizes();d.bubbleLegend.updateRanges(g[0],g[1]);f.placed||(d.group.placed=!1,d.allItems.forEach(function(a){a.legendGroup.translateY=null}));d.render();this.getMargins();this.axes.forEach(function(a){a.visible&&a.render();f.placed||(a.setScale(),
a.updateNames(),E(a.ticks,function(a){a.isNew=!0;a.isNewLabel=!0}))});f.placed=!0;this.getMargins();a.call(this,b,c);d.bubbleLegend.correctSizes();d.retranslateItems(d.getLinesHeights())}else a.call(this,b,c),d&&d.options.enabled&&d.bubbleLegend&&(d.render(),d.retranslateItems(d.getLinesHeights()))});m.BubbleLegend=z;return m.BubbleLegend});u(a,"Series/Bubble/BubbleSeries.js",[a["Core/Axis/Axis.js"],a["Core/Series/Series.js"],a["Series/Bubble/BubblePoint.js"],a["Core/Color/Color.js"],a["Core/Globals.js"],
a["Series/Line/LineSeries.js"],a["Core/Utilities.js"]],function(a,e,m,t,r,k,c){var u=this&&this.__extends||function(){var a=function(d,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,d){for(var b in d)d.hasOwnProperty(b)&&(a[b]=d[b])};return a(d,b)};return function(d,b){function c(){this.constructor=d}a(d,b);d.prototype=null===b?Object.create(b):(c.prototype=b.prototype,new c)}}(),h=e.seriesTypes,b=h.column,g=h.scatter,f=t.parse;t=r.noop;var x=
c.arrayMax,E=c.arrayMin,C=c.clamp,z=c.extend,D=c.isNumber,H=c.merge,y=c.pick,d=c.pInt;c=function(a){function d(){var d=null!==a&&a.apply(this,arguments)||this;d.data=void 0;d.maxPxSize=void 0;d.minPxSize=void 0;d.options=void 0;d.points=void 0;d.radii=void 0;d.yData=void 0;d.zData=void 0;return d}u(d,a);d.prototype.animate=function(a){!a&&this.points.length<this.options.animationLimit&&this.points.forEach(function(a){var d=a.graphic;d&&d.width&&(this.hasRendered||d.attr({x:a.plotX,y:a.plotY,width:1,
height:1}),d.animate(this.markerAttribs(a),this.options.animation))},this)};d.prototype.getRadii=function(a,d,b){var c=this.zData,g=this.yData,f=b.minPxSize,l=b.maxPxSize,e=[];var h=0;for(b=c.length;h<b;h++){var n=c[h];e.push(this.getRadius(a,d,f,l,n,g[h]))}this.radii=e};d.prototype.getRadius=function(a,d,b,c,g,f){var e=this.options,l="width"!==e.sizeBy,h=e.zThreshold,n=d-a,q=.5;if(null===f||null===g)return null;if(D(g)){e.sizeByAbsoluteValue&&(g=Math.abs(g-h),n=Math.max(d-h,Math.abs(a-h)),a=0);if(g<
a)return b/2-1;0<n&&(q=(g-a)/n)}l&&0<=q&&(q=Math.sqrt(q));return Math.ceil(b+q*(c-b))/2};d.prototype.hasData=function(){return!!this.processedXData.length};d.prototype.pointAttribs=function(a,d){var b=this.options.marker.fillOpacity;a=k.prototype.pointAttribs.call(this,a,d);1!==b&&(a.fill=f(a.fill).setOpacity(b).get("rgba"));return a};d.prototype.translate=function(){var d,b=this.data,c=this.radii;a.prototype.translate.call(this);for(d=b.length;d--;){var g=b[d];var f=c?c[d]:0;D(f)&&f>=this.minPxSize/
2?(g.marker=z(g.marker,{radius:f,width:2*f,height:2*f}),g.dlBox={x:g.plotX-f,y:g.plotY-f,width:2*f,height:2*f}):g.shapeArgs=g.plotY=g.dlBox=void 0}};d.defaultOptions=H(g.defaultOptions,{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},
turboThreshold:0,zThreshold:0,zoneAxis:"z"});return d}(g);z(c.prototype,{alignDataLabel:b.prototype.alignDataLabel,applyZones:t,bubblePadding:!0,buildKDTree:t,directTouch:!0,isBubble:!0,pointArrayMap:["y","z"],pointClass:m,parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",zoneAxis:"z"});a.prototype.beforePadding=function(){var a=this,b=this.len,c=this.chart,g=0,f=b,e=this.isXAxis,h=e?"xData":"yData",k=this.min,m={},r=Math.min(c.plotWidth,c.plotHeight),t=Number.MAX_VALUE,
u=-Number.MAX_VALUE,A=this.max-k,z=b/A,F=[];this.series.forEach(function(b){var g=b.options;!b.bubblePadding||!b.visible&&c.options.chart.ignoreHiddenSeries||(a.allowZoomOutside=!0,F.push(b),e&&(["minSize","maxSize"].forEach(function(a){var b=g[a],c=/%$/.test(b);b=d(b);m[a]=c?r*b/100:b}),b.minPxSize=m.minSize,b.maxPxSize=Math.max(m.maxSize,m.minSize),b=b.zData.filter(D),b.length&&(t=y(g.zMin,C(E(b),!1===g.displayNegative?g.zThreshold:-Number.MAX_VALUE,t)),u=y(g.zMax,Math.max(u,x(b))))))});F.forEach(function(d){var b=
d[h],c=b.length;e&&d.getRadii(t,u,d);if(0<A)for(;c--;)if(D(b[c])&&a.dataMin<=b[c]&&b[c]<=a.max){var l=d.radii?d.radii[c]:0;g=Math.min((b[c]-k)*z-l,g);f=Math.max((b[c]-k)*z+l,f)}});F.length&&0<A&&!this.logarithmic&&(f-=b,z*=(b+Math.max(0,g)-Math.min(f,b))/b,[["min","userMin",g],["max","userMax",f]].forEach(function(d){"undefined"===typeof y(a.options[d[0]],a[d[1]])&&(a[d[0]]+=d[2]/z)}))};e.registerSeriesType("bubble",c);"";"";return c});u(a,"Series/MapBubble/MapBubblePoint.js",[a["Core/Series/Series.js"],
a["Core/Utilities.js"]],function(a,e){var m=this&&this.__extends||function(){var a=function(c,e){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,e)};return function(c,e){function b(){this.constructor=c}a(c,e);c.prototype=null===e?Object.create(e):(b.prototype=e.prototype,new b)}}(),t=a.seriesTypes,r=t.map;a=e.extend;var k=e.merge;e=function(a){function c(){return null!==a&&a.apply(this,
arguments)||this}m(c,a);c.prototype.applyOptions=function(c,b){return c&&"undefined"!==typeof c.lat&&"undefined"!==typeof c.lon?a.prototype.applyOptions.call(this,k(c,this.series.chart.fromLatLonToPoint(c)),b):r.prototype.pointClass.prototype.applyOptions.call(this,c,b)};c.prototype.isValid=function(){return"number"===typeof this.z};return c}(t.bubble.prototype.pointClass);a(e.prototype,{ttBelow:!1});return e});u(a,"Series/MapBubble/MapBubbleSeries.js",[a["Core/Series/Series.js"],a["Series/Bubble/BubbleSeries.js"],
a["Series/MapBubble/MapBubblePoint.js"],a["Series/Map/MapSeries.js"],a["Core/Utilities.js"]],function(a,e,m,t,r){var k=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function g(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(g.prototype=c.prototype,new g)}}(),c=r.extend,u=r.merge;r=function(a){function b(){var b=
null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}k(b,a);b.defaultOptions=u(e.defaultOptions,{animationLimit:500,tooltip:{pointFormat:"{point.name}: {point.z}"}});return b}(e);c(r.prototype,{type:"mapbubble",getBox:t.prototype.getBox,pointArrayMap:["z"],pointClass:m,setData:t.prototype.setData,setOptions:t.prototype.setOptions,xyFromShape:!0});a.registerSeriesType("mapbubble",r);"";return r});u(a,"Series/HeatmapSeries.js",[a["Core/Series/Series.js"],a["Mixins/ColorMapSeries.js"],
a["Core/Globals.js"],a["Core/Series/Point.js"],a["Mixins/LegendSymbol.js"],a["Series/Line/LineSeries.js"],a["Core/Color/Palette.js"],a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,e,m,t,r,k,c,u,h){var b=a.seriesTypes,g=e.colorMapPointMixin;e=e.colorMapSeriesMixin;var f=m.noop,x=h.clamp,E=h.extend,A=h.fireEvent,z=h.isNumber,D=h.merge,C=h.pick,y=u.prototype.symbols;"";a.seriesType("heatmap","scatter",{animation:!1,borderWidth:0,nullColor:c.neutralColor3,dataLabels:{formatter:function(){return this.point.value},
inside:!0,verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}}},D(e,{pointArrayMap:["y","value"],hasPointSpecificOptions:!0,getExtremesFromAll:!0,directTouch:!0,init:function(){k.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=C(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=
a.rowsize||1;E(y,{ellipse:y.circle,rect:y.square})},getSymbol:k.prototype.getSymbol,setClip:function(a){var b=this.chart;k.prototype.setClip.apply(this,arguments);(!1!==this.options.clip||a)&&this.markerGroup.clip((a||this.clipBox)&&this.sharedClipKey?b[this.sharedClipKey]:b.clipRect)},translate:function(){var a=this.options,b=a.marker&&a.marker.symbol||"",c=y[b]?b:"rect";a=this.options;var g=-1!==["circle","square"].indexOf(c);this.generatePoints();this.points.forEach(function(a){var d=a.getCellAttributes(),
f={x:Math.min(d.x1,d.x2),y:Math.min(d.y1,d.y2),width:Math.max(Math.abs(d.x2-d.x1),0),height:Math.max(Math.abs(d.y2-d.y1),0)};var e=a.hasImage=0===(a.marker&&a.marker.symbol||b||"").indexOf("url");if(g){var h=Math.abs(f.width-f.height);f.x=Math.min(d.x1,d.x2)+(f.width<f.height?0:h/2);f.y=Math.min(d.y1,d.y2)+(f.width<f.height?h/2:0);f.width=f.height=Math.min(f.width,f.height)}h={plotX:(d.x1+d.x2)/2,plotY:(d.y1+d.y2)/2,clientX:(d.x1+d.x2)/2,shapeType:"path",shapeArgs:D(!0,f,{d:y[c](f.x,f.y,f.width,f.height)})};
e&&(a.marker={width:f.width,height:f.height});E(a,h)});A(this,"afterTranslate")},pointAttribs:function(a,b){var d=k.prototype.pointAttribs.call(this,a,b),c=this.options||{},g=this.chart.options.plotOptions||{},f=g.series||{},e=g.heatmap||{};g=c.borderColor||e.borderColor||f.borderColor;f=c.borderWidth||e.borderWidth||f.borderWidth||d["stroke-width"];d.stroke=a&&a.marker&&a.marker.lineColor||c.marker&&c.marker.lineColor||g||this.color;d["stroke-width"]=f;b&&(a=D(c.states[b],c.marker&&c.marker.states[b],
a.options.states&&a.options.states[b]||{}),b=a.brightness,d.fill=a.color||m.color(d.fill).brighten(b||0).get(),d.stroke=a.lineColor);return d},markerAttribs:function(a,b){var d=a.marker||{},c=this.options.marker||{},g=a.shapeArgs||{},f={};if(a.hasImage)return{x:a.plotX,y:a.plotY};if(b){var e=c.states[b]||{};var h=d.states&&d.states[b]||{};[["width","x"],["height","y"]].forEach(function(a){f[a[0]]=(h[a[0]]||e[a[0]]||g[a[0]])+(h[a[0]+"Plus"]||e[a[0]+"Plus"]||0);f[a[1]]=g[a[1]]+(g[a[0]]-f[a[0]])/2})}return b?
f:g},drawPoints:function(){var a=this;if((this.options.marker||{}).enabled||this._hasPointMarkers)k.prototype.drawPoints.call(this),this.points.forEach(function(b){b.graphic&&b.graphic[a.chart.styledMode?"css":"animate"](a.colorAttribs(b))})},hasData:function(){return!!this.processedXData.length},getValidPoints:function(a,b){return k.prototype.getValidPoints.call(this,a,b,!0)},getBox:f,drawLegendSymbol:r.drawRectangle,alignDataLabel:b.column.prototype.alignDataLabel,getExtremes:function(){var a=k.prototype.getExtremes.call(this,
this.valueData),b=a.dataMin;a=a.dataMax;z(b)&&(this.valueMin=b);z(a)&&(this.valueMax=a);return k.prototype.getExtremes.call(this)}}),D(g,{applyOptions:function(a,b){a=t.prototype.applyOptions.call(this,a,b);a.formatPrefix=a.isNull||null===a.value?"null":"point";return a},isValid:function(){return Infinity!==this.value&&-Infinity!==this.value},haloPath:function(a){if(!a)return[];var b=this.shapeArgs;return["M",b.x-a,b.y-a,"L",b.x-a,b.y+b.height+a,b.x+b.width+a,b.y+b.height+a,b.x+b.width+a,b.y-a,"Z"]},
getCellAttributes:function(){var a=this.series,b=a.options,c=(b.colsize||1)/2,g=(b.rowsize||1)/2,f=a.xAxis,e=a.yAxis,h=this.options.marker||a.options.marker;a=a.pointPlacementToXValue();var k=C(this.pointPadding,b.pointPadding,0),m={x1:x(Math.round(f.len-(f.translate(this.x-c,!1,!0,!1,!0,-a)||0)),-f.len,2*f.len),x2:x(Math.round(f.len-(f.translate(this.x+c,!1,!0,!1,!0,-a)||0)),-f.len,2*f.len),y1:x(Math.round(e.translate(this.y-g,!1,!0,!1,!0)||0),-e.len,2*e.len),y2:x(Math.round(e.translate(this.y+g,
!1,!0,!1,!0)||0),-e.len,2*e.len)};[["width","x"],["height","y"]].forEach(function(a){var b=a[0];a=a[1];var d=a+"1",c=a+"2",g=Math.abs(m[d]-m[c]),f=h&&h.lineWidth||0,e=Math.abs(m[d]+m[c])/2;h[b]&&h[b]<g&&(m[d]=e-h[b]/2-f/2,m[c]=e+h[b]/2+f/2);k&&("y"===a&&(d=c,c=a+"1"),m[d]+=k,m[c]-=k)});return m}}));""});u(a,"Extensions/GeoJSON.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,e,m){function t(a,c){var b,g=!1,e=a.x,h=a.y;a=0;for(b=c.length-1;a<c.length;b=a++){var k=
c[a][1]>h;var m=c[b][1]>h;k!==m&&e<(c[b][0]-c[a][0])*(h-c[a][1])/(c[b][1]-c[a][1])+c[a][0]&&(g=!g)}return g}var r=e.win,k=m.error,c=m.extend,u=m.format,h=m.merge;m=m.wrap;"";a.prototype.transformFromLatLon=function(a,c){var b,g=(null===(b=this.userOptions.chart)||void 0===b?void 0:b.proj4)||r.proj4;if(!g)return k(21,!1,this),{x:0,y:null};a=g(c.crs,[a.lon,a.lat]);b=c.cosAngle||c.rotation&&Math.cos(c.rotation);g=c.sinAngle||c.rotation&&Math.sin(c.rotation);a=c.rotation?[a[0]*b+a[1]*g,-a[0]*g+a[1]*b]:
a;return{x:((a[0]-(c.xoffset||0))*(c.scale||1)+(c.xpan||0))*(c.jsonres||1)+(c.jsonmarginX||0),y:(((c.yoffset||0)-a[1])*(c.scale||1)+(c.ypan||0))*(c.jsonres||1)-(c.jsonmarginY||0)}};a.prototype.transformToLatLon=function(a,c){if("undefined"===typeof r.proj4)k(21,!1,this);else{a={x:((a.x-(c.jsonmarginX||0))/(c.jsonres||1)-(c.xpan||0))/(c.scale||1)+(c.xoffset||0),y:((-a.y-(c.jsonmarginY||0))/(c.jsonres||1)+(c.ypan||0))/(c.scale||1)+(c.yoffset||0)};var b=c.cosAngle||c.rotation&&Math.cos(c.rotation),g=
c.sinAngle||c.rotation&&Math.sin(c.rotation);c=r.proj4(c.crs,"WGS84",c.rotation?{x:a.x*b+a.y*-g,y:a.x*g+a.y*b}:a);return{lat:c.y,lon:c.x}}};a.prototype.fromPointToLatLon=function(a){var b=this.mapTransforms,c;if(b){for(c in b)if(Object.hasOwnProperty.call(b,c)&&b[c].hitZone&&t({x:a.x,y:-a.y},b[c].hitZone.coordinates[0]))return this.transformToLatLon(a,b[c]);return this.transformToLatLon(a,b["default"])}k(22,!1,this)};a.prototype.fromLatLonToPoint=function(a){var b=this.mapTransforms,c;if(!b)return k(22,
!1,this),{x:0,y:null};for(c in b)if(Object.hasOwnProperty.call(b,c)&&b[c].hitZone){var e=this.transformFromLatLon(a,b[c]);if(t({x:e.x,y:-e.y},b[c].hitZone.coordinates[0]))return e}return this.transformFromLatLon(a,b["default"])};e.geojson=function(a,e,f){var b=[],g=[],h=function(a){a.forEach(function(a,b){0===b?g.push(["M",a[0],-a[1]]):g.push(["L",a[0],-a[1]])})};e=e||"map";a.features.forEach(function(a){var f=a.geometry,k=f.type;f=f.coordinates;a=a.properties;var m;g=[];"map"===e||"mapbubble"===
e?("Polygon"===k?(f.forEach(h),g.push(["Z"])):"MultiPolygon"===k&&(f.forEach(function(a){a.forEach(h)}),g.push(["Z"])),g.length&&(m={path:g})):"mapline"===e?("LineString"===k?h(f):"MultiLineString"===k&&f.forEach(h),g.length&&(m={path:g})):"mappoint"===e&&"Point"===k&&(m={x:f[0],y:-f[1]});m&&b.push(c(m,{name:a.name||a.NAME,properties:a}))});f&&a.copyrightShort&&(f.chart.mapCredits=u(f.chart.options.credits.mapText,{geojson:a}),f.chart.mapCreditsFull=u(f.chart.options.credits.mapTextFull,{geojson:a}));
return b};m(a.prototype,"addCredits",function(a,c){c=h(!0,this.options.credits,c);this.mapCredits&&(c.href=null);a.call(this,c);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})})});u(a,"masters/modules/map.src.js",[],function(){})});
//# sourceMappingURL=map.js.map