/*
 Highcharts JS v8.2.2 (2020-11-23)

 Force directed graph module

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(e){"object"===typeof module&&module.exports?(e["default"]=e,module.exports=e):"function"===typeof define&&define.amd?define("highcharts/modules/networkgraph",["highcharts"],function(l){e(l);e.Highcharts=l;return e}):e("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(e){function l(e,a,c,f){e.hasOwnProperty(a)||(e[a]=f.apply(null,c))}e=e?e._modules:{};l(e,"Mixins/Nodes.js",[e["Core/Globals.js"],e["Series/Line/LineSeries.js"],e["Core/Series/Point.js"],e["Core/Utilities.js"]],function(e,
a,c,f){var d=f.defined,h=f.extend,p=f.find,k=f.pick;return e.NodesMixin={createNode:function(d){function a(b,g){return p(b,function(b){return b.id===g})}var b=a(this.nodes,d),g=this.pointClass;if(!b){var n=this.options.nodes&&a(this.options.nodes,d);b=(new g).init(this,h({className:"highcharts-node",isNode:!0,id:d,y:1},n));b.linksTo=[];b.linksFrom=[];b.formatPrefix="node";b.name=b.name||b.options.id||"";b.mass=k(b.options.mass,b.options.marker&&b.options.marker.radius,this.options.marker&&this.options.marker.radius,
4);b.getSum=function(){var g=0,n=0;b.linksTo.forEach(function(b){g+=b.weight});b.linksFrom.forEach(function(b){n+=b.weight});return Math.max(g,n)};b.offset=function(g,n){for(var d=0,a=0;a<b[n].length;a++){if(b[n][a]===g)return d;d+=b[n][a].weight}};b.hasShape=function(){var g=0;b.linksTo.forEach(function(b){b.outgoing&&g++});return!b.linksTo.length||g!==b.linksTo.length};this.nodes.push(b)}return b},generatePoints:function(){var c=this.chart,f={};a.prototype.generatePoints.call(this);this.nodes||
(this.nodes=[]);this.colorCounter=0;this.nodes.forEach(function(b){b.linksFrom.length=0;b.linksTo.length=0;b.level=b.options.level});this.points.forEach(function(b){d(b.from)&&(f[b.from]||(f[b.from]=this.createNode(b.from)),f[b.from].linksFrom.push(b),b.fromNode=f[b.from],c.styledMode?b.colorIndex=k(b.options.colorIndex,f[b.from].colorIndex):b.color=b.options.color||f[b.from].color);d(b.to)&&(f[b.to]||(f[b.to]=this.createNode(b.to)),f[b.to].linksTo.push(b),b.toNode=f[b.to]);b.name=b.name||b.id},this);
this.nodeLookup=f},setData:function(){this.nodes&&(this.nodes.forEach(function(d){d.destroy()}),this.nodes.length=0);a.prototype.setData.apply(this,arguments)},destroy:function(){this.data=[].concat(this.points||[],this.nodes);return a.prototype.destroy.apply(this,arguments)},setNodeState:function(d){var a=arguments,b=this.isNode?this.linksTo.concat(this.linksFrom):[this.fromNode,this.toNode];"select"!==d&&b.forEach(function(b){b&&b.series&&(c.prototype.setState.apply(b,a),b.isNode||(b.fromNode.graphic&&
c.prototype.setState.apply(b.fromNode,a),b.toNode&&b.toNode.graphic&&c.prototype.setState.apply(b.toNode,a)))});c.prototype.setState.apply(this,a)}}});l(e,"Series/Networkgraph/Integrations.js",[e["Core/Globals.js"]],function(e){e.networkgraphIntegrations={verlet:{attractiveForceFunction:function(a,c){return(c-a)/a},repulsiveForceFunction:function(a,c){return(c-a)/a*(c>a?1:0)},barycenter:function(){var a=this.options.gravitationalConstant,c=this.barycenter.xFactor,f=this.barycenter.yFactor;c=(c-(this.box.left+
this.box.width)/2)*a;f=(f-(this.box.top+this.box.height)/2)*a;this.nodes.forEach(function(a){a.fixedPosition||(a.plotX-=c/a.mass/a.degree,a.plotY-=f/a.mass/a.degree)})},repulsive:function(a,c,f){c=c*this.diffTemperature/a.mass/a.degree;a.fixedPosition||(a.plotX+=f.x*c,a.plotY+=f.y*c)},attractive:function(a,c,f){var d=a.getMass(),h=-f.x*c*this.diffTemperature;c=-f.y*c*this.diffTemperature;a.fromNode.fixedPosition||(a.fromNode.plotX-=h*d.fromNode/a.fromNode.degree,a.fromNode.plotY-=c*d.fromNode/a.fromNode.degree);
a.toNode.fixedPosition||(a.toNode.plotX+=h*d.toNode/a.toNode.degree,a.toNode.plotY+=c*d.toNode/a.toNode.degree)},integrate:function(a,c){var f=-a.options.friction,d=a.options.maxSpeed,h=(c.plotX+c.dispX-c.prevX)*f;f*=c.plotY+c.dispY-c.prevY;var e=Math.abs,k=e(h)/(h||1);e=e(f)/(f||1);h=k*Math.min(d,Math.abs(h));f=e*Math.min(d,Math.abs(f));c.prevX=c.plotX+c.dispX;c.prevY=c.plotY+c.dispY;c.plotX+=h;c.plotY+=f;c.temperature=a.vectorLength({x:h,y:f})},getK:function(a){return Math.pow(a.box.width*a.box.height/
a.nodes.length,.5)}},euler:{attractiveForceFunction:function(a,c){return a*a/c},repulsiveForceFunction:function(a,c){return c*c/a},barycenter:function(){var a=this.options.gravitationalConstant,c=this.barycenter.xFactor,f=this.barycenter.yFactor;this.nodes.forEach(function(d){if(!d.fixedPosition){var h=d.getDegree();h*=1+h/2;d.dispX+=(c-d.plotX)*a*h/d.degree;d.dispY+=(f-d.plotY)*a*h/d.degree}})},repulsive:function(a,c,f,d){a.dispX+=f.x/d*c/a.degree;a.dispY+=f.y/d*c/a.degree},attractive:function(a,
c,f,d){var h=a.getMass(),e=f.x/d*c;c*=f.y/d;a.fromNode.fixedPosition||(a.fromNode.dispX-=e*h.fromNode/a.fromNode.degree,a.fromNode.dispY-=c*h.fromNode/a.fromNode.degree);a.toNode.fixedPosition||(a.toNode.dispX+=e*h.toNode/a.toNode.degree,a.toNode.dispY+=c*h.toNode/a.toNode.degree)},integrate:function(a,c){c.dispX+=c.dispX*a.options.friction;c.dispY+=c.dispY*a.options.friction;var f=c.temperature=a.vectorLength({x:c.dispX,y:c.dispY});0!==f&&(c.plotX+=c.dispX/f*Math.min(Math.abs(c.dispX),a.temperature),
c.plotY+=c.dispY/f*Math.min(Math.abs(c.dispY),a.temperature))},getK:function(a){return Math.pow(a.box.width*a.box.height/a.nodes.length,.3)}}}});l(e,"Series/Networkgraph/QuadTree.js",[e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,a){a=a.extend;var c=e.QuadTreeNode=function(a){this.box=a;this.boxSize=Math.min(a.width,a.height);this.nodes=[];this.body=this.isInternal=!1;this.isEmpty=!0};a(c.prototype,{insert:function(a,d){this.isInternal?this.nodes[this.getBoxPosition(a)].insert(a,d-1):(this.isEmpty=
!1,this.body?d?(this.isInternal=!0,this.divideBox(),!0!==this.body&&(this.nodes[this.getBoxPosition(this.body)].insert(this.body,d-1),this.body=!0),this.nodes[this.getBoxPosition(a)].insert(a,d-1)):(d=new c({top:a.plotX,left:a.plotY,width:.1,height:.1}),d.body=a,d.isInternal=!1,this.nodes.push(d)):(this.isInternal=!1,this.body=a))},updateMassAndCenter:function(){var a=0,d=0,c=0;this.isInternal?(this.nodes.forEach(function(f){f.isEmpty||(a+=f.mass,d+=f.plotX*f.mass,c+=f.plotY*f.mass)}),d/=a,c/=a):
this.body&&(a=this.body.mass,d=this.body.plotX,c=this.body.plotY);this.mass=a;this.plotX=d;this.plotY=c},divideBox:function(){var a=this.box.width/2,d=this.box.height/2;this.nodes[0]=new c({left:this.box.left,top:this.box.top,width:a,height:d});this.nodes[1]=new c({left:this.box.left+a,top:this.box.top,width:a,height:d});this.nodes[2]=new c({left:this.box.left+a,top:this.box.top+d,width:a,height:d});this.nodes[3]=new c({left:this.box.left,top:this.box.top+d,width:a,height:d})},getBoxPosition:function(a){var c=
a.plotY<this.box.top+this.box.height/2;return a.plotX<this.box.left+this.box.width/2?c?0:3:c?1:2}});e=e.QuadTree=function(a,d,e,p){this.box={left:a,top:d,width:e,height:p};this.maxDepth=25;this.root=new c(this.box,"0");this.root.isInternal=!0;this.root.isRoot=!0;this.root.divideBox()};a(e.prototype,{insertNodes:function(a){a.forEach(function(a){this.root.insert(a,this.maxDepth)},this)},visitNodeRecursive:function(a,c,e){var d;a||(a=this.root);a===this.root&&c&&(d=c(a));!1!==d&&(a.nodes.forEach(function(a){if(a.isInternal){c&&
(d=c(a));if(!1===d)return;this.visitNodeRecursive(a,c,e)}else a.body&&c&&c(a.body);e&&e(a)},this),a===this.root&&e&&e(a))},calculateMassAndCenter:function(){this.visitNodeRecursive(null,null,function(a){a.updateMassAndCenter()})}})});l(e,"Series/Networkgraph/Layouts.js",[e["Core/Chart/Chart.js"],e["Core/Animation/AnimationUtilities.js"],e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,a,c,f){var d=a.setAnimation;a=f.addEvent;var h=f.clamp,p=f.defined,k=f.extend,q=f.isFunction,m=f.pick;c.layouts=
{"reingold-fruchterman":function(){}};k(c.layouts["reingold-fruchterman"].prototype,{init:function(b){this.options=b;this.nodes=[];this.links=[];this.series=[];this.box={x:0,y:0,width:0,height:0};this.setInitialRendering(!0);this.integration=c.networkgraphIntegrations[b.integration];this.enableSimulation=b.enableSimulation;this.attractiveForce=m(b.attractiveForce,this.integration.attractiveForceFunction);this.repulsiveForce=m(b.repulsiveForce,this.integration.repulsiveForceFunction);this.approximation=
b.approximation},updateSimulation:function(b){this.enableSimulation=m(b,this.options.enableSimulation)},start:function(){var b=this.series,a=this.options;this.currentStep=0;this.forces=b[0]&&b[0].forces||[];this.chart=b[0]&&b[0].chart;this.initialRendering&&(this.initPositions(),b.forEach(function(b){b.finishedAnimating=!0;b.render()}));this.setK();this.resetSimulation(a);this.enableSimulation&&this.step()},step:function(){var b=this,a=this.series;b.currentStep++;"barnes-hut"===b.approximation&&(b.createQuadTree(),
b.quadTree.calculateMassAndCenter());b.forces.forEach(function(a){b[a+"Forces"](b.temperature)});b.applyLimits(b.temperature);b.temperature=b.coolDown(b.startTemperature,b.diffTemperature,b.currentStep);b.prevSystemTemperature=b.systemTemperature;b.systemTemperature=b.getSystemTemperature();b.enableSimulation&&(a.forEach(function(b){b.chart&&b.render()}),b.maxIterations--&&isFinite(b.temperature)&&!b.isStable()?(b.simulation&&c.win.cancelAnimationFrame(b.simulation),b.simulation=c.win.requestAnimationFrame(function(){b.step()})):
b.simulation=!1)},stop:function(){this.simulation&&c.win.cancelAnimationFrame(this.simulation)},setArea:function(b,a,c,d){this.box={left:b,top:a,width:c,height:d}},setK:function(){this.k=this.options.linkLength||this.integration.getK(this)},addElementsToCollection:function(b,a){b.forEach(function(b){-1===a.indexOf(b)&&a.push(b)})},removeElementFromCollection:function(b,a){b=a.indexOf(b);-1!==b&&a.splice(b,1)},clear:function(){this.nodes.length=0;this.links.length=0;this.series.length=0;this.resetSimulation()},
resetSimulation:function(){this.forcedStop=!1;this.systemTemperature=0;this.setMaxIterations();this.setTemperature();this.setDiffTemperature()},restartSimulation:function(){this.simulation?this.resetSimulation():(this.setInitialRendering(!1),this.enableSimulation?this.start():this.setMaxIterations(1),this.chart&&this.chart.redraw(),this.setInitialRendering(!0))},setMaxIterations:function(b){this.maxIterations=m(b,this.options.maxIterations)},setTemperature:function(){this.temperature=this.startTemperature=
Math.sqrt(this.nodes.length)},setDiffTemperature:function(){this.diffTemperature=this.startTemperature/(this.options.maxIterations+1)},setInitialRendering:function(b){this.initialRendering=b},createQuadTree:function(){this.quadTree=new c.QuadTree(this.box.left,this.box.top,this.box.width,this.box.height);this.quadTree.insertNodes(this.nodes)},initPositions:function(){var b=this.options.initialPositions;q(b)?(b.call(this),this.nodes.forEach(function(b){p(b.prevX)||(b.prevX=b.plotX);p(b.prevY)||(b.prevY=
b.plotY);b.dispX=0;b.dispY=0})):"circle"===b?this.setCircularPositions():this.setRandomPositions()},setCircularPositions:function(){function b(a){a.linksFrom.forEach(function(a){h[a.toNode.id]||(h[a.toNode.id]=!0,e.push(a.toNode),b(a.toNode))})}var a=this.box,c=this.nodes,d=2*Math.PI/(c.length+1),f=c.filter(function(b){return 0===b.linksTo.length}),e=[],h={},k=this.options.initialPositionRadius;f.forEach(function(a){e.push(a);b(a)});e.length?c.forEach(function(b){-1===e.indexOf(b)&&e.push(b)}):e=
c;e.forEach(function(b,c){b.plotX=b.prevX=m(b.plotX,a.width/2+k*Math.cos(c*d));b.plotY=b.prevY=m(b.plotY,a.height/2+k*Math.sin(c*d));b.dispX=0;b.dispY=0})},setRandomPositions:function(){function b(b){b=b*b/Math.PI;return b-=Math.floor(b)}var a=this.box,c=this.nodes,d=c.length+1;c.forEach(function(c,g){c.plotX=c.prevX=m(c.plotX,a.width*b(g));c.plotY=c.prevY=m(c.plotY,a.height*b(d+g));c.dispX=0;c.dispY=0})},force:function(b){this.integration[b].apply(this,Array.prototype.slice.call(arguments,1))},barycenterForces:function(){this.getBarycenter();
this.force("barycenter")},getBarycenter:function(){var b=0,a=0,c=0;this.nodes.forEach(function(g){a+=g.plotX*g.mass;c+=g.plotY*g.mass;b+=g.mass});return this.barycenter={x:a,y:c,xFactor:a/b,yFactor:c/b}},barnesHutApproximation:function(b,a){var c=this.getDistXY(b,a),g=this.vectorLength(c);if(b!==a&&0!==g)if(a.isInternal)if(a.boxSize/g<this.options.theta&&0!==g){var d=this.repulsiveForce(g,this.k);this.force("repulsive",b,d*a.mass,c,g);var e=!1}else e=!0;else d=this.repulsiveForce(g,this.k),this.force("repulsive",
b,d*a.mass,c,g);return e},repulsiveForces:function(){var b=this;"barnes-hut"===b.approximation?b.nodes.forEach(function(a){b.quadTree.visitNodeRecursive(null,function(c){return b.barnesHutApproximation(a,c)})}):b.nodes.forEach(function(a){b.nodes.forEach(function(c){if(a!==c&&!a.fixedPosition){var g=b.getDistXY(a,c);var d=b.vectorLength(g);if(0!==d){var n=b.repulsiveForce(d,b.k);b.force("repulsive",a,n*c.mass,g,d)}}})})},attractiveForces:function(){var b=this,a,c,d;b.links.forEach(function(g){g.fromNode&&
g.toNode&&(a=b.getDistXY(g.fromNode,g.toNode),c=b.vectorLength(a),0!==c&&(d=b.attractiveForce(c,b.k),b.force("attractive",g,d,a,c)))})},applyLimits:function(){var b=this;b.nodes.forEach(function(a){a.fixedPosition||(b.integration.integrate(b,a),b.applyLimitBox(a,b.box),a.dispX=0,a.dispY=0)})},applyLimitBox:function(b,a){var c=b.radius;b.plotX=h(b.plotX,a.left+c,a.width-c);b.plotY=h(b.plotY,a.top+c,a.height-c)},coolDown:function(b,a,c){return b-a*c},isStable:function(){return.00001>Math.abs(this.systemTemperature-
this.prevSystemTemperature)||0>=this.temperature},getSystemTemperature:function(){return this.nodes.reduce(function(b,a){return b+a.temperature},0)},vectorLength:function(b){return Math.sqrt(b.x*b.x+b.y*b.y)},getDistR:function(b,a){b=this.getDistXY(b,a);return this.vectorLength(b)},getDistXY:function(b,a){var c=b.plotX-a.plotX;b=b.plotY-a.plotY;return{x:c,y:b,absX:Math.abs(c),absY:Math.abs(b)}}});a(e,"predraw",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(b){b.stop()})});
a(e,"render",function(){function b(b){b.maxIterations--&&isFinite(b.temperature)&&!b.isStable()&&!b.enableSimulation&&(b.beforeStep&&b.beforeStep(),b.step(),c=!1,a=!0)}var a=!1;if(this.graphLayoutsLookup){d(!1,this);for(this.graphLayoutsLookup.forEach(function(b){b.start()});!c;){var c=!0;this.graphLayoutsLookup.forEach(b)}a&&this.series.forEach(function(b){b&&b.layout&&b.render()})}});a(e,"beforePrint",function(){this.graphLayoutsLookup&&(this.graphLayoutsLookup.forEach(function(b){b.updateSimulation(!1)}),
this.redraw())});a(e,"afterPrint",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(b){b.updateSimulation()});this.redraw()})});l(e,"Series/Networkgraph/DraggableNodes.js",[e["Core/Chart/Chart.js"],e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,a,c){var f=c.addEvent;a.dragNodesMixin={onMouseDown:function(a,c){c=this.chart.pointer.normalize(c);a.fixedPosition={chartX:c.chartX,chartY:c.chartY,plotX:a.plotX,plotY:a.plotY};a.inDragMode=!0},onMouseMove:function(a,c){if(a.fixedPosition&&
a.inDragMode){var d=this.chart;c=d.pointer.normalize(c);var e=a.fixedPosition.chartX-c.chartX,f=a.fixedPosition.chartY-c.chartY;c=d.graphLayoutsLookup;if(5<Math.abs(e)||5<Math.abs(f))e=a.fixedPosition.plotX-e,f=a.fixedPosition.plotY-f,d.isInsidePlot(e,f)&&(a.plotX=e,a.plotY=f,a.hasDragged=!0,this.redrawHalo(a),c.forEach(function(a){a.restartSimulation()}))}},onMouseUp:function(a,c){a.fixedPosition&&(a.hasDragged&&(this.layout.enableSimulation?this.layout.start():this.chart.redraw()),a.inDragMode=
a.hasDragged=!1,this.options.fixedDraggable||delete a.fixedPosition)},redrawHalo:function(a){a&&this.halo&&this.halo.attr({d:a.haloPath(this.options.states.hover.halo.size)})}};f(e,"load",function(){var a=this,c,e,k;a.container&&(c=f(a.container,"mousedown",function(c){var d=a.hoverPoint;d&&d.series&&d.series.hasDraggableNodes&&d.series.options.draggable&&(d.series.onMouseDown(d,c),e=f(a.container,"mousemove",function(a){return d&&d.series&&d.series.onMouseMove(d,a)}),k=f(a.container.ownerDocument,
"mouseup",function(a){e();k();return d&&d.series&&d.series.onMouseUp(d,a)}))}));f(a,"destroy",function(){c()})})});l(e,"Series/Networkgraph/Networkgraph.js",[e["Core/Series/Series.js"],e["Core/Globals.js"],e["Series/Line/LineSeries.js"],e["Mixins/Nodes.js"],e["Core/Series/Point.js"],e["Core/Utilities.js"]],function(e,a,c,f,d,h){var l=e.seriesTypes,k=h.addEvent,q=h.css,m=h.defined,b=h.pick;h=a.dragNodesMixin;"";e.seriesType("networkgraph","line",{stickyTracking:!1,inactiveOtherPoints:!0,marker:{enabled:!0,
states:{inactive:{opacity:.3,animation:{duration:50}}}},states:{inactive:{linkOpacity:.3,animation:{duration:50}}},dataLabels:{formatter:function(){return this.key},linkFormatter:function(){return this.point.fromNode.name+"<br>"+this.point.toNode.name},linkTextPath:{enabled:!0},textPath:{enabled:!1},style:{transition:"opacity 2000ms"}},link:{color:"rgba(100, 100, 100, 0.5)",width:1},draggable:!0,layoutAlgorithm:{initialPositions:"circle",initialPositionRadius:1,enableSimulation:!1,theta:.5,maxSpeed:10,
approximation:"none",type:"reingold-fruchterman",integration:"euler",maxIterations:1E3,gravitationalConstant:.0625,friction:-.981},showInLegend:!1},{forces:["barycenter","repulsive","attractive"],hasDraggableNodes:!0,drawGraph:null,isCartesian:!1,requireSorting:!1,directTouch:!0,noSharedTooltip:!0,pointArrayMap:["from","to"],trackerGroups:["group","markerGroup","dataLabelsGroup"],drawTracker:a.TrackerMixin.drawTrackerPoint,animate:null,buildKDTree:a.noop,createNode:f.createNode,destroy:function(){this.layout&&
this.layout.removeElementFromCollection(this,this.layout.series);f.destroy.call(this)},init:function(){c.prototype.init.apply(this,arguments);k(this,"updatedData",function(){this.layout&&this.layout.stop()});return this},generatePoints:function(){var a;f.generatePoints.apply(this,arguments);this.options.nodes&&this.options.nodes.forEach(function(a){this.nodeLookup[a.id]||(this.nodeLookup[a.id]=this.createNode(a.id))},this);for(a=this.nodes.length-1;0<=a;a--){var c=this.nodes[a];c.degree=c.getDegree();
c.radius=b(c.marker&&c.marker.radius,this.options.marker&&this.options.marker.radius,0);this.nodeLookup[c.id]||c.remove()}this.data.forEach(function(a){a.formatPrefix="link"});this.indexateNodes()},getPointsCollection:function(){return this.nodes||[]},indexateNodes:function(){this.nodes.forEach(function(a,b){a.index=b})},markerAttribs:function(a,b){b=c.prototype.markerAttribs.call(this,a,b);m(a.plotY)||(b.y=0);b.x=(a.plotX||0)-(b.width/2||0);return b},translate:function(){this.processedXData||this.processData();
this.generatePoints();this.deferLayout();this.nodes.forEach(function(a){a.isInside=!0;a.linksFrom.forEach(function(a){a.shapeType="path";a.y=1})})},deferLayout:function(){var b=this.options.layoutAlgorithm,c=this.chart.graphLayoutsStorage,d=this.chart.graphLayoutsLookup,e=this.chart.options.chart;if(this.visible){c||(this.chart.graphLayoutsStorage=c={},this.chart.graphLayoutsLookup=d=[]);var f=c[b.type];f||(b.enableSimulation=m(e.forExport)?!e.forExport:b.enableSimulation,c[b.type]=f=new a.layouts[b.type],
f.init(b),d.splice(f.index,0,f));this.layout=f;f.setArea(0,0,this.chart.plotWidth,this.chart.plotHeight);f.addElementsToCollection([this],f.series);f.addElementsToCollection(this.nodes,f.nodes);f.addElementsToCollection(this.points,f.links)}},render:function(){var a=this.points,b=this.chart.hoverPoint,c=[];this.points=this.nodes;l.line.prototype.render.call(this);this.points=a;a.forEach(function(a){a.fromNode&&a.toNode&&(a.renderLink(),a.redrawLink())});b&&b.series===this&&this.redrawHalo(b);this.chart.hasRendered&&
!this.options.dataLabels.allowOverlap&&(this.nodes.concat(this.points).forEach(function(a){a.dataLabel&&c.push(a.dataLabel)}),this.chart.hideOverlappingLabels(c))},drawDataLabels:function(){var a=this.options.dataLabels.textPath;c.prototype.drawDataLabels.apply(this,arguments);this.points=this.data;this.options.dataLabels.textPath=this.options.dataLabels.linkTextPath;c.prototype.drawDataLabels.apply(this,arguments);this.points=this.nodes;this.options.dataLabels.textPath=a},pointAttribs:function(a,
d){var e=d||a&&a.state||"normal";d=c.prototype.pointAttribs.call(this,a,e);e=this.options.states[e];a&&!a.isNode&&(d=a.getLinkAttributes(),e&&(d={stroke:e.linkColor||d.stroke,dashstyle:e.linkDashStyle||d.dashstyle,opacity:b(e.linkOpacity,d.opacity),"stroke-width":e.linkColor||d["stroke-width"]}));return d},redrawHalo:h.redrawHalo,onMouseDown:h.onMouseDown,onMouseMove:h.onMouseMove,onMouseUp:h.onMouseUp,setState:function(a,b){b?(this.points=this.nodes.concat(this.data),c.prototype.setState.apply(this,
arguments),this.points=this.data):c.prototype.setState.apply(this,arguments);this.layout.simulation||a||this.render()}},{setState:f.setNodeState,init:function(){d.prototype.init.apply(this,arguments);this.series.options.draggable&&!this.series.chart.styledMode&&(k(this,"mouseOver",function(){q(this.series.chart.container,{cursor:"move"})}),k(this,"mouseOut",function(){q(this.series.chart.container,{cursor:"default"})}));return this},getDegree:function(){var a=this.isNode?this.linksFrom.length+this.linksTo.length:
0;return 0===a?1:a},getLinkAttributes:function(){var a=this.series.options.link,c=this.options;return{"stroke-width":b(c.width,a.width),stroke:c.color||a.color,dashstyle:c.dashStyle||a.dashStyle,opacity:b(c.opacity,a.opacity,1)}},renderLink:function(){if(!this.graphic&&(this.graphic=this.series.chart.renderer.path(this.getLinkPath()).add(this.series.group),!this.series.chart.styledMode)){var a=this.series.pointAttribs(this);this.graphic.attr(a);(this.dataLabels||[]).forEach(function(b){b&&b.attr({opacity:a.opacity})})}},
redrawLink:function(){var a=this.getLinkPath();if(this.graphic){this.shapeArgs={d:a};if(!this.series.chart.styledMode){var b=this.series.pointAttribs(this);this.graphic.attr(b);(this.dataLabels||[]).forEach(function(a){a&&a.attr({opacity:b.opacity})})}this.graphic.animate(this.shapeArgs);var c=a[0];a=a[1];"M"===c[0]&&"L"===a[0]&&(this.plotX=(c[1]+a[1])/2,this.plotY=(c[2]+a[2])/2)}},getMass:function(){var a=this.fromNode.mass,b=this.toNode.mass,c=a+b;return{fromNode:1-a/c,toNode:1-b/c}},getLinkPath:function(){var a=
this.fromNode,b=this.toNode;a.plotX>b.plotX&&(a=this.toNode,b=this.fromNode);return[["M",a.plotX||0,a.plotY||0],["L",b.plotX||0,b.plotY||0]]},isValid:function(){return!this.isNode||m(this.id)},remove:function(a,b){var d=this.series,e=d.options.nodes||[],f,g=e.length;if(this.isNode){d.points=[];[].concat(this.linksFrom).concat(this.linksTo).forEach(function(a){f=a.fromNode.linksFrom.indexOf(a);-1<f&&a.fromNode.linksFrom.splice(f,1);f=a.toNode.linksTo.indexOf(a);-1<f&&a.toNode.linksTo.splice(f,1);c.prototype.removePoint.call(d,
d.data.indexOf(a),!1,!1)});d.points=d.data.slice();for(d.nodes.splice(d.nodes.indexOf(this),1);g--;)if(e[g].id===this.options.id){d.options.nodes.splice(g,1);break}this&&this.destroy();d.isDirty=!0;d.isDirtyData=!0;a&&d.chart.redraw(a)}else d.removePoint(d.data.indexOf(this),a,b)},destroy:function(){this.isNode&&this.linksFrom.concat(this.linksTo).forEach(function(a){a.destroyElements&&a.destroyElements()});this.series.layout.removeElementFromCollection(this,this.series.layout[this.isNode?"nodes":
"links"]);return d.prototype.destroy.apply(this,arguments)}});""});l(e,"masters/modules/networkgraph.src.js",[],function(){})});
//# sourceMappingURL=networkgraph.js.map