/*
 Highstock JS v8.2.2 (2020-11-23)

 Highstock as a plugin for Highcharts

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(d){"object"===typeof module&&module.exports?(d["default"]=d,module.exports=d):"function"===typeof define&&define.amd?define("highcharts/modules/stock",["highcharts"],function(I){d(I);d.Highcharts=I;return d}):d("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(d){function I(d,C,y,t){d.hasOwnProperty(C)||(d[C]=t.apply(null,y))}d=d?d._modules:{};I(d,"Core/Axis/NavigatorAxis.js",[d["Core/Globals.js"],d["Core/Utilities.js"]],function(d,C){var y=d.isTouchDevice,t=C.addEvent,m=C.correctFloat,
D=C.defined,v=C.isNumber,q=C.pick,b=function(){function a(a){this.axis=a}a.prototype.destroy=function(){this.axis=void 0};a.prototype.toFixedRange=function(a,b,h,A){var x=this.axis,n=x.chart;n=n&&n.fixedRange;var H=(x.pointRange||0)/2;a=q(h,x.translate(a,!0,!x.horiz));b=q(A,x.translate(b,!0,!x.horiz));x=n&&(b-a)/n;D(h)||(a=m(a+H));D(A)||(b=m(b-H));.7<x&&1.3>x&&(A?a=b-n:b=a+n);v(a)&&v(b)||(a=b=void 0);return{min:a,max:b}};return a}();return function(){function a(){}a.compose=function(a){a.keepProps.push("navigatorAxis");
t(a,"init",function(){this.navigatorAxis||(this.navigatorAxis=new b(this))});t(a,"zoom",function(a){var b=this.chart.options,A=b.navigator,x=this.navigatorAxis,n=b.chart.pinchType,H=b.rangeSelector;b=b.chart.zoomType;this.isXAxis&&(A&&A.enabled||H&&H.enabled)&&("y"===b?a.zoomed=!1:(!y&&"xy"===b||y&&"xy"===n)&&this.options.range&&(A=x.previousZoom,D(a.newMin)?x.previousZoom=[this.min,this.max]:A&&(a.newMin=A[0],a.newMax=A[1],x.previousZoom=void 0)));"undefined"!==typeof a.zoomed&&a.preventDefault()})};
a.AdditionsClass=b;return a}()});I(d,"Core/Axis/ScrollbarAxis.js",[d["Core/Globals.js"],d["Core/Utilities.js"]],function(d,C){var y=C.addEvent,t=C.defined,m=C.pick;return function(){function D(){}D.compose=function(v,q){y(v,"afterInit",function(){var b=this;b.options&&b.options.scrollbar&&b.options.scrollbar.enabled&&(b.options.scrollbar.vertical=!b.horiz,b.options.startOnTick=b.options.endOnTick=!1,b.scrollbar=new q(b.chart.renderer,b.options.scrollbar,b.chart),y(b.scrollbar,"changed",function(a){var q=
m(b.options&&b.options.min,b.min),v=m(b.options&&b.options.max,b.max),h=t(b.dataMin)?Math.min(q,b.min,b.dataMin):q,A=(t(b.dataMax)?Math.max(v,b.max,b.dataMax):v)-h;t(q)&&t(v)&&(b.horiz&&!b.reversed||!b.horiz&&b.reversed?(q=h+A*this.to,h+=A*this.from):(q=h+A*(1-this.from),h+=A*(1-this.to)),m(this.options.liveRedraw,d.svg&&!d.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===a.DOMType||!t(a.DOMType)?b.setExtremes(h,q,!0,"mousemove"!==a.DOMType,a):this.setRange(this.from,this.to))}))});y(v,"afterRender",
function(){var b=Math.min(m(this.options.min,this.min),this.min,m(this.dataMin,this.min)),a=Math.max(m(this.options.max,this.max),this.max,m(this.dataMax,this.max)),q=this.scrollbar,d=this.axisTitleMargin+(this.titleOffset||0),h=this.chart.scrollbarsOffsets,A=this.options.margin||0;q&&(this.horiz?(this.opposite||(h[1]+=d),q.position(this.left,this.top+this.height+2+h[1]-(this.opposite?A:0),this.width,this.height),this.opposite||(h[1]+=A),d=1):(this.opposite&&(h[0]+=d),q.position(this.left+this.width+
2+h[0]-(this.opposite?0:A),this.top,this.width,this.height),this.opposite&&(h[0]+=A),d=0),h[d]+=q.size+q.options.margin,isNaN(b)||isNaN(a)||!t(this.min)||!t(this.max)||this.min===this.max?q.setRange(0,1):(h=(this.min-b)/(a-b),b=(this.max-b)/(a-b),this.horiz&&!this.reversed||!this.horiz&&this.reversed?q.setRange(h,b):q.setRange(1-b,1-h)))});y(v,"afterGetOffset",function(){var b=this.horiz?2:1,a=this.scrollbar;a&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[b]+=a.size+a.options.margin)})};
return D}()});I(d,"Core/Scrollbar.js",[d["Core/Axis/Axis.js"],d["Core/Globals.js"],d["Core/Color/Palette.js"],d["Core/Axis/ScrollbarAxis.js"],d["Core/Utilities.js"],d["Core/Options.js"]],function(d,C,y,t,m,D){var v=m.addEvent,q=m.correctFloat,b=m.defined,a=m.destroyObjectProperties,E=m.fireEvent,J=m.merge,h=m.pick,A=m.removeEvent;m=D.defaultOptions;var x=C.hasTouch,n=C.isTouchDevice,H=C.swapXY=function(a,G){G&&a.forEach(function(l){for(var f=l.length,G,a=0;a<f;a+=2)G=l[a+1],"number"===typeof G&&(l[a+
1]=l[a+2],l[a+2]=G)});return a};D=function(){function r(a,l,f){this._events=[];this.from=this.chartY=this.chartX=0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=1;this.userOptions={};this.y=this.x=0;this.chart=f;this.options=l;this.renderer=f.renderer;this.init(a,l,f)}r.prototype.addEvents=function(){var a=
this.options.inverted?[1,0]:[0,1],l=this.scrollbarButtons,f=this.scrollbarGroup.element,b=this.track.element,n=this.mouseDownHandler.bind(this),p=this.mouseMoveHandler.bind(this),g=this.mouseUpHandler.bind(this);a=[[l[a[0]].element,"click",this.buttonToMinClick.bind(this)],[l[a[1]].element,"click",this.buttonToMaxClick.bind(this)],[b,"click",this.trackClick.bind(this)],[f,"mousedown",n],[f.ownerDocument,"mousemove",p],[f.ownerDocument,"mouseup",g]];x&&a.push([f,"touchstart",n],[f.ownerDocument,"touchmove",
p],[f.ownerDocument,"touchend",g]);a.forEach(function(g){v.apply(null,g)});this._events=a};r.prototype.buttonToMaxClick=function(a){var l=(this.to-this.from)*h(this.options.step,.2);this.updatePosition(this.from+l,this.to+l);E(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};r.prototype.buttonToMinClick=function(a){var l=q(this.to-this.from)*h(this.options.step,.2);this.updatePosition(q(this.from-l),q(this.to-l));E(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",
DOMEvent:a})};r.prototype.cursorToScrollbarPosition=function(a){var l=this.options;l=l.minWidth>this.calculatedWidth?l.minWidth:0;return{chartX:(a.chartX-this.x-this.xOffset)/(this.barWidth-l),chartY:(a.chartY-this.y-this.yOffset)/(this.barWidth-l)}};r.prototype.destroy=function(){var G=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(l){this[l]&&this[l].destroy&&(this[l]=this[l].destroy())},this);G&&this===G.scrollbar&&(G.scrollbar=
null,a(G.scrollbarButtons))};r.prototype.drawScrollbarButton=function(a){var l=this.renderer,f=this.scrollbarButtons,b=this.options,G=this.size;var p=l.g().add(this.group);f.push(p);p=l.rect().addClass("highcharts-scrollbar-button").add(p);this.chart.styledMode||p.attr({stroke:b.buttonBorderColor,"stroke-width":b.buttonBorderWidth,fill:b.buttonBackgroundColor});p.attr(p.crisp({x:-.5,y:-.5,width:G+1,height:G+1,r:b.buttonBorderRadius},p.strokeWidth()));p=l.path(H([["M",G/2+(a?-1:1),G/2-3],["L",G/2+
(a?-1:1),G/2+3],["L",G/2+(a?2:-2),G/2]],b.vertical)).addClass("highcharts-scrollbar-arrow").add(f[a]);this.chart.styledMode||p.attr({fill:b.buttonArrowColor})};r.prototype.init=function(a,l,f){this.scrollbarButtons=[];this.renderer=a;this.userOptions=l;this.options=J(r.defaultOptions,l);this.chart=f;this.size=h(this.options.size,this.options.height);l.enabled&&(this.render(),this.addEvents())};r.prototype.mouseDownHandler=function(a){a=this.chart.pointer.normalize(a);a=this.cursorToScrollbarPosition(a);
this.chartX=a.chartX;this.chartY=a.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=!0};r.prototype.mouseMoveHandler=function(a){var l=this.chart.pointer.normalize(a),f=this.options.vertical?"chartY":"chartX",b=this.initPositions||[];!this.grabbedCenter||a.touches&&0===a.touches[0][f]||(l=this.cursorToScrollbarPosition(l)[f],f=this[f],f=l-f,this.hasDragged=!0,this.updatePosition(b[0]+f,b[1]+f),this.hasDragged&&E(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:a.type,
DOMEvent:a}))};r.prototype.mouseUpHandler=function(a){this.hasDragged&&E(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:a.type,DOMEvent:a});this.grabbedCenter=this.hasDragged=this.chartX=this.chartY=null};r.prototype.position=function(a,l,f,b){var n=this.options.vertical,p=0,g=this.rendered?"animate":"attr";this.x=a;this.y=l+this.trackBorderWidth;this.width=f;this.xOffset=this.height=b;this.yOffset=p;n?(this.width=this.yOffset=f=p=this.size,this.xOffset=l=0,this.barWidth=b-
2*f,this.x=a+=this.options.margin):(this.height=this.xOffset=b=l=this.size,this.barWidth=f-2*b,this.y+=this.options.margin);this.group[g]({translateX:a,translateY:this.y});this.track[g]({width:f,height:b});this.scrollbarButtons[1][g]({translateX:n?0:f-l,translateY:n?b-p:0})};r.prototype.removeEvents=function(){this._events.forEach(function(a){A.apply(null,a)});this._events.length=0};r.prototype.render=function(){var a=this.renderer,l=this.options,f=this.size,b=this.chart.styledMode,n;this.group=n=
a.g("scrollbar").attr({zIndex:l.zIndex,translateY:-99999}).add();this.track=a.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:l.trackBorderRadius||0,height:f,width:f}).add(n);b||this.track.attr({fill:l.trackBackgroundColor,stroke:l.trackBorderColor,"stroke-width":l.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=a.g().add(n);this.scrollbar=a.rect().addClass("highcharts-scrollbar-thumb").attr({height:f,
width:f,r:l.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=a.path(H([["M",-3,f/4],["L",-3,2*f/3],["M",0,f/4],["L",0,2*f/3],["M",3,f/4],["L",3,2*f/3]],l.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);b||(this.scrollbar.attr({fill:l.barBackgroundColor,stroke:l.barBorderColor,"stroke-width":l.barBorderWidth}),this.scrollbarRifles.attr({stroke:l.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%
2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};r.prototype.setRange=function(a,l){var f=this.options,n=f.vertical,r=f.minWidth,p=this.barWidth,g,w=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(b(p)){a=Math.max(a,0);var e=Math.ceil(p*a);this.calculatedWidth=g=q(p*Math.min(l,1)-e);g<r&&(e=(p-r+g)*a,g=r);r=Math.floor(e+this.xOffset+this.yOffset);p=g/2-.5;this.from=a;this.to=l;n?(this.scrollbarGroup[w]({translateY:r}),
this.scrollbar[w]({height:g}),this.scrollbarRifles[w]({translateY:p}),this.scrollbarTop=r,this.scrollbarLeft=0):(this.scrollbarGroup[w]({translateX:r}),this.scrollbar[w]({width:g}),this.scrollbarRifles[w]({translateX:p}),this.scrollbarLeft=r,this.scrollbarTop=0);12>=g?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===f.showFull&&(0>=a&&1<=l?this.group.hide():this.group.show());this.rendered=!0}};r.prototype.trackClick=function(a){var l=this.chart.pointer.normalize(a),f=this.to-this.from,
b=this.y+this.scrollbarTop,n=this.x+this.scrollbarLeft;this.options.vertical&&l.chartY>b||!this.options.vertical&&l.chartX>n?this.updatePosition(this.from+f,this.to+f):this.updatePosition(this.from-f,this.to-f);E(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};r.prototype.update=function(a){this.destroy();this.init(this.chart.renderer,J(!0,this.options,a),this.chart)};r.prototype.updatePosition=function(a,l){1<l&&(a=q(1-q(l-a)),l=1);0>a&&(l=q(l-a),a=0);this.from=a;this.to=
l};r.defaultOptions={height:n?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:y.neutralColor20,barBorderWidth:1,barBorderColor:y.neutralColor20,buttonArrowColor:y.neutralColor80,buttonBackgroundColor:y.neutralColor10,buttonBorderColor:y.neutralColor20,buttonBorderWidth:1,rifleColor:y.neutralColor80,trackBackgroundColor:y.neutralColor5,trackBorderColor:y.neutralColor5,trackBorderWidth:1};return r}();C.Scrollbar||(m.scrollbar=J(!0,
D.defaultOptions,m.scrollbar),C.Scrollbar=D,t.compose(d,D));return C.Scrollbar});I(d,"Core/Navigator.js",[d["Core/Axis/Axis.js"],d["Core/Series/Series.js"],d["Core/Chart/Chart.js"],d["Core/Color/Color.js"],d["Core/Globals.js"],d["Series/Line/LineSeries.js"],d["Core/Axis/NavigatorAxis.js"],d["Core/Options.js"],d["Core/Color/Palette.js"],d["Core/Scrollbar.js"],d["Core/Utilities.js"]],function(d,C,y,t,m,D,v,q,b,a,E){t=t.parse;var J=m.hasTouch,h=m.isTouchDevice,A=q.defaultOptions,x=E.addEvent,n=E.clamp,
H=E.correctFloat,r=E.defined,G=E.destroyObjectProperties,l=E.erase,f=E.extend,L=E.find,K=E.isArray,p=E.isNumber,g=E.merge,w=E.pick,e=E.removeEvent,c=E.splat,z=function(c){for(var k=[],F=1;F<arguments.length;F++)k[F-1]=arguments[F];k=[].filter.call(k,p);if(k.length)return Math[c].apply(0,k)};C="undefined"===typeof C.seriesTypes.areaspline?"line":"areaspline";f(A,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,
backgroundColor:b.neutralColor5,borderColor:b.neutralColor40},maskFill:t(b.highlightColor60).setOpacity(.3).get(),outlineColor:b.neutralColor20,outlineWidth:1,series:{type:C,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,
zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:b.neutralColor10,gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:b.neutralColor40},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},
crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});m.Renderer.prototype.symbols["navigator-handle"]=function(c,k,F,a,e){c=(e&&e.width||0)/2;k=Math.round(c/3)+.5;e=e&&e.height||0;return[["M",-c-1,.5],["L",c,.5],["L",c,e+.5],["L",-c-1,e+.5],["L",-c-1,.5],["M",-k,4],["L",-k,e-3],["M",k-1,4],["L",k-1,e-3]]};var B=function(){function u(k){this.zoomedMin=this.zoomedMax=this.yAxis=this.xAxis=this.top=this.size=this.shades=this.rendered=this.range=this.outlineHeight=this.outline=this.opposite=this.navigatorSize=
this.navigatorSeries=this.navigatorOptions=this.navigatorGroup=this.navigatorEnabled=this.left=this.height=this.handles=this.chart=this.baseSeries=void 0;this.init(k)}u.prototype.drawHandle=function(k,c,e,a){var F=this.navigatorOptions.handles.height;this.handles[c][a](e?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(k,10)+.5-F)}:{translateX:Math.round(this.left+parseInt(k,10)),translateY:Math.round(this.top+this.height/2-F/2-1)})};u.prototype.drawOutline=
function(k,c,e,a){var F=this.navigatorOptions.maskInside,z=this.outline.strokeWidth(),M=z/2,g=z%2/2;z=this.outlineHeight;var u=this.scrollbarHeight||0,l=this.size,f=this.left-u,B=this.top;e?(f-=M,e=B+c+g,c=B+k+g,g=[["M",f+z,B-u-g],["L",f+z,e],["L",f,e],["L",f,c],["L",f+z,c],["L",f+z,B+l+u]],F&&g.push(["M",f+z,e-M],["L",f+z,c+M])):(k+=f+u-g,c+=f+u-g,B+=M,g=[["M",f,B],["L",k,B],["L",k,B+z],["L",c,B+z],["L",c,B],["L",f+l+2*u,B]],F&&g.push(["M",k-M,B],["L",c+M,B]));this.outline[a]({d:g})};u.prototype.drawMasks=
function(k,c,e,a){var F=this.left,z=this.top,g=this.height;if(e){var M=[F,F,F];var u=[z,z+k,z+c];var f=[g,g,g];var l=[k,c-k,this.size-c]}else M=[F,F+k,F+c],u=[z,z,z],f=[k,c-k,this.size-c],l=[g,g,g];this.shades.forEach(function(k,c){k[a]({x:M[c],y:u[c],width:f[c],height:l[c]})})};u.prototype.renderElements=function(){var k=this,c=k.navigatorOptions,e=c.maskInside,a=k.chart,z=a.renderer,g,u={cursor:a.inverted?"ns-resize":"ew-resize"};k.navigatorGroup=g=z.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();
[!e,e,!e].forEach(function(e,F){k.shades[F]=z.rect().addClass("highcharts-navigator-mask"+(1===F?"-inside":"-outside")).add(g);a.styledMode||k.shades[F].attr({fill:e?c.maskFill:"rgba(0,0,0,0)"}).css(1===F&&u)});k.outline=z.path().addClass("highcharts-navigator-outline").add(g);a.styledMode||k.outline.attr({"stroke-width":c.outlineWidth,stroke:c.outlineColor});c.handles.enabled&&[0,1].forEach(function(e){c.handles.inverted=a.inverted;k.handles[e]=z.symbol(c.handles.symbols[e],-c.handles.width/2-1,
0,c.handles.width,c.handles.height,c.handles);k.handles[e].attr({zIndex:7-e}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][e]).add(g);if(!a.styledMode){var F=c.handles;k.handles[e].attr({fill:F.backgroundColor,stroke:F.borderColor,"stroke-width":F.lineWidth}).css(u)}})};u.prototype.update=function(k){(this.series||[]).forEach(function(k){k.baseSeries&&delete k.baseSeries.navigatorSeries});this.destroy();g(!0,this.chart.options.navigator,this.options,k);this.init(this.chart)};
u.prototype.render=function(k,c,e,a){var z=this.chart,g=this.scrollbarHeight,F,u=this.xAxis,M=u.pointRange||0;var f=u.navigatorAxis.fake?z.xAxis[0]:u;var l=this.navigatorEnabled,B,b=this.rendered;var N=z.inverted;var h=z.xAxis[0].minRange,d=z.xAxis[0].options.maxRange;if(!this.hasDragged||r(e)){k=H(k-M/2);c=H(c+M/2);if(!p(k)||!p(c))if(b)e=0,a=w(u.width,f.width);else return;this.left=w(u.left,z.plotLeft+g+(N?z.plotWidth:0));this.size=B=F=w(u.len,(N?z.plotHeight:z.plotWidth)-2*g);z=N?g:F+2*g;e=w(e,
u.toPixels(k,!0));a=w(a,u.toPixels(c,!0));p(e)&&Infinity!==Math.abs(e)||(e=0,a=z);k=u.toValue(e,!0);c=u.toValue(a,!0);var x=Math.abs(H(c-k));x<h?this.grabbedLeft?e=u.toPixels(c-h-M,!0):this.grabbedRight&&(a=u.toPixels(k+h+M,!0)):r(d)&&H(x-M)>d&&(this.grabbedLeft?e=u.toPixels(c-d-M,!0):this.grabbedRight&&(a=u.toPixels(k+d+M,!0)));this.zoomedMax=n(Math.max(e,a),0,B);this.zoomedMin=n(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(e,a),0,B);this.range=this.zoomedMax-this.zoomedMin;B=Math.round(this.zoomedMax);
e=Math.round(this.zoomedMin);l&&(this.navigatorGroup.attr({visibility:"visible"}),b=b&&!this.hasDragged?"animate":"attr",this.drawMasks(e,B,N,b),this.drawOutline(e,B,N,b),this.navigatorOptions.handles.enabled&&(this.drawHandle(e,0,N,b),this.drawHandle(B,1,N,b)));this.scrollbar&&(N?(N=this.top-g,f=this.left-g+(l||!f.opposite?0:(f.titleOffset||0)+f.axisTitleMargin),g=F+2*g):(N=this.top+(l?this.height:-g),f=this.left-g),this.scrollbar.position(f,N,z,g),this.scrollbar.setRange(this.zoomedMin/(F||1),this.zoomedMax/
(F||1)));this.rendered=!0}};u.prototype.addMouseEvents=function(){var k=this,c=k.chart,e=c.container,a=[],z,g;k.mouseMoveHandler=z=function(c){k.onMouseMove(c)};k.mouseUpHandler=g=function(c){k.onMouseUp(c)};a=k.getPartsEvents("mousedown");a.push(x(c.renderTo,"mousemove",z),x(e.ownerDocument,"mouseup",g));J&&(a.push(x(c.renderTo,"touchmove",z),x(e.ownerDocument,"touchend",g)),a.concat(k.getPartsEvents("touchstart")));k.eventsToUnbind=a;k.series&&k.series[0]&&a.push(x(k.series[0].xAxis,"foundExtremes",
function(){c.navigator.modifyNavigatorAxisExtremes()}))};u.prototype.getPartsEvents=function(k){var c=this,e=[];["shades","handles"].forEach(function(a){c[a].forEach(function(z,g){e.push(x(z.element,k,function(k){c[a+"Mousedown"](k,g)}))})});return e};u.prototype.shadesMousedown=function(k,c){k=this.chart.pointer.normalize(k);var e=this.chart,a=this.xAxis,z=this.zoomedMin,g=this.left,u=this.size,F=this.range,f=k.chartX;e.inverted&&(f=k.chartY,g=this.top);if(1===c)this.grabbedCenter=f,this.fixedWidth=
F,this.dragOffset=f-z;else{k=f-g-F/2;if(0===c)k=Math.max(0,k);else if(2===c&&k+F>=u)if(k=u-F,this.reversedExtremes){k-=F;var l=this.getUnionExtremes().dataMin}else var B=this.getUnionExtremes().dataMax;k!==z&&(this.fixedWidth=F,c=a.navigatorAxis.toFixedRange(k,k+F,l,B),r(c.min)&&e.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,null,{trigger:"navigator"}))}};u.prototype.handlesMousedown=function(c,e){this.chart.pointer.normalize(c);c=this.chart;var k=c.xAxis[0],a=this.reversedExtremes;
0===e?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=a?k.min:k.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=a?k.max:k.min);c.fixedRange=null};u.prototype.onMouseMove=function(c){var k=this,e=k.chart,a=k.left,z=k.navigatorSize,g=k.range,u=k.dragOffset,f=e.inverted;c.touches&&0===c.touches[0].pageX||(c=e.pointer.normalize(c),e=c.chartX,f&&(a=k.top,e=c.chartY),k.grabbedLeft?(k.hasDragged=!0,k.render(0,0,e-a,k.otherHandlePos)):k.grabbedRight?
(k.hasDragged=!0,k.render(0,0,k.otherHandlePos,e-a)):k.grabbedCenter&&(k.hasDragged=!0,e<u?e=u:e>z+u-g&&(e=z+u-g),k.render(0,0,e-u,e-u+g)),k.hasDragged&&k.scrollbar&&w(k.scrollbar.options.liveRedraw,m.svg&&!h&&!this.chart.isBoosting)&&(c.DOMType=c.type,setTimeout(function(){k.onMouseUp(c)},0)))};u.prototype.onMouseUp=function(c){var k=this.chart,e=this.xAxis,a=this.scrollbar,z=c.DOMEvent||c,g=k.inverted,u=this.rendered&&!this.hasDragged?"animate":"attr";if(this.hasDragged&&(!a||!a.hasDragged)||"scrollbar"===
c.trigger){a=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var f=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var l=this.fixedExtreme;this.zoomedMax===this.size&&(l=this.reversedExtremes?a.dataMin:a.dataMax);0===this.zoomedMin&&(f=this.reversedExtremes?a.dataMax:a.dataMin);e=e.navigatorAxis.toFixedRange(this.zoomedMin,this.zoomedMax,f,l);r(e.min)&&k.xAxis[0].setExtremes(Math.min(e.min,e.max),Math.max(e.min,e.max),!0,this.hasDragged?!1:null,{trigger:"navigator",
triggerOp:"navigator-drag",DOMEvent:z})}"mousemove"!==c.DOMType&&"touchmove"!==c.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&p(this.zoomedMin)&&p(this.zoomedMax)&&(k=Math.round(this.zoomedMin),c=Math.round(this.zoomedMax),this.shades&&this.drawMasks(k,c,g,u),this.outline&&this.drawOutline(k,c,g,u),this.navigatorOptions.handles.enabled&&Object.keys(this.handles).length===
this.handles.length&&(this.drawHandle(k,0,g,u),this.drawHandle(c,1,g,u)))};u.prototype.removeEvents=function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(c){c()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()};u.prototype.removeBaseSeriesEvents=function(){var c=this.baseSeries||[];this.navigatorEnabled&&c[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&c.forEach(function(c){e(c,"updatedData",this.updatedDataHandler)},this),c[0].xAxis&&e(c[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))};
u.prototype.init=function(c){var e=c.options,k=e.navigator,u=k.enabled,f=e.scrollbar,l=f.enabled;e=u?k.height:0;var B=l?f.height:0;this.handles=[];this.shades=[];this.chart=c;this.setBaseSeries();this.height=e;this.scrollbarHeight=B;this.scrollbarEnabled=l;this.navigatorEnabled=u;this.navigatorOptions=k;this.scrollbarOptions=f;this.outlineHeight=e+B;this.opposite=w(k.opposite,!(u||!c.inverted));var b=this;u=b.baseSeries;f=c.xAxis.length;l=c.yAxis.length;var n=u&&u[0]&&u[0].xAxis||c.xAxis[0]||{options:{}};
c.isDirtyBox=!0;b.navigatorEnabled?(b.xAxis=new d(c,g({breaks:n.options.breaks,ordinal:n.options.ordinal},k.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:f,isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},c.inverted?{offsets:[B,0,-B,0],width:e}:{offsets:[0,-B,0,B],height:e})),b.yAxis=new d(c,g(k.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:l,isInternal:!0,reversed:w(k.yAxis&&k.yAxis.reversed,
c.yAxis[0]&&c.yAxis[0].reversed,!1),zoomEnabled:!1},c.inverted?{width:e}:{height:e})),u||k.series.data?b.updateNavigatorSeries(!1):0===c.series.length&&(b.unbindRedraw=x(c,"beforeRedraw",function(){0<c.series.length&&!b.series&&(b.setBaseSeries(),b.unbindRedraw())})),b.reversedExtremes=c.inverted&&!b.xAxis.reversed||!c.inverted&&b.xAxis.reversed,b.renderElements(),b.addMouseEvents()):(b.xAxis={chart:c,navigatorAxis:{fake:!0},translate:function(e,k){var a=c.xAxis[0],g=a.getExtremes(),u=a.len-2*B,f=
z("min",a.options.min,g.dataMin);a=z("max",a.options.max,g.dataMax)-f;return k?e*a/u+f:u*(e-f)/a},toPixels:function(c){return this.translate(c)},toValue:function(c){return this.translate(c,!0)}},b.xAxis.navigatorAxis.axis=b.xAxis,b.xAxis.navigatorAxis.toFixedRange=v.AdditionsClass.prototype.toFixedRange.bind(b.xAxis.navigatorAxis));c.options.scrollbar.enabled&&(c.scrollbar=b.scrollbar=new a(c.renderer,g(c.options.scrollbar,{margin:b.navigatorEnabled?0:10,vertical:c.inverted}),c),x(b.scrollbar,"changed",
function(e){var k=b.size,a=k*this.to;k*=this.from;b.hasDragged=b.scrollbar.hasDragged;b.render(0,0,k,a);(c.options.scrollbar.liveRedraw||"mousemove"!==e.DOMType&&"touchmove"!==e.DOMType)&&setTimeout(function(){b.onMouseUp(e)})}));b.addBaseSeriesEvents();b.addChartEvents()};u.prototype.getUnionExtremes=function(c){var e=this.chart.xAxis[0],k=this.xAxis,a=k.options,g=e.options,u;c&&null===e.dataMin||(u={dataMin:w(a&&a.min,z("min",g.min,e.dataMin,k.dataMin,k.min)),dataMax:w(a&&a.max,z("max",g.max,e.dataMax,
k.dataMax,k.max))});return u};u.prototype.setBaseSeries=function(c,e){var k=this.chart,a=this.baseSeries=[];c=c||k.options&&k.options.navigator.baseSeries||(k.series.length?L(k.series,function(c){return!c.options.isInternal}).index:0);(k.series||[]).forEach(function(e,k){e.options.isInternal||!e.options.showInNavigator&&(k!==c&&e.options.id!==c||!1===e.options.showInNavigator)||a.push(e)});this.xAxis&&!this.xAxis.navigatorAxis.fake&&this.updateNavigatorSeries(!0,e)};u.prototype.updateNavigatorSeries=
function(k,a){var z=this,u=z.chart,b=z.baseSeries,l,B,F=z.navigatorOptions.series,n,p={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:void 0,isInternal:!0,states:{inactive:{opacity:1}}},r=z.series=(z.series||[]).filter(function(c){var k=c.baseSeries;return 0>b.indexOf(k)?(k&&(e(k,"updatedData",z.updatedDataHandler),delete k.navigatorSeries),c.chart&&c.destroy(),!1):!0});b&&b.length&&b.forEach(function(c){var e=
c.navigatorSeries,k=f({color:c.color,visible:c.visible},K(F)?A.navigator.series:F);e&&!1===z.navigatorOptions.adaptToUpdatedData||(p.name="Navigator "+b.length,l=c.options||{},n=l.navigatorOptions||{},B=g(l,p,k,n),B.pointRange=w(k.pointRange,n.pointRange,A.plotOptions[B.type||"line"].pointRange),k=n.data||k.data,z.hasNavigatorData=z.hasNavigatorData||!!k,B.data=k||l.data&&l.data.slice(0),e&&e.options?e.update(B,a):(c.navigatorSeries=u.initSeries(B),c.navigatorSeries.baseSeries=c,r.push(c.navigatorSeries)))});
if(F.data&&(!b||!b.length)||K(F))z.hasNavigatorData=!1,F=c(F),F.forEach(function(c,e){p.name="Navigator "+(r.length+1);B=g(A.navigator.series,{color:u.series[e]&&!u.series[e].options.isInternal&&u.series[e].color||u.options.colors[e]||u.options.colors[0]},p,c);B.data=c.data;B.data&&(z.hasNavigatorData=!0,r.push(u.initSeries(B)))});k&&this.addBaseSeriesEvents()};u.prototype.addBaseSeriesEvents=function(){var c=this,e=c.baseSeries||[];e[0]&&e[0].xAxis&&x(e[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);
e.forEach(function(e){x(e,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});x(e,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&e.xAxis&&x(e,"updatedData",this.updatedDataHandler);x(e,"remove",function(){this.navigatorSeries&&(l(c.series,this.navigatorSeries),r(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)};u.prototype.getBaseSeriesMin=
function(c){return this.baseSeries.reduce(function(c,e){return Math.min(c,e.xData?e.xData[0]:c)},c)};u.prototype.modifyNavigatorAxisExtremes=function(){var c=this.xAxis,e;"undefined"!==typeof c.getExtremes&&(!(e=this.getUnionExtremes(!0))||e.dataMin===c.min&&e.dataMax===c.max||(c.min=e.dataMin,c.max=e.dataMax))};u.prototype.modifyBaseAxisExtremes=function(){var c=this.chart.navigator,e=this.getExtremes(),a=e.dataMin,z=e.dataMax;e=e.max-e.min;var g=c.stickToMin,u=c.stickToMax,f=w(this.options.overscroll,
0),B=c.series&&c.series[0],b=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(g){var l=a;var n=l+e}u&&(n=z+f,g||(l=Math.max(a,n-e,c.getBaseSeriesMin(B&&B.xData?B.xData[0]:-Number.MAX_VALUE))));b&&(g||u)&&p(l)&&(this.min=this.userMin=l,this.max=this.userMax=n)}c.stickToMin=c.stickToMax=null};u.prototype.updatedDataHandler=function(){var c=this.chart.navigator,e=this.navigatorSeries,a=c.getBaseSeriesMin(this.xData[0]);c.stickToMax=c.reversedExtremes?0===Math.round(c.zoomedMin):
Math.round(c.zoomedMax)>=Math.round(c.size);c.stickToMin=p(this.xAxis.min)&&this.xAxis.min<=a&&(!this.chart.fixedRange||!c.stickToMax);e&&!c.hasNavigatorData&&(e.options.pointStart=this.xData[0],e.setData(this.options.data,!1,null,!1))};u.prototype.addChartEvents=function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(x(this.chart,"redraw",function(){var c=this.navigator,e=c&&(c.baseSeries&&c.baseSeries[0]&&c.baseSeries[0].xAxis||this.xAxis[0]);e&&c.render(e.min,e.max)}),
x(this.chart,"getMargins",function(){var c=this.navigator,e=c.opposite?"plotTop":"marginBottom";this.inverted&&(e=c.opposite?"marginRight":"plotLeft");this[e]=(this[e]||0)+(c.navigatorEnabled||!this.inverted?c.outlineHeight:0)+c.navigatorOptions.margin}))};u.prototype.destroy=function(){this.removeEvents();this.xAxis&&(l(this.chart.xAxis,this.xAxis),l(this.chart.axes,this.xAxis));this.yAxis&&(l(this.chart.yAxis,this.yAxis),l(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(c){c.destroy&&
c.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(c){this[c]&&this[c].destroy&&this[c].destroy();this[c]=null},this);[this.handles].forEach(function(c){G(c)},this)};return u}();m.Navigator||(m.Navigator=B,v.compose(d),x(y,"beforeShowResetZoom",function(){var c=this.options,e=c.navigator,a=c.rangeSelector;if((e&&e.enabled||a&&a.enabled)&&(!h&&"x"===c.chart.zoomType||h&&"x"===c.chart.pinchType))return!1}),
x(y,"beforeRender",function(){var c=this.options;if(c.navigator.enabled||c.scrollbar.enabled)this.scroller=this.navigator=new B(this)}),x(y,"afterSetChartSize",function(){var c=this.legend,e=this.navigator;if(e){var a=c&&c.options;var z=e.xAxis;var g=e.yAxis;var f=e.scrollbarHeight;this.inverted?(e.left=e.opposite?this.chartWidth-f-e.height:this.spacing[3]+f,e.top=this.plotTop+f):(e.left=this.plotLeft+f,e.top=e.navigatorOptions.top||this.chartHeight-e.height-f-this.spacing[2]-(this.rangeSelector&&
this.extraBottomMargin?this.rangeSelector.getHeight():0)-(a&&"bottom"===a.verticalAlign&&"proximate"!==a.layout&&a.enabled&&!a.floating?c.legendHeight+w(a.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));z&&g&&(this.inverted?z.options.left=g.options.left=e.left:z.options.top=g.options.top=e.top,z.setAxisSize(),g.setAxisSize())}}),x(y,"update",function(c){var e=c.options.navigator||{},a=c.options.scrollbar||{};this.navigator||this.scroller||!e.enabled&&!a.enabled||(g(!0,this.options.navigator,
e),g(!0,this.options.scrollbar,a),delete c.options.navigator,delete c.options.scrollbar)}),x(y,"afterUpdate",function(c){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new B(this),w(c.redraw,!0)&&this.redraw(c.animation))}),x(y,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),x(D,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,
!1)}),y.prototype.callbacks.push(function(c){var e=c.navigator;e&&c.xAxis[0]&&(c=c.xAxis[0].getExtremes(),e.render(c.min,c.max))}));m.Navigator=B;return m.Navigator});I(d,"Core/Axis/OrdinalAxis.js",[d["Core/Axis/Axis.js"],d["Core/Globals.js"],d["Series/Line/LineSeries.js"],d["Core/Utilities.js"],d["Core/Chart/Chart.js"]],function(d,C,y,t,m){var D=t.addEvent,v=t.css,q=t.defined,b=t.error,a=t.pick,E=t.timeUnits,J;(function(h){var d=function(){function b(a){this.index={};this.axis=a}b.prototype.beforeSetTickPositions=
function(){var b=this.axis,h=b.ordinal,r=[],d,l=!1,f=b.getExtremes(),q=f.min,x=f.max,p,g=b.isXAxis&&!!b.options.breaks;f=b.options.ordinal;var w=Number.MAX_VALUE,e=b.chart.options.chart.ignoreHiddenSeries,c;if(f||g){b.series.forEach(function(b,k){d=[];if(!(e&&!1===b.visible||!1===b.takeOrdinalPosition&&!g)&&(r=r.concat(b.processedXData),z=r.length,r.sort(function(c,e){return c-e}),w=Math.min(w,a(b.closestPointRange,w)),z)){for(k=0;k<z-1;)r[k]!==r[k+1]&&d.push(r[k+1]),k++;d[0]!==r[0]&&d.unshift(r[0]);
r=d}b.isSeriesBoosting&&(c=!0)});c&&(r.length=0);var z=r.length;if(2<z){var B=r[1]-r[0];for(p=z-1;p--&&!l;)r[p+1]-r[p]!==B&&(l=!0);!b.options.keepOrdinalPadding&&(r[0]-q>B||x-r[r.length-1]>B)&&(l=!0)}else b.options.overscroll&&(2===z?w=r[1]-r[0]:1===z?(w=b.options.overscroll,r=[r[0],r[0]+w]):w=h.overscrollPointsRange);l?(b.options.overscroll&&(h.overscrollPointsRange=w,r=r.concat(h.getOverscrollPositions())),h.positions=r,B=b.ordinal2lin(Math.max(q,r[0]),!0),p=Math.max(b.ordinal2lin(Math.min(x,r[r.length-
1]),!0),1),h.slope=x=(x-q)/(p-B),h.offset=q-B*x):(h.overscrollPointsRange=a(b.closestPointRange,h.overscrollPointsRange),h.positions=b.ordinal.slope=h.offset=void 0)}b.isOrdinal=f&&l;h.groupIntervalFactor=null};b.prototype.getExtendedPositions=function(){var a=this,b=a.axis,r=b.constructor.prototype,h=b.chart,l=b.series[0].currentDataGrouping,f=a.index,d=l?l.count+l.unitName:"raw",q=b.options.overscroll,p=b.getExtremes(),g;f||(f=a.index={});if(!f[d]){var w={series:[],chart:h,getExtremes:function(){return{min:p.dataMin,
max:p.dataMax+q}},options:{ordinal:!0},ordinal:{},ordinal2lin:r.ordinal2lin,val2lin:r.val2lin};w.ordinal.axis=w;b.series.forEach(function(e){g={xAxis:w,xData:e.xData.slice(),chart:h,destroyGroupedData:C.noop,getProcessedData:y.prototype.getProcessedData};g.xData=g.xData.concat(a.getOverscrollPositions());g.options={dataGrouping:l?{enabled:!0,forced:!0,approximation:"open",units:[[l.unitName,[l.count]]]}:{enabled:!1}};e.processData.apply(g);w.series.push(g)});b.ordinal.beforeSetTickPositions.apply({axis:w});
f[d]=w.ordinal.positions}return f[d]};b.prototype.getGroupIntervalFactor=function(a,b,r){r=r.processedXData;var n=r.length,l=[];var f=this.groupIntervalFactor;if(!f){for(f=0;f<n-1;f++)l[f]=r[f+1]-r[f];l.sort(function(a,b){return a-b});l=l[Math.floor(n/2)];a=Math.max(a,r[0]);b=Math.min(b,r[n-1]);this.groupIntervalFactor=f=n*l/(b-a)}return f};b.prototype.getOverscrollPositions=function(){var a=this.axis,b=a.options.overscroll,r=this.overscrollPointsRange,h=[],l=a.dataMax;if(q(r))for(h.push(l);l<=a.dataMax+
b;)l+=r,h.push(l);return h};b.prototype.postProcessTickInterval=function(a){var b=this.axis,r=this.slope;return r?b.options.breaks?b.closestPointRange||a:a/(r/b.closestPointRange):a};return b}();h.Composition=d;h.compose=function(a,n,d){a.keepProps.push("ordinal");var r=a.prototype;a.prototype.getTimeTicks=function(a,l,f,r,n,p,g){void 0===n&&(n=[]);void 0===p&&(p=0);var w=0,e,c,z={},B=[],u=-Number.MAX_VALUE,k=this.options.tickPixelInterval,h=this.chart.time,d=[];if(!this.options.ordinal&&!this.options.breaks||
!n||3>n.length||"undefined"===typeof l)return h.getTimeTicks.apply(h,arguments);var x=n.length;for(e=0;e<x;e++){var A=e&&n[e-1]>f;n[e]<l&&(w=e);if(e===x-1||n[e+1]-n[e]>5*p||A){if(n[e]>u){for(c=h.getTimeTicks(a,n[w],n[e],r);c.length&&c[0]<=u;)c.shift();c.length&&(u=c[c.length-1]);d.push(B.length);B=B.concat(c)}w=e+1}if(A)break}if(c){c=c.info;if(g&&c.unitRange<=E.hour){e=B.length-1;for(w=1;w<e;w++)if(h.dateFormat("%d",B[w])!==h.dateFormat("%d",B[w-1])){z[B[w]]="day";var G=!0}G&&(z[B[0]]="day");c.higherRanks=
z}c.segmentStarts=d;B.info=c}else b(12,!1,this.chart);if(g&&q(k)){w=d=B.length;G=[];var v;for(h=[];w--;)e=this.translate(B[w]),v&&(h[w]=v-e),G[w]=v=e;h.sort();h=h[Math.floor(h.length/2)];h<.6*k&&(h=null);w=B[d-1]>f?d-1:d;for(v=void 0;w--;)e=G[w],d=Math.abs(v-e),v&&d<.8*k&&(null===h||d<.8*h)?(z[B[w]]&&!z[B[w+1]]?(d=w+1,v=e):d=w,B.splice(d,1)):v=e}return B};r.lin2val=function(a,b){var f=this.ordinal,l=f.positions;if(l){var h=f.slope,p=f.offset;f=l.length-1;if(b)if(0>a)a=l[0];else if(a>f)a=l[f];else{f=
Math.floor(a);var g=a-f}else for(;f--;)if(b=h*f+p,a>=b){h=h*(f+1)+p;g=(a-b)/(h-b);break}return"undefined"!==typeof g&&"undefined"!==typeof l[f]?l[f]+(g?g*(l[f+1]-l[f]):0):a}return a};r.val2lin=function(a,b){var f=this.ordinal,l=f.positions;if(l){var h=l.length,p;for(p=h;p--;)if(l[p]===a){var g=p;break}for(p=h-1;p--;)if(a>l[p]||0===p){a=(a-l[p])/(l[p+1]-l[p]);g=p+a;break}b=b?g:f.slope*(g||0)+f.offset}else b=a;return b};r.ordinal2lin=r.val2lin;D(a,"afterInit",function(){this.ordinal||(this.ordinal=
new h.Composition(this))});D(a,"foundExtremes",function(){this.isXAxis&&q(this.options.overscroll)&&this.max===this.dataMax&&(!this.chart.mouseIsDown||this.isInternal)&&(!this.eventArgs||this.eventArgs&&"navigator"!==this.eventArgs.trigger)&&(this.max+=this.options.overscroll,!this.isInternal&&q(this.userMin)&&(this.min+=this.options.overscroll))});D(a,"afterSetScale",function(){this.horiz&&!this.isDirty&&(this.isDirty=this.isOrdinal&&this.chart.navigator&&!this.chart.navigator.adaptToUpdatedData)});
D(a,"initialAxisTranslation",function(){this.ordinal&&(this.ordinal.beforeSetTickPositions(),this.tickInterval=this.ordinal.postProcessTickInterval(this.tickInterval))});D(n,"pan",function(a){var b=this.xAxis[0],f=b.options.overscroll,h=a.originalEvent.chartX,n=this.options.chart&&this.options.chart.panning,p=!1;if(n&&"y"!==n.type&&b.options.ordinal&&b.series.length){var g=this.mouseDownX,w=b.getExtremes(),e=w.dataMax,c=w.min,z=w.max,B=this.hoverPoints,u=b.closestPointRange||b.ordinal&&b.ordinal.overscrollPointsRange;
g=(g-h)/(b.translationSlope*(b.ordinal.slope||u));var k={ordinal:{positions:b.ordinal.getExtendedPositions()}};u=b.lin2val;var d=b.val2lin;if(!k.ordinal.positions)p=!0;else if(1<Math.abs(g)){B&&B.forEach(function(c){c.setState()});if(0>g){B=k;var r=b.ordinal.positions?b:k}else B=b.ordinal.positions?b:k,r=k;k=r.ordinal.positions;e>k[k.length-1]&&k.push(e);this.fixedRange=z-c;g=b.navigatorAxis.toFixedRange(null,null,u.apply(B,[d.apply(B,[c,!0])+g,!0]),u.apply(r,[d.apply(r,[z,!0])+g,!0]));g.min>=Math.min(w.dataMin,
c)&&g.max<=Math.max(e,z)+f&&b.setExtremes(g.min,g.max,!0,!1,{trigger:"pan"});this.mouseDownX=h;v(this.container,{cursor:"move"})}}else p=!0;p||n&&/y/.test(n.type)?f&&(b.max=b.dataMax+f):a.preventDefault()});D(d,"updatedData",function(){var a=this.xAxis;a&&a.options.ordinal&&delete a.ordinal.index})}})(J||(J={}));J.compose(d,m,y);return J});I(d,"Core/Axis/BrokenAxis.js",[d["Core/Axis/Axis.js"],d["Series/Line/LineSeries.js"],d["Extensions/Stacking.js"],d["Core/Utilities.js"]],function(d,C,y,t){var m=
t.addEvent,D=t.find,v=t.fireEvent,q=t.isArray,b=t.isNumber,a=t.pick,E=function(){function b(a){this.hasBreaks=!1;this.axis=a}b.isInBreak=function(a,b){var h=a.repeat||Infinity,n=a.from,d=a.to-a.from;b=b>=n?(b-n)%h:h-(n-b)%h;return a.inclusive?b<=d:b<d&&0!==b};b.lin2Val=function(a){var d=this.brokenAxis;d=d&&d.breakArray;if(!d)return a;var h;for(h=0;h<d.length;h++){var n=d[h];if(n.from>=a)break;else n.to<a?a+=n.len:b.isInBreak(n,a)&&(a+=n.len)}return a};b.val2Lin=function(a){var d=this.brokenAxis;
d=d&&d.breakArray;if(!d)return a;var h=a,n;for(n=0;n<d.length;n++){var q=d[n];if(q.to<=a)h-=q.len;else if(q.from>=a)break;else if(b.isInBreak(q,a)){h-=a-q.from;break}}return h};b.prototype.findBreakAt=function(a,b){return D(b,function(b){return b.from<a&&a<b.to})};b.prototype.isInAnyBreak=function(d,q){var h=this.axis,n=h.options.breaks,v=n&&n.length,r;if(v){for(;v--;)if(b.isInBreak(n[v],d)){var A=!0;r||(r=a(n[v].showPoints,!h.isXAxis))}var l=A&&q?A&&!r:A}return l};b.prototype.setBreaks=function(h,
A){var x=this,n=x.axis,m=q(h)&&!!h.length;n.isDirty=x.hasBreaks!==m;x.hasBreaks=m;n.options.breaks=n.userOptions.breaks=h;n.forceRedraw=!0;n.series.forEach(function(a){a.isDirty=!0});m||n.val2lin!==b.val2Lin||(delete n.val2lin,delete n.lin2val);m&&(n.userOptions.ordinal=!1,n.lin2val=b.lin2Val,n.val2lin=b.val2Lin,n.setExtremes=function(a,b,l,f,n){if(x.hasBreaks){for(var h,p=this.options.breaks;h=x.findBreakAt(a,p);)a=h.to;for(;h=x.findBreakAt(b,p);)b=h.from;b<a&&(b=a)}d.prototype.setExtremes.call(this,
a,b,l,f,n)},n.setAxisTranslation=function(){d.prototype.setAxisTranslation.call(this);x.unitLength=null;if(x.hasBreaks){var h=n.options.breaks||[],q=[],l=[],f=0,A,m=n.userMin||n.min,p=n.userMax||n.max,g=a(n.pointRangePadding,0),w;h.forEach(function(c){A=c.repeat||Infinity;b.isInBreak(c,m)&&(m+=c.to%A-m%A);b.isInBreak(c,p)&&(p-=p%A-c.from%A)});h.forEach(function(e){c=e.from;for(A=e.repeat||Infinity;c-A>m;)c-=A;for(;c<m;)c+=A;for(w=c;w<p;w+=A)q.push({value:w,move:"in"}),q.push({value:w+(e.to-e.from),
move:"out",size:e.breakSize})});q.sort(function(c,e){return c.value===e.value?("in"===c.move?0:1)-("in"===e.move?0:1):c.value-e.value});var e=0;var c=m;q.forEach(function(a){e+="in"===a.move?1:-1;1===e&&"in"===a.move&&(c=a.value);0===e&&(l.push({from:c,to:a.value,len:a.value-c-(a.size||0)}),f+=a.value-c-(a.size||0))});n.breakArray=x.breakArray=l;x.unitLength=p-m-f+g;v(n,"afterBreaks");n.staticScale?n.transA=n.staticScale:x.unitLength&&(n.transA*=(p-n.min+g)/x.unitLength);g&&(n.minPixelPadding=n.transA*
n.minPointOffset);n.min=m;n.max=p}});a(A,!0)&&n.chart.redraw()};return b}();t=function(){function d(){}d.compose=function(d,q){d.keepProps.push("brokenAxis");var h=C.prototype;h.drawBreaks=function(d,h){var n=this,q=n.points,l,f,A,m;if(d&&d.brokenAxis&&d.brokenAxis.hasBreaks){var p=d.brokenAxis;h.forEach(function(g){l=p&&p.breakArray||[];f=d.isXAxis?d.min:a(n.options.threshold,d.min);q.forEach(function(w){m=a(w["stack"+g.toUpperCase()],w[g]);l.forEach(function(e){if(b(f)&&b(m)){A=!1;if(f<e.from&&
m>e.to||f>e.from&&m<e.from)A="pointBreak";else if(f<e.from&&m>e.from&&m<e.to||f>e.from&&m>e.to&&m<e.from)A="pointInBreak";A&&v(d,A,{point:w,brk:e})}})})})}};h.gappedPath=function(){var a=this.currentDataGrouping,b=a&&a.gapSize;a=this.options.gapSize;var d=this.points.slice(),h=d.length-1,l=this.yAxis,f;if(a&&0<h)for("value"!==this.options.gapUnit&&(a*=this.basePointRange),b&&b>a&&b>=this.basePointRange&&(a=b),f=void 0;h--;)f&&!1!==f.visible||(f=d[h+1]),b=d[h],!1!==f.visible&&!1!==b.visible&&(f.x-
b.x>a&&(f=(b.x+f.x)/2,d.splice(h+1,0,{isNull:!0,x:f}),l.stacking&&this.options.stacking&&(f=l.stacking.stacks[this.stackKey][f]=new y(l,l.options.stackLabels,!1,f,this.stack),f.total=0)),f=b);return this.getGraphPath(d)};m(d,"init",function(){this.brokenAxis||(this.brokenAxis=new E(this))});m(d,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});m(d,"afterSetTickPositions",function(){var a=this.brokenAxis;if(a&&a.hasBreaks){var b=this.tickPositions,
d=this.tickPositions.info,h=[],l;for(l=0;l<b.length;l++)a.isInAnyBreak(b[l])||h.push(b[l]);this.tickPositions=h;this.tickPositions.info=d}});m(d,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});m(q,"afterGeneratePoints",function(){var a=this.options.connectNulls,b=this.points,d=this.xAxis,h=this.yAxis;if(this.isDirty)for(var l=b.length;l--;){var f=b[l],q=!(null===f.y&&!1===a)&&(d&&d.brokenAxis&&d.brokenAxis.isInAnyBreak(f.x,!0)||h&&h.brokenAxis&&
h.brokenAxis.isInAnyBreak(f.y,!0));f.visible=q?!1:!1!==f.options.visible}});m(q,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,a(this.pointArrayMap,["y"]))})};return d}();t.compose(d,C);return t});I(d,"masters/modules/broken-axis.src.js",[],function(){});I(d,"Extensions/DataGrouping.js",[d["Core/Axis/Axis.js"],d["Core/Axis/DateTimeAxis.js"],d["Core/Globals.js"],d["Series/Line/LineSeries.js"],d["Core/Options.js"],d["Core/Series/Point.js"],d["Core/Tooltip.js"],
d["Core/Utilities.js"]],function(d,C,y,t,m,D,v,q){var b=t.prototype,a=q.addEvent,E=q.arrayMax,J=q.arrayMin,h=q.correctFloat,A=q.defined,x=q.error,n=q.extend,H=q.format,r=q.isNumber,G=q.merge,l=q.pick;"";var f=y.approximations={sum:function(c){var a=c.length;if(!a&&c.hasNulls)var e=null;else if(a)for(e=0;a--;)e+=c[a];return e},average:function(c){var a=c.length;c=f.sum(c);r(c)&&a&&(c=h(c/a));return c},averages:function(){var c=[];[].forEach.call(arguments,function(a){c.push(f.average(a))});return"undefined"===
typeof c[0]?void 0:c},open:function(c){return c.length?c[0]:c.hasNulls?null:void 0},high:function(c){return c.length?E(c):c.hasNulls?null:void 0},low:function(c){return c.length?J(c):c.hasNulls?null:void 0},close:function(c){return c.length?c[c.length-1]:c.hasNulls?null:void 0},ohlc:function(c,a,e,b){c=f.open(c);a=f.high(a);e=f.low(e);b=f.close(b);if(r(c)||r(a)||r(e)||r(b))return[c,a,e,b]},range:function(c,a){c=f.low(c);a=f.high(a);if(r(c)||r(a))return[c,a];if(null===c&&null===a)return null}};q=function(c,
a,e,b){var g=this,z=g.data,u=g.options&&g.options.data,B=[],l=[],d=[],h=c.length,w=!!a,p=[],n=g.pointArrayMap,q=n&&n.length,v=["x"].concat(n||["y"]),m=0,x=0,E;b="function"===typeof b?b:f[b]?f[b]:f[g.getDGApproximation&&g.getDGApproximation()||"average"];q?n.forEach(function(){p.push([])}):p.push([]);var y=q||1;for(E=0;E<=h&&!(c[E]>=e[0]);E++);for(E;E<=h;E++){for(;"undefined"!==typeof e[m+1]&&c[E]>=e[m+1]||E===h;){var t=e[m];g.dataGroupInfo={start:g.cropStart+x,length:p[0].length};var D=b.apply(g,
p);g.pointClass&&!A(g.dataGroupInfo.options)&&(g.dataGroupInfo.options=G(g.pointClass.prototype.optionsToObject.call({series:g},g.options.data[g.cropStart+x])),v.forEach(function(c){delete g.dataGroupInfo.options[c]}));"undefined"!==typeof D&&(B.push(t),l.push(D),d.push(g.dataGroupInfo));x=E;for(t=0;t<y;t++)p[t].length=0,p[t].hasNulls=!1;m+=1;if(E===h)break}if(E===h)break;if(n)for(t=g.cropStart+E,D=z&&z[t]||g.pointClass.prototype.applyOptions.apply({series:g},[u[t]]),t=0;t<q;t++){var J=D[n[t]];r(J)?
p[t].push(J):null===J&&(p[t].hasNulls=!0)}else t=w?a[E]:null,r(t)?p[0].push(t):null===t&&(p[0].hasNulls=!0)}return{groupedXData:B,groupedYData:l,groupMap:d}};var L={approximations:f,groupData:q},K=b.processData,p=b.generatePoints,g={groupPixelWidth:2,dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],minute:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M",
"-%H:%M"],day:["%A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},w={line:{},spline:{},area:{},areaspline:{},arearange:{},column:{groupPixelWidth:10},columnrange:{groupPixelWidth:10},candlestick:{groupPixelWidth:10},ohlc:{groupPixelWidth:5}},e=y.defaultDataGroupingUnits=[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,
3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]];b.getDGApproximation=function(){return this.is("arearange")?"range":this.is("ohlc")?"ohlc":this.is("column")?"sum":"average"};b.groupData=q;b.processData=function(){var c=this.chart,a=this.options.dataGrouping,g=!1!==this.allowDG&&a&&l(a.enabled,c.options.isStock),f=this.visible||!c.options.chart.ignoreHiddenSeries,k,d=this.currentDataGrouping,h=!1;this.forceCrop=g;this.groupPixelWidth=null;this.hasProcessed=!0;g&&!this.requireSorting&&
(this.requireSorting=h=!0);g=!1===K.apply(this,arguments)||!g;h&&(this.requireSorting=!1);if(!g){this.destroyGroupedData();g=a.groupAll?this.xData:this.processedXData;var p=a.groupAll?this.yData:this.processedYData,w=c.plotSizeX;c=this.xAxis;var n=c.options.ordinal,q=this.groupPixelWidth=c.getGroupPixelWidth&&c.getGroupPixelWidth();if(q){this.isDirty=k=!0;this.points=null;h=c.getExtremes();var r=h.min;h=h.max;n=n&&c.ordinal&&c.ordinal.getGroupIntervalFactor(r,h,this)||1;q=q*(h-r)/w*n;w=c.getTimeTicks(C.AdditionsClass.prototype.normalizeTimeTickInterval(q,
a.units||e),Math.min(r,g[0]),Math.max(h,g[g.length-1]),c.options.startOfWeek,g,this.closestPointRange);p=b.groupData.apply(this,[g,p,w,a.approximation]);g=p.groupedXData;n=p.groupedYData;var v=0;if(a.smoothed&&g.length){var m=g.length-1;for(g[m]=Math.min(g[m],h);m--&&0<m;)g[m]+=q/2;g[0]=Math.max(g[0],r)}for(m=1;m<w.length;m++)w.info.segmentStarts&&-1!==w.info.segmentStarts.indexOf(m)||(v=Math.max(w[m]-w[m-1],v));r=w.info;r.gapSize=v;this.closestPointRange=w.info.totalRange;this.groupMap=p.groupMap;
if(A(g[0])&&g[0]<c.min&&f){if(!A(c.options.min)&&c.min<=c.dataMin||c.min===c.dataMin)c.min=Math.min(g[0],c.min);c.dataMin=Math.min(g[0],c.dataMin)}a.groupAll&&(a=this.cropData(g,n,c.min,c.max,1),g=a.xData,n=a.yData);this.processedXData=g;this.processedYData=n}else this.groupMap=null;this.hasGroupedData=k;this.currentDataGrouping=r;this.preventGraphAnimation=(d&&d.totalRange)!==(r&&r.totalRange)}};b.destroyGroupedData=function(){this.groupedData&&(this.groupedData.forEach(function(c,a){c&&(this.groupedData[a]=
c.destroy?c.destroy():null)},this),this.groupedData.length=0)};b.generatePoints=function(){p.apply(this);this.destroyGroupedData();this.groupedData=this.hasGroupedData?this.points:null};a(D,"update",function(){if(this.dataGroup)return x(24,!1,this.series.chart),!1});a(v,"headerFormatter",function(c){var a=this.chart,e=a.time,b=c.labelConfig,k=b.series,f=k.tooltipOptions,d=k.options.dataGrouping,l=f.xDateFormat,h=k.xAxis,w=f[(c.isFooter?"footer":"header")+"Format"];if(h&&"datetime"===h.options.type&&
d&&r(b.key)){var p=k.currentDataGrouping;d=d.dateTimeLabelFormats||g.dateTimeLabelFormats;if(p)if(f=d[p.unitName],1===p.count)l=f[0];else{l=f[1];var q=f[2]}else!l&&d&&(l=this.getXDateFormat(b,f,h));l=e.dateFormat(l,b.key);q&&(l+=e.dateFormat(q,b.key+p.totalRange-1));k.chart.styledMode&&(w=this.styledModeFormat(w));c.text=H(w,{point:n(b.point,{key:l}),series:k},a);c.preventDefault()}});a(t,"destroy",b.destroyGroupedData);a(t,"afterSetOptions",function(c){c=c.options;var a=this.type,e=this.chart.options.plotOptions,
b=m.defaultOptions.plotOptions[a].dataGrouping,k=this.useCommonDataGrouping&&g;if(w[a]||k)b||(b=G(g,w[a])),c.dataGrouping=G(k,b,e.series&&e.series.dataGrouping,e[a].dataGrouping,this.userOptions.dataGrouping)});a(d,"afterSetScale",function(){this.series.forEach(function(c){c.hasProcessed=!1})});d.prototype.getGroupPixelWidth=function(){var c=this.series,a=c.length,e,b=0,k=!1,f;for(e=a;e--;)(f=c[e].options.dataGrouping)&&(b=Math.max(b,l(f.groupPixelWidth,g.groupPixelWidth)));for(e=a;e--;)(f=c[e].options.dataGrouping)&&
c[e].hasProcessed&&(a=(c[e].processedXData||c[e].data).length,c[e].groupPixelWidth||a>this.chart.plotSizeX/b||a&&f.forced)&&(k=!0);return k?b:0};d.prototype.setDataGrouping=function(c,a){var e;a=l(a,!0);c||(c={forced:!1,units:null});if(this instanceof d)for(e=this.series.length;e--;)this.series[e].update({dataGrouping:c},!1);else this.chart.options.series.forEach(function(a){a.dataGrouping=c},!1);this.ordinal&&(this.ordinal.slope=void 0);a&&this.chart.redraw()};y.dataGrouping=L;"";return L});I(d,
"Series/OHLC/OHLCPoint.js",[d["Core/Series/Series.js"]],function(d){var C=this&&this.__extends||function(){var d=function(t,m){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(d,m){d.__proto__=m}||function(d,m){for(var q in m)m.hasOwnProperty(q)&&(d[q]=m[q])};return d(t,m)};return function(t,m){function y(){this.constructor=t}d(t,m);t.prototype=null===m?Object.create(m):(y.prototype=m.prototype,new y)}}();return function(d){function t(){var m=null!==d&&d.apply(this,arguments)||this;
m.close=void 0;m.high=void 0;m.low=void 0;m.open=void 0;m.options=void 0;m.plotClose=void 0;m.plotOpen=void 0;m.series=void 0;return m}C(t,d);t.prototype.getClassName=function(){return d.prototype.getClassName.call(this)+(this.open<this.close?" highcharts-point-up":" highcharts-point-down")};return t}(d.seriesTypes.column.prototype.pointClass)});I(d,"Series/OHLC/OHLCSeries.js",[d["Core/Series/Series.js"],d["Series/OHLC/OHLCPoint.js"],d["Core/Utilities.js"]],function(d,C,y){var t=this&&this.__extends||
function(){var d=function(b,a){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])};return d(b,a)};return function(b,a){function q(){this.constructor=b}d(b,a);b.prototype=null===a?Object.create(a):(q.prototype=a.prototype,new q)}}(),m=d.seriesTypes.column,D=y.extend,v=y.merge;y=function(d){function b(){var a=null!==d&&d.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;a.yData=
void 0;return a}t(b,d);b.prototype.drawPoints=function(){var a=this,b=a.chart,d=function(a,b,d){var h=a[0];a=a[1];"number"===typeof h[2]&&(h[2]=Math.max(d+b,h[2]));"number"===typeof a[2]&&(a[2]=Math.min(d-b,a[2]))};a.points.forEach(function(h){var q=h.graphic,m=!q;if("undefined"!==typeof h.plotY){q||(h.graphic=q=b.renderer.path().add(a.group));b.styledMode||q.attr(a.pointAttribs(h,h.selected&&"select"));var n=q.strokeWidth();var v=n%2/2;var r=Math.round(h.plotX)-v;var t=Math.round(h.shapeArgs.width/
2);var l=[["M",r,Math.round(h.yBottom)],["L",r,Math.round(h.plotHigh)]];if(null!==h.open){var f=Math.round(h.plotOpen)+v;l.push(["M",r,f],["L",r-t,f]);d(l,n/2,f)}null!==h.close&&(f=Math.round(h.plotClose)+v,l.push(["M",r,f],["L",r+t,f]),d(l,n/2,f));q[m?"attr":"animate"]({d:l}).addClass(h.getClassName(),!0)}})};b.prototype.init=function(){d.prototype.init.apply(this,arguments);this.options.stacking=void 0};b.prototype.pointAttribs=function(a,b){b=d.prototype.pointAttribs.call(this,a,b);var q=this.options;
delete b.fill;!a.options.color&&q.upColor&&a.open<a.close&&(b.stroke=q.upColor);return b};b.prototype.toYData=function(a){return[a.open,a.high,a.low,a.close]};b.prototype.translate=function(){var a=this,b=a.yAxis,q=!!a.modifyValue,h=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];d.prototype.translate.apply(a);a.points.forEach(function(d){[d.open,d.high,d.low,d.close,d.low].forEach(function(m,n){null!==m&&(q&&(m=a.modifyValue(m)),d[h[n]]=b.toPixels(m,!0))});d.tooltipPos[1]=d.plotHigh+b.pos-
a.chart.plotTop})};b.defaultOptions=v(m.defaultOptions,{lineWidth:1,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Open: {point.open}<br/>High: {point.high}<br/>Low: {point.low}<br/>Close: {point.close}<br/>'},threshold:null,states:{hover:{lineWidth:3}},stickyTracking:!0});return b}(m);D(y.prototype,{animate:null,directTouch:!1,pointArrayMap:["open","high","low","close"],pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},pointValKey:"close"});
y.prototype.pointClass=C;d.registerSeriesType("ohlc",y);"";return y});I(d,"Series/CandlestickSeries.js",[d["Core/Series/Series.js"],d["Series/Column/ColumnSeries.js"],d["Core/Options.js"],d["Core/Color/Palette.js"],d["Core/Utilities.js"]],function(d,C,y,t,m){var D=C.prototype;C=y.defaultOptions;m=m.merge;d.seriesType("candlestick","ohlc",m(C.plotOptions.column,{states:{hover:{lineWidth:2}},tooltip:C.plotOptions.ohlc.tooltip,threshold:null,lineColor:t.neutralColor100,lineWidth:1,upColor:t.backgroundColor,
stickyTracking:!0}),{pointAttribs:function(d,q){var b=D.pointAttribs.call(this,d,q),a=this.options,m=d.open<d.close,v=a.lineColor||this.color;b["stroke-width"]=a.lineWidth;b.fill=d.options.color||(m?a.upColor||this.color:this.color);b.stroke=d.options.lineColor||(m?a.upLineColor||v:v);q&&(d=a.states[q],b.fill=d.color||b.fill,b.stroke=d.lineColor||b.stroke,b["stroke-width"]=d.lineWidth||b["stroke-width"]);return b},drawPoints:function(){var d=this,q=d.chart,b=d.yAxis.reversed;d.points.forEach(function(a){var m=
a.graphic,v=!m;if("undefined"!==typeof a.plotY){m||(a.graphic=m=q.renderer.path().add(d.group));d.chart.styledMode||m.attr(d.pointAttribs(a,a.selected&&"select")).shadow(d.options.shadow);var h=m.strokeWidth()%2/2;var t=Math.round(a.plotX)-h;var x=a.plotOpen;var n=a.plotClose;var y=Math.min(x,n);x=Math.max(x,n);var r=Math.round(a.shapeArgs.width/2);n=b?x!==a.yBottom:Math.round(y)!==Math.round(a.plotHigh);var D=b?Math.round(y)!==Math.round(a.plotHigh):x!==a.yBottom;y=Math.round(y)+h;x=Math.round(x)+
h;h=[];h.push(["M",t-r,x],["L",t-r,y],["L",t+r,y],["L",t+r,x],["Z"],["M",t,y],["L",t,n?Math.round(b?a.yBottom:a.plotHigh):y],["M",t,x],["L",t,D?Math.round(b?a.plotHigh:a.yBottom):x]);m[v?"attr":"animate"]({d:h}).addClass(a.getClassName(),!0)}})}});""});I(d,"Series/Flags/FlagsPoint.js",[d["Core/Series/Series.js"],d["Core/Utilities.js"]],function(d,C){var y=this&&this.__extends||function(){var d=function(m,v){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(d,b){d.__proto__=b}||function(d,
b){for(var a in b)b.hasOwnProperty(a)&&(d[a]=b[a])};return d(m,v)};return function(m,v){function q(){this.constructor=m}d(m,v);m.prototype=null===v?Object.create(v):(q.prototype=v.prototype,new q)}}(),t=C.isNumber;return function(d){function m(){var m=null!==d&&d.apply(this,arguments)||this;m.options=void 0;m.series=void 0;return m}y(m,d);m.prototype.isValid=function(){return t(this.y)||"undefined"===typeof this.y};return m}(d.seriesTypes.column.prototype.pointClass)});I(d,"Mixins/OnSeries.js",[d["Series/Column/ColumnSeries.js"],
d["Series/Line/LineSeries.js"],d["Core/Utilities.js"]],function(d,C,y){var t=d.prototype,m=C.prototype,D=y.defined,v=y.stableSort;return{getPlotBox:function(){return m.getPlotBox.call(this.options.onSeries&&this.chart.get(this.options.onSeries)||this)},translate:function(){t.translate.apply(this);var d=this,b=d.options,a=d.chart,m=d.points,y=m.length-1,h,A=b.onSeries;A=A&&a.get(A);b=b.onKey||"y";var x=A&&A.options.step,n=A&&A.points,C=n&&n.length,r=a.inverted,G=d.xAxis,l=d.yAxis,f=0,L;if(A&&A.visible&&
C){f=(A.pointXOffset||0)+(A.barW||0)/2;a=A.currentDataGrouping;var K=n[C-1].x+(a?a.totalRange:0);v(m,function(a,e){return a.x-e.x});for(b="plot"+b[0].toUpperCase()+b.substr(1);C--&&m[y];){var p=n[C];a=m[y];a.y=p.y;if(p.x<=a.x&&"undefined"!==typeof p[b]){if(a.x<=K&&(a.plotY=p[b],p.x<a.x&&!x&&(L=n[C+1])&&"undefined"!==typeof L[b])){var g=(a.x-p.x)/(L.x-p.x);a.plotY+=g*(L[b]-p[b]);a.y+=g*(L.y-p.y)}y--;C++;if(0>y)break}}}m.forEach(function(a,e){a.plotX+=f;if("undefined"===typeof a.plotY||r)0<=a.plotX&&
a.plotX<=G.len?r?(a.plotY=G.translate(a.x,0,1,0,1),a.plotX=D(a.y)?l.translate(a.y,0,0,0,1):0):a.plotY=(G.opposite?0:d.yAxis.len)+G.offset:a.shapeArgs={};if((h=m[e-1])&&h.plotX===a.plotX){"undefined"===typeof h.stackIndex&&(h.stackIndex=0);var c=h.stackIndex+1}a.stackIndex=c});this.onSeries=A}}});I(d,"Series/Flags/FlagsSymbols.js",[d["Core/Globals.js"],d["Core/Renderer/SVG/SVGRenderer.js"]],function(d,C){function y(d){D[d+"pin"]=function(m,b,a,t,v){var h=v&&v.anchorX;v=v&&v.anchorY;"circle"===d&&t>
a&&(m-=Math.round((t-a)/2),a=t);var q=D[d](m,b,a,t);if(h&&v){var x=h;"circle"===d?x=m+a/2:(m=q[0],a=q[1],"M"===m[0]&&"L"===a[0]&&(x=(m[1]+a[1])/2));q.push(["M",x,b>v?b:b+t],["L",h,v]);q=q.concat(D.circle(h-1,v-1,2,2))}return q}}var t=d.Renderer,m=d.VMLRenderer,D=C.prototype.symbols;D.flag=function(d,m,b,a,t){var q=t&&t.anchorX||d;t=t&&t.anchorY||m;var h=D.circle(q-1,t-1,2,2);h.push(["M",q,t],["L",d,m+a],["L",d,m],["L",d+b,m],["L",d+b,m+a],["L",d,m+a],["Z"]);return h};y("circle");y("square");t===m&&
["circlepin","flag","squarepin"].forEach(function(d){m.prototype.symbols[d]=D[d]});return D});I(d,"Series/Flags/FlagsSeries.js",[d["Core/Series/Series.js"],d["Series/Flags/FlagsPoint.js"],d["Core/Globals.js"],d["Mixins/OnSeries.js"],d["Core/Color/Palette.js"],d["Core/Renderer/SVG/SVGElement.js"],d["Core/Utilities.js"]],function(d,C,y,t,m,D,v){var q=this&&this.__extends||function(){var a=function(b,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,
b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])};return a(b,d)};return function(b,d){function f(){this.constructor=b}a(b,d);b.prototype=null===d?Object.create(d):(f.prototype=d.prototype,new f)}}(),b=d.seriesTypes,a=b.column,E=b.line;b=y.noop;var J=v.addEvent,h=v.defined,A=v.extend,x=v.merge,n=v.objectEach,H=v.wrap,r=y.TrackerMixin;v=function(b){function d(){var a=null!==b&&b.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}q(d,b);d.prototype.animate=function(a){a&&
this.setClip()};d.prototype.drawPoints=function(){var a=this.points,b=this.chart,d=b.renderer,l=b.inverted,g=this.options,w=g.y,e,c=this.yAxis,z={},m=[];for(e=a.length;e--;){var u=a[e];var k=(l?u.plotY:u.plotX)>this.xAxis.len;var q=u.plotX;var r=u.stackIndex;var t=u.options.shape||g.shape;var v=u.plotY;"undefined"!==typeof v&&(v=u.plotY+w-("undefined"!==typeof r&&r*g.stackDistance));u.anchorX=r?void 0:u.plotX;var A=r?void 0:u.plotY;var C="flag"!==t;r=u.graphic;"undefined"!==typeof v&&0<=q&&!k?(r||
(r=u.graphic=d.label("",null,null,t,null,null,g.useHTML),b.styledMode||r.attr(this.pointAttribs(u)).css(x(g.style,u.style)),r.attr({align:C?"center":"left",width:g.width,height:g.height,"text-align":g.textAlign}).addClass("highcharts-point").add(this.markerGroup),u.graphic.div&&(u.graphic.div.point=u),b.styledMode||r.shadow(g.shadow),r.isNew=!0),0<q&&(q-=r.strokeWidth()%2),t={y:v,anchorY:A},g.allowOverlapX&&(t.x=q,t.anchorX=u.anchorX),r.attr({text:u.options.title||g.title||"A"})[r.isNew?"attr":"animate"](t),
g.allowOverlapX||(z[u.plotX]?z[u.plotX].size=Math.max(z[u.plotX].size,r.width):z[u.plotX]={align:C?.5:0,size:r.width,target:q,anchorX:q}),u.tooltipPos=[q,v+c.pos-b.plotTop]):r&&(u.graphic=r.destroy())}g.allowOverlapX||(n(z,function(a){a.plotX=a.anchorX;m.push(a)}),y.distribute(m,l?c.len:this.xAxis.len,100),a.forEach(function(a){var c=a.graphic&&z[a.plotX];c&&(a.graphic[a.graphic.isNew?"attr":"animate"]({x:c.pos+c.align*c.size,anchorX:a.anchorX}),h(c.pos)?a.graphic.isNew=!1:(a.graphic.attr({x:-9999,
anchorX:-9999}),a.graphic.isNew=!0))}));g.useHTML&&H(this.markerGroup,"on",function(a){return D.prototype.on.apply(a.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,1))})};d.prototype.pointAttribs=function(a,b){var d=this.options,f=a&&a.color||this.color,g=d.lineColor,l=a&&a.lineWidth;a=a&&a.fillColor||d.fillColor;b&&(a=d.states[b].fillColor,g=d.states[b].lineColor,l=d.states[b].lineWidth);return{fill:a||f,stroke:g||f,"stroke-width":l||d.lineWidth||0}};d.prototype.setClip=function(){E.prototype.setClip.apply(this,
arguments);!1!==this.options.clip&&this.sharedClipKey&&this.markerGroup.clip(this.chart[this.sharedClipKey])};d.defaultOptions=x(a.defaultOptions,{pointRange:0,allowOverlapX:!1,shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}<br/>"},threshold:null,y:-30,fillColor:m.backgroundColor,lineWidth:1,states:{hover:{lineColor:m.neutralColor100,fillColor:m.highlightColor20}},style:{fontSize:"11px",fontWeight:"bold"}});return d}(a);A(v.prototype,{allowDG:!1,buildKDTree:b,forceCrop:!0,
getPlotBox:t.getPlotBox,init:E.prototype.init,invertGroups:b,noSharedTooltip:!0,pointClass:C,sorted:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],translate:t.translate,drawTracker:function(){var a=this.points;r.drawTrackerPoint.apply(this);a.forEach(function(b){var d=b.graphic;d&&J(d.element,"mouseover",function(){0<b.stackIndex&&!b.raised&&(b._y=d.y,d.attr({y:b._y-8}),b.raised=!0);a.forEach(function(a){a!==b&&a.raised&&a.graphic&&(a.graphic.attr({y:a._y}),a.raised=!1)})})})}});d.registerSeriesType("flags",
v);"";"";return v});I(d,"Extensions/RangeSelector.js",[d["Core/Axis/Axis.js"],d["Core/Chart/Chart.js"],d["Core/Globals.js"],d["Core/Options.js"],d["Core/Color/Palette.js"],d["Core/Renderer/SVG/SVGElement.js"],d["Core/Utilities.js"]],function(d,C,y,t,m,D,v){var q=t.defaultOptions,b=v.addEvent,a=v.createElement,E=v.css,J=v.defined,h=v.destroyObjectProperties,A=v.discardElement,x=v.extend,n=v.fireEvent,H=v.isNumber,r=v.merge,G=v.objectEach,l=v.pick,f=v.pInt,I=v.splat;x(q,{rangeSelector:{verticalAlign:"top",
buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:m.neutralColor60}}});q.lang=r(q.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});var K=function(){function p(a){this.buttons=void 0;this.buttonOptions=p.prototype.defaultButtons;this.options=void 0;this.chart=a;this.init(a)}p.prototype.clickButton=function(a,f){var e=this.chart,c=this.buttonOptions[a],
g=e.xAxis[0],h=e.scroller&&e.scroller.getUnionExtremes()||g||{},u=h.dataMin,k=h.dataMax,p=g&&Math.round(Math.min(g.max,l(k,g.max))),m=c.type;h=c._range;var w,r=c.dataGrouping;if(null!==u&&null!==k){e.fixedRange=h;r&&(this.forcedDataGrouping=!0,d.prototype.setDataGrouping.call(g||{chart:this.chart},r,!1),this.frozenStates=c.preserveDataGrouping);if("month"===m||"year"===m)if(g){m={range:c,max:p,chart:e,dataMin:u,dataMax:k};var n=g.minFromRange.call(m);H(m.newMax)&&(p=m.newMax)}else h=c;else if(h)n=
Math.max(p-h,u),p=Math.min(n+h,k);else if("ytd"===m)if(g)"undefined"===typeof k&&(u=Number.MAX_VALUE,k=Number.MIN_VALUE,e.series.forEach(function(a){a=a.xData;u=Math.min(a[0],u);k=Math.max(a[a.length-1],k)}),f=!1),p=this.getYTDExtremes(k,u,e.time.useUTC),n=w=p.min,p=p.max;else{this.deferredYTDClick=a;return}else"all"===m&&g&&(n=u,p=k);J(n)&&(n+=c._offsetMin);J(p)&&(p+=c._offsetMax);this.setSelected(a);if(g)g.setExtremes(n,p,l(f,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:c});else{var q=
I(e.options.xAxis)[0];var t=q.range;q.range=h;var v=q.min;q.min=w;b(e,"load",function(){q.range=t;q.min=v})}}};p.prototype.setSelected=function(a){this.selected=this.options.selected=a};p.prototype.init=function(a){var d=this,e=a.options.rangeSelector,c=e.buttons||d.defaultButtons.slice(),g=e.selected,f=function(){var a=d.minInput,c=d.maxInput;a&&a.blur&&n(a,"blur");c&&c.blur&&n(c,"blur")};d.chart=a;d.options=e;d.buttons=[];d.buttonOptions=c;this.unMouseDown=b(a.container,"mousedown",f);this.unResize=
b(a,"resize",f);c.forEach(d.computeButtonRange);"undefined"!==typeof g&&c[g]&&this.clickButton(g,!1);b(a,"load",function(){a.xAxis&&a.xAxis[0]&&b(a.xAxis[0],"setExtremes",function(c){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==c.trigger&&"updatedData"!==c.trigger&&d.forcedDataGrouping&&!d.frozenStates&&this.setDataGrouping(!1,!1)})})};p.prototype.updateButtonStates=function(){var a=this,b=this.chart,e=b.xAxis[0],c=Math.round(e.max-e.min),d=!e.hasVisibleSeries,f=b.scroller&&b.scroller.getUnionExtremes()||
e,l=f.dataMin,k=f.dataMax;b=a.getYTDExtremes(k,l,b.time.useUTC);var h=b.min,p=b.max,m=a.selected,n=H(m),r=a.options.allButtonsEnabled,q=a.buttons;a.buttonOptions.forEach(function(b,g){var f=b._range,u=b.type,z=b.count||1,w=q[g],B=0,t=b._offsetMax-b._offsetMin;b=g===m;var v=f>k-l,x=f<e.minRange,y=!1,F=!1;f=f===c;("month"===u||"year"===u)&&c+36E5>=864E5*{month:28,year:365}[u]*z-t&&c-36E5<=864E5*{month:31,year:366}[u]*z+t?f=!0:"ytd"===u?(f=p-h+t===c,y=!b):"all"===u&&(f=e.max-e.min>=k-l,F=!b&&n&&f);u=
!r&&(v||x||F||d);z=b&&f||f&&!n&&!y||b&&a.frozenStates;u?B=3:z&&(n=!0,B=2);w.state!==B&&(w.setState(B),0===B&&m===g&&a.setSelected(null))})};p.prototype.computeButtonRange=function(a){var b=a.type,e=a.count||1,c={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(c[b])a._range=c[b]*e;else if("month"===b||"year"===b)a._range=864E5*{month:30,year:365}[b]*e;a._offsetMin=l(a.offsetMin,0);a._offsetMax=l(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin};p.prototype.setInputValue=function(a,
b){var e=this.chart.options.rangeSelector,c=this.chart.time,d="min"===a?this.minInput:this.maxInput;if(d){var g=d.getAttribute("data-hc-time");g=J(g)?Number(g):void 0;J(b)&&(g&&d.setAttribute("data-hc-time-previous",g),d.setAttribute("data-hc-time",b),g=b);d.value=c.dateFormat(e.inputEditDateFormat||"%Y-%m-%d",g);this[a+"DateBox"].attr({text:c.dateFormat(e.inputDateFormat||"%b %e, %Y",g)})}};p.prototype.showInput=function(a){var b=this.inputGroup,e=this[a+"DateBox"];E(this[a+"Input"],{left:b.translateX+
e.x+"px",top:b.translateY+"px",width:e.width-2+"px",height:e.height-2+"px",border:"2px solid silver"})};p.prototype.hideInput=function(a){E(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)};p.prototype.defaultInputDateParser=function(a,b,e){var c=a.split("/").join("-").split(" ").join("T");-1===c.indexOf("T")&&(c+="T00:00");if(b)c+="Z";else{var d;if(d=y.isSafari)d=c,d=!(6<d.length&&(d.lastIndexOf("-")===d.length-6||d.lastIndexOf("+")===d.length-6));d&&(d=(new Date(c)).getTimezoneOffset()/
60,c+=0>=d?"+"+y.pad(-d)+":00":"-"+y.pad(d)+":00")}c=Date.parse(c);H(c)||(a=a.split("-"),c=Date.UTC(f(a[0]),f(a[1])-1,f(a[2])));e&&b&&(c+=6E4*e.getTimezoneOffset(c));return c};p.prototype.drawInput=function(b){function d(){var a=e.xAxis[0];var b=e.scroller&&e.scroller.xAxis?e.scroller.xAxis:a;var d=b.dataMin,g=b.dataMax,f=l.maxInput,k=l.minInput;b=(p.inputDateParser||c)(t.value,e.time.useUTC,e.time);b!==Number(t.getAttribute("data-hc-time-previous"))&&H(b)&&(t.setAttribute("data-hc-time-previous",
b),n&&f&&H(d)?b>Number(f.getAttribute("data-hc-time"))?b=void 0:b<d&&(b=d):k&&H(g)&&(b<Number(k.getAttribute("data-hc-time"))?b=void 0:b>g&&(b=g)),"undefined"!==typeof b&&a.setExtremes(n?b:a.min,n?a.max:b,void 0,void 0,{trigger:"rangeSelectorInput"}))}var e=this.chart,c=this.defaultInputDateParser,g=this.div,f=this.inputGroup,l=this,k=e.renderer.style||{},h=e.renderer,p=e.options.rangeSelector,n="min"===b,t,v;this[b+"Label"]=v=h.label(q.lang[n?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(f);
f.offset+=v.width+5;this[b+"DateBox"]=h=h.label("",f.offset).addClass("highcharts-range-input").attr({padding:2,width:p.inputBoxWidth||90,height:p.inputBoxHeight||17,"text-align":"center"}).on("click",function(){l.showInput(b);l[b+"Input"].focus()});e.styledMode||h.attr({stroke:p.inputBoxBorderColor||m.neutralColor20,"stroke-width":1});h.add(f);f.offset+=h.width+(n?10:0);this[b+"Input"]=t=a("input",{name:b,className:"highcharts-range-selector",type:"text"},{top:e.plotTop+"px"},g);e.styledMode||(v.css(r(k,
p.labelStyle)),h.css(r({color:m.neutralColor80},k,p.inputStyle)),E(t,x({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:k.fontSize,fontFamily:k.fontFamily,top:"-9999em"},p.inputStyle)));t.onfocus=function(){l.showInput(b)};t.onblur=function(){t===y.doc.activeElement&&d();l.hideInput(b);t.blur()};t.onchange=d;t.onkeypress=function(a){13===a.keyCode&&d()}};p.prototype.getPosition=function(){var a=this.chart,b=a.options.rangeSelector;a="top"===b.verticalAlign?
a.plotTop-a.axisOffset[0]:0;return{buttonTop:a+b.buttonPosition.y,inputTop:a+b.inputPosition.y-10}};p.prototype.getYTDExtremes=function(a,b,e){var c=this.chart.time,d=new c.Date(a),g=c.get("FullYear",d);e=e?c.Date.UTC(g,0,1):+new c.Date(g,0,1);b=Math.max(b||0,e);d=d.getTime();return{max:Math.min(a||d,d),min:b}};p.prototype.render=function(b,d){var e=this,c=e.chart,g=c.renderer,f=c.container,h=c.options,k=h.exporting&&!1!==h.exporting.enabled&&h.navigation&&h.navigation.buttonOptions,p=q.lang,m=e.div,
n=h.rangeSelector,r=l(h.chart.style&&h.chart.style.zIndex,0)+1,t=n.floating,w=e.buttons;m=e.inputGroup;var v=n.buttonTheme,x=n.buttonPosition,y=n.inputPosition;h=n.inputEnabled;var A=v&&v.states,C=c.plotLeft,D=e.buttonGroup,E,G=e.options.verticalAlign,H=c.legend,J=H&&H.options,I=x.y,L=y.y,K=c.hasLoaded,Q=K?"animate":"attr",P=0,O=0;if(!1!==n.enabled){e.rendered||(e.group=E=g.g("range-selector-group").attr({zIndex:7}).add(),e.buttonGroup=D=g.g("range-selector-buttons").add(E),e.zoomText=g.text(p.rangeSelectorZoom,
0,15).add(D),c.styledMode||(e.zoomText.css(n.labelStyle),v["stroke-width"]=l(v["stroke-width"],0)),e.buttonOptions.forEach(function(a,c){w[c]=g.button(a.text,0,0,function(b){var d=a.events&&a.events.click,g;d&&(g=d.call(a,b));!1!==g&&e.clickButton(c);e.isActive=!0},v,A&&A.hover,A&&A.select,A&&A.disabled).attr({"text-align":"center"}).add(D);a.title&&w[c].attr("title",a.title)}),!1!==h&&(e.div=m=a("div",null,{position:"relative",height:0,zIndex:r}),f.parentNode.insertBefore(m,f),e.inputGroup=m=g.g("input-group").add(E),
m.offset=0,e.drawInput("min"),e.drawInput("max")));e.zoomText[Q]({x:l(C+x.x,C)});var R=l(C+x.x,C)+e.zoomText.getBBox().width+5;e.buttonOptions.forEach(function(a,c){w[c][Q]({x:R});R+=w[c].width+l(n.buttonSpacing,5)});C=c.plotLeft-c.spacing[3];e.updateButtonStates();k&&this.titleCollision(c)&&"top"===G&&"right"===x.align&&x.y+D.getBBox().height-12<(k.y||0)+k.height&&(P=-40);f=x.x-c.spacing[3];"right"===x.align?f+=P-C:"center"===x.align&&(f-=C/2);D.align({y:x.y,width:D.getBBox().width,align:x.align,
x:f},!0,c.spacingBox);e.group.placed=K;e.buttonGroup.placed=K;!1!==h&&(P=k&&this.titleCollision(c)&&"top"===G&&"right"===y.align&&y.y-m.getBBox().height-12<(k.y||0)+k.height+c.spacing[0]?-40:0,"left"===y.align?f=C:"right"===y.align&&(f=-Math.max(c.axisOffset[1],-P)),m.align({y:y.y,width:m.getBBox().width,align:y.align,x:y.x+f-2},!0,c.spacingBox),k=m.alignAttr.translateX+m.alignOptions.x-P+m.getBBox().x+2,f=m.alignOptions.width,p=D.alignAttr.translateX+D.getBBox().x,C=D.getBBox().width+20,(y.align===
x.align||p+C>k&&k+f>p&&I<L+m.getBBox().height)&&m.attr({translateX:m.alignAttr.translateX+(c.axisOffset[1]>=-P?0:-P),translateY:m.alignAttr.translateY+D.getBBox().height+10}),e.setInputValue("min",b),e.setInputValue("max",d),e.inputGroup.placed=K);e.group.align({verticalAlign:G},!0,c.spacingBox);b=e.group.getBBox().height+20;d=e.group.alignAttr.translateY;"bottom"===G&&(H=J&&"bottom"===J.verticalAlign&&J.enabled&&!J.floating?H.legendHeight+l(J.margin,10):0,b=b+H-20,O=d-b-(t?0:n.y)-(c.titleOffset?
c.titleOffset[2]:0)-10);if("top"===G)t&&(O=0),c.titleOffset&&c.titleOffset[0]&&(O=c.titleOffset[0]),O+=c.margin[0]-c.spacing[0]||0;else if("middle"===G)if(L===I)O=0>L?d+void 0:d;else if(L||I)O=0>L||0>I?O-Math.min(L,I):d-b+NaN;e.group.translate(n.x,n.y+Math.floor(O));c=e.minInput;t=e.maxInput;!1!==h&&c&&t&&(c.style.marginTop=e.group.translateY+"px",t.style.marginTop=e.group.translateY+"px");e.rendered=!0}};p.prototype.getHeight=function(){var a=this.options,b=this.group,e=a.y,c=a.buttonPosition.y,
d=a.inputPosition.y;if(a.height)return a.height;a=b?b.getBBox(!0).height+13+e:0;b=Math.min(d,c);if(0>d&&0>c||0<d&&0<c)a+=Math.abs(b);return a};p.prototype.titleCollision=function(a){return!(a.options.title.text||a.options.subtitle.text)};p.prototype.update=function(a){var b=this.chart;r(!0,b.options.rangeSelector,a);this.destroy();this.init(b);b.rangeSelector.render()};p.prototype.destroy=function(){var a=this,b=a.minInput,e=a.maxInput;a.unMouseDown();a.unResize();h(a.buttons);b&&(b.onfocus=b.onblur=
b.onchange=null);e&&(e.onfocus=e.onblur=e.onchange=null);G(a,function(c,b){c&&"chart"!==b&&(c instanceof D?c.destroy():c instanceof window.HTMLElement&&A(c));c!==p.prototype[b]&&(a[b]=null)},this)};return p}();K.prototype.defaultButtons=[{type:"month",count:1,text:"1m",title:"View 1 month"},{type:"month",count:3,text:"3m",title:"View 3 months"},{type:"month",count:6,text:"6m",title:"View 6 months"},{type:"ytd",text:"YTD",title:"View year to date"},{type:"year",count:1,text:"1y",title:"View 1 year"},
{type:"all",text:"All",title:"View all"}];d.prototype.minFromRange=function(){var a=this.range,b=a.type,d=this.max,e=this.chart.time,c=function(a,c){var d="year"===b?"FullYear":"Month",f=new e.Date(a),g=e.get(d,f);e.set(d,f,g+c);g===e.get(d,f)&&e.set("Date",f,0);return f.getTime()-a};if(H(a)){var f=d-a;var h=a}else f=d+c(d,-a.count),this.chart&&(this.chart.fixedRange=d-f);var m=l(this.dataMin,Number.MIN_VALUE);H(f)||(f=m);f<=m&&(f=m,"undefined"===typeof h&&(h=c(f,a.count)),this.newMax=Math.min(f+
h,this.dataMax));H(d)||(f=void 0);return f};y.RangeSelector||(b(C,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new K(this))}),b(C,"beforeRender",function(){var a=this.axes,b=this.rangeSelector;b&&(H(b.deferredYTDClick)&&(b.clickButton(b.deferredYTDClick),delete b.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),b.render(),a=b.options.verticalAlign,b.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==
a&&(this.extraTopMargin=!0)))}),b(C,"update",function(a){var b=a.options.rangeSelector;a=this.rangeSelector;var d=this.extraBottomMargin,e=this.extraTopMargin;b&&b.enabled&&!J(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new K(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),b=b&&b.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)),this.extraBottomMargin!==d||this.extraTopMargin!==
e)&&(this.isDirtyBox=!0)}),b(C,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),b(C,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),C.prototype.callbacks.push(function(a){function d(){f=a.xAxis[0].getExtremes();c=a.legend;l=null===e||void 0===e?void 0:
e.options.verticalAlign;H(f.min)&&e.render(f.min,f.max);e&&c.display&&"top"===l&&l===c.options.verticalAlign&&(h=r(a.spacingBox),h.y="vertical"===c.options.layout?a.plotTop:h.y+e.getHeight(),c.group.placed=!1,c.align(h))}var f,e=a.rangeSelector,c,h,l;if(e){var m=b(a.xAxis[0],"afterSetExtremes",function(a){e.render(a.min,a.max)});var k=b(a,"redraw",d);d()}b(a,"destroy",function(){e&&(k(),m())})}),y.RangeSelector=K);return y.RangeSelector});I(d,"Core/Chart/StockChart.js",[d["Core/Axis/Axis.js"],d["Core/Chart/Chart.js"],
d["Core/Globals.js"],d["Series/Line/LineSeries.js"],d["Core/Color/Palette.js"],d["Core/Series/Point.js"],d["Core/Renderer/SVG/SVGRenderer.js"],d["Core/Utilities.js"]],function(d,C,y,t,m,D,v,q){function b(a,c,b){var e=K(a)||a.nodeName,d=arguments[e?1:0],k=d,h=d.series,l=f(),m,n=g(d.navigator&&d.navigator.enabled,l.navigator.enabled,!0);d.xAxis=w(d.xAxis||{}).map(function(a,c){return p({minPadding:0,maxPadding:0,overscroll:0,ordinal:!0,title:{text:null},labels:{overflow:"justify"},showLastLabel:!0},
l.xAxis,l.xAxis&&l.xAxis[c],a,{type:"datetime",categories:null},n?{startOnTick:!1,endOnTick:!1}:null)});d.yAxis=w(d.yAxis||{}).map(function(a,c){m=g(a.opposite,!0);return p({labels:{y:-2},opposite:m,showLastLabel:!(!a.categories&&"category"!==a.type),title:{text:null}},l.yAxis,l.yAxis&&l.yAxis[c],a)});d.series=null;d=p({chart:{panning:{enabled:!0,type:"x"},pinchType:"x"},navigator:{enabled:n},scrollbar:{enabled:g(l.scrollbar.enabled,!0)},rangeSelector:{enabled:g(l.rangeSelector.enabled,!0)},title:{text:null},
tooltip:{split:g(l.tooltip.split,!0),crosshairs:!0},legend:{enabled:!1}},d,{isStock:!0});d.series=k.series=h;return e?new C(a,d,b):new C(d,c)}var a=t.prototype,E=a.init,J=a.processData,h=D.prototype.tooltipFormatter;a=q.addEvent;var A=q.arrayMax,x=q.arrayMin,n=q.clamp,H=q.defined,r=q.extend,G=q.find,l=q.format,f=q.getOptions,I=q.isNumber,K=q.isString,p=q.merge,g=q.pick,w=q.splat;a(t,"setOptions",function(a){var c;this.chart.options.isStock&&(this.is("column")||this.is("columnrange")?c={borderWidth:0,
shadow:!1}:this.is("scatter")||this.is("sma")||(c={marker:{enabled:!1,radius:2}}),c&&(a.plotOptions[this.type]=p(a.plotOptions[this.type],c)))});a(d,"autoLabelAlign",function(a){var c=this.chart,b=this.options;c=c._labelPanes=c._labelPanes||{};var d=this.options.labels;this.chart.options.isStock&&"yAxis"===this.coll&&(b=b.top+","+b.height,!c[b]&&d.enabled&&(15===d.x&&(d.x=0),"undefined"===typeof d.align&&(d.align="right"),c[b]=this,a.align="right",a.preventDefault()))});a(d,"destroy",function(){var a=
this.chart,b=this.options&&this.options.top+","+this.options.height;b&&a._labelPanes&&a._labelPanes[b]===this&&delete a._labelPanes[b]});a(d,"getPlotLinePath",function(a){function b(a){var b="xAxis"===a?"yAxis":"xAxis";a=d.options[b];return I(a)?[f[b][a]]:K(a)?[f.get(a)]:e.map(function(a){return a[b]})}var d=this,e=this.isLinked&&!this.series?this.linkedParent.series:this.series,f=d.chart,k=f.renderer,h=d.left,l=d.top,m,p,r,q,t=[],v=[],w=a.translatedValue,x=a.value,y=a.force;if(f.options.isStock&&
!1!==a.acrossPanes&&"xAxis"===d.coll||"yAxis"===d.coll){a.preventDefault();v=b(d.coll);var A=d.isXAxis?f.yAxis:f.xAxis;A.forEach(function(a){if(H(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var b=a.isXAxis?"yAxis":"xAxis";b=H(a.options[b])?f[b][a.options[b]]:f[b][0];d===b&&v.push(a)}});var C=v.length?[]:[d.isXAxis?f.yAxis[0]:f.xAxis[0]];v.forEach(function(a){-1!==C.indexOf(a)||G(C,function(b){return b.pos===a.pos&&b.len===a.len})||C.push(a)});var D=g(w,d.translate(x,null,null,a.old));
I(D)&&(d.horiz?C.forEach(function(a){var b;p=a.pos;q=p+a.len;m=r=Math.round(D+d.transB);"pass"!==y&&(m<h||m>h+d.width)&&(y?m=r=n(m,h,h+d.width):b=!0);b||t.push(["M",m,p],["L",r,q])}):C.forEach(function(a){var b;m=a.pos;r=m+a.len;p=q=Math.round(l+d.height-D);"pass"!==y&&(p<l||p>l+d.height)&&(y?p=q=n(p,l,l+d.height):b=!0);b||t.push(["M",m,p],["L",r,q])}));a.path=0<t.length?k.crispPolyLine(t,a.lineWidth||1):null}});v.prototype.crispPolyLine=function(a,b){for(var c=0;c<a.length;c+=2){var d=a[c],e=a[c+
1];d[1]===e[1]&&(d[1]=e[1]=Math.round(d[1])-b%2/2);d[2]===e[2]&&(d[2]=e[2]=Math.round(d[2])+b%2/2)}return a};a(d,"afterHideCrosshair",function(){this.crossLabel&&(this.crossLabel=this.crossLabel.hide())});a(d,"afterDrawCrosshair",function(a){var b,d;if(H(this.crosshair.label)&&this.crosshair.label.enabled&&this.cross){var e=this.chart,f=this.logarithmic,k=this.options.crosshair.label,h=this.horiz,n=this.opposite,p=this.left,q=this.top,t=this.crossLabel,v=k.format,w="",x="inside"===this.options.tickPosition,
y=!1!==this.crosshair.snap,A=0,C=a.e||this.cross&&this.cross.e,D=a.point;a=this.min;var E=this.max;f&&(a=f.lin2log(a),E=f.lin2log(E));f=h?"center":n?"right"===this.labelAlign?"right":"left":"left"===this.labelAlign?"left":"center";t||(t=this.crossLabel=e.renderer.label(null,null,null,k.shape||"callout").addClass("highcharts-crosshair-label"+(this.series[0]&&" highcharts-color-"+this.series[0].colorIndex)).attr({align:k.align||f,padding:g(k.padding,8),r:g(k.borderRadius,3),zIndex:2}).add(this.labelGroup),
e.styledMode||t.attr({fill:k.backgroundColor||this.series[0]&&this.series[0].color||m.neutralColor60,stroke:k.borderColor||"","stroke-width":k.borderWidth||0}).css(r({color:m.backgroundColor,fontWeight:"normal",fontSize:"11px",textAlign:"center"},k.style)));h?(f=y?D.plotX+p:C.chartX,q+=n?0:this.height):(f=n?this.width+p:0,q=y?D.plotY+q:C.chartY);v||k.formatter||(this.dateTime&&(w="%b %d, %Y"),v="{value"+(w?":"+w:"")+"}");w=y?D[this.isXAxis?"x":"y"]:this.toValue(h?C.chartX:C.chartY);t.attr({text:v?
l(v,{value:w},e):k.formatter.call(this,w),x:f,y:q,visibility:w<a||w>E?"hidden":"visible"});k=t.getBBox();if(I(t.y))if(h){if(x&&!n||!x&&n)q=t.y-k.height}else q=t.y-k.height/2;h?(b=p-k.x,d=p+this.width-k.x):(b="left"===this.labelAlign?p:0,d="right"===this.labelAlign?p+this.width:e.chartWidth);t.translateX<b&&(A=b-t.translateX);t.translateX+k.width>=d&&(A=-(t.translateX+k.width-d));t.attr({x:f+A,y:q,anchorX:h?f:this.opposite?0:e.chartWidth,anchorY:h?this.opposite?e.chartHeight:0:q+k.height/2})}});t.prototype.init=
function(){E.apply(this,arguments);this.setCompare(this.options.compare)};t.prototype.setCompare=function(a){this.modifyValue="value"===a||"percent"===a?function(b,d){var c=this.compareValue;return"undefined"!==typeof b&&"undefined"!==typeof c?(b="value"===a?b-c:b/c*100-(100===this.options.compareBase?0:100),d&&(d.change=b),b):0}:null;this.userOptions.compare=a;this.chart.hasRendered&&(this.isDirty=!0)};t.prototype.processData=function(a){var b,d=-1,e=!0===this.options.compareStart?0:1;J.apply(this,
arguments);if(this.xAxis&&this.processedYData){var f=this.processedXData;var g=this.processedYData;var h=g.length;this.pointArrayMap&&(d=this.pointArrayMap.indexOf(this.options.pointValKey||this.pointValKey||"y"));for(b=0;b<h-e;b++){var l=g[b]&&-1<d?g[b][d]:g[b];if(I(l)&&f[b+e]>=this.xAxis.min&&0!==l){this.compareValue=l;break}}}};a(t,"afterGetExtremes",function(a){a=a.dataExtremes;if(this.modifyValue&&a){var b=[this.modifyValue(a.dataMin),this.modifyValue(a.dataMax)];a.dataMin=x(b);a.dataMax=A(b)}});
d.prototype.setCompare=function(a,b){this.isXAxis||(this.series.forEach(function(b){b.setCompare(a)}),g(b,!0)&&this.chart.redraw())};D.prototype.tooltipFormatter=function(a){var b=this.series.chart.numberFormatter;a=a.replace("{point.change}",(0<this.change?"+":"")+b(this.change,g(this.series.tooltipOptions.changeDecimals,2)));return h.apply(this,[a])};a(t,"render",function(){var a=this.chart;if(!(a.is3d&&a.is3d()||a.polar)&&this.xAxis&&!this.xAxis.isRadial){var b=this.yAxis.len;if(this.xAxis.axisLine){var d=
a.plotTop+a.plotHeight-this.yAxis.pos-this.yAxis.len,f=Math.floor(this.xAxis.axisLine.strokeWidth()/2);0<=d&&(b-=Math.max(f-d,0))}this.clipBox||a.hasRendered?a[this.sharedClipKey]&&(a[this.sharedClipKey].animate({width:this.xAxis.len,height:b}),a[this.sharedClipKey+"m"]&&a[this.sharedClipKey+"m"].animate({width:this.xAxis.len})):(this.clipBox=p(a.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=b)}});a(C,"update",function(a){a=a.options;"scrollbar"in a&&this.navigator&&(p(!0,this.options.scrollbar,
a.scrollbar),this.navigator.update({},!1),delete a.scrollbar)});y.StockChart=y.stockChart=b;"";return b});I(d,"masters/modules/stock.src.js",[],function(){})});
//# sourceMappingURL=stock.js.map