/*
 Highcharts JS v8.2.2 (2020-11-23)

 (c) 2016-2019 Highsoft AS
 Authors: Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/sunburst",["highcharts"],function(v){a(v);a.Highcharts=v;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function v(a,c,r,M){a.hasOwnProperty(c)||(a[c]=M.apply(null,r))}a=a?a._modules:{};v(a,"Mixins/DrawPoint.js",[],function(){var a=function(a){return"function"===typeof a},c=function(r){var c,y=this,k=y.graphic,q=r.animatableAttribs,
B=r.onComplete,z=r.css,h=r.renderer,l=null===(c=y.series)||void 0===c?void 0:c.options.animation;if(y.shouldDraw())k||(y.graphic=k=h[r.shapeType](r.shapeArgs).add(r.group)),k.css(z).attr(r.attribs).animate(q,r.isNew?!1:l,B);else if(k){var E=function(){y.graphic=k=k.destroy();a(B)&&B()};Object.keys(q).length?k.animate(q,void 0,function(){E()}):E()}};return{draw:c,drawPoint:function(a){(a.attribs=a.attribs||{})["class"]=this.getClassName();c.call(this,a)},isFn:a}});v(a,"Mixins/TreeSeries.js",[a["Core/Color/Color.js"],
a["Core/Utilities.js"]],function(a,c){var r=c.extend,v=c.isArray,y=c.isNumber,k=c.isObject,q=c.merge,B=c.pick;return{getColor:function(z,h){var l=h.index,c=h.mapOptionsToLevel,k=h.parentColor,r=h.parentColorIndex,q=h.series,G=h.colors,y=h.siblings,u=q.points,D=q.chart.options.chart,C;if(z){u=u[z.i];z=c[z.level]||{};if(c=u&&z.colorByPoint){var v=u.index%(G?G.length:D.colorCount);var H=G&&G[v]}if(!q.chart.styledMode){G=u&&u.options.color;D=z&&z.color;if(C=k)C=(C=z&&z.colorVariation)&&"brightness"===
C.key?a.parse(k).brighten(l/y*C.to).get():k;C=B(G,D,H,C,q.color)}var K=B(u&&u.options.colorIndex,z&&z.colorIndex,v,r,h.colorIndex)}return{color:C,colorIndex:K}},getLevelOptions:function(a){var h=null;if(k(a)){h={};var l=y(a.from)?a.from:1;var c=a.levels;var z={};var B=k(a.defaults)?a.defaults:{};v(c)&&(z=c.reduce(function(a,h){if(k(h)&&y(h.level)){var c=q({},h);var u="boolean"===typeof c.levelIsConstant?c.levelIsConstant:B.levelIsConstant;delete c.levelIsConstant;delete c.level;h=h.level+(u?0:l-1);
k(a[h])?r(a[h],c):a[h]=c}return a},{}));c=y(a.to)?a.to:1;for(a=0;a<=c;a++)h[a]=q({},B,k(z[a])?z[a]:{})}return h},setTreeValues:function E(a,c){var h=c.before,k=c.idRoot,q=c.mapIdToNode[k],l=c.points[a.i],y=l&&l.options||{},u=0,D=[];r(a,{levelDynamic:a.level-(("boolean"===typeof c.levelIsConstant?c.levelIsConstant:1)?0:q.level),name:B(l&&l.name,""),visible:k===a.id||("boolean"===typeof c.visible?c.visible:!1)});"function"===typeof h&&(a=h(a,c));a.children.forEach(function(h,k){var l=r({},c);r(l,{index:k,
siblings:a.children.length,visible:a.visible});h=E(h,l);D.push(h);h.visible&&(u+=h.val)});a.visible=0<u||a.visible;h=B(y.value,u);r(a,{children:D,childrenTotal:u,isLeaf:a.visible&&!u,val:h});return a},updateRootId:function(a){if(k(a)){var c=k(a.options)?a.options:{};c=B(a.rootNode,c.rootId,"");k(a.userOptions)&&(a.userOptions.rootId=c);a.rootNode=c}return c}}});v(a,"Mixins/ColorMapSeries.js",[a["Core/Globals.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,c,r){var v=r.defined;return{colorMapPointMixin:{dataLabelOnNull:!0,
isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value},setState:function(a){c.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})}},colorMapSeriesMixin:{pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:a.noop,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:a.seriesTypes.column.prototype.pointAttribs,colorAttribs:function(a){var c=
{};v(a.color)&&(c[this.colorProp||"fill"]=a.color);return c}}}});v(a,"Series/TreemapSeries.js",[a["Core/Series/Series.js"],a["Core/Color/Color.js"],a["Mixins/ColorMapSeries.js"],a["Mixins/DrawPoint.js"],a["Core/Globals.js"],a["Mixins/LegendSymbol.js"],a["Series/Line/LineSeries.js"],a["Core/Color/Palette.js"],a["Core/Series/Point.js"],a["Mixins/TreeSeries.js"],a["Core/Utilities.js"]],function(a,c,r,v,y,k,q,B,z,h,l){var E=a.seriesTypes,K=c.parse,Q=r.colorMapSeriesMixin;c=y.noop;var R=h.getColor,G=h.getLevelOptions,
S=h.updateRootId,u=l.addEvent,D=l.correctFloat,C=l.defined,L=l.error,H=l.extend,M=l.fireEvent,N=l.isArray,O=l.isNumber,T=l.isObject,P=l.isString,e=l.merge,f=l.objectEach,m=l.pick,x=l.stableSort,F=function(b,d,g){g=g||this;f(b,function(a,p){d.call(g,a,p,b)})},t=function(b,d,g){g=g||this;b=d.call(g,b);!1!==b&&t(b,d,g)},n=!1;a.seriesType("treemap","scatter",{allowTraversingTree:!1,animationLimit:250,showInLegend:!1,marker:void 0,colorByPoint:!1,dataLabels:{defer:!1,enabled:!0,formatter:function(){var b=
this&&this.point?this.point:{};return P(b.name)?b.name:""},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:"",pointFormat:"<b>{point.name}</b>: {point.value}<br/>"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,drillUpButton:{position:{align:"right",x:-10,y:10}},traverseUpButton:{position:{align:"right",x:-10,y:10}},borderColor:B.neutralColor10,borderWidth:1,colorKey:"colorValue",opacity:.15,states:{hover:{borderColor:B.neutralColor40,
brightness:E.heatmap?0:.1,halo:!1,opacity:.75,shadow:!1}}},{pointArrayMap:["value"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:c,parallelArrays:["x","y","value","colorValue"],colorKey:"colorValue",trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(b,d){b=N(b)?b:[];var g=N(d)?d:[];d=b.reduce(function(b,d,g){d=m(d.parent,"");"undefined"===typeof b[d]&&(b[d]=[]);b[d].push(g);return b},{"":[]});F(d,function(b,d,a){""!==d&&-1===g.indexOf(d)&&(b.forEach(function(b){a[""].push(b)}),
delete a[d])});return d},getTree:function(){var b=this.data.map(function(b){return b.id});b=this.getListOfParents(this.data,b);this.nodeMap={};return this.buildNode("",-1,0,b)},hasData:function(){return!!this.processedXData.length},init:function(b,d){Q&&(this.colorAttribs=Q.colorAttribs);var g=u(this,"setOptions",function(b){b=b.userOptions;C(b.allowDrillToNode)&&!C(b.allowTraversingTree)&&(b.allowTraversingTree=b.allowDrillToNode,delete b.allowDrillToNode);C(b.drillUpButton)&&!C(b.traverseUpButton)&&
(b.traverseUpButton=b.drillUpButton,delete b.drillUpButton)});q.prototype.init.call(this,b,d);delete this.opacity;this.eventsToUnbind.push(g);this.options.allowTraversingTree&&this.eventsToUnbind.push(u(this,"click",this.onClickDrillToNode))},buildNode:function(b,d,g,a,e){var p=this,w=[],c=p.points[d],m=0,f;(a[b]||[]).forEach(function(d){f=p.buildNode(p.points[d].id,d,g+1,a,b);m=Math.max(f.height+1,m);w.push(f)});d={id:b,i:d,children:w,height:m,level:g,parent:e,visible:!1};p.nodeMap[d.id]=d;c&&(c.node=
d);return d},setTreeValues:function(b){var d=this,g=d.options,a=d.nodeMap[d.rootNode];g="boolean"===typeof g.levelIsConstant?g.levelIsConstant:!0;var p=0,e=[],c=d.points[b.i];b.children.forEach(function(b){b=d.setTreeValues(b);e.push(b);b.ignore||(p+=b.val)});x(e,function(b,d){return(b.sortIndex||0)-(d.sortIndex||0)});var f=m(c&&c.options.value,p);c&&(c.value=f);H(b,{children:e,childrenTotal:p,ignore:!(m(c&&c.visible,!0)&&0<f),isLeaf:b.visible&&!p,levelDynamic:b.level-(g?0:a.level),name:m(c&&c.name,
""),sortIndex:m(c&&c.sortIndex,-f),val:f});return b},calculateChildrenAreas:function(b,d){var g=this,a=g.options,p=g.mapOptionsToLevel[b.level+1],c=m(g[p&&p.layoutAlgorithm]&&p.layoutAlgorithm,a.layoutAlgorithm),f=a.alternateStartingDirection,U=[];b=b.children.filter(function(b){return!b.ignore});p&&p.layoutStartingDirection&&(d.direction="vertical"===p.layoutStartingDirection?0:1);U=g[c](d,b);b.forEach(function(b,a){a=U[a];b.values=e(a,{val:b.childrenTotal,direction:f?1-d.direction:d.direction});
b.pointValues=e(a,{x:a.x/g.axisRatio,y:100-a.y-a.height,width:a.width/g.axisRatio});b.children.length&&g.calculateChildrenAreas(b,b.values)})},setPointValues:function(){var b=this,d=b.xAxis,g=b.yAxis,a=b.chart.styledMode;b.points.forEach(function(e){var p=e.node,c=p.pointValues;p=p.visible;if(c&&p){p=c.height;var f=c.width,w=c.x,m=c.y,t=a?0:(b.pointAttribs(e)["stroke-width"]||0)%2/2;c=Math.round(d.toPixels(w,!0))-t;f=Math.round(d.toPixels(w+f,!0))-t;w=Math.round(g.toPixels(m,!0))-t;p=Math.round(g.toPixels(m+
p,!0))-t;e.shapeArgs={x:Math.min(c,f),y:Math.min(w,p),width:Math.abs(f-c),height:Math.abs(p-w)};e.plotX=e.shapeArgs.x+e.shapeArgs.width/2;e.plotY=e.shapeArgs.y+e.shapeArgs.height/2}else delete e.plotX,delete e.plotY})},setColorRecursive:function(b,d,a,e,p){var g=this,c=g&&g.chart;c=c&&c.options&&c.options.colors;if(b){var f=R(b,{colors:c,index:e,mapOptionsToLevel:g.mapOptionsToLevel,parentColor:d,parentColorIndex:a,series:g,siblings:p});if(d=g.points[b.i])d.color=f.color,d.colorIndex=f.colorIndex;
(b.children||[]).forEach(function(d,a){g.setColorRecursive(d,f.color,f.colorIndex,a,b.children.length)})}},algorithmGroup:function(b,d,g,a){this.height=b;this.width=d;this.plot=a;this.startDirection=this.direction=g;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(b,d){return Math.max(b/d,d/b)}};this.addElement=function(b){this.lP.total=this.elArr[this.elArr.length-1];this.total+=b;0===this.direction?(this.lW=this.nW,this.lP.lH=
this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(b)};this.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=0}},algorithmCalcPoints:function(b,
d,a,e){var g,c,f,w,m=a.lW,t=a.lH,n=a.plot,h=0,J=a.elArr.length-1;if(d)m=a.nW,t=a.nH;else var x=a.elArr[a.elArr.length-1];a.elArr.forEach(function(b){if(d||h<J)0===a.direction?(g=n.x,c=n.y,f=m,w=b/f):(g=n.x,c=n.y,w=t,f=b/w),e.push({x:g,y:c,width:f,height:D(w)}),0===a.direction?n.y+=w:n.x+=f;h+=1});a.reset();0===a.direction?a.width-=m:a.height-=t;n.y=n.parent.y+(n.parent.height-a.height);n.x=n.parent.x+(n.parent.width-a.width);b&&(a.direction=1-a.direction);d||a.addElement(x)},algorithmLowAspectRatio:function(b,
d,a){var e=[],g=this,c,f={x:d.x,y:d.y,parent:d},m=0,t=a.length-1,n=new this.algorithmGroup(d.height,d.width,d.direction,f);a.forEach(function(a){c=a.val/d.val*d.height*d.width;n.addElement(c);n.lP.nR>n.lP.lR&&g.algorithmCalcPoints(b,!1,n,e,f);m===t&&g.algorithmCalcPoints(b,!0,n,e,f);m+=1});return e},algorithmFill:function(b,d,a){var e=[],g,c=d.direction,f=d.x,m=d.y,n=d.width,t=d.height,h,x,J,k;a.forEach(function(a){g=a.val/d.val*d.height*d.width;h=f;x=m;0===c?(k=t,J=g/k,n-=J,f+=J):(J=n,k=g/J,t-=k,
m+=k);e.push({x:h,y:x,width:J,height:k});b&&(c=1-c)});return e},strip:function(b,d){return this.algorithmLowAspectRatio(!1,b,d)},squarified:function(b,d){return this.algorithmLowAspectRatio(!0,b,d)},sliceAndDice:function(b,d){return this.algorithmFill(!0,b,d)},stripes:function(b,d){return this.algorithmFill(!1,b,d)},translate:function(){var b=this,d=b.options,a=S(b);q.prototype.translate.call(b);var c=b.tree=b.getTree();var f=b.nodeMap[a];b.renderTraverseUpButton(a);b.mapOptionsToLevel=G({from:f.level+
1,levels:d.levels,to:c.height,defaults:{levelIsConstant:b.options.levelIsConstant,colorByPoint:d.colorByPoint}});""===a||f&&f.children.length||(b.setRootNode("",!1),a=b.rootNode,f=b.nodeMap[a]);t(b.nodeMap[b.rootNode],function(d){var a=!1,e=d.parent;d.visible=!0;if(e||""===e)a=b.nodeMap[e];return a});t(b.nodeMap[b.rootNode].children,function(b){var d=!1;b.forEach(function(b){b.visible=!0;b.children.length&&(d=(d||[]).concat(b.children))});return d});b.setTreeValues(c);b.axisRatio=b.xAxis.len/b.yAxis.len;
b.nodeMap[""].pointValues=a={x:0,y:0,width:100,height:100};b.nodeMap[""].values=a=e(a,{width:a.width*b.axisRatio,direction:"vertical"===d.layoutStartingDirection?0:1,val:c.val});b.calculateChildrenAreas(c,a);b.colorAxis||d.colorByPoint||b.setColorRecursive(b.tree);d.allowTraversingTree&&(d=f.pointValues,b.xAxis.setExtremes(d.x,d.x+d.width,!1),b.yAxis.setExtremes(d.y,d.y+d.height,!1),b.xAxis.setScale(),b.yAxis.setScale());b.setPointValues()},drawDataLabels:function(){var b=this,d=b.mapOptionsToLevel,
a,c;b.points.filter(function(b){return b.node.visible}).forEach(function(g){c=d[g.node.level];a={style:{}};g.node.isLeaf||(a.enabled=!1);c&&c.dataLabels&&(a=e(a,c.dataLabels),b._hasPointLabels=!0);g.shapeArgs&&(a.style.width=g.shapeArgs.width,g.dataLabel&&g.dataLabel.css({width:g.shapeArgs.width+"px"}));g.dlOptions=e(a,g.options.dataLabels)});q.prototype.drawDataLabels.call(this)},alignDataLabel:function(b,d,a){var e=a.style;!C(e.textOverflow)&&d.text&&d.getBBox().width>d.text.textWidth&&d.css({textOverflow:"ellipsis",
width:e.width+="px"});E.column.prototype.alignDataLabel.apply(this,arguments);b.dataLabel&&b.dataLabel.attr({zIndex:(b.node.zIndex||0)+1})},pointAttribs:function(b,d){var a=T(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},e=b&&a[b.node.level]||{};a=this.options;var c=d&&a.states[d]||{},f=b&&b.getClassName()||"";b={stroke:b&&b.borderColor||e.borderColor||c.borderColor||a.borderColor,"stroke-width":m(b&&b.borderWidth,e.borderWidth,c.borderWidth,a.borderWidth),dashstyle:b&&b.borderDashStyle||e.borderDashStyle||
c.borderDashStyle||a.borderDashStyle,fill:b&&b.color||this.color};-1!==f.indexOf("highcharts-above-level")?(b.fill="none",b["stroke-width"]=0):-1!==f.indexOf("highcharts-internal-node-interactive")?(d=m(c.opacity,a.opacity),b.fill=K(b.fill).setOpacity(d).get(),b.cursor="pointer"):-1!==f.indexOf("highcharts-internal-node")?b.fill="none":d&&(b.fill=K(b.fill).brighten(c.brightness).get());return b},drawPoints:function(){var b=this,a=b.chart,c=a.renderer,f=a.styledMode,m=b.options,n=f?{}:m.shadow,t=m.borderRadius,
h=a.pointCount<m.animationLimit,x=m.allowTraversingTree;b.points.forEach(function(a){var d=a.node.levelDynamic,g={},p={},w={},k="level-group-"+a.node.level,F=!!a.graphic,q=h&&F,l=a.shapeArgs;a.shouldDraw()&&(t&&(p.r=t),e(!0,q?g:p,F?l:{},f?{}:b.pointAttribs(a,a.selected?"select":void 0)),b.colorAttribs&&f&&H(w,b.colorAttribs(a)),b[k]||(b[k]=c.g(k).attr({zIndex:1E3-(d||0)}).add(b.group),b[k].survive=!0));a.draw({animatableAttribs:g,attribs:p,css:w,group:b[k],renderer:c,shadow:n,shapeArgs:l,shapeType:"rect"});
x&&a.graphic&&(a.drillId=m.interactByLeaf?b.drillToByLeaf(a):b.drillToByGroup(a))})},onClickDrillToNode:function(b){var a=(b=b.point)&&b.drillId;P(a)&&(b.setState(""),this.setRootNode(a,!0,{trigger:"click"}))},drillToByGroup:function(b){var a=!1;1!==b.node.level-this.nodeMap[this.rootNode].level||b.node.isLeaf||(a=b.id);return a},drillToByLeaf:function(b){var a=!1;if(b.node.parent!==this.rootNode&&b.node.isLeaf)for(b=b.node;!a;)b=this.nodeMap[b.parent],b.parent===this.rootNode&&(a=b.id);return a},
drillUp:function(){var b=this.nodeMap[this.rootNode];b&&P(b.parent)&&this.setRootNode(b.parent,!0,{trigger:"traverseUpButton"})},drillToNode:function(b,a){L(32,!1,void 0,{"treemap.drillToNode":"use treemap.setRootNode"});this.setRootNode(b,a)},setRootNode:function(b,a,e){b=H({newRootId:b,previousRootId:this.rootNode,redraw:m(a,!0),series:this},e);M(this,"setRootNode",b,function(b){var a=b.series;a.idPreviousRoot=b.previousRootId;a.rootNode=b.newRootId;a.isDirty=!0;b.redraw&&a.chart.redraw()})},renderTraverseUpButton:function(b){var a=
this,e=a.options.traverseUpButton,c=m(e.text,a.nodeMap[b].name,"\u25c1 Back");if(""===b||a.is("sunburst")&&1===a.tree.children.length&&b===a.tree.children[0].id)a.drillUpButton&&(a.drillUpButton=a.drillUpButton.destroy());else if(this.drillUpButton)this.drillUpButton.placed=!1,this.drillUpButton.attr({text:c}).align();else{var f=(b=e.theme)&&b.states;this.drillUpButton=this.chart.renderer.button(c,0,0,function(){a.drillUp()},b,f&&f.hover,f&&f.select).addClass("highcharts-drillup-button").attr({align:e.position.align,
zIndex:7}).add().align(e.position,!1,e.relativeTo||"plotBox")}},buildKDTree:c,drawLegendSymbol:k.drawRectangle,getExtremes:function(){var b=q.prototype.getExtremes.call(this,this.colorValueData),a=b.dataMax;this.valueMin=b.dataMin;this.valueMax=a;return q.prototype.getExtremes.call(this)},getExtremesFromAll:!0,setState:function(b){this.options.inactiveOtherPoints=!0;q.prototype.setState.call(this,b,!1);this.options.inactiveOtherPoints=!1},utils:{recursive:t}},{draw:v.drawPoint,setVisible:E.pie.prototype.pointClass.prototype.setVisible,
getClassName:function(){var b=z.prototype.getClassName.call(this),a=this.series,e=a.options;this.node.level<=a.nodeMap[a.rootNode].level?b+=" highcharts-above-level":this.node.isLeaf||m(e.interactByLeaf,!e.allowTraversingTree)?this.node.isLeaf||(b+=" highcharts-internal-node"):b+=" highcharts-internal-node-interactive";return b},isValid:function(){return!(!this.id&&!O(this.value))},setState:function(b){z.prototype.setState.call(this,b);this.graphic&&this.graphic.attr({zIndex:"hover"===b?1:0})},shouldDraw:function(){return O(this.plotY)&&
null!==this.y}});u(q,"afterBindAxes",function(){var b=this.xAxis,a=this.yAxis;if(b&&a)if(this.is("treemap")){var e={endOnTick:!1,gridLineWidth:0,lineWidth:0,min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};H(a.options,e);H(b.options,e);n=!0}else n&&(a.setOptions(a.userOptions),b.setOptions(b.userOptions),n=!1)});""});v(a,"Series/SunburstSeries.js",[a["Core/Series/Series.js"],a["Mixins/CenteredSeries.js"],a["Mixins/DrawPoint.js"],a["Core/Globals.js"],
a["Series/Line/LineSeries.js"],a["Mixins/TreeSeries.js"],a["Core/Utilities.js"]],function(a,c,r,v,y,k,q){var B=a.seriesTypes,z=c.getCenter,h=c.getStartAndEndRadians,l=k.getColor,E=k.getLevelOptions,K=k.setTreeValues,Q=k.updateRootId,R=q.correctFloat,G=q.error,S=q.extend,u=q.isNumber,D=q.isObject,C=q.isString,L=q.merge,H=q.splat,M=180/Math.PI,N=function(a,c){var e=[];if(u(a)&&u(c)&&a<=c)for(;a<=c;a++)e.push(a);return e},O=function(a,c){c=D(c)?c:{};var e=0,f;if(D(a)){var h=L({},a);a=u(c.from)?c.from:
0;var t=u(c.to)?c.to:0;var n=N(a,t);a=Object.keys(h).filter(function(b){return-1===n.indexOf(+b)});var b=f=u(c.diffRadius)?c.diffRadius:0;n.forEach(function(a){a=h[a];var d=a.levelSize.unit,c=a.levelSize.value;"weight"===d?e+=c:"percentage"===d?(a.levelSize={unit:"pixels",value:c/100*b},f-=a.levelSize.value):"pixels"===d&&(f-=c)});n.forEach(function(b){var a=h[b];"weight"===a.levelSize.unit&&(a=a.levelSize.value,h[b].levelSize={unit:"pixels",value:a/e*f})});a.forEach(function(b){h[b].levelSize={value:0,
unit:"pixels"}})}return h},T=function(a){var c=a.level;return{from:0<c?c:1,to:c+a.height}},P=function(a,c){var e=c.mapIdToNode[a.parent],f=c.series,h=f.chart,t=f.points[a.i];e=l(a,{colors:f.options.colors||h&&h.options.colors,colorIndex:f.colorIndex,index:c.index,mapOptionsToLevel:c.mapOptionsToLevel,parentColor:e&&e.color,parentColorIndex:e&&e.colorIndex,series:c.series,siblings:c.siblings});a.color=e.color;a.colorIndex=e.colorIndex;t&&(t.color=a.color,t.colorIndex=a.colorIndex,a.sliced=a.id!==c.idRoot?
t.sliced:!1);return a};c={drawDataLabels:v.noop,drawPoints:function(){var a=this,c=a.mapOptionsToLevel,m=a.shapeRoot,h=a.group,k=a.hasRendered,t=a.rootNode,n=a.idPreviousRoot,b=a.nodeMap,d=b[n],g=d&&d.shapeArgs;d=a.points;var w=a.startAndEndRadians,p=a.chart,l=p&&p.options&&p.options.chart||{},q="boolean"===typeof l.animation?l.animation:!0,r=a.center[3]/2,z=a.chart.renderer,v=!1,B=!1;if(l=!!(q&&k&&t!==n&&a.dataLabelsGroup)){a.dataLabelsGroup.attr({opacity:0});var C=function(){v=!0;a.dataLabelsGroup&&
a.dataLabelsGroup.animate({opacity:1,visibility:"visible"})}}d.forEach(function(d){var e=d.node,f=c[e.level];var l=d.shapeExisting||{};var x=e.shapeArgs||{},v=!(!e.visible||!e.shapeArgs);if(k&&q){var F={};var y={end:x.end,start:x.start,innerR:x.innerR,r:x.r,x:x.x,y:x.y};v?!d.graphic&&g&&(F=t===d.id?{start:w.start,end:w.end}:g.end<=x.start?{start:w.end,end:w.end}:{start:w.start,end:w.start},F.innerR=F.r=r):d.graphic&&(n===d.id?y={innerR:r,r:r}:m&&(y=m.end<=l.start?{innerR:r,r:r,start:w.end,end:w.end}:
{innerR:r,r:r,start:w.start,end:w.start}));l=F}else y=x,l={};F=[x.plotX,x.plotY];if(!d.node.isLeaf)if(t===d.id){var A=b[t];A=A.parent}else A=d.id;S(d,{shapeExisting:x,tooltipPos:F,drillId:A,name:""+(d.name||d.id||d.index),plotX:x.plotX,plotY:x.plotY,value:e.val,isNull:!v});A=d.options;e=D(x)?x:{};A=D(A)?A.dataLabels:{};f=H(D(f)?f.dataLabels:{})[0];f=L({style:{}},f,A);A=f.rotationMode;if(!u(f.rotation)){if("auto"===A||"circular"===A)if(1>d.innerArcLength&&d.outerArcLength>e.radius){var I=0;d.dataLabelPath&&
"circular"===A&&(f.textPath={enabled:!0})}else 1<d.innerArcLength&&d.outerArcLength>1.5*e.radius?"circular"===A?f.textPath={enabled:!0,attributes:{dy:5}}:A="parallel":(d.dataLabel&&d.dataLabel.textPathWrapper&&"circular"===A&&(f.textPath={enabled:!1}),A="perpendicular");"auto"!==A&&"circular"!==A&&(I=e.end-(e.end-e.start)/2);f.style.width="parallel"===A?Math.min(2.5*e.radius,(d.outerArcLength+d.innerArcLength)/2):e.radius;"perpendicular"===A&&d.series.chart.renderer.fontMetrics(f.style.fontSize).h>
d.outerArcLength&&(f.style.width=1);f.style.width=Math.max(f.style.width-2*(f.padding||0),1);I=I*M%180;"parallel"===A&&(I-=90);90<I?I-=180:-90>I&&(I+=180);f.rotation=I}f.textPath&&(0===d.shapeExisting.innerR&&f.textPath.enabled?(f.rotation=0,f.textPath.enabled=!1,f.style.width=Math.max(2*d.shapeExisting.r-2*(f.padding||0),1)):d.dlOptions&&d.dlOptions.textPath&&!d.dlOptions.textPath.enabled&&"circular"===A&&(f.textPath.enabled=!0),f.textPath.enabled&&(f.rotation=0,f.style.width=Math.max((d.outerArcLength+
d.innerArcLength)/2-2*(f.padding||0),1)));0===f.rotation&&(f.rotation=.001);d.dlOptions=f;if(!B&&v){B=!0;var E=C}d.draw({animatableAttribs:y,attribs:S(l,!p.styledMode&&a.pointAttribs(d,d.selected&&"select")),onComplete:E,group:h,renderer:z,shapeType:"arc",shapeArgs:x})});l&&B?(a.hasRendered=!1,a.options.dataLabels.defer=!0,y.prototype.drawDataLabels.call(a),a.hasRendered=!0,v&&C()):y.prototype.drawDataLabels.call(a)},pointAttribs:B.column.prototype.pointAttribs,layoutAlgorithm:function(a,c,m){var e=
a.start,f=a.end-e,t=a.val,n=a.x,b=a.y,d=m&&D(m.levelSize)&&u(m.levelSize.value)?m.levelSize.value:0,g=a.r,h=g+d,k=m&&u(m.slicedOffset)?m.slicedOffset:0;return(c||[]).reduce(function(a,c){var m=1/t*c.val*f,l=e+m/2,p=n+Math.cos(l)*k;l=b+Math.sin(l)*k;c={x:c.sliced?p:n,y:c.sliced?l:b,innerR:g,r:h,radius:d,start:e,end:e+m};a.push(c);e=c.end;return a},[])},setShapeArgs:function(a,c,m){var e=[],f=m[a.level+1];a=a.children.filter(function(a){return a.visible});e=this.layoutAlgorithm(c,a,f);a.forEach(function(a,
c){c=e[c];var b=c.start+(c.end-c.start)/2,d=c.innerR+(c.r-c.innerR)/2,f=c.end-c.start;d=0===c.innerR&&6.28<f?{x:c.x,y:c.y}:{x:c.x+Math.cos(b)*d,y:c.y+Math.sin(b)*d};var h=a.val?a.childrenTotal>a.val?a.childrenTotal:a.val:a.childrenTotal;this.points[a.i]&&(this.points[a.i].innerArcLength=f*c.innerR,this.points[a.i].outerArcLength=f*c.r);a.shapeArgs=L(c,{plotX:d.x,plotY:d.y+4*Math.abs(Math.cos(b))});a.values=L(c,{val:h});a.children.length&&this.setShapeArgs(a,a.values,m)},this)},translate:function(){var a=
this,c=a.options,m=a.center=z.call(a),k=a.startAndEndRadians=h(c.startAngle,c.endAngle),l=m[3]/2,t=m[2]/2-l,n=Q(a),b=a.nodeMap,d=b&&b[n],g={};a.shapeRoot=d&&d.shapeArgs;y.prototype.translate.call(a);var r=a.tree=a.getTree();a.renderTraverseUpButton(n);b=a.nodeMap;d=b[n];var p=C(d.parent)?d.parent:"";p=b[p];var q=T(d);var u=q.from,v=q.to;q=E({from:u,levels:a.options.levels,to:v,defaults:{colorByPoint:c.colorByPoint,dataLabels:c.dataLabels,levelIsConstant:c.levelIsConstant,levelSize:c.levelSize,slicedOffset:c.slicedOffset}});
q=O(q,{diffRadius:t,from:u,to:v});K(r,{before:P,idRoot:n,levelIsConstant:c.levelIsConstant,mapOptionsToLevel:q,mapIdToNode:b,points:a.points,series:a});c=b[""].shapeArgs={end:k.end,r:l,start:k.start,val:d.val,x:m[0],y:m[1]};this.setShapeArgs(p,c,q);a.mapOptionsToLevel=q;a.data.forEach(function(b){g[b.id]&&G(31,!1,a.chart);g[b.id]=!0});g={}},alignDataLabel:function(a,c,m){if(!m.textPath||!m.textPath.enabled)return B.treemap.prototype.alignDataLabel.apply(this,arguments)},animate:function(a){var c=
this.chart,e=[c.plotWidth/2,c.plotHeight/2],h=c.plotLeft,k=c.plotTop;c=this.group;a?(a={translateX:e[0]+h,translateY:e[1]+k,scaleX:.001,scaleY:.001,rotation:10,opacity:.01},c.attr(a)):(a={translateX:h,translateY:k,scaleX:1,scaleY:1,rotation:0,opacity:1},c.animate(a,this.options.animation))},utils:{calculateLevelSizes:O,getLevelFromAndTo:T,range:N}};r={draw:r.drawPoint,shouldDraw:function(){return!this.isNull},isValid:function(){return!0},getDataLabelPath:function(a){var c=this.series.chart.renderer,
e=this.shapeExisting,h=e.start,k=e.end,l=h+(k-h)/2;l=0>l&&l>-Math.PI||l>Math.PI;var n=e.r+(a.options.distance||0);h===-Math.PI/2&&R(k)===R(1.5*Math.PI)&&(h=-Math.PI+Math.PI/360,k=-Math.PI/360,l=!0);if(k-h>Math.PI){l=!1;var b=!0}this.dataLabelPath&&(this.dataLabelPath=this.dataLabelPath.destroy());this.dataLabelPath=c.arc({open:!0,longArc:b?1:0}).add(a);this.dataLabelPath.attr({start:l?h:k,end:l?k:h,clockwise:+l,x:e.x,y:e.y,r:(n+e.innerR)/2});return this.dataLabelPath}};"";a.seriesType("sunburst",
"treemap",{center:["50%","50%"],colorByPoint:!1,opacity:1,dataLabels:{allowOverlap:!0,defer:!0,rotationMode:"auto",style:{textOverflow:"ellipsis"}},rootId:void 0,levelIsConstant:!0,levelSize:{value:1,unit:"weight"},slicedOffset:10},c,r)});v(a,"masters/modules/sunburst.src.js",[],function(){})});
//# sourceMappingURL=sunburst.js.map