/*
 Highcharts Gantt JS v8.2.2 (2020-11-23)

 Tree Grid

 (c) 2016-2019 Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/treegrid",["highcharts"],function(C){b(C);b.Highcharts=C;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function C(b,t,x,u){b.hasOwnProperty(t)||(b[t]=u.apply(null,x))}b=b?b._modules:{};C(b,"Gantt/Tree.js",[b["Core/Utilities.js"]],function(b){var t=b.extend,x=b.isNumber,u=b.pick,p=function(b,p){var m=b.reduce(function(f,
m){var l=u(m.parent,"");"undefined"===typeof f[l]&&(f[l]=[]);f[l].push(m);return f},{});Object.keys(m).forEach(function(f,b){var l=m[f];""!==f&&-1===p.indexOf(f)&&(l.forEach(function(f){b[""].push(f)}),delete b[f])});return m},v=function(b,p,m,f,D,l){var n=0,r=0,k=l&&l.after,a=l&&l.before;p={data:f,depth:m-1,id:b,level:m,parent:p};var g,h;"function"===typeof a&&a(p,l);a=(D[b]||[]).map(function(d){var c=v(d.id,b,m+1,d,D,l),e=d.start;d=!0===d.milestone?e:d.end;g=!x(g)||e<g?e:g;h=!x(h)||d>h?d:h;n=n+
1+c.descendants;r=Math.max(c.height+1,r);return c});f&&(f.start=u(f.start,g),f.end=u(f.end,h));t(p,{children:a,descendants:n,height:r});"function"===typeof k&&k(p,l);return p};return{getListOfParents:p,getNode:v,getTree:function(b,u){var m=b.map(function(f){return f.id});b=p(b,m);return v("",null,1,null,b,u)}}});C(b,"Core/Axis/TreeGridTick.js",[b["Core/Color/Palette.js"],b["Core/Utilities.js"]],function(b,t){var x=t.addEvent,u=t.defined,p=t.isObject,v=t.isNumber,w=t.pick,A=t.wrap,m;(function(f){function m(){this.treeGrid||
(this.treeGrid=new a(this))}function l(a,h){a=a.treeGrid;var d=!a.labelIcon,c=h.renderer,e=h.xy,q=h.options,B=q.width,g=q.height,f=e.x-B/2-q.padding;e=e.y-g/2;var n=h.collapsed?90:180,z=h.show&&v(e),k=a.labelIcon;k||(a.labelIcon=k=c.path(c.symbols[q.type](q.x,q.y,B,g)).addClass("highcharts-label-icon").add(h.group));z||k.attr({y:-9999});c.styledMode||k.attr({"stroke-width":1,fill:w(h.color,b.neutralColor60)}).css({cursor:"pointer",stroke:q.lineColor,strokeWidth:q.lineWidth});k[d?"attr":"animate"]({translateX:f,
translateY:e,rotation:n})}function n(a,h,d,c,e,q,B,f,k){var g=w(this.options&&this.options.labels,q);q=this.pos;var G=this.axis,n="treegrid"===G.options.type;a=a.apply(this,[h,d,c,e,g,B,f,k]);n&&(h=g&&p(g.symbol,!0)?g.symbol:{},g=g&&v(g.indentation)?g.indentation:0,q=(q=(G=G.treeGrid.mapOfPosToGridNode)&&G[q])&&q.depth||1,a.x+=h.width+2*h.padding+(q-1)*g);return a}function r(a){var h=this,d=h.pos,c=h.axis,e=h.label,q=c.treeGrid.mapOfPosToGridNode,B=c.options,g=w(h.options&&h.options.labels,B&&B.labels),
f=g&&p(g.symbol,!0)?g.symbol:{},k=(q=q&&q[d])&&q.depth;B="treegrid"===B.type;var n=-1<c.tickPositions.indexOf(d);d=c.chart.styledMode;B&&q&&e&&e.element&&e.addClass("highcharts-treegrid-node-level-"+k);a.apply(h,Array.prototype.slice.call(arguments,1));B&&e&&e.element&&q&&q.descendants&&0<q.descendants&&(c=c.treeGrid.isCollapsed(q),l(h,{color:!d&&e.styles&&e.styles.color||"",collapsed:c,group:e.parentGroup,options:f,renderer:e.renderer,show:n,xy:e.xy}),f="highcharts-treegrid-node-"+(c?"expanded":
"collapsed"),e.addClass("highcharts-treegrid-node-"+(c?"collapsed":"expanded")).removeClass(f),d||e.css({cursor:"pointer"}),[e,h.treeGrid.labelIcon].forEach(function(c){c&&!c.attachedTreeGridEvents&&(x(c.element,"mouseover",function(){e.addClass("highcharts-treegrid-node-active");e.renderer.styledMode||e.css({textDecoration:"underline"})}),x(c.element,"mouseout",function(){var c=u(g.style)?g.style:{};e.removeClass("highcharts-treegrid-node-active");e.renderer.styledMode||e.css({textDecoration:c.textDecoration})}),
x(c.element,"click",function(){h.treeGrid.toggleCollapse()}),c.attachedTreeGridEvents=!0)}))}var k=!1;f.compose=function(a){k||(x(a,"init",m),A(a.prototype,"getLabelPosition",n),A(a.prototype,"renderLabel",r),a.prototype.collapse=function(a){this.treeGrid.collapse(a)},a.prototype.expand=function(a){this.treeGrid.expand(a)},a.prototype.toggleCollapse=function(a){this.treeGrid.toggleCollapse(a)},k=!0)};var a=function(){function a(a){this.tick=a}a.prototype.collapse=function(a){var d=this.tick,c=d.axis,
e=c.brokenAxis;e&&c.treeGrid.mapOfPosToGridNode&&(d=c.treeGrid.collapse(c.treeGrid.mapOfPosToGridNode[d.pos]),e.setBreaks(d,w(a,!0)))};a.prototype.expand=function(a){var d=this.tick,c=d.axis,e=c.brokenAxis;e&&c.treeGrid.mapOfPosToGridNode&&(d=c.treeGrid.expand(c.treeGrid.mapOfPosToGridNode[d.pos]),e.setBreaks(d,w(a,!0)))};a.prototype.toggleCollapse=function(a){var d=this.tick,c=d.axis,e=c.brokenAxis;e&&c.treeGrid.mapOfPosToGridNode&&(d=c.treeGrid.toggleCollapse(c.treeGrid.mapOfPosToGridNode[d.pos]),
e.setBreaks(d,w(a,!0)))};return a}();f.Additions=a})(m||(m={}));return m});C(b,"Mixins/TreeSeries.js",[b["Core/Color/Color.js"],b["Core/Utilities.js"]],function(b,t){var x=t.extend,u=t.isArray,p=t.isNumber,v=t.isObject,w=t.merge,A=t.pick;return{getColor:function(m,f){var p=f.index,l=f.mapOptionsToLevel,n=f.parentColor,r=f.parentColorIndex,k=f.series,a=f.colors,g=f.siblings,h=k.points,d=k.chart.options.chart,c;if(m){h=h[m.i];m=l[m.level]||{};if(l=h&&m.colorByPoint){var e=h.index%(a?a.length:d.colorCount);
var q=a&&a[e]}if(!k.chart.styledMode){a=h&&h.options.color;d=m&&m.color;if(c=n)c=(c=m&&m.colorVariation)&&"brightness"===c.key?b.parse(n).brighten(p/g*c.to).get():n;c=A(a,d,q,c,k.color)}var B=A(h&&h.options.colorIndex,m&&m.colorIndex,e,r,f.colorIndex)}return{color:c,colorIndex:B}},getLevelOptions:function(b){var f=null;if(v(b)){f={};var m=p(b.from)?b.from:1;var l=b.levels;var n={};var r=v(b.defaults)?b.defaults:{};u(l)&&(n=l.reduce(function(f,a){if(v(a)&&p(a.level)){var b=w({},a);var h="boolean"===
typeof b.levelIsConstant?b.levelIsConstant:r.levelIsConstant;delete b.levelIsConstant;delete b.level;a=a.level+(h?0:m-1);v(f[a])?x(f[a],b):f[a]=b}return f},{}));l=p(b.to)?b.to:1;for(b=0;b<=l;b++)f[b]=w({},r,v(n[b])?n[b]:{})}return f},setTreeValues:function l(f,b){var n=b.before,r=b.idRoot,k=b.mapIdToNode[r],a=b.points[f.i],g=a&&a.options||{},h=0,d=[];x(f,{levelDynamic:f.level-(("boolean"===typeof b.levelIsConstant?b.levelIsConstant:1)?0:k.level),name:A(a&&a.name,""),visible:r===f.id||("boolean"===
typeof b.visible?b.visible:!1)});"function"===typeof n&&(f=n(f,b));f.children.forEach(function(c,e){var a=x({},b);x(a,{index:e,siblings:f.children.length,visible:f.visible});c=l(c,a);d.push(c);c.visible&&(h+=c.val)});f.visible=0<h||f.visible;n=A(g.value,h);x(f,{children:d,childrenTotal:h,isLeaf:f.visible&&!h,val:n});return f},updateRootId:function(b){if(v(b)){var f=v(b.options)?b.options:{};f=A(b.rootNode,f.rootId,"");v(b.userOptions)&&(b.userOptions.rootId=f);b.rootNode=f}return f}}});C(b,"Core/Axis/GridAxis.js",
[b["Core/Axis/Axis.js"],b["Core/Globals.js"],b["Core/Axis/Tick.js"],b["Core/Utilities.js"]],function(b,t,x,u){var p=u.addEvent,v=u.defined,w=u.erase,A=u.find,m=u.isArray,f=u.isNumber,D=u.merge,l=u.pick,n=u.timeUnits,r=u.wrap,k=t.Chart,a=function(a){var c=a.options;c.labels||(c.labels={});c.labels.align=l(c.labels.align,"center");a.categories||(c.showLastLabel=!1);a.labelRotation=0;c.labels.rotation=0};"";b.prototype.getMaxLabelDimensions=function(a,c){var e={width:0,height:0};c.forEach(function(c){c=
a[c];if(u.isObject(c,!0)){var d=u.isObject(c.label,!0)?c.label:{};c=d.getBBox?d.getBBox().height:0;d.textStr&&!f(d.textPxLength)&&(d.textPxLength=d.getBBox().width);var q=f(d.textPxLength)?Math.round(d.textPxLength):0;d.textStr&&(q=Math.round(d.getBBox().width));e.height=Math.max(c,e.height);e.width=Math.max(q,e.width)}});return e};t.dateFormats.W=function(a){a=new this.Date(a);var c=(this.get("Day",a)+6)%7,e=new this.Date(a.valueOf());this.set("Date",e,this.get("Date",a)-c+3);c=new this.Date(this.get("FullYear",
e),0,1);4!==this.get("Day",c)&&(this.set("Month",a,0),this.set("Date",a,1+(11-this.get("Day",c))%7));return(1+Math.floor((e.valueOf()-c.valueOf())/6048E5)).toString()};t.dateFormats.E=function(a){return this.dateFormat("%a",a,!0).charAt(0)};p(k,"afterSetChartSize",function(){this.axes.forEach(function(a){(a.grid&&a.grid.columns||[]).forEach(function(c){c.setAxisSize();c.setAxisTranslation()})})});p(x,"afterGetLabelPosition",function(a){var c=this.label,e=this.axis,d=e.reversed,b=e.chart,g=e.options.grid||
{},n=e.options.labels,k=n.align,z=h.Side[e.side],r=a.tickmarkOffset,l=e.tickPositions,E=this.pos-r;l=f(l[a.index+1])?l[a.index+1]-r:e.max+r;var y=e.tickSize("tick");r=y?y[0]:0;y=y?y[1]/2:0;if(!0===g.enabled){if("top"===z){g=e.top+e.offset;var F=g-r}else"bottom"===z?(F=b.chartHeight-e.bottom+e.offset,g=F+r):(g=e.top+e.len-e.translate(d?l:E),F=e.top+e.len-e.translate(d?E:l));"right"===z?(z=b.chartWidth-e.right+e.offset,d=z+r):"left"===z?(d=e.left+e.offset,z=d-r):(z=Math.round(e.left+e.translate(d?l:
E))-y,d=Math.round(e.left+e.translate(d?E:l))-y);this.slotWidth=d-z;a.pos.x="left"===k?z:"right"===k?d:z+(d-z)/2;a.pos.y=F+(g-F)/2;b=b.renderer.fontMetrics(n.style.fontSize,c.element);c=c.getBBox().height;n.useHTML?a.pos.y+=b.b+-(c/2):(c=Math.round(c/b.h),a.pos.y+=(b.b-(b.h-b.f))/2+-((c-1)*b.h/2));a.pos.x+=e.horiz&&n.x||0}});var g=function(){function a(c){this.axis=c}a.prototype.isOuterAxis=function(){var c=this.axis,a=c.grid.columnIndex,d=c.linkedParent&&c.linkedParent.grid.columns||c.grid.columns,
b=a?c.linkedParent:c,h=-1,g=0;c.chart[c.coll].forEach(function(a,e){a.side!==c.side||a.options.isInternal||(g=e,a===b&&(h=e))});return g===h&&(f(a)?d.length===a:!0)};a.prototype.renderBorder=function(c){var a=this.axis,d=a.chart.renderer,b=a.options;c=d.path(c).addClass("highcharts-axis-line").add(a.axisBorder);d.styledMode||c.attr({stroke:b.lineColor,"stroke-width":b.lineWidth,zIndex:7});return c};return a}(),h=function(){function d(){}d.compose=function(c){b.keepProps.push("grid");r(c.prototype,
"unsquish",d.wrapUnsquish);p(c,"init",d.onInit);p(c,"afterGetOffset",d.onAfterGetOffset);p(c,"afterGetTitlePosition",d.onAfterGetTitlePosition);p(c,"afterInit",d.onAfterInit);p(c,"afterRender",d.onAfterRender);p(c,"afterSetAxisTranslation",d.onAfterSetAxisTranslation);p(c,"afterSetOptions",d.onAfterSetOptions);p(c,"afterSetOptions",d.onAfterSetOptions2);p(c,"afterSetScale",d.onAfterSetScale);p(c,"afterTickSize",d.onAfterTickSize);p(c,"trimTicks",d.onTrimTicks);p(c,"destroy",d.onDestroy)};d.onAfterGetOffset=
function(){var c=this.grid;(c&&c.columns||[]).forEach(function(c){c.getOffset()})};d.onAfterGetTitlePosition=function(c){if(!0===(this.options.grid||{}).enabled){var a=this.axisTitle,b=this.height,h=this.horiz,f=this.left,g=this.offset,n=this.opposite,k=this.options.title,r=void 0===k?{}:k;k=this.top;var p=this.width,E=this.tickSize(),y=a&&a.getBBox().width,F=r.x||0,J=r.y||0,m=l(r.margin,h?5:10);a=this.chart.renderer.fontMetrics(r.style&&r.style.fontSize,a).f;E=(h?k+b:f)+(h?1:-1)*(n?-1:1)*(E?E[0]/
2:0)+(this.side===d.Side.bottom?a:0);c.titlePosition.x=h?f-y/2-m+F:E+(n?p:0)+g+F;c.titlePosition.y=h?E-(n?b:0)+(n?a:-a)/2+g+J:k-m+J}};d.onAfterInit=function(){var c=this.chart,e=this.options.grid;e=void 0===e?{}:e;var d=this.userOptions;e.enabled&&(a(this),r(this,"labelFormatter",function(c){var a=this.axis,e=this.value,d=a.tickPositions,b=(a.isLinked?a.linkedParent:a).series[0],q=e===d[0];d=e===d[d.length-1];var h=b&&A(b.options.data,function(c){return c[a.isXAxis?"x":"y"]===e});if(h&&b.is("gantt")){var g=
D(h);t.seriesTypes.gantt.prototype.setGanttPointAliases(g)}this.isFirst=q;this.isLast=d;this.point=g;return c.call(this)}));if(e.columns)for(var h=this.grid.columns=[],f=this.grid.columnIndex=0;++f<e.columns.length;){var g=D(d,e.columns[e.columns.length-f-1],{linkedTo:0,type:"category",scrollbar:{enabled:!1}});delete g.grid.columns;g=new b(this.chart,g);g.grid.isColumn=!0;g.grid.columnIndex=f;w(c.axes,g);w(c[this.coll],g);h.push(g)}};d.onAfterRender=function(){var c,a=this.grid,b=this.options;if(!0===
(b.grid||{}).enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();if(this.grid&&this.grid.isOuterAxis()&&this.axisLine&&(b=b.lineWidth)){b=this.getLinePath(b);var h=b[0],g=b[1],f=((this.tickSize("tick")||[1])[0]-1)*(this.side===d.Side.top||this.side===d.Side.left?-1:1);"M"===h[0]&&"L"===g[0]&&(this.horiz?(h[2]+=f,g[2]+=f):(h[1]+=f,g[1]+=f));!this.horiz&&this.chart.marginRight&&(h=[h,["L",this.left,h[2]]],f=["L",this.chart.chartWidth-
this.chart.marginRight,this.toPixels(this.max+this.tickmarkOffset)],g=[["M",g[1],this.toPixels(this.max+this.tickmarkOffset)],f],this.grid.upperBorder||0===this.min%1||(this.grid.upperBorder=this.grid.renderBorder(h)),this.grid.upperBorder&&this.grid.upperBorder.animate({d:h}),this.grid.lowerBorder||0===this.max%1||(this.grid.lowerBorder=this.grid.renderBorder(g)),this.grid.lowerBorder&&this.grid.lowerBorder.animate({d:g}));this.grid.axisLineExtra?this.grid.axisLineExtra.animate({d:b}):this.grid.axisLineExtra=
this.grid.renderBorder(b);this.axisLine[this.showAxis?"show":"hide"](!0)}(a&&a.columns||[]).forEach(function(a){a.render()});!this.horiz&&this.chart.hasRendered&&(this.scrollbar||(null===(c=this.linkedParent)||void 0===c?0:c.scrollbar))&&(c=this.max,a=this.tickmarkOffset,b=this.tickPositions[this.tickPositions.length-1],g=this.tickPositions[0],this.min-g>a?this.ticks[g].label.hide():this.ticks[g].label.show(),b-c>a?this.ticks[b].label.hide():this.ticks[b].label.show(),b-c<a&&0<b-c&&this.ticks[b].isLast?
this.ticks[b].mark.hide():this.ticks[b-1].mark.show())}};d.onAfterSetAxisTranslation=function(){var a,e=this.tickPositions&&this.tickPositions.info,d=this.options,b=d.grid||{},h=this.userOptions.labels||{};this.horiz?(!0===b.enabled&&this.series.forEach(function(a){a.options.pointRange=0}),e&&d.dateTimeLabelFormats&&d.labels&&!v(h.align)&&(!1===d.dateTimeLabelFormats[e.unitName].range||1<e.count)&&(d.labels.align="left",v(h.x)||(d.labels.x=3))):"treegrid"!==this.options.type&&(null===(a=this.grid)||
void 0===a?0:a.columns)&&(this.minPointOffset=this.tickInterval)};d.onAfterSetOptions=function(a){var c=this.options;a=a.userOptions;var d=c&&u.isObject(c.grid,!0)?c.grid:{};if(!0===d.enabled){var b=D(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,
reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},a);"xAxis"===this.coll&&(v(a.linkedTo)&&!v(a.tickPixelInterval)&&(b.tickPixelInterval=350),v(a.tickPixelInterval)||!v(a.linkedTo)||v(a.tickPositioner)||v(a.tickInterval)||(b.tickPositioner=function(a,c){var d=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(d){var e,h=b.units;for(e=0;e<h.length;e++)if(h[e][0]===
d.unitName){var g=e;break}if(h[g+1]){var f=h[g+1][0];var y=(h[g+1][1]||[1])[0]}else"year"===d.unitName&&(f="year",y=10*d.count);d=n[f];this.tickInterval=d*y;return this.getTimeTicks({unitRange:d,count:y,unitName:f},a,c,this.options.startOfWeek)}}));D(!0,this.options,b);this.horiz&&(c.minPadding=l(a.minPadding,0),c.maxPadding=l(a.maxPadding,0));f(c.grid.borderWidth)&&(c.tickWidth=c.lineWidth=d.borderWidth)}};d.onAfterSetOptions2=function(a){a=(a=a.userOptions)&&a.grid||{};var c=a.columns;a.enabled&&
c&&D(!0,this.options,c[c.length-1])};d.onAfterSetScale=function(){(this.grid.columns||[]).forEach(function(a){a.setScale()})};d.onAfterTickSize=function(a){var c=b.defaultLeftAxisOptions,d=this.horiz,h=this.maxLabelDimensions,g=this.options.grid;g=void 0===g?{}:g;g.enabled&&h&&(c=2*Math.abs(c.labels.x),d=d?g.cellHeight||c+h.height:c+h.width,m(a.tickSize)?a.tickSize[0]=d:a.tickSize=[d,0])};d.onDestroy=function(a){var c=this.grid;(c.columns||[]).forEach(function(c){c.destroy(a.keepEvents)});c.columns=
void 0};d.onInit=function(a){a=a.userOptions||{};var c=a.grid||{};c.enabled&&v(c.borderColor)&&(a.tickColor=a.lineColor=c.borderColor);this.grid||(this.grid=new g(this))};d.onTrimTicks=function(){var a=this.options,d=this.categories,b=this.tickPositions,h=b[0],g=b[b.length-1],f=this.linkedParent&&this.linkedParent.min||this.min,n=this.linkedParent&&this.linkedParent.max||this.max,k=this.tickInterval;!0!==(a.grid||{}).enabled||d||!this.horiz&&!this.isLinked||(h<f&&h+k>f&&!a.startOnTick&&(b[0]=f),g>
n&&g-k<n&&!a.endOnTick&&(b[b.length-1]=n))};d.wrapUnsquish=function(a){var c=this.options.grid;return!0===(void 0===c?{}:c).enabled&&this.categories?this.tickInterval:a.apply(this,Array.prototype.slice.call(arguments,1))};return d}();(function(a){a=a.Side||(a.Side={});a[a.top=0]="top";a[a.right=1]="right";a[a.bottom=2]="bottom";a[a.left=3]="left"})(h||(h={}));h.compose(b);return h});C(b,"Core/Axis/BrokenAxis.js",[b["Core/Axis/Axis.js"],b["Series/Line/LineSeries.js"],b["Extensions/Stacking.js"],b["Core/Utilities.js"]],
function(b,t,x,u){var p=u.addEvent,v=u.find,w=u.fireEvent,A=u.isArray,m=u.isNumber,f=u.pick,D=function(){function l(b){this.hasBreaks=!1;this.axis=b}l.isInBreak=function(b,f){var k=b.repeat||Infinity,a=b.from,g=b.to-b.from;f=f>=a?(f-a)%k:k-(a-f)%k;return b.inclusive?f<=g:f<g&&0!==f};l.lin2Val=function(b){var f=this.brokenAxis;f=f&&f.breakArray;if(!f)return b;var k;for(k=0;k<f.length;k++){var a=f[k];if(a.from>=b)break;else a.to<b?b+=a.len:l.isInBreak(a,b)&&(b+=a.len)}return b};l.val2Lin=function(b){var f=
this.brokenAxis;f=f&&f.breakArray;if(!f)return b;var k=b,a;for(a=0;a<f.length;a++){var g=f[a];if(g.to<=b)k-=g.len;else if(g.from>=b)break;else if(l.isInBreak(g,b)){k-=b-g.from;break}}return k};l.prototype.findBreakAt=function(b,f){return v(f,function(f){return f.from<b&&b<f.to})};l.prototype.isInAnyBreak=function(b,m){var k=this.axis,a=k.options.breaks,g=a&&a.length,h;if(g){for(;g--;)if(l.isInBreak(a[g],b)){var d=!0;h||(h=f(a[g].showPoints,!k.isXAxis))}var c=d&&m?d&&!h:d}return c};l.prototype.setBreaks=
function(n,m){var k=this,a=k.axis,g=A(n)&&!!n.length;a.isDirty=k.hasBreaks!==g;k.hasBreaks=g;a.options.breaks=a.userOptions.breaks=n;a.forceRedraw=!0;a.series.forEach(function(a){a.isDirty=!0});g||a.val2lin!==l.val2Lin||(delete a.val2lin,delete a.lin2val);g&&(a.userOptions.ordinal=!1,a.lin2val=l.lin2Val,a.val2lin=l.val2Lin,a.setExtremes=function(a,d,c,e,f){if(k.hasBreaks){for(var g,h=this.options.breaks;g=k.findBreakAt(a,h);)a=g.to;for(;g=k.findBreakAt(d,h);)d=g.from;d<a&&(d=a)}b.prototype.setExtremes.call(this,
a,d,c,e,f)},a.setAxisTranslation=function(){b.prototype.setAxisTranslation.call(this);k.unitLength=null;if(k.hasBreaks){var g=a.options.breaks||[],d=[],c=[],e=0,q,n=a.userMin||a.min,m=a.userMax||a.max,p=f(a.pointRangePadding,0),r;g.forEach(function(a){q=a.repeat||Infinity;l.isInBreak(a,n)&&(n+=a.to%q-n%q);l.isInBreak(a,m)&&(m-=m%q-a.from%q)});g.forEach(function(a){t=a.from;for(q=a.repeat||Infinity;t-q>n;)t-=q;for(;t<n;)t+=q;for(r=t;r<m;r+=q)d.push({value:r,move:"in"}),d.push({value:r+(a.to-a.from),
move:"out",size:a.breakSize})});d.sort(function(a,c){return a.value===c.value?("in"===a.move?0:1)-("in"===c.move?0:1):a.value-c.value});var u=0;var t=n;d.forEach(function(a){u+="in"===a.move?1:-1;1===u&&"in"===a.move&&(t=a.value);0===u&&(c.push({from:t,to:a.value,len:a.value-t-(a.size||0)}),e+=a.value-t-(a.size||0))});a.breakArray=k.breakArray=c;k.unitLength=m-n-e+p;w(a,"afterBreaks");a.staticScale?a.transA=a.staticScale:k.unitLength&&(a.transA*=(m-a.min+p)/k.unitLength);p&&(a.minPixelPadding=a.transA*
a.minPointOffset);a.min=n;a.max=m}});f(m,!0)&&a.chart.redraw()};return l}();u=function(){function b(){}b.compose=function(b,l){b.keepProps.push("brokenAxis");var k=t.prototype;k.drawBreaks=function(a,b){var g=this,d=g.points,c,e,k,l;if(a&&a.brokenAxis&&a.brokenAxis.hasBreaks){var n=a.brokenAxis;b.forEach(function(b){c=n&&n.breakArray||[];e=a.isXAxis?a.min:f(g.options.threshold,a.min);d.forEach(function(d){l=f(d["stack"+b.toUpperCase()],d[b]);c.forEach(function(b){if(m(e)&&m(l)){k=!1;if(e<b.from&&
l>b.to||e>b.from&&l<b.from)k="pointBreak";else if(e<b.from&&l>b.from&&l<b.to||e>b.from&&l>b.to&&l<b.from)k="pointInBreak";k&&w(a,k,{point:d,brk:b})}})})})}};k.gappedPath=function(){var a=this.currentDataGrouping,b=a&&a.gapSize;a=this.options.gapSize;var f=this.points.slice(),d=f.length-1,c=this.yAxis,e;if(a&&0<d)for("value"!==this.options.gapUnit&&(a*=this.basePointRange),b&&b>a&&b>=this.basePointRange&&(a=b),e=void 0;d--;)e&&!1!==e.visible||(e=f[d+1]),b=f[d],!1!==e.visible&&!1!==b.visible&&(e.x-
b.x>a&&(e=(b.x+e.x)/2,f.splice(d+1,0,{isNull:!0,x:e}),c.stacking&&this.options.stacking&&(e=c.stacking.stacks[this.stackKey][e]=new x(c,c.options.stackLabels,!1,e,this.stack),e.total=0)),e=b);return this.getGraphPath(f)};p(b,"init",function(){this.brokenAxis||(this.brokenAxis=new D(this))});p(b,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});p(b,"afterSetTickPositions",function(){var a=this.brokenAxis;if(a&&a.hasBreaks){var b=this.tickPositions,
f=this.tickPositions.info,d=[],c;for(c=0;c<b.length;c++)a.isInAnyBreak(b[c])||d.push(b[c]);this.tickPositions=d;this.tickPositions.info=f}});p(b,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});p(l,"afterGeneratePoints",function(){var a=this.options.connectNulls,b=this.points,f=this.xAxis,d=this.yAxis;if(this.isDirty)for(var c=b.length;c--;){var e=b[c],k=!(null===e.y&&!1===a)&&(f&&f.brokenAxis&&f.brokenAxis.isInAnyBreak(e.x,!0)||d&&d.brokenAxis&&
d.brokenAxis.isInAnyBreak(e.y,!0));e.visible=k?!1:!1!==e.options.visible}});p(l,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,f(this.pointArrayMap,["y"]))})};return b}();u.compose(b,t);return u});C(b,"Core/Axis/TreeGridAxis.js",[b["Core/Globals.js"],b["Core/Axis/Axis.js"],b["Core/Axis/Tick.js"],b["Gantt/Tree.js"],b["Core/Axis/TreeGridTick.js"],b["Mixins/TreeSeries.js"],b["Core/Utilities.js"]],function(b,t,x,u,p,v,w){var A=v.getLevelOptions,m=w.addEvent,f=w.find,
D=w.fireEvent,l=w.isArray,n=w.isNumber,r=w.isObject,k=w.isString,a=w.merge,g=w.pick,h=w.wrap,d;(function(c){function d(a,b){var c=a.collapseStart||0;a=a.collapseEnd||0;a>=b&&(c-=.5);return{from:c,to:a,showPoints:!1}}function q(a,b,c){var d=[],e=[],g={},h={},y=-1,l="boolean"===typeof b?b:!1;a=u.getTree(a,{after:function(a){a=h[a.pos];var b=0,c=0;a.children.forEach(function(a){c+=(a.descendants||0)+1;b=Math.max((a.height||0)+1,b)});a.descendants=c;a.height=b;a.collapsed&&e.push(a)},before:function(a){var b=
r(a.data,!0)?a.data:{},c=k(b.name)?b.name:"",e=g[a.parent];e=r(e,!0)?h[e.pos]:null;var m=function(a){return a.name===c},n;l&&r(e,!0)&&(n=f(e.children,m))?(m=n.pos,n.nodes.push(a)):m=y++;h[m]||(h[m]=n={depth:e?e.depth+1:0,name:c,id:b.id,nodes:[a],children:[],pos:m},-1!==m&&d.push(c),r(e,!0)&&e.children.push(n));k(a.id)&&(g[a.id]=a);n&&!0===b.collapsed&&(n.collapsed=!0);a.pos=m}});h=function(a,b){var c=function(a,d,e){var f=d+(-1===d?0:b-1),g=(f-d)/2,h=d+g;a.nodes.forEach(function(a){var b=a.data;r(b,
!0)&&(b.y=d+(b.seriesIndex||0),delete b.seriesIndex);a.pos=h});e[h]=a;a.pos=h;a.tickmarkOffset=g+.5;a.collapseStart=f+.5;a.children.forEach(function(a){c(a,f+1,e);f=(a.collapseEnd||0)-.5});a.collapseEnd=f+.5;return e};return c(a["-1"],-1,{})}(h,c);return{categories:d,mapOfIdToNode:g,mapOfPosToGridNode:h,collapsedNodes:e,tree:a}}function t(c){c.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(d){var e=d.options||{},f=e.labels,g=e.uniqueNames,h=0;e=e.max;if(!d.treeGrid.mapOfPosToGridNode||
d.series.some(function(a){return!a.hasRendered||a.isDirtyData||a.isDirty})){var k=d.series.reduce(function(a,c){c.visible&&((c.options.data||[]).forEach(function(d){c.options.keys&&c.options.keys.length&&(d=c.pointClass.prototype.optionsToObject.call({series:c},d),b.seriesTypes.gantt.prototype.setGanttPointAliases(d));r(d,!0)&&(d.seriesIndex=h,a.push(d))}),!0===g&&h++);return a},[]);if(e&&k.length<e)for(var y=k.length;y<=e;y++)k.push({name:y+"\u200b"});e=q(k,g||!1,!0===g?h:1);d.categories=e.categories;
d.treeGrid.mapOfPosToGridNode=e.mapOfPosToGridNode;d.hasNames=!0;d.treeGrid.tree=e.tree;d.series.forEach(function(b){var c=(b.options.data||[]).map(function(c){l(c)&&b.options.keys&&b.options.keys.length&&k.forEach(function(a){0<=c.indexOf(a.x)&&0<=c.indexOf(a.x2)&&(c=a)});return r(c,!0)?a(c):c});b.visible&&b.setData(c,!1)});d.treeGrid.mapOptionsToLevel=A({defaults:f,from:1,levels:f&&f.levels,to:d.treeGrid.tree&&d.treeGrid.tree.height});"beforeRender"===c.type&&(d.treeGrid.collapsedNodes=e.collapsedNodes)}})}
function v(a,b){var c=this.treeGrid.mapOptionsToLevel||{},d=this.ticks,e=d[b],f;if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var g=this.treeGrid.mapOfPosToGridNode[b];(c=c[g.depth])&&(f={labels:c});e?(e.parameters.category=g.name,e.options=f,e.addLabel()):d[b]=new x(this,b,void 0,void 0,{category:g.name,tickmarkOffset:g.tickmarkOffset,options:f})}else a.apply(this,Array.prototype.slice.call(arguments,1))}function w(a){var b=this.options;b=(b=b&&b.labels)&&n(b.indentation)?
b.indentation:0;var c=a.apply(this,Array.prototype.slice.call(arguments,1));if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var d=this.treeGrid.mapOfPosToGridNode[-1].height||0;c.width+=b*(d-1)}return c}function C(b,c,d){var e=this,f="treegrid"===d.type;e.treeGrid||(e.treeGrid=new I(e));f&&(m(c,"beforeRender",t),m(c,"beforeRedraw",t),m(c,"addSeries",function(a){a.options.data&&(a=q(a.options.data,d.uniqueNames||!1,1),e.treeGrid.collapsedNodes=(e.treeGrid.collapsedNodes||[]).concat(a.collapsedNodes))}),
m(e,"foundExtremes",function(){e.treeGrid.collapsedNodes&&e.treeGrid.collapsedNodes.forEach(function(a){var b=e.treeGrid.collapse(a);e.brokenAxis&&(e.brokenAxis.setBreaks(b,!1),e.treeGrid.collapsedNodes&&(e.treeGrid.collapsedNodes=e.treeGrid.collapsedNodes.filter(function(b){return a.collapseStart!==b.collapseStart||a.collapseEnd!==b.collapseEnd})))})}),m(e,"afterBreaks",function(){var a;"yAxis"===e.coll&&!e.staticScale&&(null===(a=e.chart.options.chart)||void 0===a?0:a.height)&&(e.isDirty=!0)}),
d=a({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},d,{reversed:!0,grid:{columns:void 0}}));b.apply(e,[c,d]);f&&(e.hasNames=!0,e.options.showLastLabel=!0)}function z(a){var b=this.options;"treegrid"===b.type?(this.min=g(this.userMin,b.min,this.dataMin),this.max=g(this.userMax,b.max,this.dataMax),D(this,"foundExtremes"),this.setAxisTranslation(),this.tickmarkOffset=.5,
this.tickInterval=1,this.tickPositions=this.treeGrid.mapOfPosToGridNode?this.treeGrid.getTickPositions():[]):a.apply(this,Array.prototype.slice.call(arguments,1))}var H=!1;c.compose=function(a){H||(h(a.prototype,"generateTick",v),h(a.prototype,"getMaxLabelDimensions",w),h(a.prototype,"init",C),h(a.prototype,"setTickInterval",z),p.compose(x),H=!0)};var I=function(){function a(a){this.axis=a}a.prototype.setCollapsedStatus=function(a){var b=this.axis,c=b.chart;b.series.forEach(function(b){var d=b.options.data;
if(a.id&&d){var e=c.get(a.id);b=d[b.data.indexOf(e)];e&&b&&(e.collapsed=a.collapsed,b.collapsed=a.collapsed)}})};a.prototype.collapse=function(a){var b=this.axis,c=b.options.breaks||[],e=d(a,b.max);c.push(e);a.collapsed=!0;b.treeGrid.setCollapsedStatus(a);return c};a.prototype.expand=function(a){var b=this.axis,c=b.options.breaks||[],e=d(a,b.max);a.collapsed=!1;b.treeGrid.setCollapsedStatus(a);return c.reduce(function(a,b){b.to===e.to&&b.from===e.from||a.push(b);return a},[])};a.prototype.getTickPositions=
function(){var a=this.axis,b=Math.floor(a.min/a.tickInterval)*a.tickInterval,c=Math.ceil(a.max/a.tickInterval)*a.tickInterval;return Object.keys(a.treeGrid.mapOfPosToGridNode||{}).reduce(function(d,e){e=+e;!(e>=b&&e<=c)||a.brokenAxis&&a.brokenAxis.isInAnyBreak(e)||d.push(e);return d},[])};a.prototype.isCollapsed=function(a){var b=this.axis,c=b.options.breaks||[],e=d(a,b.max);return c.some(function(a){return a.from===e.from&&a.to===e.to})};a.prototype.toggleCollapse=function(a){return this.isCollapsed(a)?
this.expand(a):this.collapse(a)};return a}();c.Additions=I})(d||(d={}));t.prototype.utils={getNode:u.getNode};d.compose(t);return d});C(b,"masters/modules/treegrid.src.js",[],function(){})});
//# sourceMappingURL=treegrid.js.map