/*
 Highcharts JS v8.2.2 (2020-11-23)

 (c) 2014-2019 Highsoft AS
 Authors: Jon Arild Nygard / Oystein Moseng

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/treemap",["highcharts"],function(p){b(p);b.Highcharts=p;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function p(b,d,k,z){b.hasOwnProperty(d)||(b[d]=z.apply(null,k))}b=b?b._modules:{};p(b,"Mixins/ColorMapSeries.js",[b["Core/Globals.js"],b["Core/Series/Point.js"],b["Core/Utilities.js"]],function(b,d,k){var z=k.defined;
return{colorMapPointMixin:{dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value},setState:function(b){d.prototype.setState.call(this,b);this.graphic&&this.graphic.attr({zIndex:"hover"===b?1:0})}},colorMapSeriesMixin:{pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:b.noop,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:b.seriesTypes.column.prototype.pointAttribs,
colorAttribs:function(b){var k={};z(b.color)&&(k[this.colorProp||"fill"]=b.color);return k}}}});p(b,"Mixins/DrawPoint.js",[],function(){var b=function(b){return"function"===typeof b},d=function(k){var d,v=this,q=v.graphic,g=k.animatableAttribs,w=k.onComplete,n=k.css,f=k.renderer,m=null===(d=v.series)||void 0===d?void 0:d.options.animation;if(v.shouldDraw())q||(v.graphic=q=f[k.shapeType](k.shapeArgs).add(k.group)),q.css(n).attr(k.attribs).animate(g,k.isNew?!1:m,w);else if(q){var A=function(){v.graphic=
q=q.destroy();b(w)&&w()};Object.keys(g).length?q.animate(g,void 0,function(){A()}):A()}};return{draw:d,drawPoint:function(b){(b.attribs=b.attribs||{})["class"]=this.getClassName();d.call(this,b)},isFn:b}});p(b,"Mixins/TreeSeries.js",[b["Core/Color/Color.js"],b["Core/Utilities.js"]],function(b,d){var k=d.extend,p=d.isArray,v=d.isNumber,q=d.isObject,g=d.merge,w=d.pick;return{getColor:function(n,f){var m=f.index,k=f.mapOptionsToLevel,d=f.parentColor,q=f.parentColorIndex,g=f.series,B=f.colors,G=f.siblings,
r=g.points,v=g.chart.options.chart,x;if(n){r=r[n.i];n=k[n.level]||{};if(k=r&&n.colorByPoint){var p=r.index%(B?B.length:v.colorCount);var C=B&&B[p]}if(!g.chart.styledMode){B=r&&r.options.color;v=n&&n.color;if(x=d)x=(x=n&&n.colorVariation)&&"brightness"===x.key?b.parse(d).brighten(m/G*x.to).get():d;x=w(B,v,C,x,g.color)}var z=w(r&&r.options.colorIndex,n&&n.colorIndex,p,q,f.colorIndex)}return{color:x,colorIndex:z}},getLevelOptions:function(b){var f=null;if(q(b)){f={};var m=v(b.from)?b.from:1;var d=b.levels;
var n={};var w=q(b.defaults)?b.defaults:{};p(d)&&(n=d.reduce(function(b,f){if(q(f)&&v(f.level)){var d=g({},f);var n="boolean"===typeof d.levelIsConstant?d.levelIsConstant:w.levelIsConstant;delete d.levelIsConstant;delete d.level;f=f.level+(n?0:m-1);q(b[f])?k(b[f],d):b[f]=d}return b},{}));d=v(b.to)?b.to:1;for(b=0;b<=d;b++)f[b]=g({},w,q(n[b])?n[b]:{})}return f},setTreeValues:function A(b,d){var f=d.before,m=d.idRoot,q=d.mapIdToNode[m],g=d.points[b.i],v=g&&g.options||{},r=0,p=[];k(b,{levelDynamic:b.level-
(("boolean"===typeof d.levelIsConstant?d.levelIsConstant:1)?0:q.level),name:w(g&&g.name,""),visible:m===b.id||("boolean"===typeof d.visible?d.visible:!1)});"function"===typeof f&&(b=f(b,d));b.children.forEach(function(f,m){var g=k({},d);k(g,{index:m,siblings:b.children.length,visible:b.visible});f=A(f,g);p.push(f);f.visible&&(r+=f.val)});b.visible=0<r||b.visible;f=w(v.value,r);k(b,{children:p,childrenTotal:r,isLeaf:b.visible&&!r,val:f});return b},updateRootId:function(b){if(q(b)){var d=q(b.options)?
b.options:{};d=w(b.rootNode,d.rootId,"");q(b.userOptions)&&(b.userOptions.rootId=d);b.rootNode=d}return d}}});p(b,"Series/TreemapSeries.js",[b["Core/Series/Series.js"],b["Core/Color/Color.js"],b["Mixins/ColorMapSeries.js"],b["Mixins/DrawPoint.js"],b["Core/Globals.js"],b["Mixins/LegendSymbol.js"],b["Series/Line/LineSeries.js"],b["Core/Color/Palette.js"],b["Core/Series/Point.js"],b["Mixins/TreeSeries.js"],b["Core/Utilities.js"]],function(b,d,k,p,v,q,g,w,n,f,m){var A=b.seriesTypes,z=d.parse,K=k.colorMapSeriesMixin;
d=v.noop;var N=f.getColor,B=f.getLevelOptions,G=f.updateRootId,r=m.addEvent,O=m.correctFloat,x=m.defined,P=m.error,C=m.extend,Q=m.fireEvent,L=m.isArray,M=m.isNumber,R=m.isObject,H=m.isString,E=m.merge,S=m.objectEach,y=m.pick,T=m.stableSort,U=function(a,c,e){e=e||this;S(a,function(b,l){c.call(e,b,l,a)})},F=function(a,c,e){e=e||this;a=c.call(e,a);!1!==a&&F(a,c,e)},I=!1;b.seriesType("treemap","scatter",{allowTraversingTree:!1,animationLimit:250,showInLegend:!1,marker:void 0,colorByPoint:!1,dataLabels:{defer:!1,
enabled:!0,formatter:function(){var a=this&&this.point?this.point:{};return H(a.name)?a.name:""},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:"",pointFormat:"<b>{point.name}</b>: {point.value}<br/>"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,drillUpButton:{position:{align:"right",x:-10,y:10}},traverseUpButton:{position:{align:"right",x:-10,y:10}},borderColor:w.neutralColor10,borderWidth:1,colorKey:"colorValue",
opacity:.15,states:{hover:{borderColor:w.neutralColor40,brightness:A.heatmap?0:.1,halo:!1,opacity:.75,shadow:!1}}},{pointArrayMap:["value"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:d,parallelArrays:["x","y","value","colorValue"],colorKey:"colorValue",trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(a,c){a=L(a)?a:[];var e=L(c)?c:[];c=a.reduce(function(a,c,e){c=y(c.parent,"");"undefined"===typeof a[c]&&(a[c]=[]);a[c].push(e);return a},{"":[]});U(c,function(a,c,b){""!==c&&
-1===e.indexOf(c)&&(a.forEach(function(a){b[""].push(a)}),delete b[c])});return c},getTree:function(){var a=this.data.map(function(a){return a.id});a=this.getListOfParents(this.data,a);this.nodeMap={};return this.buildNode("",-1,0,a)},hasData:function(){return!!this.processedXData.length},init:function(a,c){K&&(this.colorAttribs=K.colorAttribs);var e=r(this,"setOptions",function(a){a=a.userOptions;x(a.allowDrillToNode)&&!x(a.allowTraversingTree)&&(a.allowTraversingTree=a.allowDrillToNode,delete a.allowDrillToNode);
x(a.drillUpButton)&&!x(a.traverseUpButton)&&(a.traverseUpButton=a.drillUpButton,delete a.drillUpButton)});g.prototype.init.call(this,a,c);delete this.opacity;this.eventsToUnbind.push(e);this.options.allowTraversingTree&&this.eventsToUnbind.push(r(this,"click",this.onClickDrillToNode))},buildNode:function(a,c,e,b,l){var d=this,h=[],u=d.points[c],J=0,t;(b[a]||[]).forEach(function(c){t=d.buildNode(d.points[c].id,c,e+1,b,a);J=Math.max(t.height+1,J);h.push(t)});c={id:a,i:c,children:h,height:J,level:e,
parent:l,visible:!1};d.nodeMap[c.id]=c;u&&(u.node=c);return c},setTreeValues:function(a){var c=this,e=c.options,b=c.nodeMap[c.rootNode];e="boolean"===typeof e.levelIsConstant?e.levelIsConstant:!0;var l=0,d=[],h=c.points[a.i];a.children.forEach(function(a){a=c.setTreeValues(a);d.push(a);a.ignore||(l+=a.val)});T(d,function(a,c){return(a.sortIndex||0)-(c.sortIndex||0)});var D=y(h&&h.options.value,l);h&&(h.value=D);C(a,{children:d,childrenTotal:l,ignore:!(y(h&&h.visible,!0)&&0<D),isLeaf:a.visible&&!l,
levelDynamic:a.level-(e?0:b.level),name:y(h&&h.name,""),sortIndex:y(h&&h.sortIndex,-D),val:D});return a},calculateChildrenAreas:function(a,c){var b=this,d=b.options,l=b.mapOptionsToLevel[a.level+1],V=y(b[l&&l.layoutAlgorithm]&&l.layoutAlgorithm,d.layoutAlgorithm),h=d.alternateStartingDirection,D=[];a=a.children.filter(function(a){return!a.ignore});l&&l.layoutStartingDirection&&(c.direction="vertical"===l.layoutStartingDirection?0:1);D=b[V](c,a);a.forEach(function(a,e){e=D[e];a.values=E(e,{val:a.childrenTotal,
direction:h?1-c.direction:c.direction});a.pointValues=E(e,{x:e.x/b.axisRatio,y:100-e.y-e.height,width:e.width/b.axisRatio});a.children.length&&b.calculateChildrenAreas(a,a.values)})},setPointValues:function(){var a=this,c=a.xAxis,b=a.yAxis,d=a.chart.styledMode;a.points.forEach(function(e){var l=e.node,h=l.pointValues;l=l.visible;if(h&&l){l=h.height;var u=h.width,f=h.x,t=h.y,k=d?0:(a.pointAttribs(e)["stroke-width"]||0)%2/2;h=Math.round(c.toPixels(f,!0))-k;u=Math.round(c.toPixels(f+u,!0))-k;f=Math.round(b.toPixels(t,
!0))-k;l=Math.round(b.toPixels(t+l,!0))-k;e.shapeArgs={x:Math.min(h,u),y:Math.min(f,l),width:Math.abs(u-h),height:Math.abs(l-f)};e.plotX=e.shapeArgs.x+e.shapeArgs.width/2;e.plotY=e.shapeArgs.y+e.shapeArgs.height/2}else delete e.plotX,delete e.plotY})},setColorRecursive:function(a,c,b,d,l){var e=this,h=e&&e.chart;h=h&&h.options&&h.options.colors;if(a){var u=N(a,{colors:h,index:d,mapOptionsToLevel:e.mapOptionsToLevel,parentColor:c,parentColorIndex:b,series:e,siblings:l});if(c=e.points[a.i])c.color=
u.color,c.colorIndex=u.colorIndex;(a.children||[]).forEach(function(c,b){e.setColorRecursive(c,u.color,u.colorIndex,b,a.children.length)})}},algorithmGroup:function(a,c,b,d){this.height=a;this.width=c;this.plot=d;this.startDirection=this.direction=b;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,c){return Math.max(a/c,c/a)}};this.addElement=function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===
this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)};this.reset=function(){this.lW=this.nW=
0;this.elArr=[];this.total=0}},algorithmCalcPoints:function(a,c,b,d){var e,u,h,f,k=b.lW,t=b.lH,g=b.plot,m=0,q=b.elArr.length-1;if(c)k=b.nW,t=b.nH;else var n=b.elArr[b.elArr.length-1];b.elArr.forEach(function(a){if(c||m<q)0===b.direction?(e=g.x,u=g.y,h=k,f=a/h):(e=g.x,u=g.y,f=t,h=a/f),d.push({x:e,y:u,width:h,height:O(f)}),0===b.direction?g.y+=f:g.x+=h;m+=1});b.reset();0===b.direction?b.width-=k:b.height-=t;g.y=g.parent.y+(g.parent.height-b.height);g.x=g.parent.x+(g.parent.width-b.width);a&&(b.direction=
1-b.direction);c||b.addElement(n)},algorithmLowAspectRatio:function(a,c,b){var e=[],d=this,f,h={x:c.x,y:c.y,parent:c},g=0,k=b.length-1,t=new this.algorithmGroup(c.height,c.width,c.direction,h);b.forEach(function(b){f=b.val/c.val*c.height*c.width;t.addElement(f);t.lP.nR>t.lP.lR&&d.algorithmCalcPoints(a,!1,t,e,h);g===k&&d.algorithmCalcPoints(a,!0,t,e,h);g+=1});return e},algorithmFill:function(a,c,b){var e=[],d,f=c.direction,h=c.x,g=c.y,k=c.width,t=c.height,m,q,n,p;b.forEach(function(b){d=b.val/c.val*
c.height*c.width;m=h;q=g;0===f?(p=t,n=d/p,k-=n,h+=n):(n=k,p=d/n,t-=p,g+=p);e.push({x:m,y:q,width:n,height:p});a&&(f=1-f)});return e},strip:function(a,b){return this.algorithmLowAspectRatio(!1,a,b)},squarified:function(a,b){return this.algorithmLowAspectRatio(!0,a,b)},sliceAndDice:function(a,b){return this.algorithmFill(!0,a,b)},stripes:function(a,b){return this.algorithmFill(!1,a,b)},translate:function(){var a=this,b=a.options,e=G(a);g.prototype.translate.call(a);var d=a.tree=a.getTree();var l=a.nodeMap[e];
a.renderTraverseUpButton(e);a.mapOptionsToLevel=B({from:l.level+1,levels:b.levels,to:d.height,defaults:{levelIsConstant:a.options.levelIsConstant,colorByPoint:b.colorByPoint}});""===e||l&&l.children.length||(a.setRootNode("",!1),e=a.rootNode,l=a.nodeMap[e]);F(a.nodeMap[a.rootNode],function(b){var c=!1,e=b.parent;b.visible=!0;if(e||""===e)c=a.nodeMap[e];return c});F(a.nodeMap[a.rootNode].children,function(a){var b=!1;a.forEach(function(a){a.visible=!0;a.children.length&&(b=(b||[]).concat(a.children))});
return b});a.setTreeValues(d);a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=e={x:0,y:0,width:100,height:100};a.nodeMap[""].values=e=E(e,{width:e.width*a.axisRatio,direction:"vertical"===b.layoutStartingDirection?0:1,val:d.val});a.calculateChildrenAreas(d,e);a.colorAxis||b.colorByPoint||a.setColorRecursive(a.tree);b.allowTraversingTree&&(b=l.pointValues,a.xAxis.setExtremes(b.x,b.x+b.width,!1),a.yAxis.setExtremes(b.y,b.y+b.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()},
drawDataLabels:function(){var a=this,b=a.mapOptionsToLevel,e,d;a.points.filter(function(a){return a.node.visible}).forEach(function(c){d=b[c.node.level];e={style:{}};c.node.isLeaf||(e.enabled=!1);d&&d.dataLabels&&(e=E(e,d.dataLabels),a._hasPointLabels=!0);c.shapeArgs&&(e.style.width=c.shapeArgs.width,c.dataLabel&&c.dataLabel.css({width:c.shapeArgs.width+"px"}));c.dlOptions=E(e,c.options.dataLabels)});g.prototype.drawDataLabels.call(this)},alignDataLabel:function(a,b,e){var c=e.style;!x(c.textOverflow)&&
b.text&&b.getBBox().width>b.text.textWidth&&b.css({textOverflow:"ellipsis",width:c.width+="px"});A.column.prototype.alignDataLabel.apply(this,arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})},pointAttribs:function(a,b){var c=R(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},d=a&&c[a.node.level]||{};c=this.options;var f=b&&c.states[b]||{},g=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||d.borderColor||f.borderColor||c.borderColor,"stroke-width":y(a&&a.borderWidth,d.borderWidth,
f.borderWidth,c.borderWidth),dashstyle:a&&a.borderDashStyle||d.borderDashStyle||f.borderDashStyle||c.borderDashStyle,fill:a&&a.color||this.color};-1!==g.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==g.indexOf("highcharts-internal-node-interactive")?(b=y(f.opacity,c.opacity),a.fill=z(a.fill).setOpacity(b).get(),a.cursor="pointer"):-1!==g.indexOf("highcharts-internal-node")?a.fill="none":b&&(a.fill=z(a.fill).brighten(f.brightness).get());return a},drawPoints:function(){var a=
this,b=a.chart,e=b.renderer,d=b.styledMode,f=a.options,g=d?{}:f.shadow,h=f.borderRadius,k=b.pointCount<f.animationLimit,n=f.allowTraversingTree;a.points.forEach(function(b){var c=b.node.levelDynamic,l={},m={},q={},p="level-group-"+b.node.level,u=!!b.graphic,t=k&&u,r=b.shapeArgs;b.shouldDraw()&&(h&&(m.r=h),E(!0,t?l:m,u?r:{},d?{}:a.pointAttribs(b,b.selected?"select":void 0)),a.colorAttribs&&d&&C(q,a.colorAttribs(b)),a[p]||(a[p]=e.g(p).attr({zIndex:1E3-(c||0)}).add(a.group),a[p].survive=!0));b.draw({animatableAttribs:l,
attribs:m,css:q,group:a[p],renderer:e,shadow:g,shapeArgs:r,shapeType:"rect"});n&&b.graphic&&(b.drillId=f.interactByLeaf?a.drillToByLeaf(b):a.drillToByGroup(b))})},onClickDrillToNode:function(a){var b=(a=a.point)&&a.drillId;H(b)&&(a.setState(""),this.setRootNode(b,!0,{trigger:"click"}))},drillToByGroup:function(a){var b=!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(b=a.id);return b},drillToByLeaf:function(a){var b=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!b;)a=
this.nodeMap[a.parent],a.parent===this.rootNode&&(b=a.id);return b},drillUp:function(){var a=this.nodeMap[this.rootNode];a&&H(a.parent)&&this.setRootNode(a.parent,!0,{trigger:"traverseUpButton"})},drillToNode:function(a,b){P(32,!1,void 0,{"treemap.drillToNode":"use treemap.setRootNode"});this.setRootNode(a,b)},setRootNode:function(a,b,e){a=C({newRootId:a,previousRootId:this.rootNode,redraw:y(b,!0),series:this},e);Q(this,"setRootNode",a,function(a){var b=a.series;b.idPreviousRoot=a.previousRootId;
b.rootNode=a.newRootId;b.isDirty=!0;a.redraw&&b.chart.redraw()})},renderTraverseUpButton:function(a){var b=this,e=b.options.traverseUpButton,d=y(e.text,b.nodeMap[a].name,"\u25c1 Back");if(""===a||b.is("sunburst")&&1===b.tree.children.length&&a===b.tree.children[0].id)b.drillUpButton&&(b.drillUpButton=b.drillUpButton.destroy());else if(this.drillUpButton)this.drillUpButton.placed=!1,this.drillUpButton.attr({text:d}).align();else{var f=(a=e.theme)&&a.states;this.drillUpButton=this.chart.renderer.button(d,
0,0,function(){b.drillUp()},a,f&&f.hover,f&&f.select).addClass("highcharts-drillup-button").attr({align:e.position.align,zIndex:7}).add().align(e.position,!1,e.relativeTo||"plotBox")}},buildKDTree:d,drawLegendSymbol:q.drawRectangle,getExtremes:function(){var a=g.prototype.getExtremes.call(this,this.colorValueData),b=a.dataMax;this.valueMin=a.dataMin;this.valueMax=b;return g.prototype.getExtremes.call(this)},getExtremesFromAll:!0,setState:function(a){this.options.inactiveOtherPoints=!0;g.prototype.setState.call(this,
a,!1);this.options.inactiveOtherPoints=!1},utils:{recursive:F}},{draw:p.drawPoint,setVisible:A.pie.prototype.pointClass.prototype.setVisible,getClassName:function(){var a=n.prototype.getClassName.call(this),b=this.series,d=b.options;this.node.level<=b.nodeMap[b.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||y(d.interactByLeaf,!d.allowTraversingTree)?this.node.isLeaf||(a+=" highcharts-internal-node"):a+=" highcharts-internal-node-interactive";return a},isValid:function(){return!(!this.id&&
!M(this.value))},setState:function(a){n.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})},shouldDraw:function(){return M(this.plotY)&&null!==this.y}});r(g,"afterBindAxes",function(){var a=this.xAxis,b=this.yAxis;if(a&&b)if(this.is("treemap")){var d={endOnTick:!1,gridLineWidth:0,lineWidth:0,min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};C(b.options,d);C(a.options,d);I=!0}else I&&(b.setOptions(b.userOptions),
a.setOptions(a.userOptions),I=!1)});""});p(b,"masters/modules/treemap.src.js",[],function(){})});
//# sourceMappingURL=treemap.js.map