/*
 Highcharts JS v8.2.2 (2020-11-23)

 3D features for Highcharts JS

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/highcharts-3d",["highcharts"],function(E){b(E);b.Highcharts=E;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function E(b,r,l,v){b.hasOwnProperty(r)||(b[r]=v.apply(null,l))}b=b?b._modules:{};E(b,"Extensions/Math3D.js",[b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,r){function l(d,c,a){c=0<a&&a<Number.POSITIVE_INFINITY?
a/(d.z+c.z+a):1;return{x:d.x*c,y:d.y*c}}function v(d,c,a,q){var p=c.options.chart.options3d,m=y(q,a?c.inverted:!1),e={x:c.plotWidth/2,y:c.plotHeight/2,z:p.depth/2,vd:y(p.depth,1)*y(p.viewDistance,0)},f=c.scale3d||1;q=u*p.beta*(m?-1:1);p=u*p.alpha*(m?-1:1);var t=Math.cos(p),n=Math.cos(-q),C=Math.sin(p),b=Math.sin(-q);a||(e.x+=c.plotLeft,e.y+=c.plotTop);return d.map(function(a){var c=(m?a.y:a.x)-e.x;var h=(m?a.x:a.y)-e.y;a=(a.z||0)-e.z;c={x:n*c-b*a,y:-C*b*c+t*h-n*C*a,z:t*b*c+C*h+t*n*a};h=l(c,e,e.vd);
h.x=h.x*f+e.x;h.y=h.y*f+e.y;h.z=c.z*f+e.z;return{x:m?h.y:h.x,y:m?h.x:h.y,z:h.z}})}function d(d,c){var a=c.options.chart.options3d,q=c.plotWidth/2;c=c.plotHeight/2;a=y(a.depth,1)*y(a.viewDistance,0)+a.depth;return Math.sqrt(Math.pow(q-y(d.plotX,d.x),2)+Math.pow(c-y(d.plotY,d.y),2)+Math.pow(a-y(d.plotZ,d.z),2))}function x(d){var c=0,a;for(a=0;a<d.length;a++){var q=(a+1)%d.length;c+=d[a].x*d[q].y-d[q].x*d[a].y}return c/2}function g(d,c,a){return x(v(d,c,a))}var y=r.pick,u=b.deg2rad;b.perspective3D=l;
b.perspective=v;b.pointCameraDistance=d;b.shapeArea=x;b.shapeArea3d=g;return{perspective:v,perspective3D:l,pointCameraDistance:d,shapeArea:x,shapeArea3D:g}});E(b,"Core/Renderer/SVG/SVGElement3D.js",[b["Core/Color/Color.js"],b["Core/Renderer/SVG/SVGElement.js"],b["Core/Utilities.js"]],function(b,r,l){var v=b.parse,d=l.defined,x=l.merge,g=l.objectEach,y=l.pick,u;(function(b){b.base={initArgs:function(c){var a=this,d=a.renderer,b=d[a.pathType+"Path"](c),m=b.zIndexes;a.parts.forEach(function(e){a[e]=
d.path(b[e]).attr({"class":"highcharts-3d-"+e,zIndex:m[e]||0}).add(a)});a.attr({"stroke-linejoin":"round",zIndex:m.group});a.originalDestroy=a.destroy;a.destroy=a.destroyParts;a.forcedSides=b.forcedSides},singleSetterForParts:function(c,a,d,b,m,e){var f={};b=[null,null,b||"attr",m,e];var t=d&&d.zIndexes;d?(t&&t.group&&this.attr({zIndex:t.group}),g(d,function(e,a){f[a]={};f[a][c]=e;t&&(f[a].zIndex=d.zIndexes[a]||0)}),b[1]=f):(f[c]=a,b[0]=f);return this.processParts.apply(this,b)},processParts:function(c,
a,d,b,m){var e=this;e.parts.forEach(function(f){a&&(c=y(a[f],!1));if(!1!==c)e[f][d](c,b,m)});return e},destroyParts:function(){this.processParts(null,null,"destroy");return this.originalDestroy()}};b.cuboid=x(b.base,{parts:["front","top","side"],pathType:"cuboid",attr:function(c,a,b,p){if("string"===typeof c&&"undefined"!==typeof a){var m=c;c={};c[m]=a}return c.shapeArgs||d(c.x)?this.singleSetterForParts("d",null,this.renderer[this.pathType+"Path"](c.shapeArgs||c)):r.prototype.attr.call(this,c,void 0,
b,p)},animate:function(c,a,q){if(d(c.x)&&d(c.y)){c=this.renderer[this.pathType+"Path"](c);var p=c.forcedSides;this.singleSetterForParts("d",null,c,"animate",a,q);this.attr({zIndex:c.zIndexes.group});p!==this.forcedSides&&(this.forcedSides=p,b.cuboid.fillSetter.call(this,this.fill))}else r.prototype.animate.call(this,c,a,q);return this},fillSetter:function(c){this.forcedSides=this.forcedSides||[];this.singleSetterForParts("fill",null,{front:c,top:v(c).brighten(0<=this.forcedSides.indexOf("top")?0:
.1).get(),side:v(c).brighten(0<=this.forcedSides.indexOf("side")?0:-.1).get()});this.color=this.fill=c;return this}})})(u||(u={}));return u});E(b,"Core/Renderer/SVG/SVGRenderer3D.js",[b["Core/Animation/AnimationUtilities.js"],b["Core/Color/Color.js"],b["Core/Globals.js"],b["Extensions/Math3D.js"],b["Core/Renderer/SVG/SVGElement.js"],b["Core/Renderer/SVG/SVGElement3D.js"],b["Core/Renderer/SVG/SVGRenderer.js"],b["Core/Utilities.js"]],function(b,r,l,v,d,x,g,y){function u(a,e,k,c,f,d,n,b){var h=[],w=
d-f;return d>f&&d-f>Math.PI/2+.0001?(h=h.concat(u(a,e,k,c,f,f+Math.PI/2,n,b)),h=h.concat(u(a,e,k,c,f+Math.PI/2,d,n,b))):d<f&&f-d>Math.PI/2+.0001?(h=h.concat(u(a,e,k,c,f,f-Math.PI/2,n,b)),h=h.concat(u(a,e,k,c,f-Math.PI/2,d,n,b))):[["C",a+k*Math.cos(f)-k*F*w*Math.sin(f)+n,e+c*Math.sin(f)+c*F*w*Math.cos(f)+b,a+k*Math.cos(d)+k*F*w*Math.sin(d)+n,e+c*Math.sin(d)-c*F*w*Math.cos(d)+b,a+k*Math.cos(d)+n,e+c*Math.sin(d)+b]]}var A=b.animObject,c=r.parse,a=l.charts,q=l.deg2rad,p=v.perspective,m=v.shapeArea,e=
y.defined,f=y.extend,t=y.merge,n=y.pick,C=Math.cos,H=Math.sin,J=Math.PI,F=4*(Math.sqrt(2)-1)/3/(J/2);g.prototype.elements3d=x;g.prototype.toLinePath=function(a,e){var c=[];a.forEach(function(a){c.push(["L",a.x,a.y])});a.length&&(c[0][0]="M",e&&c.push(["Z"]));return c};g.prototype.toLineSegments=function(a){var e=[],c=!0;a.forEach(function(a){e.push(c?["M",a.x,a.y]:["L",a.x,a.y]);c=!c});return e};g.prototype.face3d=function(c){var f=this,k=this.createElement("path");k.vertexes=[];k.insidePlotArea=
!1;k.enabled=!0;k.attr=function(c){if("object"===typeof c&&(e(c.enabled)||e(c.vertexes)||e(c.insidePlotArea))){this.enabled=n(c.enabled,this.enabled);this.vertexes=n(c.vertexes,this.vertexes);this.insidePlotArea=n(c.insidePlotArea,this.insidePlotArea);delete c.enabled;delete c.vertexes;delete c.insidePlotArea;var k=p(this.vertexes,a[f.chartIndex],this.insidePlotArea),h=f.toLinePath(k,!0);k=m(k);k=this.enabled&&0<k?"visible":"hidden";c.d=h;c.visibility=k}return d.prototype.attr.apply(this,arguments)};
k.animate=function(c){if("object"===typeof c&&(e(c.enabled)||e(c.vertexes)||e(c.insidePlotArea))){this.enabled=n(c.enabled,this.enabled);this.vertexes=n(c.vertexes,this.vertexes);this.insidePlotArea=n(c.insidePlotArea,this.insidePlotArea);delete c.enabled;delete c.vertexes;delete c.insidePlotArea;var k=p(this.vertexes,a[f.chartIndex],this.insidePlotArea),h=f.toLinePath(k,!0);k=m(k);k=this.enabled&&0<k?"visible":"hidden";c.d=h;this.attr("visibility",k)}return d.prototype.animate.apply(this,arguments)};
return k.attr(c)};g.prototype.polyhedron=function(a){var c=this,k=this.g(),f=k.destroy;this.styledMode||k.attr({"stroke-linejoin":"round"});k.faces=[];k.destroy=function(){for(var a=0;a<k.faces.length;a++)k.faces[a].destroy();return f.call(this)};k.attr=function(a,f,h,n){if("object"===typeof a&&e(a.faces)){for(;k.faces.length>a.faces.length;)k.faces.pop().destroy();for(;k.faces.length<a.faces.length;)k.faces.push(c.face3d().add(k));for(var b=0;b<a.faces.length;b++)c.styledMode&&delete a.faces[b].fill,
k.faces[b].attr(a.faces[b],null,h,n);delete a.faces}return d.prototype.attr.apply(this,arguments)};k.animate=function(a,e,f){if(a&&a.faces){for(;k.faces.length>a.faces.length;)k.faces.pop().destroy();for(;k.faces.length<a.faces.length;)k.faces.push(c.face3d().add(k));for(var h=0;h<a.faces.length;h++)k.faces[h].animate(a.faces[h],e,f);delete a.faces}return d.prototype.animate.apply(this,arguments)};return k.attr(a)};g.prototype.element3d=function(a,c){var e=this.g();f(e,this.elements3d[a]);e.initArgs(c);
return e};g.prototype.cuboid=function(a){return this.element3d("cuboid",a)};g.prototype.cuboidPath=function(c){function e(a){return 0===b&&1<a&&6>a?{x:D[a].x,y:D[a].y+10,z:D[a].z}:D[0].x===D[7].x&&4<=a?{x:D[a].x+10,y:D[a].y,z:D[a].z}:0===C&&2>a||5<a?{x:D[a].x,y:D[a].y,z:D[a].z+10}:D[a]}function f(a){return D[a]}var d=c.x,n=c.y,h=c.z||0,b=c.height,t=c.width,C=c.depth,w=a[this.chartIndex],z=w.options.chart.options3d.alpha,G=0,D=[{x:d,y:n,z:h},{x:d+t,y:n,z:h},{x:d+t,y:n+b,z:h},{x:d,y:n+b,z:h},{x:d,y:n+
b,z:h+C},{x:d+t,y:n+b,z:h+C},{x:d+t,y:n,z:h+C},{x:d,y:n,z:h+C}],L=[];D=p(D,w,c.insidePlotArea);var B=function(a,c,z){var d=[[],-1],k=a.map(f),n=c.map(f);a=a.map(e);c=c.map(e);0>m(k)?d=[k,0]:0>m(n)?d=[n,1]:z&&(L.push(z),d=0>m(a)?[k,0]:0>m(c)?[n,1]:[k,0]);return d};var I=B([3,2,1,0],[7,6,5,4],"front");c=I[0];var q=I[1];I=B([1,6,7,0],[4,5,2,3],"top");t=I[0];var H=I[1];I=B([1,2,5,6],[0,7,4,3],"side");B=I[0];I=I[1];1===I?G+=1E6*(w.plotWidth-d):I||(G+=1E6*d);G+=10*(!H||0<=z&&180>=z||360>z&&357.5<z?w.plotHeight-
n:10+n);1===q?G+=100*h:q||(G+=100*(1E3-h));return{front:this.toLinePath(c,!0),top:this.toLinePath(t,!0),side:this.toLinePath(B,!0),zIndexes:{group:Math.round(G)},forcedSides:L,isFront:q,isTop:H}};g.prototype.arc3d=function(a){function e(a){var c=!1,e={},f;a=t(a);for(f in a)-1!==b.indexOf(f)&&(e[f]=a[f],delete a[f],c=!0);return c?[e,a]:!1}var k=this.g(),h=k.renderer,b="x y r innerR start end depth".split(" ");a=t(a);a.alpha=(a.alpha||0)*q;a.beta=(a.beta||0)*q;k.top=h.path();k.side1=h.path();k.side2=
h.path();k.inn=h.path();k.out=h.path();k.onAdd=function(){var a=k.parentGroup,c=k.attr("class");k.top.add(k);["out","inn","side1","side2"].forEach(function(e){k[e].attr({"class":c+" highcharts-3d-side"}).add(a)})};["addClass","removeClass"].forEach(function(a){k[a]=function(){var c=arguments;["top","out","inn","side1","side2"].forEach(function(e){k[e][a].apply(k[e],c)})}});k.setPaths=function(a){var c=k.renderer.arc3dPath(a),e=100*c.zTop;k.attribs=a;k.top.attr({d:c.top,zIndex:c.zTop});k.inn.attr({d:c.inn,
zIndex:c.zInn});k.out.attr({d:c.out,zIndex:c.zOut});k.side1.attr({d:c.side1,zIndex:c.zSide1});k.side2.attr({d:c.side2,zIndex:c.zSide2});k.zIndex=e;k.attr({zIndex:e});a.center&&(k.top.setRadialReference(a.center),delete a.center)};k.setPaths(a);k.fillSetter=function(a){var e=c(a).brighten(-.1).get();this.fill=a;this.side1.attr({fill:e});this.side2.attr({fill:e});this.inn.attr({fill:e});this.out.attr({fill:e});this.top.attr({fill:a});return this};["opacity","translateX","translateY","visibility"].forEach(function(a){k[a+
"Setter"]=function(a,c){k[c]=a;["out","inn","side1","side2","top"].forEach(function(e){k[e].attr(c,a)})}});k.attr=function(a){var c;if("object"===typeof a&&(c=e(a))){var n=c[0];arguments[0]=c[1];f(k.attribs,n);k.setPaths(k.attribs)}return d.prototype.attr.apply(k,arguments)};k.animate=function(a,c,f){var h=this.attribs,b="data-"+Math.random().toString(26).substring(2,9);delete a.center;delete a.z;delete a.alpha;delete a.beta;var z=A(n(c,this.renderer.globalAnimation));if(z.duration){c=e(a);k[b]=0;
a[b]=1;k[b+"Setter"]=l.noop;if(c){var G=c[0];z.step=function(a,c){function e(a){return h[a]+(n(G[a],h[a])-h[a])*c.pos}c.prop===b&&c.elem.setPaths(t(h,{x:e("x"),y:e("y"),r:e("r"),innerR:e("innerR"),start:e("start"),end:e("end"),depth:e("depth")}))}}c=z}return d.prototype.animate.call(this,a,c,f)};k.destroy=function(){this.top.destroy();this.out.destroy();this.inn.destroy();this.side1.destroy();this.side2.destroy();return d.prototype.destroy.call(this)};k.hide=function(){this.top.hide();this.out.hide();
this.inn.hide();this.side1.hide();this.side2.hide()};k.show=function(a){this.top.show(a);this.out.show(a);this.inn.show(a);this.side1.show(a);this.side2.show(a)};return k};g.prototype.arc3dPath=function(a){function c(a){a%=2*Math.PI;a>Math.PI&&(a=2*Math.PI-a);return a}var e=a.x,f=a.y,d=a.start,n=a.end-.00001,b=a.r,h=a.innerR||0,t=a.depth||0,w=a.alpha,z=a.beta,G=Math.cos(d),D=Math.sin(d);a=Math.cos(n);var m=Math.sin(n),B=b*Math.cos(z);b*=Math.cos(w);var q=h*Math.cos(z),p=h*Math.cos(w);h=t*Math.sin(z);
var g=t*Math.sin(w);t=[["M",e+B*G,f+b*D]];t=t.concat(u(e,f,B,b,d,n,0,0));t.push(["L",e+q*a,f+p*m]);t=t.concat(u(e,f,q,p,n,d,0,0));t.push(["Z"]);var A=0<z?Math.PI/2:0;z=0<w?0:Math.PI/2;A=d>-A?d:n>-A?-A:d;var F=n<J-z?n:d<J-z?J-z:n,l=2*J-z;w=[["M",e+B*C(A),f+b*H(A)]];w=w.concat(u(e,f,B,b,A,F,0,0));n>l&&d<l?(w.push(["L",e+B*C(F)+h,f+b*H(F)+g]),w=w.concat(u(e,f,B,b,F,l,h,g)),w.push(["L",e+B*C(l),f+b*H(l)]),w=w.concat(u(e,f,B,b,l,n,0,0)),w.push(["L",e+B*C(n)+h,f+b*H(n)+g]),w=w.concat(u(e,f,B,b,n,l,h,g)),
w.push(["L",e+B*C(l),f+b*H(l)]),w=w.concat(u(e,f,B,b,l,F,0,0))):n>J-z&&d<J-z&&(w.push(["L",e+B*Math.cos(F)+h,f+b*Math.sin(F)+g]),w=w.concat(u(e,f,B,b,F,n,h,g)),w.push(["L",e+B*Math.cos(n),f+b*Math.sin(n)]),w=w.concat(u(e,f,B,b,n,F,0,0)));w.push(["L",e+B*Math.cos(F)+h,f+b*Math.sin(F)+g]);w=w.concat(u(e,f,B,b,F,A,h,g));w.push(["Z"]);z=[["M",e+q*G,f+p*D]];z=z.concat(u(e,f,q,p,d,n,0,0));z.push(["L",e+q*Math.cos(n)+h,f+p*Math.sin(n)+g]);z=z.concat(u(e,f,q,p,n,d,h,g));z.push(["Z"]);G=[["M",e+B*G,f+b*D],
["L",e+B*G+h,f+b*D+g],["L",e+q*G+h,f+p*D+g],["L",e+q*G,f+p*D],["Z"]];e=[["M",e+B*a,f+b*m],["L",e+B*a+h,f+b*m+g],["L",e+q*a+h,f+p*m+g],["L",e+q*a,f+p*m],["Z"]];m=Math.atan2(g,-h);f=Math.abs(n+m);a=Math.abs(d+m);d=Math.abs((d+n)/2+m);f=c(f);a=c(a);d=c(d);d*=1E5;n=1E5*a;f*=1E5;return{top:t,zTop:1E5*Math.PI+1,out:w,zOut:Math.max(d,n,f),inn:z,zInn:Math.max(d,n,f),side1:G,zSide1:.99*f,side2:e,zSide2:.99*n}};return g});E(b,"Core/Axis/Tick3D.js",[b["Core/Utilities.js"]],function(b){var r=b.addEvent,l=b.extend,
v=b.wrap;return function(){function d(){}d.compose=function(b){r(b,"afterGetLabelPosition",d.onAfterGetLabelPosition);v(b.prototype,"getMarkPath",d.wrapGetMarkPath)};d.onAfterGetLabelPosition=function(d){var b=this.axis.axis3D;b&&l(d.pos,b.fix3dPosition(d.pos))};d.wrapGetMarkPath=function(d){var b=this.axis.axis3D,l=d.apply(this,[].slice.call(arguments,1));if(b){var u=l[0],A=l[1];if("M"===u[0]&&"L"===A[0])return b=[b.fix3dPosition({x:u[1],y:u[2],z:0}),b.fix3dPosition({x:A[1],y:A[2],z:0})],this.axis.chart.renderer.toLineSegments(b)}return l};
return d}()});E(b,"Core/Axis/Axis3D.js",[b["Core/Globals.js"],b["Extensions/Math3D.js"],b["Core/Axis/Tick.js"],b["Core/Axis/Tick3D.js"],b["Core/Utilities.js"]],function(b,r,l,v,d){var x=r.perspective,g=r.perspective3D,y=r.shapeArea,u=d.addEvent,A=d.merge,c=d.pick,a=d.wrap,q=b.deg2rad,p=function(){function a(a){this.axis=a}a.prototype.fix3dPosition=function(a,f){var e=this.axis,d=e.chart;if("colorAxis"===e.coll||!d.chart3d||!d.is3d())return a;var b=q*d.options.chart.options3d.alpha,m=q*d.options.chart.options3d.beta,
p=c(f&&e.options.title.position3d,e.options.labels.position3d);f=c(f&&e.options.title.skew3d,e.options.labels.skew3d);var g=d.chart3d.frame3d,h=d.plotLeft,A=d.plotWidth+h,k=d.plotTop,u=d.plotHeight+k;d=!1;var l=0,v=0,r={x:0,y:1,z:0};a=e.axis3D.swapZ({x:a.x,y:a.y,z:0});if(e.isZAxis)if(e.opposite){if(null===g.axes.z.top)return{};v=a.y-k;a.x=g.axes.z.top.x;a.y=g.axes.z.top.y;h=g.axes.z.top.xDir;d=!g.top.frontFacing}else{if(null===g.axes.z.bottom)return{};v=a.y-u;a.x=g.axes.z.bottom.x;a.y=g.axes.z.bottom.y;
h=g.axes.z.bottom.xDir;d=!g.bottom.frontFacing}else if(e.horiz)if(e.opposite){if(null===g.axes.x.top)return{};v=a.y-k;a.y=g.axes.x.top.y;a.z=g.axes.x.top.z;h=g.axes.x.top.xDir;d=!g.top.frontFacing}else{if(null===g.axes.x.bottom)return{};v=a.y-u;a.y=g.axes.x.bottom.y;a.z=g.axes.x.bottom.z;h=g.axes.x.bottom.xDir;d=!g.bottom.frontFacing}else if(e.opposite){if(null===g.axes.y.right)return{};l=a.x-A;a.x=g.axes.y.right.x;a.z=g.axes.y.right.z;h=g.axes.y.right.xDir;h={x:h.z,y:h.y,z:-h.x}}else{if(null===g.axes.y.left)return{};
l=a.x-h;a.x=g.axes.y.left.x;a.z=g.axes.y.left.z;h=g.axes.y.left.xDir}"chart"!==p&&("flap"===p?e.horiz?(m=Math.sin(b),b=Math.cos(b),e.opposite&&(m=-m),d&&(m=-m),r={x:h.z*m,y:b,z:-h.x*m}):h={x:Math.cos(m),y:0,z:Math.sin(m)}:"ortho"===p?e.horiz?(r=Math.cos(b),p=Math.sin(m)*r,b=-Math.sin(b),m=-r*Math.cos(m),r={x:h.y*m-h.z*b,y:h.z*p-h.x*m,z:h.x*b-h.y*p},b=1/Math.sqrt(r.x*r.x+r.y*r.y+r.z*r.z),d&&(b=-b),r={x:b*r.x,y:b*r.y,z:b*r.z}):h={x:Math.cos(m),y:0,z:Math.sin(m)}:e.horiz?r={x:Math.sin(m)*Math.sin(b),
y:Math.cos(b),z:-Math.cos(m)*Math.sin(b)}:h={x:Math.cos(m),y:0,z:Math.sin(m)});a.x+=l*h.x+v*r.x;a.y+=l*h.y+v*r.y;a.z+=l*h.z+v*r.z;d=x([a],e.chart)[0];f&&(0>y(x([a,{x:a.x+h.x,y:a.y+h.y,z:a.z+h.z},{x:a.x+r.x,y:a.y+r.y,z:a.z+r.z}],e.chart))&&(h={x:-h.x,y:-h.y,z:-h.z}),a=x([{x:a.x,y:a.y,z:a.z},{x:a.x+h.x,y:a.y+h.y,z:a.z+h.z},{x:a.x+r.x,y:a.y+r.y,z:a.z+r.z}],e.chart),d.matrix=[a[1].x-a[0].x,a[1].y-a[0].y,a[2].x-a[0].x,a[2].y-a[0].y,d.x,d.y],d.matrix[4]-=d.x*d.matrix[0]+d.y*d.matrix[2],d.matrix[5]-=d.x*
d.matrix[1]+d.y*d.matrix[3]);return d};a.prototype.swapZ=function(a,c){var e=this.axis;return e.isZAxis?(c=c?0:e.chart.plotLeft,{x:c+a.z,y:a.y,z:a.x-c}):a};return a}();return function(){function d(){}d.compose=function(c){A(!0,c.defaultOptions,d.defaultOptions);c.keepProps.push("axis3D");u(c,"init",d.onInit);u(c,"afterSetOptions",d.onAfterSetOptions);u(c,"drawCrosshair",d.onDrawCrosshair);u(c,"destroy",d.onDestroy);c=c.prototype;a(c,"getLinePath",d.wrapGetLinePath);a(c,"getPlotBandPath",d.wrapGetPlotBandPath);
a(c,"getPlotLinePath",d.wrapGetPlotLinePath);a(c,"getSlotWidth",d.wrapGetSlotWidth);a(c,"getTitlePosition",d.wrapGetTitlePosition);v.compose(l)};d.onAfterSetOptions=function(){var a=this.chart,d=this.options;a.is3d&&a.is3d()&&"colorAxis"!==this.coll&&(d.tickWidth=c(d.tickWidth,0),d.gridLineWidth=c(d.gridLineWidth,1))};d.onDestroy=function(){["backFrame","bottomFrame","sideFrame"].forEach(function(a){this[a]&&(this[a]=this[a].destroy())},this)};d.onDrawCrosshair=function(a){this.chart.is3d()&&"colorAxis"!==
this.coll&&a.point&&(a.point.crosshairPos=this.isXAxis?a.point.axisXpos:this.len-a.point.axisYpos)};d.onInit=function(){this.axis3D||(this.axis3D=new p(this))};d.wrapGetLinePath=function(a){return this.chart.is3d()&&"colorAxis"!==this.coll?[]:a.apply(this,[].slice.call(arguments,1))};d.wrapGetPlotBandPath=function(a){if(!this.chart.is3d()||"colorAxis"===this.coll)return a.apply(this,[].slice.call(arguments,1));var c=arguments,d=c[2],b=[];c=this.getPlotLinePath({value:c[1]});d=this.getPlotLinePath({value:d});
if(c&&d)for(var e=0;e<c.length;e+=2){var g=c[e],q=c[e+1],p=d[e],h=d[e+1];"M"===g[0]&&"L"===q[0]&&"M"===p[0]&&"L"===h[0]&&b.push(g,q,h,["L",p[1],p[2]],["Z"])}return b};d.wrapGetPlotLinePath=function(a){var c=this.axis3D,d=this.chart,b=a.apply(this,[].slice.call(arguments,1));if("colorAxis"===this.coll||!d.chart3d||!d.is3d()||null===b)return b;var e=d.options.chart.options3d,g=this.isZAxis?d.plotWidth:e.depth;e=d.chart3d.frame3d;var q=b[0],p=b[1];b=[];"M"===q[0]&&"L"===p[0]&&(c=[c.swapZ({x:q[1],y:q[2],
z:0}),c.swapZ({x:q[1],y:q[2],z:g}),c.swapZ({x:p[1],y:p[2],z:0}),c.swapZ({x:p[1],y:p[2],z:g})],this.horiz?(this.isZAxis?(e.left.visible&&b.push(c[0],c[2]),e.right.visible&&b.push(c[1],c[3])):(e.front.visible&&b.push(c[0],c[2]),e.back.visible&&b.push(c[1],c[3])),e.top.visible&&b.push(c[0],c[1]),e.bottom.visible&&b.push(c[2],c[3])):(e.front.visible&&b.push(c[0],c[2]),e.back.visible&&b.push(c[1],c[3]),e.left.visible&&b.push(c[0],c[1]),e.right.visible&&b.push(c[2],c[3])),b=x(b,this.chart,!1));return d.renderer.toLineSegments(b)};
d.wrapGetSlotWidth=function(a,d){var b=this.chart,e=this.ticks,f=this.gridGroup;if(this.categories&&b.frameShapes&&b.is3d()&&f&&d&&d.label){f=f.element.childNodes[0].getBBox();var q=b.frameShapes.left.getBBox(),p=b.options.chart.options3d;b={x:b.plotWidth/2,y:b.plotHeight/2,z:p.depth/2,vd:c(p.depth,1)*c(p.viewDistance,0)};var m,h;p=d.pos;var l=e[p-1];e=e[p+1];0!==p&&l&&l.label&&l.label.xy&&(m=g({x:l.label.xy.x,y:l.label.xy.y,z:null},b,b.vd));e&&e.label&&e.label.xy&&(h=g({x:e.label.xy.x,y:e.label.xy.y,
z:null},b,b.vd));e={x:d.label.xy.x,y:d.label.xy.y,z:null};e=g(e,b,b.vd);return Math.abs(m?e.x-m.x:h?h.x-e.x:f.x-q.x)}return a.apply(this,[].slice.call(arguments,1))};d.wrapGetTitlePosition=function(a){var c=a.apply(this,[].slice.call(arguments,1));return this.axis3D?this.axis3D.fix3dPosition(c,!0):c};d.defaultOptions={labels:{position3d:"offset",skew3d:!1},title:{position3d:null,skew3d:null}};return d}()});E(b,"Core/Axis/ZAxis.js",[b["Core/Axis/Axis.js"],b["Core/Utilities.js"]],function(b,r){var l=
this&&this.__extends||function(){var d=function(c,a){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d])};return d(c,a)};return function(c,a){function b(){this.constructor=c}d(c,a);c.prototype=null===a?Object.create(a):(b.prototype=a.prototype,new b)}}(),v=r.addEvent,d=r.merge,x=r.pick,g=r.splat,y=function(){function d(){}d.compose=function(c){v(c,"afterGetAxes",d.onAfterGetAxes);c=c.prototype;c.addZAxis=
d.wrapAddZAxis;c.collectionsWithInit.zAxis=[c.addZAxis];c.collectionsWithUpdate.push("zAxis")};d.onAfterGetAxes=function(){var c=this,a=this.options;a=a.zAxis=g(a.zAxis||{});c.is3d()&&(c.zAxis=[],a.forEach(function(a,d){a.index=d;a.isX=!0;c.addZAxis(a).setScale()}))};d.wrapAddZAxis=function(c){return new u(this,c)};return d}(),u=function(b){function c(a,c){a=b.call(this,a,c)||this;a.isZAxis=!0;return a}l(c,b);c.prototype.getSeriesExtremes=function(){var a=this,c=a.chart;a.hasVisibleSeries=!1;a.dataMin=
a.dataMax=a.ignoreMinPadding=a.ignoreMaxPadding=void 0;a.stacking&&a.stacking.buildStacks();a.series.forEach(function(d){!d.visible&&c.options.chart&&c.options.chart.ignoreHiddenSeries||(a.hasVisibleSeries=!0,d=d.zData,d.length&&(a.dataMin=Math.min(x(a.dataMin,d[0]),Math.min.apply(null,d)),a.dataMax=Math.max(x(a.dataMax,d[0]),Math.max.apply(null,d))))})};c.prototype.setAxisSize=function(){var a=this.chart;b.prototype.setAxisSize.call(this);this.width=this.len=a.options.chart&&a.options.chart.options3d&&
a.options.chart.options3d.depth||0;this.right=a.chartWidth-this.width-this.left};c.prototype.setOptions=function(a){a=d({offset:0,lineWidth:0},a);b.prototype.setOptions.call(this,a);this.coll="zAxis"};c.ZChartComposition=y;return c}(b);return u});E(b,"Core/Chart/Chart3D.js",[b["Core/Axis/Axis.js"],b["Core/Axis/Axis3D.js"],b["Core/Chart/Chart.js"],b["Core/Animation/Fx.js"],b["Core/Globals.js"],b["Extensions/Math3D.js"],b["Core/Options.js"],b["Core/Utilities.js"],b["Core/Axis/ZAxis.js"]],function(b,
r,l,v,d,x,g,y,u){var A=x.perspective,c=x.shapeArea3D,a=g.defaultOptions,q=y.addEvent,p=y.isArray,m=y.merge,e=y.pick,f=y.wrap,t;(function(b){function n(a){this.is3d()&&"scatter"===a.options.type&&(a.options.type="scatter3d")}function g(){if(this.chart3d&&this.is3d()){var a=this.renderer,c=this.options.chart.options3d,b=this.chart3d.get3dFrame(),e=this.plotLeft,f=this.plotLeft+this.plotWidth,h=this.plotTop,k=this.plotTop+this.plotHeight;c=c.depth;var n=e-(b.left.visible?b.left.size:0),g=f+(b.right.visible?
b.right.size:0),p=h-(b.top.visible?b.top.size:0),q=k+(b.bottom.visible?b.bottom.size:0),m=0-(b.front.visible?b.front.size:0),l=c+(b.back.visible?b.back.size:0),t=this.hasRendered?"animate":"attr";this.chart3d.frame3d=b;this.frameShapes||(this.frameShapes={bottom:a.polyhedron().add(),top:a.polyhedron().add(),left:a.polyhedron().add(),right:a.polyhedron().add(),back:a.polyhedron().add(),front:a.polyhedron().add()});this.frameShapes.bottom[t]({"class":"highcharts-3d-frame highcharts-3d-frame-bottom",
zIndex:b.bottom.frontFacing?-1E3:1E3,faces:[{fill:d.color(b.bottom.color).brighten(.1).get(),vertexes:[{x:n,y:q,z:m},{x:g,y:q,z:m},{x:g,y:q,z:l},{x:n,y:q,z:l}],enabled:b.bottom.visible},{fill:d.color(b.bottom.color).brighten(.1).get(),vertexes:[{x:e,y:k,z:c},{x:f,y:k,z:c},{x:f,y:k,z:0},{x:e,y:k,z:0}],enabled:b.bottom.visible},{fill:d.color(b.bottom.color).brighten(-.1).get(),vertexes:[{x:n,y:q,z:m},{x:n,y:q,z:l},{x:e,y:k,z:c},{x:e,y:k,z:0}],enabled:b.bottom.visible&&!b.left.visible},{fill:d.color(b.bottom.color).brighten(-.1).get(),
vertexes:[{x:g,y:q,z:l},{x:g,y:q,z:m},{x:f,y:k,z:0},{x:f,y:k,z:c}],enabled:b.bottom.visible&&!b.right.visible},{fill:d.color(b.bottom.color).get(),vertexes:[{x:g,y:q,z:m},{x:n,y:q,z:m},{x:e,y:k,z:0},{x:f,y:k,z:0}],enabled:b.bottom.visible&&!b.front.visible},{fill:d.color(b.bottom.color).get(),vertexes:[{x:n,y:q,z:l},{x:g,y:q,z:l},{x:f,y:k,z:c},{x:e,y:k,z:c}],enabled:b.bottom.visible&&!b.back.visible}]});this.frameShapes.top[t]({"class":"highcharts-3d-frame highcharts-3d-frame-top",zIndex:b.top.frontFacing?
-1E3:1E3,faces:[{fill:d.color(b.top.color).brighten(.1).get(),vertexes:[{x:n,y:p,z:l},{x:g,y:p,z:l},{x:g,y:p,z:m},{x:n,y:p,z:m}],enabled:b.top.visible},{fill:d.color(b.top.color).brighten(.1).get(),vertexes:[{x:e,y:h,z:0},{x:f,y:h,z:0},{x:f,y:h,z:c},{x:e,y:h,z:c}],enabled:b.top.visible},{fill:d.color(b.top.color).brighten(-.1).get(),vertexes:[{x:n,y:p,z:l},{x:n,y:p,z:m},{x:e,y:h,z:0},{x:e,y:h,z:c}],enabled:b.top.visible&&!b.left.visible},{fill:d.color(b.top.color).brighten(-.1).get(),vertexes:[{x:g,
y:p,z:m},{x:g,y:p,z:l},{x:f,y:h,z:c},{x:f,y:h,z:0}],enabled:b.top.visible&&!b.right.visible},{fill:d.color(b.top.color).get(),vertexes:[{x:n,y:p,z:m},{x:g,y:p,z:m},{x:f,y:h,z:0},{x:e,y:h,z:0}],enabled:b.top.visible&&!b.front.visible},{fill:d.color(b.top.color).get(),vertexes:[{x:g,y:p,z:l},{x:n,y:p,z:l},{x:e,y:h,z:c},{x:f,y:h,z:c}],enabled:b.top.visible&&!b.back.visible}]});this.frameShapes.left[t]({"class":"highcharts-3d-frame highcharts-3d-frame-left",zIndex:b.left.frontFacing?-1E3:1E3,faces:[{fill:d.color(b.left.color).brighten(.1).get(),
vertexes:[{x:n,y:q,z:m},{x:e,y:k,z:0},{x:e,y:k,z:c},{x:n,y:q,z:l}],enabled:b.left.visible&&!b.bottom.visible},{fill:d.color(b.left.color).brighten(.1).get(),vertexes:[{x:n,y:p,z:l},{x:e,y:h,z:c},{x:e,y:h,z:0},{x:n,y:p,z:m}],enabled:b.left.visible&&!b.top.visible},{fill:d.color(b.left.color).brighten(-.1).get(),vertexes:[{x:n,y:q,z:l},{x:n,y:p,z:l},{x:n,y:p,z:m},{x:n,y:q,z:m}],enabled:b.left.visible},{fill:d.color(b.left.color).brighten(-.1).get(),vertexes:[{x:e,y:h,z:c},{x:e,y:k,z:c},{x:e,y:k,z:0},
{x:e,y:h,z:0}],enabled:b.left.visible},{fill:d.color(b.left.color).get(),vertexes:[{x:n,y:q,z:m},{x:n,y:p,z:m},{x:e,y:h,z:0},{x:e,y:k,z:0}],enabled:b.left.visible&&!b.front.visible},{fill:d.color(b.left.color).get(),vertexes:[{x:n,y:p,z:l},{x:n,y:q,z:l},{x:e,y:k,z:c},{x:e,y:h,z:c}],enabled:b.left.visible&&!b.back.visible}]});this.frameShapes.right[t]({"class":"highcharts-3d-frame highcharts-3d-frame-right",zIndex:b.right.frontFacing?-1E3:1E3,faces:[{fill:d.color(b.right.color).brighten(.1).get(),
vertexes:[{x:g,y:q,z:l},{x:f,y:k,z:c},{x:f,y:k,z:0},{x:g,y:q,z:m}],enabled:b.right.visible&&!b.bottom.visible},{fill:d.color(b.right.color).brighten(.1).get(),vertexes:[{x:g,y:p,z:m},{x:f,y:h,z:0},{x:f,y:h,z:c},{x:g,y:p,z:l}],enabled:b.right.visible&&!b.top.visible},{fill:d.color(b.right.color).brighten(-.1).get(),vertexes:[{x:f,y:h,z:0},{x:f,y:k,z:0},{x:f,y:k,z:c},{x:f,y:h,z:c}],enabled:b.right.visible},{fill:d.color(b.right.color).brighten(-.1).get(),vertexes:[{x:g,y:q,z:m},{x:g,y:p,z:m},{x:g,y:p,
z:l},{x:g,y:q,z:l}],enabled:b.right.visible},{fill:d.color(b.right.color).get(),vertexes:[{x:g,y:p,z:m},{x:g,y:q,z:m},{x:f,y:k,z:0},{x:f,y:h,z:0}],enabled:b.right.visible&&!b.front.visible},{fill:d.color(b.right.color).get(),vertexes:[{x:g,y:q,z:l},{x:g,y:p,z:l},{x:f,y:h,z:c},{x:f,y:k,z:c}],enabled:b.right.visible&&!b.back.visible}]});this.frameShapes.back[t]({"class":"highcharts-3d-frame highcharts-3d-frame-back",zIndex:b.back.frontFacing?-1E3:1E3,faces:[{fill:d.color(b.back.color).brighten(.1).get(),
vertexes:[{x:g,y:q,z:l},{x:n,y:q,z:l},{x:e,y:k,z:c},{x:f,y:k,z:c}],enabled:b.back.visible&&!b.bottom.visible},{fill:d.color(b.back.color).brighten(.1).get(),vertexes:[{x:n,y:p,z:l},{x:g,y:p,z:l},{x:f,y:h,z:c},{x:e,y:h,z:c}],enabled:b.back.visible&&!b.top.visible},{fill:d.color(b.back.color).brighten(-.1).get(),vertexes:[{x:n,y:q,z:l},{x:n,y:p,z:l},{x:e,y:h,z:c},{x:e,y:k,z:c}],enabled:b.back.visible&&!b.left.visible},{fill:d.color(b.back.color).brighten(-.1).get(),vertexes:[{x:g,y:p,z:l},{x:g,y:q,
z:l},{x:f,y:k,z:c},{x:f,y:h,z:c}],enabled:b.back.visible&&!b.right.visible},{fill:d.color(b.back.color).get(),vertexes:[{x:e,y:h,z:c},{x:f,y:h,z:c},{x:f,y:k,z:c},{x:e,y:k,z:c}],enabled:b.back.visible},{fill:d.color(b.back.color).get(),vertexes:[{x:n,y:q,z:l},{x:g,y:q,z:l},{x:g,y:p,z:l},{x:n,y:p,z:l}],enabled:b.back.visible}]});this.frameShapes.front[t]({"class":"highcharts-3d-frame highcharts-3d-frame-front",zIndex:b.front.frontFacing?-1E3:1E3,faces:[{fill:d.color(b.front.color).brighten(.1).get(),
vertexes:[{x:n,y:q,z:m},{x:g,y:q,z:m},{x:f,y:k,z:0},{x:e,y:k,z:0}],enabled:b.front.visible&&!b.bottom.visible},{fill:d.color(b.front.color).brighten(.1).get(),vertexes:[{x:g,y:p,z:m},{x:n,y:p,z:m},{x:e,y:h,z:0},{x:f,y:h,z:0}],enabled:b.front.visible&&!b.top.visible},{fill:d.color(b.front.color).brighten(-.1).get(),vertexes:[{x:n,y:p,z:m},{x:n,y:q,z:m},{x:e,y:k,z:0},{x:e,y:h,z:0}],enabled:b.front.visible&&!b.left.visible},{fill:d.color(b.front.color).brighten(-.1).get(),vertexes:[{x:g,y:q,z:m},{x:g,
y:p,z:m},{x:f,y:h,z:0},{x:f,y:k,z:0}],enabled:b.front.visible&&!b.right.visible},{fill:d.color(b.front.color).get(),vertexes:[{x:f,y:h,z:0},{x:e,y:h,z:0},{x:e,y:k,z:0},{x:f,y:k,z:0}],enabled:b.front.visible},{fill:d.color(b.front.color).get(),vertexes:[{x:g,y:q,z:m},{x:n,y:q,z:m},{x:n,y:p,z:m},{x:g,y:p,z:m}],enabled:b.front.visible}]})}}function l(){this.styledMode&&(this.renderer.definition({tagName:"style",textContent:".highcharts-3d-top{filter: url(#highcharts-brighter)}\n.highcharts-3d-side{filter: url(#highcharts-darker)}\n"}),
[{name:"darker",slope:.6},{name:"brighter",slope:1.4}].forEach(function(a){this.renderer.definition({tagName:"filter",id:"highcharts-"+a.name,children:[{tagName:"feComponentTransfer",children:[{tagName:"feFuncR",type:"linear",slope:a.slope},{tagName:"feFuncG",type:"linear",slope:a.slope},{tagName:"feFuncB",type:"linear",slope:a.slope}]}]})},this))}function t(){var a=this.options;this.is3d()&&(a.series||[]).forEach(function(b){"scatter"===(b.type||a.chart.type||a.chart.defaultSeriesType)&&(b.type=
"scatter3d")})}function h(){var a=this.options.chart.options3d;if(this.chart3d&&this.is3d()){a&&(a.alpha=a.alpha%360+(0<=a.alpha?0:360),a.beta=a.beta%360+(0<=a.beta?0:360));var b=this.inverted,c=this.clipBox,d=this.margin;c[b?"y":"x"]=-(d[3]||0);c[b?"x":"y"]=-(d[0]||0);c[b?"height":"width"]=this.chartWidth+(d[3]||0)+(d[1]||0);c[b?"width":"height"]=this.chartHeight+(d[0]||0)+(d[2]||0);this.scale3d=1;!0===a.fitToPlot&&(this.scale3d=this.chart3d.getScale(a.depth));this.chart3d.frame3d=this.chart3d.get3dFrame()}}
function u(){this.is3d()&&(this.isDirtyBox=!0)}function k(){this.chart3d&&this.is3d()&&(this.chart3d.frame3d=this.chart3d.get3dFrame())}function r(){this.chart3d||(this.chart3d=new K(this))}function v(a){return this.is3d()||a.apply(this,[].slice.call(arguments,1))}function x(a){var b=this.series.length;if(this.is3d())for(;b--;)a=this.series[b],a.translate(),a.render();else a.call(this)}function y(a){a.apply(this,[].slice.call(arguments,1));this.is3d()&&(this.container.className+=" highcharts-3d-chart")}
var K=function(){function a(a){this.frame3d=void 0;this.chart=a}a.prototype.get3dFrame=function(){var a=this.chart,b=a.options.chart.options3d,d=b.frame,f=a.plotLeft,h=a.plotLeft+a.plotWidth,k=a.plotTop,n=a.plotTop+a.plotHeight,g=b.depth,p=function(b){b=c(b,a);return.5<b?1:-.5>b?-1:0},q=p([{x:f,y:n,z:g},{x:h,y:n,z:g},{x:h,y:n,z:0},{x:f,y:n,z:0}]),m=p([{x:f,y:k,z:0},{x:h,y:k,z:0},{x:h,y:k,z:g},{x:f,y:k,z:g}]),l=p([{x:f,y:k,z:0},{x:f,y:k,z:g},{x:f,y:n,z:g},{x:f,y:n,z:0}]),t=p([{x:h,y:k,z:g},{x:h,y:k,
z:0},{x:h,y:n,z:0},{x:h,y:n,z:g}]),u=p([{x:f,y:n,z:0},{x:h,y:n,z:0},{x:h,y:k,z:0},{x:f,y:k,z:0}]);p=p([{x:f,y:k,z:g},{x:h,y:k,z:g},{x:h,y:n,z:g},{x:f,y:n,z:g}]);var r=!1,v=!1,C=!1,H=!1;[].concat(a.xAxis,a.yAxis,a.zAxis).forEach(function(a){a&&(a.horiz?a.opposite?v=!0:r=!0:a.opposite?H=!0:C=!0)});var x=function(a,b,c){for(var d=["size","color","visible"],f={},h=0;h<d.length;h++)for(var k=d[h],n=0;n<a.length;n++)if("object"===typeof a[n]){var g=a[n][k];if("undefined"!==typeof g&&null!==g){f[k]=g;break}}a=
c;!0===f.visible||!1===f.visible?a=f.visible:"auto"===f.visible&&(a=0<b);return{size:e(f.size,1),color:e(f.color,"none"),frontFacing:0<b,visible:a}};d={axes:{},bottom:x([d.bottom,d.top,d],q,r),top:x([d.top,d.bottom,d],m,v),left:x([d.left,d.right,d.side,d],l,C),right:x([d.right,d.left,d.side,d],t,H),back:x([d.back,d.front,d],p,!0),front:x([d.front,d.back,d],u,!1)};"auto"===b.axisLabelPosition?(t=function(a,b){return a.visible!==b.visible||a.visible&&b.visible&&a.frontFacing!==b.frontFacing},b=[],t(d.left,
d.front)&&b.push({y:(k+n)/2,x:f,z:0,xDir:{x:1,y:0,z:0}}),t(d.left,d.back)&&b.push({y:(k+n)/2,x:f,z:g,xDir:{x:0,y:0,z:-1}}),t(d.right,d.front)&&b.push({y:(k+n)/2,x:h,z:0,xDir:{x:0,y:0,z:1}}),t(d.right,d.back)&&b.push({y:(k+n)/2,x:h,z:g,xDir:{x:-1,y:0,z:0}}),q=[],t(d.bottom,d.front)&&q.push({x:(f+h)/2,y:n,z:0,xDir:{x:1,y:0,z:0}}),t(d.bottom,d.back)&&q.push({x:(f+h)/2,y:n,z:g,xDir:{x:-1,y:0,z:0}}),m=[],t(d.top,d.front)&&m.push({x:(f+h)/2,y:k,z:0,xDir:{x:1,y:0,z:0}}),t(d.top,d.back)&&m.push({x:(f+h)/
2,y:k,z:g,xDir:{x:-1,y:0,z:0}}),l=[],t(d.bottom,d.left)&&l.push({z:(0+g)/2,y:n,x:f,xDir:{x:0,y:0,z:-1}}),t(d.bottom,d.right)&&l.push({z:(0+g)/2,y:n,x:h,xDir:{x:0,y:0,z:1}}),n=[],t(d.top,d.left)&&n.push({z:(0+g)/2,y:k,x:f,xDir:{x:0,y:0,z:-1}}),t(d.top,d.right)&&n.push({z:(0+g)/2,y:k,x:h,xDir:{x:0,y:0,z:1}}),f=function(b,c,d){if(0===b.length)return null;if(1===b.length)return b[0];for(var e=0,f=A(b,a,!1),h=1;h<f.length;h++)d*f[h][c]>d*f[e][c]?e=h:d*f[h][c]===d*f[e][c]&&f[h].z<f[e].z&&(e=h);return b[e]},
d.axes={y:{left:f(b,"x",-1),right:f(b,"x",1)},x:{top:f(m,"y",-1),bottom:f(q,"y",1)},z:{top:f(n,"y",-1),bottom:f(l,"y",1)}}):d.axes={y:{left:{x:f,z:0,xDir:{x:1,y:0,z:0}},right:{x:h,z:0,xDir:{x:0,y:0,z:1}}},x:{top:{y:k,z:0,xDir:{x:1,y:0,z:0}},bottom:{y:n,z:0,xDir:{x:1,y:0,z:0}}},z:{top:{x:C?h:f,y:k,xDir:C?{x:0,y:0,z:1}:{x:0,y:0,z:-1}},bottom:{x:C?h:f,y:n,xDir:C?{x:0,y:0,z:1}:{x:0,y:0,z:-1}}}};return d};a.prototype.getScale=function(a){var b=this.chart,c=b.plotLeft,d=b.plotWidth+c,e=b.plotTop,f=b.plotHeight+
e,h=c+b.plotWidth/2,k=e+b.plotHeight/2,n=Number.MAX_VALUE,g=-Number.MAX_VALUE,p=Number.MAX_VALUE,q=-Number.MAX_VALUE,m=1;var l=[{x:c,y:e,z:0},{x:c,y:e,z:a}];[0,1].forEach(function(a){l.push({x:d,y:l[a].y,z:l[a].z})});[0,1,2,3].forEach(function(a){l.push({x:l[a].x,y:f,z:l[a].z})});l=A(l,b,!1);l.forEach(function(a){n=Math.min(n,a.x);g=Math.max(g,a.x);p=Math.min(p,a.y);q=Math.max(q,a.y)});c>n&&(m=Math.min(m,1-Math.abs((c+h)/(n+h))%1));d<g&&(m=Math.min(m,(d-h)/(g-h)));e>p&&(m=0>p?Math.min(m,(e+k)/(-p+
e+k)):Math.min(m,1-(e+k)/(p+k)%1));f<q&&(m=Math.min(m,Math.abs((f-k)/(q-k))));return m};return a}();b.Composition=K;b.defaultOptions={chart:{options3d:{enabled:!1,alpha:0,beta:0,depth:100,fitToPlot:!0,viewDistance:25,axisLabelPosition:null,frame:{visible:"default",size:1,bottom:{},top:{},left:{},right:{},back:{},front:{}}}}};b.compose=function(c,e){var A=c.prototype;e=e.prototype;A.is3d=function(){return this.options.chart.options3d&&this.options.chart.options3d.enabled};A.propsRequireDirtyBox.push("chart.options3d");
A.propsRequireUpdateSeries.push("chart.options3d");e.matrixSetter=function(){if(1>this.pos&&(p(this.start)||p(this.end))){var a=this.start||[1,0,0,1,0,0],b=this.end||[1,0,0,1,0,0];var c=[];for(var d=0;6>d;d++)c.push(this.pos*b[d]+(1-this.pos)*a[d])}else c=this.end;this.elem.attr(this.prop,c,null,!0)};m(!0,a,b.defaultOptions);q(c,"init",r);q(c,"addSeries",n);q(c,"afterDrawChartBox",g);q(c,"afterGetContainer",l);q(c,"afterInit",t);q(c,"afterSetChartSize",h);q(c,"beforeRedraw",u);q(c,"beforeRender",
k);f(d.Chart.prototype,"isInsidePlot",v);f(c,"renderSeries",x);f(c,"setClassName",y)}})(t||(t={}));t.compose(l,v);u.ZChartComposition.compose(l);r.compose(b);"";return t});E(b,"Core/Series/Series3D.js",[b["Series/Line/LineSeries.js"],b["Extensions/Math3D.js"],b["Core/Utilities.js"]],function(b,r,l){var v=this&&this.__extends||function(){var b=function(d,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=
b[c])};return b(d,c)};return function(d,c){function a(){this.constructor=d}b(d,c);d.prototype=null===c?Object.create(c):(a.prototype=c.prototype,new a)}}(),d=r.perspective;r=l.addEvent;var x=l.extend,g=l.merge,y=l.pick;l=function(l){function r(){return null!==l&&l.apply(this,arguments)||this}v(r,l);r.prototype.translate=function(){l.prototype.translate.apply(this,arguments);this.chart.is3d()&&this.translate3dPoints()};r.prototype.translate3dPoints=function(){var b=this.chart,a=y(this.zAxis,b.options.zAxis[0]),
g=[],p;for(p=0;p<this.data.length;p++){var m=this.data[p];if(a&&a.translate){var e=a.logarithmic&&a.val2lin?a.val2lin(m.z):m.z;m.plotZ=a.translate(e);m.isInside=m.isInside?e>=a.min&&e<=a.max:!1}else m.plotZ=0;m.axisXpos=m.plotX;m.axisYpos=m.plotY;m.axisZpos=m.plotZ;g.push({x:m.plotX,y:m.plotY,z:m.plotZ})}b=d(g,b,!0);for(p=0;p<this.data.length;p++)m=this.data[p],a=b[p],m.plotX=a.x,m.plotY=a.y,m.plotZ=a.z};r.defaultOptions=g(b.defaultOptions);return r}(b);r(b,"afterTranslate",function(){this.chart.is3d()&&
this.translate3dPoints()});x(b.prototype,{translate3dPoints:l.prototype.translate3dPoints});return l});E(b,"Series/Column3D/Column3DComposition.js",[b["Core/Series/Series.js"],b["Series/Column/ColumnSeries.js"],b["Core/Globals.js"],b["Series/Line/LineSeries.js"],b["Extensions/Math3D.js"],b["Extensions/Stacking.js"],b["Core/Utilities.js"]],function(b,r,l,v,d,x,g){function y(a,b){var c=a.series,d={},e,f=1;c.forEach(function(a){e=m(a.options.stack,b?0:c.length-1-a.index);d[e]?d[e].series.push(a):(d[e]=
{series:[a],position:f},f++)});d.totalStacks=f+1;return d}function u(a){var b=a.apply(this,[].slice.call(arguments,1));this.chart.is3d&&this.chart.is3d()&&(b.stroke=this.options.edgeColor||b.fill,b["stroke-width"]=m(this.options.edgeWidth,1));return b}function A(a,b,c){var d=this.chart.is3d&&this.chart.is3d();d&&(this.options.inactiveOtherPoints=!0);a.call(this,b,c);d&&(this.options.inactiveOtherPoints=!1)}function c(a){for(var b=[],c=1;c<arguments.length;c++)b[c-1]=arguments[c];return this.series.chart.is3d()?
this.graphic&&"g"!==this.graphic.element.nodeName:a.apply(this,b)}var a=r.prototype,q=l.svg,p=d.perspective;l=g.addEvent;var m=g.pick;g=g.wrap;g(a,"translate",function(a){a.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.translate3dShapes()});g(v.prototype,"justifyDataLabel",function(a){return arguments[2].outside3dPlot?!1:a.apply(this,[].slice.call(arguments,1))});a.translate3dPoints=function(){};a.translate3dShapes=function(){var a=this,b=a.chart,c=a.options,d=c.depth,g=(c.stacking?
c.stack||0:a.index)*(d+(c.groupZPadding||1)),m=a.borderWidth%2?.5:0,l;b.inverted&&!a.yAxis.reversed&&(m*=-1);!1!==c.grouping&&(g=0);g+=c.groupZPadding||1;a.data.forEach(function(c){c.outside3dPlot=null;if(null!==c.y){var e=c.shapeArgs,f=c.tooltipPos,k;[["x","width"],["y","height"]].forEach(function(b){k=e[b[0]]-m;0>k&&(e[b[1]]+=e[b[0]]+m,e[b[0]]=-m,k=0);k+e[b[1]]>a[b[0]+"Axis"].len&&0!==e[b[1]]&&(e[b[1]]=a[b[0]+"Axis"].len-e[b[0]]);if(0!==e[b[1]]&&(e[b[0]]>=a[b[0]+"Axis"].len||e[b[0]]+e[b[1]]<=m)){for(var d in e)e[d]=
0;c.outside3dPlot=!0}});"rect"===c.shapeType&&(c.shapeType="cuboid");e.z=g;e.depth=d;e.insidePlotArea=!0;l={x:e.x+e.width/2,y:e.y,z:g+d/2};b.inverted&&(l.x=e.height,l.y=c.clientX);c.plot3d=p([l],b,!0,!1)[0];f=p([{x:f[0],y:f[1],z:g+d/2}],b,!0,!1)[0];c.tooltipPos=[f.x,f.y]}});a.z=g};g(a,"animate",function(a){if(this.chart.is3d()){var b=arguments[1],c=this.yAxis,d=this,e=this.yAxis.reversed;q&&(b?d.data.forEach(function(a){null!==a.y&&(a.height=a.shapeArgs.height,a.shapey=a.shapeArgs.y,a.shapeArgs.height=
1,e||(a.shapeArgs.y=a.stackY?a.plotY+c.translate(a.stackY):a.plotY+(a.negative?-a.height:a.height)))}):(d.data.forEach(function(a){null!==a.y&&(a.shapeArgs.height=a.height,a.shapeArgs.y=a.shapey,a.graphic&&a.graphic.animate(a.shapeArgs,d.options.animation))}),this.drawDataLabels()))}else a.apply(this,[].slice.call(arguments,1))});g(a,"plotGroup",function(a,b,c,d,g,m){"dataLabelsGroup"!==b&&this.chart.is3d()&&(this[b]&&delete this[b],m&&(this.chart.columnGroup||(this.chart.columnGroup=this.chart.renderer.g("columnGroup").add(m)),
this[b]=this.chart.columnGroup,this.chart.columnGroup.attr(this.getPlotBox()),this[b].survive=!0,"group"===b||"markerGroup"===b))&&(arguments[3]="visible");return a.apply(this,Array.prototype.slice.call(arguments,1))});g(a,"setVisible",function(a,b){var c=this,d;c.chart.is3d()&&c.data.forEach(function(a){d=(a.visible=a.options.visible=b="undefined"===typeof b?!m(c.visible,a.visible):b)?"visible":"hidden";c.options.data[c.data.indexOf(a)]=a.options;a.graphic&&a.graphic.attr({visibility:d})});a.apply(this,
Array.prototype.slice.call(arguments,1))});a.handle3dGrouping=!0;l(v,"afterInit",function(){if(this.chart.is3d()&&this.handle3dGrouping){var a=this.options,b=a.grouping,c=a.stacking,d=m(this.yAxis.options.reversedStacks,!0),g=0;if("undefined"===typeof b||b){b=y(this.chart,c);g=a.stack||0;for(c=0;c<b[g].series.length&&b[g].series[c]!==this;c++);g=10*(b.totalStacks-b[g].position)+(d?c:-c);this.xAxis.reversed||(g=10*b.totalStacks-g)}a.depth=a.depth||25;this.z=this.z||0;a.zIndex=g}});g(a,"pointAttribs",
u);g(a,"setState",A);g(a.pointClass.prototype,"hasNewShapeType",c);b.seriesTypes.columnRange&&(l=b.seriesTypes.columnrange.prototype,g(l,"pointAttribs",u),g(l,"setState",A),g(l.pointClass.prototype,"hasNewShapeType",c),l.plotGroup=a.plotGroup,l.setVisible=a.setVisible);g(v.prototype,"alignDataLabel",function(a,b,c,d,g){var e=this.chart;d.outside3dPlot=b.outside3dPlot;if(e.is3d()&&this.is("column")){var f=this.options,n=m(d.inside,!!this.options.stacking),h=e.options.chart.options3d,l=b.pointWidth/
2||0;f={x:g.x+l,y:g.y,z:this.z+f.depth/2};e.inverted&&(n&&(g.width=0,f.x+=b.shapeArgs.height/2),90<=h.alpha&&270>=h.alpha&&(f.y+=b.shapeArgs.width));f=p([f],e,!0,!1)[0];g.x=f.x-l;g.y=b.outside3dPlot?-9E9:f.y}a.apply(this,[].slice.call(arguments,1))});g(x.prototype,"getStackBox",function(a,c,d,g,m,l,q,r){var e=a.apply(this,[].slice.call(arguments,1));if(c.is3d()&&d.base){var f=+d.base.split(",")[0],k=c.series[f];f=c.options.chart.options3d;k&&k instanceof b.seriesTypes.column&&(k={x:e.x+(c.inverted?
q:l/2),y:e.y,z:k.options.depth/2},c.inverted&&(e.width=0,90<=f.alpha&&270>=f.alpha&&(k.y+=l)),k=p([k],c,!0,!1)[0],e.x=k.x-l/2,e.y=k.y)}return e});"";return r});E(b,"Series/Pie3D/Pie3DPoint.js",[b["Core/Series/Series.js"]],function(b){var r=this&&this.__extends||function(){var b=function(d,l){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,d){b.__proto__=d}||function(b,d){for(var g in d)d.hasOwnProperty(g)&&(b[g]=d[g])};return b(d,l)};return function(d,l){function g(){this.constructor=
d}b(d,l);d.prototype=null===l?Object.create(l):(g.prototype=l.prototype,new g)}}();b=b.seriesTypes.pie.prototype.pointClass;var l=b.prototype.haloPath;return function(b){function d(){var d=null!==b&&b.apply(this,arguments)||this;d.series=void 0;return d}r(d,b);d.prototype.haloPath=function(){return this.series.chart.is3d()?[]:l.apply(this,arguments)};return d}(b)});E(b,"Series/Pie3D/Pie3DSeries.js",[b["Core/Series/Series.js"],b["Core/Globals.js"],b["Series/Pie3D/Pie3DPoint.js"],b["Core/Utilities.js"]],
function(b,r,l,v){var d=this&&this.__extends||function(){var b=function(d,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return b(d,c)};return function(d,c){function a(){this.constructor=d}b(d,c);d.prototype=null===c?Object.create(c):(a.prototype=c.prototype,new a)}}(),x=r.deg2rad,g=r.svg;r=v.extend;var y=v.pick;b=function(b){function l(){return null!==b&&b.apply(this,arguments)||this}d(l,b);
l.prototype.addPoint=function(){b.prototype.addPoint.apply(this,arguments);this.chart.is3d()&&this.update(this.userOptions,!0)};l.prototype.animate=function(c){if(this.chart.is3d()){var a=this.options.animation;var d=this.center;var l=this.group,m=this.markerGroup;g&&(!0===a&&(a={}),c?(l.oldtranslateX=y(l.oldtranslateX,l.translateX),l.oldtranslateY=y(l.oldtranslateY,l.translateY),d={translateX:d[0],translateY:d[1],scaleX:.001,scaleY:.001},l.attr(d),m&&(m.attrSetters=l.attrSetters,m.attr(d))):(d={translateX:l.oldtranslateX,
translateY:l.oldtranslateY,scaleX:1,scaleY:1},l.animate(d,a),m&&m.animate(d,a)))}else b.prototype.animate.apply(this,arguments)};l.prototype.drawDataLabels=function(){if(this.chart.is3d()){var c=this.chart.options.chart.options3d;this.data.forEach(function(a){var b=a.shapeArgs,d=b.r,g=(b.start+b.end)/2;a=a.labelPosition;var e=a.connectorPosition,f=-d*(1-Math.cos((b.alpha||c.alpha)*x))*Math.sin(g),l=d*(Math.cos((b.beta||c.beta)*x)-1)*Math.cos(g);[a.natural,e.breakAt,e.touchingSliceAt].forEach(function(a){a.x+=
l;a.y+=f})})}b.prototype.drawDataLabels.apply(this,arguments)};l.prototype.pointAttribs=function(c){var a=b.prototype.pointAttribs.apply(this,arguments),d=this.options;this.chart.is3d()&&!this.chart.styledMode&&(a.stroke=d.edgeColor||c.color||this.color,a["stroke-width"]=y(d.edgeWidth,1));return a};l.prototype.translate=function(){b.prototype.translate.apply(this,arguments);if(this.chart.is3d()){var c=this,a=c.options,d=a.depth||0,g=c.chart.options.chart.options3d,l=g.alpha,e=g.beta,f=a.stacking?
(a.stack||0)*d:c._i*d;f+=d/2;!1!==a.grouping&&(f=0);c.data.forEach(function(b){var g=b.shapeArgs;b.shapeType="arc3d";g.z=f;g.depth=.75*d;g.alpha=l;g.beta=e;g.center=c.center;g=(g.end+g.start)/2;b.slicedTranslation={translateX:Math.round(Math.cos(g)*a.slicedOffset*Math.cos(l*x)),translateY:Math.round(Math.sin(g)*a.slicedOffset*Math.cos(l*x))}})}};return l}(b.seriesTypes.pie);r(b,{pointClass:l});"";return b});E(b,"Series/Pie3D/Pie3DComposition.js",[b["Core/Series/Series.js"],b["Series/Pie3D/Pie3DPoint.js"],
b["Series/Pie3D/Pie3DSeries.js"]],function(b,r,l){b.seriesTypes.pie.prototype.pointClass.prototype.haloPath=r.prototype.haloPath;b.seriesTypes.pie=l});E(b,"Series/Scatter3D/Scatter3DPoint.js",[b["Series/Scatter/ScatterSeries.js"]],function(b){var r=this&&this.__extends||function(){var b=function(l,d){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,d){b.__proto__=d}||function(b,d){for(var g in d)d.hasOwnProperty(g)&&(b[g]=d[g])};return b(l,d)};return function(l,d){function r(){this.constructor=
l}b(l,d);l.prototype=null===d?Object.create(d):(r.prototype=d.prototype,new r)}}();return function(b){function l(){var d=null!==b&&b.apply(this,arguments)||this;d.options=void 0;d.series=void 0;return d}r(l,b);l.prototype.applyOptions=function(){b.prototype.applyOptions.apply(this,arguments);"undefined"===typeof this.z&&(this.z=0);return this};return l}(b.prototype.pointClass)});E(b,"Series/Scatter3D/Scatter3DSeries.js",[b["Core/Series/Series.js"],b["Series/Scatter3D/Scatter3DPoint.js"],b["Series/Scatter/ScatterSeries.js"],
b["Extensions/Math3D.js"],b["Core/Utilities.js"]],function(b,r,l,v,d){var x=this&&this.__extends||function(){var b=function(d,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return b(d,c)};return function(d,c){function a(){this.constructor=d}b(d,c);d.prototype=null===c?Object.create(c):(a.prototype=c.prototype,new a)}}(),g=v.pointCameraDistance;v=d.extend;var y=d.merge;d=function(b){function d(){var c=
null!==b&&b.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}x(d,b);d.prototype.pointAttribs=function(c){var a=b.prototype.pointAttribs.apply(this,arguments);this.chart.is3d()&&c&&(a.zIndex=g(c,this.chart));return a};d.defaultOptions=y(l.defaultOptions,{tooltip:{pointFormat:"x: <b>{point.x}</b><br/>y: <b>{point.y}</b><br/>z: <b>{point.z}</b><br/>"}});return d}(l);v(d.prototype,{axisTypes:["xAxis","yAxis","zAxis"],directTouch:!0,parallelArrays:["x","y","z"],pointArrayMap:["x",
"y","z"],pointClass:r});b.registerSeriesType("scatter3d",d);"";return d});E(b,"masters/highcharts-3d.src.js",[],function(){})});
//# sourceMappingURL=highcharts-3d.js.map