/*
 Highcharts JS v8.2.2 (2020-11-23)

 (c) 2009-2018 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(d){"object"===typeof module&&module.exports?(d["default"]=d,module.exports=d):"function"===typeof define&&define.amd?define("highcharts/highcharts-more",["highcharts"],function(A){d(A);d.Highcharts=A;return d}):d("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(d){function A(d,c,h,f){d.hasOwnProperty(c)||(d[c]=f.apply(null,h))}d=d?d._modules:{};A(d,"Extensions/Pane.js",[d["Core/Chart/Chart.js"],d["Core/Globals.js"],d["Core/Color/Palette.js"],d["Core/Pointer.js"],d["Core/Utilities.js"],
d["Mixins/CenteredSeries.js"]],function(d,c,h,f,a,p){function k(b,g,a){return Math.sqrt(Math.pow(b-a[0],2)+Math.pow(g-a[1],2))<=a[2]/2}var t=a.addEvent,w=a.extend,v=a.merge,b=a.pick,g=a.splat;d.prototype.collectionsWithUpdate.push("pane");a=function(){function b(b,g){this.options=this.chart=this.center=this.background=void 0;this.coll="pane";this.defaultOptions={center:["50%","50%"],size:"85%",innerSize:"0%",startAngle:0};this.defaultBackgroundOptions={shape:"circle",borderWidth:1,borderColor:h.neutralColor20,
backgroundColor:{linearGradient:{x1:0,y1:0,x2:0,y2:1},stops:[[0,h.backgroundColor],[1,h.neutralColor10]]},from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,outerRadius:"105%"};this.init(b,g)}b.prototype.init=function(b,g){this.chart=g;this.background=[];g.pane.push(this);this.setOptions(b)};b.prototype.setOptions=function(b){this.options=v(this.defaultOptions,this.chart.angular?{background:{}}:void 0,b)};b.prototype.render=function(){var b=this.options,a=this.options.background,l=this.chart.renderer;
this.group||(this.group=l.g("pane-group").attr({zIndex:b.zIndex||0}).add());this.updateCenter();if(a)for(a=g(a),b=Math.max(a.length,this.background.length||0),l=0;l<b;l++)a[l]&&this.axis?this.renderBackground(v(this.defaultBackgroundOptions,a[l]),l):this.background[l]&&(this.background[l]=this.background[l].destroy(),this.background.splice(l,1))};b.prototype.renderBackground=function(b,g){var a="animate",l={"class":"highcharts-pane "+(b.className||"")};this.chart.styledMode||w(l,{fill:b.backgroundColor,
stroke:b.borderColor,"stroke-width":b.borderWidth});this.background[g]||(this.background[g]=this.chart.renderer.path().add(this.group),a="attr");this.background[g][a]({d:this.axis.getPlotBandPath(b.from,b.to,b)}).attr(l)};b.prototype.updateCenter=function(b){this.center=(b||this.axis||{}).center=p.getCenter.call(this)};b.prototype.update=function(b,g){v(!0,this.options,b);v(!0,this.chart.options.pane,b);this.setOptions(this.options);this.render();this.chart.axes.forEach(function(b){b.pane===this&&
(b.pane=null,b.update({},g))},this)};return b}();d.prototype.getHoverPane=function(b){var g=this,a;b&&g.pane.forEach(function(l){var c=b.chartX-g.plotLeft,B=b.chartY-g.plotTop;k(g.inverted?B:c,g.inverted?c:B,l.center)&&(a=l)});return a};t(d,"afterIsInsidePlot",function(b){this.polar&&(b.isInsidePlot=this.pane.some(function(g){return k(b.x,b.y,g.center)}))});t(f,"beforeGetHoverData",function(g){var a=this.chart;a.polar&&(a.hoverPane=a.getHoverPane(g),g.filter=function(l){return l.visible&&!(!g.shared&&
l.directTouch)&&b(l.options.enableMouseTracking,!0)&&(!a.hoverPane||l.xAxis.pane===a.hoverPane)})});t(f,"afterGetHoverData",function(b){var g=this.chart;b.hoverPoint&&b.hoverPoint.plotX&&b.hoverPoint.plotY&&g.hoverPane&&!k(b.hoverPoint.plotX,b.hoverPoint.plotY,g.hoverPane.center)&&(b.hoverPoint=void 0)});c.Pane=a;return c.Pane});A(d,"Core/Axis/HiddenAxis.js",[],function(){return function(){function d(){}d.init=function(c){c.getOffset=function(){};c.redraw=function(){this.isDirty=!1};c.render=function(){this.isDirty=
!1};c.createLabelCollector=function(){return function(){}};c.setScale=function(){};c.setCategories=function(){};c.setTitle=function(){};c.isHidden=!0};return d}()});A(d,"Core/Axis/RadialAxis.js",[d["Core/Axis/Axis.js"],d["Core/Axis/Tick.js"],d["Core/Axis/HiddenAxis.js"],d["Core/Utilities.js"]],function(d,c,h,f){var a=f.addEvent,p=f.correctFloat,k=f.defined,t=f.extend,w=f.fireEvent,v=f.merge,b=f.pick,g=f.relativeLength,l=f.wrap;f=function(){function c(){}c.init=function(a){var c=d.prototype;a.setOptions=
function(b){b=this.options=v(a.constructor.defaultOptions,this.defaultPolarOptions,b);b.plotBands||(b.plotBands=[]);w(this,"afterSetOptions")};a.getOffset=function(){c.getOffset.call(this);this.chart.axisOffset[this.side]=0};a.getLinePath=function(a,g,x){a=this.pane.center;var q=this.chart,r=b(g,a[2]/2-this.offset);"undefined"===typeof x&&(x=this.horiz?0:this.center&&-this.center[3]/2);x&&(r+=x);this.isCircular||"undefined"!==typeof g?(g=this.chart.renderer.symbols.arc(this.left+a[0],this.top+a[1],
r,r,{start:this.startAngleRad,end:this.endAngleRad,open:!0,innerR:0}),g.xBounds=[this.left+a[0]],g.yBounds=[this.top+a[1]-r]):(g=this.postTranslate(this.angleRad,r),g=[["M",this.center[0]+q.plotLeft,this.center[1]+q.plotTop],["L",g.x,g.y]]);return g};a.setAxisTranslation=function(){c.setAxisTranslation.call(this);this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/(this.max-this.min||1):(this.center[2]-this.center[3])/2/(this.max-this.min||1),this.minPixelPadding=this.isXAxis?
this.transA*this.minPointOffset:0)};a.beforeSetTickPositions=function(){this.autoConnect=this.isCircular&&"undefined"===typeof b(this.userMax,this.options.max)&&p(this.endAngleRad-this.startAngleRad)===p(2*Math.PI);!this.isCircular&&this.chart.inverted&&this.max++;this.autoConnect&&(this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0)};a.setAxisSize=function(){c.setAxisSize.call(this);if(this.isRadial){this.pane.updateCenter(this);var a=this.center=t([],this.pane.center);if(this.isCircular)this.sector=
this.endAngleRad-this.startAngleRad;else{var g=this.postTranslate(this.angleRad,a[3]/2);a[0]=g.x-this.chart.plotLeft;a[1]=g.y-this.chart.plotTop}this.len=this.width=this.height=(a[2]-a[3])*b(this.sector,1)/2}};a.getPosition=function(a,g){a=this.translate(a);return this.postTranslate(this.isCircular?a:this.angleRad,b(this.isCircular?g:0>a?0:a,this.center[2]/2)-this.offset)};a.postTranslate=function(b,a){var g=this.chart,q=this.center;b=this.startAngleRad+b;return{x:g.plotLeft+q[0]+Math.cos(b)*a,y:g.plotTop+
q[1]+Math.sin(b)*a}};a.getPlotBandPath=function(a,g,x){var q=function(e){if("string"===typeof e){var b=parseInt(e,10);n.test(e)&&(b=b*m/100);return b}return e},r=this.center,e=this.startAngleRad,m=r[2]/2,u=Math.min(this.offset,0),n=/%$/;var F=this.isCircular;var E=b(q(x.outerRadius),m),D=q(x.innerRadius);q=b(q(x.thickness),10);if("polygon"===this.options.gridLineInterpolation)u=this.getPlotLinePath({value:a}).concat(this.getPlotLinePath({value:g,reverse:!0}));else{a=Math.max(a,this.min);g=Math.min(g,
this.max);a=this.translate(a);g=this.translate(g);F||(E=a||0,D=g||0);if("circle"!==x.shape&&F)x=e+(a||0),e+=g||0;else{x=-Math.PI/2;e=1.5*Math.PI;var c=!0}E-=u;u=this.chart.renderer.symbols.arc(this.left+r[0],this.top+r[1],E,E,{start:Math.min(x,e),end:Math.max(x,e),innerR:b(D,E-(q-u)),open:c});F&&(F=(e+x)/2,c=this.left+r[0]+r[2]/2*Math.cos(F),u.xBounds=F>-Math.PI/2&&F<Math.PI/2?[c,this.chart.plotWidth]:[0,c],u.yBounds=[this.top+r[1]+r[2]/2*Math.sin(F)],u.yBounds[0]+=F>-Math.PI&&0>F||F>Math.PI?-10:
10)}return u};a.getCrosshairPosition=function(b,a,g){var q=b.value,r=this.pane.center;if(this.isCircular){if(k(q))b.point&&(e=b.point.shapeArgs||{},e.start&&(q=this.chart.inverted?this.translate(b.point.rectPlotY,!0):b.point.x));else{var e=b.chartX||0;var m=b.chartY||0;q=this.translate(Math.atan2(m-g,e-a)-this.startAngleRad,!0)}b=this.getPosition(q);e=b.x;m=b.y}else k(q)||(e=b.chartX,m=b.chartY),k(e)&&k(m)&&(g=r[1]+this.chart.plotTop,q=this.translate(Math.min(Math.sqrt(Math.pow(e-a,2)+Math.pow(m-
g,2)),r[2]/2)-r[3]/2,!0));return[q,e||0,m||0]};a.getPlotLinePath=function(b){var a=this,c=a.pane.center,q=a.chart,r=q.inverted,e=b.value,m=b.reverse,u=a.getPosition(e),n=a.pane.options.background?a.pane.options.background[0]||a.pane.options.background:{},F=n.innerRadius||"0%",E=n.outerRadius||"100%";n=c[0]+q.plotLeft;var D=c[1]+q.plotTop,l=u.x,G=u.y,f=a.height;u=c[3]/2;var h;b.isCrosshair&&(G=this.getCrosshairPosition(b,n,D),e=G[0],l=G[1],G=G[2]);if(a.isCircular)e=Math.sqrt(Math.pow(l-n,2)+Math.pow(G-
D,2)),m="string"===typeof F?g(F,1):F/e,q="string"===typeof E?g(E,1):E/e,c&&u&&(e=u/e,m<e&&(m=e),q<e&&(q=e)),c=[["M",n+m*(l-n),D-m*(D-G)],["L",l-(1-q)*(l-n),G+(1-q)*(D-G)]];else if((e=a.translate(e))&&(0>e||e>f)&&(e=0),"circle"===a.options.gridLineInterpolation)c=a.getLinePath(0,e,u);else if(c=[],q[r?"yAxis":"xAxis"].forEach(function(e){e.pane===a.pane&&(h=e)}),h)for(n=h.tickPositions,h.autoConnect&&(n=n.concat([n[0]])),m&&(n=n.slice().reverse()),e&&(e+=u),l=0;l<n.length;l++)D=h.getPosition(n[l],e),
c.push(l?["L",D.x,D.y]:["M",D.x,D.y]);return c};a.getTitlePosition=function(){var b=this.center,a=this.chart,g=this.options.title;return{x:a.plotLeft+b[0]+(g.x||0),y:a.plotTop+b[1]-{high:.5,middle:.25,low:0}[g.align]*b[2]+(g.y||0)}};a.createLabelCollector=function(){var b=this;return function(){if(b.isRadial&&b.tickPositions&&!0!==b.options.labels.allowOverlap)return b.tickPositions.map(function(a){return b.ticks[a]&&b.ticks[a].label}).filter(function(b){return!!b})}}};c.compose=function(f,d){a(f,
"init",function(b){var a=this.chart,g=a.inverted,q=a.angular,r=a.polar,e=this.isXAxis,m=this.coll,u=q&&e,n,F=a.options;b=b.userOptions.pane||0;b=this.pane=a.pane&&a.pane[b];if("colorAxis"===m)this.isRadial=!1;else{if(q){if(u?h.init(this):c.init(this),n=!e)this.defaultPolarOptions=c.defaultRadialGaugeOptions}else r&&(c.init(this),this.defaultPolarOptions=(n=this.horiz)?c.defaultCircularOptions:v("xAxis"===m?f.defaultOptions:f.defaultYAxisOptions,c.defaultRadialOptions),g&&"yAxis"===m&&(this.defaultPolarOptions.stackLabels=
f.defaultYAxisOptions.stackLabels));q||r?(this.isRadial=!0,F.chart.zoomType=null,this.labelCollector||(this.labelCollector=this.createLabelCollector()),this.labelCollector&&a.labelCollectors.push(this.labelCollector)):this.isRadial=!1;b&&n&&(b.axis=this);this.isCircular=n}});a(f,"afterInit",function(){var a=this.chart,g=this.options,c=this.pane,q=c&&c.options;a.angular&&this.isXAxis||!c||!a.angular&&!a.polar||(this.angleRad=(g.angle||0)*Math.PI/180,this.startAngleRad=(q.startAngle-90)*Math.PI/180,
this.endAngleRad=(b(q.endAngle,q.startAngle+360)-90)*Math.PI/180,this.offset=g.offset||0)});a(f,"autoLabelAlign",function(b){this.isRadial&&(b.align=void 0,b.preventDefault())});a(f,"destroy",function(){if(this.chart&&this.chart.labelCollectors){var b=this.labelCollector?this.chart.labelCollectors.indexOf(this.labelCollector):-1;0<=b&&this.chart.labelCollectors.splice(b,1)}});a(f,"initialAxisTranslation",function(){this.isRadial&&this.beforeSetTickPositions()});a(d,"afterGetPosition",function(b){this.axis.getPosition&&
t(b.pos,this.axis.getPosition(this.pos))});a(d,"afterGetLabelPosition",function(a){var c=this.axis,l=this.label;if(l){var q=l.getBBox(),r=c.options.labels,e=r.y,m=20,u=r.align,n=(c.translate(this.pos)+c.startAngleRad+Math.PI/2)/Math.PI*180%360,F=Math.round(n),E="end",D=0>F?F+360:F,f=D,G=0,h=0,d=null===r.y?.3*-q.height:0;if(c.isRadial){var k=c.getPosition(this.pos,c.center[2]/2+g(b(r.distance,-25),c.center[2]/2,-c.center[2]/2));"auto"===r.rotation?l.attr({rotation:n}):null===e&&(e=c.chart.renderer.fontMetrics(l.styles&&
l.styles.fontSize).b-q.height/2);null===u&&(c.isCircular?(q.width>c.len*c.tickInterval/(c.max-c.min)&&(m=0),u=n>m&&n<180-m?"left":n>180+m&&n<360-m?"right":"center"):u="center",l.attr({align:u}));if("auto"===u&&2===c.tickPositions.length&&c.isCircular){90<D&&180>D?D=180-D:270<D&&360>=D&&(D=540-D);180<f&&360>=f&&(f=360-f);if(c.pane.options.startAngle===F||c.pane.options.startAngle===F+360||c.pane.options.startAngle===F-360)E="start";u=-90<=F&&90>=F||-360<=F&&-270>=F||270<=F&&360>=F?"start"===E?"right":
"left":"start"===E?"left":"right";70<f&&110>f&&(u="center");15>D||180<=D&&195>D?G=.3*q.height:15<=D&&35>=D?G="start"===E?0:.75*q.height:195<=D&&215>=D?G="start"===E?.75*q.height:0:35<D&&90>=D?G="start"===E?.25*-q.height:q.height:215<D&&270>=D&&(G="start"===E?q.height:.25*-q.height);15>f?h="start"===E?.15*-q.height:.15*q.height:165<f&&180>=f&&(h="start"===E?.15*q.height:.15*-q.height);l.attr({align:u});l.translate(h,G+d)}a.pos.x=k.x+r.x;a.pos.y=k.y+e}}});l(d.prototype,"getMarkPath",function(b,a,g,
q,r,e,m){var u=this.axis;u.isRadial?(b=u.getPosition(this.pos,u.center[2]/2+q),a=["M",a,g,"L",b.x,b.y]):a=b.call(this,a,g,q,r,e,m);return a})};c.defaultCircularOptions={gridLineWidth:1,labels:{align:null,distance:15,x:0,y:null,style:{textOverflow:"none"}},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0};c.defaultRadialGaugeOptions={labels:{align:"center",x:0,y:null},minorGridLineWidth:0,minorTickInterval:"auto",minorTickLength:10,minorTickPosition:"inside",minorTickWidth:1,tickLength:10,tickPosition:"inside",
tickWidth:2,title:{rotation:0},zIndex:2};c.defaultRadialOptions={gridLineInterpolation:"circle",gridLineWidth:1,labels:{align:"right",x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}};return c}();f.compose(d,c);return f});A(d,"Series/AreaRange/AreaRangePoint.js",[d["Series/Area/AreaSeries.js"],d["Core/Series/Point.js"],d["Core/Utilities.js"]],function(d,c,h){var f=this&&this.__extends||function(){var a=function(c,f){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,
a){b.__proto__=a}||function(b,a){for(var g in a)a.hasOwnProperty(g)&&(b[g]=a[g])};return a(c,f)};return function(c,f){function b(){this.constructor=c}a(c,f);c.prototype=null===f?Object.create(f):(b.prototype=f.prototype,new b)}}(),a=c.prototype,p=h.defined,k=h.isNumber;return function(c){function h(){var a=null!==c&&c.apply(this,arguments)||this;a.high=void 0;a.low=void 0;a.options=void 0;a.plotHigh=void 0;a.plotLow=void 0;a.plotHighX=void 0;a.plotLowX=void 0;a.plotX=void 0;a.series=void 0;return a}
f(h,c);h.prototype.setState=function(){var c=this.state,b=this.series,g=b.chart.polar;p(this.plotHigh)||(this.plotHigh=b.yAxis.toPixels(this.high,!0));p(this.plotLow)||(this.plotLow=this.plotY=b.yAxis.toPixels(this.low,!0));b.stateMarkerGraphic&&(b.lowerStateMarkerGraphic=b.stateMarkerGraphic,b.stateMarkerGraphic=b.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;g&&(this.plotX=this.plotHighX);a.setState.apply(this,arguments);this.state=c;this.plotY=this.plotLow;this.graphic=
this.lowerGraphic;g&&(this.plotX=this.plotLowX);b.stateMarkerGraphic&&(b.upperStateMarkerGraphic=b.stateMarkerGraphic,b.stateMarkerGraphic=b.lowerStateMarkerGraphic,b.lowerStateMarkerGraphic=void 0);a.setState.apply(this,arguments)};h.prototype.haloPath=function(){var c=this.series.chart.polar,b=[];this.plotY=this.plotLow;c&&(this.plotX=this.plotLowX);this.isInside&&(b=a.haloPath.apply(this,arguments));this.plotY=this.plotHigh;c&&(this.plotX=this.plotHighX);this.isTopInside&&(b=b.concat(a.haloPath.apply(this,
arguments)));return b};h.prototype.destroyElements=function(){["lowerGraphic","upperGraphic"].forEach(function(a){this[a]&&(this[a]=this[a].destroy())},this);this.graphic=null;return a.destroyElements.apply(this,arguments)};h.prototype.isValid=function(){return k(this.low)&&k(this.high)};return h}(d.prototype.pointClass)});A(d,"Series/AreaRange/AreaRangeSeries.js",[d["Series/AreaRange/AreaRangePoint.js"],d["Series/Area/AreaSeries.js"],d["Core/Series/Series.js"],d["Series/Column/ColumnSeries.js"],
d["Core/Globals.js"],d["Series/Line/LineSeries.js"],d["Core/Utilities.js"]],function(d,c,h,f,a,p,k){var t=this&&this.__extends||function(){var b=function(a,q){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,e){b.__proto__=e}||function(b,e){for(var m in e)e.hasOwnProperty(m)&&(b[m]=e[m])};return b(a,q)};return function(a,q){function r(){this.constructor=a}b(a,q);a.prototype=null===q?Object.create(q):(r.prototype=q.prototype,new r)}}(),w=c.prototype,v=f.prototype,b=a.noop,g=p.prototype,
l=k.defined,z=k.extend,C=k.isArray,H=k.pick,y=k.merge;f=function(a){function f(){var q=null!==a&&a.apply(this,arguments)||this;q.data=void 0;q.options=void 0;q.points=void 0;q.lowerStateMarkerGraphic=void 0;q.xAxis=void 0;q.setStackedPoints=b;return q}t(f,a);f.prototype.toYData=function(b){return[b.low,b.high]};f.prototype.highToXY=function(b){var a=this.chart,e=this.xAxis.postTranslate(b.rectPlotX,this.yAxis.len-b.plotHigh);b.plotHighX=e.x-a.plotLeft;b.plotHigh=e.y-a.plotTop;b.plotLowX=b.plotX};
f.prototype.translate=function(){var b=this,a=b.yAxis,e=!!b.modifyValue;w.translate.apply(b);b.points.forEach(function(m){var u=m.high,n=m.plotY;m.isNull?m.plotY=null:(m.plotLow=n,m.plotHigh=a.translate(e?b.modifyValue(u,m):u,0,1,0,1),e&&(m.yBottom=m.plotHigh))});this.chart.polar&&this.points.forEach(function(e){b.highToXY(e);e.tooltipPos=[(e.plotHighX+e.plotLowX)/2,(e.plotHigh+e.plotLow)/2]})};f.prototype.getGraphPath=function(b){var a=[],e=[],m,u=w.getGraphPath;var n=this.options;var g=this.chart.polar,
q=g&&!1!==n.connectEnds,c=n.connectNulls,l=n.step;b=b||this.points;for(m=b.length;m--;){var f=b[m];var h=g?{plotX:f.rectPlotX,plotY:f.yBottom,doCurve:!1}:{plotX:f.plotX,plotY:f.plotY,doCurve:!1};f.isNull||q||c||b[m+1]&&!b[m+1].isNull||e.push(h);var d={polarPlotY:f.polarPlotY,rectPlotX:f.rectPlotX,yBottom:f.yBottom,plotX:H(f.plotHighX,f.plotX),plotY:f.plotHigh,isNull:f.isNull};e.push(d);a.push(d);f.isNull||q||c||b[m-1]&&!b[m-1].isNull||e.push(h)}b=u.call(this,b);l&&(!0===l&&(l="left"),n.step={left:"right",
center:"center",right:"left"}[l]);a=u.call(this,a);e=u.call(this,e);n.step=l;n=[].concat(b,a);!this.chart.polar&&e[0]&&"M"===e[0][0]&&(e[0]=["L",e[0][1],e[0][2]]);this.graphPath=n;this.areaPath=b.concat(e);n.isArea=!0;n.xMap=b.xMap;this.areaPath.xMap=b.xMap;return n};f.prototype.drawDataLabels=function(){var b=this.points,a=b.length,e,m=[],u=this.options.dataLabels,n,F=this.chart.inverted;if(C(u)){var c=u[0]||{enabled:!1};var l=u[1]||{enabled:!1}}else c=z({},u),c.x=u.xHigh,c.y=u.yHigh,l=z({},u),l.x=
u.xLow,l.y=u.yLow;if(c.enabled||this._hasPointLabels){for(e=a;e--;)if(n=b[e]){var f=c.inside?n.plotHigh<n.plotLow:n.plotHigh>n.plotLow;n.y=n.high;n._plotY=n.plotY;n.plotY=n.plotHigh;m[e]=n.dataLabel;n.dataLabel=n.dataLabelUpper;n.below=f;F?c.align||(c.align=f?"right":"left"):c.verticalAlign||(c.verticalAlign=f?"top":"bottom")}this.options.dataLabels=c;g.drawDataLabels&&g.drawDataLabels.apply(this,arguments);for(e=a;e--;)if(n=b[e])n.dataLabelUpper=n.dataLabel,n.dataLabel=m[e],delete n.dataLabels,n.y=
n.low,n.plotY=n._plotY}if(l.enabled||this._hasPointLabels){for(e=a;e--;)if(n=b[e])f=l.inside?n.plotHigh<n.plotLow:n.plotHigh>n.plotLow,n.below=!f,F?l.align||(l.align=f?"left":"right"):l.verticalAlign||(l.verticalAlign=f?"bottom":"top");this.options.dataLabels=l;g.drawDataLabels&&g.drawDataLabels.apply(this,arguments)}if(c.enabled)for(e=a;e--;)if(n=b[e])n.dataLabels=[n.dataLabelUpper,n.dataLabel].filter(function(b){return!!b});this.options.dataLabels=u};f.prototype.alignDataLabel=function(){v.alignDataLabel.apply(this,
arguments)};f.prototype.drawPoints=function(){var b=this.points.length,a;g.drawPoints.apply(this,arguments);for(a=0;a<b;){var e=this.points[a];e.origProps={plotY:e.plotY,plotX:e.plotX,isInside:e.isInside,negative:e.negative,zone:e.zone,y:e.y};e.lowerGraphic=e.graphic;e.graphic=e.upperGraphic;e.plotY=e.plotHigh;l(e.plotHighX)&&(e.plotX=e.plotHighX);e.y=e.high;e.negative=e.high<(this.options.threshold||0);e.zone=this.zones.length&&e.getZone();this.chart.polar||(e.isInside=e.isTopInside="undefined"!==
typeof e.plotY&&0<=e.plotY&&e.plotY<=this.yAxis.len&&0<=e.plotX&&e.plotX<=this.xAxis.len);a++}g.drawPoints.apply(this,arguments);for(a=0;a<b;)e=this.points[a],e.upperGraphic=e.graphic,e.graphic=e.lowerGraphic,z(e,e.origProps),delete e.origProps,a++};f.defaultOptions=y(c.defaultOptions,{lineWidth:1,threshold:null,tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},trackByArea:!0,dataLabels:{align:void 0,verticalAlign:void 0,
xLow:0,xHigh:0,yLow:0,yHigh:0}});return f}(c);z(f.prototype,{pointArrayMap:["low","high"],pointValKey:"low",deferTranslatePolar:!0,pointClass:d});h.registerSeriesType("arearange",f);"";return f});A(d,"Series/AreaSplineRangeSeries.js",[d["Core/Series/Series.js"]],function(d){d.seriesType("areasplinerange","arearange",null,{getPointSpline:d.seriesTypes.spline.prototype.getPointSpline});""});A(d,"Series/ColumnRangeSeries.js",[d["Core/Series/Series.js"],d["Series/Column/ColumnSeries.js"],d["Core/Globals.js"],
d["Core/Options.js"],d["Core/Utilities.js"]],function(d,c,h,f,a){var p=c.prototype;c=h.noop;f=f.defaultOptions;var k=a.clamp,t=a.merge,w=a.pick,v=d.seriesTypes.arearange.prototype;d.seriesType("columnrange","arearange",t(f.plotOptions.column,f.plotOptions.arearange,{pointRange:null,marker:null,states:{hover:{halo:!1}}}),{setOptions:function(){t(!0,arguments[0],{stacking:void 0});return v.setOptions.apply(this,arguments)},translate:function(){var b=this,a=b.yAxis,c=b.xAxis,f=c.startAngleRad,h,d=b.chart,
t=b.xAxis.isRadial,v=Math.max(d.chartWidth,d.chartHeight)+999,x;p.translate.apply(b);b.points.forEach(function(g){var r=g.shapeArgs,e=b.options.minPointLength;g.plotHigh=x=k(a.translate(g.high,0,1,0,1),-v,v);g.plotLow=k(g.plotY,-v,v);var m=x;var u=w(g.rectPlotY,g.plotY)-x;Math.abs(u)<e?(e-=u,u+=e,m-=e/2):0>u&&(u*=-1,m-=u);t?(h=g.barX+f,g.shapeType="arc",g.shapeArgs=b.polarArc(m+u,m,h,h+g.pointWidth)):(r.height=u,r.y=m,g.tooltipPos=d.inverted?[a.len+a.pos-d.plotLeft-m-u/2,c.len+c.pos-d.plotTop-r.x-
r.width/2,u]:[c.left-d.plotLeft+r.x+r.width/2,a.pos-d.plotTop+m+u/2,u])})},directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:c,getSymbol:c,crispCol:function(){return p.crispCol.apply(this,arguments)},drawPoints:function(){return p.drawPoints.apply(this,arguments)},drawTracker:function(){return p.drawTracker.apply(this,arguments)},getColumnMetrics:function(){return p.getColumnMetrics.apply(this,arguments)},pointAttribs:function(){return p.pointAttribs.apply(this,arguments)},adjustForMissingColumns:function(){return p.adjustForMissingColumns.apply(this,
arguments)},animate:function(){return p.animate.apply(this,arguments)},polarArc:function(){return p.polarArc.apply(this,arguments)},translate3dPoints:function(){return p.translate3dPoints.apply(this,arguments)},translate3dShapes:function(){return p.translate3dShapes.apply(this,arguments)}},{setState:p.pointClass.prototype.setState});""});A(d,"Series/ColumnPyramid/ColumnPyramidSeries.js",[d["Core/Series/Series.js"],d["Series/Column/ColumnSeries.js"],d["Core/Utilities.js"]],function(d,c,h){var f=this&&
this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return a(c,b)};return function(c,b){function g(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(g.prototype=b.prototype,new g)}}(),a=c.prototype,p=h.clamp,k=h.merge,t=h.pick;h=function(d){function h(){var b=null!==d&&d.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=
void 0;return b}f(h,d);h.prototype.translate=function(){var b=this,c=b.chart,f=b.options,d=b.dense=2>b.closestPointRange*b.xAxis.transA;d=b.borderWidth=t(f.borderWidth,d?0:1);var h=b.yAxis,k=f.threshold,v=b.translatedThreshold=h.getThreshold(k),w=t(f.minPointLength,5),x=b.getColumnMetrics(),q=x.width,r=b.barW=Math.max(q,1+2*d),e=b.pointXOffset=x.offset;c.inverted&&(v-=.5);f.pointPadding&&(r=Math.ceil(r));a.translate.apply(b);b.points.forEach(function(m){var a=t(m.yBottom,v),n=999+Math.abs(a),g=p(m.plotY,
-n,h.len+n);n=m.plotX+e;var E=r/2,l=Math.min(g,a);a=Math.max(g,a)-l;var d;m.barX=n;m.pointWidth=q;m.tooltipPos=c.inverted?[h.len+h.pos-c.plotLeft-g,b.xAxis.len-n-E,a]:[n+E,g+h.pos-c.plotTop,a];g=k+(m.total||m.y);"percent"===f.stacking&&(g=k+(0>m.y)?-100:100);g=h.toPixels(g,!0);var G=(d=c.plotHeight-g-(c.plotHeight-v))?E*(l-g)/d:0;var x=d?E*(l+a-g)/d:0;d=n-G+E;G=n+G+E;var z=n+x+E;x=n-x+E;var C=l-w;var B=l+a;0>m.y&&(C=l,B=l+a+w);c.inverted&&(z=c.plotWidth-l,d=g-(c.plotWidth-v),G=E*(g-z)/d,x=E*(g-(z-
a))/d,d=n+E+G,G=d-2*G,z=n-x+E,x=n+x+E,C=l,B=l+a-w,0>m.y&&(B=l+a+w));m.shapeType="path";m.shapeArgs={x:d,y:C,width:G-d,height:a,d:[["M",d,C],["L",G,C],["L",z,B],["L",x,B],["Z"]]}})};h.defaultOptions=k(c.defaultOptions,{});return h}(c);d.registerSeriesType("columnpyramid",h);"";return h});A(d,"Series/GaugeSeries.js",[d["Core/Series/Series.js"],d["Core/Globals.js"],d["Series/Line/LineSeries.js"],d["Core/Color/Palette.js"],d["Core/Utilities.js"]],function(d,c,h,f,a){var p=a.clamp,k=a.isNumber,t=a.merge,
w=a.pick,v=a.pInt;a=c.TrackerMixin;d.seriesType("gauge","line",{dataLabels:{borderColor:f.neutralColor20,borderRadius:3,borderWidth:1,crop:!1,defer:!1,enabled:!0,verticalAlign:"top",y:15,zIndex:2},dial:{},pivot:{},tooltip:{headerFormat:""},showInLegend:!1},{angular:!0,directTouch:!0,drawGraph:c.noop,fixedBox:!0,forceDL:!0,noSharedTooltip:!0,trackerGroups:["group","dataLabelsGroup"],translate:function(){var b=this.yAxis,a=this.options,c=b.center;this.generatePoints();this.points.forEach(function(g){var f=
t(a.dial,g.dial),l=v(w(f.radius,"80%"))*c[2]/200,d=v(w(f.baseLength,"70%"))*l/100,h=v(w(f.rearLength,"10%"))*l/100,x=f.baseWidth||3,q=f.topWidth||1,r=a.overshoot,e=b.startAngleRad+b.translate(g.y,null,null,null,!0);if(k(r)||!1===a.wrap)r=k(r)?r/180*Math.PI:0,e=p(e,b.startAngleRad-r,b.endAngleRad+r);e=180*e/Math.PI;g.shapeType="path";g.shapeArgs={d:f.path||[["M",-h,-x/2],["L",d,-x/2],["L",l,-q/2],["L",l,q/2],["L",d,x/2],["L",-h,x/2],["Z"]],translateX:c[0],translateY:c[1],rotation:e};g.plotX=c[0];g.plotY=
c[1]})},drawPoints:function(){var b=this,a=b.chart,c=b.yAxis.center,d=b.pivot,h=b.options,k=h.pivot,p=a.renderer;b.points.forEach(function(c){var g=c.graphic,q=c.shapeArgs,r=q.d,e=t(h.dial,c.dial);g?(g.animate(q),q.d=r):c.graphic=p[c.shapeType](q).attr({rotation:q.rotation,zIndex:1}).addClass("highcharts-dial").add(b.group);if(!a.styledMode)c.graphic[g?"animate":"attr"]({stroke:e.borderColor||"none","stroke-width":e.borderWidth||0,fill:e.backgroundColor||f.neutralColor100})});d?d.animate({translateX:c[0],
translateY:c[1]}):(b.pivot=p.circle(0,0,w(k.radius,5)).attr({zIndex:2}).addClass("highcharts-pivot").translate(c[0],c[1]).add(b.group),a.styledMode||b.pivot.attr({"stroke-width":k.borderWidth||0,stroke:k.borderColor||f.neutralColor20,fill:k.backgroundColor||f.neutralColor100}))},animate:function(b){var a=this;b||a.points.forEach(function(b){var c=b.graphic;c&&(c.attr({rotation:180*a.yAxis.startAngleRad/Math.PI}),c.animate({rotation:b.shapeArgs.rotation},a.options.animation))})},render:function(){this.group=
this.plotGroup("group","series",this.visible?"visible":"hidden",this.options.zIndex,this.chart.seriesGroup);h.prototype.render.call(this);this.group.clip(this.chart.clipRect)},setData:function(b,a){h.prototype.setData.call(this,b,!1);this.processData();this.generatePoints();w(a,!0)&&this.chart.redraw()},hasData:function(){return!!this.points.length},drawTracker:a&&a.drawTrackerPoint},{setState:function(b){this.state=b}});""});A(d,"Series/BoxPlot/BoxPlotSeries.js",[d["Core/Series/Series.js"],d["Series/Column/ColumnSeries.js"],
d["Core/Globals.js"],d["Core/Color/Palette.js"],d["Core/Utilities.js"]],function(d,c,h,f,a){var p=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return a(b,c)};return function(b,c){function g(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(g.prototype=c.prototype,new g)}}();h=h.noop;var k=a.extend,t=a.merge,w=a.pick;a=function(a){function b(){var b=
null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}p(b,a);b.prototype.pointAttribs=function(){return{}};b.prototype.translate=function(){var b=this.yAxis,c=this.pointArrayMap;a.prototype.translate.apply(this);this.points.forEach(function(a){c.forEach(function(c){null!==a[c]&&(a[c+"Plot"]=b.translate(a[c],0,1,0,1))});a.plotHigh=a.highPlot})};b.prototype.drawPoints=function(){var b=this,a=b.options,c=b.chart,f=c.renderer,d,h,k,x,q,r,e=0,m,u,n,F,E=!1!==b.doQuartiles,
D,p=b.options.whiskerLength;b.points.forEach(function(g){var l=g.graphic,t=l?"animate":"attr",G=g.shapeArgs,I={},v={},z={},C={},B=g.color||b.color;"undefined"!==typeof g.plotY&&(m=Math.round(G.width),u=Math.floor(G.x),n=u+m,F=Math.round(m/2),d=Math.floor(E?g.q1Plot:g.lowPlot),h=Math.floor(E?g.q3Plot:g.lowPlot),k=Math.floor(g.highPlot),x=Math.floor(g.lowPlot),l||(g.graphic=l=f.g("point").add(b.group),g.stem=f.path().addClass("highcharts-boxplot-stem").add(l),p&&(g.whiskers=f.path().addClass("highcharts-boxplot-whisker").add(l)),
E&&(g.box=f.path(void 0).addClass("highcharts-boxplot-box").add(l)),g.medianShape=f.path(void 0).addClass("highcharts-boxplot-median").add(l)),c.styledMode||(v.stroke=g.stemColor||a.stemColor||B,v["stroke-width"]=w(g.stemWidth,a.stemWidth,a.lineWidth),v.dashstyle=g.stemDashStyle||a.stemDashStyle||a.dashStyle,g.stem.attr(v),p&&(z.stroke=g.whiskerColor||a.whiskerColor||B,z["stroke-width"]=w(g.whiskerWidth,a.whiskerWidth,a.lineWidth),z.dashstyle=g.whiskerDashStyle||a.whiskerDashStyle||a.dashStyle,g.whiskers.attr(z)),
E&&(I.fill=g.fillColor||a.fillColor||B,I.stroke=a.lineColor||B,I["stroke-width"]=a.lineWidth||0,I.dashstyle=g.boxDashStyle||a.boxDashStyle||a.dashStyle,g.box.attr(I)),C.stroke=g.medianColor||a.medianColor||B,C["stroke-width"]=w(g.medianWidth,a.medianWidth,a.lineWidth),C.dashstyle=g.medianDashStyle||a.medianDashStyle||a.dashStyle,g.medianShape.attr(C)),r=g.stem.strokeWidth()%2/2,e=u+F+r,l=[["M",e,h],["L",e,k],["M",e,d],["L",e,x]],g.stem[t]({d:l}),E&&(r=g.box.strokeWidth()%2/2,d=Math.floor(d)+r,h=Math.floor(h)+
r,u+=r,n+=r,l=[["M",u,h],["L",u,d],["L",n,d],["L",n,h],["L",u,h],["Z"]],g.box[t]({d:l})),p&&(r=g.whiskers.strokeWidth()%2/2,k+=r,x+=r,D=/%$/.test(p)?F*parseFloat(p)/100:p/2,l=[["M",e-D,k],["L",e+D,k],["M",e-D,x],["L",e+D,x]],g.whiskers[t]({d:l})),q=Math.round(g.medianPlot),r=g.medianShape.strokeWidth()%2/2,q+=r,l=[["M",u,q],["L",n,q]],g.medianShape[t]({d:l}))})};b.prototype.toYData=function(b){return[b.low,b.q1,b.median,b.q3,b.high]};b.defaultOptions=t(c.defaultOptions,{threshold:null,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Maximum: {point.high}<br/>Upper quartile: {point.q3}<br/>Median: {point.median}<br/>Lower quartile: {point.q1}<br/>Minimum: {point.low}<br/>'},
whiskerLength:"50%",fillColor:f.backgroundColor,lineWidth:1,medianWidth:2,whiskerWidth:2});return b}(c);k(a.prototype,{pointArrayMap:["low","q1","median","q3","high"],pointValKey:"high",drawDataLabels:h,setStackedPoints:h});d.registerSeriesType("boxplot",a);"";return a});A(d,"Series/ErrorBar/ErrorBarSeries.js",[d["Core/Series/Series.js"],d["Series/BoxPlot/BoxPlotSeries.js"],d["Series/Column/ColumnSeries.js"],d["Core/Color/Palette.js"],d["Core/Utilities.js"]],function(d,c,h,f,a){var p=this&&this.__extends||
function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return a(b,c)};return function(b,c){function g(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(g.prototype=c.prototype,new g)}}(),k=d.seriesTypes.arearange,t=a.merge;a=a.extend;var w=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;
return b}p(b,a);b.prototype.getColumnMetrics=function(){return this.linkedParent&&this.linkedParent.columnMetrics||h.prototype.getColumnMetrics.call(this)};b.prototype.drawDataLabels=function(){var b=this.pointValKey;k&&(k.prototype.drawDataLabels.call(this),this.data.forEach(function(a){a.y=a[b]}))};b.prototype.toYData=function(b){return[b.low,b.high]};b.defaultOptions=t(c.defaultOptions,{color:f.neutralColor100,grouping:!1,linkedTo:":previous",tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},
whiskerWidth:null});return b}(c);a(w.prototype,{pointArrayMap:["low","high"],pointValKey:"high",doQuartiles:!1});d.registerSeriesType("errorbar",w);"";return w});A(d,"Series/WaterfallSeries.js",[d["Core/Axis/Axis.js"],d["Core/Series/Series.js"],d["Core/Chart/Chart.js"],d["Series/Line/LineSeries.js"],d["Core/Color/Palette.js"],d["Core/Series/Point.js"],d["Extensions/Stacking.js"],d["Core/Utilities.js"]],function(d,c,h,f,a,p,k,t){var w=c.seriesTypes,v=t.addEvent,b=t.arrayMax,g=t.arrayMin,l=t.correctFloat,
z=t.isNumber,C=t.objectEach,y=t.pick,A;(function(b){function a(){var b=this.waterfall.stacks;b&&(b.changed=!1,delete b.alreadyChanged)}function c(){var b=this.options.stackLabels;b&&b.enabled&&this.waterfall.stacks&&this.waterfall.renderStackTotals()}function r(){for(var b=this.axes,a=this.series,e=a.length;e--;)a[e].options.stacking&&(b.forEach(function(b){b.isXAxis||(b.waterfall.stacks.changed=!0)}),e=0)}function e(){this.waterfall||(this.waterfall=new m(this))}var m=function(){function b(b){this.axis=
b;this.stacks={changed:!1}}b.prototype.renderStackTotals=function(){var b=this.axis,a=b.waterfall.stacks,e=b.stacking&&b.stacking.stackTotalGroup,m=new k(b,b.options.stackLabels,!1,0,void 0);this.dummyStackItem=m;C(a,function(b){C(b,function(b){m.total=b.stackTotal;b.label&&(m.label=b.label);k.prototype.render.call(m,e);b.label=m.label;delete m.label})});m.total=null};return b}();b.Composition=m;b.compose=function(b,m){v(b,"init",e);v(b,"afterBuildStacks",a);v(b,"afterRender",c);v(m,"beforeRedraw",
r)}})(A||(A={}));c.seriesType("waterfall","column",{dataLabels:{inside:!0},lineWidth:1,lineColor:a.neutralColor80,dashStyle:"Dot",borderColor:a.neutralColor80,states:{hover:{lineWidthPlus:0}}},{pointValKey:"y",showLine:!0,generatePoints:function(){var b;w.column.prototype.generatePoints.apply(this);var a=0;for(b=this.points.length;a<b;a++){var c=this.points[a];var r=this.processedYData[a];if(c.isIntermediateSum||c.isSum)c.y=l(r)}},translate:function(){var b=this.options,a=this.yAxis,c,r=y(b.minPointLength,
5),e=r/2,m=b.threshold,u=b.stacking,n=a.waterfall.stacks[this.stackKey];w.column.prototype.translate.apply(this);var g=c=m;var f=this.points;var d=0;for(b=f.length;d<b;d++){var h=f[d];var l=this.processedYData[d];var k=h.shapeArgs;var p=[0,l];var t=h.y;if(u){if(n){p=n[d];if("overlap"===u){var v=p.stackState[p.stateIndex--];v=0<=t?v:v-t;Object.hasOwnProperty.call(p,"absolutePos")&&delete p.absolutePos;Object.hasOwnProperty.call(p,"absoluteNeg")&&delete p.absoluteNeg}else 0<=t?(v=p.threshold+p.posTotal,
p.posTotal-=t):(v=p.threshold+p.negTotal,p.negTotal-=t,v-=t),!p.posTotal&&Object.hasOwnProperty.call(p,"absolutePos")&&(p.posTotal=p.absolutePos,delete p.absolutePos),!p.negTotal&&Object.hasOwnProperty.call(p,"absoluteNeg")&&(p.negTotal=p.absoluteNeg,delete p.absoluteNeg);h.isSum||(p.connectorThreshold=p.threshold+p.stackTotal);a.reversed?(l=0<=t?v-t:v+t,t=v):(l=v,t=v-t);h.below=l<=y(m,0);k.y=a.translate(l,0,1,0,1);k.height=Math.abs(k.y-a.translate(t,0,1,0,1))}if(t=a.waterfall.dummyStackItem)t.x=
d,t.label=n[d].label,t.setOffset(this.pointXOffset||0,this.barW||0,this.stackedYNeg[d],this.stackedYPos[d])}else v=Math.max(g,g+t)+p[0],k.y=a.translate(v,0,1,0,1),h.isSum?(k.y=a.translate(p[1],0,1,0,1),k.height=Math.min(a.translate(p[0],0,1,0,1),a.len)-k.y):h.isIntermediateSum?(0<=t?(l=p[1]+c,t=c):(l=c,t=p[1]+c),a.reversed&&(l^=t,t^=l,l^=t),k.y=a.translate(l,0,1,0,1),k.height=Math.abs(k.y-Math.min(a.translate(t,0,1,0,1),a.len)),c+=p[1]):(k.height=0<l?a.translate(g,0,1,0,1)-k.y:a.translate(g,0,1,0,
1)-a.translate(g-l,0,1,0,1),g+=l,h.below=g<y(m,0)),0>k.height&&(k.y+=k.height,k.height*=-1);h.plotY=k.y=Math.round(k.y)-this.borderWidth%2/2;k.height=Math.max(Math.round(k.height),.001);h.yBottom=k.y+k.height;k.height<=r&&!h.isNull?(k.height=r,k.y-=e,h.plotY=k.y,h.minPointLengthOffset=0>h.y?-e:e):(h.isNull&&(k.width=0),h.minPointLengthOffset=0);k=h.plotY+(h.negative?k.height:0);this.chart.inverted?h.tooltipPos[0]=a.len-k:h.tooltipPos[1]=k}},processData:function(b){var a=this.options,c=this.yData,
r=a.data,e=c.length,m=a.threshold||0,u,n,g,d,h;for(h=n=u=g=d=0;h<e;h++){var k=c[h];var p=r&&r[h]?r[h]:{};"sum"===k||p.isSum?c[h]=l(n):"intermediateSum"===k||p.isIntermediateSum?(c[h]=l(u),u=0):(n+=k,u+=k);g=Math.min(n,g);d=Math.max(n,d)}f.prototype.processData.call(this,b);a.stacking||(this.dataMin=g+m,this.dataMax=d)},toYData:function(b){return b.isSum?"sum":b.isIntermediateSum?"intermediateSum":b.y},updateParallelArrays:function(b,a){f.prototype.updateParallelArrays.call(this,b,a);if("sum"===this.yData[0]||
"intermediateSum"===this.yData[0])this.yData[0]=null},pointAttribs:function(b,a){var c=this.options.upColor;c&&!b.options.color&&(b.color=0<b.y?c:null);b=w.column.prototype.pointAttribs.call(this,b,a);delete b.dashstyle;return b},getGraphPath:function(){return[["M",0,0]]},getCrispPath:function(){var b=this.data,a=this.yAxis,c=b.length,r=Math.round(this.graph.strokeWidth())%2/2,e=Math.round(this.borderWidth)%2/2,m=this.xAxis.reversed,u=this.yAxis.reversed,n=this.options.stacking,g=[],f;for(f=1;f<c;f++){var d=
b[f].shapeArgs;var h=b[f-1];var l=b[f-1].shapeArgs;var k=a.waterfall.stacks[this.stackKey];var p=0<h.y?-l.height:0;k&&l&&d&&(k=k[f-1],n?(k=k.connectorThreshold,p=Math.round(a.translate(k,0,1,0,1)+(u?p:0))-r):p=l.y+h.minPointLengthOffset+e-r,g.push(["M",(l.x||0)+(m?0:l.width||0),p],["L",(d.x||0)+(m?d.width||0:0),p]));!n&&g.length&&l&&(0>h.y&&!u||0<h.y&&u)&&(g[g.length-2][2]+=l.height,g[g.length-1][2]+=l.height)}return g},drawGraph:function(){f.prototype.drawGraph.call(this);this.graph.attr({d:this.getCrispPath()})},
setStackedPoints:function(){function b(b,a,e,m){if(y)for(e;e<y;e++)v.stackState[e]+=m;else v.stackState[0]=b,y=v.stackState.length;v.stackState.push(v.stackState[y-1]+a)}var a=this.options,c=this.yAxis.waterfall.stacks,r=a.threshold,e=r||0,m=e,u=this.stackKey,n=this.xData,g=n.length,f,d,h;this.yAxis.stacking.usePercentage=!1;var l=d=h=e;if(this.visible||!this.chart.options.chart.ignoreHiddenSeries){var k=c.changed;(f=c.alreadyChanged)&&0>f.indexOf(u)&&(k=!0);c[u]||(c[u]={});f=c[u];for(var p=0;p<g;p++){var t=
n[p];if(!f[t]||k)f[t]={negTotal:0,posTotal:0,stackTotal:0,threshold:0,stateIndex:0,stackState:[],label:k&&f[t]?f[t].label:void 0};var v=f[t];var w=this.yData[p];0<=w?v.posTotal+=w:v.negTotal+=w;var z=a.data[p];t=v.absolutePos=v.posTotal;var C=v.absoluteNeg=v.negTotal;v.stackTotal=t+C;var y=v.stackState.length;z&&z.isIntermediateSum?(b(h,d,0,h),h=d,d=r,e^=m,m^=e,e^=m):z&&z.isSum?(b(r,l,y),e=r):(b(e,w,0,l),z&&(l+=w,d+=w));v.stateIndex++;v.threshold=e;e+=v.stackTotal}c.changed=!1;c.alreadyChanged||(c.alreadyChanged=
[]);c.alreadyChanged.push(u)}},getExtremes:function(){var a=this.options.stacking;if(a){var c=this.yAxis;c=c.waterfall.stacks;var f=this.stackedYNeg=[];var r=this.stackedYPos=[];"overlap"===a?C(c[this.stackKey],function(a){f.push(g(a.stackState));r.push(b(a.stackState))}):C(c[this.stackKey],function(b){f.push(b.negTotal+b.threshold);r.push(b.posTotal+b.threshold)});return{dataMin:g(f),dataMax:b(r)}}return{dataMin:this.dataMin,dataMax:this.dataMax}}},{getClassName:function(){var b=p.prototype.getClassName.call(this);
this.isSum?b+=" highcharts-sum":this.isIntermediateSum&&(b+=" highcharts-intermediate-sum");return b},isValid:function(){return z(this.y)||this.isSum||!!this.isIntermediateSum}});"";A.compose(d,h);return A});A(d,"Series/PolygonSeries.js",[d["Core/Series/Series.js"],d["Core/Globals.js"],d["Mixins/LegendSymbol.js"],d["Series/Line/LineSeries.js"]],function(d,c,h,f){var a=d.seriesTypes;d.seriesType("polygon","scatter",{marker:{enabled:!1,states:{hover:{enabled:!1}}},stickyTracking:!1,tooltip:{followPointer:!0,
pointFormat:""},trackByArea:!0},{type:"polygon",getGraphPath:function(){for(var a=f.prototype.getGraphPath.call(this),c=a.length+1;c--;)(c===a.length||"M"===a[c][0])&&0<c&&a.splice(c,0,["Z"]);return this.areaPath=a},drawGraph:function(){this.options.fillColor=this.color;a.area.prototype.drawGraph.call(this)},drawLegendSymbol:h.drawRectangle,drawTracker:f.prototype.drawTracker,setStackedPoints:c.noop});""});A(d,"Series/Bubble/BubblePoint.js",[d["Core/Series/Series.js"],d["Core/Series/Point.js"],d["Core/Utilities.js"]],
function(d,c,h){var f=this&&this.__extends||function(){var a=function(c,f){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var f in c)c.hasOwnProperty(f)&&(a[f]=c[f])};return a(c,f)};return function(c,f){function d(){this.constructor=c}a(c,f);c.prototype=null===f?Object.create(f):(d.prototype=f.prototype,new d)}}();h=h.extend;d=function(a){function d(){var c=null!==a&&a.apply(this,arguments)||this;c.options=void 0;c.series=void 0;return c}f(d,
a);d.prototype.haloPath=function(a){return c.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)};return d}(d.seriesTypes.scatter.prototype.pointClass);h(d.prototype,{ttBelow:!1});return d});A(d,"Series/Bubble/BubbleLegend.js",[d["Core/Chart/Chart.js"],d["Core/Color/Color.js"],d["Core/Globals.js"],d["Core/Legend.js"],d["Series/Line/LineSeries.js"],d["Core/Color/Palette.js"],d["Core/Utilities.js"]],function(d,c,h,f,a,p,k){var t=c.parse,w=h.noop;c=k.addEvent;var v=k.arrayMax,
b=k.arrayMin,g=k.isNumber,l=k.merge,z=k.objectEach,C=k.pick,y=k.setOptions,A=k.stableSort,B=k.wrap;"";y({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},
sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});y=function(){function a(b,a){this.options=this.symbols=this.visible=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=w;this.init(b,a)}a.prototype.init=function(b,a){this.options=b;this.visible=!0;this.chart=a.chart;this.legend=a};a.prototype.addToLegend=function(b){b.splice(this.options.legendIndex,
0,this)};a.prototype.drawLegendSymbol=function(b){var a=this.chart,e=this.options,m=C(b.options.itemDistance,20),c=e.ranges;var n=e.connectorDistance;this.fontMetrics=a.renderer.fontMetrics(e.labels.style.fontSize.toString()+"px");c&&c.length&&g(c[0].value)?(A(c,function(b,a){return a.value-b.value}),this.ranges=c,this.setOptions(),this.render(),a=this.getMaxLabelSize(),c=this.ranges[0].radius,b=2*c,n=n-c+a.width,n=0<n?n:0,this.maxLabel=a,this.movementX="left"===e.labels.align?n:0,this.legendItemWidth=
b+n+m,this.legendItemHeight=b+this.fontMetrics.h/2):b.options.bubbleLegend.autoRanges=!0};a.prototype.setOptions=function(){var b=this.ranges,a=this.options,e=this.chart.series[a.seriesIndex],m=this.legend.baseline,c={"z-index":a.zIndex,"stroke-width":a.borderWidth},n={"z-index":a.zIndex,"stroke-width":a.connectorWidth},g=this.getLabelStyles(),f=e.options.marker.fillOpacity,d=this.chart.styledMode;b.forEach(function(u,r){d||(c.stroke=C(u.borderColor,a.borderColor,e.color),c.fill=C(u.color,a.color,
1!==f?t(e.color).setOpacity(f).get("rgba"):e.color),n.stroke=C(u.connectorColor,a.connectorColor,e.color));b[r].radius=this.getRangeRadius(u.value);b[r]=l(b[r],{center:b[0].radius-b[r].radius+m});d||l(!0,b[r],{bubbleStyle:l(!1,c),connectorStyle:l(!1,n),labelStyle:g})},this)};a.prototype.getLabelStyles=function(){var b=this.options,a={},e="left"===b.labels.align,m=this.legend.options.rtl;z(b.labels.style,function(b,e){"color"!==e&&"fontSize"!==e&&"z-index"!==e&&(a[e]=b)});return l(!1,a,{"font-size":b.labels.style.fontSize,
fill:C(b.labels.style.color,p.neutralColor100),"z-index":b.zIndex,align:m||e?"right":"left"})};a.prototype.getRangeRadius=function(b){var a=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,a.ranges[a.ranges.length-1].value,a.ranges[0].value,a.minSize,a.maxSize,b)};a.prototype.render=function(){var b=this.chart.renderer,a=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=b.g("bubble-legend");this.legendItem=
b.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(b){b.value>=a&&this.renderRange(b)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};a.prototype.renderRange=function(b){var a=this.options,e=a.labels,m=this.chart.renderer,c=this.symbols,n=c.labels,g=b.center,f=Math.abs(b.radius),d=a.connectorDistance||0,h=e.align,l=e.style.fontSize;d=this.legend.options.rtl||"left"===
h?-d:d;e=a.connectorWidth;var k=this.ranges[0].radius||0,p=g-f-a.borderWidth/2+e/2;l=l/2-(this.fontMetrics.h-l)/2;var q=m.styledMode;"center"===h&&(d=0,a.connectorDistance=0,b.labelStyle.align="center");h=p+a.labels.y;var t=k+d+a.labels.x;c.bubbleItems.push(m.circle(k,g+((p%1?1:.5)-(e%2?0:.5)),f).attr(q?{}:b.bubbleStyle).addClass((q?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-symbol "+(a.className||"")).add(this.legendSymbol));c.connectors.push(m.path(m.crispLine([["M",
k,p],["L",k+d,p]],a.connectorWidth)).attr(q?{}:b.connectorStyle).addClass((q?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(a.connectorClassName||"")).add(this.legendSymbol));b=m.text(this.formatLabel(b),t,h+l).attr(q?{}:b.labelStyle).addClass("highcharts-bubble-legend-labels "+(a.labels.className||"")).add(this.legendSymbol);n.push(b);b.placed=!0;b.alignAttr={x:t,y:h+l}};a.prototype.getMaxLabelSize=function(){var b,a;this.symbols.labels.forEach(function(e){a=
e.getBBox(!0);b=b?a.width>b.width?a:b:a});return b||{}};a.prototype.formatLabel=function(b){var a=this.options,e=a.labels.formatter;a=a.labels.format;var m=this.chart.numberFormatter;return a?k.format(a,b):e?e.call(b):m(b.value,1)};a.prototype.hideOverlappingLabels=function(){var b=this.chart,a=this.symbols;!this.options.labels.allowOverlap&&a&&(b.hideOverlappingLabels(a.labels),a.labels.forEach(function(b,m){b.newOpacity?b.newOpacity!==b.oldOpacity&&a.connectors[m].show():a.connectors[m].hide()}))};
a.prototype.getRanges=function(){var a=this.legend.bubbleLegend,c=a.options.ranges,e,m=Number.MAX_VALUE,u=-Number.MAX_VALUE;a.chart.series.forEach(function(a){a.isBubble&&!a.ignoreSeries&&(e=a.zData.filter(g),e.length&&(m=C(a.options.zMin,Math.min(m,Math.max(b(e),!1===a.options.displayNegative?a.options.zThreshold:-Number.MAX_VALUE))),u=C(a.options.zMax,Math.max(u,v(e)))))});var n=m===u?[{value:u}]:[{value:m},{value:(m+u)/2},{value:u,autoRanges:!0}];c.length&&c[0].radius&&n.reverse();n.forEach(function(b,
a){c&&c[a]&&(n[a]=l(!1,c[a],b))});return n};a.prototype.predictBubbleSizes=function(){var b=this.chart,a=this.fontMetrics,e=b.legend.options,c="horizontal"===e.layout,g=c?b.legend.lastLineHeight:0,n=b.plotSizeX,f=b.plotSizeY,d=b.series[this.options.seriesIndex];b=Math.ceil(d.minPxSize);var h=Math.ceil(d.maxPxSize);d=d.options.maxSize;var l=Math.min(f,n);if(e.floating||!/%$/.test(d))a=h;else if(d=parseFloat(d),a=(l+g-a.h/2)*d/100/(d/100+1),c&&f-a>=n||!c&&n-a>=f)a=h;return[b,Math.ceil(a)]};a.prototype.updateRanges=
function(b,a){var e=this.legend.options.bubbleLegend;e.minSize=b;e.maxSize=a;e.ranges=this.getRanges()};a.prototype.correctSizes=function(){var b=this.legend,a=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(a.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,a.maxPxSize),b.render())};return a}();c(f,"afterGetAllItems",function(b){var a=this.bubbleLegend,c=this.options,e=c.bubbleLegend,m=this.chart.getVisibleBubbleSeriesIndex();a&&a.ranges&&a.ranges.length&&
(e.ranges.length&&(e.autoRanges=!!e.ranges[0].autoRanges),this.destroyItem(a));0<=m&&c.enabled&&e.enabled&&(e.seriesIndex=m,this.bubbleLegend=new h.BubbleLegend(e,this),this.bubbleLegend.addToLegend(b.allItems))});d.prototype.getVisibleBubbleSeriesIndex=function(){for(var b=this.series,a=0;a<b.length;){if(b[a]&&b[a].isBubble&&b[a].visible&&b[a].zData.length)return a;a++}return-1};f.prototype.getLinesHeights=function(){var b=this.allItems,a=[],c=b.length,e,m=0;for(e=0;e<c;e++)if(b[e].legendItemHeight&&
(b[e].itemHeight=b[e].legendItemHeight),b[e]===b[c-1]||b[e+1]&&b[e]._legendItemPos[1]!==b[e+1]._legendItemPos[1]){a.push({height:0});var g=a[a.length-1];for(m;m<=e;m++)b[m].itemHeight>g.height&&(g.height=b[m].itemHeight);g.step=e}return a};f.prototype.retranslateItems=function(b){var a,c,e,m=this.options.rtl,g=0;this.allItems.forEach(function(n,d){a=n.legendGroup.translateX;c=n._legendItemPos[1];if((e=n.movementX)||m&&n.ranges)e=m?a-n.options.maxSize/2:a+e,n.legendGroup.attr({translateX:e});d>b[g].step&&
g++;n.legendGroup.attr({translateY:Math.round(c+b[g].height/2)});n._legendItemPos[1]=c+b[g].height/2})};c(a,"legendItemClick",function(){var b=this.chart,a=this.visible,c=this.chart.legend;c&&c.bubbleLegend&&(this.visible=!a,this.ignoreSeries=a,b=0<=b.getVisibleBubbleSeriesIndex(),c.bubbleLegend.visible!==b&&(c.update({bubbleLegend:{enabled:b}}),c.bubbleLegend.visible=b),this.visible=a)});B(d.prototype,"drawChartBox",function(b,a,c){var e=this.legend,m=0<=this.getVisibleBubbleSeriesIndex();if(e&&
e.options.enabled&&e.bubbleLegend&&e.options.bubbleLegend.autoRanges&&m){var g=e.bubbleLegend.options;m=e.bubbleLegend.predictBubbleSizes();e.bubbleLegend.updateRanges(m[0],m[1]);g.placed||(e.group.placed=!1,e.allItems.forEach(function(b){b.legendGroup.translateY=null}));e.render();this.getMargins();this.axes.forEach(function(b){b.visible&&b.render();g.placed||(b.setScale(),b.updateNames(),z(b.ticks,function(b){b.isNew=!0;b.isNewLabel=!0}))});g.placed=!0;this.getMargins();b.call(this,a,c);e.bubbleLegend.correctSizes();
e.retranslateItems(e.getLinesHeights())}else b.call(this,a,c),e&&e.options.enabled&&e.bubbleLegend&&(e.render(),e.retranslateItems(e.getLinesHeights()))});h.BubbleLegend=y;return h.BubbleLegend});A(d,"Series/Bubble/BubbleSeries.js",[d["Core/Axis/Axis.js"],d["Core/Series/Series.js"],d["Series/Bubble/BubblePoint.js"],d["Core/Color/Color.js"],d["Core/Globals.js"],d["Series/Line/LineSeries.js"],d["Core/Utilities.js"]],function(d,c,h,f,a,p,k){var t=this&&this.__extends||function(){var b=function(a,c){b=
Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return b(a,c)};return function(a,c){function e(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),w=c.seriesTypes,v=w.column,b=w.scatter,g=f.parse;f=a.noop;var l=k.arrayMax,z=k.arrayMin,C=k.clamp,y=k.extend,A=k.isNumber,B=k.merge,x=k.pick,q=k.pInt;k=function(a){function c(){var b=null!==a&&a.apply(this,
arguments)||this;b.data=void 0;b.maxPxSize=void 0;b.minPxSize=void 0;b.options=void 0;b.points=void 0;b.radii=void 0;b.yData=void 0;b.zData=void 0;return b}t(c,a);c.prototype.animate=function(b){!b&&this.points.length<this.options.animationLimit&&this.points.forEach(function(b){var a=b.graphic;a&&a.width&&(this.hasRendered||a.attr({x:b.plotX,y:b.plotY,width:1,height:1}),a.animate(this.markerAttribs(b),this.options.animation))},this)};c.prototype.getRadii=function(b,a,c){var e=this.zData,m=this.yData,
g=c.minPxSize,n=c.maxPxSize,d=[];var f=0;for(c=e.length;f<c;f++){var u=e[f];d.push(this.getRadius(b,a,g,n,u,m[f]))}this.radii=d};c.prototype.getRadius=function(b,a,c,e,g,d){var m=this.options,n="width"!==m.sizeBy,f=m.zThreshold,u=a-b,h=.5;if(null===d||null===g)return null;if(A(g)){m.sizeByAbsoluteValue&&(g=Math.abs(g-f),u=Math.max(a-f,Math.abs(b-f)),b=0);if(g<b)return c/2-1;0<u&&(h=(g-b)/u)}n&&0<=h&&(h=Math.sqrt(h));return Math.ceil(c+h*(e-c))/2};c.prototype.hasData=function(){return!!this.processedXData.length};
c.prototype.pointAttribs=function(b,a){var c=this.options.marker.fillOpacity;b=p.prototype.pointAttribs.call(this,b,a);1!==c&&(b.fill=g(b.fill).setOpacity(c).get("rgba"));return b};c.prototype.translate=function(){var b,c=this.data,e=this.radii;a.prototype.translate.call(this);for(b=c.length;b--;){var g=c[b];var d=e?e[b]:0;A(d)&&d>=this.minPxSize/2?(g.marker=y(g.marker,{radius:d,width:2*d,height:2*d}),g.dlBox={x:g.plotX-d,y:g.plotY-d,width:2*d,height:2*d}):g.shapeArgs=g.plotY=g.dlBox=void 0}};c.defaultOptions=
B(b.defaultOptions,{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"});return c}(b);y(k.prototype,{alignDataLabel:v.prototype.alignDataLabel,applyZones:f,bubblePadding:!0,
buildKDTree:f,directTouch:!0,isBubble:!0,pointArrayMap:["y","z"],pointClass:h,parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",zoneAxis:"z"});d.prototype.beforePadding=function(){var b=this,a=this.len,c=this.chart,g=0,d=a,f=this.isXAxis,h=f?"xData":"yData",k=this.min,p={},t=Math.min(c.plotWidth,c.plotHeight),v=Number.MAX_VALUE,w=-Number.MAX_VALUE,y=this.max-k,B=a/y,H=[];this.series.forEach(function(a){var e=a.options;!a.bubblePadding||!a.visible&&c.options.chart.ignoreHiddenSeries||
(b.allowZoomOutside=!0,H.push(a),f&&(["minSize","maxSize"].forEach(function(b){var a=e[b],c=/%$/.test(a);a=q(a);p[b]=c?t*a/100:a}),a.minPxSize=p.minSize,a.maxPxSize=Math.max(p.maxSize,p.minSize),a=a.zData.filter(A),a.length&&(v=x(e.zMin,C(z(a),!1===e.displayNegative?e.zThreshold:-Number.MAX_VALUE,v)),w=x(e.zMax,Math.max(w,l(a))))))});H.forEach(function(a){var c=a[h],e=c.length;f&&a.getRadii(v,w,a);if(0<y)for(;e--;)if(A(c[e])&&b.dataMin<=c[e]&&c[e]<=b.max){var m=a.radii?a.radii[e]:0;g=Math.min((c[e]-
k)*B-m,g);d=Math.max((c[e]-k)*B+m,d)}});H.length&&0<y&&!this.logarithmic&&(d-=a,B*=(a+Math.max(0,g)-Math.min(d,a))/a,[["min","userMin",g],["max","userMax",d]].forEach(function(a){"undefined"===typeof x(b.options[a[0]],b[a[1]])&&(b[a[0]]+=a[2]/B)}))};c.registerSeriesType("bubble",k);"";"";return k});A(d,"Series/PackedBubble/PackedBubblePoint.js",[d["Core/Series/Series.js"],d["Core/Chart/Chart.js"],d["Core/Series/Point.js"]],function(d,c,h){var f=this&&this.__extends||function(){var a=function(c,d){a=
Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d])};return a(c,d)};return function(c,d){function f(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):(f.prototype=d.prototype,new f)}}();return function(a){function d(){var c=null!==a&&a.apply(this,arguments)||this;c.degree=NaN;c.mass=NaN;c.radius=NaN;c.options=void 0;c.series=void 0;c.value=null;return c}f(d,a);d.prototype.destroy=function(){this.series.layout&&
this.series.layout.removeElementFromCollection(this,this.series.layout.nodes);return h.prototype.destroy.apply(this,arguments)};d.prototype.firePointEvent=function(){var a=this.series.options;if(this.isParentNode&&a.parentNode){var c=a.allowPointSelect;a.allowPointSelect=a.parentNode.allowPointSelect;h.prototype.firePointEvent.apply(this,arguments);a.allowPointSelect=c}else h.prototype.firePointEvent.apply(this,arguments)};d.prototype.select=function(){var a=this.series.chart;this.isParentNode?(a.getSelectedPoints=
a.getSelectedParentNodes,h.prototype.select.apply(this,arguments),a.getSelectedPoints=c.prototype.getSelectedPoints):h.prototype.select.apply(this,arguments)};return d}(d.seriesTypes.bubble.prototype.pointClass)});A(d,"Series/Networkgraph/DraggableNodes.js",[d["Core/Chart/Chart.js"],d["Core/Globals.js"],d["Core/Utilities.js"]],function(d,c,h){var f=h.addEvent;c.dragNodesMixin={onMouseDown:function(a,c){c=this.chart.pointer.normalize(c);a.fixedPosition={chartX:c.chartX,chartY:c.chartY,plotX:a.plotX,
plotY:a.plotY};a.inDragMode=!0},onMouseMove:function(a,c){if(a.fixedPosition&&a.inDragMode){var d=this.chart;c=d.pointer.normalize(c);var f=a.fixedPosition.chartX-c.chartX,h=a.fixedPosition.chartY-c.chartY;c=d.graphLayoutsLookup;if(5<Math.abs(f)||5<Math.abs(h))f=a.fixedPosition.plotX-f,h=a.fixedPosition.plotY-h,d.isInsidePlot(f,h)&&(a.plotX=f,a.plotY=h,a.hasDragged=!0,this.redrawHalo(a),c.forEach(function(a){a.restartSimulation()}))}},onMouseUp:function(a,c){a.fixedPosition&&(a.hasDragged&&(this.layout.enableSimulation?
this.layout.start():this.chart.redraw()),a.inDragMode=a.hasDragged=!1,this.options.fixedDraggable||delete a.fixedPosition)},redrawHalo:function(a){a&&this.halo&&this.halo.attr({d:a.haloPath(this.options.states.hover.halo.size)})}};f(d,"load",function(){var a=this,c,d,h;a.container&&(c=f(a.container,"mousedown",function(c){var k=a.hoverPoint;k&&k.series&&k.series.hasDraggableNodes&&k.series.options.draggable&&(k.series.onMouseDown(k,c),d=f(a.container,"mousemove",function(b){return k&&k.series&&k.series.onMouseMove(k,
b)}),h=f(a.container.ownerDocument,"mouseup",function(b){d();h();return k&&k.series&&k.series.onMouseUp(k,b)}))}));f(a,"destroy",function(){c()})})});A(d,"Series/Networkgraph/Integrations.js",[d["Core/Globals.js"]],function(d){d.networkgraphIntegrations={verlet:{attractiveForceFunction:function(c,d){return(d-c)/c},repulsiveForceFunction:function(c,d){return(d-c)/c*(d>c?1:0)},barycenter:function(){var c=this.options.gravitationalConstant,d=this.barycenter.xFactor,f=this.barycenter.yFactor;d=(d-(this.box.left+
this.box.width)/2)*c;f=(f-(this.box.top+this.box.height)/2)*c;this.nodes.forEach(function(a){a.fixedPosition||(a.plotX-=d/a.mass/a.degree,a.plotY-=f/a.mass/a.degree)})},repulsive:function(c,d,f){d=d*this.diffTemperature/c.mass/c.degree;c.fixedPosition||(c.plotX+=f.x*d,c.plotY+=f.y*d)},attractive:function(c,d,f){var a=c.getMass(),h=-f.x*d*this.diffTemperature;d=-f.y*d*this.diffTemperature;c.fromNode.fixedPosition||(c.fromNode.plotX-=h*a.fromNode/c.fromNode.degree,c.fromNode.plotY-=d*a.fromNode/c.fromNode.degree);
c.toNode.fixedPosition||(c.toNode.plotX+=h*a.toNode/c.toNode.degree,c.toNode.plotY+=d*a.toNode/c.toNode.degree)},integrate:function(c,d){var f=-c.options.friction,a=c.options.maxSpeed,h=(d.plotX+d.dispX-d.prevX)*f;f*=d.plotY+d.dispY-d.prevY;var k=Math.abs,t=k(h)/(h||1);k=k(f)/(f||1);h=t*Math.min(a,Math.abs(h));f=k*Math.min(a,Math.abs(f));d.prevX=d.plotX+d.dispX;d.prevY=d.plotY+d.dispY;d.plotX+=h;d.plotY+=f;d.temperature=c.vectorLength({x:h,y:f})},getK:function(c){return Math.pow(c.box.width*c.box.height/
c.nodes.length,.5)}},euler:{attractiveForceFunction:function(c,d){return c*c/d},repulsiveForceFunction:function(c,d){return d*d/c},barycenter:function(){var c=this.options.gravitationalConstant,d=this.barycenter.xFactor,f=this.barycenter.yFactor;this.nodes.forEach(function(a){if(!a.fixedPosition){var h=a.getDegree();h*=1+h/2;a.dispX+=(d-a.plotX)*c*h/a.degree;a.dispY+=(f-a.plotY)*c*h/a.degree}})},repulsive:function(c,d,f,a){c.dispX+=f.x/a*d/c.degree;c.dispY+=f.y/a*d/c.degree},attractive:function(c,
d,f,a){var h=c.getMass(),k=f.x/a*d;d*=f.y/a;c.fromNode.fixedPosition||(c.fromNode.dispX-=k*h.fromNode/c.fromNode.degree,c.fromNode.dispY-=d*h.fromNode/c.fromNode.degree);c.toNode.fixedPosition||(c.toNode.dispX+=k*h.toNode/c.toNode.degree,c.toNode.dispY+=d*h.toNode/c.toNode.degree)},integrate:function(c,d){d.dispX+=d.dispX*c.options.friction;d.dispY+=d.dispY*c.options.friction;var f=d.temperature=c.vectorLength({x:d.dispX,y:d.dispY});0!==f&&(d.plotX+=d.dispX/f*Math.min(Math.abs(d.dispX),c.temperature),
d.plotY+=d.dispY/f*Math.min(Math.abs(d.dispY),c.temperature))},getK:function(c){return Math.pow(c.box.width*c.box.height/c.nodes.length,.3)}}}});A(d,"Series/Networkgraph/QuadTree.js",[d["Core/Globals.js"],d["Core/Utilities.js"]],function(d,c){c=c.extend;var h=d.QuadTreeNode=function(c){this.box=c;this.boxSize=Math.min(c.width,c.height);this.nodes=[];this.body=this.isInternal=!1;this.isEmpty=!0};c(h.prototype,{insert:function(c,a){this.isInternal?this.nodes[this.getBoxPosition(c)].insert(c,a-1):(this.isEmpty=
!1,this.body?a?(this.isInternal=!0,this.divideBox(),!0!==this.body&&(this.nodes[this.getBoxPosition(this.body)].insert(this.body,a-1),this.body=!0),this.nodes[this.getBoxPosition(c)].insert(c,a-1)):(a=new h({top:c.plotX,left:c.plotY,width:.1,height:.1}),a.body=c,a.isInternal=!1,this.nodes.push(a)):(this.isInternal=!1,this.body=c))},updateMassAndCenter:function(){var c=0,a=0,d=0;this.isInternal?(this.nodes.forEach(function(f){f.isEmpty||(c+=f.mass,a+=f.plotX*f.mass,d+=f.plotY*f.mass)}),a/=c,d/=c):
this.body&&(c=this.body.mass,a=this.body.plotX,d=this.body.plotY);this.mass=c;this.plotX=a;this.plotY=d},divideBox:function(){var c=this.box.width/2,a=this.box.height/2;this.nodes[0]=new h({left:this.box.left,top:this.box.top,width:c,height:a});this.nodes[1]=new h({left:this.box.left+c,top:this.box.top,width:c,height:a});this.nodes[2]=new h({left:this.box.left+c,top:this.box.top+a,width:c,height:a});this.nodes[3]=new h({left:this.box.left,top:this.box.top+a,width:c,height:a})},getBoxPosition:function(c){var a=
c.plotY<this.box.top+this.box.height/2;return c.plotX<this.box.left+this.box.width/2?a?0:3:a?1:2}});d=d.QuadTree=function(c,a,d,k){this.box={left:c,top:a,width:d,height:k};this.maxDepth=25;this.root=new h(this.box,"0");this.root.isInternal=!0;this.root.isRoot=!0;this.root.divideBox()};c(d.prototype,{insertNodes:function(c){c.forEach(function(a){this.root.insert(a,this.maxDepth)},this)},visitNodeRecursive:function(c,a,d){var f;c||(c=this.root);c===this.root&&a&&(f=a(c));!1!==f&&(c.nodes.forEach(function(c){if(c.isInternal){a&&
(f=a(c));if(!1===f)return;this.visitNodeRecursive(c,a,d)}else c.body&&a&&a(c.body);d&&d(c)},this),c===this.root&&d&&d(c))},calculateMassAndCenter:function(){this.visitNodeRecursive(null,null,function(c){c.updateMassAndCenter()})}})});A(d,"Series/Networkgraph/Layouts.js",[d["Core/Chart/Chart.js"],d["Core/Animation/AnimationUtilities.js"],d["Core/Globals.js"],d["Core/Utilities.js"]],function(d,c,h,f){var a=c.setAnimation;c=f.addEvent;var p=f.clamp,k=f.defined,t=f.extend,w=f.isFunction,v=f.pick;h.layouts=
{"reingold-fruchterman":function(){}};t(h.layouts["reingold-fruchterman"].prototype,{init:function(b){this.options=b;this.nodes=[];this.links=[];this.series=[];this.box={x:0,y:0,width:0,height:0};this.setInitialRendering(!0);this.integration=h.networkgraphIntegrations[b.integration];this.enableSimulation=b.enableSimulation;this.attractiveForce=v(b.attractiveForce,this.integration.attractiveForceFunction);this.repulsiveForce=v(b.repulsiveForce,this.integration.repulsiveForceFunction);this.approximation=
b.approximation},updateSimulation:function(b){this.enableSimulation=v(b,this.options.enableSimulation)},start:function(){var b=this.series,a=this.options;this.currentStep=0;this.forces=b[0]&&b[0].forces||[];this.chart=b[0]&&b[0].chart;this.initialRendering&&(this.initPositions(),b.forEach(function(b){b.finishedAnimating=!0;b.render()}));this.setK();this.resetSimulation(a);this.enableSimulation&&this.step()},step:function(){var b=this,a=this.series;b.currentStep++;"barnes-hut"===b.approximation&&(b.createQuadTree(),
b.quadTree.calculateMassAndCenter());b.forces.forEach(function(a){b[a+"Forces"](b.temperature)});b.applyLimits(b.temperature);b.temperature=b.coolDown(b.startTemperature,b.diffTemperature,b.currentStep);b.prevSystemTemperature=b.systemTemperature;b.systemTemperature=b.getSystemTemperature();b.enableSimulation&&(a.forEach(function(b){b.chart&&b.render()}),b.maxIterations--&&isFinite(b.temperature)&&!b.isStable()?(b.simulation&&h.win.cancelAnimationFrame(b.simulation),b.simulation=h.win.requestAnimationFrame(function(){b.step()})):
b.simulation=!1)},stop:function(){this.simulation&&h.win.cancelAnimationFrame(this.simulation)},setArea:function(b,a,c,d){this.box={left:b,top:a,width:c,height:d}},setK:function(){this.k=this.options.linkLength||this.integration.getK(this)},addElementsToCollection:function(b,a){b.forEach(function(b){-1===a.indexOf(b)&&a.push(b)})},removeElementFromCollection:function(b,a){b=a.indexOf(b);-1!==b&&a.splice(b,1)},clear:function(){this.nodes.length=0;this.links.length=0;this.series.length=0;this.resetSimulation()},
resetSimulation:function(){this.forcedStop=!1;this.systemTemperature=0;this.setMaxIterations();this.setTemperature();this.setDiffTemperature()},restartSimulation:function(){this.simulation?this.resetSimulation():(this.setInitialRendering(!1),this.enableSimulation?this.start():this.setMaxIterations(1),this.chart&&this.chart.redraw(),this.setInitialRendering(!0))},setMaxIterations:function(b){this.maxIterations=v(b,this.options.maxIterations)},setTemperature:function(){this.temperature=this.startTemperature=
Math.sqrt(this.nodes.length)},setDiffTemperature:function(){this.diffTemperature=this.startTemperature/(this.options.maxIterations+1)},setInitialRendering:function(b){this.initialRendering=b},createQuadTree:function(){this.quadTree=new h.QuadTree(this.box.left,this.box.top,this.box.width,this.box.height);this.quadTree.insertNodes(this.nodes)},initPositions:function(){var b=this.options.initialPositions;w(b)?(b.call(this),this.nodes.forEach(function(b){k(b.prevX)||(b.prevX=b.plotX);k(b.prevY)||(b.prevY=
b.plotY);b.dispX=0;b.dispY=0})):"circle"===b?this.setCircularPositions():this.setRandomPositions()},setCircularPositions:function(){function b(a){a.linksFrom.forEach(function(a){k[a.toNode.id]||(k[a.toNode.id]=!0,h.push(a.toNode),b(a.toNode))})}var a=this.box,c=this.nodes,d=2*Math.PI/(c.length+1),f=c.filter(function(b){return 0===b.linksTo.length}),h=[],k={},t=this.options.initialPositionRadius;f.forEach(function(a){h.push(a);b(a)});h.length?c.forEach(function(b){-1===h.indexOf(b)&&h.push(b)}):h=
c;h.forEach(function(b,c){b.plotX=b.prevX=v(b.plotX,a.width/2+t*Math.cos(c*d));b.plotY=b.prevY=v(b.plotY,a.height/2+t*Math.sin(c*d));b.dispX=0;b.dispY=0})},setRandomPositions:function(){function b(b){b=b*b/Math.PI;return b-=Math.floor(b)}var a=this.box,c=this.nodes,d=c.length+1;c.forEach(function(c,g){c.plotX=c.prevX=v(c.plotX,a.width*b(g));c.plotY=c.prevY=v(c.plotY,a.height*b(d+g));c.dispX=0;c.dispY=0})},force:function(b){this.integration[b].apply(this,Array.prototype.slice.call(arguments,1))},barycenterForces:function(){this.getBarycenter();
this.force("barycenter")},getBarycenter:function(){var b=0,a=0,c=0;this.nodes.forEach(function(d){a+=d.plotX*d.mass;c+=d.plotY*d.mass;b+=d.mass});return this.barycenter={x:a,y:c,xFactor:a/b,yFactor:c/b}},barnesHutApproximation:function(b,a){var c=this.getDistXY(b,a),d=this.vectorLength(c);if(b!==a&&0!==d)if(a.isInternal)if(a.boxSize/d<this.options.theta&&0!==d){var g=this.repulsiveForce(d,this.k);this.force("repulsive",b,g*a.mass,c,d);var f=!1}else f=!0;else g=this.repulsiveForce(d,this.k),this.force("repulsive",
b,g*a.mass,c,d);return f},repulsiveForces:function(){var b=this;"barnes-hut"===b.approximation?b.nodes.forEach(function(a){b.quadTree.visitNodeRecursive(null,function(c){return b.barnesHutApproximation(a,c)})}):b.nodes.forEach(function(a){b.nodes.forEach(function(c){if(a!==c&&!a.fixedPosition){var d=b.getDistXY(a,c);var g=b.vectorLength(d);if(0!==g){var f=b.repulsiveForce(g,b.k);b.force("repulsive",a,f*c.mass,d,g)}}})})},attractiveForces:function(){var b=this,a,c,d;b.links.forEach(function(g){g.fromNode&&
g.toNode&&(a=b.getDistXY(g.fromNode,g.toNode),c=b.vectorLength(a),0!==c&&(d=b.attractiveForce(c,b.k),b.force("attractive",g,d,a,c)))})},applyLimits:function(){var b=this;b.nodes.forEach(function(a){a.fixedPosition||(b.integration.integrate(b,a),b.applyLimitBox(a,b.box),a.dispX=0,a.dispY=0)})},applyLimitBox:function(b,a){var c=b.radius;b.plotX=p(b.plotX,a.left+c,a.width-c);b.plotY=p(b.plotY,a.top+c,a.height-c)},coolDown:function(a,c,d){return a-c*d},isStable:function(){return.00001>Math.abs(this.systemTemperature-
this.prevSystemTemperature)||0>=this.temperature},getSystemTemperature:function(){return this.nodes.reduce(function(a,c){return a+c.temperature},0)},vectorLength:function(a){return Math.sqrt(a.x*a.x+a.y*a.y)},getDistR:function(a,c){a=this.getDistXY(a,c);return this.vectorLength(a)},getDistXY:function(a,c){var b=a.plotX-c.plotX;a=a.plotY-c.plotY;return{x:b,y:a,absX:Math.abs(b),absY:Math.abs(a)}}});c(d,"predraw",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.stop()})});
c(d,"render",function(){function b(a){a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()&&!a.enableSimulation&&(a.beforeStep&&a.beforeStep(),a.step(),d=!1,c=!0)}var c=!1;if(this.graphLayoutsLookup){a(!1,this);for(this.graphLayoutsLookup.forEach(function(a){a.start()});!d;){var d=!0;this.graphLayoutsLookup.forEach(b)}c&&this.series.forEach(function(a){a&&a.layout&&a.render()})}});c(d,"beforePrint",function(){this.graphLayoutsLookup&&(this.graphLayoutsLookup.forEach(function(a){a.updateSimulation(!1)}),
this.redraw())});c(d,"afterPrint",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.updateSimulation()});this.redraw()})});A(d,"Series/PackedBubble/PackedBubbleComposition.js",[d["Core/Chart/Chart.js"],d["Core/Globals.js"],d["Core/Utilities.js"]],function(d,c,h){var f=c.layouts["reingold-fruchterman"],a=h.addEvent,p=h.extendClass,k=h.pick;d.prototype.getSelectedParentNodes=function(){var a=[];this.series.forEach(function(c){c.parentNode&&c.parentNode.selected&&a.push(c.parentNode)});
return a};c.networkgraphIntegrations.packedbubble={repulsiveForceFunction:function(a,c,d,b){return Math.min(a,(d.marker.radius+b.marker.radius)/2)},barycenter:function(){var a=this,c=a.options.gravitationalConstant,d=a.box,b=a.nodes,g,f;b.forEach(function(h){a.options.splitSeries&&!h.isParentNode?(g=h.series.parentNode.plotX,f=h.series.parentNode.plotY):(g=d.width/2,f=d.height/2);h.fixedPosition||(h.plotX-=(h.plotX-g)*c/(h.mass*Math.sqrt(b.length)),h.plotY-=(h.plotY-f)*c/(h.mass*Math.sqrt(b.length)))})},
repulsive:function(a,c,d,b){var g=c*this.diffTemperature/a.mass/a.degree;c=d.x*g;d=d.y*g;a.fixedPosition||(a.plotX+=c,a.plotY+=d);b.fixedPosition||(b.plotX-=c,b.plotY-=d)},integrate:c.networkgraphIntegrations.verlet.integrate,getK:c.noop};c.layouts.packedbubble=p(f,{beforeStep:function(){this.options.marker&&this.series.forEach(function(a){a&&a.calculateParentRadius()})},setCircularPositions:function(){var a=this,c=a.box,d=a.nodes,b=2*Math.PI/(d.length+1),g,f,h=a.options.initialPositionRadius;d.forEach(function(d,
l){a.options.splitSeries&&!d.isParentNode?(g=d.series.parentNode.plotX,f=d.series.parentNode.plotY):(g=c.width/2,f=c.height/2);d.plotX=d.prevX=k(d.plotX,g+h*Math.cos(d.index||l*b));d.plotY=d.prevY=k(d.plotY,f+h*Math.sin(d.index||l*b));d.dispX=0;d.dispY=0})},repulsiveForces:function(){var a=this,c,d,b,g=a.options.bubblePadding;a.nodes.forEach(function(f){f.degree=f.mass;f.neighbours=0;a.nodes.forEach(function(h){c=0;f===h||f.fixedPosition||!a.options.seriesInteraction&&f.series!==h.series||(b=a.getDistXY(f,
h),d=a.vectorLength(b)-(f.marker.radius+h.marker.radius+g),0>d&&(f.degree+=.01,f.neighbours++,c=a.repulsiveForce(-d/Math.sqrt(f.neighbours),a.k,f,h)),a.force("repulsive",f,c*h.mass,b,h,d))})})},applyLimitBox:function(a){if(this.options.splitSeries&&!a.isParentNode&&this.options.parentNodeLimit){var c=this.getDistXY(a,a.series.parentNode);var d=a.series.parentNodeRadius-a.marker.radius-this.vectorLength(c);0>d&&d>-2*a.marker.radius&&(a.plotX-=.01*c.x,a.plotY-=.01*c.y)}f.prototype.applyLimitBox.apply(this,
arguments)}});a(d,"beforeRedraw",function(){this.allDataPoints&&delete this.allDataPoints})});A(d,"Series/PackedBubble/PackedBubbleSeries.js",[d["Core/Series/Series.js"],d["Core/Color/Color.js"],d["Core/Globals.js"],d["Series/PackedBubble/PackedBubblePoint.js"],d["Core/Utilities.js"]],function(d,c,h,f,a){var p=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&
(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),k=d.seriesTypes,t=k.bubble,w=k.line,v=c.parse,b=a.addEvent,g=a.clamp,l=a.defined,A=a.extend,C=a.fireEvent,y=a.isArray,J=a.isNumber,B=a.merge,x=a.pick,q=h.dragNodesMixin;c=function(a){function c(){var b=null!==a&&a.apply(this,arguments)||this;b.chart=void 0;b.data=void 0;b.layout=void 0;b.options=void 0;b.points=void 0;b.xData=void 0;return b}
p(c,a);c.prototype.accumulateAllPoints=function(a){var b=a.chart,c=[],d,e;for(d=0;d<b.series.length;d++)if(a=b.series[d],a.is("packedbubble")&&a.visible||!b.options.chart.ignoreHiddenSeries)for(e=0;e<a.yData.length;e++)c.push([null,null,a.yData[e],a.index,e,{id:e,marker:{radius:0}}]);return c};c.prototype.addLayout=function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,c=this.chart.graphLayoutsLookup,d=this.chart.options.chart;b||(this.chart.graphLayoutsStorage=b={},this.chart.graphLayoutsLookup=
c=[]);var e=b[a.type];e||(a.enableSimulation=l(d.forExport)?!d.forExport:a.enableSimulation,b[a.type]=e=new h.layouts[a.type],e.init(a),c.splice(e.index,0,e));this.layout=e;this.points.forEach(function(a){a.mass=2;a.degree=1;a.collisionNmb=1});e.setArea(0,0,this.chart.plotWidth,this.chart.plotHeight);e.addElementsToCollection([this],e.series);e.addElementsToCollection(this.points,e.nodes)};c.prototype.addSeriesLayout=function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,c=
this.chart.graphLayoutsLookup,d=B(a,a.parentNodeOptions,{enableSimulation:this.layout.options.enableSimulation});var e=b[a.type+"-series"];e||(b[a.type+"-series"]=e=new h.layouts[a.type],e.init(d),c.splice(e.index,0,e));this.parentNodeLayout=e;this.createParentNodes()};c.prototype.calculateParentRadius=function(){var a=this.seriesBox();this.parentNodeRadius=g(Math.sqrt(2*this.parentNodeMass/Math.PI)+20,20,a?Math.max(Math.sqrt(Math.pow(a.width,2)+Math.pow(a.height,2))/2+20,20):Math.sqrt(2*this.parentNodeMass/
Math.PI)+20);this.parentNode&&(this.parentNode.marker.radius=this.parentNode.radius=this.parentNodeRadius)};c.prototype.calculateZExtremes=function(){var a=this.options.zMin,b=this.options.zMax,c=Infinity,d=-Infinity;if(a&&b)return[a,b];this.chart.series.forEach(function(a){a.yData.forEach(function(a){l(a)&&(a>d&&(d=a),a<c&&(c=a))})});a=x(a,c);b=x(b,d);return[a,b]};c.prototype.checkOverlap=function(a,b){var c=a[0]-b[0],d=a[1]-b[1];return-.001>Math.sqrt(c*c+d*d)-Math.abs(a[2]+b[2])};c.prototype.createParentNodes=
function(){var a=this,b=a.chart,c=a.parentNodeLayout,d,e=a.parentNode,f=a.pointClass;a.parentNodeMass=0;a.points.forEach(function(b){a.parentNodeMass+=Math.PI*Math.pow(b.marker.radius,2)});a.calculateParentRadius();c.nodes.forEach(function(b){b.seriesIndex===a.index&&(d=!0)});c.setArea(0,0,b.plotWidth,b.plotHeight);d||(e||(e=(new f).init(this,{mass:a.parentNodeRadius/2,marker:{radius:a.parentNodeRadius},dataLabels:{inside:!1},dataLabelOnNull:!0,degree:a.parentNodeRadius,isParentNode:!0,seriesIndex:a.index})),
a.parentNode&&(e.plotX=a.parentNode.plotX,e.plotY=a.parentNode.plotY),a.parentNode=e,c.addElementsToCollection([a],c.series),c.addElementsToCollection([e],c.nodes))};c.prototype.deferLayout=function(){var a=this.options.layoutAlgorithm;this.visible&&(this.addLayout(),a.splitSeries&&this.addSeriesLayout())};c.prototype.destroy=function(){this.chart.graphLayoutsLookup&&this.chart.graphLayoutsLookup.forEach(function(a){a.removeElementFromCollection(this,a.series)},this);this.parentNode&&this.parentNodeLayout&&
(this.parentNodeLayout.removeElementFromCollection(this.parentNode,this.parentNodeLayout.nodes),this.parentNode.dataLabel&&(this.parentNode.dataLabel=this.parentNode.dataLabel.destroy()));w.prototype.destroy.apply(this,arguments)};c.prototype.drawDataLabels=function(){var a=this.options.dataLabels.textPath,b=this.points;w.prototype.drawDataLabels.apply(this,arguments);this.parentNode&&(this.parentNode.formatPrefix="parentNode",this.points=[this.parentNode],this.options.dataLabels.textPath=this.options.dataLabels.parentNodeTextPath,
w.prototype.drawDataLabels.apply(this,arguments),this.points=b,this.options.dataLabels.textPath=a)};c.prototype.drawGraph=function(){if(this.layout&&this.layout.options.splitSeries){var a=this.chart,b=this.layout.options.parentNodeOptions.marker;b={fill:b.fillColor||v(this.color).brighten(.4).get(),opacity:b.fillOpacity,stroke:b.lineColor||this.color,"stroke-width":b.lineWidth};var c=this.visible?"inherit":"hidden";this.parentNodesGroup||(this.parentNodesGroup=this.plotGroup("parentNodesGroup","parentNode",
c,.1,a.seriesGroup),this.group.attr({zIndex:2}));this.calculateParentRadius();c=B({x:this.parentNode.plotX-this.parentNodeRadius,y:this.parentNode.plotY-this.parentNodeRadius,width:2*this.parentNodeRadius,height:2*this.parentNodeRadius},b);this.parentNode.graphic||(this.graph=this.parentNode.graphic=a.renderer.symbol(b.symbol).add(this.parentNodesGroup));this.parentNode.graphic.attr(c)}};c.prototype.drawTracker=function(){var a=this.parentNode;h.TrackerMixin.drawTrackerPoint.call(this);if(a){var b=
y(a.dataLabels)?a.dataLabels:a.dataLabel?[a.dataLabel]:[];a.graphic&&(a.graphic.element.point=a);b.forEach(function(b){b.div?b.div.point=a:b.element.point=a})}};c.prototype.getPointRadius=function(){var a=this,b=a.chart,c=a.options,d=c.useSimulation,e=Math.min(b.plotWidth,b.plotHeight),f={},h=[],r=b.allDataPoints,k,l,p,q;["minSize","maxSize"].forEach(function(a){var b=parseInt(c[a],10),d=/%$/.test(c[a]);f[a]=d?e*b/100:b*Math.sqrt(r.length)});b.minRadius=k=f.minSize/Math.sqrt(r.length);b.maxRadius=
l=f.maxSize/Math.sqrt(r.length);var t=d?a.calculateZExtremes():[k,l];(r||[]).forEach(function(b,c){p=d?g(b[2],t[0],t[1]):b[2];q=a.getRadius(t[0],t[1],k,l,p);0===q&&(q=null);r[c][2]=q;h.push(q)});a.radii=h};c.prototype.init=function(){w.prototype.init.apply(this,arguments);this.eventsToUnbind.push(b(this,"updatedData",function(){this.chart.series.forEach(function(a){a.type===this.type&&(a.isDirty=!0)},this)}));return this};c.prototype.onMouseUp=function(a){if(a.fixedPosition&&!a.removed){var b,c,d=
this.layout,e=this.parentNodeLayout;e&&d.options.dragBetweenSeries&&e.nodes.forEach(function(e){a&&a.marker&&e!==a.series.parentNode&&(b=d.getDistXY(a,e),c=d.vectorLength(b)-e.marker.radius-a.marker.radius,0>c&&(e.series.addPoint(B(a.options,{plotX:a.plotX,plotY:a.plotY}),!1),d.removeElementFromCollection(a,d.nodes),a.remove()))});q.onMouseUp.apply(this,arguments)}};c.prototype.placeBubbles=function(a){var b=this.checkOverlap,c=this.positionBubble,d=[],e=1,f=0,g=0;var m=[];var h;a=a.sort(function(a,
b){return b[2]-a[2]});if(a.length){d.push([[0,0,a[0][2],a[0][3],a[0][4]]]);if(1<a.length)for(d.push([[0,0-a[1][2]-a[0][2],a[1][2],a[1][3],a[1][4]]]),h=2;h<a.length;h++)a[h][2]=a[h][2]||1,m=c(d[e][f],d[e-1][g],a[h]),b(m,d[e][0])?(d.push([]),g=0,d[e+1].push(c(d[e][f],d[e][0],a[h])),e++,f=0):1<e&&d[e-1][g+1]&&b(m,d[e-1][g+1])?(g++,d[e].push(c(d[e][f],d[e-1][g],a[h])),f++):(f++,d[e].push(m));this.chart.stages=d;this.chart.rawPositions=[].concat.apply([],d);this.resizeRadius();m=this.chart.rawPositions}return m};
c.prototype.positionBubble=function(a,b,c){var d=Math.sqrt,e=Math.asin,f=Math.acos,g=Math.pow,h=Math.abs;d=d(g(a[0]-b[0],2)+g(a[1]-b[1],2));f=f((g(d,2)+g(c[2]+b[2],2)-g(c[2]+a[2],2))/(2*(c[2]+b[2])*d));e=e(h(a[0]-b[0])/d);a=(0>a[1]-b[1]?0:Math.PI)+f+e*(0>(a[0]-b[0])*(a[1]-b[1])?1:-1);return[b[0]+(b[2]+c[2])*Math.sin(a),b[1]-(b[2]+c[2])*Math.cos(a),c[2],c[3],c[4]]};c.prototype.render=function(){var a=[];w.prototype.render.apply(this,arguments);this.options.dataLabels.allowOverlap||(this.data.forEach(function(b){y(b.dataLabels)&&
b.dataLabels.forEach(function(b){a.push(b)})}),this.options.useSimulation&&this.chart.hideOverlappingLabels(a))};c.prototype.resizeRadius=function(){var a=this.chart,b=a.rawPositions,c=Math.min,d=Math.max,e=a.plotLeft,f=a.plotTop,g=a.plotHeight,h=a.plotWidth,r,k,l;var p=r=Number.POSITIVE_INFINITY;var q=k=Number.NEGATIVE_INFINITY;for(l=0;l<b.length;l++){var t=b[l][2];p=c(p,b[l][0]-t);q=d(q,b[l][0]+t);r=c(r,b[l][1]-t);k=d(k,b[l][1]+t)}l=[q-p,k-r];c=c.apply([],[(h-e)/l[0],(g-f)/l[1]]);if(1e-10<Math.abs(c-
1)){for(l=0;l<b.length;l++)b[l][2]*=c;this.placeBubbles(b)}else a.diffY=g/2+f-r-(k-r)/2,a.diffX=h/2+e-p-(q-p)/2};c.prototype.seriesBox=function(){var a=this.chart,b=Math.max,c=Math.min,d,e=[a.plotLeft,a.plotLeft+a.plotWidth,a.plotTop,a.plotTop+a.plotHeight];this.data.forEach(function(a){l(a.plotX)&&l(a.plotY)&&a.marker.radius&&(d=a.marker.radius,e[0]=c(e[0],a.plotX-d),e[1]=b(e[1],a.plotX+d),e[2]=c(e[2],a.plotY-d),e[3]=b(e[3],a.plotY+d))});return J(e.width/e.height)?e:null};c.prototype.setVisible=
function(){var a=this;w.prototype.setVisible.apply(a,arguments);a.parentNodeLayout&&a.graph?a.visible?(a.graph.show(),a.parentNode.dataLabel&&a.parentNode.dataLabel.show()):(a.graph.hide(),a.parentNodeLayout.removeElementFromCollection(a.parentNode,a.parentNodeLayout.nodes),a.parentNode.dataLabel&&a.parentNode.dataLabel.hide()):a.layout&&(a.visible?a.layout.addElementsToCollection(a.points,a.layout.nodes):a.points.forEach(function(b){a.layout.removeElementFromCollection(b,a.layout.nodes)}))};c.prototype.translate=
function(){var a=this.chart,b=this.data,c=this.index,d,e=this.options.useSimulation;this.processedXData=this.xData;this.generatePoints();l(a.allDataPoints)||(a.allDataPoints=this.accumulateAllPoints(this),this.getPointRadius());if(e)var f=a.allDataPoints;else f=this.placeBubbles(a.allDataPoints),this.options.draggable=!1;for(d=0;d<f.length;d++)if(f[d][3]===c){var g=b[f[d][4]];var h=f[d][2];e||(g.plotX=f[d][0]-a.plotLeft+a.diffX,g.plotY=f[d][1]-a.plotTop+a.diffY);g.marker=A(g.marker,{radius:h,width:2*
h,height:2*h});g.radius=h}e&&this.deferLayout();C(this,"afterTranslate")};c.defaultOptions=B(t.defaultOptions,{minSize:"10%",maxSize:"50%",sizeBy:"area",zoneAxis:"y",crisp:!1,tooltip:{pointFormat:"Value: {point.value}"},draggable:!0,useSimulation:!0,parentNode:{allowPointSelect:!1},dataLabels:{formatter:function(){return this.point.value},parentNodeFormatter:function(){return this.name},parentNodeTextPath:{enabled:!0},padding:0,style:{transition:"opacity 2000ms"}},layoutAlgorithm:{initialPositions:"circle",
initialPositionRadius:20,bubblePadding:5,parentNodeLimit:!1,seriesInteraction:!0,dragBetweenSeries:!1,parentNodeOptions:{maxIterations:400,gravitationalConstant:.03,maxSpeed:50,initialPositionRadius:100,seriesInteraction:!0,marker:{fillColor:null,fillOpacity:1,lineWidth:1,lineColor:null,symbol:"circle"}},enableSimulation:!0,type:"packedbubble",integration:"packedbubble",maxIterations:1E3,splitSeries:!1,maxSpeed:5,gravitationalConstant:.01,friction:-.981}});return c}(t);A(c.prototype,{alignDataLabel:w.prototype.alignDataLabel,
axisTypes:[],directTouch:!0,forces:["barycenter","repulsive"],hasDraggableNodes:!0,isCartesian:!1,noSharedTooltip:!0,onMouseDown:q.onMouseDown,onMouseMove:q.onMouseMove,pointArrayMap:["value"],pointClass:f,pointValKey:"value",redrawHalo:q.redrawHalo,requireSorting:!1,searchPoint:h.noop,trackerGroups:["group","dataLabelsGroup","parentNodesGroup"]});d.registerSeriesType("packedbubble",c);"";"";return c});A(d,"Extensions/Polar.js",[d["Core/Animation/AnimationUtilities.js"],d["Core/Series/Series.js"],
d["Core/Chart/Chart.js"],d["Core/Globals.js"],d["Series/Line/LineSeries.js"],d["Extensions/Pane.js"],d["Core/Pointer.js"],d["Core/Renderer/SVG/SVGRenderer.js"],d["Core/Utilities.js"]],function(d,c,h,f,a,p,k,t,w){var v=d.animObject;c=c.seriesTypes;var b=w.addEvent,g=w.defined,l=w.find,A=w.isNumber,C=w.pick,y=w.splat,J=w.uniqueKey;d=w.wrap;var B=a.prototype;k=k.prototype;B.searchPointByAngle=function(a){var b=this.chart,c=this.xAxis.pane.center;return this.searchKDTree({clientX:180+-180/Math.PI*Math.atan2(a.chartX-
c[0]-b.plotLeft,a.chartY-c[1]-b.plotTop)})};B.getConnectors=function(a,b,c,d){var e=d?1:0;var f=0<=b&&b<=a.length-1?b:0>b?a.length-1+b:0;b=0>f-1?a.length-(1+e):f-1;e=f+1>a.length-1?e:f+1;var g=a[b];e=a[e];var h=g.plotX;g=g.plotY;var m=e.plotX;var r=e.plotY;e=a[f].plotX;f=a[f].plotY;h=(1.5*e+h)/2.5;g=(1.5*f+g)/2.5;m=(1.5*e+m)/2.5;var k=(1.5*f+r)/2.5;r=Math.sqrt(Math.pow(h-e,2)+Math.pow(g-f,2));var l=Math.sqrt(Math.pow(m-e,2)+Math.pow(k-f,2));h=Math.atan2(g-f,h-e);k=Math.PI/2+(h+Math.atan2(k-f,m-e))/
2;Math.abs(h-k)>Math.PI/2&&(k-=Math.PI);h=e+Math.cos(k)*r;g=f+Math.sin(k)*r;m=e+Math.cos(Math.PI+k)*l;k=f+Math.sin(Math.PI+k)*l;e={rightContX:m,rightContY:k,leftContX:h,leftContY:g,plotX:e,plotY:f};c&&(e.prevPointCont=this.getConnectors(a,b,!1,d));return e};B.toXY=function(a){var b=this.chart,c=this.xAxis;var d=this.yAxis;var f=a.plotX,g=a.plotY,h=a.series,k=b.inverted,r=a.y,l=k?f:d.len-g;k&&h&&!h.isRadialBar&&(a.plotY=g="number"===typeof r?d.translate(r)||0:0);a.rectPlotX=f;a.rectPlotY=g;d.center&&
(l+=d.center[3]/2);d=k?d.postTranslate(g,l):c.postTranslate(f,l);a.plotX=a.polarPlotX=d.x-b.plotLeft;a.plotY=a.polarPlotY=d.y-b.plotTop;this.kdByAngle?(b=(f/Math.PI*180+c.pane.options.startAngle)%360,0>b&&(b+=360),a.clientX=b):a.clientX=a.plotX};c.spline&&(d(c.spline.prototype,"getPointSpline",function(a,b,c,d){this.chart.polar?d?(a=this.getConnectors(b,d,!0,this.connectEnds),a=["C",a.prevPointCont.rightContX,a.prevPointCont.rightContY,a.leftContX,a.leftContY,a.plotX,a.plotY]):a=["M",c.plotX,c.plotY]:
a=a.call(this,b,c,d);return a}),c.areasplinerange&&(c.areasplinerange.prototype.getPointSpline=c.spline.prototype.getPointSpline));b(a,"afterTranslate",function(){var a=this.chart;if(a.polar&&this.xAxis){(this.kdByAngle=a.tooltip&&a.tooltip.shared)?this.searchPoint=this.searchPointByAngle:this.options.findNearestPointBy="xy";if(!this.preventPostTranslate)for(var c=this.points,d=c.length;d--;)this.toXY(c[d]),!a.hasParallelCoordinates&&!this.yAxis.reversed&&c[d].y<this.yAxis.min&&(c[d].isNull=!0);this.hasClipCircleSetter||
(this.hasClipCircleSetter=!!this.eventsToUnbind.push(b(this,"afterRender",function(){if(a.polar){var b=this.yAxis.pane.center;this.clipCircle?this.clipCircle.animate({x:b[0],y:b[1],r:b[2]/2,innerR:b[3]/2}):this.clipCircle=a.renderer.clipCircle(b[0],b[1],b[2]/2,b[3]/2);this.group.clip(this.clipCircle);this.setClip=f.noop}})))}},{order:2});d(B,"getGraphPath",function(a,b){var c=this,d;if(this.chart.polar){b=b||this.points;for(d=0;d<b.length;d++)if(!b[d].isNull){var e=d;break}if(!1!==this.options.connectEnds&&
"undefined"!==typeof e){this.connectEnds=!0;b.splice(b.length,0,b[e]);var f=!0}b.forEach(function(a){"undefined"===typeof a.polarPlotY&&c.toXY(a)})}d=a.apply(this,[].slice.call(arguments,1));f&&b.pop();return d});var x=function(a,b){var c=this,d=this.chart,e=this.options.animation,g=this.group,h=this.markerGroup,k=this.xAxis.center,l=d.plotLeft,r=d.plotTop,p,q,t,w;if(d.polar)if(c.isRadialBar)b||(c.startAngleRad=C(c.translatedThreshold,c.xAxis.startAngleRad),f.seriesTypes.pie.prototype.animate.call(c,
b));else{if(d.renderer.isSVG)if(e=v(e),c.is("column")){if(!b){var x=k[3]/2;c.points.forEach(function(a){p=a.graphic;t=(q=a.shapeArgs)&&q.r;w=q&&q.innerR;p&&q&&(p.attr({r:x,innerR:x}),p.animate({r:t,innerR:w},c.options.animation))})}}else b?(a={translateX:k[0]+l,translateY:k[1]+r,scaleX:.001,scaleY:.001},g.attr(a),h&&h.attr(a)):(a={translateX:l,translateY:r,scaleX:1,scaleY:1},g.animate(a,e),h&&h.animate(a,e))}else a.call(this,b)};d(B,"animate",x);if(c.column){var q=c.arearange.prototype;c=c.column.prototype;
c.polarArc=function(a,b,c,d){var e=this.xAxis.center,f=this.yAxis.len,g=e[3]/2;b=f-b+g;a=f-C(a,f)+g;this.yAxis.reversed&&(0>b&&(b=g),0>a&&(a=g));return{x:e[0],y:e[1],r:b,innerR:a,start:c,end:d}};d(c,"animate",x);d(c,"translate",function(a){var b=this.options,c=b.stacking,d=this.chart,f=this.xAxis,h=this.yAxis,k=h.reversed,l=h.center,r=f.startAngleRad,p=f.endAngleRad-r;this.preventPostTranslate=!0;a.call(this);if(f.isRadial){a=this.points;f=a.length;var q=h.translate(h.min);var t=h.translate(h.max);
b=b.threshold||0;if(d.inverted&&A(b)){var v=h.translate(b);g(v)&&(0>v?v=0:v>p&&(v=p),this.translatedThreshold=v+r)}for(;f--;){b=a[f];var x=b.barX;var C=b.x;var B=b.y;b.shapeType="arc";if(d.inverted){b.plotY=h.translate(B);if(c&&h.stacking){if(B=h.stacking.stacks[(0>B?"-":"")+this.stackKey],this.visible&&B&&B[C]&&!b.isNull){var z=B[C].points[this.getStackIndicator(void 0,C,this.index).key];var y=h.translate(z[0]);z=h.translate(z[1]);g(y)&&(y=w.clamp(y,0,p))}}else y=v,z=b.plotY;y>z&&(z=[y,y=z][0]);
if(!k)if(y<q)y=q;else if(z>t)z=t;else{if(z<q||y>t)y=z=0}else if(z>q)z=q;else if(y<t)y=t;else if(y>q||z<t)y=z=p;h.min>h.max&&(y=z=k?p:0);y+=r;z+=r;l&&(b.barX=x+=l[3]/2);C=Math.max(x,0);B=Math.max(x+b.pointWidth,0);b.shapeArgs={x:l&&l[0],y:l&&l[1],r:B,innerR:C,start:y,end:z};b.opacity=y===z?0:void 0;b.plotY=(g(this.translatedThreshold)&&(y<this.translatedThreshold?y:z))-r}else y=x+r,b.shapeArgs=this.polarArc(b.yBottom,b.plotY,y,y+b.pointWidth);this.toXY(b);d.inverted?(x=h.postTranslate(b.rectPlotY,
x+b.pointWidth/2),b.tooltipPos=[x.x-d.plotLeft,x.y-d.plotTop]):b.tooltipPos=[b.plotX,b.plotY];l&&(b.ttBelow=b.plotY>l[1])}}});c.findAlignments=function(a,b){null===b.align&&(b.align=20<a&&160>a?"left":200<a&&340>a?"right":"center");null===b.verticalAlign&&(b.verticalAlign=45>a||315<a?"bottom":135<a&&225>a?"top":"middle");return b};q&&(q.findAlignments=c.findAlignments);d(c,"alignDataLabel",function(a,b,c,d,f,g){var e=this.chart,h=C(d.inside,!!this.options.stacking);e.polar?(a=b.rectPlotX/Math.PI*
180,e.inverted?(this.forceDL=e.isInsidePlot(b.plotX,Math.round(b.plotY),!1),h&&b.shapeArgs?(f=b.shapeArgs,f=this.yAxis.postTranslate((f.start+f.end)/2-this.xAxis.startAngleRad,b.barX+b.pointWidth/2),f={x:f.x-e.plotLeft,y:f.y-e.plotTop}):b.tooltipPos&&(f={x:b.tooltipPos[0],y:b.tooltipPos[1]}),d.align=C(d.align,"center"),d.verticalAlign=C(d.verticalAlign,"middle")):this.findAlignments&&(d=this.findAlignments(a,d)),B.alignDataLabel.call(this,b,c,d,f,g),this.isRadialBar&&b.shapeArgs&&b.shapeArgs.start===
b.shapeArgs.end&&c.hide(!0)):a.call(this,b,c,d,f,g)})}d(k,"getCoordinates",function(a,b){var c=this.chart,d={xAxis:[],yAxis:[]};c.polar?c.axes.forEach(function(a){var e=a.isXAxis,f=a.center;if("colorAxis"!==a.coll){var g=b.chartX-f[0]-c.plotLeft;f=b.chartY-f[1]-c.plotTop;d[e?"xAxis":"yAxis"].push({axis:a,value:a.translate(e?Math.PI-Math.atan2(g,f):Math.sqrt(Math.pow(g,2)+Math.pow(f,2)),!0)})}}):d=a.call(this,b);return d});t.prototype.clipCircle=function(a,b,c,d){var e=J(),f=this.createElement("clipPath").attr({id:e}).add(this.defs);
a=d?this.arc(a,b,c,d,0,2*Math.PI).add(f):this.circle(a,b,c).add(f);a.id=e;a.clipPath=f;return a};b(h,"getAxes",function(){this.pane||(this.pane=[]);y(this.options.pane).forEach(function(a){new p(a,this)},this)});b(h,"afterDrawChartBox",function(){this.pane.forEach(function(a){a.render()})});b(a,"afterInit",function(){var a=this.chart;a.inverted&&a.polar&&(this.isRadialSeries=!0,this.is("column")&&(this.isRadialBar=!0))});d(h.prototype,"get",function(a,b){return l(this.pane,function(a){return a.options.id===
b})||a.call(this,b)})});A(d,"masters/highcharts-more.src.js",[],function(){})});
//# sourceMappingURL=highcharts-more.js.map