/*
 Highstock JS v8.2.2 (2020-11-23)

 All technical indicators for Highstock

 (c) 2010-2019 Pawel Fus

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/indicators/indicators-all",["highcharts","highcharts/modules/stock"],function(w){b(w);b.Highcharts=w;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function w(b,g,h,l){b.hasOwnProperty(g)||(b[g]=l.apply(null,h))}b=b?b._modules:{};w(b,"Mixins/IndicatorRequired.js",[b["Core/Utilities.js"]],function(b){var g=b.error;return{isParentLoaded:function(b,
l,k,f,a){if(b)return f?f(b):!0;g(a||this.generateMessage(k,l));return!1},generateMessage:function(b,l){return'Error: "'+b+'" indicator type requires "'+l+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+b}}});w(b,"Stock/Indicators/SMA/SMAComposition.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){var h=b.seriesTypes;b=h.line;var l=h.ohlc.prototype;h=g.addEvent;var k=g.extend;h(b,"init",function(f){f=f.options;f.useOhlcData&&"highcharts-navigator-series"!==
f.id&&k(this,{pointValKey:l.pointValKey,keys:l.keys,pointArrayMap:l.pointArrayMap,toYData:l.toYData})});h(b,"afterSetOptions",function(f){f=f.options;var a=f.dataGrouping;a&&f.useOhlcData&&"highcharts-navigator-series"!==f.id&&(a.approximation="ohlc")})});w(b,"Stock/Indicators/SMA/SMAIndicator.js",[b["Core/Series/Series.js"],b["Mixins/IndicatorRequired.js"],b["Core/Utilities.js"]],function(b,g,h){var l=this&&this.__extends||function(){var d=function(a,c){d=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(d,a){d.__proto__=a}||function(d,a){for(var c in a)a.hasOwnProperty(c)&&(d[c]=a[c])};return d(a,c)};return function(a,c){function e(){this.constructor=a}d(a,c);a.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),k=b.seriesTypes.line,f=h.addEvent,a=h.error,e=h.extend,c=h.isArray,d=h.merge,p=h.pick,u=h.splat,q=g.generateMessage;g=function(e){function r(){var d=null!==e&&e.apply(this,arguments)||this;d.data=void 0;d.dataEventsToUnbind=void 0;d.linkedParent=void 0;
d.options=void 0;d.points=void 0;return d}l(r,e);r.prototype.destroy=function(){this.dataEventsToUnbind.forEach(function(d){d()});e.prototype.destroy.apply(this,arguments)};r.prototype.getName=function(){var d=this.name,a=[];d||((this.nameComponents||[]).forEach(function(d,c){a.push(this.options.params[d]+p(this.nameSuffixes[c],""))},this),d=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+a.join(", ")+")":""));return d};r.prototype.getValues=function(d,a){var e=a.period,p=d.xData;
d=d.yData;var u=d.length,f=0,q=0,m=[],n=[],r=[],k=-1;if(!(p.length<e)){for(c(d[0])&&(k=a.index?a.index:0);f<e-1;)q+=0>k?d[f]:d[f][k],f++;for(a=f;a<u;a++){q+=0>k?d[a]:d[a][k];var l=[p[a],q/e];m.push(l);n.push(l[0]);r.push(l[1]);q-=0>k?d[a-f]:d[a-f][k]}return{values:m,xData:n,yData:r}}};r.prototype.init=function(d,c){function p(){var d=m.points||[],a=(m.xData||[]).length,c=m.getValues(m.linkedParent,m.options.params)||{values:[],xData:[],yData:[]},e=[],p=!0;if(a&&!m.hasGroupedData&&m.visible&&m.points)if(m.cropped){if(m.xAxis){var f=
m.xAxis.min;var q=m.xAxis.max}a=m.cropData(c.xData,c.yData,f,q);for(f=0;f<a.xData.length;f++)e.push([a.xData[f]].concat(u(a.yData[f])));a=c.xData.indexOf(m.xData[0]);f=c.xData.indexOf(m.xData[m.xData.length-1]);-1===a&&f===c.xData.length-2&&e[0][0]===d[0].x&&e.shift();m.updateData(e)}else c.xData.length!==a-1&&c.xData.length!==a+1&&(p=!1,m.updateData(c.values));p&&(m.xData=c.xData,m.yData=c.yData,m.options.data=c.values);!1===m.bindTo.series&&(delete m.processedXData,m.isDirty=!0,m.redraw());m.isDirtyData=
!1}var m=this,r=m.requireIndicators();if(!r.allLoaded)return a(q(m.type,r.needed));e.prototype.init.call(m,d,c);d.linkSeries();m.dataEventsToUnbind=[];if(!m.linkedParent)return a("Series "+m.options.linkedTo+" not found! Check `linkedTo`.",!1,d);m.dataEventsToUnbind.push(f(m.bindTo.series?m.linkedParent:m.linkedParent.xAxis,m.bindTo.eventName,p));if("init"===m.calculateOn)p();else var n=f(m.chart,m.calculateOn,function(){p();n()})};r.prototype.processData=function(){var d=this.options.compareToMain,
a=this.linkedParent;e.prototype.processData.apply(this,arguments);a&&a.compareValue&&d&&(this.compareValue=a.compareValue)};r.prototype.requireIndicators=function(){var d={allLoaded:!0};this.requiredIndicators.forEach(function(a){b.seriesTypes[a]?b.seriesTypes[a].prototype.requireIndicators():(d.allLoaded=!1,d.needed=a)});return d};r.defaultOptions=d(k.defaultOptions,{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,period:14}});return r}(k);e(g.prototype,{bindTo:{series:!0,
eventName:"updatedData"},calculateOn:"init",hasDerivedData:!0,nameComponents:["period"],nameSuffixes:[],requiredIndicators:[],useCommonDataGrouping:!0});b.registerSeriesType("sma",g);"";return g});w(b,"Stock/Indicators/AD/ADIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){var h=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(d,a){d.__proto__=a}||function(d,a){for(var c in a)a.hasOwnProperty(c)&&(d[c]=
a[c])};return a(c,d)};return function(c,d){function e(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):(e.prototype=d.prototype,new e)}}(),l=b.seriesTypes.sma,k=g.error,f=g.extend,a=g.merge;g=function(e){function c(){var d=null!==e&&e.apply(this,arguments)||this;d.data=void 0;d.options=void 0;d.points=void 0;return d}h(c,e);c.populateAverage=function(d,a,c,e,f){f=a[e][1];var p=a[e][2];a=a[e][3];c=c[e];return[d[e],a===f&&a===p||f===p?0:(2*a-p-f)/(f-p)*c]};c.prototype.getValues=function(a,
e){var d=e.period,f=a.xData,p=a.yData,l=e.volumeSeriesID,n=a.chart.get(l);e=n&&n.yData;var m=p?p.length:0,v=[],B=[],b=[];if(!(f.length<=d&&m&&4!==p[0].length)){if(n){for(l=d;l<m;l++)a=v.length,n=c.populateAverage(f,p,e,l,d),0<a&&(n[1]+=v[a-1][1]),v.push(n),B.push(n[0]),b.push(n[1]);return{values:v,xData:B,yData:b}}k("Series "+l+" not found! Check `volumeSeriesID`.",!0,a.chart)}};c.defaultOptions=a(l.defaultOptions,{params:{volumeSeriesID:"volume"}});return c}(l);f(g.prototype,{nameComponents:!1,nameBase:"Accumulation/Distribution"});
b.registerSeriesType("ad",g);"";return g});w(b,"Stock/Indicators/AOIndicator.js",[b["Core/Series/Series.js"],b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,g,h){var l=h.correctFloat,k=h.isArray;b.seriesType("ao","sma",{greaterBarColor:"#06B535",lowerBarColor:"#F21313",threshold:0,groupPadding:.2,pointPadding:.2,crisp:!1,states:{hover:{halo:{size:0}}}},{nameBase:"AO",nameComponents:!1,markerAttribs:g.noop,getColumnMetrics:g.seriesTypes.column.prototype.getColumnMetrics,crispCol:g.seriesTypes.column.prototype.crispCol,
translate:g.seriesTypes.column.prototype.translate,drawPoints:g.seriesTypes.column.prototype.drawPoints,drawGraph:function(){var f=this.options,a=this.points,e=f.greaterBarColor;f=f.lowerBarColor;var c=a[0];if(!this.userOptions.color&&c)for(c.color=e,c=1;c<a.length;c++)a[c].color=a[c].y>a[c-1].y?e:a[c].y<a[c-1].y?f:a[c-1].color},getValues:function(f){var a=f.xData||[];f=f.yData||[];var e=f.length,c=[],d=[],p=[],u=0,q=0,r;if(!(34>=a.length)&&k(f[0])&&4===f[0].length){for(r=0;33>r;r++){var b=(f[r][1]+
f[r][2])/2;29<=r&&(u=l(u+b));q=l(q+b)}for(r=33;r<e;r++){b=(f[r][1]+f[r][2])/2;u=l(u+b);q=l(q+b);b=u/5;var n=q/34;b=l(b-n);c.push([a[r],b]);d.push(a[r]);p.push(b);b=r+1-5;n=r+1-34;u=l(u-(f[b][1]+f[b][2])/2);q=l(q-(f[n][1]+f[n][2])/2)}return{values:c,xData:d,yData:p}}}});""});w(b,"Mixins/MultipleLines.js",[b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,g){var h=g.defined,l=g.error,k=g.merge,f=b.seriesTypes.sma;return{pointArrayMap:["top","bottom"],pointValKey:"top",linesApiNames:["bottomLine"],
getTranslatedLinesNames:function(a){var e=[];(this.pointArrayMap||[]).forEach(function(c){c!==a&&e.push("plot"+c.charAt(0).toUpperCase()+c.slice(1))});return e},toYData:function(a){var e=[];(this.pointArrayMap||[]).forEach(function(c){e.push(a[c])});return e},translate:function(){var a=this,e=a.pointArrayMap,c=[],d;c=a.getTranslatedLinesNames();f.prototype.translate.apply(a,arguments);a.points.forEach(function(p){e.forEach(function(e,f){d=p[e];null!==d&&(p[c[f]]=a.yAxis.toPixels(d,!0))})})},drawGraph:function(){var a=
this,e=a.linesApiNames,c=a.points,d=c.length,p=a.options,u=a.graph,q={options:{gapSize:p.gapSize}},r=[],b;a.getTranslatedLinesNames(a.pointValKey).forEach(function(a,e){for(r[e]=[];d--;)b=c[d],r[e].push({x:b.x,plotX:b.plotX,plotY:b[a],isNull:!h(b[a])});d=c.length});e.forEach(function(d,c){r[c]?(a.points=r[c],p[d]?a.options=k(p[d].styles,q):l('Error: "There is no '+d+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),a.graph=
a["graph"+d],f.prototype.drawGraph.call(a),a["graph"+d]=a.graph):l('Error: "'+d+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});a.points=c;a.options=p;a.graph=u;f.prototype.drawGraph.call(a)}}});w(b,"Stock/Indicators/Aroon/AroonIndicator.js",[b["Core/Series/Series.js"],b["Mixins/MultipleLines.js"],b["Core/Utilities.js"]],function(b,g,h){function l(a,c){var d=a[0],e=0,f;for(f=1;f<a.length;f++)if("max"===c&&a[f]>=d||"min"===c&&a[f]<=d)d=
a[f],e=f;return e}var k=this&&this.__extends||function(){var a=function(d,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,d){for(var c in d)d.hasOwnProperty(c)&&(a[c]=d[c])};return a(d,c)};return function(d,c){function e(){this.constructor=d}a(d,c);d.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),f=b.seriesTypes.sma,a=h.extend,e=h.merge,c=h.pick;h=function(a){function d(){var d=null!==a&&a.apply(this,arguments)||this;d.data=
void 0;d.options=void 0;d.points=void 0;return d}k(d,a);d.prototype.getValues=function(a,d){d=d.period;var e=a.xData,f=(a=a.yData)?a.length:0,p=[],m=[],u=[],q;for(q=d-1;q<f;q++){var k=a.slice(q-d+1,q+2);var b=l(k.map(function(a){return c(a[2],a)}),"min");k=l(k.map(function(a){return c(a[1],a)}),"max");k=k/d*100;b=b/d*100;e[q+1]&&(p.push([e[q+1],k,b]),m.push(e[q+1]),u.push([k,b]))}return{values:p,xData:m,yData:u}};d.defaultOptions=e(f.defaultOptions,{params:{period:25},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Aroon Up: {point.y}<br/>Aroon Down: {point.aroonDown}<br/>'},
aroonDown:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}});return d}(f);a(h.prototype,{linesApiNames:["aroonDown"],nameBase:"Aroon",pointArrayMap:["y","aroonDown"],pointValKey:"y",drawGraph:g.drawGraph,getTranslatedLinesNames:g.getTranslatedLinesNames,toYData:g.toYData,translate:g.translate});b.registerSeriesType("aroon",h);"";return h});w(b,"Stock/Indicators/AroonOscillatorIndicator.js",[b["Core/Series/Series.js"],b["Mixins/MultipleLines.js"],b["Mixins/IndicatorRequired.js"],
b["Core/Utilities.js"]],function(b,g,h,l){l=l.merge;var k=b.seriesTypes.aroon;b.seriesType("aroonoscillator","aroon",{params:{period:25},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b>: {point.y}'}},l(g,{nameBase:"Aroon Oscillator",pointArrayMap:["y"],pointValKey:"y",linesApiNames:[],init:function(){var f=arguments,a=this;h.isParentLoaded(k,"aroon",a.type,function(e){e.prototype.init.apply(a,f)})},getValues:function(f,a){var e=[],c=[],d=[];f=k.prototype.getValues.call(this,
f,a);for(a=0;a<f.yData.length;a++){var p=f.yData[a][0];var u=f.yData[a][1];p-=u;e.push([f.xData[a],p]);c.push(f.xData[a]);d.push(p)}return{values:e,xData:c,yData:d}}}));""});w(b,"Stock/Indicators/ATR/ATRIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){function h(a,c){return Math.max(a[1]-a[2],"undefined"===typeof c?0:Math.abs(a[1]-c[3]),"undefined"===typeof c?0:Math.abs(a[2]-c[3]))}var l=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(a,d){a.__proto__=d}||function(a,d){for(var c in d)d.hasOwnProperty(c)&&(a[c]=d[c])};return a(c,d)};return function(c,d){function e(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):(e.prototype=d.prototype,new e)}}(),k=b.seriesTypes.sma,f=g.isArray,a=g.merge;g=function(e){function c(){var a=null!==e&&e.apply(this,arguments)||this;a.data=void 0;a.points=void 0;a.options=void 0;return a}l(c,e);c.prototype.getValues=function(a,c){c=c.period;var d=a.xData,e=(a=a.yData)?
a.length:0,p=1,k=0,n=0,m=[],b=[],l=[],g;var A=[[d[0],a[0]]];if(!(d.length<=c)&&f(a[0])&&4===a[0].length){for(g=1;g<=e;g++)if(A.push([d[g],a[g]]),c<p){var z=c;var t=d[g-1],y=h(a[g-1],a[g-2]);z=[t,(k*(z-1)+y)/z];k=z[1];m.push(z);b.push(z[0]);l.push(z[1])}else c===p?(k=n/(g-1),m.push([d[g-1],k]),b.push(d[g-1]),l.push(k)):n+=h(a[g-1],a[g-2]),p++;return{values:m,xData:b,yData:l}}};c.defaultOptions=a(k.defaultOptions,{params:{period:14}});return c}(k);b.registerSeriesType("atr",g);"";return g});w(b,"Stock/Indicators/BB/BBIndicator.js",
[b["Core/Series/Series.js"],b["Mixins/MultipleLines.js"],b["Core/Utilities.js"]],function(b,g,h){var l=this&&this.__extends||function(){var a=function(d,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,d){for(var c in d)d.hasOwnProperty(c)&&(a[c]=d[c])};return a(d,c)};return function(d,c){function e(){this.constructor=d}a(d,c);d.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),k=b.seriesTypes.sma,f=h.extend,a=h.isArray,e=h.merge;
h=function(c){function d(){var a=null!==c&&c.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}l(d,c);d.prototype.init=function(){b.seriesTypes.sma.prototype.init.apply(this,arguments);this.options=e({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)};d.prototype.getValues=function(d,c){var e=c.period,f=c.standardDeviation,p=d.xData,u=(d=d.yData)?d.length:0,m=[],k=[],l=[],g;if(!(p.length<e)){var h=a(d[0]);for(g=e;g<=
u;g++){var z=p.slice(g-e,g);var t=d.slice(g-e,g);var y=b.seriesTypes.sma.prototype.getValues.call(this,{xData:z,yData:t},c);z=y.xData[0];y=y.yData[0];for(var D=0,E=t.length,K=0;K<E;K++){var C=(h?t[K][c.index]:t[K])-y;D+=C*C}C=Math.sqrt(D/(E-1));t=y+f*C;C=y-f*C;m.push([z,t,y,C]);k.push(z);l.push([t,y,C])}return{values:m,xData:k,yData:l}}};d.defaultOptions=e(k.defaultOptions,{params:{period:20,standardDeviation:2,index:3},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1,
lineColor:void 0}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Top: {point.top}<br/>Middle: {point.middle}<br/>Bottom: {point.bottom}<br/>'},marker:{enabled:!1},dataGrouping:{approximation:"averages"}});return d}(k);f(h.prototype,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameComponents:["period","standardDeviation"],linesApiNames:["topLine","bottomLine"],drawGraph:g.drawGraph,getTranslatedLinesNames:g.getTranslatedLinesNames,translate:g.translate,
toYData:g.toYData});b.registerSeriesType("bb",h);"";return h});w(b,"Stock/Indicators/CCIIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){function h(k){return k.reduce(function(f,a){return f+a},0)}var l=g.isArray;b.seriesType("cci","sma",{params:{period:14}},{getValues:function(k,f){f=f.period;var a=k.xData,e=(k=k.yData)?k.length:0,c=[],d=1,p=[],u=[],q=[];if(!(a.length<=f)&&l(k[0])&&4===k[0].length){for(;d<f;){var b=k[d-1];c.push((b[1]+b[2]+b[3])/3);d++}for(d=f;d<=e;d++){b=
k[d-1];b=(b[1]+b[2]+b[3])/3;var g=c.push(b);var n=c.slice(g-f);g=h(n)/f;var m,v=n.length,B=0;for(m=0;m<v;m++)B+=Math.abs(g-n[m]);n=B/f;b=(b-g)/(.015*n);p.push([a[d-1],b]);u.push(a[d-1]);q.push(b)}return{values:p,xData:u,yData:q}}}});""});w(b,"Stock/Indicators/CMF/CMFIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){var h=this&&this.__extends||function(){var f=function(a,e){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,
d){for(var c in d)d.hasOwnProperty(c)&&(a[c]=d[c])};return f(a,e)};return function(a,e){function c(){this.constructor=a}f(a,e);a.prototype=null===e?Object.create(e):(c.prototype=e.prototype,new c)}}(),l=b.seriesTypes.sma,k=g.merge;g=function(f){function a(){var a=null!==f&&f.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;a.volumeSeries=void 0;a.linkedParent=void 0;a.yData=void 0;a.nameBase="Chaikin Money Flow";return a}h(a,f);a.prototype.isValid=function(){var a=this.chart,
c=this.options,d=this.linkedParent;a=this.volumeSeries||(this.volumeSeries=a.get(c.params.volumeSeriesID));var f=d&&d.yData&&4===d.yData[0].length;return!!(d&&a&&d.xData&&d.xData.length>=c.params.period&&a.xData&&a.xData.length>=c.params.period&&f)};a.prototype.getValues=function(a,c){if(this.isValid())return this.getMoneyFlow(a.xData,a.yData,this.volumeSeries.yData,c.period)};a.prototype.getMoneyFlow=function(a,c,d,f){function e(a,d){var c=a[1],e=a[2];a=a[3];return null!==d&&null!==c&&null!==e&&
null!==a&&c!==e?(a-e-(c-a))/(c-e)*d:(A=h,null)}var p=c.length,b=[],k=0,n=0,m=[],l=[],g=[],h,A=-1;if(0<f&&f<=p){for(h=0;h<f;h++)b[h]=e(c[h],d[h]),k+=d[h],n+=b[h];m.push(a[h-1]);l.push(h-A>=f&&0!==k?n/k:null);for(g.push([m[0],l[0]]);h<p;h++){b[h]=e(c[h],d[h]);k-=d[h-f];k+=d[h];n-=b[h-f];n+=b[h];var z=[a[h],h-A>=f?n/k:null];m.push(z[0]);l.push(z[1]);g.push([z[0],z[1]])}}return{values:g,xData:m,yData:l}};a.defaultOptions=k(l.defaultOptions,{params:{period:14,volumeSeriesID:"volume"}});return a}(l);b.registerSeriesType("cmf",
g);"";return g});w(b,"Stock/Indicators/DPOIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){function h(f,a,e,c,d){a=k(a[e][c],a[e]);return d?l(f-a):l(f+a)}var l=g.correctFloat,k=g.pick;b.seriesType("dpo","sma",{params:{period:21}},{nameBase:"DPO",getValues:function(f,a){var e=a.period;a=a.index;var c=e+Math.floor(e/2+1),d=f.xData||[];f=f.yData||[];var p=f.length,b=[],q=[],l=[],g=0,n,m;if(!(d.length<=c)){for(n=0;n<e-1;n++)g=h(g,f,n,a);for(m=0;m<=p-c;m++){var v=m+e-1;n=
m+c-1;g=h(g,f,v,a);v=k(f[n][a],f[n]);v-=g/e;g=h(g,f,m,a,!0);b.push([d[n],v]);q.push(d[n]);l.push(v)}return{values:b,xData:q,yData:l}}}});""});w(b,"Stock/Indicators/EMA/EMAIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){var h=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,d){for(var c in d)d.hasOwnProperty(c)&&(a[c]=d[c])};return a(c,d)};return function(c,d){function e(){this.constructor=
c}a(c,d);c.prototype=null===d?Object.create(d):(e.prototype=d.prototype,new e)}}(),l=b.seriesTypes.sma,k=g.correctFloat,f=g.isArray,a=g.merge;g=function(e){function c(){var a=null!==e&&e.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(c,e);c.prototype.accumulatePeriodPoints=function(a,c,e){for(var d=0,f=0,b;f<a;)b=0>c?e[f]:e[f][c],d+=b,f++;return d};c.prototype.calculateEma=function(a,c,e,f,b,l,n){a=a[e-1];c=0>l?c[e-1]:c[e-1][l];f="undefined"===typeof b?n:k(c*
f+b*(1-f));return[a,f]};c.prototype.getValues=function(a,c){var d=c.period,e=a.xData,b=(a=a.yData)?a.length:0,k=2/(d+1),p=[],m=[],l=[],g=-1;if(!(b<d)){f(a[0])&&(g=c.index?c.index:0);c=this.accumulatePeriodPoints(d,g,a);for(c/=d;d<b+1;d++){var h=this.calculateEma(e,a,d,k,h,g,c);p.push(h);m.push(h[0]);l.push(h[1]);h=h[1]}return{values:p,xData:m,yData:l}}};c.defaultOptions=a(l.defaultOptions,{params:{index:3,period:9}});return c}(l);b.registerSeriesType("ema",g);"";return g});w(b,"Stock/Indicators/ChaikinIndicator.js",
[b["Core/Series/Series.js"],b["Mixins/IndicatorRequired.js"],b["Core/Utilities.js"]],function(b,g,h){var l=b.seriesTypes,k=l.ad,f=l.ema,a=h.correctFloat,e=h.error;b.seriesType("chaikin","ema",{params:{volumeSeriesID:"volume",periods:[3,10]}},{nameBase:"Chaikin Osc",nameComponents:["periods"],init:function(){var a=arguments,d=this;g.isParentLoaded(f,"ema",d.type,function(c){c.prototype.init.apply(d,a)})},getValues:function(c,d){var b=d.periods,l=d.period,q=[],g=[],h=[],n;if(2!==b.length||b[1]<=b[0])e('Error: "Chaikin requires two periods. Notice, first period should be lower than the second one."');
else if(d=k.prototype.getValues.call(this,c,{volumeSeriesID:d.volumeSeriesID,period:l}))if(c=f.prototype.getValues.call(this,d,{period:b[0]}),d=f.prototype.getValues.call(this,d,{period:b[1]}),c&&d){b=b[1]-b[0];for(n=0;n<d.yData.length;n++)l=a(c.yData[n+b]-d.yData[n]),q.push([d.xData[n],l]),g.push(d.xData[n]),h.push(l);return{values:q,xData:g,yData:h}}}});""});w(b,"Stock/Indicators/DEMAIndicator.js",[b["Core/Series/Series.js"],b["Mixins/IndicatorRequired.js"],b["Core/Utilities.js"]],function(b,g,
h){var l=h.correctFloat,k=h.isArray,f=b.seriesTypes.ema;b.seriesType("dema","ema",{},{init:function(){var a=arguments,e=this;g.isParentLoaded(f,"ema",e.type,function(c){c.prototype.init.apply(e,a)})},getEMA:function(a,e,c,d,b,k){return f.prototype.calculateEma(k||[],a,"undefined"===typeof b?1:b,this.chart.series[0].EMApercent,e,"undefined"===typeof d?-1:d,c)},getValues:function(a,e){var c=e.period,d=2*c,b=a.xData,u=a.yData,q=u?u.length:0,g=-1,h=[],n=[],m=[],v=0,B=[],I;a.EMApercent=2/(c+1);if(!(q<
2*c-1)){k(u[0])&&(g=e.index?e.index:0);a=f.prototype.accumulatePeriodPoints(c,g,u);e=a/c;a=0;for(I=c;I<q+2;I++){I<q+1&&(v=this.getEMA(u,A,e,g,I)[1],B.push(v));var A=v;if(I<d)a+=v;else{I===d&&(e=a/c);v=B[I-c-1];var z=this.getEMA([v],z,e)[1];var t=[b[I-2],l(2*v-z)];h.push(t);n.push(t[0]);m.push(t[1])}}return{values:h,xData:n,yData:m}}}});""});w(b,"Stock/Indicators/TEMAIndicator.js",[b["Core/Series/Series.js"],b["Mixins/IndicatorRequired.js"],b["Core/Utilities.js"]],function(b,g,h){var l=h.correctFloat,
k=h.isArray,f=b.seriesTypes.ema;b.seriesType("tema","ema",{},{init:function(){var a=arguments,e=this;g.isParentLoaded(f,"ema",e.type,function(c){c.prototype.init.apply(e,a)})},getEMA:function(a,e,c,d,b,k){return f.prototype.calculateEma(k||[],a,"undefined"===typeof b?1:b,this.chart.series[0].EMApercent,e,"undefined"===typeof d?-1:d,c)},getTemaPoint:function(a,e,c,d){return[a[d-3],l(3*c.level1-3*c.level2+c.level3)]},getValues:function(a,e){var c=e.period,d=2*c,b=3*c,l=a.xData,q=a.yData,g=q?q.length:
0,h=-1,n=[],m=[],v=[],B=[],I=[],A,z,t={};a.EMApercent=2/(c+1);if(!(g<3*c-2)){k(q[0])&&(h=e.index?e.index:0);a=f.prototype.accumulatePeriodPoints(c,h,q);e=a/c;a=0;for(A=c;A<g+3;A++){A<g+1&&(t.level1=this.getEMA(q,y,e,h,A)[1],B.push(t.level1));var y=t.level1;if(A<d)a+=t.level1;else{A===d&&(e=a/c,a=0);t.level1=B[A-c-1];t.level2=this.getEMA([t.level1],D,e)[1];I.push(t.level2);var D=t.level2;if(A<b)a+=t.level2;else{A===b&&(e=a/c);A===g+1&&(t.level1=B[A-c-1],t.level2=this.getEMA([t.level1],D,e)[1],I.push(t.level2));
t.level1=B[A-c-2];t.level2=I[A-2*c-1];t.level3=this.getEMA([t.level2],t.prevLevel3,e)[1];if(z=this.getTemaPoint(l,b,t,A))n.push(z),m.push(z[0]),v.push(z[1]);t.prevLevel3=t.level3}}}return{values:n,xData:m,yData:v}}}});""});w(b,"Stock/Indicators/TRIXIndicator.js",[b["Core/Series/Series.js"],b["Mixins/IndicatorRequired.js"],b["Core/Utilities.js"]],function(b,g,h){var l=h.correctFloat,k=b.seriesTypes.tema;b.seriesType("trix","tema",{},{init:function(){var f=arguments,a=this;g.isParentLoaded(k,"tema",
a.type,function(e){e.prototype.init.apply(a,f)})},getTemaPoint:function(f,a,e,c){if(c>a)var d=[f[c-3],0!==e.prevLevel3?l(e.level3-e.prevLevel3)/e.prevLevel3*100:null];return d}});""});w(b,"Stock/Indicators/APOIndicator.js",[b["Core/Series/Series.js"],b["Mixins/IndicatorRequired.js"],b["Core/Utilities.js"]],function(b,g,h){var l=h.error,k=b.seriesTypes.ema;b.seriesType("apo","ema",{params:{periods:[10,20]}},{nameBase:"APO",nameComponents:["periods"],init:function(){var f=arguments,a=this;g.isParentLoaded(k,
"ema",a.type,function(e){e.prototype.init.apply(a,f)})},getValues:function(f,a){var e=a.periods,c=a.index;a=[];var d=[],b=[],g;if(2!==e.length||e[1]<=e[0])l('Error: "APO requires two periods. Notice, first period should be lower than the second one."');else{var q=k.prototype.getValues.call(this,f,{index:c,period:e[0]});f=k.prototype.getValues.call(this,f,{index:c,period:e[1]});if(q&&f){e=e[1]-e[0];for(g=0;g<f.yData.length;g++)c=q.yData[g+e]-f.yData[g],a.push([f.xData[g],c]),d.push(f.xData[g]),b.push(c);
return{values:a,xData:d,yData:b}}}}});""});w(b,"Stock/Indicators/IKHIndicator.js",[b["Core/Series/Series.js"],b["Core/Color/Color.js"],b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,g,h,l){function k(a){return a.reduce(function(a,d){return Math.max(a,d[1])},-Infinity)}function f(a){return a.reduce(function(a,d){return Math.min(a,d[2])},Infinity)}function a(a){return{high:k(a),low:f(a)}}function e(a){var d,c,e,f,b;a.series.forEach(function(a){if(a.xData)for(f=a.xData,b=c=a.xIncrement?1:f.length-
1;0<b;b--)if(e=f[b]-f[b-1],"undefined"===typeof d||e<d)d=e});return d}function c(a,d,c,e){if(a&&d&&c&&e){var f=d.plotX-a.plotX;d=d.plotY-a.plotY;var b=e.plotX-c.plotX;e=e.plotY-c.plotY;var m=a.plotX-c.plotX,k=a.plotY-c.plotY;c=(-d*m+f*k)/(-b*d+f*e);b=(b*k-e*m)/(-b*d+f*e);if(0<=c&&1>=c&&0<=b&&1>=b)return{plotX:a.plotX+b*f,plotY:a.plotY+b*d}}return!1}function d(a){var d=a.indicator;d.points=a.points;d.nextPoints=a.nextPoints;d.color=a.color;d.options=r(a.options.senkouSpan.styles,a.gap);d.graph=a.graph;
d.fillGraph=!0;n.prototype.drawGraph.call(d)}var p=g.parse,u=l.defined,q=l.isArray,r=l.merge,x=l.objectEach,n=b.seriesTypes.sma;h.approximations["ichimoku-averages"]=function(){var a=[],d;[].forEach.call(arguments,function(c,e){a.push(h.approximations.average(c));d=!d&&"undefined"===typeof a[e]});return d?void 0:a};b.seriesType("ikh","sma",{params:{period:26,periodTenkan:9,periodSenkouSpanB:52},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>TENKAN SEN: {point.tenkanSen:.3f}<br/>KIJUN SEN: {point.kijunSen:.3f}<br/>CHIKOU SPAN: {point.chikouSpan:.3f}<br/>SENKOU SPAN A: {point.senkouSpanA:.3f}<br/>SENKOU SPAN B: {point.senkouSpanB:.3f}<br/>'},
tenkanLine:{styles:{lineWidth:1,lineColor:void 0}},kijunLine:{styles:{lineWidth:1,lineColor:void 0}},chikouLine:{styles:{lineWidth:1,lineColor:void 0}},senkouSpanA:{styles:{lineWidth:1,lineColor:void 0}},senkouSpanB:{styles:{lineWidth:1,lineColor:void 0}},senkouSpan:{styles:{fill:"rgba(255, 0, 0, 0.5)"}},dataGrouping:{approximation:"ichimoku-averages"}},{pointArrayMap:["tenkanSen","kijunSen","chikouSpan","senkouSpanA","senkouSpanB"],pointValKey:"tenkanSen",nameComponents:["periodSenkouSpanB","period",
"periodTenkan"],init:function(){n.prototype.init.apply(this,arguments);this.options=r({tenkanLine:{styles:{lineColor:this.color}},kijunLine:{styles:{lineColor:this.color}},chikouLine:{styles:{lineColor:this.color}},senkouSpanA:{styles:{lineColor:this.color,fill:p(this.color).setOpacity(.5).get()}},senkouSpanB:{styles:{lineColor:this.color,fill:p(this.color).setOpacity(.5).get()}},senkouSpan:{styles:{fill:p(this.color).setOpacity(.2).get()}}},this.options)},toYData:function(a){return[a.tenkanSen,a.kijunSen,
a.chikouSpan,a.senkouSpanA,a.senkouSpanB]},translate:function(){var a=this;n.prototype.translate.apply(a);a.points.forEach(function(d){a.pointArrayMap.forEach(function(c){u(d[c])&&(d["plot"+c]=a.yAxis.toPixels(d[c],!0),d.plotY=d["plot"+c],d.tooltipPos=[d.plotX,d["plot"+c]],d.isNull=!1)})})},drawGraph:function(){var a=this,e=a.points,f=e.length,b=a.options,k=a.graph,l=a.color,q={options:{gapSize:b.gapSize}},p=a.pointArrayMap.length,g=[[],[],[],[],[],[]],h={tenkanLine:g[0],kijunLine:g[1],chikouLine:g[2],
senkouSpanA:g[3],senkouSpanB:g[4],senkouSpan:g[5]},y=[],C=a.options.senkouSpan,w=C.color||C.styles.fill,G=C.negativeColor,N=[[],[]],L=[[],[]],P=0,M,Q,O;for(a.ikhMap=h;f--;){var F=e[f];for(M=0;M<p;M++)C=a.pointArrayMap[M],u(F[C])&&g[M].push({plotX:F.plotX,plotY:F["plot"+C],isNull:!1});G&&f!==e.length-1&&(C=h.senkouSpanB.length-1,F=c(h.senkouSpanA[C-1],h.senkouSpanA[C],h.senkouSpanB[C-1],h.senkouSpanB[C]),M={plotX:F.plotX,plotY:F.plotY,isNull:!1,intersectPoint:!0},F&&(h.senkouSpanA.splice(C,0,M),h.senkouSpanB.splice(C,
0,M),y.push(C)))}x(h,function(d,c){b[c]&&"senkouSpan"!==c&&(a.points=g[P],a.options=r(b[c].styles,q),a.graph=a["graph"+c],a.fillGraph=!1,a.color=l,n.prototype.drawGraph.call(a),a["graph"+c]=a.graph);P++});a.graphCollection&&a.graphCollection.forEach(function(d){a[d].destroy();delete a[d]});a.graphCollection=[];if(G&&h.senkouSpanA[0]&&h.senkouSpanB[0]){y.unshift(0);y.push(h.senkouSpanA.length-1);for(p=0;p<y.length-1;p++){C=y[p];F=y[p+1];f=h.senkouSpanB.slice(C,F+1);C=h.senkouSpanA.slice(C,F+1);if(1<=
Math.floor(f.length/2))if(F=Math.floor(f.length/2),f[F].plotY===C[F].plotY){for(O=M=F=0;O<f.length;O++)F+=f[O].plotY,M+=C[O].plotY;F=F>M?0:1}else F=f[F].plotY>C[F].plotY?0:1;else F=f[0].plotY>C[0].plotY?0:1;N[F]=N[F].concat(f);L[F]=L[F].concat(C)}["graphsenkouSpanColor","graphsenkouSpanNegativeColor"].forEach(function(c,e){N[e].length&&L[e].length&&(Q=0===e?w:G,d({indicator:a,points:N[e],nextPoints:L[e],color:Q,options:b,gap:q,graph:a[c]}),a[c]=a.graph,a.graphCollection.push(c))})}else d({indicator:a,
points:h.senkouSpanB,nextPoints:h.senkouSpanA,color:w,options:b,gap:q,graph:a.graphsenkouSpan}),a.graphsenkouSpan=a.graph;delete a.nextPoints;delete a.fillGraph;a.points=e;a.options=b;a.graph=k},getGraphPath:function(a){var d=[],c;a=a||this.points;if(this.fillGraph&&this.nextPoints){if((c=n.prototype.getGraphPath.call(this,this.nextPoints))&&c.length){c[0][0]="L";d=n.prototype.getGraphPath.call(this,a);c=c.slice(0,d.length);for(var e=c.length-1;0<=e;e--)d.push(c[e])}}else d=n.prototype.getGraphPath.apply(this,
arguments);return d},getValues:function(d,c){var f=c.period,b=c.periodTenkan;c=c.periodSenkouSpanB;var k=d.xData,l=d.yData,g=l&&l.length||0;d=e(d.xAxis);var p=[],n=[],h;if(!(k.length<=f)&&q(l[0])&&4===l[0].length){var m=k[0]-f*d;for(h=0;h<f;h++)n.push(m+h*d);for(h=0;h<g;h++){if(h>=b){var u=l.slice(h-b,h);u=a(u);u=(u.high+u.low)/2}if(h>=f){var r=l.slice(h-f,h);r=a(r);r=(r.high+r.low)/2;var v=(u+r)/2}if(h>=c){var x=l.slice(h-c,h);x=a(x);x=(x.high+x.low)/2}m=l[h][3];var y=k[h];"undefined"===typeof p[h]&&
(p[h]=[]);"undefined"===typeof p[h+f]&&(p[h+f]=[]);p[h+f][0]=u;p[h+f][1]=r;p[h+f][2]=void 0;p[h][2]=m;h<=f&&(p[h+f][3]=void 0,p[h+f][4]=void 0);"undefined"===typeof p[h+2*f]&&(p[h+2*f]=[]);p[h+2*f][3]=v;p[h+2*f][4]=x;n.push(y)}for(h=1;h<=f;h++)n.push(y+h*d);return{values:p,xData:n,yData:p}}}});""});w(b,"Stock/Indicators/KeltnerChannelsIndicator.js",[b["Core/Series/Series.js"],b["Mixins/MultipleLines.js"],b["Core/Utilities.js"]],function(b,g,h){var l=b.seriesTypes,k=h.correctFloat,f=h.merge,a=l.sma,
e=l.ema,c=l.atr;b.seriesType("keltnerchannels","sma",{params:{period:20,periodATR:10,multiplierATR:2},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1,lineColor:void 0}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Upper Channel: {point.top}<br/>EMA({series.options.params.period}): {point.middle}<br/>Lower Channel: {point.bottom}<br/>'},marker:{enabled:!1},dataGrouping:{approximation:"averages"},lineWidth:1},f(g,{pointArrayMap:["top",
"middle","bottom"],pointValKey:"middle",nameBase:"Keltner Channels",nameComponents:["period","periodATR","multiplierATR"],linesApiNames:["topLine","bottomLine"],requiredIndicators:["ema","atr"],init:function(){a.prototype.init.apply(this,arguments);this.options=f({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(a,f){var d=f.period,b=f.periodATR,h=f.multiplierATR,l=a.yData;l=l?l.length:0;var p=[];f=e.prototype.getValues(a,{period:d,
index:f.index});var g=c.prototype.getValues(a,{period:b}),v=[],B=[],y;if(!(l<d)){for(y=d;y<=l;y++){var A=f.values[y-d];var z=g.values[y-b];var t=A[0];a=k(A[1]+h*z[1]);z=k(A[1]-h*z[1]);A=A[1];p.push([t,a,A,z]);v.push(t);B.push([a,A,z])}return{values:p,xData:v,yData:B}}}}));""});w(b,"Stock/Indicators/MACDIndicator.js",[b["Core/Series/Series.js"],b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,g,h){var l=b.seriesTypes,k=h.correctFloat,f=h.defined,a=h.merge,e=l.sma,c=l.ema;b.seriesType("macd",
"sma",{params:{shortPeriod:12,longPeriod:26,signalPeriod:9,period:26},signalLine:{zones:[],styles:{lineWidth:1,lineColor:void 0}},macdLine:{zones:[],styles:{lineWidth:1,lineColor:void 0}},threshold:0,groupPadding:.1,pointPadding:.1,crisp:!1,states:{hover:{halo:{size:0}}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Value: {point.MACD}<br/>Signal: {point.signal}<br/>Histogram: {point.y}<br/>'},dataGrouping:{approximation:"averages"},minPointLength:0},
{nameComponents:["longPeriod","shortPeriod","signalPeriod"],requiredIndicators:["ema"],pointArrayMap:["y","signal","MACD"],parallelArrays:["x","y","signal","MACD"],pointValKey:"y",markerAttribs:g.noop,getColumnMetrics:g.seriesTypes.column.prototype.getColumnMetrics,crispCol:g.seriesTypes.column.prototype.crispCol,init:function(){e.prototype.init.apply(this,arguments);this.options&&(this.options=a({signalLine:{styles:{lineColor:this.color}},macdLine:{styles:{color:this.color}}},this.options),this.macdZones=
{zones:this.options.macdLine.zones,startIndex:0},this.signalZones={zones:this.macdZones.zones.concat(this.options.signalLine.zones),startIndex:this.macdZones.zones.length},this.resetZones=!0)},toYData:function(a){return[a.y,a.signal,a.MACD]},translate:function(){var a=this,c=["plotSignal","plotMACD"];g.seriesTypes.column.prototype.translate.apply(a);a.points.forEach(function(d){[d.signal,d.MACD].forEach(function(e,f){null!==e&&(d[c[f]]=a.yAxis.toPixels(e,!0))})})},destroy:function(){this.graph=null;
this.graphmacd=this.graphmacd&&this.graphmacd.destroy();this.graphsignal=this.graphsignal&&this.graphsignal.destroy();e.prototype.destroy.apply(this,arguments)},drawPoints:g.seriesTypes.column.prototype.drawPoints,drawGraph:function(){for(var d=this,c=d.points,b=c.length,k=d.options,h=d.zones,l={options:{gapSize:k.gapSize}},g=[[],[]],m;b--;)m=c[b],f(m.plotMACD)&&g[0].push({plotX:m.plotX,plotY:m.plotMACD,isNull:!f(m.plotMACD)}),f(m.plotSignal)&&g[1].push({plotX:m.plotX,plotY:m.plotSignal,isNull:!f(m.plotMACD)});
["macd","signal"].forEach(function(c,f){d.points=g[f];d.options=a(k[c+"Line"].styles,l);d.graph=d["graph"+c];d.currentLineZone=c+"Zones";d.zones=d[d.currentLineZone].zones;e.prototype.drawGraph.call(d);d["graph"+c]=d.graph});d.points=c;d.options=k;d.zones=h;d.currentLineZone=null},getZonesGraphs:function(a){var d=e.prototype.getZonesGraphs.call(this,a),c=d;this.currentLineZone&&(c=d.splice(this[this.currentLineZone].startIndex+1),c.length?c.splice(0,0,a[0]):c=[a[0]]);return c},applyZones:function(){var a=
this.zones;this.zones=this.signalZones.zones;e.prototype.applyZones.call(this);this.graphmacd&&this.options.macdLine.zones.length&&this.graphmacd.hide();this.zones=a},getValues:function(a,e){var d=0,b=[],h=[],l=[];if(!(a.xData.length<e.longPeriod+e.signalPeriod)){var g=c.prototype.getValues(a,{period:e.shortPeriod});var p=c.prototype.getValues(a,{period:e.longPeriod});g=g.values;p=p.values;for(a=1;a<=g.length;a++)f(p[a-1])&&f(p[a-1][1])&&f(g[a+e.shortPeriod+1])&&f(g[a+e.shortPeriod+1][0])&&b.push([g[a+
e.shortPeriod+1][0],0,null,g[a+e.shortPeriod+1][1]-p[a-1][1]]);for(a=0;a<b.length;a++)h.push(b[a][0]),l.push([0,null,b[a][3]]);e=c.prototype.getValues({xData:h,yData:l},{period:e.signalPeriod,index:2});e=e.values;for(a=0;a<b.length;a++)b[a][0]>=e[0][0]&&(b[a][2]=e[d][1],l[a]=[0,e[d][1],b[a][3]],null===b[a][3]?(b[a][1]=0,l[a][0]=0):(b[a][1]=k(b[a][3]-e[d][1]),l[a][0]=k(b[a][3]-e[d][1])),d++);return{values:b,xData:h,yData:l}}}});""});w(b,"Stock/Indicators/MFIIndicator.js",[b["Core/Series/Series.js"],
b["Core/Utilities.js"]],function(b,g){function h(a){return a.reduce(function(a,c){return a+c})}function l(a){return(a[1]+a[2]+a[3])/3}var k=g.error,f=g.isArray;b.seriesType("mfi","sma",{params:{period:14,volumeSeriesID:"volume",decimals:4}},{nameBase:"Money Flow Index",getValues:function(a,e){var c=e.period,d=a.xData,b=a.yData,g=b?b.length:0,q=e.decimals,r=1,x=a.chart.get(e.volumeSeriesID),n=x&&x.yData,m=[],v=[],B=[],y=[],A=[];if(!x)k("Series "+e.volumeSeriesID+" not found! Check `volumeSeriesID`.",
!0,a.chart);else if(!(d.length<=c)&&f(b[0])&&4===b[0].length&&n){for(a=l(b[r]);r<c+1;)e=a,a=l(b[r]),e=a>=e,x=a*n[r],y.push(e?x:0),A.push(e?0:x),r++;for(c=r-1;c<g;c++)c>r-1&&(y.shift(),A.shift(),e=a,a=l(b[c]),e=a>e,x=a*n[c],y.push(e?x:0),A.push(e?0:x)),e=h(A),x=h(y),e=x/e,e=parseFloat((100-100/(1+e)).toFixed(q)),m.push([d[c],e]),v.push(d[c]),B.push(e);return{values:m,xData:v,yData:B}}}});""});w(b,"Stock/Indicators/MomentumIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,
g){function h(b,f,a,e,c){a=a[e-1][3]-a[e-c-1][3];f=f[e-1];b.shift();return[f,a]}var l=g.isArray;b.seriesType("momentum","sma",{params:{period:14}},{nameBase:"Momentum",getValues:function(b,f){f=f.period;var a=b.xData,e=(b=b.yData)?b.length:0,c=a[0],d=[],k=[],g=[];if(!(a.length<=f)&&l(b[0])){var q=b[0][3];q=[[c,q]];for(c=f+1;c<e;c++){var r=h(q,a,b,c,f,void 0);d.push(r);k.push(r[0]);g.push(r[1])}r=h(q,a,b,c,f,void 0);d.push(r);k.push(r[0]);g.push(r[1]);return{values:d,xData:k,yData:g}}}});""});w(b,
"Stock/Indicators/NATRIndicator.js",[b["Core/Series/Series.js"]],function(b){var g=b.seriesTypes.atr;b.seriesType("natr","sma",{tooltip:{valueSuffix:"%"}},{requiredIndicators:["atr"],getValues:function(b,l){var k=g.prototype.getValues.apply(this,arguments),f=k.values.length,a=l.period-1,e=b.yData,c=0;if(k){for(;c<f;c++)k.yData[c]=k.values[c][1]/e[a][3]*100,k.values[c][1]=k.yData[c],a++;return k}}});""});w(b,"Stock/Indicators/PivotPointsIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],
function(b,g){function h(a,e){var c=a.series.pointArrayMap,d=c.length;for(f.prototype.pointClass.prototype[e].call(a);d--;)e="dataLabel"+c[d],a[e]&&a[e].element&&a[e].destroy(),a[e]=null}var l=g.defined,k=g.isArray,f=b.seriesTypes.sma;b.seriesType("pivotpoints","sma",{params:{period:28,algorithm:"standard"},marker:{enabled:!1},enableMouseTracking:!1,dataLabels:{enabled:!0,format:"{point.pivotLine}"},dataGrouping:{approximation:"averages"}},{nameBase:"Pivot Points",pointArrayMap:"R4 R3 R2 R1 P S1 S2 S3 S4".split(" "),
pointValKey:"P",toYData:function(a){return[a.P]},translate:function(){var a=this;f.prototype.translate.apply(a);a.points.forEach(function(e){a.pointArrayMap.forEach(function(c){l(e[c])&&(e["plot"+c]=a.yAxis.toPixels(e[c],!0))})});a.plotEndPoint=a.xAxis.toPixels(a.endPoint,!0)},getGraphPath:function(a){for(var e=this,c=a.length,d=[[],[],[],[],[],[],[],[],[]],b=[],k=e.plotEndPoint,h=e.pointArrayMap.length,g,x,n;c--;){x=a[c];for(n=0;n<h;n++)g=e.pointArrayMap[n],l(x[g])&&d[n].push({plotX:x.plotX,plotY:x["plot"+
g],isNull:!1},{plotX:k,plotY:x["plot"+g],isNull:!1},{plotX:k,plotY:null,isNull:!0});k=x.plotX}d.forEach(function(a){b=b.concat(f.prototype.getGraphPath.call(e,a))});return b},drawDataLabels:function(){var a=this,e=a.pointArrayMap,c,d,b;if(a.options.dataLabels.enabled){var k=a.points.length;e.concat([!1]).forEach(function(l,g){for(b=k;b--;)d=a.points[b],l?(d.y=d[l],d.pivotLine=l,d.plotY=d["plot"+l],c=d["dataLabel"+l],g&&(d["dataLabel"+e[g-1]]=d.dataLabel),d.dataLabels||(d.dataLabels=[]),d.dataLabels[0]=
d.dataLabel=c=c&&c.element?c:null):d["dataLabel"+e[g-1]]=d.dataLabel;f.prototype.drawDataLabels.apply(a,arguments)})}},getValues:function(a,e){var c=e.period,d=a.xData,b=(a=a.yData)?a.length:0;e=this[e.algorithm+"Placement"];var f=[],l=[],g=[],h;if(!(d.length<c)&&k(a[0])&&4===a[0].length){for(h=c+1;h<=b+c;h+=c){var n=d.slice(h-c-1,h);var m=a.slice(h-c-1,h);var v=n.length;var B=n[v-1];m=this.getPivotAndHLC(m);m=e(m);m=f.push([B].concat(m));l.push(B);g.push(f[m-1].slice(1))}this.endPoint=n[0]+(B-n[0])/
v*c;return{values:f,xData:l,yData:g}}},getPivotAndHLC:function(a){var e=-Infinity,c=Infinity,d=a[a.length-1][3];a.forEach(function(a){e=Math.max(e,a[1]);c=Math.min(c,a[2])});return[(e+c+d)/3,e,c,d]},standardPlacement:function(a){var e=a[1]-a[2];return[null,null,a[0]+e,2*a[0]-a[2],a[0],2*a[0]-a[1],a[0]-e,null,null]},camarillaPlacement:function(a){var e=a[1]-a[2];return[a[3]+1.5*e,a[3]+1.25*e,a[3]+1.1666*e,a[3]+1.0833*e,a[0],a[3]-1.0833*e,a[3]-1.1666*e,a[3]-1.25*e,a[3]-1.5*e]},fibonacciPlacement:function(a){var e=
a[1]-a[2];return[null,a[0]+e,a[0]+.618*e,a[0]+.382*e,a[0],a[0]-.382*e,a[0]-.618*e,a[0]-e,null]}},{destroyElements:function(){h(this,"destroyElements")},destroy:function(){h(this,"destroyElements")}});""});w(b,"Stock/Indicators/PPOIndicator.js",[b["Core/Globals.js"],b["Mixins/IndicatorRequired.js"],b["Core/Utilities.js"]],function(b,g,h){var l=h.correctFloat,k=h.error,f=b.seriesTypes.ema;b.seriesType("ppo","ema",{params:{periods:[12,26]}},{nameBase:"PPO",nameComponents:["periods"],init:function(){var a=
arguments,e=this;g.isParentLoaded(f,"ema",e.type,function(c){c.prototype.init.apply(e,a)})},getValues:function(a,e){var c=e.periods,d=e.index;e=[];var b=[],g=[],h;if(2!==c.length||c[1]<=c[0])k('Error: "PPO requires two periods. Notice, first period should be lower than the second one."');else{var r=f.prototype.getValues.call(this,a,{index:d,period:c[0]});a=f.prototype.getValues.call(this,a,{index:d,period:c[1]});if(r&&a){c=c[1]-c[0];for(h=0;h<a.yData.length;h++)d=l((r.yData[h+c]-a.yData[h])/a.yData[h]*
100),e.push([a.xData[h],d]),b.push(a.xData[h]),g.push(d);return{values:e,xData:b,yData:g}}}}});""});w(b,"Mixins/ReduceArray.js",[],function(){return{minInArray:function(b,g){return b.reduce(function(b,l){return Math.min(b,l[g])},Number.MAX_VALUE)},maxInArray:function(b,g){return b.reduce(function(b,l){return Math.max(b,l[g])},-Number.MAX_VALUE)},getArrayExtremes:function(b,g,h){return b.reduce(function(b,k){return[Math.min(b[0],k[g]),Math.max(b[1],k[h])]},[Number.MAX_VALUE,-Number.MAX_VALUE])}}});
w(b,"Stock/Indicators/PCIndicator.js",[b["Core/Series/Series.js"],b["Core/Color/Palette.js"],b["Mixins/MultipleLines.js"],b["Mixins/ReduceArray.js"],b["Core/Utilities.js"]],function(b,g,h,l,k){k=k.merge;var f=l.getArrayExtremes;b.seriesType("pc","sma",{params:{period:20},lineWidth:1,topLine:{styles:{lineColor:g.colors[2],lineWidth:1}},bottomLine:{styles:{lineColor:g.colors[8],lineWidth:1}},dataGrouping:{approximation:"averages"}},k(h,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Price Channel",
nameComponents:["period"],linesApiNames:["topLine","bottomLine"],getValues:function(a,b){b=b.period;var c=a.xData,d=(a=a.yData)?a.length:0,e=[],h=[],g=[],l;if(!(d<b)){for(l=b;l<=d;l++){var k=c[l-1];var n=a.slice(l-b,l);var m=f(n,2,1);n=m[1];var v=m[0];m=(n+v)/2;e.push([k,n,m,v]);h.push(k);g.push([n,m,v])}return{values:e,xData:h,yData:g}}}}));""});w(b,"Stock/Indicators/PriceEnvelopesIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){var h=g.isArray,l=g.merge,k=b.seriesTypes.sma;
b.seriesType("priceenvelopes","sma",{marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Top: {point.top}<br/>Middle: {point.middle}<br/>Bottom: {point.bottom}<br/>'},params:{period:20,topBand:.1,bottomBand:.1},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1}},dataGrouping:{approximation:"averages"}},{nameComponents:["period","topBand","bottomBand"],nameBase:"Price envelopes",pointArrayMap:["top","middle",
"bottom"],parallelArrays:["x","y","top","bottom"],pointValKey:"middle",init:function(){k.prototype.init.apply(this,arguments);this.options=l({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)},toYData:function(b){return[b.top,b.middle,b.bottom]},translate:function(){var b=this,a=["plotTop","plotMiddle","plotBottom"];k.prototype.translate.apply(b);b.points.forEach(function(e){[e.top,e.middle,e.bottom].forEach(function(c,d){null!==c&&(e[a[d]]=b.yAxis.toPixels(c,
!0))})})},drawGraph:function(){for(var b=this,a=b.points,e=a.length,c=b.options,d=b.graph,h={options:{gapSize:c.gapSize}},g=[[],[]],q;e--;)q=a[e],g[0].push({plotX:q.plotX,plotY:q.plotTop,isNull:q.isNull}),g[1].push({plotX:q.plotX,plotY:q.plotBottom,isNull:q.isNull});["topLine","bottomLine"].forEach(function(a,d){b.points=g[d];b.options=l(c[a].styles,h);b.graph=b["graph"+a];k.prototype.drawGraph.call(b);b["graph"+a]=b.graph});b.points=a;b.options=c;b.graph=d;k.prototype.drawGraph.call(b)},getValues:function(b,
a){var e=a.period,c=a.topBand,d=a.bottomBand,f=b.xData,g=(b=b.yData)?b.length:0,l=[],r=[],x=[],n;if(!(f.length<e)&&h(b[0])&&4===b[0].length){for(n=e;n<=g;n++){var m=f.slice(n-e,n);var v=b.slice(n-e,n);v=k.prototype.getValues.call(this,{xData:m,yData:v},a);m=v.xData[0];v=v.yData[0];var B=v*(1+c);var y=v*(1-d);l.push([m,B,v,y]);r.push(m);x.push([B,v,y])}return{values:l,xData:r,yData:x}}}});""});w(b,"Stock/Indicators/PSARIndicator.js",[b["Core/Series/Series.js"]],function(b){b.seriesType("psar","sma",
{lineWidth:0,marker:{enabled:!0},states:{hover:{lineWidthPlus:0}},params:{initialAccelerationFactor:.02,maxAccelerationFactor:.2,increment:.02,index:2,decimals:4}},{nameComponents:!1,getValues:function(b,h){var l=b.xData;b=b.yData;var k=b[0][1],f=h.maxAccelerationFactor,a=h.increment,e=h.initialAccelerationFactor,c=b[0][2],d=h.decimals,g=h.index,u=[],q=[],r=[],x=1,n;if(!(g>=b.length)){for(n=0;n<g;n++)k=Math.max(b[n][1],k),c=Math.min(b[n][2],parseFloat(c.toFixed(d)));var m=b[n][1]>c?1:-1;h=h.initialAccelerationFactor;
var v=h*(k-c);u.push([l[g],c]);q.push(l[g]);r.push(parseFloat(c.toFixed(d)));for(n=g+1;n<b.length;n++){g=b[n-1][2];var B=b[n-2][2];var y=b[n-1][1];var A=b[n-2][1];var z=b[n][1];var t=b[n][2];null!==B&&null!==A&&null!==g&&null!==y&&null!==z&&null!==t&&(c=m===x?1===m?c+v<Math.min(B,g)?c+v:Math.min(B,g):c+v>Math.max(A,y)?c+v:Math.max(A,y):k,g=1===m?z>k?z:k:t<k?t:k,z=1===x&&t>c||-1===x&&z>c?1:-1,x=z,v=g,t=a,B=f,y=e,h=x===m?1===x&&v>k?h===B?B:parseFloat((h+t).toFixed(2)):-1===x&&v<k?h===B?B:parseFloat((h+
t).toFixed(2)):h:y,k=g-c,v=h*k,u.push([l[n],parseFloat(c.toFixed(d))]),q.push(l[n]),r.push(parseFloat(c.toFixed(d))),x=m,m=z,k=g)}return{values:u,xData:q,yData:r}}}});""});w(b,"Stock/Indicators/ROCIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){var h=g.isArray;b.seriesType("roc","sma",{params:{index:3,period:9}},{nameBase:"Rate of Change",getValues:function(b,g){var f=g.period,a=b.xData,e=(b=b.yData)?b.length:0,c=[],d=[],l=[],k=-1;if(!(a.length<=f)){h(b[0])&&(k=g.index);
for(g=f;g<e;g++){var q=0>k?(q=b[g-f])?(b[g]-q)/q*100:null:(q=b[g-f][k])?(b[g][k]-q)/q*100:null;q=[a[g],q];c.push(q);d.push(q[0]);l.push(q[1])}return{values:c,xData:d,yData:l}}}});""});w(b,"Stock/Indicators/RSIIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){var h=g.isArray;b.seriesType("rsi","sma",{params:{period:14,decimals:4}},{getValues:function(b,g){var f=g.period,a=b.xData,e=(b=b.yData)?b.length:0;g=g.decimals;var c=1,d=[],l=[],k=[],q=0,r=0,x;if(!(a.length<f)&&
h(b[0])&&4===b[0].length){for(;c<f;){var n=parseFloat((b[c][3]-b[c-1][3]).toFixed(g));0<n?q+=n:r+=Math.abs(n);c++}var m=parseFloat((q/(f-1)).toFixed(g));for(x=parseFloat((r/(f-1)).toFixed(g));c<e;c++)n=parseFloat((b[c][3]-b[c-1][3]).toFixed(g)),0<n?(q=n,r=0):(q=0,r=Math.abs(n)),m=parseFloat(((m*(f-1)+q)/f).toFixed(g)),x=parseFloat(((x*(f-1)+r)/f).toFixed(g)),q=0===x?100:0===m?0:parseFloat((100-100/(1+m/x)).toFixed(g)),d.push([a[c],q]),l.push(a[c]),k.push(q);return{values:d,xData:l,yData:k}}}});""});
w(b,"Stock/Indicators/StochasticIndicator.js",[b["Core/Series/Series.js"],b["Mixins/MultipleLines.js"],b["Mixins/ReduceArray.js"],b["Core/Utilities.js"]],function(b,g,h,l){var k=l.isArray,f=l.merge,a=b.seriesTypes.sma,e=h.getArrayExtremes;b.seriesType("stochastic","sma",{params:{periods:[14,3]},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>%K: {point.y}<br/>%D: {point.smoothed}<br/>'},smoothedLine:{styles:{lineWidth:1,lineColor:void 0}},
dataGrouping:{approximation:"averages"}},f(g,{nameComponents:["periods"],nameBase:"Stochastic",pointArrayMap:["y","smoothed"],parallelArrays:["x","y","smoothed"],pointValKey:"y",linesApiNames:["smoothedLine"],init:function(){a.prototype.init.apply(this,arguments);this.options=f({smoothedLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(b,d){var c=d.periods[0];d=d.periods[1];var f=b.xData,g=(b=b.yData)?b.length:0,h=[],l=[],n=[],m=null,v;if(!(g<c)&&k(b[0])&&4===b[0].length){for(v=
c-1;v<g;v++){var B=b.slice(v-c+1,v+1);var y=e(B,2,1);var A=y[0];B=b[v][3]-A;A=y[1]-A;B=B/A*100;l.push(f[v]);n.push([B,null]);v>=c-1+(d-1)&&(m=a.prototype.getValues.call(this,{xData:l.slice(-d),yData:n.slice(-d)},{period:d}),m=m.yData[0]);h.push([f[v],B,m]);n[n.length-1][1]=m}return{values:h,xData:l,yData:n}}}}));""});w(b,"Stock/Indicators/SlowStochasticIndicator.js",[b["Core/Series/Series.js"],b["Mixins/IndicatorRequired.js"]],function(b,g){var h=b.seriesTypes;b.seriesType("slowstochastic","stochastic",
{params:{periods:[14,3,3]}},{nameBase:"Slow Stochastic",init:function(){var b=arguments,k=this;g.isParentLoaded(h.stochastic,"stochastic",k.type,function(f){f.prototype.init.apply(k,b)})},getValues:function(b,g){var f=g.periods,a=h.stochastic.prototype.getValues.call(this,b,g);b={values:[],xData:[],yData:[]};g=0;if(a){b.xData=a.xData.slice(f[1]-1);a=a.yData.slice(f[1]-1);var e=h.sma.prototype.getValues.call(this,{xData:b.xData,yData:a},{index:1,period:f[2]});if(e){for(var c=b.xData.length;g<c;g++)b.yData[g]=
[a[g][1],e.yData[g-f[2]+1]||null],b.values[g]=[b.xData[g],a[g][1],e.yData[g-f[2]+1]||null];return b}}}});""});w(b,"Stock/Indicators/SupertrendIndicator.js",[b["Core/Series/Series.js"],b["Core/Color/Palette.js"],b["Core/Utilities.js"]],function(b,g,h){function l(a,b,c){return{index:b,close:a.yData[b][c],x:a.xData[b]}}var k=b.seriesTypes,f=h.correctFloat,a=h.isArray,e=h.merge,c=h.objectEach,d=k.atr,p=k.sma;b.seriesType("supertrend","sma",{params:{multiplier:3,period:10},risingTrendColor:g.indicatorPositiveLine,
fallingTrendColor:g.indicatorNegativeLine,changeTrendLine:{styles:{lineWidth:1,lineColor:g.neutralColor80,dashStyle:"LongDash"}}},{nameBase:"Supertrend",nameComponents:["multiplier","period"],requiredIndicators:["atr"],init:function(){p.prototype.init.apply(this,arguments);var a=this.options;a.cropThreshold=this.linkedParent.options.cropThreshold-(a.params.period-1)},drawGraph:function(){var a=this,b=a.options,d=a.linkedParent,f=d?d.points:[],g=a.points,h=a.graph,k=g.length,B=f.length-k;B=0<B?B:0;
for(var y={options:{gapSize:b.gapSize}},A={top:[],bottom:[],intersect:[]},z={top:{styles:{lineWidth:b.lineWidth,lineColor:b.fallingTrendColor||b.color,dashStyle:b.dashStyle}},bottom:{styles:{lineWidth:b.lineWidth,lineColor:b.risingTrendColor||b.color,dashStyle:b.dashStyle}},intersect:b.changeTrendLine},t,J,D,E,w,C,H,G;k--;)t=g[k],J=g[k-1],D=f[k-1+B],E=f[k-2+B],w=f[k+B],C=f[k+B+1],H=t.options.color,G={x:t.x,plotX:t.plotX,plotY:t.plotY,isNull:!1},!E&&D&&d.yData[D.index-1]&&(E=l(d,D.index-1,3)),!C&&
w&&d.yData[w.index+1]&&(C=l(d,w.index+1,3)),!D&&E&&d.yData[E.index+1]?D=l(d,E.index+1,3):!D&&w&&d.yData[w.index-1]&&(D=l(d,w.index-1,3)),t&&D&&w&&E&&t.x!==D.x&&(t.x===w.x?(E=D,D=w):t.x===E.x?(D=E,E={close:d.yData[D.index-1][3],x:d.xData[D.index-1]}):C&&t.x===C.x&&(D=C,E=w)),J&&E&&D?(w={x:J.x,plotX:J.plotX,plotY:J.plotY,isNull:!1},t.y>=D.close&&J.y>=E.close?(t.color=H||b.fallingTrendColor||b.color,A.top.push(G)):t.y<D.close&&J.y<E.close?(t.color=H||b.risingTrendColor||b.color,A.bottom.push(G)):(A.intersect.push(G),
A.intersect.push(w),A.intersect.push(e(w,{isNull:!0})),t.y>=D.close&&J.y<E.close?(t.color=H||b.fallingTrendColor||b.color,J.color=H||b.risingTrendColor||b.color,A.top.push(G),A.top.push(e(w,{isNull:!0}))):t.y<D.close&&J.y>=E.close&&(t.color=H||b.risingTrendColor||b.color,J.color=H||b.fallingTrendColor||b.color,A.bottom.push(G),A.bottom.push(e(w,{isNull:!0}))))):D&&(t.y>=D.close?(t.color=H||b.fallingTrendColor||b.color,A.top.push(G)):(t.color=H||b.risingTrendColor||b.color,A.bottom.push(G)));c(A,function(b,
c){a.points=b;a.options=e(z[c].styles,y);a.graph=a["graph"+c+"Line"];p.prototype.drawGraph.call(a);a["graph"+c+"Line"]=a.graph});a.points=g;a.options=b;a.graph=h},getValues:function(b,c){var e=c.period;c=c.multiplier;var g=b.xData,h=b.yData,l=[],k=[],p=[],q=0===e?0:e-1,u=[],z=[],t;if(!(g.length<=e||!a(h[0])||4!==h[0].length||0>e)){b=d.prototype.getValues.call(this,b,{period:e}).yData;for(t=0;t<b.length;t++){var y=h[q+t];var D=h[q+t-1]||[];var w=u[t-1];var K=z[t-1];var C=p[t-1];0===t&&(w=K=C=0);e=
f((y[1]+y[2])/2+c*b[t]);var H=f((y[1]+y[2])/2-c*b[t]);u[t]=e<w||D[3]>w?e:w;z[t]=H>K||D[3]<K?H:K;if(C===w&&y[3]<u[t]||C===K&&y[3]<z[t])var G=u[t];else if(C===w&&y[3]>u[t]||C===K&&y[3]>z[t])G=z[t];l.push([g[q+t],G]);k.push(g[q+t]);p.push(G)}return{values:l,xData:k,yData:p}}}});""});w(b,"Stock/Indicators/VBPIndicator.js",[b["Core/Animation/AnimationUtilities.js"],b["Core/Series/Series.js"],b["Core/Globals.js"],b["Core/Series/Point.js"],b["Core/Utilities.js"]],function(b,g,h,l,k){var f=b.animObject;b=
h.noop;var a=k.addEvent,e=k.arrayMax,c=k.arrayMin,d=k.correctFloat,p=k.error,u=k.extend,q=k.isArray,r=Math.abs,x=g.seriesTypes.column.prototype;g.seriesType("vbp","sma",{params:{ranges:12,volumeSeriesID:"volume"},zoneLines:{enabled:!0,styles:{color:"#0A9AC9",dashStyle:"LongDash",lineWidth:1}},volumeDivision:{enabled:!0,styles:{positiveColor:"rgba(144, 237, 125, 0.8)",negativeColor:"rgba(244, 91, 91, 0.8)"}},animationLimit:1E3,enableMouseTracking:!1,pointPadding:0,zIndex:-1,crisp:!0,dataGrouping:{enabled:!1},
dataLabels:{allowOverlap:!0,enabled:!0,format:"P: {point.volumePos:.2f} | N: {point.volumeNeg:.2f}",padding:0,style:{fontSize:"7px"},verticalAlign:"top"}},{nameBase:"Volume by Price",bindTo:{series:!1,eventName:"afterSetExtremes"},calculateOn:"render",markerAttribs:b,drawGraph:b,getColumnMetrics:x.getColumnMetrics,crispCol:x.crispCol,init:function(a){h.seriesTypes.sma.prototype.init.apply(this,arguments);var b=this.options.params;var c=this.linkedParent;b=a.get(b.volumeSeriesID);this.addCustomEvents(c,
b);return this},addCustomEvents:function(b,c){function d(){e.chart.redraw();e.setData([]);e.zoneStarts=[];e.zoneLinesSVG&&(e.zoneLinesSVG.destroy(),delete e.zoneLinesSVG)}var e=this;e.dataEventsToUnbind.push(a(b,"remove",function(){d()}));c&&e.dataEventsToUnbind.push(a(c,"remove",function(){d()}));return e},animate:function(a){var b=this,c=b.chart.inverted,d=b.group,e={};!a&&d&&(a=c?"translateY":"translateX",c=c?b.yAxis.top:b.xAxis.left,d["forceAnimate:"+a]=!0,e[a]=c,d.animate(e,u(f(b.options.animation),
{step:function(a,c){b.group.attr({scaleX:Math.max(.001,c.pos)})}})))},drawPoints:function(){this.options.volumeDivision.enabled&&(this.posNegVolume(!0,!0),x.drawPoints.apply(this,arguments),this.posNegVolume(!1,!1));x.drawPoints.apply(this,arguments)},posNegVolume:function(a,b){var c=b?["positive","negative"]:["negative","positive"],d=this.options.volumeDivision,e=this.points.length,f=[],g=[],h=0,l;a?(this.posWidths=f,this.negWidths=g):(f=this.posWidths,g=this.negWidths);for(;h<e;h++){var k=this.points[h];
k[c[0]+"Graphic"]=k.graphic;k.graphic=k[c[1]+"Graphic"];if(a){var n=k.shapeArgs.width;var m=this.priceZones[h];(l=m.wholeVolumeData)?(f.push(n/l*m.positiveVolumeData),g.push(n/l*m.negativeVolumeData)):(f.push(0),g.push(0))}k.color=b?d.styles.positiveColor:d.styles.negativeColor;k.shapeArgs.width=b?this.posWidths[h]:this.negWidths[h];k.shapeArgs.x=b?k.shapeArgs.x:this.posWidths[h]}},translate:function(){var a=this,b=a.options,c=a.chart,f=a.yAxis,g=f.min,h=a.options.zoneLines,k=a.priceZones,l=0,p,q,
u;x.translate.apply(a);var w=a.points;if(w.length){var y=.5>b.pointPadding?b.pointPadding:.1;b=a.volumeDataArray;var H=e(b);var G=c.plotWidth/2;var N=c.plotTop;var L=r(f.toPixels(g)-f.toPixels(g+a.rangeStep));var P=r(f.toPixels(g)-f.toPixels(g+a.rangeStep));y&&(g=r(L*(1-2*y)),l=r((L-g)/2),L=r(g));w.forEach(function(b,c){q=b.barX=b.plotX=0;u=b.plotY=f.toPixels(k[c].start)-N-(f.reversed?L-P:L)-l;p=d(G*k[c].wholeVolumeData/H);b.pointWidth=p;b.shapeArgs=a.crispCol.apply(a,[q,u,p,L]);b.volumeNeg=k[c].negativeVolumeData;
b.volumePos=k[c].positiveVolumeData;b.volumeAll=k[c].wholeVolumeData});h.enabled&&a.drawZones(c,f,a.zoneStarts,h.styles)}},getValues:function(a,b){var c=a.processedXData,d=a.processedYData,e=this.chart,f=b.ranges,g=[],h=[],k=[],l;if(a.chart)if(l=e.get(b.volumeSeriesID))if((b=q(d[0]))&&4!==d[0].length)p("Type of "+a.name+" series is different than line, OHLC or candlestick.",!0,e);else return(this.priceZones=this.specifyZones(b,c,d,f,l)).forEach(function(a,b){g.push([a.x,a.end]);h.push(g[b][0]);k.push(g[b][1])}),
{values:g,xData:h,yData:k};else p("Series "+b.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,e);else p("Base series not found! In case it has been removed, add a new one.",!0,e)},specifyZones:function(a,b,f,g,h){if(a){var k=f.length;for(var l=f[0][3],n=l,p=1,m;p<k;p++)m=f[p][3],m<l&&(l=m),m>n&&(n=m);k={min:l,max:n}}else k=!1;k=(l=k)?l.min:c(f);m=l?l.max:e(f);l=this.zoneStarts=[];n=[];var q=0;p=1;if(!k||!m)return this.points.length&&(this.setData([]),this.zoneStarts=[],this.zoneLinesSVG.destroy()),
[];var u=this.rangeStep=d(m-k)/g;for(l.push(k);q<g-1;q++)l.push(d(l[q]+u));l.push(m);for(g=l.length;p<g;p++)n.push({index:p-1,x:b[0],start:l[p-1],end:l[p]});return this.volumePerZone(a,n,h,b,f)},volumePerZone:function(a,b,c,d,e){var f=this,g=c.processedXData,h=c.processedYData,l=b.length-1,k=e.length;c=h.length;var p,n,m,q,u;r(k-c)&&(d[0]!==g[0]&&h.unshift(0),d[k-1]!==g[c-1]&&h.push(0));f.volumeDataArray=[];b.forEach(function(b){b.wholeVolumeData=0;b.positiveVolumeData=0;for(u=b.negativeVolumeData=
0;u<k;u++)m=n=!1,q=a?e[u][3]:e[u],p=u?a?e[u-1][3]:e[u-1]:q,q<=b.start&&0===b.index&&(n=!0),q>=b.end&&b.index===l&&(m=!0),(q>b.start||n)&&(q<b.end||m)&&(b.wholeVolumeData+=h[u],p>q?b.negativeVolumeData+=h[u]:b.positiveVolumeData+=h[u]);f.volumeDataArray.push(b.wholeVolumeData)});return b},drawZones:function(a,b,c,d){var e=a.renderer,f=this.zoneLinesSVG,g=[],h=a.plotWidth,k=a.plotTop,l;c.forEach(function(c){l=b.toPixels(c)-k;g=g.concat(a.renderer.crispLine([["M",0,l],["L",h,l]],d.lineWidth))});f?f.animate({d:g}):
f=this.zoneLinesSVG=e.path(g).attr({"stroke-width":d.lineWidth,stroke:d.color,dashstyle:d.dashStyle,zIndex:this.group.zIndex+.1}).add(this.group)}},{destroy:function(){this.negativeGraphic&&(this.negativeGraphic=this.negativeGraphic.destroy());return l.prototype.destroy.apply(this,arguments)}});""});w(b,"Stock/Indicators/VWAPIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){var h=g.error,l=g.isArray;b.seriesType("vwap","sma",{params:{period:30,volumeSeriesID:"volume"}},
{getValues:function(b,f){var a=b.chart,e=b.xData;b=b.yData;var c=f.period,d=!0,g;if(g=a.get(f.volumeSeriesID))return l(b[0])||(d=!1),this.calculateVWAPValues(d,e,b,g,c);h("Series "+f.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,a)},calculateVWAPValues:function(b,f,a,e,c){var d=e.yData,g=e.xData.length,h=f.length;e=[];var l=[],k=[],x=[],n=[],m;g=h<=g?h:g;for(m=h=0;h<g;h++){var v=b?(a[h][1]+a[h][2]+a[h][3])/3:a[h];v*=d[h];v=m?e[h-1]+v:v;var w=m?l[h-1]+d[h]:d[h];e.push(v);l.push(w);n.push([f[h],
v/w]);k.push(n[h][0]);x.push(n[h][1]);m++;m===c&&(m=0)}return{values:n,xData:k,yData:x}}});""});w(b,"Stock/Indicators/WilliamsRIndicator.js",[b["Core/Series/Series.js"],b["Mixins/ReduceArray.js"],b["Core/Utilities.js"]],function(b,g,h){var l=g.getArrayExtremes,k=h.isArray;b.seriesType("williamsr","sma",{params:{period:14}},{nameBase:"Williams %R",getValues:function(b,a){a=a.period;var e=b.xData,c=(b=b.yData)?b.length:0,d=[],f=[],g=[],h;if(!(e.length<a)&&k(b[0])&&4===b[0].length){for(h=a-1;h<c;h++){var r=
b.slice(h-a+1,h+1);var x=l(r,2,1);r=x[0];x=x[1];var n=b[h][3];r=(x-n)/(x-r)*-100;e[h]&&(d.push([e[h],r]),f.push(e[h]),g.push(r))}return{values:d,xData:f,yData:g}}}});""});w(b,"Stock/Indicators/WMAIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){function h(b,a){a*=(a+1)/2;return b.reduce(function(a,b,d){return[null,a[1]+b[1]*(d+1)]})[1]/a}function l(b,a,e,c){e=h(b,b.length);a=a[c-1];b.shift();return[a,e]}var k=g.isArray;b.seriesType("wma","sma",{params:{index:3,period:9}},
{getValues:function(b,a){var e=a.period,c=b.xData,d=(b=b.yData)?b.length:0,f=1,g=c[0],h=b[0],r=[],x=[],n=[],m=-1;if(!(c.length<e)){k(b[0])&&(m=a.index,h=b[0][m]);for(a=[[g,h]];f!==e;)a.push([c[f],0>m?b[f]:b[f][m]]),f++;for(e=f;e<d;e++)f=l(a,c,b,e),r.push(f),x.push(f[0]),n.push(f[1]),a.push([c[e],0>m?b[e]:b[e][m]]);f=l(a,c,b,e);r.push(f);x.push(f[0]);n.push(f[1]);return{values:r,xData:x,yData:n}}}});""});w(b,"Stock/Indicators/ZigzagIndicator.js",[b["Core/Series/Series.js"]],function(b){b.seriesType("zigzag",
"sma",{params:{lowIndex:2,highIndex:1,deviation:1}},{nameComponents:["deviation"],nameSuffixes:["%"],nameBase:"Zig Zag",getValues:function(b,h){var g=h.lowIndex,k=h.highIndex,f=h.deviation/100;h=1+f;var a=1-f;f=b.xData;var e=b.yData;b=e?e.length:0;var c=[],d=[],p=[],u,q,r=!1,x=!1;if(!(!f||1>=f.length||b&&("undefined"===typeof e[0][g]||"undefined"===typeof e[0][k]))){var n=e[0][g];var m=e[0][k];for(u=1;u<b;u++){if(e[u][g]<=m*a){c.push([f[0],m]);var v=[f[u],e[u][g]];r=q=!0}else e[u][k]>=n*h&&(c.push([f[0],
n]),v=[f[u],e[u][k]],q=!1,r=!0);if(r){d.push(c[0][0]);p.push(c[0][1]);var w=u++;u=b}}for(u=w;u<b;u++)q?(e[u][g]<=v[1]&&(v=[f[u],e[u][g]]),e[u][k]>=v[1]*h&&(x=k)):(e[u][k]>=v[1]&&(v=[f[u],e[u][k]]),e[u][g]<=v[1]*a&&(x=g)),!1!==x&&(c.push(v),d.push(v[0]),p.push(v[1]),v=[f[u],e[u][x]],q=!q,x=!1);g=c.length;0!==g&&c[g-1][0]<f[b-1]&&(c.push(v),d.push(v[0]),p.push(v[1]));return{values:c,xData:d,yData:p}}}});""});w(b,"Stock/Indicators/RegressionIndicators.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],
function(b,g){var h=g.isArray;b.seriesType("linearRegression","sma",{params:{xAxisUnit:void 0},tooltip:{valueDecimals:4}},{nameBase:"Linear Regression Indicator",getRegressionLineParameters:function(b,g){var f=this.options.params.index,a=function(a,b){return h(a)?a[b]:a},e=b.reduce(function(a,b){return b+a},0),c=g.reduce(function(b,c){return a(c,f)+b},0);e/=b.length;c/=g.length;var d=0,k=0,l;for(l=0;l<b.length;l++){var q=b[l]-e;var r=a(g[l],f)-c;d+=q*r;k+=Math.pow(q,2)}b=k?d/k:0;return{slope:b,intercept:c-
b*e}},getEndPointY:function(b,g){return b.slope*g+b.intercept},transformXData:function(b,g){var f=b[0];return b.map(function(a){return(a-f)/g})},findClosestDistance:function(b){var g,f;for(f=1;f<b.length-1;f++){var a=b[f]-b[f-1];0<a&&("undefined"===typeof g||a<g)&&(g=a)}return g},getValues:function(b,g){var f=b.xData;b=b.yData;g=g.period;var a,e={xData:[],yData:[],values:[]},c=this.options.params.xAxisUnit||this.findClosestDistance(f);for(a=g-1;a<=f.length-1;a++){var d=a-g+1;var h=a+1;var k=f[a];
var l=f.slice(d,h);d=b.slice(d,h);h=this.transformXData(l,c);l=this.getRegressionLineParameters(h,d);d=this.getEndPointY(l,h[h.length-1]);e.values.push({regressionLineParameters:l,x:k,y:d});e.xData.push(k);e.yData.push(d)}return e}});b.seriesType("linearRegressionSlope","linearRegression",{},{nameBase:"Linear Regression Slope Indicator",getEndPointY:function(b){return b.slope}});b.seriesType("linearRegressionIntercept","linearRegression",{},{nameBase:"Linear Regression Intercept Indicator",getEndPointY:function(b){return b.intercept}});
b.seriesType("linearRegressionAngle","linearRegression",{tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span>{series.name}: <b>{point.y}\u00b0</b><br/>'}},{nameBase:"Linear Regression Angle Indicator",slopeToAngle:function(b){return 180/Math.PI*Math.atan(b)},getEndPointY:function(b){return this.slopeToAngle(b.slope)}});""});w(b,"Stock/Indicators/ABands/ABandsIndicator.js",[b["Core/Series/Series.js"],b["Mixins/MultipleLines.js"],b["Core/Utilities.js"]],function(b,g,h){var l=this&&
this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),k=b.seriesTypes.sma,f=h.correctFloat,a=h.extend,e=h.merge;h=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=
void 0;b.points=void 0;return b}l(b,a);b.prototype.getValues=function(b,c){var d=c.period,e=c.factor;c=c.index;var g=b.xData,h=(b=b.yData)?b.length:0,k=[],l=[],p=[],u=[],w=[],z;if(!(h<d)){for(z=0;z<=h;z++){if(z<h){var t=b[z][2];var y=b[z][1];var D=e;t=f(y-t)/(f(y+t)/2)*1E3*D;k.push(b[z][1]*f(1+2*t));l.push(b[z][2]*f(1-2*t))}if(z>=d){t=g.slice(z-d,z);var E=b.slice(z-d,z);D=a.prototype.getValues.call(this,{xData:t,yData:k.slice(z-d,z)},{period:d});y=a.prototype.getValues.call(this,{xData:t,yData:l.slice(z-
d,z)},{period:d});E=a.prototype.getValues.call(this,{xData:t,yData:E},{period:d,index:c});t=E.xData[0];D=D.yData[0];y=y.yData[0];E=E.yData[0];p.push([t,D,E,y]);u.push(t);w.push([D,E,y])}}return{values:p,xData:u,yData:w}}};b.defaultOptions=e(k.defaultOptions,{params:{period:20,factor:.001,index:3},lineWidth:1,topLine:{styles:{lineWidth:1}},bottomLine:{styles:{lineWidth:1}},dataGrouping:{approximation:"averages"}});return b}(k);a(h.prototype,{drawGraph:g.drawGraph,getTranslatedLinesNames:g.getTranslatedLinesNames,
linesApiNames:["topLine","bottomLine"],nameBase:"Acceleration Bands",nameComponents:["period","factor"],pointArrayMap:["top","middle","bottom"],pointValKey:"middle",toYData:g.toYData,translate:g.translate});b.registerSeriesType("abands",h);"";return h});w(b,"Stock/Indicators/TrendLineIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){var h=g.isArray;b.seriesType("trendline","sma",{params:{index:3}},{nameBase:"Trendline",nameComponents:!1,getValues:function(b,g){var f=
b.xData,a=b.yData;b=[];var e=[],c=[],d=0,k=0,l=0,q=0,r=f.length,w=g.index;for(g=0;g<r;g++){var n=f[g];var m=h(a[g])?a[g][w]:a[g];d+=n;k+=m;l+=n*m;q+=n*n}a=(r*l-d*k)/(r*q-d*d);isNaN(a)&&(a=0);d=(k-a*d)/r;for(g=0;g<r;g++)n=f[g],m=a*n+d,b[g]=[n,m],e[g]=n,c[g]=m;return{xData:e,yData:c,values:b}}});""});w(b,"masters/indicators/indicators-all.src.js",[],function(){})});
//# sourceMappingURL=indicators-all.js.map