/*
 Highstock JS v8.2.2 (2020-11-23)

 Indicator series type for Highstock

 (c) 2010-2019 Sebastian Bochan

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/indicators/macd",["highcharts","highcharts/modules/stock"],function(d){b(d);b.Highcharts=d;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function d(b,e,d,m){b.hasOwnProperty(e)||(b[e]=m.apply(null,d))}b=b?b._modules:{};d(b,"Stock/Indicators/MACDIndicator.js",[b["Core/Series/Series.js"],b["Core/Globals.js"],b["Core/Utilities.js"]],
function(b,e,d){var m=b.seriesTypes,q=d.correctFloat,k=d.defined,r=d.merge,l=m.sma,n=m.ema;b.seriesType("macd","sma",{params:{shortPeriod:12,longPeriod:26,signalPeriod:9,period:26},signalLine:{zones:[],styles:{lineWidth:1,lineColor:void 0}},macdLine:{zones:[],styles:{lineWidth:1,lineColor:void 0}},threshold:0,groupPadding:.1,pointPadding:.1,crisp:!1,states:{hover:{halo:{size:0}}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Value: {point.MACD}<br/>Signal: {point.signal}<br/>Histogram: {point.y}<br/>'},
dataGrouping:{approximation:"averages"},minPointLength:0},{nameComponents:["longPeriod","shortPeriod","signalPeriod"],requiredIndicators:["ema"],pointArrayMap:["y","signal","MACD"],parallelArrays:["x","y","signal","MACD"],pointValKey:"y",markerAttribs:e.noop,getColumnMetrics:e.seriesTypes.column.prototype.getColumnMetrics,crispCol:e.seriesTypes.column.prototype.crispCol,init:function(){l.prototype.init.apply(this,arguments);this.options&&(this.options=r({signalLine:{styles:{lineColor:this.color}},
macdLine:{styles:{color:this.color}}},this.options),this.macdZones={zones:this.options.macdLine.zones,startIndex:0},this.signalZones={zones:this.macdZones.zones.concat(this.options.signalLine.zones),startIndex:this.macdZones.zones.length},this.resetZones=!0)},toYData:function(a){return[a.y,a.signal,a.MACD]},translate:function(){var a=this,p=["plotSignal","plotMACD"];e.seriesTypes.column.prototype.translate.apply(a);a.points.forEach(function(b){[b.signal,b.MACD].forEach(function(c,f){null!==c&&(b[p[f]]=
a.yAxis.toPixels(c,!0))})})},destroy:function(){this.graph=null;this.graphmacd=this.graphmacd&&this.graphmacd.destroy();this.graphsignal=this.graphsignal&&this.graphsignal.destroy();l.prototype.destroy.apply(this,arguments)},drawPoints:e.seriesTypes.column.prototype.drawPoints,drawGraph:function(){for(var a=this,b=a.points,f=b.length,c=a.options,d=a.zones,e={options:{gapSize:c.gapSize}},h=[[],[]],g;f--;)g=b[f],k(g.plotMACD)&&h[0].push({plotX:g.plotX,plotY:g.plotMACD,isNull:!k(g.plotMACD)}),k(g.plotSignal)&&
h[1].push({plotX:g.plotX,plotY:g.plotSignal,isNull:!k(g.plotMACD)});["macd","signal"].forEach(function(b,p){a.points=h[p];a.options=r(c[b+"Line"].styles,e);a.graph=a["graph"+b];a.currentLineZone=b+"Zones";a.zones=a[a.currentLineZone].zones;l.prototype.drawGraph.call(a);a["graph"+b]=a.graph});a.points=b;a.options=c;a.zones=d;a.currentLineZone=null},getZonesGraphs:function(a){var b=l.prototype.getZonesGraphs.call(this,a),f=b;this.currentLineZone&&(f=b.splice(this[this.currentLineZone].startIndex+1),
f.length?f.splice(0,0,a[0]):f=[a[0]]);return f},applyZones:function(){var a=this.zones;this.zones=this.signalZones.zones;l.prototype.applyZones.call(this);this.graphmacd&&this.options.macdLine.zones.length&&this.graphmacd.hide();this.zones=a},getValues:function(a,b){var f=0,c=[],d=[],e=[];if(!(a.xData.length<b.longPeriod+b.signalPeriod)){var h=n.prototype.getValues(a,{period:b.shortPeriod});var g=n.prototype.getValues(a,{period:b.longPeriod});h=h.values;g=g.values;for(a=1;a<=h.length;a++)k(g[a-1])&&
k(g[a-1][1])&&k(h[a+b.shortPeriod+1])&&k(h[a+b.shortPeriod+1][0])&&c.push([h[a+b.shortPeriod+1][0],0,null,h[a+b.shortPeriod+1][1]-g[a-1][1]]);for(a=0;a<c.length;a++)d.push(c[a][0]),e.push([0,null,c[a][3]]);b=n.prototype.getValues({xData:d,yData:e},{period:b.signalPeriod,index:2});b=b.values;for(a=0;a<c.length;a++)c[a][0]>=b[0][0]&&(c[a][2]=b[f][1],e[a]=[0,b[f][1],c[a][3]],null===c[a][3]?(c[a][1]=0,e[a][0]=0):(c[a][1]=q(c[a][3]-b[f][1]),e[a][0]=q(c[a][3]-b[f][1])),f++);return{values:c,xData:d,yData:e}}}});
""});d(b,"masters/indicators/macd.src.js",[],function(){})});
//# sourceMappingURL=macd.js.map