/*
 Highstock JS v8.2.2 (2020-11-23)

 Indicator series type for Highstock

 (c) 2010-2019 Daniel Studencki

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/price-channel",["highcharts","highcharts/modules/stock"],function(c){a(c);a.Highcharts=c;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function c(a,b,e,d){a.hasOwnProperty(b)||(a[b]=d.apply(null,e))}a=a?a._modules:{};c(a,"Mixins/MultipleLines.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,b){var e=
b.defined,d=b.error,k=b.merge,c=a.seriesTypes.sma;return{pointArrayMap:["top","bottom"],pointValKey:"top",linesApiNames:["bottomLine"],getTranslatedLinesNames:function(g){var a=[];(this.pointArrayMap||[]).forEach(function(b){b!==g&&a.push("plot"+b.charAt(0).toUpperCase()+b.slice(1))});return a},toYData:function(g){var a=[];(this.pointArrayMap||[]).forEach(function(b){a.push(g[b])});return a},translate:function(){var a=this,b=a.pointArrayMap,d=[],e;d=a.getTranslatedLinesNames();c.prototype.translate.apply(a,
arguments);a.points.forEach(function(g){b.forEach(function(b,c){e=g[b];null!==e&&(g[d[c]]=a.yAxis.toPixels(e,!0))})})},drawGraph:function(){var a=this,b=a.linesApiNames,h=a.points,q=h.length,m=a.options,r=a.graph,t={options:{gapSize:m.gapSize}},f=[],l;a.getTranslatedLinesNames(a.pointValKey).forEach(function(a,b){for(f[b]=[];q--;)l=h[q],f[b].push({x:l.x,plotX:l.plotX,plotY:l[a],isNull:!e(l[a])});q=h.length});b.forEach(function(b,e){f[e]?(a.points=f[e],m[b]?a.options=k(m[b].styles,t):d('Error: "There is no '+
b+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),a.graph=a["graph"+b],c.prototype.drawGraph.call(a),a["graph"+b]=a.graph):d('Error: "'+b+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});a.points=h;a.options=m;a.graph=r;c.prototype.drawGraph.call(a)}}});c(a,"Mixins/ReduceArray.js",[],function(){return{minInArray:function(a,b){return a.reduce(function(a,d){return Math.min(a,
d[b])},Number.MAX_VALUE)},maxInArray:function(a,b){return a.reduce(function(a,d){return Math.max(a,d[b])},-Number.MAX_VALUE)},getArrayExtremes:function(a,b,e){return a.reduce(function(a,c){return[Math.min(a[0],c[b]),Math.max(a[1],c[e])]},[Number.MAX_VALUE,-Number.MAX_VALUE])}}});c(a,"Stock/Indicators/PCIndicator.js",[a["Core/Series/Series.js"],a["Core/Color/Palette.js"],a["Mixins/MultipleLines.js"],a["Mixins/ReduceArray.js"],a["Core/Utilities.js"]],function(a,b,c,d,k){k=k.merge;var e=d.getArrayExtremes;
a.seriesType("pc","sma",{params:{period:20},lineWidth:1,topLine:{styles:{lineColor:b.colors[2],lineWidth:1}},bottomLine:{styles:{lineColor:b.colors[8],lineWidth:1}},dataGrouping:{approximation:"averages"}},k(c,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Price Channel",nameComponents:["period"],linesApiNames:["topLine","bottomLine"],getValues:function(a,b){b=b.period;var c=a.xData,d=(a=a.yData)?a.length:0,m=[],g=[],k=[],f;if(!(d<b)){for(f=b;f<=d;f++){var l=c[f-1];var n=
a.slice(f-b,f);var p=e(n,2,1);n=p[1];var h=p[0];p=(n+h)/2;m.push([l,n,p,h]);g.push(l);k.push([n,p,h])}return{values:m,xData:g,yData:k}}}}));""});c(a,"masters/indicators/price-channel.src.js",[],function(){})});
//# sourceMappingURL=price-channel.js.map