/*
 Highstock JS v8.2.2 (2020-11-23)

 Indicator series type for Highstock

 (c) 2010-2019 Wojciech Chmiel

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/indicators/supertrend",["highcharts","highcharts/modules/stock"],function(m){c(m);c.Highcharts=m;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function m(c,r,t,x){c.hasOwnProperty(r)||(c[r]=x.apply(null,t))}c=c?c._modules:{};m(c,"Stock/Indicators/SupertrendIndicator.js",[c["Core/Series/Series.js"],c["Core/Color/Palette.js"],
c["Core/Utilities.js"]],function(c,r,t){function x(e,b,g){return{index:b,close:e.yData[b][g],x:e.xData[b]}}var m=c.seriesTypes,A=t.correctFloat,C=t.isArray,y=t.merge,D=t.objectEach,E=m.atr,B=m.sma;c.seriesType("supertrend","sma",{params:{multiplier:3,period:10},risingTrendColor:r.indicatorPositiveLine,fallingTrendColor:r.indicatorNegativeLine,changeTrendLine:{styles:{lineWidth:1,lineColor:r.neutralColor80,dashStyle:"LongDash"}}},{nameBase:"Supertrend",nameComponents:["multiplier","period"],requiredIndicators:["atr"],
init:function(){B.prototype.init.apply(this,arguments);var e=this.options;e.cropThreshold=this.linkedParent.options.cropThreshold-(e.params.period-1)},drawGraph:function(){var e=this,b=e.options,g=e.linkedParent,c=g?g.points:[],z=e.points,m=e.graph,u=z.length,v=c.length-u;v=0<v?v:0;for(var r={options:{gapSize:b.gapSize}},l={top:[],bottom:[],intersect:[]},w={top:{styles:{lineWidth:b.lineWidth,lineColor:b.fallingTrendColor||b.color,dashStyle:b.dashStyle}},bottom:{styles:{lineWidth:b.lineWidth,lineColor:b.risingTrendColor||
b.color,dashStyle:b.dashStyle}},intersect:b.changeTrendLine},a,k,d,f,h,n,p,q;u--;)a=z[u],k=z[u-1],d=c[u-1+v],f=c[u-2+v],h=c[u+v],n=c[u+v+1],p=a.options.color,q={x:a.x,plotX:a.plotX,plotY:a.plotY,isNull:!1},!f&&d&&g.yData[d.index-1]&&(f=x(g,d.index-1,3)),!n&&h&&g.yData[h.index+1]&&(n=x(g,h.index+1,3)),!d&&f&&g.yData[f.index+1]?d=x(g,f.index+1,3):!d&&h&&g.yData[h.index-1]&&(d=x(g,h.index-1,3)),a&&d&&h&&f&&a.x!==d.x&&(a.x===h.x?(f=d,d=h):a.x===f.x?(d=f,f={close:g.yData[d.index-1][3],x:g.xData[d.index-
1]}):n&&a.x===n.x&&(d=n,f=h)),k&&f&&d?(h={x:k.x,plotX:k.plotX,plotY:k.plotY,isNull:!1},a.y>=d.close&&k.y>=f.close?(a.color=p||b.fallingTrendColor||b.color,l.top.push(q)):a.y<d.close&&k.y<f.close?(a.color=p||b.risingTrendColor||b.color,l.bottom.push(q)):(l.intersect.push(q),l.intersect.push(h),l.intersect.push(y(h,{isNull:!0})),a.y>=d.close&&k.y<f.close?(a.color=p||b.fallingTrendColor||b.color,k.color=p||b.risingTrendColor||b.color,l.top.push(q),l.top.push(y(h,{isNull:!0}))):a.y<d.close&&k.y>=f.close&&
(a.color=p||b.risingTrendColor||b.color,k.color=p||b.fallingTrendColor||b.color,l.bottom.push(q),l.bottom.push(y(h,{isNull:!0}))))):d&&(a.y>=d.close?(a.color=p||b.fallingTrendColor||b.color,l.top.push(q)):(a.color=p||b.risingTrendColor||b.color,l.bottom.push(q)));D(l,function(a,b){e.points=a;e.options=y(w[b].styles,r);e.graph=e["graph"+b+"Line"];B.prototype.drawGraph.call(e);e["graph"+b+"Line"]=e.graph});e.points=z;e.options=b;e.graph=m},getValues:function(c,b){var g=b.period;b=b.multiplier;var e=
c.xData,m=c.yData,r=[],u=[],v=[],t=0===g?0:g-1,l=[],w=[],a;if(!(e.length<=g||!C(m[0])||4!==m[0].length||0>g)){c=E.prototype.getValues.call(this,c,{period:g}).yData;for(a=0;a<c.length;a++){var k=m[t+a];var d=m[t+a-1]||[];var f=l[a-1];var h=w[a-1];var n=v[a-1];0===a&&(f=h=n=0);g=A((k[1]+k[2])/2+b*c[a]);var p=A((k[1]+k[2])/2-b*c[a]);l[a]=g<f||d[3]>f?g:f;w[a]=p>h||d[3]<h?p:h;if(n===f&&k[3]<l[a]||n===h&&k[3]<w[a])var q=l[a];else if(n===f&&k[3]>l[a]||n===h&&k[3]>w[a])q=w[a];r.push([e[t+a],q]);u.push(e[t+
a]);v.push(q)}return{values:r,xData:u,yData:v}}}});""});m(c,"masters/indicators/supertrend.src.js",[],function(){})});
//# sourceMappingURL=supertrend.js.map